"""Homepage "Card collection" carousel (owner-approved 2026-09-30) on all 24
homepages. Replaces the old static certificate sample. Cards are rendered by
the bot's own drawer (assets/cards/*.webp); the carousel logic lives in
assets/glass.js, styles in scripts/design/css/glass-art.css. Idempotent.
Honesty rules: tier = estimate (not luck), editions by number, non-transferable,
not an investment, no monetary value."""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) + os.sep
KEYS = ['wood', 'iron', 'bronze', 'silver', 'gold', 'platinum', 'emerald', 'diamond', 'whale', 'genesis', 'founder']
NAMES = ['🪵 WOOD', '⚙️ IRON', '🥉 BRONZE', '🥈 SILVER', '🥇 GOLD', '🔷 PLATINUM', '💚 EMERALD', '💎 DIAMOND', '🐋 WHALE',
         '✨ GENESIS', '🔹 FOUNDER']
RANGES = ['< $3', '$3–8', '$8–18', '$18–35', '$35–65', '$65–110', '$110–180', '$180–380', '$380+', '#1–100', '#101–1000']

# title, lead, p1, p2, p3, note, prev, next, [9 tier flavours], genesis, founder
T = {
 'en': ('GameAccountValue card collection',
        'Every paid estimate is a named card with a unique number. <b>You can’t buy the foil colour</b>: it depends only on the honest estimate of your account. Anyone can check that a card is real with its QR code.',
        '🎴 <b>9 foil tiers</b> — from wooden WOOD to black-rainbow WHALE. The tier shows the estimate, not luck: nothing is random.',
        '✨ <b>GENESIS — only #1–100, FOUNDER — #101–1000.</b> Numbers are issued in order and will never repeat.',
        '🔒 <b>The card is yours and can’t be transferred</b> — a badge and a verified result, not something to resell.',
        'The card confirms what the AI saw on the screenshots on the check date. It doesn’t confirm account ownership, isn’t an investment and has no monetary value. Samples with test data.',
        'Previous card', 'Next card',
        ['Everyone starts here — the first card in a collection.', 'Your first steps in the game are already worth something.', 'Copper foil: the account has reached the market.',
         'Silver: a solid mid-level account.', 'Gold foil: a valuable account.', 'Icy platinum: premium level.', 'Emerald hologram: an elite collection.',
         'Full rainbow hologram: a rare specimen.', 'Black-rainbow foil: a legendary account.'],
        'Gold edition frame for the first 100 cards — at any tier. Never issued again.', 'Founder frame for cards #101–1000 — at any tier. Closed forever.'),
 'ru': ('Коллекция карт GameAccountValue',
        'Каждая платная оценка — это именная карта с уникальным номером. <b>Цвет фольги не купишь</b>: он зависит только от честной оценки твоего аккаунта. Любой может проверить подлинность карты по QR-коду.',
        '🎴 <b>9 уровней фольги</b> — от деревянной WOOD до чёрно-радужной WHALE. Уровень показывает оценку, а не удачу: никаких случайных выпадений.',
        '✨ <b>GENESIS — только № 1–100, FOUNDER — № 101–1000.</b> Номера выдаются по порядку и больше никогда не повторятся.',
        '🔒 <b>Карта твоя и не передаётся</b> — это знак отличия и проверенный результат, а не товар для перепродажи.',
        'Карта подтверждает, что ИИ увидел на скриншотах в день проверки. Она не подтверждает владение аккаунтом, не является инвестицией и не имеет денежной стоимости. Образцы с тестовыми данными.',
        'Предыдущая карта', 'Следующая карта',
        ['С неё начинают все — первая карта в коллекции.', 'Первые шаги в игре уже чего-то стоят.', 'Медная фольга: аккаунт вышел на рынок.',
         'Серебро: крепкий средний аккаунт.', 'Золотая фольга: ценный аккаунт.', 'Ледяная платина: премиальный уровень.', 'Изумрудная голограмма: элитная коллекция.',
         'Полная радужная голограмма: редкий экземпляр.', 'Чёрно-радужная фольга: легендарный аккаунт.'],
        'Золотая спецрамка первых 100 карт — на любом уровне. Больше не выпустят.', 'Рамка основателя для карт № 101–1000 — на любом уровне. Тираж закрыт навсегда.'),
 'es': ('Colección de cartas GameAccountValue',
        'Cada estimación de pago es una carta con nombre y número único. <b>El color de la lámina no se compra</b>: depende solo de la estimación honesta de tu cuenta. Cualquiera puede comprobar que la carta es auténtica con su código QR.',
        '🎴 <b>9 niveles de lámina</b>: de WOOD de madera a WHALE negro arcoíris. El nivel muestra la estimación, no la suerte: nada es aleatorio.',
        '✨ <b>GENESIS: solo n.º 1–100; FOUNDER: n.º 101–1000.</b> Los números se entregan en orden y nunca se repetirán.',
        '🔒 <b>La carta es tuya y no se transfiere</b>: una insignia y un resultado verificado, no algo para revender.',
        'La carta confirma lo que la IA vio en las capturas el día de la revisión. No confirma la propiedad de la cuenta, no es una inversión y no tiene valor monetario. Muestras con datos de prueba.',
        'Carta anterior', 'Carta siguiente',
        ['Todos empiezan aquí: la primera carta de la colección.', 'Tus primeros pasos en el juego ya valen algo.', 'Lámina de cobre: la cuenta llegó al mercado.',
         'Plata: una cuenta media sólida.', 'Lámina dorada: una cuenta valiosa.', 'Platino helado: nivel premium.', 'Holograma esmeralda: una colección de élite.',
         'Holograma arcoíris completo: un ejemplar raro.', 'Lámina negra arcoíris: una cuenta legendaria.'],
        'Marco dorado especial para las primeras 100 cartas, en cualquier nivel. Nunca más se emitirá.', 'Marco de fundador para las cartas n.º 101–1000, en cualquier nivel. Cerrado para siempre.'),
 'pt': ('Coleção de cartas GameAccountValue',
        'Cada estimativa paga é uma carta nomeada com número único. <b>A cor da lâmina não se compra</b>: depende só da estimativa honesta da sua conta. Qualquer pessoa pode verificar se a carta é autêntica pelo QR code.',
        '🎴 <b>9 níveis de lâmina</b> — de WOOD de madeira a WHALE preto-arco-íris. O nível mostra a estimativa, não a sorte: nada é aleatório.',
        '✨ <b>GENESIS — só nº 1–100, FOUNDER — nº 101–1000.</b> Os números saem em ordem e nunca se repetirão.',
        '🔒 <b>A carta é sua e não pode ser transferida</b> — um distintivo e um resultado verificado, não algo para revender.',
        'A carta confirma o que a IA viu nas capturas na data da verificação. Não confirma a posse da conta, não é investimento e não tem valor monetário. Amostras com dados de teste.',
        'Carta anterior', 'Próxima carta',
        ['Todo mundo começa aqui — a primeira carta da coleção.', 'Seus primeiros passos no jogo já valem algo.', 'Lâmina de cobre: a conta chegou ao mercado.',
         'Prata: uma conta intermediária sólida.', 'Lâmina dourada: uma conta valiosa.', 'Platina gelada: nível premium.', 'Holograma esmeralda: uma coleção de elite.',
         'Holograma arco-íris completo: um exemplar raro.', 'Lâmina preto-arco-íris: uma conta lendária.'],
        'Moldura dourada especial das primeiras 100 cartas — em qualquer nível. Nunca mais será emitida.', 'Moldura de fundador para as cartas nº 101–1000 — em qualquer nível. Fechada para sempre.'),
 'id': ('Koleksi kartu GameAccountValue',
        'Setiap estimasi berbayar adalah kartu bernama dengan nomor unik. <b>Warna foil tidak bisa dibeli</b>: hanya tergantung estimasi jujur akunmu. Siapa pun bisa mengecek keaslian kartu lewat kode QR.',
        '🎴 <b>9 tingkat foil</b> — dari WOOD kayu sampai WHALE hitam-pelangi. Tingkat menunjukkan estimasi, bukan keberuntungan: tidak ada yang acak.',
        '✨ <b>GENESIS — hanya #1–100, FOUNDER — #101–1000.</b> Nomor dibagikan berurutan dan tidak akan pernah terulang.',
        '🔒 <b>Kartu ini milikmu dan tidak bisa dipindahkan</b> — tanda kebanggaan dan hasil terverifikasi, bukan barang untuk dijual lagi.',
        'Kartu menegaskan apa yang dilihat AI di screenshot pada tanggal cek. Kartu tidak membuktikan kepemilikan akun, bukan investasi, dan tidak punya nilai uang. Contoh dengan data uji.',
        'Kartu sebelumnya', 'Kartu berikutnya',
        ['Semua mulai dari sini — kartu pertama di koleksi.', 'Langkah pertama di game sudah ada nilainya.', 'Foil tembaga: akun sudah masuk pasar.',
         'Perak: akun menengah yang solid.', 'Foil emas: akun berharga.', 'Platina es: level premium.', 'Hologram zamrud: koleksi elit.',
         'Hologram pelangi penuh: spesimen langka.', 'Foil hitam-pelangi: akun legendaris.'],
        'Bingkai emas khusus untuk 100 kartu pertama — di tingkat mana pun. Tidak akan diterbitkan lagi.', 'Bingkai pendiri untuk kartu #101–1000 — di tingkat mana pun. Ditutup selamanya.'),
 'tr': ('GameAccountValue kart koleksiyonu',
        'Her ücretli tahmin, benzersiz numaralı isimli bir karttır. <b>Folyo rengi satın alınamaz</b>: yalnızca hesabınızın dürüst tahminine bağlıdır. Herkes kartın gerçek olduğunu QR koduyla kontrol edebilir.',
        '🎴 <b>9 folyo seviyesi</b> — ahşap WOOD’dan siyah-gökkuşağı WHALE’a. Seviye şansı değil tahmini gösterir: hiçbir şey rastgele değildir.',
        '✨ <b>GENESIS — yalnızca #1–100, FOUNDER — #101–1000.</b> Numaralar sırayla verilir ve asla tekrarlanmaz.',
        '🔒 <b>Kart sizindir ve devredilemez</b> — bir onur rozeti ve doğrulanmış sonuç, yeniden satılacak bir ürün değil.',
        'Kart, yapay zekânın kontrol tarihinde ekran görüntülerinde gördüğünü doğrular. Hesap sahipliğini kanıtlamaz, yatırım değildir ve parasal değeri yoktur. Test verili örnekler.',
        'Önceki kart', 'Sonraki kart',
        ['Herkes buradan başlar — koleksiyondaki ilk kart.', 'Oyundaki ilk adımlarınız bile bir değer taşır.', 'Bakır folyo: hesap pazara çıktı.',
         'Gümüş: sağlam, orta seviye bir hesap.', 'Altın folyo: değerli bir hesap.', 'Buz platin: premium seviye.', 'Zümrüt hologram: elit bir koleksiyon.',
         'Tam gökkuşağı hologram: nadir bir örnek.', 'Siyah-gökkuşağı folyo: efsanevi bir hesap.'],
        'İlk 100 kart için özel altın çerçeve — her seviyede. Bir daha çıkarılmayacak.', '#101–1000 kartlar için kurucu çerçevesi — her seviyede. Sonsuza dek kapandı.'),
 'ar': ('مجموعة بطاقات GameAccountValue',
        'كل تقييم مدفوع هو بطاقة باسمك برقم فريد. <b>لون الرقاقة لا يُشترى</b>: يعتمد فقط على التقييم الصادق لحسابك. يمكن لأي شخص التحقق من أصالة البطاقة عبر رمز QR.',
        '🎴 <b>9 مستويات من الرقاقة</b> — من WOOD الخشبية إلى WHALE السوداء بألوان قوس قزح. المستوى يعكس التقييم لا الحظ: لا شيء عشوائي.',
        '✨ <b>GENESIS — فقط رقم 1–100، وFOUNDER — رقم 101–1000.</b> تُمنح الأرقام بالترتيب ولن تتكرر أبدًا.',
        '🔒 <b>البطاقة لك ولا يمكن نقلها</b> — شارة تميّز ونتيجة موثّقة، وليست سلعة لإعادة البيع.',
        'تؤكد البطاقة ما رآه الذكاء الاصطناعي في لقطات الشاشة يوم الفحص. لا تثبت ملكية الحساب، وليست استثمارًا، وليس لها قيمة مالية. عينات ببيانات تجريبية.',
        'البطاقة السابقة', 'البطاقة التالية',
        ['يبدأ الجميع من هنا — أول بطاقة في المجموعة.', 'خطواتك الأولى في اللعبة لها قيمة بالفعل.', 'رقاقة نحاسية: الحساب دخل السوق.',
         'فضة: حساب متوسط متين.', 'رقاقة ذهبية: حساب ثمين.', 'بلاتين جليدي: مستوى مميز.', 'هولوغرام زمردي: مجموعة نخبوية.',
         'هولوغرام قوس قزح كامل: قطعة نادرة.', 'رقاقة سوداء بألوان قوس قزح: حساب أسطوري.'],
        'إطار ذهبي خاص لأول 100 بطاقة — في أي مستوى. لن يُصدر مجددًا.', 'إطار المؤسسين للبطاقات 101–1000 — في أي مستوى. أُغلق إلى الأبد.'),
 'vi': ('Bộ sưu tập thẻ GameAccountValue',
        'Mỗi lần định giá trả phí là một thẻ mang tên bạn với số hiệu riêng. <b>Không thể mua màu lá kim</b>: màu chỉ phụ thuộc vào định giá trung thực tài khoản của bạn. Ai cũng có thể kiểm tra thẻ thật bằng mã QR.',
        '🎴 <b>9 cấp lá kim</b> — từ WOOD gỗ đến WHALE đen cầu vồng. Cấp thể hiện định giá, không phải may mắn: không có gì ngẫu nhiên.',
        '✨ <b>GENESIS — chỉ số 1–100, FOUNDER — số 101–1000.</b> Số được cấp theo thứ tự và sẽ không bao giờ lặp lại.',
        '🔒 <b>Thẻ là của bạn và không thể chuyển nhượng</b> — một huy hiệu và kết quả đã xác minh, không phải hàng để bán lại.',
        'Thẻ xác nhận những gì AI thấy trên ảnh chụp màn hình vào ngày kiểm tra. Thẻ không chứng minh quyền sở hữu tài khoản, không phải khoản đầu tư và không có giá trị tiền tệ. Mẫu với dữ liệu thử.',
        'Thẻ trước', 'Thẻ tiếp theo',
        ['Ai cũng bắt đầu từ đây — thẻ đầu tiên trong bộ sưu tập.', 'Những bước đầu trong game đã có giá trị.', 'Lá kim đồng: tài khoản đã ra thị trường.',
         'Bạc: tài khoản tầm trung vững chắc.', 'Lá kim vàng: tài khoản giá trị.', 'Bạch kim băng: cấp cao cấp.', 'Hologram ngọc lục bảo: bộ sưu tập tinh hoa.',
         'Hologram cầu vồng trọn vẹn: mẫu hiếm.', 'Lá kim đen cầu vồng: tài khoản huyền thoại.'],
        'Khung vàng đặc biệt cho 100 thẻ đầu tiên — ở mọi cấp. Không bao giờ phát hành lại.', 'Khung nhà sáng lập cho thẻ số 101–1000 — ở mọi cấp. Đóng lại mãi mãi.'),
 'hi': ('GameAccountValue कार्ड कलेक्शन',
        'हर पेड अनुमान एक नाम वाला कार्ड है, जिस पर यूनिक नंबर होता है। <b>फ़ॉयल का रंग ख़रीदा नहीं जा सकता</b>: यह सिर्फ़ आपके अकाउंट के ईमानदार अनुमान पर निर्भर है। कोई भी QR कोड से कार्ड की असलियत जाँच सकता है।',
        '🎴 <b>फ़ॉयल के 9 लेवल</b> — लकड़ी वाले WOOD से काले-इंद्रधनुषी WHALE तक। लेवल अनुमान दिखाता है, क़िस्मत नहीं: कुछ भी रैंडम नहीं।',
        '✨ <b>GENESIS — सिर्फ़ #1–100, FOUNDER — #101–1000.</b> नंबर क्रम से मिलते हैं और कभी दोहराए नहीं जाएँगे।',
        '🔒 <b>कार्ड आपका है और ट्रांसफ़र नहीं होता</b> — यह सम्मान का निशान और जाँचा हुआ नतीजा है, दोबारा बेचने की चीज़ नहीं।',
        'कार्ड बताता है कि जाँच वाले दिन AI ने स्क्रीनशॉट में क्या देखा। यह अकाउंट के मालिकाना हक़ की पुष्टि नहीं करता, निवेश नहीं है और इसकी कोई मौद्रिक क़ीमत नहीं। टेस्ट डेटा वाले नमूने।',
        'पिछला कार्ड', 'अगला कार्ड',
        ['सब यहीं से शुरू करते हैं — कलेक्शन का पहला कार्ड।', 'गेम में आपके पहले क़दमों की भी क़ीमत है।', 'ताँबे की फ़ॉयल: अकाउंट बाज़ार तक पहुँचा।',
         'चाँदी: मज़बूत मिड-लेवल अकाउंट।', 'सोने की फ़ॉयल: क़ीमती अकाउंट।', 'बर्फ़ीला प्लैटिनम: प्रीमियम लेवल।', 'पन्ना होलोग्राम: एलीट कलेक्शन।',
         'पूरा इंद्रधनुषी होलोग्राम: दुर्लभ नमूना।', 'काली-इंद्रधनुषी फ़ॉयल: लेजेंडरी अकाउंट।'],
        'पहले 100 कार्ड के लिए ख़ास सुनहरा फ़्रेम — किसी भी लेवल पर। दोबारा जारी नहीं होगा।', '#101–1000 कार्ड के लिए फ़ाउंडर फ़्रेम — किसी भी लेवल पर। हमेशा के लिए बंद।'),
 'fr': ('La collection de cartes GameAccountValue',
        'Chaque estimation payante est une carte nominative avec un numéro unique. <b>La couleur de la dorure ne s’achète pas</b> : elle dépend uniquement de l’estimation honnête de votre compte. Tout le monde peut vérifier l’authenticité d’une carte grâce à son QR code.',
        '🎴 <b>9 niveaux de dorure</b> — du WOOD en bois au WHALE noir irisé. Le niveau reflète l’estimation, pas la chance : rien n’est aléatoire.',
        '✨ <b>GENESIS — uniquement nº 1–100, FOUNDER — nº 101–1000.</b> Les numéros sont attribués dans l’ordre et ne se répéteront jamais.',
        '🔒 <b>La carte est à vous et n’est pas cessible</b> — une distinction et un résultat vérifié, pas un objet à revendre.',
        'La carte confirme ce que l’IA a vu sur les captures à la date du contrôle. Elle ne prouve pas la propriété du compte, n’est pas un investissement et n’a aucune valeur monétaire. Exemples avec des données de test.',
        'Carte précédente', 'Carte suivante',
        ['Tout le monde commence ici — la première carte de la collection.', 'Vos premiers pas dans le jeu valent déjà quelque chose.', 'Dorure cuivre : le compte arrive sur le marché.',
         'Argent : un compte intermédiaire solide.', 'Dorure or : un compte de valeur.', 'Platine glacé : niveau premium.', 'Hologramme émeraude : une collection d’élite.',
         'Hologramme arc-en-ciel intégral : une pièce rare.', 'Dorure noire irisée : un compte légendaire.'],
        'Cadre doré spécial pour les 100 premières cartes — à tout niveau. Plus jamais réédité.', 'Cadre fondateur pour les cartes nº 101–1000 — à tout niveau. Fermé pour toujours.'),
 'de': ('Die GameAccountValue-Kartensammlung',
        'Jede bezahlte Schätzung ist eine Karte mit deinem Namen und einer einmaligen Nummer. <b>Die Folienfarbe kann man nicht kaufen</b>: Sie hängt nur von der ehrlichen Schätzung deines Accounts ab. Jeder kann per QR-Code prüfen, ob eine Karte echt ist.',
        '🎴 <b>9 Folienstufen</b> — vom hölzernen WOOD bis zum schwarz-schillernden WHALE. Die Stufe zeigt die Schätzung, nicht Glück: nichts ist zufällig.',
        '✨ <b>GENESIS — nur Nr. 1–100, FOUNDER — Nr. 101–1000.</b> Die Nummern werden der Reihe nach vergeben und wiederholen sich nie.',
        '🔒 <b>Die Karte gehört dir und ist nicht übertragbar</b> — ein Abzeichen und ein geprüftes Ergebnis, keine Ware zum Weiterverkauf.',
        'Die Karte bestätigt, was die KI am Prüfdatum auf den Screenshots gesehen hat. Sie belegt nicht den Besitz des Accounts, ist keine Geldanlage und hat keinen Geldwert. Beispiele mit Testdaten.',
        'Vorherige Karte', 'Nächste Karte',
        ['Hier fangen alle an — die erste Karte der Sammlung.', 'Deine ersten Schritte im Spiel sind schon etwas wert.', 'Kupferfolie: Der Account ist auf dem Markt angekommen.',
         'Silber: ein solider mittlerer Account.', 'Goldfolie: ein wertvoller Account.', 'Eisiges Platin: Premium-Stufe.', 'Smaragd-Hologramm: eine Elite-Sammlung.',
         'Volles Regenbogen-Hologramm: ein seltenes Exemplar.', 'Schwarz-schillernde Folie: ein legendärer Account.'],
        'Goldener Sonderrahmen für die ersten 100 Karten — auf jeder Stufe. Wird nie wieder ausgegeben.', 'Gründerrahmen für die Karten Nr. 101–1000 — auf jeder Stufe. Für immer geschlossen.'),
 'it': ('La collezione di carte GameAccountValue',
        'Ogni stima a pagamento è una carta nominativa con un numero unico. <b>Il colore della lamina non si compra</b>: dipende solo dalla stima onesta del tuo account. Chiunque può verificare che la carta sia autentica con il QR code.',
        '🎴 <b>9 livelli di lamina</b> — dal WOOD in legno al WHALE nero iridescente. Il livello mostra la stima, non la fortuna: niente è casuale.',
        '✨ <b>GENESIS — solo n. 1–100, FOUNDER — n. 101–1000.</b> I numeri vengono assegnati in ordine e non si ripeteranno mai.',
        '🔒 <b>La carta è tua e non è trasferibile</b> — un distintivo e un risultato verificato, non un oggetto da rivendere.',
        'La carta conferma ciò che l’IA ha visto negli screenshot alla data del controllo. Non conferma la proprietà dell’account, non è un investimento e non ha valore monetario. Esempi con dati di prova.',
        'Carta precedente', 'Carta successiva',
        ['Tutti iniziano da qui — la prima carta della collezione.', 'I tuoi primi passi nel gioco valgono già qualcosa.', 'Lamina di rame: l’account è arrivato sul mercato.',
         'Argento: un solido account di livello medio.', 'Lamina d’oro: un account di valore.', 'Platino ghiaccio: livello premium.', 'Ologramma smeraldo: una collezione d’élite.',
         'Ologramma arcobaleno completo: un esemplare raro.', 'Lamina nera iridescente: un account leggendario.'],
        'Cornice dorata speciale per le prime 100 carte — a qualsiasi livello. Non verrà mai più emessa.', 'Cornice dei fondatori per le carte n. 101–1000 — a qualsiasi livello. Chiusa per sempre.'),
 'ja': ('GameAccountValue カードコレクション',
        '有料査定のたびに、固有番号入りの名前付きカードが発行されます。<b>箔の色はお金では買えません</b>。アカウントの正直な査定額だけで決まります。QRコードで誰でも本物か確認できます。',
        '🎴 <b>9段階の箔</b>：木目のWOODから黒虹のWHALEまで。段階は運ではなく査定額を表します。ランダム要素は一切ありません。',
        '✨ <b>GENESISは#1〜100のみ、FOUNDERは#101〜1000。</b>番号は発行順に付けられ、二度と繰り返されません。',
        '🔒 <b>カードはあなた専用で譲渡できません</b>。転売する商品ではなく、称号と確認済みの結果です。',
        'カードは確認日にAIがスクリーンショットで見た内容を示すものです。アカウントの所有を証明せず、投資でもなく、金銭的価値もありません。テストデータによる見本です。',
        '前のカード', '次のカード',
        ['誰もがここから始まる、コレクション最初の一枚。', 'ゲームでの最初の一歩にも価値があります。', '銅箔：アカウントが市場に登場。',
         'シルバー：しっかりした中堅アカウント。', '金箔：価値あるアカウント。', 'アイスプラチナ：プレミアム級。', 'エメラルドホログラム：エリートコレクション。',
         'フルレインボーホログラム：希少な一枚。', '黒虹箔：伝説のアカウント。'],
        '最初の100枚だけの特別な金枠。どの段階でも付き、二度と発行されません。', '#101〜1000のカードに付くファウンダー枠。どの段階でも付き、永久に締め切り。'),
 'ko': ('GameAccountValue 카드 컬렉션',
        '유료 감정마다 고유 번호가 새겨진 이름 카드가 발급됩니다. <b>포일 색상은 돈으로 살 수 없습니다</b>. 오직 계정의 정직한 감정가로만 정해집니다. QR 코드로 누구나 진품인지 확인할 수 있어요.',
        '🎴 <b>9단계 포일</b> — 나무 WOOD부터 블랙 레인보우 WHALE까지. 단계는 운이 아니라 감정가를 보여 줍니다. 랜덤 요소는 없습니다.',
        '✨ <b>GENESIS는 #1–100만, FOUNDER는 #101–1000.</b> 번호는 순서대로 발급되며 절대 반복되지 않습니다.',
        '🔒 <b>카드는 당신의 것이며 양도할 수 없습니다</b> — 되팔 물건이 아니라 명예의 배지이자 검증된 결과입니다.',
        '카드는 확인 날짜에 AI가 스크린샷에서 본 내용을 확인해 줄 뿐입니다. 계정 소유를 증명하지 않으며, 투자 상품이 아니고 금전적 가치가 없습니다. 테스트 데이터 예시.',
        '이전 카드', '다음 카드',
        ['모두가 여기서 시작합니다 — 컬렉션의 첫 카드.', '게임에서의 첫걸음도 이미 가치가 있어요.', '구리 포일: 계정이 시장에 나왔어요.',
         '실버: 탄탄한 중급 계정.', '골드 포일: 가치 있는 계정.', '아이스 플래티넘: 프리미엄 등급.', '에메랄드 홀로그램: 엘리트 컬렉션.',
         '풀 레인보우 홀로그램: 희귀한 표본.', '블랙 레인보우 포일: 전설의 계정.'],
        '첫 100장만을 위한 특별 골드 프레임 — 어느 단계든. 다시는 발급되지 않습니다.', '#101–1000 카드를 위한 파운더 프레임 — 어느 단계든. 영원히 마감.'),
 'zh': ('GameAccountValue 卡牌收藏',
        '每一次付费估值都是一张带有专属编号的记名卡牌。<b>烫金颜色买不到</b>：它只取决于你账号的真实估值。任何人都可以通过二维码验证卡牌真伪。',
        '🎴 <b>9 个烫金等级</b>：从木质 WOOD 到黑色彩虹 WHALE。等级代表估值而不是运气：没有任何随机。',
        '✨ <b>GENESIS 仅限 #1–100，FOUNDER 为 #101–1000。</b>编号按顺序发放，永不重复。',
        '🔒 <b>卡牌归你所有，不可转让</b>：这是荣誉徽章和经过验证的结果，不是用来转卖的商品。',
        '卡牌确认的是检测当天 AI 在截图中看到的内容。它不证明账号归属，不是投资，也没有货币价值。示例使用测试数据。',
        '上一张卡牌', '下一张卡牌',
        ['所有人都从这里开始：收藏中的第一张卡牌。', '你在游戏中的第一步就已经有价值。', '铜色烫金：账号已进入市场。',
         '白银：扎实的中级账号。', '金色烫金：有价值的账号。', '冰晶铂金：高级等级。', '翡翠全息：精英收藏。',
         '全彩虹全息：稀有珍品。', '黑色彩虹烫金：传奇账号。'],
        '前 100 张卡牌专属金色特别边框，任何等级都可获得，永不再发。', '#101–1000 卡牌的创始者边框，任何等级都可获得，永久截止。'),
 'pl': ('Kolekcja kart GameAccountValue',
        'Każda płatna wycena to imienna karta z unikalnym numerem. <b>Koloru folii nie da się kupić</b>: zależy tylko od uczciwej wyceny Twojego konta. Każdy może sprawdzić autentyczność karty kodem QR.',
        '🎴 <b>9 poziomów folii</b> — od drewnianej WOOD po czarno-tęczową WHALE. Poziom pokazuje wycenę, a nie szczęście: nic nie jest losowe.',
        '✨ <b>GENESIS — tylko nr 1–100, FOUNDER — nr 101–1000.</b> Numery są wydawane po kolei i nigdy się nie powtórzą.',
        '🔒 <b>Karta jest Twoja i nie da się jej przekazać</b> — to wyróżnienie i sprawdzony wynik, a nie towar na odsprzedaż.',
        'Karta potwierdza to, co AI zobaczyło na zrzutach ekranu w dniu sprawdzenia. Nie potwierdza własności konta, nie jest inwestycją i nie ma wartości pieniężnej. Przykłady z danymi testowymi.',
        'Poprzednia karta', 'Następna karta',
        ['Tu zaczyna każdy — pierwsza karta w kolekcji.', 'Twoje pierwsze kroki w grze już coś są warte.', 'Miedziana folia: konto trafiło na rynek.',
         'Srebro: solidne konto średniego poziomu.', 'Złota folia: wartościowe konto.', 'Lodowa platyna: poziom premium.', 'Szmaragdowy hologram: elitarna kolekcja.',
         'Pełny tęczowy hologram: rzadki egzemplarz.', 'Czarno-tęczowa folia: legendarne konto.'],
        'Specjalna złota ramka pierwszych 100 kart — na każdym poziomie. Nigdy więcej nie zostanie wydana.', 'Ramka założyciela dla kart nr 101–1000 — na każdym poziomie. Zamknięta na zawsze.'),
 'th': ('คอลเลกชันการ์ด GameAccountValue',
        'การประเมินแบบชำระเงินทุกครั้งคือการ์ดที่มีชื่อและหมายเลขไม่ซ้ำ <b>สีฟอยล์ซื้อไม่ได้</b> ขึ้นอยู่กับการประเมินบัญชีของคุณอย่างตรงไปตรงมาเท่านั้น ใครก็ตรวจสอบได้ว่าการ์ดเป็นของจริงผ่านคิวอาร์โค้ด',
        '🎴 <b>ฟอยล์ 9 ระดับ</b> — ตั้งแต่ WOOD ลายไม้ถึง WHALE ดำรุ้ง ระดับสะท้อนผลประเมิน ไม่ใช่ดวง ไม่มีการสุ่มใดๆ',
        '✨ <b>GENESIS เฉพาะ #1–100, FOUNDER #101–1000</b> หมายเลขออกตามลำดับและจะไม่ซ้ำอีกเลย',
        '🔒 <b>การ์ดเป็นของคุณและโอนให้ใครไม่ได้</b> — เป็นสัญลักษณ์และผลการตรวจที่ยืนยันแล้ว ไม่ใช่สินค้าไว้ขายต่อ',
        'การ์ดยืนยันสิ่งที่ AI เห็นในภาพหน้าจอในวันที่ตรวจ ไม่ได้ยืนยันความเป็นเจ้าของบัญชี ไม่ใช่การลงทุน และไม่มีมูลค่าเป็นเงิน ตัวอย่างใช้ข้อมูลทดสอบ',
        'การ์ดก่อนหน้า', 'การ์ดถัดไป',
        ['ทุกคนเริ่มจากตรงนี้ — การ์ดใบแรกในคอลเลกชัน', 'ก้าวแรกในเกมก็มีค่าแล้ว', 'ฟอยล์ทองแดง: บัญชีเข้าสู่ตลาดแล้ว',
         'เงิน: บัญชีระดับกลางที่แข็งแรง', 'ฟอยล์ทอง: บัญชีที่มีค่า', 'แพลทินัมน้ำแข็ง: ระดับพรีเมียม', 'โฮโลแกรมมรกต: คอลเลกชันระดับหัวกะทิ',
         'โฮโลแกรมรุ้งเต็มใบ: ชิ้นหายาก', 'ฟอยล์ดำรุ้ง: บัญชีระดับตำนาน'],
        'กรอบทองพิเศษสำหรับการ์ด 100 ใบแรก — ทุกระดับ จะไม่ออกอีกแล้ว', 'กรอบผู้ก่อตั้งสำหรับการ์ด #101–1000 — ทุกระดับ ปิดรับตลอดไป'),
 'tl': ('Koleksyon ng card ng GameAccountValue',
        'Bawat bayad na estimate ay isang card na may pangalan at natatanging numero. <b>Hindi nabibili ang kulay ng foil</b>: nakadepende lang ito sa tapat na estimate ng account mo. Kahit sino ay puwedeng mag-check kung totoo ang card gamit ang QR code.',
        '🎴 <b>9 na antas ng foil</b> — mula sa kahoy na WOOD hanggang sa itim-na-bahaghari na WHALE. Ang antas ay nagpapakita ng estimate, hindi ng swerte: walang random.',
        '✨ <b>GENESIS — #1–100 lang, FOUNDER — #101–1000.</b> Sunud-sunod ang pagbibigay ng numero at hindi na mauulit kailanman.',
        '🔒 <b>Sa iyo ang card at hindi ito maililipat</b> — isang badge at beripikadong resulta, hindi paninda para ibenta ulit.',
        'Kinukumpirma ng card ang nakita ng AI sa mga screenshot sa petsa ng pagsusuri. Hindi nito pinapatunayan ang pagmamay-ari ng account, hindi ito investment at walang halagang pera. Mga sample na may test data.',
        'Nakaraang card', 'Susunod na card',
        ['Dito nagsisimula ang lahat — ang unang card sa koleksyon.', 'May halaga na ang mga unang hakbang mo sa laro.', 'Tansong foil: nasa merkado na ang account.',
         'Pilak: matatag na mid-level na account.', 'Gintong foil: mahalagang account.', 'Nagyeyelong platinum: premium na antas.', 'Esmeraldang hologram: elite na koleksyon.',
         'Buong bahagharing hologram: bihirang specimen.', 'Itim-na-bahagharing foil: maalamat na account.'],
        'Espesyal na gintong frame para sa unang 100 card — sa kahit anong antas. Hindi na ilalabas muli.', 'Frame ng founder para sa mga card #101–1000 — sa kahit anong antas. Sarado na magpakailanman.'),
 'sw': ('Mkusanyiko wa kadi za GameAccountValue',
        'Kila makadirio ya kulipia ni kadi yenye jina na namba ya kipekee. <b>Rangi ya foili hainunuliki</b>: inategemea tu makadirio ya haki ya akaunti yako. Mtu yeyote anaweza kukagua uhalali wa kadi kwa msimbo wa QR.',
        '🎴 <b>Viwango 9 vya foili</b> — kutoka WOOD ya mbao hadi WHALE nyeusi-upinde wa mvua. Kiwango kinaonyesha makadirio, si bahati: hakuna kitu cha kubahatisha.',
        '✨ <b>GENESIS — #1–100 pekee, FOUNDER — #101–1000.</b> Namba hutolewa kwa mpangilio na hazitajirudia kamwe.',
        '🔒 <b>Kadi ni yako na haihamishiki</b> — ni nishani na matokeo yaliyothibitishwa, si bidhaa ya kuuza tena.',
        'Kadi inathibitisha kile AI iliona kwenye picha za skrini siku ya ukaguzi. Haithibitishi umiliki wa akaunti, si uwekezaji na haina thamani ya kifedha. Mifano yenye data ya majaribio.',
        'Kadi iliyotangulia', 'Kadi inayofuata',
        ['Kila mtu huanzia hapa — kadi ya kwanza kwenye mkusanyiko.', 'Hatua zako za kwanza kwenye mchezo tayari zina thamani.', 'Foili ya shaba: akaunti imefika sokoni.',
         'Fedha: akaunti imara ya kiwango cha kati.', 'Foili ya dhahabu: akaunti yenye thamani.', 'Platinamu ya barafu: kiwango cha premium.', 'Hologramu ya zumaridi: mkusanyiko wa hadhi ya juu.',
         'Hologramu kamili ya upinde wa mvua: kielelezo adimu.', 'Foili nyeusi-upinde wa mvua: akaunti ya hadithi.'],
        'Fremu maalum ya dhahabu kwa kadi 100 za kwanza — kwa kiwango chochote. Haitatolewa tena.', 'Fremu ya waanzilishi kwa kadi #101–1000 — kwa kiwango chochote. Imefungwa milele.'),
 'ms': ('Koleksi kad GameAccountValue',
        'Setiap anggaran berbayar ialah kad bernama dengan nombor unik. <b>Warna foil tidak boleh dibeli</b>: ia hanya bergantung pada anggaran jujur akaun anda. Sesiapa sahaja boleh menyemak keaslian kad melalui kod QR.',
        '🎴 <b>9 peringkat foil</b> — daripada WOOD kayu hingga WHALE hitam-pelangi. Peringkat menunjukkan anggaran, bukan nasib: tiada yang rawak.',
        '✨ <b>GENESIS — hanya #1–100, FOUNDER — #101–1000.</b> Nombor diberikan mengikut turutan dan tidak akan berulang.',
        '🔒 <b>Kad ini milik anda dan tidak boleh dipindahkan</b> — lencana dan keputusan yang disahkan, bukan barang untuk dijual semula.',
        'Kad mengesahkan apa yang dilihat AI pada tangkapan skrin pada tarikh semakan. Ia tidak membuktikan pemilikan akaun, bukan pelaburan dan tidak mempunyai nilai wang. Contoh dengan data ujian.',
        'Kad sebelumnya', 'Kad seterusnya',
        ['Semua orang bermula di sini — kad pertama dalam koleksi.', 'Langkah pertama anda dalam permainan sudah bernilai.', 'Foil tembaga: akaun sudah masuk pasaran.',
         'Perak: akaun sederhana yang kukuh.', 'Foil emas: akaun yang bernilai.', 'Platinum ais: tahap premium.', 'Hologram zamrud: koleksi elit.',
         'Hologram pelangi penuh: spesimen jarang.', 'Foil hitam-pelangi: akaun legenda.'],
        'Bingkai emas khas untuk 100 kad pertama — di mana-mana peringkat. Tidak akan dikeluarkan lagi.', 'Bingkai pengasas untuk kad #101–1000 — di mana-mana peringkat. Ditutup selama-lamanya.'),
 'uz': ('GameAccountValue kartalar kolleksiyasi',
        'Har bir pullik baholash — noyob raqamli, nomingiz yozilgan karta. <b>Folga rangini sotib olib boʻlmaydi</b>: u faqat akkauntingizning halol bahosiga bogʻliq. Har kim kartaning haqiqiyligini QR-kod orqali tekshira oladi.',
        '🎴 <b>Folganing 9 darajasi</b> — yogʻoch WOODdan qora-kamalak WHALEgacha. Daraja omadni emas, bahoni koʻrsatadi: hech narsa tasodifiy emas.',
        '✨ <b>GENESIS — faqat №1–100, FOUNDER — №101–1000.</b> Raqamlar navbat bilan beriladi va hech qachon takrorlanmaydi.',
        '🔒 <b>Karta sizniki va boshqaga berilmaydi</b> — bu qayta sotiladigan tovar emas, faxr belgisi va tekshirilgan natija.',
        'Karta tekshiruv kuni SI skrinshotlarda nimani koʻrganini tasdiqlaydi. U akkauntga egalikni tasdiqlamaydi, investitsiya emas va pul qiymatiga ega emas. Test maʼlumotli namunalar.',
        'Oldingi karta', 'Keyingi karta',
        ['Hamma shu yerdan boshlaydi — kolleksiyadagi birinchi karta.', 'Oʻyindagi ilk qadamlaringiz ham qadrli.', 'Mis folga: akkaunt bozorga chiqdi.',
         'Kumush: mustahkam oʻrta darajadagi akkaunt.', 'Oltin folga: qimmatli akkaunt.', 'Muzdek platina: premium daraja.', 'Zumrad gologramma: elita kolleksiyasi.',
         'Toʻliq kamalak gologramma: noyob nusxa.', 'Qora-kamalak folga: afsonaviy akkaunt.'],
        'Birinchi 100 karta uchun maxsus oltin ramka — istalgan darajada. Boshqa chiqarilmaydi.', '№101–1000 kartalar uchun asoschilar ramkasi — istalgan darajada. Abadiy yopildi.'),
 'kk': ('GameAccountValue карталар коллекциясы',
        'Әр ақылы бағалау — бірегей нөмірі бар атаулы карта. <b>Фольга түсін сатып алу мүмкін емес</b>: ол тек аккаунтыңыздың адал бағасына байланысты. Кез келген адам картаның түпнұсқа екенін QR-код арқылы тексере алады.',
        '🎴 <b>Фольганың 9 деңгейі</b> — ағаш WOOD-тан қара-кемпірқосақ WHALE-ға дейін. Деңгей сәттілікті емес, бағаны көрсетеді: ешнәрсе кездейсоқ емес.',
        '✨ <b>GENESIS — тек №1–100, FOUNDER — №101–1000.</b> Нөмірлер кезекпен беріледі және ешқашан қайталанбайды.',
        '🔒 <b>Карта сіздікі және басқаға берілмейді</b> — бұл қайта сатуға арналған тауар емес, мақтаныш белгісі және тексерілген нәтиже.',
        'Карта тексеру күні ЖИ скриншоттарда нені көргенін растайды. Ол аккаунтқа иелікті растамайды, инвестиция емес және ақшалай құны жоқ. Тест деректері бар үлгілер.',
        'Алдыңғы карта', 'Келесі карта',
        ['Бәрі осыдан бастайды — коллекциядағы алғашқы карта.', 'Ойындағы алғашқы қадамдарыңыздың да құны бар.', 'Мыс фольга: аккаунт нарыққа шықты.',
         'Күміс: берік орташа аккаунт.', 'Алтын фольга: құнды аккаунт.', 'Мұзды платина: премиум деңгей.', 'Зүмірет голограмма: элиталық коллекция.',
         'Толық кемпірқосақ голограмма: сирек дана.', 'Қара-кемпірқосақ фольга: аңызға айналған аккаунт.'],
        'Алғашқы 100 картаға арналған арнайы алтын жиектеме — кез келген деңгейде. Қайта шығарылмайды.', '№101–1000 карталарға арналған негізін салушылар жиектемесі — кез келген деңгейде. Мәңгіге жабылды.'),
 'tk': ('GameAccountValue kartlar kolleksiýasy',
        'Her tölegli baha — üýtgeşik belgili, adyňyz ýazylan kart. <b>Folganyň reňkini satyn alyp bolmaýar</b>: ol diňe hasabyňyzyň dogruçyl bahasyna bagly. Islendik adam kartyň hakykydygyny QR-kod arkaly barlap biler.',
        '🎴 <b>Folganyň 9 derejesi</b> — agaç WOOD-dan gara-älemgoşar WHALE-a çenli. Dereje bagty däl-de, bahany görkezýär: hiç zat tötänleýin däl.',
        '✨ <b>GENESIS — diňe №1–100, FOUNDER — №101–1000.</b> Belgiler nobat bilen berilýär we hiç haçan gaýtalanmaýar.',
        '🔒 <b>Kart siziňki we başga berilmeýär</b> — bu gaýtadan satylýan haryt däl, buýsanç nyşany we barlanan netije.',
        'Kart barlag güni emeli aňyň skrinşotlarda näme görendigini tassyklaýar. Ol hasaba eýeçiligi tassyklamaýar, maýa goýum däl we pul gymmaty ýok. Synag maglumatly nusgalar.',
        'Öňki kart', 'Indiki kart',
        ['Hemmeler şu ýerden başlaýar — kolleksiýadaky ilkinji kart.', 'Oýundaky ilkinji ädimleriňiz hem gymmatly.', 'Mis folga: hasap bazara çykdy.',
         'Kümüş: berk orta derejeli hasap.', 'Altyn folga: gymmatly hasap.', 'Buzly platina: premium dereje.', 'Zümerret gologramma: elita kolleksiýasy.',
         'Doly älemgoşar gologramma: seýrek nusga.', 'Gara-älemgoşar folga: rowaýata öwrülen hasap.'],
        'Ilkinji 100 kart üçin ýörite altyn çarçuwa — islendik derejede. Indi çykarylmaz.', '№101–1000 kartlar üçin esaslandyryjylar çarçuwasy — islendik derejede. Baky ýapyldy.'),
 'ky': ('GameAccountValue карталар коллекциясы',
        'Ар бир акы төлөнгөн баалоо — уникалдуу номери бар аталган карта. <b>Фольганын түсүн сатып алуу мүмкүн эмес</b>: ал аккаунтуңдун чынчыл баасына гана көз каранды. Каалаган адам картанын чыныгы экенин QR-код аркылуу текшере алат.',
        '🎴 <b>Фольганын 9 деңгээли</b> — жыгач WOOD’дон кара-желекей WHALE’ге чейин. Деңгээл ийгиликти эмес, бааны көрсөтөт: эч нерсе кокусунан эмес.',
        '✨ <b>GENESIS — №1–100 гана, FOUNDER — №101–1000.</b> Номерлер кезек менен берилет жана эч качан кайталанбайт.',
        '🔒 <b>Карта сеники жана башкага берилбейт</b> — бул кайра сатыла турган товар эмес, сыймык белгиси жана текшерилген натыйжа.',
        'Карта текшерүү күнү ЖИ скриншотторду эмнени көргөнүн тастыктайт. Ал аккаунтка ээликти тастыктабайт, инвестиция эмес жана акчалай наркы жок. Тест маалыматтары бар үлгүлөр.',
        'Мурунку карта', 'Кийинки карта',
        ['Баары ушундан баштайт — коллекциядагы биринчи карта.', 'Оюндагы алгачкы кадамдарыңдын да баасы бар.', 'Жез фольга: аккаунт базарга чыкты.',
         'Күмүш: бекем орто деңгээлдеги аккаунт.', 'Алтын фольга: баалуу аккаунт.', 'Муздай платина: премиум деңгээл.', 'Зымырыт голограмма: элиталык коллекция.',
         'Толук желекей голограмма: сейрек нуска.', 'Кара-желекей фольга: легендарлуу аккаунт.'],
        'Алгачкы 100 карта үчүн атайын алтын алкак — каалаган деңгээлде. Кайра чыгарылбайт.', '№101–1000 карталар үчүн негиздөөчүлөр алкагы — каалаган деңгээлде. Түбөлүккө жабылды.'),
}


def section(lang: str, prefix: str) -> str:
    title, lead, p1, p2, p3, note, prev, nxt, flav, gen, fou = T[lang]
    descs = [f'{RANGES[i]} · {flav[i]}' for i in range(9)] + [f'{RANGES[9]} · {gen}', f'{RANGES[10]} · {fou}']
    esc = lambda s: s.replace('"', '&quot;')
    items = ''.join(f'<div class="gc-card" data-k="{k}" data-t="{NAMES[i]}" data-d="{esc(descs[i])}"><img src="{prefix}assets/cards/{lang}/{k}.webp?v=2" '
                    f'width="540" height="360" alt="{NAMES[i]}" loading="lazy" decoding="async"></div>' for i, k in enumerate(KEYS))
    return (f'<!-- CARD COLLECTION -->\n<section class="gc-sec" id="cards">\n  <div class="gc-intro">\n    <h2>{title}</h2>\n    <p>{lead}</p>\n'
            f'    <ul class="gc-points">\n      <li>{p1}</li>\n      <li>{p2}</li>\n      <li>{p3}</li>\n    </ul>\n  </div>\n'
            f'  <div class="gc-stage">\n    <button class="gc-arrow gc-prev" type="button" aria-label="{prev}">&#8249;</button>\n'
            f'    <div class="gc-track">{items}</div>\n'
            f'    <button class="gc-arrow gc-next" type="button" aria-label="{nxt}">&#8250;</button>\n  </div>\n'
            f'  <div class="gc-cap" aria-live="polite"></div>\n  <div class="gc-dots" aria-hidden="true"></div>\n'
            f'  <p class="gc-note">{note}</p>\n</section>\n\n')


def main():
    n = 0
    for lang in T:
        f = ROOT + ('index.html' if lang == 'en' else lang + os.sep + 'index.html')
        pre = './' if lang == 'en' else '../'
        s = open(f, encoding='utf-8').read()
        s = re.sub(r'<!-- CARD COLLECTION -->.*?</section>\n\n', '', s, flags=re.S)
        s = re.sub(r'\s*<div class="cert-sample">.*?</div>', '', s, count=1, flags=re.S)
        s = s.replace('<!-- FEATURES -->', section(lang, pre) + '<!-- FEATURES -->', 1)
        open(f, 'w', encoding='utf-8', newline='').write(s)
        n += 1
    print('card collection on', n, 'homepages')


if __name__ == '__main__':
    main()
