# English master text of the privacy policy and terms (reference version).
# Facts checked against the bot code 2026-09-30: core/database.py (tables,
# delete_user_data, 90-day fingerprint purge), core/providers.py (Gemini, cache
# key = one-way hash of the images), core/telegraph_api.py (public card page),
# tg_bot/bot.py (card name = Telegram first name or in-game name).
TEXT = {'en': {
 'updated': 'Last updated: 30 September 2026',
 'ref': 'This English text is the reference version. Translations into 23 other languages are provided so that everyone can read it in their own language; if a translation differs, the English version applies.',
 'privacy': {
  'title': 'Privacy Policy',
  'desc': 'What the GameAccountValue website and Telegram bot collect, what they never collect, how long data is kept and how to delete it with one command.',
  'h1': 'Privacy Policy',
  'lead': 'The website collects nothing. The bot keeps the minimum it needs to deliver and verify your valuation, and <code>/delete</code> erases it.',
  'sec': [
   ('The short version', '<ul><li>The website sets <strong>no cookies</strong> and the calculator runs entirely in your browser.</li><li>The bot <strong>never stores your screenshots</strong>: they are held in memory for the AI analysis and then discarded.</li><li>Your Telegram ID is stored only as a <strong>one-way SHA-256 hash</strong>.</li><li>Send <code>/delete</code> in the bot to erase your data immediately.</li></ul>'),
   ('This website', '<p>gameaccountvalue.com sets <strong>no cookies</strong>, uses <strong>no analytics, tracking pixels or advertising</strong>, and loads <strong>no third-party scripts, fonts or images</strong>. Everything is served from this domain, and a Content-Security-Policy blocks other origins. The value calculator runs in your browser: nothing you move or select is sent anywhere. The hosting provider (GitHub Pages) processes standard technical request data such as IP addresses to deliver the site, as any web host does; we do not receive or store it. Links to marketplaces, publishers, Twitch and other sources open their own sites, which have their own privacy policies.</p>'),
   ('Screenshots and AI processing', '<p>To produce a valuation, your screenshots are sent to <strong>Google’s Gemini API</strong> for AI image analysis at the moment you submit them. The service cannot work without this step. Google processes this data under its own API terms and privacy policy; we do not control Google’s retention of API inputs. No other third party receives your screenshots.</p>'),
   ('What the bot stores', '<ul><li>Your Telegram ID as a one-way hash, whether you accepted the 18+ terms, and the date of your last free estimate.</li><li>The game, the date and the AI-generated valuation result.</li><li>For paid audits: the name printed on your card (your Telegram first name, or the in-game name read from your screenshots), the card number, edition and tier, and the Telegram payment charge ID, which is kept so that a payment can be refunded.</li><li>A <strong>fingerprint</strong> of each screenshot — a short code calculated from the image, not the image itself — used to notice the same screenshot being reused by different people. Fingerprints are deleted after 90 days.</li><li>Anything you choose to write to us in the bot, such as feedback or a support message.</li><li>Referral and partner records, if you use those programmes.</li></ul><p>To avoid running the AI twice on identical screenshots, its reading of the images is cached under a one-way hash of the image files. The cache contains no user ID and is not linked to you.</p>'),
   ('What we never collect', '<ul><li>Your screenshots — they are never written to disk or kept by us.</li><li>Game logins or passwords. We never ask for them.</li><li>Payment card details — payments are handled by Telegram.</li><li>Your phone number or contacts.</li></ul>'),
   ('Your card and its public page', '<p>For a paid audit the bot also publishes your card image and estimated value on a page at <strong>telegra.ph</strong> (Telegram’s publishing service), so you can share it with a link. We do not publish that link anywhere, but anyone who has it can open the page, and search engines may index it. Telegraph does not allow pages to be deleted, so <code>/delete</code> cannot remove it. The card shows the name printed on it — if you do not want your name on a public page, do not share the link. Anyone who knows your card number or Scan ID can also check the card in the bot, which shows the data printed on it.</p>'),
   ('Legal basis', '<p>We process the data above under GDPR Art. 6(1)(b): it is necessary to perform the valuation you asked for. For paid features, processing your payment status is also necessary for that contract. Screenshot fingerprints are processed under Art. 6(1)(f), our legitimate interest in preventing fraud, and are limited to 90 days.</p>'),
   ('How long we keep it', '<p>Data is kept until you delete it yourself with <code>/delete</code>. That command immediately removes everything linked to your hashed ID: valuations, cards, payment references, fingerprints, messages, and referral or partner balances. Once deleted, your card no longer verifies. Screenshot fingerprints are removed automatically after 90 days in any case. The public Telegraph page described above is outside our control.</p>'),
   ('Automated decision-making', '<p>Your valuation is produced entirely by automated AI processing — no person reviews or approves individual results. It has no legal or similarly significant effect on you: it is an estimate for information and entertainment, not a binding price, a credit decision or an eligibility check, so GDPR Art. 22 does not apply. See the AI disclaimer in our <a href="./terms.html">Terms of Service</a> for how to read the result.</p>'),
   ('Your rights', '<p>Depending on where you live, you may have the right to access, correct, erase, restrict or object to the processing of your data, and to receive a copy of it. Because we hold so little, most of these rights are exercised the same way: write to us in the bot or use <code>/delete</code>. If you are in the EU, EEA or UK, you can also complain to your local data protection authority at any time.</p>'),
   ('Contact', '<p>Data controller: Aleksei Sergeevich Bitkin, independent developer. Contact and support: <a href="https://t.me/GameAccountValue_Bot">t.me/GameAccountValue_Bot</a></p>'),
  ]},
 'terms': {
  'title': 'Terms of Service',
  'desc': 'GameAccountValue terms: who can use the bot, payments in Telegram Stars, refunds and the EU withdrawal right, collector cards and the AI valuation disclaimer.',
  'h1': 'Terms of Service',
  'lead': 'GameAccountValue is an <strong>entertainment and information service</strong>. It gives an approximate, AI-generated estimate of the value invested in a game collection. By using @GameAccountValue_Bot you agree to these terms.',
  'sec': [
   ('Not a marketplace', '<p>We do <strong>not</strong> sell, buy or broker game accounts, and we do not help transfer or trade them. Trading accounts may break the rules of the game you play — you alone are responsible for following each game’s terms.</p>'),
   ('Who can use it', '<p>You must be 18 or older to use the service.</p>'),
   ('Payments', '<p>Payments are made in Telegram Stars (XTR). The partner and referral programmes pay out in free-audit credits, not cash.</p>'),
   ('Collector cards', '<p>Every paid audit includes a PDF collector card. Cards are numbered in the order they are issued, starting from #1. Cards #1–100 carry the GENESIS edition mark and cards #101–1000 the FOUNDER mark; editions are assigned only by that order. The foil colour follows the estimated value. A card is a record of your valuation: it <strong>has no monetary value</strong>, cannot be exchanged for cash, cannot be transferred and is not an investment. If you delete your data with <code>/delete</code>, the card is removed from our records and no longer verifies.</p>'),
   ('EU, EEA and UK right of withdrawal', '<p>A paid audit (the valuation result and the PDF collector card) is digital content delivered immediately after payment. In the EU, EEA and UK you normally have a 14-day right of withdrawal for online purchases — <strong>except</strong> when you expressly ask for immediate delivery and acknowledge that you lose that right once delivery starts (Consumer Rights Directive 2011/83/EU, Art. 16(m), and the equivalent UK rules). The bot’s payment invoice says this explicitly: paying there is your request for immediate delivery and your acknowledgement that the withdrawal right ends when your result is delivered. Outside the EU, EEA and UK there is no statutory withdrawal right, and the refund terms below apply.</p>'),
   ('Refunds', '<p>You get an automatic full refund if the AI cannot find a valid game account in your screenshots or a technical error prevents delivery. For any other problem, write to @GameAccountValue_Bot within 7 days. This does not replace the EU, EEA and UK withdrawal right above.</p>'),
   ('AI disclaimer', '<p>Every valuation is an AI-generated estimate for information only — not financial advice, not a guaranteed price and not an offer to buy. GameAccountValue is not affiliated with Roblox Corporation, Supercell, Garena, miHoYo (HoYoverse), Moonton, Epic Games, Mojang or any other game developer.</p>'),
   ('Liability', '<p>Our total liability is limited to the amount you paid in Telegram Stars for the transaction in question. We are not liable for bans or other actions taken by game publishers. This does not limit any liability that cannot be limited by law.</p>'),
   ('Contact', '<p>Service operator: Aleksei Sergeevich Bitkin, independent developer. Questions: <a href="https://t.me/GameAccountValue_Bot">t.me/GameAccountValue_Bot</a></p>'),
  ]},
}}
