"""Privacy policy addition (2026-10-06): the bot's opt-in public leaderboard (/top).
Facts (GameAccountValue_Bot tg_bot/bot.py _top_name / 'top:' callback, core/database.py get_top_scans):
after a paid audit the bot asks — list with the name printed on the card, list with the card number only,
or don't list. Nothing is listed without that choice; /delete removes the entry with the rest of the data.
legal_pages.py appends TOP[lang] to the privacy section 'Your card and its public page' (6th section)."""

TOP = {
 'en': '<p><strong>Public leaderboard (optional).</strong> After a paid audit the bot asks whether to list your card in its <code>/top</code> leaderboard. You choose: with the name printed on your card, with the card number only, or not at all. The entry shows that name or number, the game and the estimated value. Nothing is listed unless you choose to, and <code>/delete</code> removes your entry together with the rest of your data.</p>',
 'ru': '<p><strong>Публичная таблица лидеров (по желанию).</strong> После платного отчёта бот спрашивает, показывать ли твою карту в таблице лидеров <code>/top</code>. Ты выбираешь: с именем, напечатанным на карте, только с номером карты или не показывать вовсе. В записи видны это имя или номер, игра и оценочная стоимость. Без твоего выбора ничего не публикуется, а <code>/delete</code> удаляет запись вместе с остальными данными.</p>',
 'es': '<p><strong>Clasificación pública (opcional).</strong> Tras una auditoría de pago, el bot pregunta si quieres que tu tarjeta aparezca en su clasificación <code>/top</code>. Tú eliges: con el nombre impreso en la tarjeta, solo con el número de la tarjeta o no aparecer. La entrada muestra ese nombre o número, el juego y el valor estimado. No se publica nada sin tu elección, y <code>/delete</code> elimina la entrada junto con el resto de tus datos.</p>',
 'pt': '<p><strong>Ranking público (opcional).</strong> Após uma auditoria paga, o bot pergunta se você quer listar seu cartão no ranking <code>/top</code>. Você escolhe: com o nome impresso no cartão, só com o número do cartão ou não listar. A entrada mostra esse nome ou número, o jogo e o valor estimado. Nada é publicado sem a sua escolha, e <code>/delete</code> remove a entrada junto com o restante dos seus dados.</p>',
 'id': '<p><strong>Papan peringkat publik (opsional).</strong> Setelah audit berbayar, bot bertanya apakah kartumu mau dicantumkan di papan peringkat <code>/top</code>. Kamu yang memilih: dengan nama yang tercetak di kartu, hanya dengan nomor kartu, atau tidak sama sekali. Entri menampilkan nama atau nomor tersebut, game, dan nilai perkiraan. Tidak ada yang dicantumkan tanpa pilihanmu, dan <code>/delete</code> menghapus entri itu bersama data kamu lainnya.</p>',
 'tr': '<p><strong>Herkese açık sıralama (isteğe bağlı).</strong> Ücretli bir incelemeden sonra bot, kartının <code>/top</code> sıralamasında yer alıp almayacağını sorar. Sen seçersin: kartta yazan adla, yalnızca kart numarasıyla ya da hiç listelenmeden. Kayıtta bu ad veya numara, oyun ve tahmini değer görünür. Senin seçimin olmadan hiçbir şey listelenmez; <code>/delete</code> kaydı diğer verilerinle birlikte siler.</p>',
 'ar': '<p><strong>لوحة صدارة عامة (اختيارية).</strong> بعد التقييم المدفوع يسألك البوت هل تريد إدراج بطاقتك في لوحة الصدارة <code>/top</code>. أنت تختار: مع الاسم المطبوع على البطاقة، أو برقم البطاقة فقط، أو عدم الإدراج إطلاقًا. يظهر في الإدخال ذلك الاسم أو الرقم، واللعبة، والقيمة التقديرية. لا يُدرج شيء دون اختيارك، ويحذف الأمر <code>/delete</code> الإدخال مع بقية بياناتك.</p>',
 'vi': '<p><strong>Bảng xếp hạng công khai (tùy chọn).</strong> Sau khi thẩm định trả phí, bot hỏi bạn có muốn đưa thẻ vào bảng xếp hạng <code>/top</code> không. Bạn chọn: kèm tên in trên thẻ, chỉ kèm số thẻ, hoặc không đưa vào. Mục hiển thị tên hoặc số đó, trò chơi và giá trị ước tính. Không có gì được đăng nếu bạn không chọn, và <code>/delete</code> xóa mục này cùng các dữ liệu khác của bạn.</p>',
 'hi': '<p><strong>सार्वजनिक लीडरबोर्ड (वैकल्पिक)।</strong> पेड ऑडिट के बाद बॉट पूछता है कि क्या आपका कार्ड <code>/top</code> लीडरबोर्ड में दिखाया जाए। आप चुनते हैं: कार्ड पर छपे नाम के साथ, सिर्फ़ कार्ड नंबर के साथ, या बिल्कुल नहीं। एंट्री में वह नाम या नंबर, गेम और अनुमानित वैल्यू दिखती है। आपकी पसंद के बिना कुछ भी नहीं दिखाया जाता, और <code>/delete</code> आपके बाकी डेटा के साथ यह एंट्री भी हटा देता है।</p>',
 'fr': '<p><strong>Classement public (facultatif).</strong> Après un audit payant, le bot vous demande si votre carte doit figurer dans son classement <code>/top</code>. Vous choisissez : avec le nom imprimé sur la carte, avec le seul numéro de carte, ou pas du tout. L’entrée affiche ce nom ou ce numéro, le jeu et la valeur estimée. Rien n’est publié sans votre choix, et <code>/delete</code> supprime l’entrée avec le reste de vos données.</p>',
 'de': '<p><strong>Öffentliche Rangliste (freiwillig).</strong> Nach einem kostenpflichtigen Audit fragt der Bot, ob deine Karte in der Rangliste <code>/top</code> erscheinen soll. Du wählst: mit dem auf der Karte gedruckten Namen, nur mit der Kartennummer oder gar nicht. Der Eintrag zeigt diesen Namen oder die Nummer, das Spiel und den geschätzten Wert. Ohne deine Wahl wird nichts veröffentlicht, und <code>/delete</code> löscht den Eintrag zusammen mit deinen übrigen Daten.</p>',
 'it': '<p><strong>Classifica pubblica (facoltativa).</strong> Dopo un audit a pagamento il bot ti chiede se inserire la tua carta nella classifica <code>/top</code>. Scegli tu: con il nome stampato sulla carta, solo con il numero della carta o per niente. La voce mostra quel nome o numero, il gioco e il valore stimato. Senza la tua scelta non viene pubblicato nulla, e <code>/delete</code> elimina la voce insieme al resto dei tuoi dati.</p>',
 'ja': '<p><strong>公開ランキング（任意）。</strong> 有料査定のあと、ボットはあなたのカードを <code>/top</code> ランキングに載せるかどうかを尋ねます。選択肢は「カードに印字された名前で掲載」「カード番号のみで掲載」「掲載しない」です。掲載されるのはその名前または番号、ゲーム名、推定価値です。あなたが選ばない限り何も掲載されず、<code>/delete</code> を使うと他のデータと一緒にこの掲載も削除されます。</p>',
 'ko': '<p><strong>공개 순위표(선택).</strong> 유료 감정 후 봇은 카드를 <code>/top</code> 순위표에 올릴지 묻습니다. 카드에 인쇄된 이름으로, 카드 번호만으로, 또는 올리지 않음 중에서 선택할 수 있습니다. 항목에는 그 이름 또는 번호, 게임, 추정 가치가 표시됩니다. 선택하지 않으면 아무것도 게시되지 않으며, <code>/delete</code>를 사용하면 다른 데이터와 함께 이 항목도 삭제됩니다.</p>',
 'th': '<p><strong>ตารางอันดับสาธารณะ (ไม่บังคับ)</strong> หลังการประเมินแบบชำระเงิน บอทจะถามว่าคุณต้องการให้การ์ดของคุณแสดงในตารางอันดับ <code>/top</code> หรือไม่ คุณเลือกได้ว่าจะแสดงพร้อมชื่อที่พิมพ์บนการ์ด แสดงเฉพาะหมายเลขการ์ด หรือไม่แสดงเลย รายการจะแสดงชื่อหรือหมายเลขนั้น เกม และมูลค่าประมาณ จะไม่มีการแสดงสิ่งใดหากคุณไม่เลือก และคำสั่ง <code>/delete</code> จะลบรายการนี้พร้อมข้อมูลอื่นของคุณ</p>',
 'pl': '<p><strong>Publiczny ranking (opcjonalnie).</strong> Po płatnym audycie bot pyta, czy umieścić Twoją kartę w rankingu <code>/top</code>. Wybierasz: z imieniem wydrukowanym na karcie, tylko z numerem karty albo wcale. Wpis pokazuje to imię lub numer, grę i szacowaną wartość. Bez Twojego wyboru nic nie jest publikowane, a <code>/delete</code> usuwa wpis razem z resztą Twoich danych.</p>',
 'zh': '<p><strong>公开排行榜（可选）。</strong>付费评估完成后，机器人会询问是否将你的卡片列入 <code>/top</code> 排行榜。你可以选择：显示卡片上印的名字、只显示卡片编号，或不列入。条目会显示该名字或编号、游戏和估算价值。未经你的选择不会公开任何内容；使用 <code>/delete</code> 会连同你的其他数据一起删除该条目。</p>',
 'tl': '<p><strong>Pampublikong leaderboard (opsyonal).</strong> Pagkatapos ng bayad na audit, itatanong ng bot kung ilalagay ang card mo sa <code>/top</code> leaderboard. Ikaw ang pipili: kasama ang pangalang nakaimprenta sa card, numero lang ng card, o huwag ilagay. Makikita sa entry ang pangalan o numerong iyon, ang laro at ang tinatayang halaga. Walang ilalagay kung hindi ka pipili, at buburahin ng <code>/delete</code> ang entry kasama ng iba mo pang data.</p>',
 'sw': '<p><strong>Orodha ya wanaoongoza ya umma (hiari).</strong> Baada ya ukaguzi wa kulipia, bot inauliza kama kadi yako iorodheshwe kwenye <code>/top</code>. Wewe unachagua: pamoja na jina lililochapishwa kwenye kadi, kwa namba ya kadi pekee, au isiorodheshwe kabisa. Kipengele kinaonyesha jina au namba hiyo, mchezo na thamani inayokadiriwa. Hakuna kinachoorodheshwa bila chaguo lako, na <code>/delete</code> inafuta kipengele hicho pamoja na data yako nyingine.</p>',
 'ms': '<p><strong>Papan pendahulu awam (pilihan).</strong> Selepas audit berbayar, bot bertanya sama ada kad anda mahu disenaraikan dalam papan pendahulu <code>/top</code>. Anda memilih: dengan nama yang tercetak pada kad, dengan nombor kad sahaja, atau tidak langsung. Entri memaparkan nama atau nombor itu, permainan dan nilai anggaran. Tiada apa-apa disenaraikan tanpa pilihan anda, dan <code>/delete</code> memadam entri itu bersama data anda yang lain.</p>',
 'uz': '<p><strong>Ommaviy reyting (ixtiyoriy).</strong> Pullik tahlildan so‘ng bot kartangizni <code>/top</code> reytingiga qo‘shish-qo‘shmaslikni so‘raydi. Siz tanlaysiz: kartada bosilgan ism bilan, faqat karta raqami bilan yoki umuman qo‘shmaslik. Yozuvda o‘sha ism yoki raqam, o‘yin va taxminiy qiymat ko‘rinadi. Sizning tanlovingizsiz hech narsa e’lon qilinmaydi, <code>/delete</code> esa yozuvni boshqa ma’lumotlaringiz bilan birga o‘chiradi.</p>',
 'kk': '<p><strong>Жария рейтинг (қалауыңыз бойынша).</strong> Ақылы талдаудан кейін бот картаңызды <code>/top</code> рейтингіне қосу-қоспауды сұрайды. Сіз таңдайсыз: картада басылған атпен, тек карта нөмірімен немесе мүлдем қоспау. Жазбада сол ат не нөмір, ойын және болжамды құн көрсетіледі. Сіздің таңдауыңызсыз ештеңе жарияланбайды, ал <code>/delete</code> жазбаны басқа деректеріңізбен бірге жояды.</p>',
 'tk': '<p><strong>Açyk reýting (islegiňize görä).</strong> Tölegli derňewden soň bot kartyňyzy <code>/top</code> reýtingine goşmalymy diýip soraýar. Siz saýlaýarsyňyz: kartada çap edilen at bilen, diňe kartyň belgisi bilen ýa-da asla goşmazlyk. Ýazgyda şol at ýa-da belgi, oýun we çak edilýän baha görkezilýär. Siziň saýlawyňyz bolmasa hiç zat çap edilmeýär, <code>/delete</code> bolsa ýazgyny beýleki maglumatlaryňyz bilen bilelikde pozýar.</p>',
 'ky': '<p><strong>Ачык рейтинг (каалооңуз боюнча).</strong> Акылуу талдоодон кийин бот картаңызды <code>/top</code> рейтингине кошуу-кошпоону сурайт. Сиз тандайсыз: картада басылган ат менен, карта номери менен гана же такыр кошпоо. Жазууда ошол ат же номер, оюн жана болжолдуу нарк көрсөтүлөт. Сиздин тандооңузсуз эч нерсе жарыяланбайт, ал эми <code>/delete</code> жазууну башка маалыматтарыңыз менен кошо өчүрөт.</p>',
}
