# News batch 3: tr, ar, vi, hi (from news_text_b3_en.py, facts unchanged)
TEXT = {
'tr': {'a': {
 'cr-shock': {
  'title': 'Clash Royale Shocktober sezonu: Kahraman Elektro Büyücü ve ücretsiz Elektro Dev Evrimi',
  'desc': 'Shocktober sezonu 6 Ekim – 2 Kasım 2026 arasında: Kahraman Elektro Büyücü yükseltilmiş Pass Royale’de, Elektro Dev Evrimi Albüm Etkinliği ile ücretsiz, yeni rozetler.',
  'lead': 'Supercell, Shocktober sezonunu 5 Ekim 2026’da duyurdu; sezon 6 Ekim’den 2 Kasım’a kadar sürüyor.',
  'new': ['Yeni Kahraman: Elektro Büyücü (Electro Wizard). Surging Strikes yeteneği yakındaki iki düşmanı aynı anda sersemletiyor. Yükseltilmiş Pass Royale’de yer alıyor.',
          'Yeni Evrim: Elektro Dev (Electro Giant). “Shocktober: The Movie!” Albüm Etkinliği (6 Ekim – 2 Kasım, Arena 3’ten itibaren) tamamlanınca ücretsiz açılıyor; etkinlik ayrıca bir ifade ve kule görünümü veriyor.',
          'Rozetler: Spooky Chess liginde (5–19 Ekim) en fazla iki, Power Surge Küresel Turnuvası’nda (20–25 Ekim) bir rozet; her birinde ilk 10.000’e girenlere ek rozet var.',
          '20 Galibiyet Mücadelesi 26 Ekim – 2 Kasım arasında geri dönüyor: 3’ten az yenilgiyle 20 galibiyet bir ifade kazandırıyor.'],
  'impact': 'Her oyuncunun ücretsiz alabildiği bir Evrim, bir hesabı diğerinden pek ayırmaz. İlk 10.000 rozetlerini almak daha zordur ve profilde beceriyi gösterir. Araştırmamıza göre Kral Kulesi seviyesi ve kart seviyeleri ana değer etkenleri olmayı sürdürüyor.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — Ekim’de Portal Pendant ekipmanı ve yeni Kahraman görünümleri',
  'desc': 'Cosmic Curse: Portal Panic 1–31 Ekim 2026 arasında: Minyon Prens için Destansı Ekipman Portal Pendant Madalya Etkinliği’nden (8–25 Ekim), Kahraman görünümleri ve Altın Bilet görünümü.',
  'lead': 'Supercell, Clash-O-Ween sezonu “Cosmic Curse: Portal Panic”i 1 Ekim 2026’da duyurdu; sezon 31 Ekim’e kadar sürüyor.',
  'new': ['Portal Panic Madalya Etkinliği, 8–25 Ekim, Belediye Binası 6 ve üzeri: savaşlarda toplanan Sour Elixir ödülleri ve Rift Medals’ı açıyor; bunlarla Tüccar Dükkânı’ndan Minyon Prens için yeni Destansı Ekipman Portal Pendant alınıyor (dükkân 27 Ekim’e kadar açık).',
          'Altın Bilet, 1–31 Ekim: sezonun özel Kahraman görünümü Shroud Queen, alternatif seçenek Ghost Champion.',
          'Ay boyunca gelen Kahraman görünümleri: Savage King (5 Ekim), Nasty Prince (7 Ekim), Terror Champion (9 Ekim), Behemoth Duke (11 Ekim) ve Spider Warden (13 Ekim); Cosmic Portals XL manzarası 3 Ekim’den itibaren.',
          'Sezon boyunca geçici birlik Totem Thrower oyunda; 2025 Cosmic Curse kozmetikleri 15 Ekim’de geri dönüyor.'],
  'impact': 'Kahraman ekipmanı ve görünümleri hesapta kalır, bu yüzden hesabın gösterdiklerine eklenir. Araştırmamıza göre Belediye Binası seviyesi ve kahramanların o seviye için ne kadar tamamlandığı ana değer etkenleri olmayı sürdürüyor; sezonluk görünümler ikincil bir ayrıntı.'},
 'coc-ore': {
  'title': 'Clash of Clans Cevher için Taş fiyatlarını düşürdü: Yıldızlı Cevher 35’ten 20 Taş’a',
  'desc': 'Supercell 2 Ekim 2026’da Cevher için yeni temel Taş fiyatlarını duyurdu: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Destansı Ekipmanı en üst seviyeye çıkarmak yaklaşık yarı Taş tutuyor.',
  'lead': 'Supercell, 2 Ekim 2026’da Clash of Clans’ta Cevher için Taş fiyatlarının düştüğünü duyurdu; bu geçici bir indirim değil, yeni temel fiyat.',
  'new': ['Yeni fiyatlar: Shiny Ore 1 Taş → 0,5 Taş, Glowy Ore 5 → 3 Taş, Starry Ore 35 → 20 Taş.',
          'Supercell’e göre bir Destansı Ekipmanı en üst seviyeye çıkarmanın Taş maliyeti yaklaşık yarıya iniyor.',
          'Tüccar yeni fiyatları Temmuz’dan beri kullanıyor; Madalya dükkânı Ekim Madalya Etkinliği’nde geçiyor, bir sonraki büyük güncelleme ise bu fiyatları oyunun her yerinde standart yapacak.',
          'Cevher ekonomisiyle ilgili başka değişiklikler Ekim’in ilerleyen günleri için söz verildi.'],
  'impact': 'En üst seviye Kahraman ekipmanına ulaşmak ucuzluyor, bu yüzden yüksek Belediye Binalı hesaplarda daha yaygın hâle gelebilir. Araştırmamıza göre Belediye Binası seviyesi ve kahraman ilerlemesi ana değer etkenleri olmayı sürdürüyor.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: her bölgedeki sekiz takım nasıl belirleniyor',
  'desc': 'Supercell 1 Ekim 2026’da takımların BSC 2027’ye nasıl katılacağını açıkladı: 2026 sıralamasından bölge başına altı doğrudan davet ve 16–17 Ocak 2027’deki BSC Invitational’dan iki kontenjan.',
  'lead': 'Supercell, 1 Ekim 2026’da Brawl Stars Championship 2027’nin eleme yolunu yayımladı.',
  'new': ['BSC 2027’de dört bölgenin her birinde sekiz takım var: APAC, EMEA, Güney Amerika ve Kuzey Amerika.',
          'Her bölgenin 2026 BSC Sıralaması’ndaki ilk altı takım doğrudan davet alıyor ve en fazla bir oyuncu değiştirebiliyor.',
          'Bölge başına son iki kontenjan 16–17 Ocak 2027’deki BSC Invitational’da belirleniyor: 7–10. sıradaki takımlar, EMEA’da ise 7–14. sıradakiler oynuyor.',
          'Davetler 23 Kasım 2026’da gönderiliyor, takımların 20 Aralık’a kadar yanıt vermesi gerekiyor; Supercell tarihlerin değişebileceğini belirtiyor. Yeni takımlar oyun içi Championship Challenge ve Brawl Stars Challengers ile başlıyor.'],
  'impact': 'Espor elemeleri sıradan bir hesabın değerini değiştirmez. Araştırmamıza göre ilanlarda fiyatı hâlâ kupalar, savaşçılar ve Güç Seviyeleri belirliyor.'},
}},
'ar': {'a': {
 'cr-shock': {
  'title': 'موسم Shocktober في Clash Royale: البطل الساحر الكهربائي وتطوّر مجاني للعملاق الكهربائي',
  'desc': 'يمتد موسم Shocktober من 6 أكتوبر إلى 2 نوفمبر 2026: البطل الساحر الكهربائي في Pass Royale المطوَّر، وتطوّر العملاق الكهربائي مجانًا عبر حدث الألبوم، وشارات جديدة.',
  'lead': 'أعلنت Supercell عن موسم Shocktober في 5 أكتوبر 2026؛ ويمتد من 6 أكتوبر إلى 2 نوفمبر.',
  'new': ['بطل جديد: الساحر الكهربائي (Electro Wizard)، وقدرته Surging Strikes تصعق عدوّين قريبين في وقت واحد. وهو متاح في Pass Royale المطوَّر.',
          'تطوّر جديد: العملاق الكهربائي (Electro Giant). يُفتح مجانًا عند إكمال حدث الألبوم «Shocktober: The Movie!» (6 أكتوبر – 2 نوفمبر، من الساحة 3)، ويمنح الحدث أيضًا تعبيرًا ومظهرًا للبرج.',
          'الشارات: حتى شارتين في دوري Spooky Chess (5–19 أكتوبر) وشارة في بطولة Power Surge العالمية (20–25 أكتوبر)، مع شارة إضافية في كلٍّ منهما لمن ينهي ضمن أفضل 10,000.',
          'يعود تحدي 20 فوزًا من 26 أكتوبر إلى 2 نوفمبر: 20 فوزًا بأقل من 3 هزائم مقابل تعبير.'],
  'impact': 'التطوّر الذي يستطيع كل لاعب الحصول عليه مجانًا لا يميّز حسابًا عن آخر إلا قليلًا. أما شارات أفضل 10,000 فهي أصعب وتدل على المهارة في الملف الشخصي. وبحسب بحثنا، يبقى مستوى برج الملك ومستويات البطاقات أهم عوامل القيمة.'},
 'coc-cosmic': {
  'title': 'Clash of Clans، Cosmic Curse: Portal Panic — معدات Portal Pendant ومظاهر أبطال جديدة في أكتوبر',
  'desc': 'يمتد Cosmic Curse: Portal Panic من 1 إلى 31 أكتوبر 2026: المعدات الملحمية Portal Pendant لأمير المينيون من حدث الميداليات (8–25 أكتوبر)، ومظاهر أبطال ومظهر التذكرة الذهبية.',
  'lead': 'أعلنت Supercell عن موسم Clash-O-Ween «Cosmic Curse: Portal Panic» في 1 أكتوبر 2026؛ ويستمر حتى 31 أكتوبر.',
  'new': ['حدث ميداليات Portal Panic، من 8 إلى 25 أكتوبر، لقاعة البلدة 6 فما فوق: Sour Elixir الذي يُجمع في المعارك يفتح مكافآت وRift Medals، وبها تُشترى من متجر التاجر Portal Pendant الجديدة — معدات ملحمية لأمير المينيون (المتجر مفتوح حتى 27 أكتوبر).',
          'التذكرة الذهبية، من 1 إلى 31 أكتوبر: مظهر البطل الحصري للموسم هو Shroud Queen، والخيار البديل Ghost Champion.',
          'مظاهر الأبطال التي تصل خلال الشهر: Savage King (5 أكتوبر)، Nasty Prince (7 أكتوبر)، Terror Champion (9 أكتوبر)، Behemoth Duke (11 أكتوبر) وSpider Warden (13 أكتوبر)؛ ومشهد Cosmic Portals XL من 3 أكتوبر.',
          'تنضم قوة مؤقتة هي Totem Thrower طوال الموسم، وتعود مستحضرات Cosmic Curse لعام 2025 في 15 أكتوبر.'],
  'impact': 'معدات الأبطال ومظاهرهم تبقى في الحساب، ولذلك تضيف إلى ما يُظهره الحساب. وبحسب بحثنا، يبقى مستوى قاعة البلدة ومدى اكتمال الأبطال لذلك المستوى أهم عوامل القيمة؛ أما المظاهر الموسمية فتفصيل ثانوي.'},
 'coc-ore': {
  'title': 'Clash of Clans تخفّض أسعار الخام بالجواهر: الخام النجمي من 35 إلى 20 جوهرة',
  'desc': 'أعلنت Supercell في 2 أكتوبر 2026 أسعارًا أساسية جديدة للخام بالجواهر: Shiny من 1 إلى 0.5، Glowy من 5 إلى 3، Starry من 35 إلى 20. وصار رفع المعدات الملحمية إلى الحد الأقصى يكلّف نحو نصف الجواهر.',
  'lead': 'في 2 أكتوبر 2026 أعلنت Supercell خفض أسعار الخام بالجواهر في Clash of Clans، كسعر أساسي جديد لا كعرض مؤقت.',
  'new': ['الأسعار الجديدة: Shiny Ore من جوهرة واحدة إلى 0.5، Glowy Ore من 5 إلى 3 جواهر، Starry Ore من 35 إلى 20 جوهرة.',
          'تقول Supercell إن تكلفة الجواهر لرفع قطعة من المعدات الملحمية إلى الحد الأقصى تنخفض إلى النصف تقريبًا.',
          'يستخدم التاجر الأسعار الجديدة منذ يوليو؛ ويلحق به متجر الميداليات في حدث ميداليات أكتوبر، ثم يجعلها التحديث الكامل التالي الأسعار المعتمدة في كل اللعبة.',
          'وُعد بتغييرات أخرى في اقتصاد الخام في وقت لاحق من أكتوبر.'],
  'impact': 'يصبح الوصول إلى معدات الأبطال بالحد الأقصى أرخص، ولذلك قد تصير أكثر شيوعًا في حسابات قاعة البلدة العالية. وبحسب بحثنا، يبقى مستوى قاعة البلدة وتقدّم الأبطال أهم عوامل القيمة.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: كيف تُختار الفرق الثمانية في كل منطقة',
  'desc': 'شرحت Supercell في 1 أكتوبر 2026 كيف تصل الفرق إلى BSC 2027: ست دعوات مباشرة لكل منطقة من ترتيب 2026، ومقعدان من BSC Invitational في 16–17 يناير 2027.',
  'lead': 'في 1 أكتوبر 2026 نشرت Supercell مسار التأهل إلى Brawl Stars Championship 2027.',
  'new': ['تضم BSC 2027 ثمانية فرق في كل واحدة من أربع مناطق: APAC وEMEA وأمريكا الجنوبية وأمريكا الشمالية.',
          'أفضل ستة فرق في ترتيب BSC 2026 لكل منطقة تحصل على دعوة مباشرة، ويمكنها تغيير لاعب واحد على الأكثر.',
          'يُحسم المقعدان الأخيران في كل منطقة في BSC Invitational يومي 16–17 يناير 2027: تلعب الفرق من المركز 7 إلى 10، ومن 7 إلى 14 في EMEA.',
          'تُرسل الدعوات في 23 نوفمبر 2026 وعلى الفرق الرد قبل 20 ديسمبر؛ وتشير Supercell إلى أن التواريخ قد تتغير. الفرق الجديدة تبدأ من Championship Challenge داخل اللعبة وBrawl Stars Challengers.'],
  'impact': 'التأهل في الرياضات الإلكترونية لا يغيّر قيمة الحساب العادي. وبحسب بحثنا، ما زالت الكؤوس والمقاتلون ومستويات قوتهم هي ما تُسعَّر عليه الإعلانات.'},
}},
'vi': {'a': {
 'cr-shock': {
  'title': 'Mùa Shocktober của Clash Royale: Hero Electro Wizard và Tiến hóa Electro Giant miễn phí',
  'desc': 'Mùa Shocktober diễn ra từ 6/10 đến 2/11/2026: Hero Electro Wizard trong Pass Royale nâng cấp, Tiến hóa Electro Giant miễn phí qua Sự kiện Album và các huy hiệu mới.',
  'lead': 'Supercell công bố mùa Shocktober ngày 5/10/2026; mùa diễn ra từ 6/10 đến 2/11.',
  'new': ['Hero mới: Electro Wizard, với kỹ năng Surging Strikes làm choáng hai kẻ địch ở gần cùng lúc. Hero này nằm trong Pass Royale nâng cấp.',
          'Tiến hóa mới: Electro Giant. Được mở khóa miễn phí khi hoàn thành Sự kiện Album “Shocktober: The Movie!” (6/10 – 2/11, từ Đấu trường 3); sự kiện còn tặng một biểu cảm và một skin tháp.',
          'Huy hiệu: tối đa hai ở giải Spooky Chess (5–19/10) và một ở Giải đấu Toàn cầu Power Surge (20–25/10); mỗi giải có thêm huy hiệu cho người vào top 10.000.',
          'Thử thách 20 Trận thắng trở lại từ 26/10 đến 2/11: thắng 20 trận với ít hơn 3 trận thua để nhận một biểu cảm.'],
  'impact': 'Một Tiến hóa mà ai cũng nhận miễn phí được thì gần như không làm tài khoản này khác tài khoản kia. Huy hiệu top 10.000 khó lấy hơn và cho thấy kỹ năng trên hồ sơ. Theo nghiên cứu của chúng tôi, cấp King Tower và cấp thẻ bài vẫn là yếu tố giá trị chính.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — trang bị Portal Pendant và skin Hero mới trong tháng 10',
  'desc': 'Cosmic Curse: Portal Panic diễn ra từ 1 đến 31/10/2026: Trang bị Epic Portal Pendant cho Minion Prince từ Sự kiện Huy chương (8–25/10), skin Hero và skin Gold Pass.',
  'lead': 'Supercell công bố mùa Clash-O-Ween “Cosmic Curse: Portal Panic” ngày 1/10/2026; mùa kéo dài đến hết 31/10.',
  'new': ['Sự kiện Huy chương Portal Panic, 8–25/10, từ Town Hall 6: Sour Elixir thu được trong trận mở khóa phần thưởng và Rift Medals, dùng để đổi Portal Pendant mới — Trang bị Epic cho Minion Prince — tại Cửa hàng Thương nhân (mở đến hết 27/10).',
          'Gold Pass, 1–31/10: skin Hero độc quyền của mùa là Shroud Queen, lựa chọn thay thế là Ghost Champion.',
          'Các skin Hero ra mắt trong tháng: Savage King (5/10), Nasty Prince (7/10), Terror Champion (9/10), Behemoth Duke (11/10) và Spider Warden (13/10); Cảnh quan Cosmic Portals XL từ 3/10.',
          'Lính tạm thời Totem Thrower xuất hiện trong mùa này, và các vật phẩm trang trí của Cosmic Curse 2025 quay lại vào 15/10.'],
  'impact': 'Trang bị và skin Hero ở lại trên tài khoản nên bổ sung vào những gì tài khoản thể hiện. Theo nghiên cứu của chúng tôi, cấp Town Hall và mức độ hoàn thiện Hero ở cấp đó vẫn là yếu tố giá trị chính; skin theo mùa chỉ là chi tiết phụ.'},
 'coc-ore': {
  'title': 'Clash of Clans giảm giá Quặng tính bằng Ngọc: Starry Ore từ 35 xuống 20 Ngọc',
  'desc': 'Ngày 2/10/2026 Supercell công bố mức giá cơ bản mới của Quặng tính bằng Ngọc: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Nâng tối đa một Trang bị Epic tốn khoảng một nửa số Ngọc.',
  'lead': 'Ngày 2/10/2026 Supercell công bố giảm giá Quặng tính bằng Ngọc trong Clash of Clans — là mức giá cơ bản mới, không phải khuyến mãi có thời hạn.',
  'new': ['Giá mới: Shiny Ore 1 Ngọc → 0,5 Ngọc, Glowy Ore 5 → 3 Ngọc, Starry Ore 35 → 20 Ngọc.',
          'Supercell cho biết chi phí Ngọc để nâng tối đa một Trang bị Epic giảm khoảng một nửa.',
          'Thương nhân đã dùng giá mới từ tháng 7; cửa hàng Huy chương áp dụng trong Sự kiện Huy chương tháng 10, và bản cập nhật lớn tiếp theo sẽ biến đây thành giá chuẩn ở mọi nơi trong game.',
          'Các thay đổi khác về kinh tế Quặng được hứa sẽ đến vào cuối tháng 10.'],
  'impact': 'Trang bị Hero cấp tối đa trở nên rẻ hơn để đạt được, nên có thể phổ biến hơn ở các tài khoản Town Hall cao. Theo nghiên cứu của chúng tôi, cấp Town Hall và tiến độ Hero vẫn là yếu tố giá trị chính.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: tám đội mỗi khu vực được chọn như thế nào',
  'desc': 'Ngày 1/10/2026 Supercell giải thích cách các đội vào BSC 2027: sáu suất mời trực tiếp mỗi khu vực theo bảng xếp hạng 2026 và hai suất từ BSC Invitational ngày 16–17/1/2027.',
  'lead': 'Ngày 1/10/2026 Supercell công bố lộ trình vòng loại của Brawl Stars Championship 2027.',
  'new': ['BSC 2027 có tám đội ở mỗi khu vực trong bốn khu vực: APAC, EMEA, Nam Mỹ và Bắc Mỹ.',
          'Sáu đội đứng đầu Bảng xếp hạng BSC 2026 của mỗi khu vực được mời trực tiếp và chỉ được thay tối đa một tuyển thủ.',
          'Hai suất cuối của mỗi khu vực được quyết định tại BSC Invitational ngày 16–17/1/2027: các đội hạng 7–10 thi đấu, riêng EMEA là hạng 7–14.',
          'Thư mời được gửi ngày 23/11/2026 và các đội phải trả lời trước 20/12; Supercell lưu ý các ngày này có thể thay đổi. Đội mới bắt đầu từ Championship Challenge trong game và Brawl Stars Challengers.'],
  'impact': 'Vòng loại esports không làm thay đổi giá trị của một tài khoản thông thường. Theo nghiên cứu của chúng tôi, cúp, brawler và Cấp Sức mạnh của họ vẫn là căn cứ định giá trong các tin đăng.'},
}},
'hi': {'a': {
 'cr-shock': {
  'title': 'Clash Royale का Shocktober सीज़न: हीरो Electro Wizard और मुफ़्त Electro Giant इवोल्यूशन',
  'desc': 'Shocktober सीज़न 6 अक्टूबर से 2 नवंबर 2026 तक चलता है: अपग्रेडेड Pass Royale में हीरो Electro Wizard, एल्बम इवेंट से मुफ़्त Electro Giant इवोल्यूशन और नए बैज।',
  'lead': 'Supercell ने 5 अक्टूबर 2026 को Shocktober सीज़न की घोषणा की; यह 6 अक्टूबर से 2 नवंबर तक चलता है।',
  'new': ['नया हीरो: Electro Wizard, जिसकी Surging Strikes क्षमता पास के दो दुश्मनों को एक साथ स्टन करती है। यह अपग्रेडेड Pass Royale में है।',
          'नया इवोल्यूशन: Electro Giant। एल्बम इवेंट “Shocktober: The Movie!” (6 अक्टूबर – 2 नवंबर, एरीना 3 से) पूरा करने पर यह मुफ़्त मिलता है; इवेंट से एक इमोट और टावर स्किन भी मिलती है।',
          'बैज: Spooky Chess लीग (5–19 अक्टूबर) में दो तक और Power Surge ग्लोबल टूर्नामेंट (20–25 अक्टूबर) में एक; दोनों में टॉप 10,000 में आने पर एक अतिरिक्त बैज।',
          '20-विन चैलेंज 26 अक्टूबर से 2 नवंबर तक लौट रहा है: 3 से कम हार के साथ 20 जीत पर एक इमोट मिलता है।'],
  'impact': 'जो इवोल्यूशन हर खिलाड़ी मुफ़्त में पा सकता है, वह एक अकाउंट को दूसरे से ज़्यादा अलग नहीं करता। टॉप 10,000 के बैज पाना कठिन है और वे प्रोफ़ाइल पर कौशल दिखाते हैं। हमारी रिसर्च में King Tower का लेवल और कार्ड लेवल ही वैल्यू के मुख्य कारक बने हुए हैं।'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — अक्टूबर में Portal Pendant इक्विपमेंट और नई हीरो स्किन',
  'desc': 'Cosmic Curse: Portal Panic 1 से 31 अक्टूबर 2026 तक चलता है: मेडल इवेंट (8–25 अक्टूबर) से Minion Prince के लिए एपिक इक्विपमेंट Portal Pendant, हीरो स्किन और Gold Pass स्किन।',
  'lead': 'Supercell ने 1 अक्टूबर 2026 को Clash-O-Ween सीज़न “Cosmic Curse: Portal Panic” की घोषणा की; यह 31 अक्टूबर तक चलता है।',
  'new': ['Portal Panic मेडल इवेंट, 8–25 अक्टूबर, Town Hall 6 और ऊपर: लड़ाइयों में जुटाया गया Sour Elixir इनाम और Rift Medals खोलता है, जिनसे Trader Shop में नया Portal Pendant — Minion Prince के लिए एपिक इक्विपमेंट — मिलता है (दुकान 27 अक्टूबर तक खुली है)।',
          'Gold Pass, 1–31 अक्टूबर: सीज़न की एक्सक्लूसिव हीरो स्किन Shroud Queen है, वैकल्पिक विकल्प Ghost Champion।',
          'महीने भर में आने वाली हीरो स्किन: Savage King (5 अक्टूबर), Nasty Prince (7 अक्टूबर), Terror Champion (9 अक्टूबर), Behemoth Duke (11 अक्टूबर) और Spider Warden (13 अक्टूबर); Cosmic Portals XL सीनरी 3 अक्टूबर से।',
          'सीज़न के लिए अस्थायी ट्रूप Totem Thrower जुड़ा है, और 2025 के Cosmic Curse कॉस्मेटिक्स 15 अक्टूबर को लौटते हैं।'],
  'impact': 'हीरो इक्विपमेंट और हीरो स्किन अकाउंट पर ही रहते हैं, इसलिए अकाउंट जो दिखाता है उसमें जुड़ते हैं। हमारी रिसर्च में Town Hall का लेवल और उस लेवल के लिए हीरो कितने पूरे हैं, यही वैल्यू के मुख्य कारक हैं; सीज़नल स्किन एक गौण बात है।'},
 'coc-ore': {
  'title': 'Clash of Clans ने Ore के Gem दाम घटाए: Starry Ore 35 से 20 Gems',
  'desc': 'Supercell ने 2 अक्टूबर 2026 को Ore के नए बेस Gem दाम घोषित किए: Shiny 1 → 0.5, Glowy 5 → 3, Starry 35 → 20। एपिक इक्विपमेंट को मैक्स करने में लगभग आधे Gems लगते हैं।',
  'lead': '2 अक्टूबर 2026 को Supercell ने Clash of Clans में Ore के Gem दाम घटाने की घोषणा की — सीमित समय की सेल नहीं, बल्कि नया बेस दाम।',
  'new': ['नए दाम: Shiny Ore 1 Gem → 0.5 Gem, Glowy Ore 5 → 3 Gems, Starry Ore 35 → 20 Gems।',
          'Supercell के अनुसार एक एपिक इक्विपमेंट को मैक्स करने की Gem लागत लगभग आधी हो जाती है।',
          'Trader जुलाई से नए दाम इस्तेमाल कर रहा है; मेडल शॉप अक्टूबर के मेडल इवेंट में इन्हें अपनाएगी, और अगला पूरा अपडेट इन्हें गेम में हर जगह मानक बना देगा।',
          'Ore इकॉनमी में और बदलाव अक्टूबर में आगे आने का वादा किया गया है।'],
  'impact': 'मैक्स हीरो इक्विपमेंट तक पहुँचना सस्ता हो जाता है, इसलिए ऊँचे Town Hall वाले अकाउंट पर यह ज़्यादा आम हो सकता है। हमारी रिसर्च में Town Hall का लेवल और हीरो की प्रगति ही वैल्यू के मुख्य कारक बने हुए हैं।'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: हर रीजन की आठ टीमें कैसे चुनी जाती हैं',
  'desc': 'Supercell ने 1 अक्टूबर 2026 को बताया कि टीमें BSC 2027 में कैसे पहुँचती हैं: 2026 की लीडरबोर्ड से हर रीजन में छह सीधे निमंत्रण और 16–17 जनवरी 2027 के BSC Invitational से दो स्थान।',
  'lead': '1 अक्टूबर 2026 को Supercell ने Brawl Stars Championship 2027 का क्वालिफ़िकेशन रास्ता प्रकाशित किया।',
  'new': ['BSC 2027 में चार रीजन में से हर एक में आठ टीमें हैं: APAC, EMEA, दक्षिण अमेरिका और उत्तरी अमेरिका।',
          'हर रीजन की 2026 BSC लीडरबोर्ड की शीर्ष छह टीमों को सीधा निमंत्रण मिलता है और वे ज़्यादा से ज़्यादा एक खिलाड़ी बदल सकती हैं।',
          'हर रीजन के आख़िरी दो स्थान 16–17 जनवरी 2027 के BSC Invitational में तय होते हैं: 7वें से 10वें स्थान की टीमें खेलती हैं, और EMEA में 7वें से 14वें।',
          'निमंत्रण 23 नवंबर 2026 को भेजे जाते हैं और टीमों को 20 दिसंबर तक जवाब देना है; Supercell के अनुसार तारीख़ें बदल सकती हैं। नई टीमें इन-गेम Championship Challenge और Brawl Stars Challengers से शुरू करती हैं।'],
  'impact': 'ईस्पोर्ट्स क्वालिफ़िकेशन से किसी सामान्य अकाउंट की क़ीमत नहीं बदलती। हमारी रिसर्च में लिस्टिंग के दाम अब भी ट्रॉफ़ी, ब्रॉलर और उनके Power Level पर तय होते हैं।'},
}},
}
