# News batch 3: fr, de, it, pl (from news_text_b3_en.py, facts unchanged)
TEXT = {
'fr': {'a': {
 'cr-shock': {
  'title': 'Saison Shocktober de Clash Royale : Héros Électro-sorcier et Évolution gratuite de l’Électro-géant',
  'desc': 'La saison Shocktober dure du 6 octobre au 2 novembre 2026 : Héros Électro-sorcier dans le Pass Royale amélioré, Évolution de l’Électro-géant gratuite via l’événement Album, nouveaux badges.',
  'lead': 'Supercell a annoncé la saison Shocktober le 5 octobre 2026 ; elle dure du 6 octobre au 2 novembre.',
  'new': ['Nouveau Héros : l’Électro-sorcier (Electro Wizard), dont la capacité Surging Strikes étourdit deux ennemis proches à la fois. Il se trouve dans le Pass Royale amélioré.',
          'Nouvelle Évolution : l’Électro-géant (Electro Giant). Elle se débloque gratuitement en terminant l’événement Album « Shocktober: The Movie! » (6 octobre – 2 novembre, à partir de l’Arène 3), qui donne aussi une emote et une apparence de tour.',
          'Badges : jusqu’à deux dans la ligue Spooky Chess (5–19 octobre) et un dans le Tournoi mondial Power Surge (20–25 octobre), avec à chaque fois un badge supplémentaire pour une place dans le top 10 000.',
          'Le Défi des 20 victoires revient du 26 octobre au 2 novembre : 20 victoires avec moins de 3 défaites pour une emote.'],
  'impact': 'Une Évolution que tout joueur peut obtenir gratuitement ne distingue guère un compte d’un autre. Les badges du top 10 000 sont plus difficiles à obtenir et montrent le niveau du joueur sur le profil. D’après nos recherches, le niveau de la Tour du Roi et le niveau des cartes restent les principaux facteurs de valeur.'},
 'coc-cosmic': {
  'title': 'Clash of Clans, Cosmic Curse: Portal Panic — équipement Portal Pendant et nouvelles apparences de héros en octobre',
  'desc': 'Cosmic Curse: Portal Panic dure du 1er au 31 octobre 2026 : l’équipement épique Portal Pendant pour le Prince gargouille via l’événement à médailles (8–25 octobre), des apparences de héros et celle du Pass Or.',
  'lead': 'Supercell a annoncé la saison Clash-O-Ween « Cosmic Curse: Portal Panic » le 1er octobre 2026 ; elle dure jusqu’au 31 octobre.',
  'new': ['Événement à médailles Portal Panic, du 8 au 25 octobre, à partir de l’Hôtel de ville 6 : le Sour Elixir récolté en combat débloque des récompenses et des Rift Medals, qui permettent d’acheter chez le Marchand le nouveau Portal Pendant, équipement épique pour le Prince gargouille (boutique ouverte jusqu’au 27 octobre).',
          'Pass Or, du 1er au 31 octobre : l’apparence de héros exclusive de la saison est Shroud Queen, avec Ghost Champion en option alternative.',
          'Apparences de héros arrivant au fil du mois : Savage King (5 octobre), Nasty Prince (7 octobre), Terror Champion (9 octobre), Behemoth Duke (11 octobre) et Spider Warden (13 octobre) ; le décor Cosmic Portals XL à partir du 3 octobre.',
          'Une troupe temporaire, Totem Thrower, rejoint la saison, et les cosmétiques du Cosmic Curse 2025 reviennent le 15 octobre.'],
  'impact': 'Les équipements et les apparences de héros restent sur le compte : ils s’ajoutent donc à ce que le compte montre. D’après nos recherches, le niveau de l’Hôtel de ville et le degré d’avancement des héros pour ce niveau restent les principaux facteurs de valeur ; les apparences saisonnières sont un détail secondaire.'},
 'coc-ore': {
  'title': 'Clash of Clans baisse le prix des minerais en gemmes : le minerai étoilé passe de 35 à 20 gemmes',
  'desc': 'Supercell a annoncé le 2 octobre 2026 de nouveaux prix de base des minerais en gemmes : Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Monter un équipement épique au maximum coûte environ deux fois moins de gemmes.',
  'lead': 'Le 2 octobre 2026, Supercell a annoncé une baisse du prix des minerais en gemmes dans Clash of Clans — comme nouveau prix de base, pas comme promotion temporaire.',
  'new': ['Nouveaux prix : Shiny Ore 1 gemme → 0,5 gemme, Glowy Ore 5 → 3 gemmes, Starry Ore 35 → 20 gemmes.',
          'Selon Supercell, le coût en gemmes pour monter un équipement épique au maximum baisse d’environ la moitié.',
          'Le Marchand applique les nouveaux prix depuis juillet ; la boutique de médailles suit lors de l’événement à médailles d’octobre, et la prochaine mise à jour complète en fera le prix standard partout dans le jeu.',
          'D’autres changements de l’économie des minerais sont promis plus tard en octobre.'],
  'impact': 'Un équipement de héros au maximum devient moins cher à atteindre ; il pourrait donc devenir plus courant sur les comptes à Hôtel de ville élevé. D’après nos recherches, le niveau de l’Hôtel de ville et la progression des héros restent les principaux facteurs de valeur.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027 : comment sont choisies les huit équipes de chaque région',
  'desc': 'Supercell a expliqué le 1er octobre 2026 comment les équipes accèdent au BSC 2027 : six invitations directes par région d’après le classement 2026 et deux places via le BSC Invitational des 16–17 janvier 2027.',
  'lead': 'Le 1er octobre 2026, Supercell a publié le parcours de qualification du Brawl Stars Championship 2027.',
  'new': ['Le BSC 2027 compte huit équipes dans chacune des quatre régions : APAC, EMEA, Amérique du Sud et Amérique du Nord.',
          'Les six meilleures équipes du classement BSC 2026 de chaque région reçoivent une invitation directe et peuvent changer au maximum un joueur.',
          'Les deux dernières places par région se jouent au BSC Invitational les 16–17 janvier 2027 : les équipes classées de la 7e à la 10e place y participent, et de la 7e à la 14e en EMEA.',
          'Les invitations partent le 23 novembre 2026 et les équipes doivent répondre avant le 20 décembre ; Supercell précise que les dates peuvent changer. Les nouvelles équipes commencent par le Championship Challenge en jeu et les Brawl Stars Challengers.'],
  'impact': 'La qualification esport ne change pas la valeur d’un compte ordinaire. D’après nos recherches, les trophées, les brawlers et leurs niveaux de puissance restent ce sur quoi les annonces sont tarifées.'},
}},
'de': {'a': {
 'cr-shock': {
  'title': 'Clash Royale Shocktober-Saison: Held Elektromagier und kostenlose Elektroriese-Evolution',
  'desc': 'Die Shocktober-Saison läuft vom 6. Oktober bis 2. November 2026: Held Elektromagier im verbesserten Pass Royale, Elektroriese-Evolution kostenlos über das Album-Event, neue Abzeichen.',
  'lead': 'Supercell hat die Shocktober-Saison am 5. Oktober 2026 angekündigt; sie läuft vom 6. Oktober bis 2. November.',
  'new': ['Neuer Held: Elektromagier (Electro Wizard). Seine Fähigkeit Surging Strikes betäubt zwei nahe Gegner gleichzeitig. Er ist im verbesserten Pass Royale enthalten.',
          'Neue Evolution: Elektroriese (Electro Giant). Sie wird kostenlos freigeschaltet, wenn man das Album-Event „Shocktober: The Movie!“ (6. Oktober – 2. November, ab Arena 3) abschließt; dazu gibt es ein Emote und einen Turm-Skin.',
          'Abzeichen: bis zu zwei in der Liga Spooky Chess (5.–19. Oktober) und eines im Globalen Turnier Power Surge (20.–25. Oktober), jeweils mit einem zusätzlichen Abzeichen für einen Platz unter den besten 10.000.',
          'Die 20-Siege-Herausforderung kehrt vom 26. Oktober bis 2. November zurück: 20 Siege bei weniger als 3 Niederlagen bringen ein Emote.'],
  'impact': 'Eine Evolution, die jeder Spieler kostenlos bekommen kann, hebt ein Konto kaum von anderen ab. Abzeichen für die besten 10.000 sind schwerer zu erreichen und zeigen im Profil Können. Nach unserer Recherche bleiben das Level des Königsturms und die Kartenlevel die wichtigsten Wertfaktoren.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — Ausrüstung Portal Pendant und neue Helden-Skins im Oktober',
  'desc': 'Cosmic Curse: Portal Panic läuft vom 1. bis 31. Oktober 2026: die epische Ausrüstung Portal Pendant für den Lakaienprinzen aus dem Medaillen-Event (8.–25. Oktober), Helden-Skins und ein Gold-Pass-Skin.',
  'lead': 'Supercell hat die Clash-O-Ween-Saison „Cosmic Curse: Portal Panic“ am 1. Oktober 2026 angekündigt; sie läuft bis zum 31. Oktober.',
  'new': ['Medaillen-Event Portal Panic, 8.–25. Oktober, ab Rathaus 6: In Kämpfen gesammeltes Sour Elixir schaltet Belohnungen und Rift Medals frei, mit denen man im Händler-Shop das neue Portal Pendant kauft — epische Ausrüstung für den Lakaienprinzen (Shop bis 27. Oktober geöffnet).',
          'Gold-Pass, 1.–31. Oktober: Der exklusive Helden-Skin der Saison ist Shroud Queen, die Alternative ist Ghost Champion.',
          'Helden-Skins im Lauf des Monats: Savage King (5. Oktober), Nasty Prince (7. Oktober), Terror Champion (9. Oktober), Behemoth Duke (11. Oktober) und Spider Warden (13. Oktober); die Szenerie Cosmic Portals XL ab 3. Oktober.',
          'Für die Saison kommt die temporäre Truppe Totem Thrower dazu, und die Kosmetik-Items der Cosmic Curse 2025 kehren am 15. Oktober zurück.'],
  'impact': 'Helden-Ausrüstung und Helden-Skins bleiben auf dem Konto und ergänzen damit, was ein Konto vorzeigt. Nach unserer Recherche bleiben das Rathaus-Level und der Ausbaustand der Helden für dieses Level die wichtigsten Wertfaktoren; saisonale Skins sind ein Nebendetail.'},
 'coc-ore': {
  'title': 'Clash of Clans senkt die Juwelenpreise für Erz: Sternenerz von 35 auf 20 Juwelen',
  'desc': 'Supercell hat am 2. Oktober 2026 neue Basis-Juwelenpreise für Erz angekündigt: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Epische Ausrüstung zu maximieren kostet etwa halb so viele Juwelen.',
  'lead': 'Am 2. Oktober 2026 hat Supercell niedrigere Juwelenpreise für Erz in Clash of Clans angekündigt — als neuen Basispreis, nicht als befristetes Angebot.',
  'new': ['Neue Preise: Shiny Ore 1 Juwel → 0,5 Juwelen, Glowy Ore 5 → 3 Juwelen, Starry Ore 35 → 20 Juwelen.',
          'Laut Supercell sinken die Juwelenkosten, um ein Teil epischer Ausrüstung zu maximieren, um ungefähr die Hälfte.',
          'Der Händler nutzt die neuen Preise seit Juli; der Medaillen-Shop folgt im Medaillen-Event im Oktober, und das nächste große Update macht sie überall im Spiel zum Standard.',
          'Weitere Änderungen an der Erz-Ökonomie sind für später im Oktober angekündigt.'],
  'impact': 'Maximierte Helden-Ausrüstung wird günstiger erreichbar und könnte daher auf Konten mit hohem Rathaus häufiger werden. Nach unserer Recherche bleiben das Rathaus-Level und der Heldenfortschritt die wichtigsten Wertfaktoren.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: So werden die acht Teams pro Region bestimmt',
  'desc': 'Supercell hat am 1. Oktober 2026 erklärt, wie Teams in die BSC 2027 kommen: sechs Direkteinladungen pro Region aus der Rangliste 2026 und zwei Plätze über das BSC Invitational am 16.–17. Januar 2027.',
  'lead': 'Am 1. Oktober 2026 hat Supercell den Qualifikationsweg für die Brawl Stars Championship 2027 veröffentlicht.',
  'new': ['Die BSC 2027 hat acht Teams in jeder der vier Regionen: APAC, EMEA, Südamerika und Nordamerika.',
          'Die sechs besten Teams der BSC-Rangliste 2026 jeder Region erhalten eine Direkteinladung und dürfen höchstens einen Spieler wechseln.',
          'Die letzten zwei Plätze pro Region werden beim BSC Invitational am 16.–17. Januar 2027 vergeben: Es spielen die Teams auf den Plätzen 7–10, in EMEA die Plätze 7–14.',
          'Die Einladungen gehen am 23. November 2026 raus, Teams müssen bis 20. Dezember antworten; Supercell weist darauf hin, dass sich die Termine ändern können. Neue Teams starten über die Championship Challenge im Spiel und Brawl Stars Challengers.'],
  'impact': 'Die E-Sport-Qualifikation ändert nichts am Wert eines normalen Kontos. Nach unserer Recherche richten sich die Preise in Angeboten weiterhin nach Trophäen, Brawlern und deren Powerleveln.'},
}},
'it': {'a': {
 'cr-shock': {
  'title': 'Stagione Shocktober di Clash Royale: Eroe Stregone elettrico ed Evoluzione gratuita del Gigante elettrico',
  'desc': 'La stagione Shocktober dura dal 6 ottobre al 2 novembre 2026: Eroe Stregone elettrico nel Pass Royale potenziato, Evoluzione del Gigante elettrico gratis con l’evento Album, nuovi distintivi.',
  'lead': 'Supercell ha annunciato la stagione Shocktober il 5 ottobre 2026; dura dal 6 ottobre al 2 novembre.',
  'new': ['Nuovo Eroe: Stregone elettrico (Electro Wizard), la cui abilità Surging Strikes stordisce due nemici vicini contemporaneamente. Si trova nel Pass Royale potenziato.',
          'Nuova Evoluzione: Gigante elettrico (Electro Giant). Si sblocca gratis completando l’evento Album “Shocktober: The Movie!” (6 ottobre – 2 novembre, dall’Arena 3), che dà anche un’emote e un aspetto della torre.',
          'Distintivi: fino a due nella lega Spooky Chess (5–19 ottobre) e uno nel Torneo globale Power Surge (20–25 ottobre), ciascuno con un distintivo extra per chi chiude tra i primi 10.000.',
          'La Sfida delle 20 vittorie torna dal 26 ottobre al 2 novembre: 20 vittorie con meno di 3 sconfitte per un’emote.'],
  'impact': 'Un’Evoluzione che ogni giocatore può ottenere gratis distingue poco un account da un altro. I distintivi per i primi 10.000 sono più difficili da ottenere e mostrano abilità sul profilo. Secondo la nostra ricerca, il livello della Torre del Re e il livello delle carte restano i principali fattori di valore.'},
 'coc-cosmic': {
  'title': 'Clash of Clans, Cosmic Curse: Portal Panic — equipaggiamento Portal Pendant e nuovi aspetti degli eroi a ottobre',
  'desc': 'Cosmic Curse: Portal Panic dura dal 1º al 31 ottobre 2026: l’equipaggiamento epico Portal Pendant per il Principe sgherro dall’evento medaglie (8–25 ottobre), aspetti degli eroi e un aspetto del Pass oro.',
  'lead': 'Supercell ha annunciato la stagione di Clash-O-Ween “Cosmic Curse: Portal Panic” il 1º ottobre 2026; dura fino al 31 ottobre.',
  'new': ['Evento medaglie Portal Panic, 8–25 ottobre, dal Municipio 6: il Sour Elixir raccolto in battaglia sblocca ricompense e Rift Medals, con cui si compra nel negozio del Mercante il nuovo Portal Pendant, equipaggiamento epico per il Principe sgherro (negozio aperto fino al 27 ottobre).',
          'Pass oro, 1–31 ottobre: l’aspetto eroe esclusivo della stagione è Shroud Queen, con Ghost Champion come alternativa.',
          'Aspetti degli eroi in arrivo nel mese: Savage King (5 ottobre), Nasty Prince (7 ottobre), Terror Champion (9 ottobre), Behemoth Duke (11 ottobre) e Spider Warden (13 ottobre); lo scenario Cosmic Portals XL dal 3 ottobre.',
          'Per la stagione arriva una truppa temporanea, Totem Thrower, e i cosmetici della Cosmic Curse 2025 tornano il 15 ottobre.'],
  'impact': 'Equipaggiamenti e aspetti degli eroi restano sull’account, quindi si aggiungono a ciò che l’account mostra. Secondo la nostra ricerca, il livello del Municipio e quanto sono completi gli eroi per quel livello restano i principali fattori di valore; gli aspetti stagionali sono un dettaglio secondario.'},
 'coc-ore': {
  'title': 'Clash of Clans abbassa i prezzi in gemme dei minerali: il minerale stellare passa da 35 a 20 gemme',
  'desc': 'Supercell ha annunciato il 2 ottobre 2026 nuovi prezzi base in gemme per i minerali: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Portare al massimo un equipaggiamento epico costa circa la metà delle gemme.',
  'lead': 'Il 2 ottobre 2026 Supercell ha annunciato prezzi in gemme più bassi per i minerali in Clash of Clans, come nuovo prezzo base e non come offerta a tempo.',
  'new': ['Nuovi prezzi: Shiny Ore 1 gemma → 0,5 gemme, Glowy Ore 5 → 3 gemme, Starry Ore 35 → 20 gemme.',
          'Secondo Supercell, il costo in gemme per portare al massimo un equipaggiamento epico scende all’incirca della metà.',
          'Il Mercante usa i nuovi prezzi da luglio; il negozio delle medaglie si adegua nell’evento medaglie di ottobre e il prossimo aggiornamento completo li renderà standard in tutto il gioco.',
          'Altre modifiche all’economia dei minerali sono promesse più avanti a ottobre.'],
  'impact': 'L’equipaggiamento degli eroi al massimo diventa meno costoso da raggiungere, quindi potrebbe diventare più comune sugli account con Municipio alto. Secondo la nostra ricerca, il livello del Municipio e i progressi degli eroi restano i principali fattori di valore.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: come vengono scelte le otto squadre di ogni regione',
  'desc': 'Supercell ha spiegato il 1º ottobre 2026 come le squadre arrivano al BSC 2027: sei inviti diretti per regione dalla classifica 2026 e due posti dal BSC Invitational del 16–17 gennaio 2027.',
  'lead': 'Il 1º ottobre 2026 Supercell ha pubblicato il percorso di qualificazione al Brawl Stars Championship 2027.',
  'new': ['Il BSC 2027 ha otto squadre in ciascuna delle quattro regioni: APAC, EMEA, Sud America e Nord America.',
          'Le prime sei squadre della classifica BSC 2026 di ogni regione ricevono un invito diretto e possono cambiare al massimo un giocatore.',
          'Gli ultimi due posti per regione si decidono al BSC Invitational del 16–17 gennaio 2027: giocano le squadre dal 7º al 10º posto, e dal 7º al 14º in EMEA.',
          'Gli inviti partono il 23 novembre 2026 e le squadre devono rispondere entro il 20 dicembre; Supercell precisa che le date possono cambiare. Le nuove squadre partono dal Championship Challenge in gioco e dai Brawl Stars Challengers.'],
  'impact': 'La qualificazione esport non cambia il valore di un account normale. Secondo la nostra ricerca, trofei, brawler e i loro livelli di potenza restano ciò su cui si basano i prezzi degli annunci.'},
}},
'pl': {'a': {
 'cr-shock': {
  'title': 'Sezon Shocktober w Clash Royale: Bohater Electro Wizard i darmowa Ewolucja Electro Giant',
  'desc': 'Sezon Shocktober trwa od 6 października do 2 listopada 2026 r.: Bohater Electro Wizard w ulepszonym Pass Royale, Ewolucja Electro Giant za darmo w wydarzeniu albumowym, nowe odznaki.',
  'lead': 'Supercell ogłosił sezon Shocktober 5 października 2026 r.; trwa on od 6 października do 2 listopada.',
  'new': ['Nowy Bohater: Electro Wizard, którego zdolność Surging Strikes ogłusza jednocześnie dwóch pobliskich wrogów. Jest dostępny w ulepszonym Pass Royale.',
          'Nowa Ewolucja: Electro Giant. Odblokowuje się ją za darmo po ukończeniu wydarzenia albumowego „Shocktober: The Movie!” (6 października – 2 listopada, od Areny 3), które daje też emotkę i skórkę wieży.',
          'Odznaki: do dwóch w lidze Spooky Chess (5–19 października) i jedna w Turnieju Globalnym Power Surge (20–25 października), w każdym z dodatkową odznaką za miejsce w najlepszych 10 000.',
          'Wyzwanie 20 zwycięstw wraca od 26 października do 2 listopada: 20 zwycięstw przy mniej niż 3 porażkach daje emotkę.'],
  'impact': 'Ewolucja, którą każdy gracz może zdobyć za darmo, niewiele odróżnia jedno konto od drugiego. Odznaki za najlepsze 10 000 są trudniejsze do zdobycia i pokazują umiejętności w profilu. Według naszych badań głównymi czynnikami wartości pozostają poziom Wieży Króla i poziomy kart.'},
 'coc-cosmic': {
  'title': 'Clash of Clans, Cosmic Curse: Portal Panic — wyposażenie Portal Pendant i nowe skórki bohaterów w październiku',
  'desc': 'Cosmic Curse: Portal Panic trwa od 1 do 31 października 2026 r.: epickie wyposażenie Portal Pendant dla Księcia Sługusów z wydarzenia medalowego (8–25 października), skórki bohaterów i skórka Złotej Przepustki.',
  'lead': 'Supercell ogłosił sezon Clash-O-Ween „Cosmic Curse: Portal Panic” 1 października 2026 r.; trwa on do 31 października.',
  'new': ['Wydarzenie medalowe Portal Panic, 8–25 października, od Ratusza 6: Sour Elixir zbierany w bitwach odblokowuje nagrody i Rift Medals, za które w sklepie Handlarza kupuje się nowy Portal Pendant — epickie wyposażenie dla Księcia Sługusów (sklep otwarty do 27 października).',
          'Złota Przepustka, 1–31 października: ekskluzywną skórką bohatera w tym sezonie jest Shroud Queen, a alternatywą Ghost Champion.',
          'Skórki bohaterów pojawiające się w ciągu miesiąca: Savage King (5 października), Nasty Prince (7 października), Terror Champion (9 października), Behemoth Duke (11 października) i Spider Warden (13 października); sceneria Cosmic Portals XL od 3 października.',
          'Na czas sezonu dochodzi tymczasowa jednostka Totem Thrower, a kosmetyki z Cosmic Curse 2025 wracają 15 października.'],
  'impact': 'Wyposażenie i skórki bohaterów zostają na koncie, więc dokładają się do tego, co konto pokazuje. Według naszych badań głównymi czynnikami wartości pozostają poziom Ratusza i to, jak rozwinięci są bohaterowie na tym poziomie; sezonowe skórki to szczegół drugorzędny.'},
 'coc-ore': {
  'title': 'Clash of Clans obniża ceny rudy w klejnotach: gwiezdna ruda z 35 do 20 klejnotów',
  'desc': 'Supercell ogłosił 2 października 2026 r. nowe bazowe ceny rudy w klejnotach: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Maksymalne ulepszenie epickiego wyposażenia kosztuje mniej więcej połowę klejnotów.',
  'lead': '2 października 2026 r. Supercell ogłosił niższe ceny rudy w klejnotach w Clash of Clans — jako nową cenę bazową, a nie czasową promocję.',
  'new': ['Nowe ceny: Shiny Ore 1 klejnot → 0,5 klejnotu, Glowy Ore 5 → 3 klejnoty, Starry Ore 35 → 20 klejnotów.',
          'Według Supercell koszt w klejnotach maksymalnego ulepszenia jednego epickiego wyposażenia spada mniej więcej o połowę.',
          'Handlarz stosuje nowe ceny od lipca; sklep medalowy przejdzie na nie w październikowym wydarzeniu medalowym, a następna pełna aktualizacja uczyni je standardem w całej grze.',
          'Kolejne zmiany w ekonomii rudy zapowiedziano na dalszą część października.'],
  'impact': 'Maksymalnie ulepszone wyposażenie bohaterów staje się tańsze do zdobycia, więc może być częstsze na kontach z wysokim Ratuszem. Według naszych badań głównymi czynnikami wartości pozostają poziom Ratusza i postęp bohaterów.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: jak wybieranych jest osiem drużyn w każdym regionie',
  'desc': 'Supercell wyjaśnił 1 października 2026 r., jak drużyny trafiają do BSC 2027: sześć bezpośrednich zaproszeń na region z rankingu 2026 i dwa miejsca z BSC Invitational 16–17 stycznia 2027 r.',
  'lead': '1 października 2026 r. Supercell opublikował ścieżkę kwalifikacji do Brawl Stars Championship 2027.',
  'new': ['W BSC 2027 gra po osiem drużyn w każdym z czterech regionów: APAC, EMEA, Ameryka Południowa i Ameryka Północna.',
          'Sześć najlepszych drużyn rankingu BSC 2026 każdego regionu dostaje bezpośrednie zaproszenie i może wymienić najwyżej jednego gracza.',
          'O dwóch ostatnich miejscach w regionie decyduje BSC Invitational 16–17 stycznia 2027 r.: grają drużyny z miejsc 7–10, a w EMEA z miejsc 7–14.',
          'Zaproszenia zostaną wysłane 23 listopada 2026 r., a drużyny muszą odpowiedzieć do 20 grudnia; Supercell zaznacza, że terminy mogą się zmienić. Nowe drużyny zaczynają od Championship Challenge w grze i Brawl Stars Challengers.'],
  'impact': 'Kwalifikacje esportowe nie zmieniają wartości zwykłego konta. Według naszych badań ceny w ogłoszeniach nadal zależą od trofeów, zadymiarzy i ich poziomów mocy.'},
}},
}
