# News batch 2: ru, es (from news_text_b2_en.py, facts unchanged)
TEXT = {
'ru': {'a': {
 'mc-d2': {'title': 'Вышла Minecraft Dungeons II: измерение the Sift и Совет иллагеров',
  'desc': 'Mojang выпустила Minecraft Dungeons II 29 сентября 2026 года на Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch и Switch 2, с кооперативом до 4 игроков.',
  'lead': 'Mojang Studios выпустила Minecraft Dungeons II 29 сентября 2026 года.',
  'new': ['Игра вышла на Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch и Nintendo Switch 2.',
          'Сюжет сталкивает игроков с Советом иллагеров: Верховным заклинателем, Верховным вызывателем и Великим иллюзионистом.',
          'Игроки исследуют новое измерение the Sift — по словам Mojang, в следующем году оно появится и в Minecraft Java и Bedrock.',
          'Можно играть одному или в кооперативе до 4 игроков — онлайн или на одном экране.'],
  'impact': 'Dungeons II — отдельная игра. Аккаунты Minecraft Java и Bedrock по-прежнему оцениваются по типу, нику и плащам, поэтому выход игры не меняет их стоимость.'},
 'cr-mt-oct': {'title': 'Clash Royale, Merge Tactics: октябрьские изменения суперов, эликсира и значков',
  'desc': 'С 1 октября 2026 года в 11-м сезоне Merge Tactics суперы уходят в общий пул, эликсир за раунд снижается с 5 до 4, появляются скины 5-го уровня; правила значков меняются в 12-м сезоне.',
  'lead': 'Supercell объявила октябрьские изменения 11-го сезона Merge Tactics 30 сентября 2026 года; они действуют с 1 октября.',
  'new': ['Суперы больше не выдаются стартовыми войсками: они попадают в общий пул, за который соревнуются все игроки.',
          'Эликсир за раунд возвращается с 5 к 4.',
          'Боевая машина и Герцогиня кинжалов получают скины 5-го уровня для тех, кто их уже улучшил.',
          'С 12-го сезона серебряный значок требует дойти до Алмазной лиги, а золотой — попасть в топ-10 000.'],
  'impact': 'С 12-го сезона значки за высокие места станет сложнее получить, и они яснее покажут уровень игры на профиле Clash Royale. Главными факторами стоимости остаются уровень Королевской башни и уровни карт.'},
 'ml-mplph': {'title': 'Плей-офф MPL Philippines, 18-й сезон: PhilSports Arena, 21–25 октября',
  'desc': 'MOONTON 26 сентября 2026 года объявила, что плей-офф MPL Philippines 18-го сезона пройдёт 21–25 октября на PhilSports Arena и определит филиппинские команды на M8.',
  'lead': 'MOONTON Games 26 сентября 2026 года объявила место и даты плей-офф MPL Philippines 18-го сезона.',
  'new': ['Плей-офф пройдёт на PhilSports Arena в Пасиге с 21 по 25 октября 2026 года.',
          'Он определит команды, которые представят Филиппины на чемпионате мира M8 в Стамбуле в январе 2027 года.',
          'Продажа билетов открылась 26 сентября, цены — от 200 филиппинских песо.',
          'Анонс приурочен к 10-летию игры: MOONTON называет 1,5 млрд установок и 110 млн активных игроков в месяц.'],
  'impact': 'Киберспортивные события не меняют стоимость существующих аккаунтов. По нашему исследованию, стоимость аккаунтов Mobile Legends определяют скины, герои и прогресс.'},
 'cr-bal-sep': {'title': 'Сентябрьский баланс Clash Royale: ослаблены герой Ледяной маг и Миньон-гигант',
  'desc': 'Сентябрьские изменения баланса Supercell 2026 года сокращают заморозку героя Ледяного мага с 7 до 5 секунд и урон Миньона-гиганта со 189 до 168, переделывают героев Мега-миньона и Мага.',
  'lead': 'Supercell опубликовала два раунда изменений баланса Clash Royale — они вступили в силу 8 и 16 сентября 2026 года.',
  'new': ['16 сентября: заморозка героя Ледяного мага 7 с → 5 с; способность Гоблинштейна 4 с → 3,5 с; урон Миньона-гиганта 189 → 168; урон Огненного духа 207 → 215.',
          '8 сентября: Заморозка 4 с → 3,5 с; урон Огненного шара по башням 172 → 159; здоровье Ледяного голема 1 315 → 1 228.',
          'Переработки: герой Мега-миньон (возвращается телепортом, урон 399 → 422) и герой Маг (способность 5 с → 3,5 с); урон Мага 281 → 304.',
          'Усилены в том числе Ронин, Императрица духов и Клетка с гоблином.'],
  'impact': 'Баланс меняет популярность карт, а не то, что есть в аккаунте. По нашему исследованию, стоимость Clash Royale зависит от уровня Королевской башни, уровней карт, эволюций и редкой косметики.'},
 'gi-wish71': {'title': 'Молитвы события Genshin Impact 7.1: баннеры Весны и Водяницы до 13 октября',
  'desc': 'Молитвы события первой фазы 7.1 от HoYoverse повышают шанс Весны и Водяницы до 13 октября 2026 года; 4-звёздочные с повышенным шансом — Диона, Фарузан и Чун Юнь.',
  'lead': 'HoYoverse опубликовала молитвы события первой фазы версии 7.1 21 сентября 2026 года; они действуют до 13 октября 2026 года, 17:59.',
  'new': ['«When Warm Winds Cavort» повышает шанс выпадения Весны (Анемо).',
          '«Surging Ballad» повышает шанс выпадения Водяницы (Гидро).',
          '4-звёздочные персонажи с повышенным шансом: Диона (Крио), Фарузан (Анемо) и Чун Юнь (Крио).',
          'Персонажей события нет в стандартной молитве; два баннера персонажей делят общий счётчик гаранта.'],
  'impact': 'Персонажи, которых можно получить только из лимитированных баннеров, и их созвездия — один из главных факторов стоимости аккаунтов Genshin по нашему исследованию.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: скин Darryl «Мусорный гоблин» и награды до 30 сентября',
  'desc': 'Ивент Brawl Stars × Duolingo от Supercell (анонс 19 сентября 2026 года) давал скин Darryl «Мусорный гоблин», гемы, Starr Drop и другое до 30 сентября.',
  'lead': 'Supercell объявила кроссовер Brawl Stars × Duolingo 19 сентября 2026 года; он шёл до 30 сентября.',
  'new': ['Две фазы общих целей сообщества и игровых заданий плюс новый режим Duo Boss Fight.',
          'Награды: скин Darryl «Мусорный гоблин» (Trash Goblin), 20 гемов, 5 Chaos Drop, 3 мифических Starr Drop, 2 000 монет, 2 500 блинга и 1 000 кредитов.',
          'Квест Brawl Stars в приложении Duolingo давал дополнительную косметику.',
          'Supercell также провела в соцсетях викторину с раздачей 3,141592 млн гемов.'],
  'impact': 'Скины единичных кроссоверов выделяют некоторые коллекции Brawl Stars; скин, который многие получили бесплатно, добавляет меньше, чем редкий платный.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN снова в игре: Девятихвостый и набор Хинаты (16 сентября — 15 октября)',
  'desc': 'Коллаборация Garena с NARUTO SHIPPUDEN идёт с 16 сентября по 15 октября 2026 года: навык Sharingan: Control, набор на выбор Джирайи или Хинаты и тематическая косметика.',
  'lead': 'Garena 15 сентября 2026 года объявила, что коллаборация Free Fire × NARUTO SHIPPUDEN возвращается с 16 сентября по 15 октября.',
  'new': ['Новые навыки: Sharingan: Control, позволяющий управлять Девятихвостым, и 8 Trigrams Palm Rotation.',
          'Расширенная Академия ниндзя на карте Деревни Скрытого Листа.',
          'Главный приз на выбор: набор Джирайи или набор Хинаты (её дебют в игре).',
          'Косметика: плащ Цунаде, раскраска-тату Гаары, маска АНБУ Какаши и ящик Froggy Wallet.'],
  'impact': 'Наборы из лицензионных коллабораций, доступные ограниченное время, — среди редких предметов, которые ищет наш калькулятор Free Fire.'},
 'ml-mtc8': {'title': 'Стартовал 8-й сезон MLBB Türkiye Championship — путь к M8 в Стамбуле',
  'desc': '8-й сезон MTC идёт с 12 сентября по 18 октября 2026 года: восемь команд и призовой фонд 40 000 долларов перед чемпионатом мира M8 в Стамбуле в январе 2027 года.',
  'lead': 'MOONTON Games 10 сентября 2026 года объявила, что 8-й сезон MLBB Türkiye Championship стартует 12 сентября.',
  'new': ['Регулярный сезон — с 12 сентября по 18 октября; гранд-финал — 7 ноября 2026 года.',
          'Участвуют восемь команд, среди них Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok и Dark Passage.',
          'Шесть лучших команд выходят в плей-офф и разыгрывают призовой фонд 40 000 долларов.',
          'Чемпионат мира M8 пройдёт в Стамбуле в январе 2027 года — это первый турнир серии M в Европе.'],
  'impact': 'Результаты турниров не меняют стоимость существующих аккаунтов; главными факторами по нашему исследованию остаются коллекционные и легендарные скины и число героев.'},
 'coc-blast': {'title': 'Ивент с медалями Equipment Blast в Clash of Clans (9–22 сентября)',
  'desc': 'Ивент Equipment Blast шёл с 9 по 22 сентября 2026 года: билеты Tag Tickets и медали Champ Medals обменивались у Торговца на снаряжение героев, руду и косметику. С Ратуши 6.',
  'lead': 'Supercell объявила ивент с медалями Equipment Blast 9 сентября 2026 года; он шёл до 22 сентября 08:00 UTC, Торговец работал до 24 сентября.',
  'new': ['Бои в мультиплеере приносили Tag Tickets; трек ивента давал медали Champ Medals, временные войска и сундуки.',
          'Торговец продавал за медали ивента снаряжение героев, руду и косметику.',
          'Временные войска: Undertaker Yeti, K.A.N.E., Yeeter и Giant Giant.',
          'Ивент был доступен с Ратуши 6.'],
  'impact': 'Снаряжение героев и его уровни влияют на силу героев, которая по нашему исследованию определяет стоимость аккаунтов Clash of Clans; медали ивента — ещё один способ его улучшить.'},
 'mc-wild': {'title': 'Дроп Minecraft Wilderness Bound: пятнистый лес, соломенные кровати и заброшенные лагеря',
  'desc': 'Игровой дроп Mojang Wilderness Bound вышел 15 сентября 2026 года: биом пятнистого леса, тополь, соломенные кровати, заброшенные лагеря и подушки.',
  'lead': 'Mojang Studios 5 сентября назвала третий игровой дроп 2026 года «Wilderness Bound» и выпустила его 15 сентября.',
  'new': ['Новый биом — пятнистый лес с высокими тополями и грибами-трутовиками.',
          'Соломенные кровати из трёх тюков сена позволяют пропустить ночь, не меняя точку возрождения.',
          'Заброшенные лагеря для исследования и подушки из трёх одноцветных плит шерсти.',
          'Древесина тополя и расширенные наборы бетона и шерсти для строительства.'],
  'impact': 'Аккаунты Minecraft оцениваются по типу, нику и плащам, а не по игровому контенту, поэтому игровой дроп не меняет их стоимость.'},
 'ff-award': {'title': 'Free Fire получил награду «Лучшее использование IP или лицензии» Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena 3 сентября 2026 года сообщила, что Free Fire получил награду Best Use of IP or Licence на Pocket Gamer Mobile Games Awards 2026 за коллаборацию с NARUTO SHIPPUDEN.',
  'lead': 'Garena 3 сентября 2026 года объявила, что Free Fire получил награду «Best Use of IP or Licence» на Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Награда отмечает коллаборацию NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'По данным Garena, турнир Ninja Clash All Stars в Бангкоке собрал почти 5 000 зрителей и более 247 млн просмотров видео.',
          'Коллаборация включала тематических персонажей, техники-дзюцу и преображённую карту Деревни Скрытого Листа.',
          'Мероприятия для сообщества прошли в Перу, Бангладеш, Малайзии и на Тайване.'],
  'impact': 'Награда не меняет стоимость аккаунтов. Но она подтверждает, что лицензионные коллаборации — постоянная часть Free Fire, а лимитированные наборы из них — среди редких предметов, которые учитывает оценка.'},
 'rbx-fall': {'title': 'Осенний обзор игр Roblox: 10 плейсов в сентябре и октябре',
  'desc': 'Осенний обзор игр Roblox (2 сентября 2026 года) называет 10 новых плейсов — от Showdown и Nemesis в сентябре до Prime Heroes, Octane и Starforged в октябре.',
  'lead': 'Roblox опубликовал осенний обзор игр 2 сентября 2026 года — десять плейсов, которые выходят в сентябре и октябре.',
  'new': ['Сентябрь: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force и Caramel.',
          'Октябрь: Prime Heroes (ранний доступ в сентябре с 6 героями), Octane, Starforged и Scrapbook Saga.',
          'Несколько игр вышли из программ для авторов Roblox Jumpstart и Incubator.',
          'Жанры — от шутеров и гонок до хоррора на выживание и фермы.'],
  'impact': 'Новые плейсы не меняют существующие аккаунты. По нашему исследованию, стоимость аккаунта Roblox складывается из Robux, лимитированных предметов и предметов в давно существующих плейсах; новая игра важна, только когда её предметы начинают продаваться.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: разовые скины героев, которые «не вернутся» после 1 октября',
  'desc': 'Ивент Supercell WWE: Search for Cena (сентябрь 2026 года) продавал шесть скинов героев WWE, которые, по словам Supercell, не вернутся после 1 октября, а также декорации Money in the Bank.',
  'lead': 'Supercell объявила ивент WWE: Search for Cena для Clash of Clans 1 сентября 2026 года; он шёл весь сентябрь.',
  'new': ['Скины героев по 9,99 доллара: Коди Роудс (Король варваров), Алекса Блисс (Королева лучниц), Иё Скай (Королевская чемпионка), Кейн (Король драконов) и American Badass Undertaker (Великий хранитель).',
          'Джей Усо (Принц миньонов) шёл в комплекте с Золотым пропуском.',
          'Supercell пишет, что после 1 октября эти скины «не вернутся. Никогда».',
          'Декорации Money in the Bank XL продавались со 2 по 30 сентября; параллельно шли испытание Джона Сины и временные войска WWE.'],
  'impact': 'Скины, о которых издатель говорит, что они никогда не вернутся, — именно та косметика, что делает аккаунт Clash of Clans редче. Но основную стоимость по-прежнему дают уровни Ратуши и героев.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: первый взгляд на новый формат из двух сплитов',
  'desc': 'Первый взгляд Supercell на BSC 2027 (24 августа 2026 года): по восемь команд в четырёх регионах, Challengers в 12 регионах, два сплита по 12 недель, Brawl Cup и финал чемпионата мира.',
  'lead': 'Supercell 24 августа 2026 года показала первый взгляд на Brawl Stars Championship 2027, предупредив, что детали ещё могут измениться.',
  'new': ['Высший уровень: по 8 команд в регионах Восточная Азия, EMEA, Южная Америка и Северная Америка.',
          'Challengers: путь в профессионалы в 12 регионах.',
          'Два сплита по 12 недель: первый завершается Brawl Cup — трёхдневным международным LAN-турниром, второй — финалом чемпионата мира.',
          'Даты, призовой фонд и места проведения пока не объявлены.'],
  'impact': 'Киберспортивные форматы не меняют стоимость существующих аккаунтов; наш калькулятор Brawl Stars по-прежнему учитывает число бойцов, гиперзаряды и трофеи.'},
}},
'es': {'a': {
 'mc-d2': {'title': 'Ya está aquí Minecraft Dungeons II: la dimensión del Sift y el Alto Consejo Illager',
  'desc': 'Mojang lanzó Minecraft Dungeons II el 29 de septiembre de 2026 en Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch y Switch 2, con cooperativo para hasta 4 jugadores.',
  'lead': 'Mojang Studios lanzó Minecraft Dungeons II el 29 de septiembre de 2026.',
  'new': ['Disponible en Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch y Nintendo Switch 2.',
          'La historia enfrenta a los jugadores al Alto Consejo Illager: el Encantador Supremo, el Invocador Supremo y el Gran Ilusionista.',
          'Se explora una dimensión nueva, el Sift, que según Mojang también llegará a Minecraft Java y Bedrock el año que viene.',
          'Se juega en solitario o en cooperativo de hasta 4 jugadores, en línea o en la misma pantalla.'],
  'impact': 'Dungeons II es un juego aparte. Las cuentas de Minecraft Java y Bedrock se siguen valorando por el tipo, el nombre de usuario y las capas, así que el lanzamiento no cambia lo que valen.'},
 'cr-mt-oct': {'title': 'Merge Tactics de Clash Royale: cambios de octubre en Supers, elixir e insignias',
  'desc': 'Desde el 1 de octubre de 2026, la temporada 11 de Merge Tactics pasa los Supers a la reserva común, reduce el elixir por ronda de 5 a 4 y añade aspectos de nivel 5; las insignias cambian en la temporada 12.',
  'lead': 'Supercell anunció el 30 de septiembre de 2026 los cambios de octubre de la temporada 11 de Merge Tactics; se aplican desde el 1 de octubre.',
  'new': ['Los Supers dejan de ser tropas iniciales: pasan a la reserva común, donde todos los jugadores compiten por ellos.',
          'El elixir que se gana por ronda vuelve de 5 a 4.',
          'Máquina de Batalla y Duquesa de las Dagas reciben aspectos de nivel 5 para quienes ya las mejoraron.',
          'Desde la temporada 12, la insignia de plata exige llegar a la Liga Diamante y la de oro, quedar en el top 10 000.'],
  'impact': 'Desde la temporada 12 las insignias por buen puesto serán más difíciles, así que mostrarán mejor la habilidad en un perfil de Clash Royale. El nivel de la Torre del Rey y de las cartas siguen siendo los principales factores de valor.'},
 'ml-mplph': {'title': 'Playoffs de la MPL Filipinas, temporada 18: PhilSports Arena, del 21 al 25 de octubre',
  'desc': 'MOONTON anunció el 26 de septiembre de 2026 que los playoffs de la temporada 18 de la MPL Filipinas serán del 21 al 25 de octubre en el PhilSports Arena y definirán a los equipos filipinos del M8.',
  'lead': 'MOONTON Games anunció el 26 de septiembre de 2026 la sede y las fechas de los playoffs de la temporada 18 de la MPL Filipinas.',
  'new': ['Los playoffs serán en el PhilSports Arena de Pasig, del 21 al 25 de octubre de 2026.',
          'Definirán qué equipos representan a Filipinas en el Campeonato Mundial M8 de Estambul, en enero de 2027.',
          'La venta de entradas abrió el 26 de septiembre, desde 200 pesos filipinos.',
          'El anuncio celebra el 10.º aniversario del juego: 1500 millones de instalaciones y 110 millones de jugadores activos al mes.'],
  'impact': 'Los eventos de esports no cambian el valor de las cuentas existentes. Según nuestra investigación, el valor en Mobile Legends lo marcan las skins, los héroes y el progreso.'},
 'cr-bal-sep': {'title': 'Equilibrio de septiembre en Clash Royale: nerf al héroe Mago de Hielo y al Esbirro Gigante',
  'desc': 'Los ajustes de septiembre de 2026 de Supercell reducen la congelación del héroe Mago de Hielo de 7 a 5 segundos y el daño del Esbirro Gigante de 189 a 168, y rehacen a los héroes Megaesbirro y Mago.',
  'lead': 'Supercell publicó dos rondas de ajustes de equilibrio de Clash Royale, aplicadas el 8 y el 16 de septiembre de 2026.',
  'new': ['16 de septiembre: congelación del héroe Mago de Hielo 7 s → 5 s; habilidad de Goblinstein 4 s → 3,5 s; daño del Esbirro Gigante 189 → 168; daño del Espíritu de Fuego 207 → 215.',
          '8 de septiembre: Hielo 4 s → 3,5 s; daño de la Bola de Fuego a torres 172 → 159; vida del Gólem de Hielo 1315 → 1228.',
          'Rediseños: héroe Megaesbirro (vuelve con teletransporte, daño 399 → 422) y héroe Mago (habilidad 5 s → 3,5 s); daño del Mago 281 → 304.',
          'Mejoras para Ronin, Emperatriz Espiritual y Jaula de Duende, entre otros.'],
  'impact': 'El equilibrio cambia qué cartas se usan, no lo que tiene una cuenta. Según nuestra investigación, el valor en Clash Royale sigue al nivel de la Torre del Rey, de las cartas, las evoluciones y la cosmética rara.'},
 'gi-wish71': {'title': 'Gachapones de evento de Genshin Impact 7.1: Vesna y Vodyanitsa hasta el 13 de octubre',
  'desc': 'Los gachapones de evento de la fase I de la versión 7.1 aumentan la probabilidad de Vesna y Vodyanitsa hasta el 13 de octubre de 2026, con Diona, Faruzan y Chongyun como 4 estrellas destacados.',
  'lead': 'HoYoverse publicó los gachapones de evento de la fase I de la versión 7.1 el 21 de septiembre de 2026; duran hasta el 13 de octubre de 2026 a las 17:59.',
  'new': ['«When Warm Winds Cavort» aumenta la probabilidad de Vesna (Anemo).',
          '«Surging Ballad» aumenta la probabilidad de Vodyanitsa (Hydro).',
          'Personajes de 4 estrellas destacados: Diona (Cryo), Faruzan (Anemo) y Chongyun (Cryo).',
          'Los personajes exclusivos del evento no están en el gachapón estándar; los dos gachapones de personajes comparten el contador de garantía.'],
  'impact': 'Los personajes que solo se consiguen en gachapones limitados, y sus constelaciones, están entre los principales factores de valor de una cuenta de Genshin según nuestra investigación.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: aspecto Darryl Duende Basurero y recompensas hasta el 30 de septiembre',
  'desc': 'El evento Brawl Stars × Duolingo de Supercell (anunciado el 19 de septiembre de 2026) daba el aspecto Darryl Duende Basurero, gemas, Starr Drops y más hasta el 30 de septiembre.',
  'lead': 'Supercell anunció el crossover Brawl Stars × Duolingo el 19 de septiembre de 2026; duró hasta el 30 de septiembre.',
  'new': ['Dos fases de objetivos de comunidad y tareas en el juego, además de un nuevo modo Duo Boss Fight.',
          'Recompensas: aspecto Darryl Duende Basurero (Trash Goblin), 20 gemas, 5 Chaos Drops, 3 Starr Drops míticos, 2000 monedas, 2500 de bling y 1000 créditos.',
          'Una misión de Brawl Stars dentro de la app de Duolingo daba cosméticos extra.',
          'Supercell también hizo en redes un concurso de preguntas con 3,141592 millones de gemas en premios.'],
  'impact': 'Los aspectos de un crossover único son lo que hace destacar algunas colecciones de Brawl Stars; un aspecto que muchos recibieron gratis aporta menos que uno raro de pago.'},
 'ff-naruto': {'title': 'Vuelve Free Fire × NARUTO SHIPPUDEN: Nueve Colas y lote de Hinata (16 de septiembre – 15 de octubre)',
  'desc': 'La colaboración de Garena con NARUTO SHIPPUDEN va del 16 de septiembre al 15 de octubre de 2026 con la habilidad Sharingan: Control, un lote a elegir de Jiraiya o Hinata y cosméticos temáticos.',
  'lead': 'Garena anunció el 15 de septiembre de 2026 que la colaboración Free Fire × NARUTO SHIPPUDEN vuelve del 16 de septiembre al 15 de octubre.',
  'new': ['Habilidades nuevas: Sharingan: Control, que permite dirigir a Nueve Colas, y 8 Trigrams Palm Rotation.',
          'Una Academia Ninja ampliada en el mapa de la Aldea Oculta de la Hoja.',
          'Gran premio a elegir: lote de Jiraiya o lote de Hinata (su estreno en el juego).',
          'Cosméticos: capa de Tsunade, pintura facial del tatuaje de Gaara, máscara ANBU de Kakashi y la caja Froggy Wallet.'],
  'impact': 'Los lotes de colaboraciones con licencia que solo están disponibles un tiempo limitado están entre los objetos raros que busca nuestra calculadora de Free Fire.'},
 'ml-mtc8': {'title': 'Arranca la temporada 8 del MLBB Türkiye Championship, camino del M8 en Estambul',
  'desc': 'La temporada 8 del MTC va del 12 de septiembre al 18 de octubre de 2026 con ocho equipos y 40 000 dólares en premios, antes del Mundial M8 de Estambul en enero de 2027.',
  'lead': 'MOONTON Games anunció el 10 de septiembre de 2026 que la temporada 8 del MLBB Türkiye Championship empieza el 12 de septiembre.',
  'new': ['Temporada regular del 12 de septiembre al 18 de octubre; la gran final, el 7 de noviembre de 2026.',
          'Participan ocho equipos, entre ellos Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok y Dark Passage.',
          'Los seis mejores pasan a los playoffs y se reparten 40 000 dólares.',
          'El Campeonato Mundial M8 será en Estambul en enero de 2027, el primer evento de la serie M en Europa.'],
  'impact': 'Los resultados de esports no cambian el valor de las cuentas existentes; las skins Coleccionista y Leyenda y el número de héroes siguen siendo los factores principales según nuestra investigación.'},
 'coc-blast': {'title': 'Evento de medallas Equipment Blast en Clash of Clans (9–22 de septiembre)',
  'desc': 'El evento Equipment Blast fue del 9 al 22 de septiembre de 2026: Tag Tickets y Champ Medals para gastar en el Comerciante en equipo de héroe, mineral y cosméticos. Ayuntamiento 6+.',
  'lead': 'Supercell anunció el evento de medallas Equipment Blast el 9 de septiembre de 2026; duró hasta el 22 de septiembre a las 08:00 UTC, con el Comerciante abierto hasta el 24.',
  'new': ['Las batallas multijugador daban Tag Tickets; la ruta del evento daba Champ Medals, tropas temporales y cofres.',
          'El Comerciante vendía equipo de héroe, mineral y cosméticos a cambio de medallas del evento.',
          'Tropas temporales: Undertaker Yeti, K.A.N.E., Yeeter y Giant Giant.',
          'Disponible desde el Ayuntamiento 6.'],
  'impact': 'El equipo de héroe y sus niveles forman parte de la fuerza de los héroes, que según nuestra investigación marca el valor de las cuentas de Clash of Clans; las medallas del evento son otra forma de mejorarlo.'},
 'mc-wild': {'title': 'Actualización Wilderness Bound de Minecraft: bosque moteado, camas de paja y campamentos abandonados',
  'desc': 'La actualización Wilderness Bound de Mojang llegó el 15 de septiembre de 2026 con el bioma del bosque moteado, madera de álamo, camas de paja, campamentos abandonados y cojines.',
  'lead': 'Mojang Studios bautizó el 5 de septiembre su tercera actualización de 2026 como «Wilderness Bound» y la publicó el 15 de septiembre.',
  'new': ['Un bioma nuevo, el bosque moteado, con álamos altos y hongos repisa.',
          'Las camas de paja, hechas con tres balas de heno, permiten saltar la noche sin cambiar el punto de reaparición.',
          'Campamentos abandonados para explorar y cojines hechos con tres losas de lana del mismo color.',
          'Madera de álamo y conjuntos ampliados de hormigón y lana para construir.'],
  'impact': 'Las cuentas de Minecraft se valoran por el tipo, el nombre de usuario y las capas, no por el contenido del juego, así que una actualización no cambia lo que vale una cuenta.'},
 'ff-award': {'title': 'Free Fire gana «Mejor uso de una IP o licencia» en los Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena informó el 3 de septiembre de 2026 de que Free Fire ganó Best Use of IP or Licence en los Pocket Gamer Mobile Games Awards 2026 por su colaboración con NARUTO SHIPPUDEN.',
  'lead': 'Garena anunció el 3 de septiembre de 2026 que Free Fire ganó «Best Use of IP or Licence» en los Pocket Gamer Mobile Games Awards 2026.',
  'new': ['El premio reconoce la colaboración NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Según Garena, su evento Ninja Clash All Stars en Bangkok reunió a casi 5000 visitantes y más de 247 millones de visualizaciones.',
          'La colaboración incluyó personajes temáticos, habilidades jutsu y un mapa transformado de la Aldea Oculta de la Hoja.',
          'Hubo eventos de comunidad en Perú, Bangladés, Malasia y Taiwán.'],
  'impact': 'Un premio no cambia el valor de las cuentas, pero confirma que las colaboraciones con licencia son habituales en Free Fire, y sus lotes limitados están entre los objetos raros que mira una tasación.'},
 'rbx-fall': {'title': 'Avance de juegos de otoño de Roblox: 10 experiencias en septiembre y octubre',
  'desc': 'El avance de juegos de otoño de Roblox (2 de septiembre de 2026) recoge 10 experiencias nuevas, de Showdown y Nemesis en septiembre a Prime Heroes, Octane y Starforged en octubre.',
  'lead': 'Roblox publicó su avance de juegos de otoño el 2 de septiembre de 2026, con diez experiencias previstas para septiembre y octubre.',
  'new': ['Septiembre: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force y Caramel.',
          'Octubre: Prime Heroes (acceso anticipado en septiembre con 6 héroes), Octane, Starforged y Scrapbook Saga.',
          'Varios títulos salen de los programas para creadores Jumpstart e Incubator de Roblox.',
          'Los géneros van de shooters y carreras a terror de supervivencia y granjas.'],
  'impact': 'Las experiencias nuevas no cambian las cuentas existentes. Según nuestra investigación, el valor de una cuenta de Roblox viene de los Robux, los objetos limitados y los objetos de experiencias veteranas; un juego nuevo solo importa cuando sus objetos empiezan a venderse.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: aspectos de héroe únicos que «no volverán» después del 1 de octubre',
  'desc': 'El evento WWE: Search for Cena de Supercell (septiembre de 2026) vendió seis aspectos de héroe de la WWE que, según Supercell, no volverán después del 1 de octubre, además del decorado Money in the Bank.',
  'lead': 'Supercell anunció el evento WWE: Search for Cena de Clash of Clans el 1 de septiembre de 2026; duró todo septiembre.',
  'new': ['Aspectos de héroe a 9,99 $: Cody Rhodes (Rey Bárbaro), Alexa Bliss (Reina Arquera), Iyo Sky (Campeona Real), Kane (Duque Dragón) y American Badass Undertaker (Gran Centinela).',
          'Jey Uso (Príncipe Esbirro) venía con el Pase de Oro.',
          'Supercell dice que los aspectos «no volverán. Nunca» después del 1 de octubre.',
          'El decorado XL Money in the Bank estuvo disponible del 2 al 30 de septiembre, junto con un desafío de John Cena y tropas temporales de la WWE.'],
  'impact': 'Los aspectos que la editora asegura que nunca volverán son justo el tipo de cosmético que hace más rara una cuenta de Clash of Clans. Aun así, el nivel del ayuntamiento y de los héroes concentra la mayor parte del valor.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: primer vistazo al nuevo formato de dos splits',
  'desc': 'Primer vistazo de Supercell al BSC 2027 (24 de agosto de 2026): ocho equipos por región en cuatro regiones, Challengers en 12 regiones, dos splits de 12 semanas, la Brawl Cup y la Final Mundial.',
  'lead': 'Supercell mostró un primer vistazo al Brawl Stars Championship 2027 el 24 de agosto de 2026, avisando de que los detalles aún pueden cambiar.',
  'new': ['Nivel superior: 8 equipos por región en Asia Oriental, EMEA, Sudamérica y Norteamérica.',
          'Challengers: una vía de entrada en 12 regiones.',
          'Dos splits de 12 semanas; el primero termina con la Brawl Cup, una LAN internacional de tres días, y el segundo con la Final Mundial.',
          'Aún no se han anunciado fechas, premios ni sedes.'],
  'impact': 'Los formatos de esports no cambian el valor de las cuentas existentes; nuestra calculadora de Brawl Stars sigue usando el número de brawlers, las hipercargas y los trofeos.'},
}},
}
