# News articles (SITE-STANDARD step 4). Facts: scripts/research/news-2026-09.md — publisher
# sources only. Our datePublished = the day we publish; the publisher's date is shown separately.
PUBLISHED = '2026-10-01'
GAMES = {'roblox': 'Roblox', 'brawl-stars': 'Brawl Stars', 'clash-of-clans': 'Clash of Clans', 'clash-royale': 'Clash Royale',
         'free-fire': 'Free Fire', 'genshin-impact': 'Genshin Impact', 'mobile-legends': 'Mobile Legends',
         'fortnite': 'Fortnite', 'minecraft': 'Minecraft'}
# id, game, slug, sort date (publisher date), sources [(url, publisher, date or None)]
ARTICLES = [
 ('gi71', 'genshin-impact', 'news-genshin-impact-2026-09-version-7-1', '2026-09-23',
  [('https://genshin.hoyoverse.com/en/news/detail/166383', 'HoYoverse', '2026-09-23'),
   ('https://genshin.hoyoverse.com/en/news/detail/166086', 'HoYoverse', '2026-09-12')]),
 ('mc-live', 'minecraft', 'news-minecraft-2026-09-the-sift-dimension', '2026-09-26',
  [('https://www.minecraft.net/en-us/article/mclive_sept2026_recap', 'Mojang Studios', '2026-09-26'),
   ('https://www.minecraft.net/en-us/article/drop-3-2026-name-announce', 'Mojang Studios', '2026-09-05')]),
 ('rbx-hunt', 'roblox', 'news-roblox-2026-09-the-hunt-roblox-20', '2026-09-16',
  [('https://about.roblox.com/newsroom/2026/09/join-the-hunt-roblox-20', 'Roblox', '2026-09-16')]),
 ('rbx-rdc', 'roblox', 'news-roblox-2026-09-rdc-2026-creator-earnings', '2026-09-11',
  [('https://about.roblox.com/newsroom/2026/09/rdc-2026-the-world-needs-more-play', 'Roblox', '2026-09-11')]),
 ('ff-ob55', 'free-fire', 'news-free-fire-2026-09-ob55-update', '2026-09-10',
  [('https://ff.garena.com/en/article/1712/', 'Garena', '2026-09-10')]),
 ('cr-minion', 'clash-royale', 'news-clash-royale-2026-09-minion-academy-season', '2026-09-07',
  [('https://supercell.com/en/games/clashroyale/blog/release-notes/new-season-minion-academy/', 'Supercell', '2026-09-07')]),
 ('ml-10', 'mobile-legends', 'news-mobile-legends-2026-09-10th-anniversary', '2026-09-04',
  [('https://en.moonton.com/news/372.html', 'MOONTON Games', '2026-09-04')]),
 ('bs-aug', 'brawl-stars', 'news-brawl-stars-2026-09-cosmo-vince-brawler-blast', '2026-09-01',
  [('https://supercell.com/en/games/brawlstars/blog/release-notes/release-notes-august-2026/', 'Supercell', '2026-09-01')]),
 ('coc-aug', 'clash-of-clans', 'news-clash-of-clans-2026-08-august-update', '2026-08-30',
  [('https://supercell.com/en/games/clashofclans/blog/release-notes/august-update-3/', 'Supercell', '2026-08-30')]),
 ('fn-c7s4', 'fortnite', 'news-fortnite-2026-08-chapter-7-season-4-override', '2026-08-27',
  [('https://www.fortnite.com/news/fortnite-override-break-the-rules-change-the-game', 'Epic Games', None),
   ('https://www.fortnite.com/battle-pass', 'Epic Games', None)]),
]

TEXT = {'en': {
 'ui': {
  'news': 'News', 'news_title': 'Game news that affects account value',
  'news_lead': 'Official updates from game publishers — each one checked against the publisher’s own announcement, with a plain note on what it means for account value.',
  'game_title': '{game} news', 'game_lead': 'Official {game} updates that affect what an account is worth. Every article links the publisher’s own announcement.',
  'published': 'Published', 'source': 'Official source', 'by_on': '{pub}, {date}', 'whats_new': 'What’s new',
  'impact': 'What it means for account value', 'more': 'More {game} news', 'all': 'All news',
  'calc': '{game}: value calculator and market report', 'read': 'Read', 'latest': 'Latest {game} news',
  'note': 'GameAccountValue does not buy, sell or broker accounts. News is summarised from publisher announcements for information only.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna and Vodyanitsa arrive, anniversary rewards confirmed',
   'desc': 'Version 7.1 “A Rekviem for the Underworld” launched on September 23, 2026 with two new 5-star characters, two 5-star weapons and sixth-anniversary rewards.',
   'lead': 'HoYoverse released Version 7.1, “A Rekviem for the Underworld”, on September 23, 2026 — the update that also carries Genshin Impact’s sixth anniversary.',
   'new': ['Two new 5-star characters: Vesna (Anemo, Sword) and Vodyanitsa (Hydro, Catalyst).',
           'New weapons: Beyond the Chrysalis (5-star Sword), Hymn of the Maelstrom (5-star Catalyst) and New Bough (4-star Sword).',
           'Anniversary rewards announced by HoYoverse: two 5-star characters to invite, Intertwined Fate ×10, Primogems ×1,600 and a reset of the Genesis Crystal first top-up bonus.',
           'Update maintenance started on September 23 at 06:00 (UTC+8).'],
   'impact': 'The number of limited 5-star characters, their constellations and signature weapons is one of the main drivers of Genshin account value in our research. Characters given free to every player for the anniversary make an account less distinctive than limited-banner characters do.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, the first new dimension in over 14 years, comes to Java and Bedrock',
   'desc': 'Minecraft Live on September 26, 2026 revealed The Sift, a fourth dimension coming to Java and Bedrock next year, plus Dungeons II and the Wilderness Bound drop.',
   'lead': 'At Minecraft Live on September 26, 2026, Mojang Studios announced that the game’s fourth dimension, The Sift, will come to Minecraft Java and Bedrock Edition next year.',
   'new': ['The Sift is the first new dimension in over 14 years, joining the Overworld, the Nether and the End.',
           'It debuts in Minecraft Dungeons II, which Mojang dated for September 29, 2026.',
           'Minecraft World, a themed attraction, opens in London in 2027.',
           'The Wilderness Bound game drop arrived on September 15 with the dappled forest, straw beds, abandoned camps and cushions.'],
   'impact': 'Minecraft accounts are valued on the account type (Java or Bedrock), the username and capes — not on in-game content. Updates like these change what players can do, not what an account is worth.'},
  'rbx-hunt': {
   'title': 'Roblox 20 “The Hunt”: limited UGC items and Roblox Plus exclusives (September 17–28)',
   'desc': 'The Hunt: Roblox 20 ran from September 17 to 28, 2026 with UGC rewards, limited-release UGC items and three exclusive items for Roblox Plus subscribers.',
   'lead': 'Roblox marked its 20th anniversary with The Hunt: Roblox 20, a platform-wide event that ran from September 17 to 28, 2026.',
   'new': ['Players moved through 20 years of Roblox history, one quest per year, starting in “Year Zero”; finishing all 20 unlocked “Year Infinity” with 20 more games.',
           'Quests awarded UGC items, and limited-release UGC items were available during the event.',
           'Roblox Plus subscribers received three exclusive virtual items and keep the Classic app theme, classic avatar background and profile frame after the event.',
           'The Classic app theme was free for everyone while the event ran.'],
   'impact': 'Items that could only be earned during an event are one of the things an appraisal looks at. Roblox did not name the items in its announcement, so this site does not price them until real listings exist.'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox creators earned about $1.7 billion in a year; Roblox Wallet announced',
   'desc': 'At RDC 2026 Roblox reported about $1.7 billion in creator earnings in 12 months and announced Roblox Wallet and Roblox Card for creator payouts.',
   'lead': 'At its developer conference RDC 2026 (announcement of September 11, 2026), Roblox shared creator-earnings figures and new payout tools.',
   'new': ['Creators have earned over $5 billion since DevEx launched in 2013, and about $1.7 billion in the 12 months to June 30, 2026.',
           'Roblox Plus incentives produced over 300 million Robux in creator earnings in their first four months (to August 17, 2026).',
           'Roblox Wallet, a payments account run with Airwallex US, will offer daily payouts in real currency — first for eligible U.S. independent creators aged 18+ later in 2026, internationally in 2027.',
           'A Roblox Card linked to the Wallet is planned from 2027.'],
   'impact': 'These changes concern creator payouts, not player accounts: the announcement did not change Robux prices, limited items or trading. Robux balance and limited items remain what our Roblox calculator weighs.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: four new Clash Squad weapons, Prime Diamond and a Kenta rework',
   'desc': 'Garena’s OB55 patch notes (September 10, 2026) add M7, Skorp, RPK and Hawk to Clash Squad from October 1, introduce Prime Diamond and rework Kenta.',
   'lead': 'Garena published the OB55 patch notes for Free Fire on September 10, 2026; the weapon changes take effect on October 1.',
   'new': ['New Clash Squad weapons from October 1: M7 (1,600 CS Cash), Skorp (1,500), RPK (1,500) and Hawk (1,700).',
           'Prime Diamond: diamonds earned according to monthly spending, claimable the following month after any top-up.',
           'Kenta is fully reworked; Morse, Luna and Wukong receive balance changes.',
           'Weapon-class mobility changes from October 1: SMGs faster, sniper and marksman rifles slower.'],
   'impact': 'Our Free Fire calculator weighs the diamond balance and rare bundles. OB55 changes how top-ups are rewarded going forward; it does not change the items already in existing accounts.'},
  'cr-minion': {
   'title': 'Clash Royale “Minion Academy” season: new card Minion Giant and the Ice Wizard hero',
   'desc': 'The Minion Academy season (September 7 – October 5, 2026) adds the Minion Giant card, an Ice Wizard hero and an album event with 1,750 Minion Giant cards.',
   'lead': 'Supercell opened the Clash Royale season “Minion Academy”, running from September 7 to October 5, 2026.',
   'new': ['New card Minion Giant: a flying win condition that targets buildings and towers. It is free through the Academy Antics album event and will not appear in chests until next season.',
           'The album event gives 1,750 Minion Giant cards, an emote and a tower skin.',
           'New hero: Ice Wizard, from the Pass Royale track or for 200 Hero Coins.',
           'Events: 2v2 League (Sept 7–21), Princess Gambit global tournament (Sept 21–26) and Royale Shuffle (Sept 21 – Oct 5). A draw in Ultimate Champion now costs half the trophies of a loss.'],
   'impact': 'Tower skins and emotes offered only during an event make a Clash Royale collection more distinctive, while King Tower level and card levels remain the main value drivers.'},
  'ml-10': {
   'title': 'Mobile Legends turns 10: ALL IN campaign and a new Layla Collector skin',
   'desc': 'MOONTON’s ALL IN 10th-anniversary campaign (from September 4, 2026) brings a new Nana Epic skin, free skin chests and a Layla Collector skin from October 9.',
   'lead': 'MOONTON Games launched ALL IN, the tenth-anniversary campaign for Mobile Legends: Bang Bang, on September 4, 2026.',
   'new': ['10th Anniversary Celebration Pass (Sept 4 – Nov 1): a new Nana Epic skin, an Epic Skin Selection Chest, a Random Epic Skin Chest and a free Returning Anniversary skin for returning players.',
           'Anniversary Gala Weekend (Sept 25 – Oct 11): access to 265 skins, Battle Pass EXP and Premium Skin Fragments.',
           'Layla’s Stellar Gala (Oct 9 – Nov 19): Layla’s new Collector skin through the “Starfall Breakout” mini-game.',
           'MOONTON cites more than 1.5 billion installs and 110 million monthly active players.'],
   'impact': 'Collector and Legend skins are among the most-cited value drivers for Mobile Legends accounts; skins handed out free or on trial are not.'},
  'bs-aug': {
   'title': 'Brawl Stars: Mythic brawlers Cosmo and Vince; Starr Road becomes Brawler Blast',
   'desc': 'Supercell’s August 2026 release notes (September 1) add two Mythic brawlers, rework Starr Road into Brawler Blast with new credit costs and rename Ultra Legendary to Ultra.',
   'lead': 'Supercell published the Brawl Stars release notes for the August 2026 update on September 1, 2026.',
   'new': ['Two new Mythic brawlers: Cosmo (Controller) and Vince (Damage Dealer).',
           'New Hypercharges for Nori and Wendy.',
           'Starr Road is reworked into “Brawler Blast”: Credits now go toward unlocks by rarity — Rare 160, Super Rare 430, Epic 925, Mythic 1,900, Legendary 3,800, Ultra 5,500.',
           'The “Ultra Legendary” rarity is renamed “Ultra”. Plus the Royal Academy season and a month-long Brawl-O-Ween event.'],
   'impact': 'Brawler count, Hypercharges and trophies are what our Brawl Stars calculator uses. Two more Mythics raise the number of brawlers a complete collection needs.'},
  'coc-aug': {
   'title': 'Clash of Clans August update: Diggy levels 11–15 and the Gold Pass from Town Hall 3',
   'desc': 'Supercell’s August 2026 update (August 30) adds Diggy levels 11–15 and new supercharges at Town Hall 18, retires the Starter Pass and opens the Gold Pass from Town Hall 3.',
   'lead': 'Supercell released the Clash of Clans August update on August 30, 2026.',
   'new': ['Town Hall 18: the Diggy pet gets levels 11–15; the Builder’s Hut and the Monolith get new supercharge levels.',
           'The Starter Pass is retired: Season Challenges and the Gold Pass are now available from Town Hall 3, with rewards scaled by Town Hall level.',
           'Ruin Knight no longer loses health over time; Ruin Witch summons 10 Ruin Knights instead of 8.',
           'Clan War League modifiers in the Titan leagues were adjusted.'],
   'impact': 'Town Hall level and hero and pet levels drive Clash of Clans account value in our research. New maximum levels at Town Hall 18 mean a “maxed” account now needs more upgrades than before the update.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 “Override”: Sonic Battle Pass and a KINGDOM HEARTS crossover',
   'desc': 'Epic’s Chapter 7 Season 4 “Override” brings Override Consoles, an 800 V-Bucks Battle Pass led by Sonic the Hedgehog and crossovers including KINGDOM HEARTS.',
   'lead': 'Fortnite’s Chapter 7 Season 4 is called “Override”. Epic describes a season built around gaming crossovers and match-wide rule changes.',
   'new': ['Override Consoles appear in every match and let players change the rules for the whole server.',
           'The Battle Pass costs 800 V-Bucks and is headlined by Sonic the Hedgehog, joined by a Tails Sidekick.',
           'Players who bought the Pass before August 27 at 11:59 PM ET received the Infiltrator Grace Crowne outfit as a launch-week bonus.',
           'Crossovers during the season: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot and Spyro the Dragon; weapons include Midas’ Masterpiece and Mega Man’s Mega Buster.'],
   'impact': 'Outfits available only for a limited time — such as a launch-week bonus — are what separate rare Fortnite lockers from common ones. Battle Pass outfits stay tied to the season they came from.'},
 }}}
