# News batch 3: kk, tk, ky (from news_text_b3_en.py, facts unchanged)
TEXT = {
'kk': {'a': {
 'cr-shock': {
  'title': 'Clash Royale Shocktober маусымы: Hero Electro Wizard және тегін Electro Giant Evolution',
  'desc': 'Shocktober маусымы 2026 жылғы 6 қазаннан 2 қарашаға дейін өтеді: Hero Electro Wizard жақсартылған Pass Royale-де, Electro Giant Evolution альбом оқиғасы арқылы тегін, жаңа белгілер.',
  'lead': 'Supercell Shocktober маусымын 2026 жылғы 5 қазанда жариялады; ол 6 қазаннан 2 қарашаға дейін өтеді.',
  'new': ['Жаңа Hero: Electro Wizard. Оның Surging Strikes қабілеті жақын тұрған екі жауды бір мезетте есеңгіретеді. Ол жақсартылған Pass Royale-де бар.',
          'Жаңа Evolution: Electro Giant. «Shocktober: The Movie!» альбом оқиғасын (6 қазан – 2 қараша, 3-аренадан бастап) аяқтағанда тегін ашылады; оқиға эмоция мен мұнара скинін де береді.',
          'Белгілер: Spooky Chess лигасында (5–19 қазан) екеуге дейін және Power Surge жаһандық турнирінде (20–25 қазан) біреу; әрқайсысында үздік 10 000-ға кіргендерге қосымша белгі бар.',
          '«20 жеңіс» сынағы 26 қазаннан 2 қарашаға дейін қайта оралады: 3-тен аз жеңіліспен 20 жеңіс үшін эмоция беріледі.'],
  'impact': 'Әр ойыншы тегін ала алатын Evolution бір аккаунтты екіншісінен айтарлықтай ерекшелемейді. Үздік 10 000 белгілерін алу қиынырақ, және олар профильде шеберлікті көрсетеді. Біздің зерттеуімізше, King Tower деңгейі мен карталар деңгейі құнның негізгі факторлары болып қала береді.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — қазанда Portal Pendant жабдығы және жаңа Hero скиндері',
  'desc': 'Cosmic Curse: Portal Panic 2026 жылғы 1–31 қазанда өтеді: медаль оқиғасынан (8–25 қазан) Minion Prince үшін эпикалық жабдық Portal Pendant, Hero скиндері және Gold Pass скині.',
  'lead': 'Supercell Clash-O-Ween маусымы «Cosmic Curse: Portal Panic» туралы 2026 жылғы 1 қазанда жариялады; ол 31 қазанға дейін жалғасады.',
  'new': ['Portal Panic медаль оқиғасы, 8–25 қазан, Town Hall 6 және одан жоғары: шайқастарда жиналған Sour Elixir сыйлықтар мен Rift Medals ашады, оларға Trader дүкенінен жаңа Portal Pendant — Minion Prince үшін эпикалық жабдық — алынады (дүкен 27 қазанға дейін ашық).',
          'Gold Pass, 1–31 қазан: маусымның эксклюзивті Hero скині — Shroud Queen, балама нұсқа — Ghost Champion.',
          'Ай ішінде шығатын Hero скиндері: Savage King (5 қазан), Nasty Prince (7 қазан), Terror Champion (9 қазан), Behemoth Duke (11 қазан) және Spider Warden (13 қазан); Cosmic Portals XL көрінісі 3 қазаннан бастап.',
          'Маусым бойы уақытша жасақ Totem Thrower қосылады, ал 2025 жылғы Cosmic Curse косметикасы 15 қазанда қайта оралады.'],
  'impact': 'Hero жабдығы мен Hero скиндері аккаунтта қалады, сондықтан аккаунт көрсететін нәрселерге қосылады. Біздің зерттеуімізше, Town Hall деңгейі және батырлардың сол деңгей үшін қаншалықты толық дамығаны құнның негізгі факторлары болып қала береді; маусымдық скиндер — екінші кезектегі деталь.'},
 'coc-ore': {
  'title': 'Clash of Clans Ore үшін Gem бағасын төмендетті: Starry Ore 35-тен 20 Gem-ге',
  'desc': 'Supercell 2026 жылғы 2 қазанда Ore үшін жаңа негізгі Gem бағаларын жариялады: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Эпикалық жабдықты ең жоғары деңгейге жеткізу шамамен екі есе аз Gem талап етеді.',
  'lead': '2026 жылғы 2 қазанда Supercell Clash of Clans-та Ore үшін Gem бағалары төмендейтінін жариялады — бұл уақытша жеңілдік емес, жаңа негізгі баға.',
  'new': ['Жаңа бағалар: Shiny Ore 1 Gem → 0,5 Gem, Glowy Ore 5 → 3 Gem, Starry Ore 35 → 20 Gem.',
          'Supercell мәліметінше, бір эпикалық жабдықты ең жоғары деңгейге жеткізудің Gem құны шамамен екі есе азаяды.',
          'Trader жаңа бағаларды шілдеден бері қолданып келеді; медаль дүкені қазандағы медаль оқиғасында ауысады, ал келесі толық жаңарту оларды ойынның барлық жерінде стандартқа айналдырады.',
          'Ore экономикасындағы тағы өзгерістер қазанның соңына қарай уәде етілген.'],
  'impact': 'Ең жоғары деңгейдегі Hero жабдығына жету арзандайды, сондықтан ол жоғары Town Hall аккаунттарында жиірек кездесуі мүмкін. Біздің зерттеуімізше, Town Hall деңгейі мен батырлардың дамуы құнның негізгі факторлары болып қала береді.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: әр аймақтағы сегіз команда қалай таңдалады',
  'desc': 'Supercell 2026 жылғы 1 қазанда командалардың BSC 2027-ге қалай өтетінін түсіндірді: 2026 жылғы рейтингтен әр аймаққа алты тікелей шақыру және 2027 жылғы 16–17 қаңтардағы BSC Invitational-дан екі орын.',
  'lead': '2026 жылғы 1 қазанда Supercell Brawl Stars Championship 2027 іріктеу жолын жариялады.',
  'new': ['BSC 2027-де төрт аймақтың әрқайсысында сегіз командадан бар: APAC, EMEA, Оңтүстік Америка және Солтүстік Америка.',
          'Әр аймақтың 2026 жылғы BSC Leaderboard-ындағы үздік алты команда тікелей шақыру алады және ең көбі бір ойыншыны ауыстыра алады.',
          'Әр аймақтағы соңғы екі орын 2027 жылғы 16–17 қаңтардағы BSC Invitational-да шешіледі: 7–10-орындағы командалар ойнайды, ал EMEA-да 7–14-орындағылар.',
          'Шақырулар 2026 жылғы 23 қарашада жіберіледі, командалар 20 желтоқсанға дейін жауап беруі керек; Supercell күндер өзгеруі мүмкін екенін айтады. Жаңа командалар ойын ішіндегі Championship Challenge және Brawl Stars Challengers-тен бастайды.'],
  'impact': 'Киберспорттық іріктеу қарапайым аккаунттың құнын өзгертпейді. Біздің зерттеуімізше, хабарландырулардағы баға әлі де кубоктарға, brawler-лерге және олардың Power Level деңгейіне байланысты.'},
}},
'tk': {'a': {
 'cr-shock': {
  'title': 'Clash Royale Shocktober möwsümi: Hero Electro Wizard we mugt Electro Giant Evolution',
  'desc': 'Shocktober möwsümi 2026-njy ýylyň 6-njy oktýabryndan 2-nji noýabryna çenli dowam edýär: Hero Electro Wizard gowulandyrylan Pass Royale-de, Electro Giant Evolution albom çäresi arkaly mugt, täze nyşanlar.',
  'lead': 'Supercell Shocktober möwsümini 2026-njy ýylyň 5-nji oktýabrynda yglan etdi; ol 6-njy oktýabrdan 2-nji noýabra çenli dowam edýär.',
  'new': ['Täze Hero: Electro Wizard. Onuň Surging Strikes ukyby ýakyndaky iki duşmany bir wagtda sersepledýär. Ol gowulandyrylan Pass Royale-de bar.',
          'Täze Evolution: Electro Giant. «Shocktober: The Movie!» albom çäresini (6-njy oktýabr – 2-nji noýabr, 3-nji arenadan başlap) tamamlanyňda mugt açylýar; çäre emote we diň skinini hem berýär.',
          'Nyşanlar: Spooky Chess ligasynda (5–19-njy oktýabr) ikä çenli we Power Surge global ýaryşynda (20–25-nji oktýabr) bir sany; her birinde iň gowy 10 000-lige girenlere goşmaça nyşan bar.',
          '«20 ýeňiş» synagy 26-njy oktýabrdan 2-nji noýabra çenli gaýdyp gelýär: 3-den az ýeňliş bilen 20 ýeňiş üçin emote berilýär.'],
  'impact': 'Her oýunçynyň mugt alyp bilýän Evolution-y bir hasaby beýlekisinden kän tapawutlandyrmaýar. Iň gowy 10 000-lik nyşanlaryny almak kynrak we olar profilde ussatlygy görkezýär. Biziň barlagymyza görä, King Tower derejesi we kartlaryň derejesi gymmatyň esasy faktorlary bolmagynda galýar.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — oktýabrda Portal Pendant enjamy we täze Hero skinleri',
  'desc': 'Cosmic Curse: Portal Panic 2026-njy ýylyň 1–31-nji oktýabrynda geçýär: medal çäresinden (8–25-nji oktýabr) Minion Prince üçin epiki enjam Portal Pendant, Hero skinleri we Gold Pass skini.',
  'lead': 'Supercell Clash-O-Ween möwsümi «Cosmic Curse: Portal Panic» barada 2026-njy ýylyň 1-nji oktýabrynda yglan etdi; ol 31-nji oktýabra çenli dowam edýär.',
  'new': ['Portal Panic medal çäresi, 8–25-nji oktýabr, Town Hall 6 we ondan ýokary: söweşlerde ýygnalan Sour Elixir sylaglary we Rift Medals-y açýar, olara Trader dükanyndan täze Portal Pendant — Minion Prince üçin epiki enjam — alynýar (dükan 27-nji oktýabra çenli açyk).',
          'Gold Pass, 1–31-nji oktýabr: möwsümiň aýratyn Hero skini — Shroud Queen, alternatiw görnüşi — Ghost Champion.',
          'Aýyň dowamynda çykýan Hero skinleri: Savage King (5-nji oktýabr), Nasty Prince (7-nji oktýabr), Terror Champion (9-njy oktýabr), Behemoth Duke (11-nji oktýabr) we Spider Warden (13-nji oktýabr); Cosmic Portals XL görnüşi 3-nji oktýabrdan.',
          'Möwsümiň dowamynda wagtlaýyn goşun Totem Thrower goşulýar, 2025-nji ýylyň Cosmic Curse kosmetikasy bolsa 15-nji oktýabrda gaýdyp gelýär.'],
  'impact': 'Hero enjamlary we Hero skinleri hasapda galýar, şonuň üçin hasabyň görkezýän zatlaryna goşulýar. Biziň barlagymyza görä, Town Hall derejesi we gahrymanlaryň şol dereje üçin näderejede doly ösdürilendigi gymmatyň esasy faktorlary bolmagynda galýar; möwsümleýin skinler ikinji derejeli jikme-jiklik.'},
 'coc-ore': {
  'title': 'Clash of Clans Ore üçin Gem bahalaryny arzanlatdy: Starry Ore 35-den 20 Gem-e',
  'desc': 'Supercell 2026-njy ýylyň 2-nji oktýabrynda Ore üçin täze esasy Gem bahalaryny yglan etdi: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Epiki enjamy iň ýokary derejä ýetirmek takmynan iki esse az Gem talap edýär.',
  'lead': '2026-njy ýylyň 2-nji oktýabrynda Supercell Clash of Clans-da Ore üçin Gem bahalarynyň arzanlaýandygyny yglan etdi — bu wagtlaýyn arzanladyş däl, täze esasy baha.',
  'new': ['Täze bahalar: Shiny Ore 1 Gem → 0,5 Gem, Glowy Ore 5 → 3 Gem, Starry Ore 35 → 20 Gem.',
          'Supercell-iň aýtmagyna görä, bir epiki enjamy iň ýokary derejä ýetirmegiň Gem bahasy takmynan iki esse azalýar.',
          'Trader täze bahalary iýuldan bäri ulanýar; medal dükany oktýabrdaky medal çäresinde geçýär, indiki doly täzelenme bolsa olary oýnuň ähli ýerinde standart edýär.',
          'Ore ykdysadyýetinde ýene üýtgeşmeler oktýabryň ahyryna wada berildi.'],
  'impact': 'Iň ýokary derejeli Hero enjamyna ýetmek arzanlaýar, şonuň üçin ol ýokary Town Hall hasaplarynda has ýygy duş gelip biler. Biziň barlagymyza görä, Town Hall derejesi we gahrymanlaryň ösüşi gymmatyň esasy faktorlary bolmagynda galýar.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: her sebitdäki sekiz topar nähili saýlanýar',
  'desc': 'Supercell 2026-njy ýylyň 1-nji oktýabrynda toparlaryň BSC 2027-ä nähili düşýändigini düşündirdi: 2026-njy ýylyň reýtinginden her sebite alty göni çakylyk we 2027-nji ýylyň 16–17-nji ýanwaryndaky BSC Invitational-dan iki orun.',
  'lead': '2026-njy ýylyň 1-nji oktýabrynda Supercell Brawl Stars Championship 2027 saýlama ýoluny çap etdi.',
  'new': ['BSC 2027-de dört sebitiň her birinde sekiz topar bar: APAC, EMEA, Günorta Amerika we Demirgazyk Amerika.',
          'Her sebitiň 2026-njy ýyldaky BSC Leaderboard-yndaky iň gowy alty topar göni çakylyk alýar we iň köp bir oýunçyny çalşyp bilýär.',
          'Her sebitdäki soňky iki orun 2027-nji ýylyň 16–17-nji ýanwaryndaky BSC Invitational-da çözülýär: 7–10-njy orundaky toparlar oýnaýar, EMEA-da bolsa 7–14-nji orundakylar.',
          'Çakylyklar 2026-njy ýylyň 23-nji noýabrynda iberilýär, toparlar 20-nji dekabra çenli jogap bermeli; Supercell seneleriň üýtgäp biljekdigini belleýär. Täze toparlar oýnuň içindäki Championship Challenge we Brawl Stars Challengers-den başlaýar.'],
  'impact': 'Kibersport saýlamasy adaty hasabyň gymmatyny üýtgetmeýär. Biziň barlagymyza görä, bildirişlerdäki baha henizem kuboklara, brawlerlere we olaryň Power Level derejesine bagly.'},
}},
'ky': {'a': {
 'cr-shock': {
  'title': 'Clash Royale Shocktober сезону: Hero Electro Wizard жана акысыз Electro Giant Evolution',
  'desc': 'Shocktober сезону 2026-жылдын 6-октябрынан 2-ноябрына чейин өтөт: Hero Electro Wizard жакшыртылган Pass Royale’де, Electro Giant Evolution альбом иш-чарасы аркылуу акысыз, жаңы белгилер.',
  'lead': 'Supercell Shocktober сезонун 2026-жылдын 5-октябрында жарыялады; ал 6-октябрдан 2-ноябрга чейин өтөт.',
  'new': ['Жаңы Hero: Electro Wizard. Анын Surging Strikes жөндөмү жакын турган эки душманды бир убакта эсеңгиретет. Ал жакшыртылган Pass Royale’де бар.',
          'Жаңы Evolution: Electro Giant. «Shocktober: The Movie!» альбом иш-чарасын (6-октябрь – 2-ноябрь, 3-аренадан баштап) бүтүргөндө акысыз ачылат; иш-чара эмоция менен мунара скинин да берет.',
          'Белгилер: Spooky Chess лигасында (5–19-октябрь) экиге чейин жана Power Surge глобалдык турниринде (20–25-октябрь) бирөө; ар биринде мыкты 10 000ге киргендерге кошумча белги бар.',
          '«20 жеңиш» сыноосу 26-октябрдан 2-ноябрга чейин кайтып келет: 3төн аз жеңилүү менен 20 жеңиш үчүн эмоция берилет.'],
  'impact': 'Ар бир оюнчу акысыз ала турган Evolution бир аккаунтту экинчисинен дээрлик айырмалабайт. Мыкты 10 000 белгилерин алуу кыйыныраак жана алар профилде чеберчиликти көрсөтөт. Биздин изилдөөбүз боюнча, King Tower деңгээли жана карталардын деңгээли баалуулуктун негизги факторлору бойдон калууда.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — октябрда Portal Pendant жабдыгы жана жаңы Hero скиндери',
  'desc': 'Cosmic Curse: Portal Panic 2026-жылдын 1–31-октябрында өтөт: медаль иш-чарасынан (8–25-октябрь) Minion Prince үчүн эпикалык жабдык Portal Pendant, Hero скиндери жана Gold Pass скини.',
  'lead': 'Supercell Clash-O-Ween сезону «Cosmic Curse: Portal Panic» тууралуу 2026-жылдын 1-октябрында жарыялады; ал 31-октябрга чейин уланат.',
  'new': ['Portal Panic медаль иш-чарасы, 8–25-октябрь, Town Hall 6 жана андан жогору: салгылашууларда чогулган Sour Elixir сыйлыктарды жана Rift Medals ачат, аларга Trader дүкөнүнөн жаңы Portal Pendant — Minion Prince үчүн эпикалык жабдык — алынат (дүкөн 27-октябрга чейин ачык).',
          'Gold Pass, 1–31-октябрь: сезондун эксклюзивдүү Hero скини — Shroud Queen, альтернативдүү вариант — Ghost Champion.',
          'Ай ичинде чыга турган Hero скиндери: Savage King (5-октябрь), Nasty Prince (7-октябрь), Terror Champion (9-октябрь), Behemoth Duke (11-октябрь) жана Spider Warden (13-октябрь); Cosmic Portals XL көрүнүшү 3-октябрдан баштап.',
          'Сезон бою убактылуу аскер Totem Thrower кошулат, ал эми 2025-жылдагы Cosmic Curse косметикасы 15-октябрда кайтып келет.'],
  'impact': 'Hero жабдыгы жана Hero скиндери аккаунтта калат, ошондуктан аккаунт көрсөткөн нерселерге кошулат. Биздин изилдөөбүз боюнча, Town Hall деңгээли жана баатырлардын ошол деңгээл үчүн канчалык толук өнүккөнү баалуулуктун негизги факторлору бойдон калууда; сезондук скиндер — экинчи даражадагы деталь.'},
 'coc-ore': {
  'title': 'Clash of Clans Ore үчүн Gem бааларын түшүрдү: Starry Ore 35тен 20 Gemге',
  'desc': 'Supercell 2026-жылдын 2-октябрында Ore үчүн жаңы негизги Gem бааларын жарыялады: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Эпикалык жабдыкты эң жогорку деңгээлге жеткирүү болжол менен эки эсе аз Gem талап кылат.',
  'lead': '2026-жылдын 2-октябрында Supercell Clash of Clans’та Ore үчүн Gem баалары төмөндөй турганын жарыялады — бул убактылуу арзандатуу эмес, жаңы негизги баа.',
  'new': ['Жаңы баалар: Shiny Ore 1 Gem → 0,5 Gem, Glowy Ore 5 → 3 Gem, Starry Ore 35 → 20 Gem.',
          'Supercell’дин айтымында, бир эпикалык жабдыкты эң жогорку деңгээлге жеткирүүнүн Gem наркы болжол менен эки эсе азаят.',
          'Trader жаңы бааларды июлдан бери колдонуп келет; медаль дүкөнү октябрдагы медаль иш-чарасында өтөт, ал эми кийинки толук жаңыртуу аларды оюндун бардык жеринде стандарт кылат.',
          'Ore экономикасындагы дагы өзгөрүүлөр октябрдын аягына карата убада кылынган.'],
  'impact': 'Эң жогорку деңгээлдеги Hero жабдыгына жетүү арзандайт, ошондуктан ал жогорку Town Hall аккаунттарында көбүрөөк кездешиши мүмкүн. Биздин изилдөөбүз боюнча, Town Hall деңгээли жана баатырлардын өнүгүүсү баалуулуктун негизги факторлору бойдон калууда.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: ар бир аймактагы сегиз команда кантип тандалат',
  'desc': 'Supercell 2026-жылдын 1-октябрында командалар BSC 2027’ге кантип өтөрүн түшүндүрдү: 2026-жылдагы рейтингден ар бир аймакка алты түз чакыруу жана 2027-жылдын 16–17-январындагы BSC Invitational’дан эки орун.',
  'lead': '2026-жылдын 1-октябрында Supercell Brawl Stars Championship 2027 тандоо жолун жарыялады.',
  'new': ['BSC 2027’де төрт аймактын ар биринде сегизден команда бар: APAC, EMEA, Түштүк Америка жана Түндүк Америка.',
          'Ар бир аймактын 2026-жылдагы BSC Leaderboard’ундагы мыкты алты команда түз чакыруу алат жана эң көп бир оюнчуну алмаштыра алат.',
          'Ар бир аймактагы акыркы эки орун 2027-жылдын 16–17-январындагы BSC Invitational’да чечилет: 7–10-орундагы командалар ойнойт, ал эми EMEA’да 7–14-орундагылар.',
          'Чакыруулар 2026-жылдын 23-ноябрында жөнөтүлөт, командалар 20-декабрга чейин жооп бериши керек; Supercell күндөр өзгөрүшү мүмкүн экенин белгилейт. Жаңы командалар оюн ичиндеги Championship Challenge жана Brawl Stars Challengers’тен баштайт.'],
  'impact': 'Киберспорттук тандоо кадимки аккаунттун баасын өзгөртпөйт. Биздин изилдөөбүз боюнча, жарыялардагы баа дагы эле кубокторго, brawler’лерге жана алардын Power Level деңгээлине көз каранды.'},
}},
}
