# News batch 2 — English master texts (facts: scripts/research/news-2026-09.md, "Batch 2")
TEXT = {'en': {'a': {
 'mc-d2': {
  'title': 'Minecraft Dungeons II is out: the Sift dimension and the Illager High Council',
  'desc': 'Mojang launched Minecraft Dungeons II on September 29, 2026 on Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch and Switch 2, with co-op for up to 4 players.',
  'lead': 'Mojang Studios launched Minecraft Dungeons II on September 29, 2026.',
  'new': ['Available on Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch and Nintendo Switch 2.',
          'The story pits players against the Illager High Council — the Prime Enchanter, the Supreme Evoker and the Grand Illusioner.',
          'Players explore a new dimension, the Sift, which Mojang says will also come to Minecraft Java and Bedrock next year.',
          'Solo play or co-op for up to 4 players, online or on the same screen.'],
  'impact': 'Dungeons II is a separate game. Minecraft Java and Bedrock accounts are still valued on account type, username and capes, so the launch does not change what they are worth.'},
 'cr-mt-oct': {
  'title': 'Clash Royale Merge Tactics: October changes to Supers, Elixir and badges',
  'desc': 'From October 1, 2026, Merge Tactics season 11 moves Supers into the shared pool, cuts Elixir per round from 5 to 4 and adds Level 5 skins; badge rules change in season 12.',
  'lead': 'Supercell announced the October changes for Merge Tactics season 11 on September 30, 2026; they apply from October 1.',
  'new': ['Supers are no longer starting troops: they go into the shared pool, where every player can compete for them.',
          'Elixir earned each round goes back from 5 to 4.',
          'Battle Machine and Dagger Duchess get Level 5 skins for players who have already upgraded them.',
          'From season 12, the Silver badge requires reaching Diamond League and the Gold badge a Top 10,000 finish.'],
  'impact': 'Badges that need a high finish become harder to earn from season 12, which makes them a clearer sign of skill on a Clash Royale profile. King Tower and card levels remain the main value drivers.'},
 'ml-mplph': {
  'title': 'MPL Philippines Season 18 playoffs: PhilSports Arena, October 21–25',
  'desc': 'MOONTON announced on September 26, 2026 that the MPL Philippines Season 18 playoffs run October 21–25 at PhilSports Arena, deciding the Philippine teams for M8.',
  'lead': 'MOONTON Games announced the venue and dates of the MPL Philippines Season 18 playoffs on September 26, 2026.',
  'new': ['The playoffs take place at PhilSports Arena in Pasig City from October 21 to 25, 2026.',
          'They decide which teams represent the Philippines at the M8 World Championship in Istanbul in January 2027.',
          'Ticket sales opened on September 26, with prices from PHP 200.',
          'The announcement marks the game’s 10th anniversary, citing 1.5 billion installs and 110 million monthly active players.'],
  'impact': 'Esports events do not change the value of existing accounts. Skins, heroes and account progress remain what drives Mobile Legends value in our research.'},
 'cr-bal-sep': {
  'title': 'Clash Royale September balance changes: Hero Ice Wizard and Minion Giant nerfed',
  'desc': 'Supercell’s September 2026 balance notes cut the Hero Ice Wizard freeze from 7 to 5 seconds and Minion Giant damage from 189 to 168, plus reworks for Hero Mega Minion and Hero Wizard.',
  'lead': 'Supercell published two rounds of Clash Royale balance changes, applied on September 8 and September 16, 2026.',
  'new': ['September 16: Hero Ice Wizard freeze 7 s → 5 s; Goblinstein ability 4 s → 3.5 s; Minion Giant damage 189 → 168; Fire Spirit damage 207 → 215.',
          'September 8: Freeze 4 s → 3.5 s; Fireball Crown Tower damage 172 → 159; Ice Golem hitpoints 1,315 → 1,228.',
          'Reworks: Hero Mega Minion (warps back, warp damage 399 → 422) and Hero Wizard (ability 5 s → 3.5 s); Wizard damage 281 → 304.',
          'Buffs include Ronin, Spirit Empress and Goblin Cage.'],
  'impact': 'Balance changes shift which cards are popular, not what an account owns. In our research Clash Royale value follows King Tower level, card levels, evolutions and rare cosmetics.'},
 'gi-wish71': {
  'title': 'Genshin Impact 7.1 event wishes: Vesna and Vodyanitsa banners until October 13',
  'desc': 'HoYoverse’s Version 7.1 Phase I event wishes boost Vesna and Vodyanitsa until October 13, 2026, with Diona, Faruzan and Chongyun as boosted 4-star characters.',
  'lead': 'HoYoverse published the Version 7.1 Phase I event wishes on September 21, 2026; they run until October 13, 2026, 17:59.',
  'new': ['“When Warm Winds Cavort” boosts the drop rate of Vesna (Anemo).',
          '“Surging Ballad” boosts the drop rate of Vodyanitsa (Hydro).',
          'Boosted 4-star characters: Diona (Cryo), Faruzan (Anemo) and Chongyun (Cryo).',
          'Event-exclusive characters are not in the standard wish; the two character banners share one pity counter.'],
  'impact': 'Characters that can only be obtained from limited banners — and their constellations — are among the main value drivers of Genshin accounts in our research.'},
 'bs-duo': {
  'title': 'Brawl Stars × Duolingo: Trash Goblin Darryl skin and rewards until September 30',
  'desc': 'Supercell’s Brawl Stars × Duolingo event (announced September 19, 2026) gives the Trash Goblin Darryl skin, gems, Starr Drops and more until September 30.',
  'lead': 'Supercell announced the Brawl Stars × Duolingo crossover on September 19, 2026; it ran until September 30.',
  'new': ['Two phases of community goals and in-game tasks, plus a new Duo Boss Fight mode.',
          'Rewards include the Trash Goblin Darryl skin, 20 Gems, 5 Chaos Drops, 3 Mythic Starr Drops, 2,000 Coins, 2,500 Bling and 1,000 Credits.',
          'A Brawl Stars quest inside the Duolingo app gives extra cosmetics.',
          'Supercell also ran a trivia giveaway of 3.141592 million gems on its social channels.'],
  'impact': 'Skins tied to a one-time crossover are what make some Brawl Stars collections stand out; a skin many players received for free adds less than a rare paid one.'},
 'ff-naruto': {
  'title': 'Free Fire × NARUTO SHIPPUDEN returns: Nine Tails, Hinata bundle (September 16 – October 15)',
  'desc': 'Garena’s NARUTO SHIPPUDEN collaboration runs September 16 – October 15, 2026 with the Sharingan: Control skill, a pick-one Jiraiya or Hinata bundle and themed cosmetics.',
  'lead': 'Garena announced on September 15, 2026 that the Free Fire × NARUTO SHIPPUDEN collaboration returns from September 16 to October 15.',
  'new': ['New skills: Sharingan: Control, which commands Nine Tails, and 8 Trigrams Palm Rotation.',
          'An expanded Ninja Academy in the Hidden Leaf Village map.',
          'A pick-one grand prize: the Jiraiya bundle or the Hinata bundle (Hinata’s debut).',
          'Cosmetics include Tsunade’s Cloak, Gaara’s Tattoo Facepaint, Kakashi’s ANBU Black Ops Mask and the Froggy Wallet crate.'],
  'impact': 'Bundles from licensed collaborations that are only available for a limited time are among the rare items our Free Fire calculator looks for.'},
 'ml-mtc8': {
  'title': 'MLBB Türkiye Championship Season 8 starts on the road to M8 in Istanbul',
  'desc': 'MTC Season 8 runs September 12 – October 18, 2026 with eight teams and a US$40,000 prize pool, ahead of the M8 World Championship in Istanbul in January 2027.',
  'lead': 'MOONTON Games announced on September 10, 2026 that the MLBB Türkiye Championship Season 8 starts on September 12.',
  'new': ['Regular season from September 12 to October 18; the grand finals are on November 7, 2026.',
          'Eight teams take part, including Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok and Dark Passage.',
          'The top six teams go to the playoffs for a share of the US$40,000 prize pool.',
          'The M8 World Championship will be held in Istanbul in January 2027 — the first M Series event in Europe.'],
  'impact': 'Esports results do not change the value of existing accounts; Collector and Legend skins and hero count remain the main value drivers in our research.'},
 'coc-blast': {
  'title': 'Clash of Clans Equipment Blast medal event (September 9–22)',
  'desc': 'The Equipment Blast event ran September 9–22, 2026: earn Tag Tickets and Champ Medals and spend them in the Trader on hero equipment, ore and cosmetics. Town Hall 6+.',
  'lead': 'Supercell announced the Equipment Blast medal event on September 9, 2026; it ran until September 22 at 08:00 UTC, with the Trader open until September 24.',
  'new': ['Multiplayer battles earn Tag Tickets; the event track rewards Champ Medals, temporary troops and chests.',
          'The Trader sells hero equipment, ore and cosmetics for event medals.',
          'Temporary troops: Undertaker Yeti, K.A.N.E., Yeeter and Giant Giant.',
          'Available from Town Hall 6.'],
  'impact': 'Hero equipment and its levels feed into the hero strength that drives Clash of Clans account value in our research; event medals are one more way to upgrade it.'},
 'mc-wild': {
  'title': 'Minecraft Wilderness Bound drop: the dappled forest, straw beds and abandoned camps',
  'desc': 'Mojang’s Wilderness Bound game drop arrived on September 15, 2026 with the dappled forest biome, poplar wood, straw beds, abandoned camps and cushions.',
  'lead': 'Mojang Studios named its third game drop of 2026 “Wilderness Bound” on September 5 and released it on September 15.',
  'new': ['A new biome, the dappled forest, with tall poplar trees and shelf mushrooms.',
          'Straw beds made from three hay bales let players skip the night without resetting their spawn point.',
          'Abandoned camps to explore, and cushions crafted from three wool slabs of the same color.',
          'Poplar wood plus expanded concrete and wool building sets.'],
  'impact': 'Minecraft accounts are valued on account type, username and capes, not on game content, so a game drop does not change what an account is worth.'},
 'ff-award': {
  'title': 'Free Fire wins “Best Use of IP or Licence” at the Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena said on September 3, 2026 that Free Fire won Best Use of IP or Licence at the Pocket Gamer Mobile Games Awards 2026 for its NARUTO SHIPPUDEN collaboration.',
  'lead': 'Garena announced on September 3, 2026 that Free Fire won “Best Use of IP or Licence” at the Pocket Gamer Mobile Games Awards 2026.',
  'new': ['The award recognises the NARUTO SHIPPUDEN Chapter 2: Ninja War collaboration.',
          'Garena reports that its Ninja Clash All Stars event in Bangkok drew nearly 5,000 visitors and over 247 million video views.',
          'The collaboration included themed characters, jutsu abilities and a transformed Hidden Leaf Village map.',
          'Community events ran in Peru, Bangladesh, Malaysia and Taiwan.'],
  'impact': 'An award does not change account values. It does confirm that licensed collaborations are a regular part of Free Fire — and limited collaboration bundles are among the rare items appraisals look for.'},
 'rbx-fall': {
  'title': 'Roblox Fall Games Preview: 10 experiences arriving in September and October',
  'desc': 'Roblox’s Fall Games Preview (September 2, 2026) lists 10 new experiences, from Showdown and Nemesis in September to Prime Heroes, Octane and Starforged in October.',
  'lead': 'Roblox published its Fall Games Preview on September 2, 2026, listing ten experiences due in September and October.',
  'new': ['September: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force and Caramel.',
          'October: Prime Heroes (early access in September with 6 heroes), Octane, Starforged and Scrapbook Saga.',
          'Several titles come from Roblox’s Jumpstart and Incubator creator programmes.',
          'Genres range from shooters and racing to survival horror and farming.'],
  'impact': 'New experiences do not change existing accounts. Roblox account value in our research comes from Robux, limited items and items inside long-running experiences; a new game only matters once its items trade.'},
 'coc-wwe': {
  'title': 'Clash of Clans × WWE: one-time hero skins that “will not return” after October 1',
  'desc': 'Supercell’s WWE: Search for Cena event (September 2026) sold six WWE hero skins that Supercell says will not return after October 1, plus Money in the Bank scenery.',
  'lead': 'Supercell announced the WWE: Search for Cena event for Clash of Clans on September 1, 2026; it ran through September.',
  'new': ['Hero skins at $9.99 each: Cody Rhodes (Barbarian King), Alexa Bliss (Archer Queen), Iyo Sky (Royal Champion), Kane (Dragon Duke) and American Badass Undertaker (Grand Warden).',
          'Jey Uso (Minion Prince) came with the Gold Pass.',
          'Supercell says the skins “will not return. Ever” after October 1.',
          'Money in the Bank XL scenery was available from September 2 to 30, alongside a John Cena challenge and temporary WWE troops.'],
  'impact': 'Skins the publisher says will never return are exactly the kind of cosmetics that make a Clash of Clans account rarer. Town Hall and hero levels still carry most of the value.'},
 'bs-bsc27': {
  'title': 'Brawl Stars Championship 2027: first look at the new two-split format',
  'desc': 'Supercell’s first look at BSC 2027 (August 24, 2026): eight teams per region in four regions, Challengers in 12 regions, two 12-week splits, the Brawl Cup and the World Finals.',
  'lead': 'Supercell gave a first look at the 2027 Brawl Stars Championship on August 24, 2026, noting that details may still change.',
  'new': ['Top level: 8 teams per region in East Asia, EMEA, South America and North America.',
          'Challengers: an entry path in 12 regions.',
          'Two splits of 12 weeks each; Split 1 ends with the Brawl Cup, a three-day international LAN, and Split 2 with the World Finals.',
          'Dates, prize pool and locations have not been announced yet.'],
  'impact': 'Esports formats do not change the value of existing accounts; brawler count, Hypercharges and trophies remain what our Brawl Stars calculator uses.'},
}}}
