# News batch 2: tr, ar (from news_text_b2_en.py, facts unchanged)
TEXT = {
'tr': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II çıktı: Sift boyutu ve Illager Yüksek Konseyi',
  'desc': 'Mojang, Minecraft Dungeons II’yi 29 Eylül 2026’da Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch ve Switch 2’de 4 oyunculu ortak oyun desteğiyle çıkardı.',
  'lead': 'Mojang Studios, Minecraft Dungeons II’yi 29 Eylül 2026’da çıkardı.',
  'new': ['Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch ve Nintendo Switch 2’de satışta.',
          'Hikâyede oyuncular Illager Yüksek Konseyi’ne karşı savaşıyor: Prime Enchanter, Supreme Evoker ve Grand Illusioner.',
          'Oyuncular yeni bir boyutu, Sift’i keşfediyor; Mojang’a göre bu boyut gelecek yıl Minecraft Java ve Bedrock’a da gelecek.',
          'Tek başına ya da çevrim içi veya aynı ekranda 4 kişiye kadar ortak oynanabiliyor.'],
  'impact': 'Dungeons II ayrı bir oyun. Minecraft Java ve Bedrock hesapları hâlâ hesap türü, kullanıcı adı ve pelerinlere göre değerleniyor; bu çıkış değerlerini değiştirmiyor.'},
 'cr-mt-oct': {'title': 'Clash Royale Merge Tactics: Süperler, iksir ve rozetlerde ekim değişiklikleri',
  'desc': '1 Ekim 2026’dan itibaren Merge Tactics 11. sezonunda Süperler ortak havuza geçiyor, tur başına iksir 5’ten 4’e iniyor ve 5. seviye görünümler geliyor; rozet kuralları 12. sezonda değişiyor.',
  'lead': 'Supercell, Merge Tactics 11. sezonunun ekim değişikliklerini 30 Eylül 2026’da duyurdu; değişiklikler 1 Ekim’den itibaren geçerli.',
  'new': ['Süperler artık başlangıç birliği olarak verilmiyor; tüm oyuncuların yarıştığı ortak havuza giriyor.',
          'Tur başına kazanılan iksir 5’ten tekrar 4’e iniyor.',
          'Savaş Makinesi ve Hançer Düşesi, onları zaten yükseltmiş oyuncular için 5. seviye görünümler alıyor.',
          '12. sezondan itibaren gümüş rozet için Elmas Lig’e ulaşmak, altın rozet için ilk 10.000’e girmek gerekiyor.'],
  'impact': '12. sezondan itibaren yüksek sıralama rozetleri daha zor kazanılacak; bu da bir Clash Royale profilinde beceriyi daha net gösterecek. Kral Kulesi ve kart seviyeleri ana değer belirleyiciler olmaya devam ediyor.'},
 'ml-mplph': {'title': 'MPL Filipinler 18. sezon play-off’ları: PhilSports Arena, 21–25 Ekim',
  'desc': 'MOONTON, 26 Eylül 2026’da MPL Filipinler 18. sezon play-off’larının 21–25 Ekim’de PhilSports Arena’da yapılacağını ve M8 için Filipin takımlarını belirleyeceğini duyurdu.',
  'lead': 'MOONTON Games, MPL Filipinler 18. sezon play-off’larının yerini ve tarihlerini 26 Eylül 2026’da açıkladı.',
  'new': ['Play-off’lar 21–25 Ekim 2026’da Pasig’deki PhilSports Arena’da oynanacak.',
          'Ocak 2027’de İstanbul’daki M8 Dünya Şampiyonası’nda Filipinler’i temsil edecek takımları belirleyecek.',
          'Bilet satışı 26 Eylül’de 200 Filipin pesosundan başlayan fiyatlarla açıldı.',
          'Duyuru oyunun 10. yılını kutluyor: 1,5 milyar indirme ve aylık 110 milyon aktif oyuncu.'],
  'impact': 'Espor etkinlikleri mevcut hesapların değerini değiştirmez. Araştırmamıza göre Mobile Legends’ta değeri kostümler, kahramanlar ve ilerleme belirliyor.'},
 'cr-bal-sep': {'title': 'Clash Royale eylül dengesi: Buz Büyücüsü kahramanı ve Minyon Dev zayıfladı',
  'desc': 'Supercell’in Eylül 2026 denge notları Buz Büyücüsü kahramanının dondurmasını 7’den 5 saniyeye, Minyon Dev’in hasarını 189’dan 168’e düşürüyor; Mega Minyon ve Büyücü kahramanları yeniden düzenleniyor.',
  'lead': 'Supercell, 8 ve 16 Eylül 2026’da uygulanan iki tur Clash Royale denge değişikliği yayımladı.',
  'new': ['16 Eylül: Buz Büyücüsü kahramanı dondurma 7 sn → 5 sn; Goblinstein yeteneği 4 sn → 3,5 sn; Minyon Dev hasarı 189 → 168; Ateş Ruhu hasarı 207 → 215.',
          '8 Eylül: Dondurma 4 sn → 3,5 sn; Ateş Topu kule hasarı 172 → 159; Buz Golemi canı 1.315 → 1.228.',
          'Yeniden düzenlemeler: Mega Minyon kahramanı (ışınlanarak geri döner, hasar 399 → 422) ve Büyücü kahramanı (yetenek 5 sn → 3,5 sn); Büyücü hasarı 281 → 304.',
          'Güçlendirilenler arasında Ronin, Ruh İmparatoriçesi ve Goblin Kafesi var.'],
  'impact': 'Denge değişiklikleri hangi kartların popüler olduğunu değiştirir, hesabın sahip olduklarını değil. Araştırmamıza göre Clash Royale’de değer Kral Kulesi seviyesi, kart seviyeleri, evrimler ve nadir kozmetiklere bağlı.'},
 'gi-wish71': {'title': 'Genshin Impact 7.1 etkinlik dilekleri: Vesna ve Vodyanitsa afişleri 13 Ekim’e kadar',
  'desc': 'HoYoverse’ün 7.1 sürümü I. aşama etkinlik dilekleri Vesna ve Vodyanitsa’nın şansını 13 Ekim 2026’ya kadar artırıyor; öne çıkan 4 yıldızlılar Diona, Faruzan ve Chongyun.',
  'lead': 'HoYoverse, 7.1 sürümünün I. aşama etkinlik dileklerini 21 Eylül 2026’da yayımladı; dilekler 13 Ekim 2026 saat 17.59’a kadar sürüyor.',
  'new': ['"When Warm Winds Cavort", Vesna’nın (Anemo) çıkma şansını artırıyor.',
          '"Surging Ballad", Vodyanitsa’nın (Hydro) çıkma şansını artırıyor.',
          'Şansı artırılan 4 yıldızlı karakterler: Diona (Cryo), Faruzan (Anemo) ve Chongyun (Cryo).',
          'Etkinliğe özel karakterler standart dilekte yok; iki karakter afişi aynı garanti sayacını paylaşıyor.'],
  'impact': 'Yalnızca sınırlı afişlerden alınabilen karakterler ve takımyıldızları, araştırmamıza göre Genshin hesap değerinin başlıca belirleyicilerinden.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Çöp Goblini Darryl görünümü ve 30 Eylül’e kadar ödüller',
  'desc': 'Supercell’in Brawl Stars × Duolingo etkinliği (19 Eylül 2026’da duyuruldu) 30 Eylül’e kadar Çöp Goblini Darryl görünümü, elmas, Starr Drop ve daha fazlasını verdi.',
  'lead': 'Supercell, Brawl Stars × Duolingo ortaklığını 19 Eylül 2026’da duyurdu; etkinlik 30 Eylül’e kadar sürdü.',
  'new': ['İki aşamalı topluluk hedefleri ve oyun içi görevler, ayrıca yeni Duo Boss Fight modu.',
          'Ödüller: Çöp Goblini Darryl (Trash Goblin) görünümü, 20 elmas, 5 Chaos Drop, 3 Mitik Starr Drop, 2.000 altın, 2.500 bling ve 1.000 kredi.',
          'Duolingo uygulamasındaki Brawl Stars görevi ek kozmetikler verdi.',
          'Supercell sosyal medyada 3,141592 milyon elmaslık bir bilgi yarışması çekilişi de düzenledi.'],
  'impact': 'Tek seferlik ortaklıklara ait görünümler bazı Brawl Stars koleksiyonlarını öne çıkarır; çok sayıda oyuncunun ücretsiz aldığı bir görünüm, nadir ve ücretli bir görünümden daha az katkı sağlar.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN geri döndü: Dokuz Kuyruklu ve Hinata paketi (16 Eylül – 15 Ekim)',
  'desc': 'Garena’nın NARUTO SHIPPUDEN ortaklığı 16 Eylül – 15 Ekim 2026 arasında Sharingan: Control yeteneği, Jiraiya ya da Hinata seçmeli paketi ve temalı kozmetiklerle sürüyor.',
  'lead': 'Garena, Free Fire × NARUTO SHIPPUDEN ortaklığının 16 Eylül – 15 Ekim arasında geri döndüğünü 15 Eylül 2026’da duyurdu.',
  'new': ['Yeni yetenekler: Dokuz Kuyruklu’yu yöneten Sharingan: Control ve 8 Trigrams Palm Rotation.',
          'Gizli Yaprak Köyü haritasında genişletilmiş bir Ninja Akademisi.',
          'Seçmeli büyük ödül: Jiraiya paketi ya da Hinata paketi (Hinata’nın oyundaki ilk çıkışı).',
          'Kozmetikler: Tsunade’nin Pelerini, Gaara’nın Dövme Yüz Boyası, Kakashi’nin ANBU Maskesi ve Froggy Wallet sandığı.'],
  'impact': 'Yalnızca sınırlı süre sunulan lisanslı ortaklık paketleri, Free Fire hesaplayıcımızın aradığı nadir eşyalar arasında.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship 8. sezon başladı: İstanbul’daki M8’e giden yol',
  'desc': 'MTC 8. sezonu 12 Eylül – 18 Ekim 2026 arasında sekiz takım ve 40.000 dolarlık ödül havuzuyla oynanıyor; ardından Ocak 2027’de İstanbul’da M8 Dünya Şampiyonası var.',
  'lead': 'MOONTON Games, MLBB Türkiye Championship 8. sezonunun 12 Eylül’de başlayacağını 10 Eylül 2026’da duyurdu.',
  'new': ['Normal sezon 12 Eylül – 18 Ekim; büyük final 7 Kasım 2026’da.',
          'Aralarında Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok ve Dark Passage’ın da bulunduğu sekiz takım yarışıyor.',
          'İlk altı takım play-off’a kalıyor ve 40.000 dolarlık ödül havuzu için mücadele ediyor.',
          'M8 Dünya Şampiyonası Ocak 2027’de İstanbul’da yapılacak; bu, M serisinin Avrupa’daki ilk etkinliği.'],
  'impact': 'Espor sonuçları mevcut hesapların değerini değiştirmez; araştırmamıza göre Collector ve Legend kostümleri ile kahraman sayısı ana değer belirleyiciler olmaya devam ediyor.'},
 'coc-blast': {'title': 'Clash of Clans Equipment Blast madalya etkinliği (9–22 Eylül)',
  'desc': 'Equipment Blast etkinliği 9–22 Eylül 2026’da yapıldı: Tag Ticket ve Champ Medal kazanıp Tüccar’da kahraman ekipmanı, cevher ve kozmetiklere harcamak mümkündü. Belediye Binası 6 ve üstü.',
  'lead': 'Supercell, Equipment Blast madalya etkinliğini 9 Eylül 2026’da duyurdu; etkinlik 22 Eylül 08.00 UTC’ye kadar sürdü, Tüccar 24 Eylül’e kadar açık kaldı.',
  'new': ['Çok oyunculu savaşlar Tag Ticket kazandırdı; etkinlik yolu Champ Medal, geçici birlikler ve sandıklar verdi.',
          'Tüccar, etkinlik madalyaları karşılığında kahraman ekipmanı, cevher ve kozmetik sattı.',
          'Geçici birlikler: Undertaker Yeti, K.A.N.E., Yeeter ve Giant Giant.',
          'Belediye Binası 6’dan itibaren açıktı.'],
  'impact': 'Kahraman ekipmanı ve seviyeleri, araştırmamıza göre Clash of Clans hesap değerini belirleyen kahraman gücünün bir parçası; etkinlik madalyaları onu yükseltmenin bir yolu daha.'},
 'mc-wild': {'title': 'Minecraft Wilderness Bound güncellemesi: benekli orman, saman yataklar ve terk edilmiş kamplar',
  'desc': 'Mojang’ın Wilderness Bound güncellemesi 15 Eylül 2026’da benekli orman biyomu, kavak ağacı, saman yataklar, terk edilmiş kamplar ve minderlerle geldi.',
  'lead': 'Mojang Studios, 2026’nın üçüncü oyun güncellemesinin adını 5 Eylül’de "Wilderness Bound" olarak açıkladı ve 15 Eylül’de yayınladı.',
  'new': ['Yeni bir biyom: uzun kavak ağaçları ve raf mantarlarıyla benekli orman.',
          'Üç saman balyasından yapılan saman yataklar, doğma noktasını değiştirmeden geceyi geçirmeyi sağlıyor.',
          'Keşfedilecek terk edilmiş kamplar ve aynı renkte üç yün levhadan yapılan minderler.',
          'Kavak odunu ile genişletilmiş beton ve yün yapı setleri.'],
  'impact': 'Minecraft hesapları oyun içeriğine göre değil; hesap türü, kullanıcı adı ve pelerinlere göre değerlenir. Bir oyun güncellemesi hesabın değerini değiştirmez.'},
 'ff-award': {'title': 'Free Fire, Pocket Gamer Mobile Games Awards 2026’da "En İyi IP veya Lisans Kullanımı" ödülünü kazandı',
  'desc': 'Garena, Free Fire’ın NARUTO SHIPPUDEN ortaklığıyla Pocket Gamer Mobile Games Awards 2026’da Best Use of IP or Licence ödülünü kazandığını 3 Eylül 2026’da açıkladı.',
  'lead': 'Garena, Free Fire’ın Pocket Gamer Mobile Games Awards 2026’da "Best Use of IP or Licence" ödülünü kazandığını 3 Eylül 2026’da duyurdu.',
  'new': ['Ödül, NARUTO SHIPPUDEN Chapter 2: Ninja War ortaklığını onurlandırıyor.',
          'Garena’ya göre Bangkok’taki Ninja Clash All Stars etkinliği yaklaşık 5.000 ziyaretçi ve 247 milyonun üzerinde video izlenmesine ulaştı.',
          'Ortaklık temalı karakterler, jutsu yetenekleri ve dönüştürülmüş bir Gizli Yaprak Köyü haritası içeriyordu.',
          'Peru, Bangladeş, Malezya ve Tayvan’da topluluk etkinlikleri düzenlendi.'],
  'impact': 'Bir ödül hesap değerlerini değiştirmez. Ancak lisanslı ortaklıkların Free Fire’ın düzenli bir parçası olduğunu doğruluyor; bunların sınırlı paketleri de değerlemenin baktığı nadir eşyalar arasında.'},
 'rbx-fall': {'title': 'Roblox Sonbahar Oyunları Önizlemesi: eylül ve ekimde gelen 10 deneyim',
  'desc': 'Roblox’un Sonbahar Oyunları Önizlemesi (2 Eylül 2026), eylülde Showdown ve Nemesis’ten ekimde Prime Heroes, Octane ve Starforged’a kadar 10 yeni deneyimi listeliyor.',
  'lead': 'Roblox, 2 Eylül 2026’da eylül ve ekimde gelecek on deneyimi listeleyen Sonbahar Oyunları Önizlemesi’ni yayımladı.',
  'new': ['Eylül: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force ve Caramel.',
          'Ekim: Prime Heroes (eylülde 6 kahramanla erken erişim), Octane, Starforged ve Scrapbook Saga.',
          'Bazı oyunlar Roblox’un Jumpstart ve Incubator içerik üreticisi programlarından çıkıyor.',
          'Türler nişancı ve yarıştan hayatta kalma korkusuna ve çiftçiliğe kadar uzanıyor.'],
  'impact': 'Yeni deneyimler mevcut hesapları değiştirmez. Araştırmamıza göre Roblox hesap değeri Robux, sınırlı eşyalar ve uzun soluklu deneyimlerdeki eşyalardan geliyor; yeni bir oyun ancak eşyaları alınıp satılmaya başladığında önem kazanır.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: 1 Ekim’den sonra "geri dönmeyecek" tek seferlik kahraman görünümleri',
  'desc': 'Supercell’in WWE: Search for Cena etkinliği (Eylül 2026), Supercell’e göre 1 Ekim’den sonra geri dönmeyecek altı WWE kahraman görünümü ve Money in the Bank dekorunu sattı.',
  'lead': 'Supercell, Clash of Clans için WWE: Search for Cena etkinliğini 1 Eylül 2026’da duyurdu; etkinlik eylül boyunca sürdü.',
  'new': ['9,99 dolarlık kahraman görünümleri: Cody Rhodes (Barbar Kral), Alexa Bliss (Okçu Kraliçe), Iyo Sky (Kraliyet Şampiyonu), Kane (Ejderha Dükü) ve American Badass Undertaker (Büyük Muhafız).',
          'Jey Uso (Minyon Prens) Altın Pass ile verildi.',
          'Supercell, görünümlerin 1 Ekim’den sonra "geri dönmeyeceğini. Asla" söylüyor.',
          'Money in the Bank XL dekoru 2–30 Eylül arasında satıldı; aynı dönemde John Cena görevi ve geçici WWE birlikleri de vardı.'],
  'impact': 'Yayıncının asla geri dönmeyeceğini söylediği görünümler, bir Clash of Clans hesabını daha nadir kılan kozmetiklerin ta kendisi. Yine de değerin büyük kısmını Belediye Binası ve kahraman seviyeleri taşıyor.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: iki bölümlü yeni formata ilk bakış',
  'desc': 'Supercell’in BSC 2027’ye ilk bakışı (24 Ağustos 2026): dört bölgede bölge başına sekiz takım, 12 bölgede Challengers, 12’şer haftalık iki bölüm, Brawl Cup ve Dünya Finalleri.',
  'lead': 'Supercell, 2027 Brawl Stars Championship’e ilk bakışı 24 Ağustos 2026’da paylaştı ve ayrıntıların değişebileceğini belirtti.',
  'new': ['Üst seviye: Doğu Asya, EMEA, Güney Amerika ve Kuzey Amerika’da bölge başına 8 takım.',
          'Challengers: 12 bölgede profesyonelliğe giriş yolu.',
          '12’şer haftalık iki bölüm; 1. bölüm üç günlük uluslararası LAN turnuvası Brawl Cup ile, 2. bölüm Dünya Finalleri ile bitiyor.',
          'Tarihler, ödül havuzu ve mekânlar henüz açıklanmadı.'],
  'impact': 'Espor formatları mevcut hesapların değerini değiştirmez; Brawl Stars hesaplayıcımız savaşçı sayısı, Hiperşarjlar ve kupaları kullanmaya devam ediyor.'},
}},
'ar': {'a': {
 'mc-d2': {'title': 'صدرت Minecraft Dungeons II: بُعد Sift ومجلس الإيلجرز الأعلى',
  'desc': 'أطلقت Mojang لعبة Minecraft Dungeons II في 29 سبتمبر 2026 على Steam وXbox Series X|S وPlayStation 5 وNintendo Switch وSwitch 2، مع لعب تعاوني حتى 4 لاعبين.',
  'lead': 'أطلقت Mojang Studios لعبة Minecraft Dungeons II في 29 سبتمبر 2026.',
  'new': ['متاحة على Steam وXbox Series X|S وPlayStation 5 وNintendo Switch وNintendo Switch 2.',
          'تضع القصة اللاعبين في مواجهة مجلس الإيلجرز الأعلى: Prime Enchanter وSupreme Evoker وGrand Illusioner.',
          'يستكشف اللاعبون بُعدًا جديدًا هو Sift، وتقول Mojang إنه سيصل أيضًا إلى Minecraft Java وBedrock العام المقبل.',
          'اللعب فرديًا أو تعاونيًا حتى 4 لاعبين، عبر الإنترنت أو على الشاشة نفسها.'],
  'impact': 'Dungeons II لعبة منفصلة. ما زالت حسابات Minecraft Java وBedrock تُقيَّم حسب النوع واسم المستخدم والعباءات، لذلك لا يغيّر الإصدار قيمتها.'},
 'cr-mt-oct': {'title': 'Merge Tactics في Clash Royale: تغييرات أكتوبر على الـSupers والإكسير والشارات',
  'desc': 'ابتداءً من 1 أكتوبر 2026، ينقل الموسم 11 من Merge Tactics الـSupers إلى المجمّع المشترك، ويخفّض الإكسير لكل جولة من 5 إلى 4، ويضيف مظاهر المستوى 5؛ وتتغير قواعد الشارات في الموسم 12.',
  'lead': 'أعلنت Supercell تغييرات أكتوبر للموسم 11 من Merge Tactics في 30 سبتمبر 2026، وتسري من 1 أكتوبر.',
  'new': ['لم تعد الـSupers قوات بداية: تنتقل إلى المجمّع المشترك الذي يتنافس عليه جميع اللاعبين.',
          'يعود الإكسير المكتسب في كل جولة من 5 إلى 4.',
          'تحصل Battle Machine وDagger Duchess على مظاهر المستوى 5 لمن طوّرهما بالفعل.',
          'من الموسم 12، تتطلب الشارة الفضية بلوغ الدوري الماسي، والذهبية دخول أفضل 10,000.'],
  'impact': 'من الموسم 12 يصبح نيل شارات المراكز العليا أصعب، فتعكس المهارة بوضوح أكبر في ملف Clash Royale. ويبقى مستوى برج الملك ومستويات البطاقات أهم عوامل القيمة.'},
 'ml-mplph': {'title': 'تصفيات MPL الفلبين الموسم 18: PhilSports Arena من 21 إلى 25 أكتوبر',
  'desc': 'أعلنت MOONTON في 26 سبتمبر 2026 أن تصفيات الموسم 18 من MPL الفلبين تُقام من 21 إلى 25 أكتوبر في PhilSports Arena وتحدد فرق الفلبين في M8.',
  'lead': 'أعلنت MOONTON Games مكان ومواعيد تصفيات الموسم 18 من MPL الفلبين في 26 سبتمبر 2026.',
  'new': ['تُقام التصفيات في PhilSports Arena بمدينة باسيغ من 21 إلى 25 أكتوبر 2026.',
          'تحدد الفرق التي تمثل الفلبين في بطولة العالم M8 في إسطنبول في يناير 2027.',
          'فُتح بيع التذاكر في 26 سبتمبر بأسعار تبدأ من 200 بيزو فلبيني.',
          'يحتفي الإعلان بالذكرى العاشرة للعبة: 1.5 مليار عملية تثبيت و110 ملايين لاعب نشط شهريًا.'],
  'impact': 'لا تغيّر فعاليات الرياضات الإلكترونية قيمة الحسابات الحالية. بحسب بحثنا، تحدد المظاهر والأبطال والتقدّم قيمة حسابات Mobile Legends.'},
 'cr-bal-sep': {'title': 'توازن سبتمبر في Clash Royale: إضعاف البطل Ice Wizard وMinion Giant',
  'desc': 'تخفّض ملاحظات توازن سبتمبر 2026 من Supercell تجميد البطل Ice Wizard من 7 إلى 5 ثوانٍ وضرر Minion Giant من 189 إلى 168، وتعيد تصميم البطلين Mega Minion وWizard.',
  'lead': 'نشرت Supercell جولتين من تغييرات التوازن في Clash Royale طُبّقتا في 8 و16 سبتمبر 2026.',
  'new': ['16 سبتمبر: تجميد البطل Ice Wizard من 7 ث إلى 5 ث؛ قدرة Goblinstein من 4 ث إلى 3.5 ث؛ ضرر Minion Giant من 189 إلى 168؛ ضرر Fire Spirit من 207 إلى 215.',
          '8 سبتمبر: Freeze من 4 ث إلى 3.5 ث؛ ضرر Fireball على الأبراج من 172 إلى 159؛ نقاط صحة Ice Golem من 1315 إلى 1228.',
          'إعادة تصميم: البطل Mega Minion (يعود بالانتقال الآني، الضرر من 399 إلى 422) والبطل Wizard (القدرة من 5 ث إلى 3.5 ث)؛ ضرر Wizard من 281 إلى 304.',
          'تعزيزات تشمل Ronin وSpirit Empress وGoblin Cage.'],
  'impact': 'يغيّر التوازن البطاقات الرائجة، لا ما يملكه الحساب. بحسب بحثنا، تتبع قيمة Clash Royale مستوى برج الملك ومستويات البطاقات والتطويرات ومستحضرات التجميل النادرة.'},
 'gi-wish71': {'title': 'أمنيات حدث Genshin Impact 7.1: لافتتا Vesna وVodyanitsa حتى 13 أكتوبر',
  'desc': 'ترفع أمنيات الحدث في المرحلة الأولى من الإصدار 7.1 فرصة Vesna وVodyanitsa حتى 13 أكتوبر 2026، مع Diona وFaruzan وChongyun كشخصيات 4 نجوم مرفوعة الفرصة.',
  'lead': 'نشرت HoYoverse أمنيات الحدث للمرحلة الأولى من الإصدار 7.1 في 21 سبتمبر 2026، وتستمر حتى 13 أكتوبر 2026 الساعة 17:59.',
  'new': ['"When Warm Winds Cavort" ترفع فرصة ظهور Vesna (أنيمو).',
          '"Surging Ballad" ترفع فرصة ظهور Vodyanitsa (هيدرو).',
          'شخصيات 4 نجوم مرفوعة الفرصة: Diona (كرايو) وFaruzan (أنيمو) وChongyun (كرايو).',
          'شخصيات الحدث الحصرية ليست في الأمنية العادية، وتتشارك لافتتا الشخصيات عدّاد الضمان نفسه.'],
  'impact': 'بحسب بحثنا، الشخصيات التي لا تُنال إلا من اللافتات المحدودة وكوكباتها من أهم عوامل قيمة حسابات Genshin.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: مظهر Trash Goblin Darryl ومكافآت حتى 30 سبتمبر',
  'desc': 'منح حدث Brawl Stars × Duolingo من Supercell (أُعلن في 19 سبتمبر 2026) مظهر Trash Goblin Darryl وجواهر وStarr Drops وغيرها حتى 30 سبتمبر.',
  'lead': 'أعلنت Supercell تعاون Brawl Stars × Duolingo في 19 سبتمبر 2026، واستمر حتى 30 سبتمبر.',
  'new': ['مرحلتان من أهداف المجتمع والمهام داخل اللعبة، إضافة إلى وضع جديد هو Duo Boss Fight.',
          'المكافآت: مظهر Trash Goblin Darryl، و20 جوهرة، و5 Chaos Drops، و3 Mythic Starr Drops، و2000 عملة، و2500 Bling، و1000 رصيد.',
          'مهمة Brawl Stars داخل تطبيق Duolingo منحت مستحضرات تجميل إضافية.',
          'أجرت Supercell أيضًا مسابقة أسئلة على منصاتها بجوائز قدرها 3.141592 مليون جوهرة.'],
  'impact': 'مظاهر التعاونات التي تحدث مرة واحدة هي ما يميّز بعض مجموعات Brawl Stars؛ والمظهر الذي ناله كثيرون مجانًا يضيف أقل من مظهر نادر مدفوع.'},
 'ff-naruto': {'title': 'عودة Free Fire × NARUTO SHIPPUDEN: ذو الذيول التسعة وحزمة Hinata (16 سبتمبر – 15 أكتوبر)',
  'desc': 'يستمر تعاون Garena مع NARUTO SHIPPUDEN من 16 سبتمبر إلى 15 أكتوبر 2026 بمهارة Sharingan: Control وحزمة اختيارية لـJiraiya أو Hinata ومستحضرات تجميل خاصة.',
  'lead': 'أعلنت Garena في 15 سبتمبر 2026 عودة تعاون Free Fire × NARUTO SHIPPUDEN من 16 سبتمبر إلى 15 أكتوبر.',
  'new': ['مهارات جديدة: Sharingan: Control للتحكم في ذي الذيول التسعة، و8 Trigrams Palm Rotation.',
          'أكاديمية نينجا موسّعة في خريطة قرية الورق الخفية.',
          'جائزة كبرى اختيارية: حزمة Jiraiya أو حزمة Hinata (أول ظهور لها في اللعبة).',
          'مستحضرات تجميل: عباءة Tsunade، وطلاء وشم Gaara، وقناع ANBU الخاص بـKakashi، وصندوق Froggy Wallet.'],
  'impact': 'حزم التعاونات المرخّصة المتاحة لفترة محدودة من بين العناصر النادرة التي تبحث عنها حاسبة Free Fire لدينا.'},
 'ml-mtc8': {'title': 'انطلاق الموسم 8 من MLBB Türkiye Championship في الطريق إلى M8 في إسطنبول',
  'desc': 'يُقام الموسم 8 من MTC بين 12 سبتمبر و18 أكتوبر 2026 بثمانية فرق وجوائز قدرها 40,000 دولار، قبل بطولة العالم M8 في إسطنبول في يناير 2027.',
  'lead': 'أعلنت MOONTON Games في 10 سبتمبر 2026 أن الموسم 8 من MLBB Türkiye Championship يبدأ في 12 سبتمبر.',
  'new': ['الموسم العادي من 12 سبتمبر إلى 18 أكتوبر، والنهائي الكبير في 7 نوفمبر 2026.',
          'تشارك ثمانية فرق منها Aurora Gaming وFUT Esports وBushido Wildcats وPacific Esports وOzorok وDark Passage.',
          'تتأهل أفضل ستة فرق إلى الأدوار الإقصائية وتتنافس على جوائز قدرها 40,000 دولار.',
          'تُقام بطولة العالم M8 في إسطنبول في يناير 2027، وهي أول حدث لسلسلة M في أوروبا.'],
  'impact': 'لا تغيّر نتائج الرياضات الإلكترونية قيمة الحسابات الحالية؛ تبقى مظاهر Collector وLegend وعدد الأبطال أهم العوامل بحسب بحثنا.'},
 'coc-blast': {'title': 'حدث ميداليات Equipment Blast في Clash of Clans (من 9 إلى 22 سبتمبر)',
  'desc': 'أُقيم حدث Equipment Blast من 9 إلى 22 سبتمبر 2026: اجمع Tag Tickets وChamp Medals واصرفها لدى التاجر على معدات الأبطال والخام ومستحضرات التجميل. من قاعة البلدة 6.',
  'lead': 'أعلنت Supercell حدث ميداليات Equipment Blast في 9 سبتمبر 2026، واستمر حتى 22 سبتمبر الساعة 08:00 UTC، وبقي التاجر مفتوحًا حتى 24 سبتمبر.',
  'new': ['منحت المعارك الجماعية Tag Tickets، ومنح مسار الحدث Champ Medals وقوات مؤقتة وصناديق.',
          'باع التاجر معدات الأبطال والخام ومستحضرات التجميل مقابل ميداليات الحدث.',
          'القوات المؤقتة: Undertaker Yeti وK.A.N.E. وYeeter وGiant Giant.',
          'متاح من قاعة البلدة 6.'],
  'impact': 'معدات الأبطال ومستوياتها جزء من قوة الأبطال التي تحدد قيمة حسابات Clash of Clans بحسب بحثنا؛ وميداليات الحدث وسيلة أخرى لترقيتها.'},
 'mc-wild': {'title': 'تحديث Minecraft Wilderness Bound: الغابة المرقّطة وأسرّة القش والمخيمات المهجورة',
  'desc': 'وصل تحديث Wilderness Bound من Mojang في 15 سبتمبر 2026 مع بيئة الغابة المرقّطة وخشب الحور وأسرّة القش والمخيمات المهجورة والوسائد.',
  'lead': 'أطلقت Mojang Studios اسم "Wilderness Bound" على التحديث الثالث لعام 2026 في 5 سبتمبر وأصدرته في 15 سبتمبر.',
  'new': ['بيئة جديدة هي الغابة المرقّطة بأشجار حور طويلة وفطر الرفوف.',
          'أسرّة القش المصنوعة من ثلاث رزم تبن تتيح تخطي الليل دون تغيير نقطة الظهور.',
          'مخيمات مهجورة للاستكشاف ووسائد تُصنع من ثلاث ألواح صوف بلون واحد.',
          'خشب الحور ومجموعات موسّعة من الخرسانة والصوف للبناء.'],
  'impact': 'تُقيَّم حسابات Minecraft حسب النوع واسم المستخدم والعباءات، لا حسب محتوى اللعبة، لذلك لا يغيّر التحديث قيمة الحساب.'},
 'ff-award': {'title': 'Free Fire يفوز بجائزة "أفضل استخدام لملكية فكرية أو ترخيص" في Pocket Gamer Mobile Games Awards 2026',
  'desc': 'ذكرت Garena في 3 سبتمبر 2026 أن Free Fire فاز بجائزة Best Use of IP or Licence في Pocket Gamer Mobile Games Awards 2026 عن تعاونه مع NARUTO SHIPPUDEN.',
  'lead': 'أعلنت Garena في 3 سبتمبر 2026 فوز Free Fire بجائزة "Best Use of IP or Licence" في Pocket Gamer Mobile Games Awards 2026.',
  'new': ['تكرّم الجائزة تعاون NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'بحسب Garena، استقطب حدث Ninja Clash All Stars في بانكوك نحو 5,000 زائر وأكثر من 247 مليون مشاهدة.',
          'شمل التعاون شخصيات خاصة وقدرات جوتسو وخريطة متحوّلة لقرية الورق الخفية.',
          'أُقيمت فعاليات مجتمعية في بيرو وبنغلاديش وماليزيا وتايوان.'],
  'impact': 'لا تغيّر الجائزة قيمة الحسابات، لكنها تؤكد أن التعاونات المرخّصة جزء ثابت من Free Fire، وحزمها المحدودة من بين العناصر النادرة التي ينظر إليها التقييم.'},
 'rbx-fall': {'title': 'معاينة ألعاب الخريف في Roblox: 10 تجارب في سبتمبر وأكتوبر',
  'desc': 'تضم معاينة ألعاب الخريف من Roblox (2 سبتمبر 2026) عشر تجارب جديدة، من Showdown وNemesis في سبتمبر إلى Prime Heroes وOctane وStarforged في أكتوبر.',
  'lead': 'نشرت Roblox معاينة ألعاب الخريف في 2 سبتمبر 2026، وتضم عشر تجارب مقررة لشهري سبتمبر وأكتوبر.',
  'new': ['سبتمبر: Showdown: The Showdown Cup وMonster in the Mansion وGOAT Football League وNemesis وFossil Force وCaramel.',
          'أكتوبر: Prime Heroes (وصول مبكر في سبتمبر بستة أبطال) وOctane وStarforged وScrapbook Saga.',
          'عدة عناوين خرجت من برنامجي Jumpstart وIncubator لصنّاع Roblox.',
          'تتنوع الأنواع من ألعاب التصويب والسباق إلى رعب البقاء والزراعة.'],
  'impact': 'لا تغيّر التجارب الجديدة الحسابات الحالية. بحسب بحثنا، تأتي قيمة حساب Roblox من الـRobux والعناصر المحدودة وعناصر التجارب القديمة؛ ولا تُحتسب اللعبة الجديدة إلا حين تبدأ عناصرها بالتداول.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: مظاهر أبطال لمرة واحدة "لن تعود" بعد 1 أكتوبر',
  'desc': 'باع حدث WWE: Search for Cena من Supercell (سبتمبر 2026) ستة مظاهر أبطال من WWE تقول Supercell إنها لن تعود بعد 1 أكتوبر، إضافة إلى ديكور Money in the Bank.',
  'lead': 'أعلنت Supercell حدث WWE: Search for Cena في Clash of Clans في 1 سبتمبر 2026، واستمر طوال سبتمبر.',
  'new': ['مظاهر أبطال بسعر 9.99 دولار: Cody Rhodes (الملك البربري) وAlexa Bliss (الملكة الرامية) وIyo Sky (البطلة الملكية) وKane (دوق التنين) وAmerican Badass Undertaker (الحارس الأكبر).',
          'جاء Jey Uso (أمير التوابع) مع البطاقة الذهبية.',
          'تقول Supercell إن المظاهر "لن تعود. أبدًا" بعد 1 أكتوبر.',
          'كان ديكور Money in the Bank XL متاحًا من 2 إلى 30 سبتمبر، مع تحدي John Cena وقوات WWE مؤقتة.'],
  'impact': 'المظاهر التي يقول الناشر إنها لن تعود أبدًا هي بالضبط نوع مستحضرات التجميل التي تجعل حساب Clash of Clans أندر. ومع ذلك يبقى مستوى قاعة البلدة والأبطال هو الجزء الأكبر من القيمة.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: نظرة أولى على الصيغة الجديدة بقسمين',
  'desc': 'نظرة Supercell الأولى على BSC 2027 (24 أغسطس 2026): ثمانية فرق لكل منطقة في أربع مناطق، وChallengers في 12 منطقة، وقسمان من 12 أسبوعًا، وBrawl Cup ونهائيات العالم.',
  'lead': 'قدّمت Supercell نظرة أولى على Brawl Stars Championship 2027 في 24 أغسطس 2026، مع التنبيه إلى أن التفاصيل قد تتغير.',
  'new': ['المستوى الأعلى: 8 فرق لكل منطقة في شرق آسيا وEMEA وأمريكا الجنوبية وأمريكا الشمالية.',
          'Challengers: مسار دخول في 12 منطقة.',
          'قسمان مدة كلٍّ منهما 12 أسبوعًا؛ ينتهي الأول بـBrawl Cup، وهي بطولة LAN دولية لثلاثة أيام، والثاني بنهائيات العالم.',
          'لم تُعلَن التواريخ ولا الجوائز ولا الأماكن بعد.'],
  'impact': 'لا تغيّر صيغ الرياضات الإلكترونية قيمة الحسابات الحالية؛ وتواصل حاسبة Brawl Stars لدينا الاعتماد على عدد المقاتلين وشحنات Hypercharge والكؤوس.'},
}},
}
