# News batch 2: pt, id (from news_text_b2_en.py, facts unchanged)
TEXT = {
'pt': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II chegou: a dimensão Sift e o Alto Conselho Illager',
  'desc': 'A Mojang lançou Minecraft Dungeons II em 29 de setembro de 2026 no Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch e Switch 2, com cooperativo para até 4 jogadores.',
  'lead': 'A Mojang Studios lançou Minecraft Dungeons II em 29 de setembro de 2026.',
  'new': ['Disponível no Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch e Nintendo Switch 2.',
          'A história coloca os jogadores contra o Alto Conselho Illager: o Encantador Supremo, o Evocador Supremo e o Grande Ilusionista.',
          'Os jogadores exploram uma nova dimensão, a Sift, que segundo a Mojang também chega ao Minecraft Java e Bedrock no ano que vem.',
          'Dá para jogar sozinho ou em cooperativo com até 4 pessoas, online ou na mesma tela.'],
  'impact': 'Dungeons II é um jogo separado. Contas de Minecraft Java e Bedrock continuam sendo avaliadas pelo tipo, nome de usuário e capas, então o lançamento não muda quanto elas valem.'},
 'cr-mt-oct': {'title': 'Merge Tactics no Clash Royale: mudanças de outubro em Supers, elixir e insígnias',
  'desc': 'A partir de 1º de outubro de 2026, a temporada 11 de Merge Tactics coloca os Supers na reserva comum, reduz o elixir por rodada de 5 para 4 e traz skins de nível 5; as insígnias mudam na temporada 12.',
  'lead': 'A Supercell anunciou as mudanças de outubro da temporada 11 de Merge Tactics em 30 de setembro de 2026; elas valem a partir de 1º de outubro.',
  'new': ['Os Supers deixam de ser tropas iniciais: vão para a reserva comum, disputada por todos os jogadores.',
          'O elixir ganho por rodada volta de 5 para 4.',
          'Máquina de Batalha e Duquesa das Adagas ganham skins de nível 5 para quem já as melhorou.',
          'A partir da temporada 12, a insígnia de prata exige chegar à Liga Diamante e a de ouro, ficar no top 10.000.'],
  'impact': 'A partir da temporada 12, insígnias de boa colocação ficam mais difíceis, mostrando melhor a habilidade num perfil de Clash Royale. Nível da Torre do Rei e das cartas continuam sendo os principais fatores de valor.'},
 'ml-mplph': {'title': 'Playoffs da MPL Filipinas, temporada 18: PhilSports Arena, 21 a 25 de outubro',
  'desc': 'A MOONTON anunciou em 26 de setembro de 2026 que os playoffs da temporada 18 da MPL Filipinas acontecem de 21 a 25 de outubro na PhilSports Arena e definem os times filipinos do M8.',
  'lead': 'A MOONTON Games anunciou o local e as datas dos playoffs da temporada 18 da MPL Filipinas em 26 de setembro de 2026.',
  'new': ['Os playoffs acontecem na PhilSports Arena, em Pasig, de 21 a 25 de outubro de 2026.',
          'Eles definem quais times representam as Filipinas no Campeonato Mundial M8, em Istambul, em janeiro de 2027.',
          'A venda de ingressos abriu em 26 de setembro, a partir de 200 pesos filipinos.',
          'O anúncio marca os 10 anos do jogo, com 1,5 bilhão de instalações e 110 milhões de jogadores ativos por mês.'],
  'impact': 'Eventos de esports não mudam o valor das contas existentes. Na nossa pesquisa, o valor em Mobile Legends vem das skins, dos heróis e do progresso.'},
 'cr-bal-sep': {'title': 'Balanceamento de setembro do Clash Royale: nerf no herói Mago de Gelo e no Servo Gigante',
  'desc': 'Os ajustes de setembro de 2026 da Supercell reduzem o congelamento do herói Mago de Gelo de 7 para 5 segundos e o dano do Servo Gigante de 189 para 168, e refazem os heróis Megasservo e Mago.',
  'lead': 'A Supercell publicou duas rodadas de balanceamento do Clash Royale, aplicadas em 8 e 16 de setembro de 2026.',
  'new': ['16 de setembro: congelamento do herói Mago de Gelo 7 s → 5 s; habilidade do Goblinstein 4 s → 3,5 s; dano do Servo Gigante 189 → 168; dano do Espírito de Fogo 207 → 215.',
          '8 de setembro: Gelo 4 s → 3,5 s; dano da Bola de Fogo em torres 172 → 159; vida do Golem de Gelo 1.315 → 1.228.',
          'Reformulações: herói Megasservo (volta por teletransporte, dano 399 → 422) e herói Mago (habilidade 5 s → 3,5 s); dano do Mago 281 → 304.',
          'Buffs para Ronin, Imperatriz Espiritual e Jaula do Goblin, entre outros.'],
  'impact': 'O balanceamento muda quais cartas são populares, não o que a conta tem. Na nossa pesquisa, o valor no Clash Royale acompanha o nível da Torre do Rei, das cartas, as evoluções e os cosméticos raros.'},
 'gi-wish71': {'title': 'Orações de evento de Genshin Impact 7.1: Vesna e Vodyanitsa até 13 de outubro',
  'desc': 'As orações de evento da fase I da versão 7.1 aumentam a chance de Vesna e Vodyanitsa até 13 de outubro de 2026, com Diona, Faruzan e Chongyun como 4 estrelas em destaque.',
  'lead': 'A HoYoverse publicou as orações de evento da fase I da versão 7.1 em 21 de setembro de 2026; elas vão até 13 de outubro de 2026, às 17:59.',
  'new': ['“When Warm Winds Cavort” aumenta a chance de Vesna (Anemo).',
          '“Surging Ballad” aumenta a chance de Vodyanitsa (Hydro).',
          'Personagens 4 estrelas em destaque: Diona (Cryo), Faruzan (Anemo) e Chongyun (Cryo).',
          'Personagens exclusivos do evento não ficam na oração padrão; os dois banners de personagens compartilham o mesmo contador de garantia.'],
  'impact': 'Personagens que só saem em banners limitados, e suas constelações, estão entre os principais fatores de valor de uma conta de Genshin na nossa pesquisa.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: skin Darryl Goblin do Lixo e recompensas até 30 de setembro',
  'desc': 'O evento Brawl Stars × Duolingo da Supercell (anunciado em 19 de setembro de 2026) dava a skin Darryl Goblin do Lixo, gemas, Starr Drops e mais até 30 de setembro.',
  'lead': 'A Supercell anunciou o crossover Brawl Stars × Duolingo em 19 de setembro de 2026; ele foi até 30 de setembro.',
  'new': ['Duas fases de metas da comunidade e tarefas no jogo, além de um novo modo Duo Boss Fight.',
          'Recompensas: skin Darryl Goblin do Lixo (Trash Goblin), 20 gemas, 5 Chaos Drops, 3 Starr Drops míticos, 2.000 moedas, 2.500 de bling e 1.000 créditos.',
          'Uma missão de Brawl Stars dentro do app Duolingo dava cosméticos extras.',
          'A Supercell também fez nas redes um quiz com 3,141592 milhões de gemas em prêmios.'],
  'impact': 'Skins de um crossover único fazem algumas coleções de Brawl Stars se destacarem; uma skin que muita gente ganhou de graça pesa menos que uma rara e paga.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN está de volta: Nove Caudas e pacote da Hinata (16 de setembro a 15 de outubro)',
  'desc': 'A colaboração da Garena com NARUTO SHIPPUDEN vai de 16 de setembro a 15 de outubro de 2026, com a habilidade Sharingan: Control, um pacote à escolha de Jiraiya ou Hinata e cosméticos temáticos.',
  'lead': 'A Garena anunciou em 15 de setembro de 2026 que a colaboração Free Fire × NARUTO SHIPPUDEN volta de 16 de setembro a 15 de outubro.',
  'new': ['Novas habilidades: Sharingan: Control, que comanda a Nove Caudas, e 8 Trigrams Palm Rotation.',
          'Uma Academia Ninja ampliada no mapa da Vila Oculta da Folha.',
          'Grande prêmio à escolha: pacote do Jiraiya ou pacote da Hinata (estreia dela no jogo).',
          'Cosméticos: capa da Tsunade, pintura facial da tatuagem do Gaara, máscara ANBU do Kakashi e a caixa Froggy Wallet.'],
  'impact': 'Pacotes de colaborações licenciadas disponíveis por tempo limitado estão entre os itens raros que nossa calculadora de Free Fire procura.'},
 'ml-mtc8': {'title': 'Começa a temporada 8 do MLBB Türkiye Championship, rumo ao M8 em Istambul',
  'desc': 'A temporada 8 do MTC vai de 12 de setembro a 18 de outubro de 2026 com oito times e US$ 40.000 em prêmios, antes do Mundial M8 em Istambul, em janeiro de 2027.',
  'lead': 'A MOONTON Games anunciou em 10 de setembro de 2026 que a temporada 8 do MLBB Türkiye Championship começa em 12 de setembro.',
  'new': ['Temporada regular de 12 de setembro a 18 de outubro; a grande final é em 7 de novembro de 2026.',
          'Oito times participam, entre eles Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok e Dark Passage.',
          'Os seis melhores vão aos playoffs e disputam US$ 40.000.',
          'O Campeonato Mundial M8 será em Istambul em janeiro de 2027, o primeiro evento da série M na Europa.'],
  'impact': 'Resultados de esports não mudam o valor das contas existentes; skins Colecionador e Lenda e a quantidade de heróis continuam sendo os principais fatores na nossa pesquisa.'},
 'coc-blast': {'title': 'Evento de medalhas Equipment Blast no Clash of Clans (9 a 22 de setembro)',
  'desc': 'O Equipment Blast foi de 9 a 22 de setembro de 2026: Tag Tickets e Champ Medals para trocar no Comerciante por equipamentos de herói, minério e cosméticos. A partir do CV 6.',
  'lead': 'A Supercell anunciou o evento de medalhas Equipment Blast em 9 de setembro de 2026; ele foi até 22 de setembro às 08:00 UTC, com o Comerciante aberto até 24 de setembro.',
  'new': ['Batalhas multijogador davam Tag Tickets; a trilha do evento dava Champ Medals, tropas temporárias e baús.',
          'O Comerciante vendia equipamentos de herói, minério e cosméticos por medalhas do evento.',
          'Tropas temporárias: Undertaker Yeti, K.A.N.E., Yeeter e Giant Giant.',
          'Disponível a partir do Centro de Vila 6.'],
  'impact': 'Equipamentos de herói e seus níveis compõem a força dos heróis, que na nossa pesquisa determina o valor das contas de Clash of Clans; as medalhas do evento são mais um jeito de melhorá-los.'},
 'mc-wild': {'title': 'Atualização Wilderness Bound do Minecraft: floresta salpicada, camas de palha e acampamentos abandonados',
  'desc': 'A atualização Wilderness Bound da Mojang chegou em 15 de setembro de 2026 com o bioma floresta salpicada, madeira de álamo, camas de palha, acampamentos abandonados e almofadas.',
  'lead': 'A Mojang Studios deu o nome de “Wilderness Bound” à terceira atualização de 2026 em 5 de setembro e a lançou em 15 de setembro.',
  'new': ['Um bioma novo, a floresta salpicada, com álamos altos e cogumelos-prateleira.',
          'Camas de palha feitas com três fardos de feno permitem pular a noite sem mudar o ponto de renascimento.',
          'Acampamentos abandonados para explorar e almofadas feitas com três lajes de lã da mesma cor.',
          'Madeira de álamo e conjuntos ampliados de concreto e lã para construir.'],
  'impact': 'Contas de Minecraft são avaliadas pelo tipo, nome de usuário e capas, não pelo conteúdo do jogo, então uma atualização não muda quanto uma conta vale.'},
 'ff-award': {'title': 'Free Fire vence “Melhor uso de IP ou licença” no Pocket Gamer Mobile Games Awards 2026',
  'desc': 'A Garena informou em 3 de setembro de 2026 que o Free Fire venceu Best Use of IP or Licence no Pocket Gamer Mobile Games Awards 2026 pela colaboração com NARUTO SHIPPUDEN.',
  'lead': 'A Garena anunciou em 3 de setembro de 2026 que o Free Fire venceu “Best Use of IP or Licence” no Pocket Gamer Mobile Games Awards 2026.',
  'new': ['O prêmio reconhece a colaboração NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Segundo a Garena, o evento Ninja Clash All Stars em Bangkok reuniu quase 5.000 visitantes e mais de 247 milhões de visualizações.',
          'A colaboração trouxe personagens temáticos, habilidades de jutsu e um mapa transformado da Vila Oculta da Folha.',
          'Houve eventos da comunidade no Peru, Bangladesh, Malásia e Taiwan.'],
  'impact': 'Um prêmio não muda o valor das contas, mas confirma que colaborações licenciadas são comuns no Free Fire — e pacotes limitados delas estão entre os itens raros que uma avaliação considera.'},
 'rbx-fall': {'title': 'Prévia de jogos de outono do Roblox: 10 experiências em setembro e outubro',
  'desc': 'A prévia de jogos de outono do Roblox (2 de setembro de 2026) lista 10 experiências novas, de Showdown e Nemesis em setembro a Prime Heroes, Octane e Starforged em outubro.',
  'lead': 'O Roblox publicou sua prévia de jogos de outono em 2 de setembro de 2026, com dez experiências previstas para setembro e outubro.',
  'new': ['Setembro: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force e Caramel.',
          'Outubro: Prime Heroes (acesso antecipado em setembro com 6 heróis), Octane, Starforged e Scrapbook Saga.',
          'Vários títulos vêm dos programas para criadores Jumpstart e Incubator do Roblox.',
          'Os gêneros vão de tiro e corrida a terror de sobrevivência e fazenda.'],
  'impact': 'Experiências novas não mudam contas existentes. Na nossa pesquisa, o valor de uma conta Roblox vem dos Robux, dos itens limitados e dos itens de experiências antigas; um jogo novo só pesa quando seus itens começam a ser negociados.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: skins de herói únicas que “não voltam” depois de 1º de outubro',
  'desc': 'O evento WWE: Search for Cena da Supercell (setembro de 2026) vendeu seis skins de herói da WWE que, segundo a Supercell, não voltam depois de 1º de outubro, além do cenário Money in the Bank.',
  'lead': 'A Supercell anunciou o evento WWE: Search for Cena do Clash of Clans em 1º de setembro de 2026; ele durou todo o mês de setembro.',
  'new': ['Skins de herói a US$ 9,99: Cody Rhodes (Rei Bárbaro), Alexa Bliss (Rainha Arqueira), Iyo Sky (Campeã Real), Kane (Duque Dragão) e American Badass Undertaker (Grande Guardião).',
          'Jey Uso (Príncipe Servo) vinha com o Passe Dourado.',
          'A Supercell diz que as skins “não voltam. Nunca” depois de 1º de outubro.',
          'O cenário XL Money in the Bank ficou disponível de 2 a 30 de setembro, com um desafio do John Cena e tropas temporárias da WWE.'],
  'impact': 'Skins que a publisher afirma que nunca vão voltar são exatamente o tipo de cosmético que deixa uma conta de Clash of Clans mais rara. Ainda assim, o nível do Centro de Vila e dos heróis concentra a maior parte do valor.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: primeira olhada no novo formato de dois splits',
  'desc': 'A primeira olhada da Supercell no BSC 2027 (24 de agosto de 2026): oito times por região em quatro regiões, Challengers em 12 regiões, dois splits de 12 semanas, a Brawl Cup e a Final Mundial.',
  'lead': 'A Supercell mostrou uma primeira olhada no Brawl Stars Championship 2027 em 24 de agosto de 2026, avisando que os detalhes ainda podem mudar.',
  'new': ['Nível principal: 8 times por região no Leste Asiático, EMEA, América do Sul e América do Norte.',
          'Challengers: um caminho de entrada em 12 regiões.',
          'Dois splits de 12 semanas; o primeiro termina na Brawl Cup, uma LAN internacional de três dias, e o segundo na Final Mundial.',
          'Datas, premiação e locais ainda não foram anunciados.'],
  'impact': 'Formatos de esports não mudam o valor das contas existentes; nossa calculadora de Brawl Stars continua usando a quantidade de brawlers, as hipercargas e os troféus.'},
}},
'id': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II sudah rilis: dimensi Sift dan Illager High Council',
  'desc': 'Mojang merilis Minecraft Dungeons II pada 29 September 2026 di Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch, dan Switch 2, dengan co-op hingga 4 pemain.',
  'lead': 'Mojang Studios merilis Minecraft Dungeons II pada 29 September 2026.',
  'new': ['Tersedia di Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch, dan Nintendo Switch 2.',
          'Ceritanya mempertemukan pemain dengan Illager High Council: Prime Enchanter, Supreme Evoker, dan Grand Illusioner.',
          'Pemain menjelajahi dimensi baru, Sift, yang menurut Mojang juga akan hadir di Minecraft Java dan Bedrock tahun depan.',
          'Bisa dimainkan sendiri atau co-op hingga 4 pemain, online maupun di satu layar.'],
  'impact': 'Dungeons II adalah game terpisah. Akun Minecraft Java dan Bedrock tetap dinilai dari jenis, nama pengguna, dan cape-nya, jadi rilis ini tidak mengubah nilainya.'},
 'cr-mt-oct': {'title': 'Merge Tactics Clash Royale: perubahan Oktober untuk Super, Elixir, dan lencana',
  'desc': 'Mulai 1 Oktober 2026, season 11 Merge Tactics memindahkan Super ke pool bersama, menurunkan Elixir per ronde dari 5 ke 4, dan menambah skin level 5; aturan lencana berubah di season 12.',
  'lead': 'Supercell mengumumkan perubahan Oktober untuk season 11 Merge Tactics pada 30 September 2026; berlaku mulai 1 Oktober.',
  'new': ['Super tidak lagi menjadi pasukan awal: semuanya masuk ke pool bersama yang diperebutkan semua pemain.',
          'Elixir per ronde kembali dari 5 ke 4.',
          'Battle Machine dan Dagger Duchess mendapat skin level 5 bagi pemain yang sudah meng-upgrade-nya.',
          'Mulai season 12, lencana Silver mensyaratkan mencapai Diamond League dan lencana Gold mensyaratkan masuk top 10.000.'],
  'impact': 'Mulai season 12, lencana peringkat tinggi makin sulit didapat sehingga lebih jelas menunjukkan kemampuan di profil Clash Royale. Level King Tower dan level kartu tetap menjadi pendorong nilai utama.'},
 'ml-mplph': {'title': 'Playoff MPL Philippines Season 18: PhilSports Arena, 21–25 Oktober',
  'desc': 'MOONTON mengumumkan pada 26 September 2026 bahwa playoff MPL Philippines Season 18 digelar 21–25 Oktober di PhilSports Arena dan menentukan tim Filipina untuk M8.',
  'lead': 'MOONTON Games mengumumkan lokasi dan jadwal playoff MPL Philippines Season 18 pada 26 September 2026.',
  'new': ['Playoff digelar di PhilSports Arena, Pasig, pada 21–25 Oktober 2026.',
          'Playoff ini menentukan tim yang mewakili Filipina di M8 World Championship di Istanbul pada Januari 2027.',
          'Penjualan tiket dibuka 26 September, mulai PHP 200.',
          'Pengumuman ini menandai ulang tahun ke-10 game, dengan 1,5 miliar instalasi dan 110 juta pemain aktif bulanan.'],
  'impact': 'Event esports tidak mengubah nilai akun yang ada. Dalam riset kami, nilai akun Mobile Legends ditentukan skin, hero, dan progres.'},
 'cr-bal-sep': {'title': 'Balance September Clash Royale: hero Ice Wizard dan Minion Giant di-nerf',
  'desc': 'Perubahan balance September 2026 dari Supercell memangkas freeze hero Ice Wizard dari 7 ke 5 detik dan damage Minion Giant dari 189 ke 168, serta me-rework hero Mega Minion dan Wizard.',
  'lead': 'Supercell merilis dua gelombang perubahan balance Clash Royale yang berlaku pada 8 dan 16 September 2026.',
  'new': ['16 September: freeze hero Ice Wizard 7 dtk → 5 dtk; kemampuan Goblinstein 4 dtk → 3,5 dtk; damage Minion Giant 189 → 168; damage Fire Spirit 207 → 215.',
          '8 September: Freeze 4 dtk → 3,5 dtk; damage Fireball ke tower 172 → 159; HP Ice Golem 1.315 → 1.228.',
          'Rework: hero Mega Minion (kembali dengan teleport, damage 399 → 422) dan hero Wizard (kemampuan 5 dtk → 3,5 dtk); damage Wizard 281 → 304.',
          'Buff antara lain untuk Ronin, Spirit Empress, dan Goblin Cage.'],
  'impact': 'Perubahan balance mengubah kartu yang populer, bukan isi akun. Dalam riset kami, nilai Clash Royale mengikuti level King Tower, level kartu, evolusi, dan kosmetik langka.'},
 'gi-wish71': {'title': 'Event Wish Genshin Impact 7.1: banner Vesna dan Vodyanitsa hingga 13 Oktober',
  'desc': 'Event Wish fase I Versi 7.1 dari HoYoverse menaikkan peluang Vesna dan Vodyanitsa hingga 13 Oktober 2026, dengan Diona, Faruzan, dan Chongyun sebagai karakter bintang 4 rate-up.',
  'lead': 'HoYoverse merilis Event Wish fase I Versi 7.1 pada 21 September 2026; berlaku hingga 13 Oktober 2026 pukul 17.59.',
  'new': ['"When Warm Winds Cavort" menaikkan peluang Vesna (Anemo).',
          '"Surging Ballad" menaikkan peluang Vodyanitsa (Hydro).',
          'Karakter bintang 4 rate-up: Diona (Cryo), Faruzan (Anemo), dan Chongyun (Cryo).',
          'Karakter eksklusif event tidak ada di wish standar; dua banner karakter berbagi satu hitungan pity.'],
  'impact': 'Karakter yang hanya bisa didapat dari banner terbatas, beserta konstelasinya, termasuk pendorong utama nilai akun Genshin dalam riset kami.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: skin Darryl Trash Goblin dan hadiah hingga 30 September',
  'desc': 'Event Brawl Stars × Duolingo dari Supercell (diumumkan 19 September 2026) memberikan skin Darryl Trash Goblin, gem, Starr Drop, dan lainnya hingga 30 September.',
  'lead': 'Supercell mengumumkan crossover Brawl Stars × Duolingo pada 19 September 2026; event berlangsung hingga 30 September.',
  'new': ['Dua fase target komunitas dan tugas dalam game, plus mode baru Duo Boss Fight.',
          'Hadiah: skin Darryl Trash Goblin, 20 Gem, 5 Chaos Drop, 3 Mythic Starr Drop, 2.000 Koin, 2.500 Bling, dan 1.000 Kredit.',
          'Quest Brawl Stars di aplikasi Duolingo memberi kosmetik tambahan.',
          'Supercell juga mengadakan kuis berhadiah 3,141592 juta gem di media sosialnya.'],
  'impact': 'Skin dari crossover sekali jalan membuat sebagian koleksi Brawl Stars menonjol; skin yang didapat banyak orang secara gratis menambah nilai lebih sedikit dibanding skin berbayar yang langka.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN kembali: Ekor Sembilan dan bundle Hinata (16 September – 15 Oktober)',
  'desc': 'Kolaborasi Garena dengan NARUTO SHIPPUDEN berlangsung 16 September – 15 Oktober 2026 dengan skill Sharingan: Control, bundle pilihan Jiraiya atau Hinata, dan kosmetik bertema.',
  'lead': 'Garena mengumumkan pada 15 September 2026 bahwa kolaborasi Free Fire × NARUTO SHIPPUDEN kembali pada 16 September – 15 Oktober.',
  'new': ['Skill baru: Sharingan: Control untuk mengendalikan Ekor Sembilan, dan 8 Trigrams Palm Rotation.',
          'Akademi Ninja yang diperluas di peta Desa Daun Tersembunyi.',
          'Hadiah utama pilihan: bundle Jiraiya atau bundle Hinata (debut Hinata di game).',
          'Kosmetik: Jubah Tsunade, Facepaint Tato Gaara, Topeng ANBU Kakashi, dan peti Froggy Wallet.'],
  'impact': 'Bundle dari kolaborasi berlisensi yang hanya tersedia dalam waktu terbatas termasuk item langka yang dicari kalkulator Free Fire kami.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship Season 8 dimulai, menuju M8 di Istanbul',
  'desc': 'MTC Season 8 berlangsung 12 September – 18 Oktober 2026 dengan delapan tim dan total hadiah US$40.000, menjelang M8 World Championship di Istanbul pada Januari 2027.',
  'lead': 'MOONTON Games mengumumkan pada 10 September 2026 bahwa MLBB Türkiye Championship Season 8 dimulai 12 September.',
  'new': ['Musim reguler 12 September – 18 Oktober; grand final pada 7 November 2026.',
          'Delapan tim bertanding, antara lain Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok, dan Dark Passage.',
          'Enam tim teratas lolos ke playoff dan memperebutkan US$40.000.',
          'M8 World Championship digelar di Istanbul pada Januari 2027 — event seri M pertama di Eropa.'],
  'impact': 'Hasil esports tidak mengubah nilai akun yang ada; skin Collector dan Legend serta jumlah hero tetap pendorong nilai utama dalam riset kami.'},
 'coc-blast': {'title': 'Event medali Equipment Blast Clash of Clans (9–22 September)',
  'desc': 'Event Equipment Blast berlangsung 9–22 September 2026: kumpulkan Tag Ticket dan Champ Medal untuk ditukar di Trader dengan hero equipment, ore, dan kosmetik. Town Hall 6+.',
  'lead': 'Supercell mengumumkan event medali Equipment Blast pada 9 September 2026; event berlangsung hingga 22 September pukul 08.00 UTC, dengan Trader buka hingga 24 September.',
  'new': ['Pertempuran multipemain memberi Tag Ticket; jalur event memberi Champ Medal, pasukan sementara, dan peti.',
          'Trader menjual hero equipment, ore, dan kosmetik dengan medali event.',
          'Pasukan sementara: Undertaker Yeti, K.A.N.E., Yeeter, dan Giant Giant.',
          'Tersedia mulai Town Hall 6.'],
  'impact': 'Hero equipment dan levelnya menentukan kekuatan hero, yang dalam riset kami mendorong nilai akun Clash of Clans; medali event adalah satu cara lagi untuk meng-upgrade-nya.'},
 'mc-wild': {'title': 'Update Minecraft Wilderness Bound: hutan belang, kasur jerami, dan kemah terbengkalai',
  'desc': 'Update Wilderness Bound dari Mojang hadir 15 September 2026 dengan bioma hutan belang, kayu poplar, kasur jerami, kemah terbengkalai, dan bantal duduk.',
  'lead': 'Mojang Studios menamai update ketiganya di 2026 "Wilderness Bound" pada 5 September dan merilisnya pada 15 September.',
  'new': ['Bioma baru, hutan belang, dengan pohon poplar tinggi dan jamur rak.',
          'Kasur jerami dari tiga bal jerami memungkinkan melewati malam tanpa mengubah titik spawn.',
          'Kemah terbengkalai untuk dijelajahi, dan bantal duduk dari tiga slab wol berwarna sama.',
          'Kayu poplar serta set beton dan wol yang diperluas untuk membangun.'],
  'impact': 'Akun Minecraft dinilai dari jenis, nama pengguna, dan cape-nya, bukan dari konten game, jadi update ini tidak mengubah nilai akun.'},
 'ff-award': {'title': 'Free Fire menang "Best Use of IP or Licence" di Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena menyampaikan pada 3 September 2026 bahwa Free Fire memenangi Best Use of IP or Licence di Pocket Gamer Mobile Games Awards 2026 berkat kolaborasi NARUTO SHIPPUDEN.',
  'lead': 'Garena mengumumkan pada 3 September 2026 bahwa Free Fire memenangi "Best Use of IP or Licence" di Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Penghargaan ini untuk kolaborasi NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Menurut Garena, event Ninja Clash All Stars di Bangkok dihadiri hampir 5.000 pengunjung dan meraih lebih dari 247 juta tayangan video.',
          'Kolaborasi ini menghadirkan karakter bertema, kemampuan jutsu, dan peta Desa Daun Tersembunyi yang diubah.',
          'Event komunitas digelar di Peru, Bangladesh, Malaysia, dan Taiwan.'],
  'impact': 'Penghargaan tidak mengubah nilai akun. Namun ini menegaskan bahwa kolaborasi berlisensi rutin hadir di Free Fire — dan bundle terbatasnya termasuk item langka yang diperhatikan penaksiran.'},
 'rbx-fall': {'title': 'Fall Games Preview Roblox: 10 experience hadir di September dan Oktober',
  'desc': 'Fall Games Preview Roblox (2 September 2026) memuat 10 experience baru, dari Showdown dan Nemesis di September hingga Prime Heroes, Octane, dan Starforged di Oktober.',
  'lead': 'Roblox merilis Fall Games Preview pada 2 September 2026, berisi sepuluh experience yang dijadwalkan untuk September dan Oktober.',
  'new': ['September: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force, dan Caramel.',
          'Oktober: Prime Heroes (early access di September dengan 6 hero), Octane, Starforged, dan Scrapbook Saga.',
          'Beberapa judul berasal dari program kreator Jumpstart dan Incubator milik Roblox.',
          'Genre-nya beragam, dari shooter dan balapan hingga horor bertahan hidup dan bertani.'],
  'impact': 'Experience baru tidak mengubah akun yang ada. Dalam riset kami, nilai akun Roblox berasal dari Robux, item limited, dan item di experience lama; game baru baru berarti setelah item-itemnya diperdagangkan.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: skin hero sekali rilis yang "tidak akan kembali" setelah 1 Oktober',
  'desc': 'Event WWE: Search for Cena dari Supercell (September 2026) menjual enam skin hero WWE yang menurut Supercell tidak akan kembali setelah 1 Oktober, plus scenery Money in the Bank.',
  'lead': 'Supercell mengumumkan event WWE: Search for Cena untuk Clash of Clans pada 1 September 2026; event berlangsung sepanjang September.',
  'new': ['Skin hero seharga $9,99: Cody Rhodes (Barbarian King), Alexa Bliss (Archer Queen), Iyo Sky (Royal Champion), Kane (Dragon Duke), dan American Badass Undertaker (Grand Warden).',
          'Jey Uso (Minion Prince) termasuk dalam Gold Pass.',
          'Supercell menyatakan skin ini "tidak akan kembali. Selamanya" setelah 1 Oktober.',
          'Scenery XL Money in the Bank tersedia 2–30 September, bersama tantangan John Cena dan pasukan WWE sementara.'],
  'impact': 'Skin yang menurut penerbit tidak akan pernah kembali adalah jenis kosmetik yang membuat akun Clash of Clans lebih langka. Namun level Town Hall dan hero tetap memegang sebagian besar nilai.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: sekilas format baru dua split',
  'desc': 'Pratinjau BSC 2027 dari Supercell (24 Agustus 2026): delapan tim per wilayah di empat wilayah, Challengers di 12 wilayah, dua split 12 minggu, Brawl Cup, dan World Finals.',
  'lead': 'Supercell memberi gambaran awal Brawl Stars Championship 2027 pada 24 Agustus 2026, dengan catatan detailnya masih bisa berubah.',
  'new': ['Level teratas: 8 tim per wilayah di Asia Timur, EMEA, Amerika Selatan, dan Amerika Utara.',
          'Challengers: jalur masuk di 12 wilayah.',
          'Dua split masing-masing 12 minggu; Split 1 diakhiri Brawl Cup, LAN internasional tiga hari, dan Split 2 diakhiri World Finals.',
          'Tanggal, total hadiah, dan lokasi belum diumumkan.'],
  'impact': 'Format esports tidak mengubah nilai akun yang ada; kalkulator Brawl Stars kami tetap memakai jumlah brawler, hypercharge, dan trofi.'},
}},
}
