# News translations: tl, sw (from news_data.py 'en', facts unchanged)
TEXT = {
'tl': {
 'ui': {
  'news': 'Balita', 'news_title': 'Mga balita sa laro na nakaaapekto sa halaga ng account',
  'news_lead': 'Mga opisyal na update mula sa mga game publisher — bawat isa ay sinuri laban sa mismong anunsyo ng publisher, may maikling paliwanag kung ano ang ibig sabihin nito para sa halaga ng account.',
  'game_title': 'Balita sa {game}', 'game_lead': 'Mga opisyal na update ng {game} na nakaaapekto sa halaga ng isang account. May link sa anunsyo ng publisher ang bawat artikulo.',
  'published': 'Inilathala', 'source': 'Opisyal na source', 'by_on': '{pub}, {date}', 'whats_new': 'Ano ang bago',
  'impact': 'Ano ang ibig sabihin nito para sa halaga ng account', 'more': 'Iba pang balita sa {game}', 'all': 'Lahat ng balita',
  'calc': '{game}: value calculator at market report', 'read': 'Basahin', 'latest': 'Pinakabagong balita sa {game}',
  'note': 'Hindi bumibili, nagbebenta o namamagitan ang GameAccountValue sa mga account. Ang mga balita ay buod ng mga anunsyo ng publisher para sa impormasyon lamang.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: dumating sina Vesna at Vodyanitsa, kumpirmado ang anniversary rewards',
   'desc': 'Inilabas noong Setyembre 23, 2026 ang Version 7.1 na "A Rekviem for the Underworld" na may dalawang bagong 5-star na karakter, dalawang 5-star na armas at rewards para sa ika-6 na anibersaryo.',
   'lead': 'Inilabas ng HoYoverse ang Version 7.1, "A Rekviem for the Underworld", noong Setyembre 23, 2026 — ang update na may kasamang ika-6 na anibersaryo ng Genshin Impact.',
   'new': ['Dalawang bagong 5-star na karakter: si Vesna (Anemo, espada) at si Vodyanitsa (Hydro, catalyst).',
           'Bagong armas: Beyond the Chrysalis (5-star na espada), Hymn of the Maelstrom (5-star na catalyst) at New Bough (4-star na espada).',
           'Anniversary rewards na inanunsyo ng HoYoverse: dalawang 5-star na karakter na maiimbitahan, Intertwined Fate ×10, Primogems ×1,600 at reset ng first top-up bonus ng Genesis Crystal.',
           'Nagsimula ang update maintenance noong Setyembre 23, 06:00 (UTC+8).'],
   'impact': 'Sa aming pananaliksik, ang bilang ng limited na 5-star na karakter, ang kanilang constellation at signature weapon ay kabilang sa pangunahing nagpapataas ng halaga ng Genshin account. Ang mga karakter na libreng ibinigay sa lahat para sa anibersaryo ay hindi nagpapaespesyal sa account gaya ng mga karakter mula sa limited banner.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, ang unang bagong dimension sa loob ng mahigit 14 na taon, darating sa Java at Bedrock',
   'desc': 'Sa Minecraft Live noong Setyembre 26, 2026, ipinakita ang The Sift, ikaapat na dimension na darating sa Java at Bedrock sa susunod na taon, pati ang Dungeons II at ang Wilderness Bound update.',
   'lead': 'Sa Minecraft Live noong Setyembre 26, 2026, inanunsyo ng Mojang Studios na darating sa Minecraft Java at Bedrock Edition sa susunod na taon ang ikaapat na dimension ng laro, ang The Sift.',
   'new': ['Ang The Sift ang unang bagong dimension sa loob ng mahigit 14 na taon, kasama ng Overworld, Nether at End.',
           'Unang lalabas ito sa Minecraft Dungeons II, na itinakda ng Mojang para sa Setyembre 29, 2026.',
           'Magbubukas sa London sa 2027 ang Minecraft World, isang themed attraction.',
           'Dumating noong Setyembre 15 ang Wilderness Bound update na may dappled forest, straw bed, abandonadong kampo at cushion.'],
   'impact': 'Tinatasa ang Minecraft account batay sa uri (Java o Bedrock), username at mga cape — hindi sa laman ng laro. Binabago ng ganitong mga update kung ano ang puwedeng gawin ng mga manlalaro, hindi ang halaga ng account.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": limited na UGC item at exclusive ng Roblox Plus (Setyembre 17–28)',
   'desc': 'Ginanap ang The Hunt: Roblox 20 mula Setyembre 17 hanggang 28, 2026 na may UGC rewards, limited-release na UGC item at tatlong exclusive item para sa mga subscriber ng Roblox Plus.',
   'lead': 'Ipinagdiwang ng Roblox ang ika-20 anibersaryo nito sa The Hunt: Roblox 20, isang event sa buong platform mula Setyembre 17 hanggang 28, 2026.',
   'new': ['Dinaanan ng mga manlalaro ang 20 taon ng kasaysayan ng Roblox, isang quest bawat taon, simula sa "Year Zero"; kapag natapos ang lahat ng 20, bubukas ang "Year Infinity" na may 20 pang laro.',
           'Nagbigay ng UGC item ang mga quest, at may mga limited-release na UGC item habang tumatakbo ang event.',
           'Tatlong exclusive na virtual item ang natanggap ng mga subscriber ng Roblox Plus, at mananatili sa kanila pagkatapos ng event ang Classic app theme, classic avatar background at profile frame.',
           'Libre para sa lahat ang Classic app theme habang tumatakbo ang event.'],
   'impact': 'Ang mga item na makukuha lang habang may event ay kabilang sa tinitingnan ng isang appraisal. Hindi pinangalanan ng Roblox ang mga item sa anunsyo nito, kaya hindi pa sila nilalagyan ng presyo ng site na ito hangga’t walang totoong listing.'},
  'rbx-rdc': {
   'title': 'RDC 2026: kumita ang mga Roblox creator ng mga $1.7 bilyon sa isang taon; inanunsyo ang Roblox Wallet',
   'desc': 'Sa RDC 2026, iniulat ng Roblox na mga $1.7 bilyon ang kinita ng mga creator sa loob ng 12 buwan at inanunsyo ang Roblox Wallet at Roblox Card para sa mga payout.',
   'lead': 'Sa developer conference na RDC 2026 (anunsyo noong Setyembre 11, 2026), ibinahagi ng Roblox ang kita ng mga creator at mga bagong payout tool.',
   'new': ['Kumita na ang mga creator ng mahigit $5 bilyon mula nang ilunsad ang DevEx noong 2013, at mga $1.7 bilyon sa 12 buwan hanggang Hunyo 30, 2026.',
           'Nakapagbigay ang Roblox Plus incentives ng mahigit 300 milyong Robux na kita sa mga creator sa unang apat na buwan (hanggang Agosto 17, 2026).',
           'Ang Roblox Wallet, isang payments account kasama ang Airwallex US, ay magbibigay ng araw-araw na payout sa totoong pera — una para sa mga kwalipikadong independent creator sa U.S. na 18+ sa huling bahagi ng 2026, at internasyonal sa 2027.',
           'May planong Roblox Card na naka-link sa Wallet simula 2027.'],
   'impact': 'Tungkol sa payout ng mga creator ang mga pagbabagong ito, hindi sa account ng mga manlalaro: hindi binago ng anunsyo ang presyo ng Robux, mga limited item o trading. Robux balance at limited item pa rin ang tinitimbang ng aming Roblox calculator.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: apat na bagong armas sa Clash Squad, Prime Diamond at rework kay Kenta',
   'desc': 'Idinagdag ng OB55 patch notes ng Garena (Setyembre 10, 2026) ang M7, Skorp, RPK at Hawk sa Clash Squad simula Oktubre 1, ipinakilala ang Prime Diamond at ni-rework si Kenta.',
   'lead': 'Inilabas ng Garena ang OB55 patch notes ng Free Fire noong Setyembre 10, 2026; magkakabisa ang mga pagbabago sa armas sa Oktubre 1.',
   'new': ['Bagong armas sa Clash Squad simula Oktubre 1: M7 (1,600 CS Cash), Skorp (1,500), RPK (1,500) at Hawk (1,700).',
           'Prime Diamond: diamond na nakukuha ayon sa buwanang gastos, puwedeng i-claim sa susunod na buwan pagkatapos ng anumang top-up.',
           'Ganap na ni-rework si Kenta; may balance change sina Morse, Luna at Wukong.',
           'Nagbago ang mobility ayon sa klase ng armas simula Oktubre 1: mas mabilis ang SMG, mas mabagal ang sniper at marksman rifle.'],
   'impact': 'Tinitimbang ng aming Free Fire calculator ang diamond balance at mga bihirang bundle. Binabago ng OB55 kung paano gagantimpalaan ang mga susunod na top-up; hindi nito binabago ang mga item na nasa mga account na.'},
  'cr-minion': {
   'title': 'Clash Royale season na "Minion Academy": bagong card na Minion Giant at hero na Ice Wizard',
   'desc': 'Idinagdag ng Minion Academy season (Setyembre 7 – Oktubre 5, 2026) ang card na Minion Giant, ang hero na Ice Wizard at isang album event na may 1,750 Minion Giant card.',
   'lead': 'Binuksan ng Supercell ang Clash Royale season na "Minion Academy", mula Setyembre 7 hanggang Oktubre 5, 2026.',
   'new': ['Bagong card na Minion Giant: isang lumilipad na win condition na tumatarget sa mga gusali at tower. Libre ito sa album event na Academy Antics at sa susunod na season pa lalabas sa mga chest.',
           'Nagbibigay ang album event ng 1,750 Minion Giant card, isang emote at isang tower skin.',
           'Bagong hero: Ice Wizard, mula sa Pass Royale track o sa halagang 200 Hero Coin.',
           'Mga event: 2v2 League (Setyembre 7–21), Princess Gambit global tournament (Setyembre 21–26) at Royale Shuffle (Setyembre 21 – Oktubre 5). Ang tabla sa Ultimate Champion ay kalahati na lang ng trophy na nawawala sa pagkatalo.'],
   'impact': 'Ang mga tower skin at emote na inaalok lang habang may event ay nagpapaespesyal sa isang Clash Royale collection, pero King Tower level at card level pa rin ang pangunahing batayan ng halaga.'},
  'ml-10': {
   'title': 'Mobile Legends, 10 taon na: ALL IN campaign at bagong Collector skin ni Layla',
   'desc': 'Ang ALL IN campaign ng MOONTON para sa ika-10 anibersaryo (mula Setyembre 4, 2026) ay may bagong Epic skin ni Nana, libreng skin chest at Collector skin ni Layla simula Oktubre 9.',
   'lead': 'Inilunsad ng MOONTON Games noong Setyembre 4, 2026 ang ALL IN, ang campaign para sa ika-10 anibersaryo ng Mobile Legends: Bang Bang.',
   'new': ['10th Anniversary Celebration Pass (Setyembre 4 – Nobyembre 1): bagong Epic skin ni Nana, Epic Skin Selection Chest, Random Epic Skin Chest at libreng anniversary skin para sa mga bumabalik na manlalaro.',
           'Anniversary Gala Weekend (Setyembre 25 – Oktubre 11): access sa 265 skin, Battle Pass EXP at Premium Skin Fragment.',
           'Layla’s Stellar Gala (Oktubre 9 – Nobyembre 19): ang bagong Collector skin ni Layla sa mini-game na "Starfall Breakout".',
           'Ayon sa MOONTON, may mahigit 1.5 bilyong install at 110 milyong aktibong manlalaro bawat buwan ang laro.'],
   'impact': 'Ang mga Collector at Legend skin ay kabilang sa pinakamadalas banggitin na batayan ng halaga ng Mobile Legends account; hindi kasama ang mga skin na libreng ipinamigay o trial.'},
  'bs-aug': {
   'title': 'Brawl Stars: Mythic brawler na sina Cosmo at Vince; naging Brawler Blast ang Starr Road',
   'desc': 'Idinagdag ng August 2026 release notes ng Supercell (Setyembre 1) ang dalawang Mythic brawler, ginawang Brawler Blast ang Starr Road na may bagong credit cost at pinalitan ng Ultra ang pangalang Ultra Legendary.',
   'lead': 'Inilabas ng Supercell ang release notes ng Brawl Stars para sa August 2026 update noong Setyembre 1, 2026.',
   'new': ['Dalawang bagong Mythic brawler: si Cosmo (Controller) at si Vince (Damage Dealer).',
           'Bagong Hypercharge para kina Nori at Wendy.',
           'Ginawang "Brawler Blast" ang Starr Road: napupunta na ang credits sa pag-unlock ayon sa rarity — Rare 160, Super Rare 430, Epic 925, Mythic 1,900, Legendary 3,800, Ultra 5,500.',
           'Pinalitan ng "Ultra" ang pangalan ng rarity na "Ultra Legendary". Kasama rin ang Royal Academy season at isang buwang Brawl-O-Ween event.'],
   'impact': 'Ginagamit ng aming Brawl Stars calculator ang bilang ng brawler, Hypercharge at trophy. Dahil sa dalawa pang Mythic, dumami ang brawler na kailangan para sa kumpletong koleksyon.'},
  'coc-aug': {
   'title': 'August update ng Clash of Clans: Diggy level 11–15 at Gold Pass mula Town Hall 3',
   'desc': 'Idinagdag ng August 2026 update ng Supercell (Agosto 30) ang Diggy level 11–15 at bagong supercharge sa Town Hall 18, tinanggal ang Starter Pass at binuksan ang Gold Pass mula Town Hall 3.',
   'lead': 'Inilabas ng Supercell ang August update ng Clash of Clans noong Agosto 30, 2026.',
   'new': ['Town Hall 18: nakakuha ang pet na si Diggy ng level 11–15; may bagong supercharge level ang Builder’s Hut at ang Monolith.',
           'Tinanggal ang Starter Pass: available na ang Season Challenges at Gold Pass mula Town Hall 3, at nakadepende ang rewards sa Town Hall level.',
           'Hindi na nababawasan ng buhay ang Ruin Knight habang tumatagal; 10 Ruin Knight na ang tinatawag ng Ruin Witch sa halip na 8.',
           'Inayos ang mga modifier ng Clan War League sa mga Titan league.'],
   'impact': 'Sa aming pananaliksik, Town Hall level at level ng hero at pet ang nagtatakda ng halaga ng Clash of Clans account. Dahil sa bagong maximum level sa Town Hall 18, mas maraming upgrade na ang kailangan ng isang "maxed" na account kaysa bago ang update.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 "Override": Battle Pass ni Sonic at crossover sa KINGDOM HEARTS',
   'desc': 'Hatid ng season na "Override" ng Epic (Chapter 7, Season 4) ang Override Console, isang 800 V-Bucks na Battle Pass na pinangungunahan ni Sonic the Hedgehog, at mga crossover kabilang ang KINGDOM HEARTS.',
   'lead': '"Override" ang pangalan ng Chapter 7 Season 4 ng Fortnite. Inilalarawan ito ng Epic bilang season ng mga gaming crossover at pagbabago ng patakaran para sa buong laban.',
   'new': ['Lumalabas ang Override Console sa bawat laban at hinahayaan ang mga manlalaro na baguhin ang patakaran para sa buong server.',
           '800 V-Bucks ang Battle Pass at si Sonic the Hedgehog ang bida, kasama ang Tails Sidekick.',
           'Ang mga bumili ng Pass bago ang Agosto 27, 11:59 PM ET ay nakatanggap ng outfit na Infiltrator Grace Crowne bilang launch-week bonus.',
           'Mga crossover ngayong season: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot at Spyro the Dragon; kabilang sa mga armas ang Midas’ Masterpiece at ang Mega Buster ni Mega Man.'],
   'impact': 'Ang mga outfit na available lang sa limitadong panahon — gaya ng launch-week bonus — ang nagpapaiba sa bihirang Fortnite locker mula sa karaniwan. Nananatiling nakatali sa kanilang season ang mga Battle Pass outfit.'},
 }},
'sw': {
 'ui': {
  'news': 'Habari', 'news_title': 'Habari za michezo zinazoathiri thamani ya akaunti',
  'news_lead': 'Masasisho rasmi kutoka kwa wachapishaji wa michezo — kila moja limelinganishwa na tangazo la mchapishaji mwenyewe, pamoja na maelezo mafupi kuhusu maana yake kwa thamani ya akaunti.',
  'game_title': 'Habari za {game}', 'game_lead': 'Masasisho rasmi ya {game} yanayoathiri thamani ya akaunti. Kila makala ina kiungo cha tangazo la mchapishaji.',
  'published': 'Imechapishwa', 'source': 'Chanzo rasmi', 'by_on': '{pub}, {date}', 'whats_new': 'Kipya ni nini',
  'impact': 'Maana yake kwa thamani ya akaunti', 'more': 'Habari zaidi za {game}', 'all': 'Habari zote',
  'calc': '{game}: kikokotoo cha thamani na ripoti ya soko', 'read': 'Soma', 'latest': 'Habari mpya za {game}',
  'note': 'GameAccountValue hainunui, haiuzi wala haiwi dalali wa akaunti. Habari ni muhtasari wa matangazo ya wachapishaji kwa ajili ya taarifa tu.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna na Vodyanitsa wamewasili, zawadi za maadhimisho zimethibitishwa',
   'desc': 'Toleo la 7.1 "A Rekviem for the Underworld" lilitoka tarehe 23 Septemba 2026 likiwa na wahusika wawili wapya wa nyota 5, silaha mbili za nyota 5 na zawadi za maadhimisho ya sita.',
   'lead': 'HoYoverse ilitoa Toleo la 7.1, "A Rekviem for the Underworld", tarehe 23 Septemba 2026 — sasisho ambalo pia linaleta maadhimisho ya sita ya Genshin Impact.',
   'new': ['Wahusika wawili wapya wa nyota 5: Vesna (Anemo, upanga) na Vodyanitsa (Hydro, catalyst).',
           'Silaha mpya: Beyond the Chrysalis (upanga wa nyota 5), Hymn of the Maelstrom (catalyst ya nyota 5) na New Bough (upanga wa nyota 4).',
           'Zawadi za maadhimisho zilizotangazwa na HoYoverse: wahusika wawili wa nyota 5 wa kualika, Intertwined Fate ×10, Primogems ×1,600 na kuwekwa upya kwa bonasi ya kwanza ya kujaza Genesis Crystal.',
           'Matengenezo ya sasisho yalianza tarehe 23 Septemba saa 06:00 (UTC+8).'],
   'impact': 'Katika utafiti wetu, idadi ya wahusika wa nyota 5 wa muda mfupi, constellation zao na silaha zao maalum ni miongoni mwa vichocheo vikuu vya thamani ya akaunti ya Genshin. Wahusika wanaotolewa bure kwa kila mtu kwenye maadhimisho hawaifanyi akaunti kuwa ya kipekee kama wahusika wa banner za muda mfupi.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, ulimwengu mpya wa kwanza baada ya zaidi ya miaka 14, unakuja kwa Java na Bedrock',
   'desc': 'Minecraft Live ya tarehe 26 Septemba 2026 ilitangaza The Sift, ulimwengu wa nne utakaokuja kwa Java na Bedrock mwaka ujao, pamoja na Dungeons II na sasisho la Wilderness Bound.',
   'lead': 'Katika Minecraft Live tarehe 26 Septemba 2026, Mojang Studios ilitangaza kwamba ulimwengu wa nne wa mchezo, The Sift, utakuja kwa Minecraft Java na Bedrock Edition mwaka ujao.',
   'new': ['The Sift ni ulimwengu (dimension) mpya wa kwanza baada ya zaidi ya miaka 14, ukiungana na Overworld, Nether na End.',
           'Unaanza kuonekana kwenye Minecraft Dungeons II, ambayo Mojang iliipangia tarehe 29 Septemba 2026.',
           'Minecraft World, kivutio chenye mandhari ya mchezo, kitafunguliwa London mwaka 2027.',
           'Sasisho la Wilderness Bound lilitoka tarehe 15 Septemba likiwa na msitu wenye madoa, vitanda vya majani makavu, kambi zilizotelekezwa na mito ya kukalia.'],
   'impact': 'Akaunti za Minecraft hupimwa kwa aina yake (Java au Bedrock), jina la mtumiaji na makoti (capes) — si kwa maudhui ya ndani ya mchezo. Masasisho kama haya hubadilisha kile wachezaji wanaweza kufanya, si thamani ya akaunti.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": vitu vya UGC vya toleo dogo na vya kipekee vya Roblox Plus (Septemba 17–28)',
   'desc': 'The Hunt: Roblox 20 ilifanyika kuanzia Septemba 17 hadi 28, 2026 ikiwa na zawadi za UGC, vitu vya UGC vya toleo dogo na vitu vitatu vya kipekee kwa wanachama wa Roblox Plus.',
   'lead': 'Roblox iliadhimisha miaka 20 kwa The Hunt: Roblox 20, tukio la jukwaa zima lililofanyika kuanzia Septemba 17 hadi 28, 2026.',
   'new': ['Wachezaji walipitia miaka 20 ya historia ya Roblox, jukumu moja kwa kila mwaka, kuanzia "Year Zero"; kumaliza miaka yote 20 kulifungua "Year Infinity" yenye michezo 20 zaidi.',
           'Majukumu yalitoa vitu vya UGC, na vitu vya UGC vya toleo dogo vilipatikana wakati wa tukio.',
           'Wanachama wa Roblox Plus walipokea vitu vitatu vya kipekee vya kidijitali na wanaendelea kuwa na mandhari ya programu ya Classic, mandharinyuma ya avatar ya zamani na fremu ya wasifu baada ya tukio.',
           'Mandhari ya programu ya Classic ilikuwa bure kwa kila mtu wakati wa tukio.'],
   'impact': 'Vitu vilivyoweza kupatikana tu wakati wa tukio ni miongoni mwa mambo ambayo tathmini huyaangalia. Roblox haikutaja majina ya vitu hivyo katika tangazo lake, kwa hiyo tovuti hii haiviwekei bei hadi kuwe na matangazo halisi ya kuuza.'},
  'rbx-rdc': {
   'title': 'RDC 2026: watengenezaji wa Roblox walipata takriban dola bilioni 1.7 kwa mwaka; Roblox Wallet yatangazwa',
   'desc': 'Katika RDC 2026 Roblox iliripoti mapato ya watengenezaji ya takriban dola bilioni 1.7 ndani ya miezi 12 na ikatangaza Roblox Wallet na Roblox Card kwa malipo.',
   'lead': 'Katika mkutano wake wa wasanidi RDC 2026 (tangazo la tarehe 11 Septemba 2026), Roblox ilitoa takwimu za mapato ya watengenezaji na zana mpya za malipo.',
   'new': ['Watengenezaji wamepata zaidi ya dola bilioni 5 tangu DevEx ilipozinduliwa mwaka 2013, na takriban dola bilioni 1.7 katika miezi 12 hadi 30 Juni 2026.',
           'Vivutio vya Roblox Plus vilizalisha zaidi ya Robux milioni 300 za mapato kwa watengenezaji katika miezi yake minne ya kwanza (hadi 17 Agosti 2026).',
           'Roblox Wallet, akaunti ya malipo inayoendeshwa pamoja na Airwallex US, itatoa malipo ya kila siku kwa pesa halisi — kwanza kwa watengenezaji huru wa Marekani wenye umri wa 18+ wanaostahiki mwishoni mwa 2026, na kimataifa mwaka 2027.',
           'Roblox Card iliyounganishwa na Wallet imepangwa kuanzia 2027.'],
   'impact': 'Mabadiliko haya yanahusu malipo ya watengenezaji, si akaunti za wachezaji: tangazo halikubadilisha bei za Robux, vitu vya limited wala biashara. Salio la Robux na vitu vya limited ndivyo kikokotoo chetu cha Roblox kinavyoendelea kupima.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: silaha nne mpya za Clash Squad, Prime Diamond na Kenta kufanyiwa upya',
   'desc': 'Maelezo ya kiraka cha OB55 kutoka Garena (10 Septemba 2026) yanaongeza M7, Skorp, RPK na Hawk kwenye Clash Squad kuanzia 1 Oktoba, yanaleta Prime Diamond na kumfanyia upya Kenta.',
   'lead': 'Garena ilichapisha maelezo ya kiraka cha OB55 cha Free Fire tarehe 10 Septemba 2026; mabadiliko ya silaha yanaanza kutumika tarehe 1 Oktoba.',
   'new': ['Silaha mpya za Clash Squad kuanzia 1 Oktoba: M7 (1,600 CS Cash), Skorp (1,500), RPK (1,500) na Hawk (1,700).',
           'Prime Diamond: almasi zinazopatikana kulingana na matumizi ya mwezi, zinazoweza kudaiwa mwezi unaofuata baada ya kujaza salio mara yoyote.',
           'Kenta amefanyiwa upya kabisa; Morse, Luna na Wukong wamepata marekebisho ya uwiano.',
           'Mabadiliko ya wepesi wa kutembea kwa kila aina ya silaha kuanzia 1 Oktoba: SMG ni za kasi zaidi, bunduki za sniper na marksman ni za polepole zaidi.'],
   'impact': 'Kikokotoo chetu cha Free Fire kinapima salio la almasi na vifurushi adimu. OB55 inabadilisha jinsi ujazaji wa baadaye unavyozawadiwa; haibadilishi vitu vilivyomo tayari kwenye akaunti.'},
  'cr-minion': {
   'title': 'Msimu wa Clash Royale "Minion Academy": kadi mpya Minion Giant na shujaa Ice Wizard',
   'desc': 'Msimu wa Minion Academy (7 Septemba – 5 Oktoba 2026) unaongeza kadi ya Minion Giant, shujaa Ice Wizard na tukio la albamu lenye kadi 1,750 za Minion Giant.',
   'lead': 'Supercell ilifungua msimu wa Clash Royale "Minion Academy", unaoendelea kuanzia 7 Septemba hadi 5 Oktoba 2026.',
   'new': ['Kadi mpya Minion Giant: kadi ya ushindi inayoruka na kulenga majengo na minara. Inapatikana bure kupitia tukio la albamu la Academy Antics na haitaonekana kwenye masanduku hadi msimu ujao.',
           'Tukio la albamu linatoa kadi 1,750 za Minion Giant, emote moja na ngozi ya mnara.',
           'Shujaa mpya: Ice Wizard, kupitia njia ya Pass Royale au kwa Hero Coin 200.',
           'Matukio: Ligi ya 2v2 (Septemba 7–21), mashindano ya dunia ya Princess Gambit (Septemba 21–26) na Royale Shuffle (21 Septemba – 5 Oktoba). Sare katika Ultimate Champion sasa inagharimu nusu ya vikombe vya kushindwa.'],
   'impact': 'Ngozi za minara na emote zinazotolewa wakati wa tukio pekee huufanya mkusanyiko wa Clash Royale kuwa wa kipekee zaidi, lakini kiwango cha King Tower na viwango vya kadi vinabaki kuwa vichocheo vikuu vya thamani.'},
  'ml-10': {
   'title': 'Mobile Legends yatimiza miaka 10: kampeni ya ALL IN na ngozi mpya ya Collector ya Layla',
   'desc': 'Kampeni ya ALL IN ya MOONTON ya miaka 10 (kuanzia 4 Septemba 2026) inaleta ngozi mpya ya Epic ya Nana, masanduku ya ngozi ya bure na ngozi ya Collector ya Layla kuanzia 9 Oktoba.',
   'lead': 'MOONTON Games ilizindua ALL IN, kampeni ya maadhimisho ya miaka kumi ya Mobile Legends: Bang Bang, tarehe 4 Septemba 2026.',
   'new': ['Pasi ya Sherehe ya Miaka 10 (4 Septemba – 1 Novemba): ngozi mpya ya Epic ya Nana, Epic Skin Selection Chest, Random Epic Skin Chest na ngozi ya bure ya maadhimisho kwa wachezaji wanaorudi.',
           'Anniversary Gala Weekend (25 Septemba – 11 Oktoba): kutumia ngozi 265, EXP ya Battle Pass na vipande vya ngozi za Premium.',
           'Layla’s Stellar Gala (9 Oktoba – 19 Novemba): ngozi mpya ya Collector ya Layla kupitia mchezo mdogo wa "Starfall Breakout".',
           'MOONTON inataja zaidi ya usakinishaji bilioni 1.5 na wachezaji milioni 110 wanaocheza kila mwezi.'],
   'impact': 'Ngozi za Collector na Legend ni miongoni mwa vichocheo vya thamani vinavyotajwa zaidi kwa akaunti za Mobile Legends; ngozi zinazotolewa bure au za majaribio sivyo.'},
  'bs-aug': {
   'title': 'Brawl Stars: brawler wa Mythic Cosmo na Vince; Starr Road inakuwa Brawler Blast',
   'desc': 'Maelezo ya sasisho la Agosti 2026 kutoka Supercell (1 Septemba) yanaongeza brawler wawili wa Mythic, yanabadilisha Starr Road kuwa Brawler Blast yenye gharama mpya za credits, na kubadilisha jina Ultra Legendary kuwa Ultra.',
   'lead': 'Supercell ilichapisha maelezo ya sasisho la Agosti 2026 la Brawl Stars tarehe 1 Septemba 2026.',
   'new': ['Brawler wawili wapya wa Mythic: Cosmo (Controller) na Vince (Damage Dealer).',
           'Hypercharge mpya kwa Nori na Wendy.',
           'Starr Road imegeuzwa kuwa "Brawler Blast": credits sasa zinaenda kufungua kwa kiwango cha uadimu — Rare 160, Super Rare 430, Epic 925, Mythic 1,900, Legendary 3,800, Ultra 5,500.',
           'Kiwango cha uadimu "Ultra Legendary" sasa kinaitwa "Ultra". Pia msimu wa Royal Academy na tukio la Brawl-O-Ween la mwezi mzima.'],
   'impact': 'Kikokotoo chetu cha Brawl Stars kinatumia idadi ya brawler, Hypercharge na vikombe. Mythic wawili zaidi wanaongeza idadi ya brawler wanaohitajika kwa mkusanyiko kamili.'},
  'coc-aug': {
   'title': 'Sasisho la Agosti la Clash of Clans: Diggy viwango 11–15 na Gold Pass kuanzia Town Hall 3',
   'desc': 'Sasisho la Agosti 2026 la Supercell (30 Agosti) linaongeza viwango 11–15 vya Diggy na supercharge mpya kwenye Town Hall 18, linaondoa Starter Pass na kufungua Gold Pass kuanzia Town Hall 3.',
   'lead': 'Supercell ilitoa sasisho la Agosti la Clash of Clans tarehe 30 Agosti 2026.',
   'new': ['Town Hall 18: mnyama kipenzi Diggy anapata viwango 11–15; Builder’s Hut na Monolith zinapata viwango vipya vya supercharge.',
           'Starter Pass imeondolewa: Season Challenges na Gold Pass sasa zinapatikana kuanzia Town Hall 3, zawadi zikiendana na kiwango cha Town Hall.',
           'Ruin Knight hapotezi tena afya kadiri muda unavyopita; Ruin Witch anaita Ruin Knight 10 badala ya 8.',
           'Virekebishaji vya Clan War League katika ligi za Titan vimerekebishwa.'],
   'impact': 'Katika utafiti wetu, kiwango cha Town Hall pamoja na viwango vya mashujaa na wanyama vipenzi ndivyo vinavyoamua thamani ya akaunti za Clash of Clans. Viwango vipya vya juu kwenye Town Hall 18 vinamaanisha kuwa akaunti "iliyojaa" sasa inahitaji maboresho zaidi kuliko kabla ya sasisho.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 "Override": Battle Pass ya Sonic na ushirikiano na KINGDOM HEARTS',
   'desc': 'Msimu wa "Override" wa Epic (Chapter 7, Season 4) unaleta Override Console, Battle Pass ya V-Bucks 800 inayoongozwa na Sonic the Hedgehog, na ushirikiano ikiwemo KINGDOM HEARTS.',
   'lead': 'Chapter 7 Season 4 ya Fortnite inaitwa "Override". Epic inauelezea kama msimu wa ushirikiano na michezo mingine na kubadilisha sheria kwa mechi nzima.',
   'new': ['Override Console zinaonekana katika kila mechi na zinawaruhusu wachezaji kubadilisha sheria kwa seva nzima.',
           'Battle Pass inagharimu V-Bucks 800 na inaongozwa na Sonic the Hedgehog, akiwa pamoja na Tails kama msaidizi.',
           'Walionunua Pass kabla ya 27 Agosti saa 11:59 usiku (saa za mashariki ya Marekani) walipata vazi la Infiltrator Grace Crowne kama bonasi ya wiki ya uzinduzi.',
           'Ushirikiano wa msimu huu: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot na Spyro the Dragon; silaha ni pamoja na Midas’ Masterpiece na Mega Buster ya Mega Man.'],
   'impact': 'Mavazi yanayopatikana kwa muda mfupi tu — kama bonasi ya wiki ya uzinduzi — ndiyo yanayotofautisha makabati adimu ya Fortnite na ya kawaida. Mavazi ya Battle Pass yanabaki kufungamana na msimu yalikotoka.'},
 }},
}
