# News batch 2: ms, uz (from news_text_b2_en.py, facts unchanged)
TEXT = {
'ms': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II kini dilancarkan: dimensi Sift dan Majlis Tertinggi Illager',
  'desc': 'Mojang melancarkan Minecraft Dungeons II pada 29 September 2026 di Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch dan Switch 2, dengan main bersama sehingga 4 pemain.',
  'lead': 'Mojang Studios melancarkan Minecraft Dungeons II pada 29 September 2026.',
  'new': ['Tersedia di Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch dan Nintendo Switch 2.',
          'Jalan ceritanya menemukan pemain dengan Majlis Tertinggi Illager: Prime Enchanter, Supreme Evoker dan Grand Illusioner.',
          'Pemain meneroka dimensi baharu, Sift, yang menurut Mojang juga akan tiba di Minecraft Java dan Bedrock tahun depan.',
          'Boleh dimain seorang atau bersama sehingga 4 pemain, dalam talian atau pada skrin yang sama.'],
  'impact': 'Dungeons II ialah permainan berasingan. Akaun Minecraft Java dan Bedrock masih dinilai mengikut jenis, nama pengguna dan jubah, jadi pelancaran ini tidak mengubah nilainya.'},
 'cr-mt-oct': {'title': 'Merge Tactics Clash Royale: perubahan Oktober untuk Super, Elixir dan lencana',
  'desc': 'Mulai 1 Oktober 2026, musim 11 Merge Tactics memindahkan Super ke kolam bersama, mengurangkan Elixir setiap pusingan daripada 5 kepada 4 dan menambah kulit tahap 5; peraturan lencana berubah pada musim 12.',
  'lead': 'Supercell mengumumkan perubahan Oktober untuk musim 11 Merge Tactics pada 30 September 2026; ia berkuat kuasa mulai 1 Oktober.',
  'new': ['Super bukan lagi tentera permulaan: ia masuk ke kolam bersama yang direbut semua pemain.',
          'Elixir yang diperoleh setiap pusingan kembali daripada 5 kepada 4.',
          'Battle Machine dan Dagger Duchess mendapat kulit tahap 5 untuk pemain yang sudah menaik tarafnya.',
          'Mulai musim 12, lencana Perak memerlukan Liga Berlian dan lencana Emas memerlukan kedudukan 10,000 teratas.'],
  'impact': 'Mulai musim 12, lencana kedudukan tinggi lebih sukar diperoleh, jadi ia menunjukkan kemahiran dengan lebih jelas pada profil Clash Royale. Tahap King Tower dan tahap kad kekal sebagai pemacu nilai utama.'},
 'ml-mplph': {'title': 'Playoff MPL Filipina Musim 18: PhilSports Arena, 21–25 Oktober',
  'desc': 'MOONTON mengumumkan pada 26 September 2026 bahawa playoff MPL Filipina Musim 18 berlangsung 21–25 Oktober di PhilSports Arena dan menentukan pasukan Filipina ke M8.',
  'lead': 'MOONTON Games mengumumkan lokasi dan tarikh playoff MPL Filipina Musim 18 pada 26 September 2026.',
  'new': ['Playoff berlangsung di PhilSports Arena, Pasig, dari 21 hingga 25 Oktober 2026.',
          'Ia menentukan pasukan yang mewakili Filipina di Kejohanan Dunia M8 di Istanbul pada Januari 2027.',
          'Jualan tiket dibuka pada 26 September, bermula PHP 200.',
          'Pengumuman ini meraikan ulang tahun ke-10 permainan: 1.5 bilion pemasangan dan 110 juta pemain aktif bulanan.'],
  'impact': 'Acara e-sukan tidak mengubah nilai akaun sedia ada. Dalam penyelidikan kami, nilai akaun Mobile Legends ditentukan oleh skin, hero dan kemajuan.'},
 'cr-bal-sep': {'title': 'Imbangan September Clash Royale: wira Ice Wizard dan Minion Giant dilemahkan',
  'desc': 'Nota imbangan September 2026 Supercell memendekkan pembekuan wira Ice Wizard daripada 7 kepada 5 saat dan kerosakan Minion Giant daripada 189 kepada 168, serta mengolah semula wira Mega Minion dan Wizard.',
  'lead': 'Supercell menerbitkan dua pusingan perubahan imbangan Clash Royale, berkuat kuasa pada 8 dan 16 September 2026.',
  'new': ['16 September: pembekuan wira Ice Wizard 7 s → 5 s; kebolehan Goblinstein 4 s → 3.5 s; kerosakan Minion Giant 189 → 168; kerosakan Fire Spirit 207 → 215.',
          '8 September: Freeze 4 s → 3.5 s; kerosakan Fireball pada menara 172 → 159; mata nyawa Ice Golem 1,315 → 1,228.',
          'Olah semula: wira Mega Minion (kembali melalui teleport, kerosakan 399 → 422) dan wira Wizard (kebolehan 5 s → 3.5 s); kerosakan Wizard 281 → 304.',
          'Yang diperkuat termasuk Ronin, Spirit Empress dan Goblin Cage.'],
  'impact': 'Imbangan mengubah kad yang popular, bukan apa yang dimiliki akaun. Dalam penyelidikan kami, nilai Clash Royale mengikut tahap King Tower, tahap kad, evolusi dan kosmetik yang jarang ditemui.'},
 'gi-wish71': {'title': 'Event Wish Genshin Impact 7.1: sepanduk Vesna dan Vodyanitsa hingga 13 Oktober',
  'desc': 'Event Wish fasa I Versi 7.1 HoYoverse meningkatkan peluang Vesna dan Vodyanitsa hingga 13 Oktober 2026, dengan Diona, Faruzan dan Chongyun sebagai watak 4 bintang yang dipertingkat.',
  'lead': 'HoYoverse menerbitkan Event Wish fasa I Versi 7.1 pada 21 September 2026; ia berlangsung hingga 13 Oktober 2026 jam 17:59.',
  'new': ['"When Warm Winds Cavort" meningkatkan peluang mendapat Vesna (Anemo).',
          '"Surging Ballad" meningkatkan peluang mendapat Vodyanitsa (Hydro).',
          'Watak 4 bintang yang dipertingkat: Diona (Cryo), Faruzan (Anemo) dan Chongyun (Cryo).',
          'Watak eksklusif acara tiada dalam wish standard; dua sepanduk watak berkongsi satu kiraan pity.'],
  'impact': 'Dalam penyelidikan kami, watak yang hanya boleh diperoleh daripada sepanduk terhad, berserta konstelasinya, ialah antara pemacu utama nilai akaun Genshin.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: kulit Trash Goblin Darryl dan ganjaran hingga 30 September',
  'desc': 'Acara Brawl Stars × Duolingo Supercell (diumumkan 19 September 2026) memberi kulit Trash Goblin Darryl, permata, Starr Drop dan banyak lagi hingga 30 September.',
  'lead': 'Supercell mengumumkan kolaborasi Brawl Stars × Duolingo pada 19 September 2026; ia berlangsung hingga 30 September.',
  'new': ['Dua fasa sasaran komuniti dan tugasan dalam permainan, ditambah mod baharu Duo Boss Fight.',
          'Ganjaran: kulit Trash Goblin Darryl, 20 Permata, 5 Chaos Drop, 3 Mythic Starr Drop, 2,000 Syiling, 2,500 Bling dan 1,000 Kredit.',
          'Quest Brawl Stars dalam aplikasi Duolingo memberi kosmetik tambahan.',
          'Supercell turut mengadakan kuiz di media sosial dengan hadiah 3.141592 juta permata.'],
  'impact': 'Kulit daripada kolaborasi sekali sahaja menyerlahkan sesetengah koleksi Brawl Stars; kulit yang diperoleh ramai secara percuma menyumbang kurang berbanding kulit berbayar yang jarang ditemui.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN kembali: Ekor Sembilan dan bundle Hinata (16 September – 15 Oktober)',
  'desc': 'Kolaborasi Garena dengan NARUTO SHIPPUDEN berlangsung 16 September – 15 Oktober 2026 dengan kemahiran Sharingan: Control, bundle pilihan Jiraiya atau Hinata dan kosmetik bertema.',
  'lead': 'Garena mengumumkan pada 15 September 2026 bahawa kolaborasi Free Fire × NARUTO SHIPPUDEN kembali dari 16 September hingga 15 Oktober.',
  'new': ['Kemahiran baharu: Sharingan: Control untuk mengawal Ekor Sembilan, dan 8 Trigrams Palm Rotation.',
          'Akademi Ninja yang diperluas dalam peta Kampung Daun Tersembunyi.',
          'Hadiah utama pilihan: bundle Jiraiya atau bundle Hinata (kemunculan pertama Hinata).',
          'Kosmetik: Jubah Tsunade, Cat Muka Tatu Gaara, Topeng ANBU Kakashi dan peti Froggy Wallet.'],
  'impact': 'Bundle daripada kolaborasi berlesen yang hanya tersedia untuk masa terhad termasuk dalam item jarang yang dicari kalkulator Free Fire kami.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship Musim 8 bermula, menuju M8 di Istanbul',
  'desc': 'MTC Musim 8 berlangsung 12 September – 18 Oktober 2026 dengan lapan pasukan dan hadiah US$40,000, menjelang Kejohanan Dunia M8 di Istanbul pada Januari 2027.',
  'lead': 'MOONTON Games mengumumkan pada 10 September 2026 bahawa MLBB Türkiye Championship Musim 8 bermula 12 September.',
  'new': ['Musim biasa 12 September – 18 Oktober; perlawanan akhir besar pada 7 November 2026.',
          'Lapan pasukan bertanding, termasuk Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok dan Dark Passage.',
          'Enam pasukan teratas mara ke playoff untuk merebut hadiah US$40,000.',
          'Kejohanan Dunia M8 akan diadakan di Istanbul pada Januari 2027 — acara M Series pertama di Eropah.'],
  'impact': 'Keputusan e-sukan tidak mengubah nilai akaun sedia ada; skin Collector dan Legend serta bilangan hero kekal sebagai pemacu utama dalam penyelidikan kami.'},
 'coc-blast': {'title': 'Acara pingat Equipment Blast Clash of Clans (9–22 September)',
  'desc': 'Acara Equipment Blast berlangsung 9–22 September 2026: kumpul Tag Ticket dan Champ Medal untuk ditukar di Trader dengan peralatan wira, bijih dan kosmetik. Town Hall 6 ke atas.',
  'lead': 'Supercell mengumumkan acara pingat Equipment Blast pada 9 September 2026; ia berlangsung hingga 22 September jam 08:00 UTC, dengan Trader dibuka hingga 24 September.',
  'new': ['Pertempuran berbilang pemain memberi Tag Ticket; laluan acara memberi Champ Medal, tentera sementara dan peti.',
          'Trader menjual peralatan wira, bijih dan kosmetik dengan pingat acara.',
          'Tentera sementara: Undertaker Yeti, K.A.N.E., Yeeter dan Giant Giant.',
          'Tersedia mulai Town Hall 6.'],
  'impact': 'Peralatan wira dan tahapnya menyumbang kepada kekuatan wira, yang dalam penyelidikan kami memacu nilai akaun Clash of Clans; pingat acara ialah satu lagi cara untuk menaik tarafnya.'},
 'mc-wild': {'title': 'Kemas kini Minecraft Wilderness Bound: hutan bertompok, katil jerami dan kem terbiar',
  'desc': 'Kemas kini Wilderness Bound Mojang tiba pada 15 September 2026 dengan biom hutan bertompok, kayu poplar, katil jerami, kem terbiar dan kusyen.',
  'lead': 'Mojang Studios menamakan kemas kini ketiga 2026 sebagai "Wilderness Bound" pada 5 September dan melancarkannya pada 15 September.',
  'new': ['Biom baharu, hutan bertompok, dengan pokok poplar tinggi dan cendawan rak.',
          'Katil jerami daripada tiga bandela rumput kering membolehkan malam dilangkau tanpa menukar titik kemunculan semula.',
          'Kem terbiar untuk diterokai dan kusyen daripada tiga papak bulu biri-biri yang sama warna.',
          'Kayu poplar serta set konkrit dan bulu biri-biri yang diperluas untuk membina.'],
  'impact': 'Akaun Minecraft dinilai mengikut jenis, nama pengguna dan jubah, bukan kandungan permainan, jadi kemas kini tidak mengubah nilai akaun.'},
 'ff-award': {'title': 'Free Fire menang "Best Use of IP or Licence" di Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena memaklumkan pada 3 September 2026 bahawa Free Fire memenangi Best Use of IP or Licence di Pocket Gamer Mobile Games Awards 2026 atas kolaborasi NARUTO SHIPPUDEN.',
  'lead': 'Garena mengumumkan pada 3 September 2026 bahawa Free Fire memenangi "Best Use of IP or Licence" di Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Anugerah ini mengiktiraf kolaborasi NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Menurut Garena, acara Ninja Clash All Stars di Bangkok menarik hampir 5,000 pengunjung dan lebih 247 juta tontonan video.',
          'Kolaborasi ini termasuk watak bertema, kebolehan jutsu dan peta Kampung Daun Tersembunyi yang diubah.',
          'Acara komuniti diadakan di Peru, Bangladesh, Malaysia dan Taiwan.'],
  'impact': 'Anugerah tidak mengubah nilai akaun. Namun ia mengesahkan bahawa kolaborasi berlesen ialah perkara biasa dalam Free Fire — dan bundle terhadnya antara item jarang yang dilihat dalam penilaian.'},
 'rbx-fall': {'title': 'Pratonton permainan musim luruh Roblox: 10 pengalaman pada September dan Oktober',
  'desc': 'Pratonton permainan musim luruh Roblox (2 September 2026) menyenaraikan 10 pengalaman baharu, daripada Showdown dan Nemesis pada September hingga Prime Heroes, Octane dan Starforged pada Oktober.',
  'lead': 'Roblox menerbitkan pratonton permainan musim luruh pada 2 September 2026, dengan sepuluh pengalaman dijadualkan pada September dan Oktober.',
  'new': ['September: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force dan Caramel.',
          'Oktober: Prime Heroes (akses awal pada September dengan 6 wira), Octane, Starforged dan Scrapbook Saga.',
          'Beberapa tajuk lahir daripada program pencipta Jumpstart dan Incubator Roblox.',
          'Genrenya daripada penembak dan perlumbaan hingga seram survival dan pertanian.'],
  'impact': 'Pengalaman baharu tidak mengubah akaun sedia ada. Dalam penyelidikan kami, nilai akaun Roblox datang daripada Robux, item terhad dan item dalam pengalaman yang lama bertahan; permainan baharu hanya penting apabila itemnya mula diperdagangkan.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: kulit wira sekali sahaja yang "tidak akan kembali" selepas 1 Oktober',
  'desc': 'Acara WWE: Search for Cena Supercell (September 2026) menjual enam kulit wira WWE yang menurut Supercell tidak akan kembali selepas 1 Oktober, serta pemandangan Money in the Bank.',
  'lead': 'Supercell mengumumkan acara WWE: Search for Cena Clash of Clans pada 1 September 2026; ia berlangsung sepanjang September.',
  'new': ['Kulit wira berharga $9.99 setiap satu: Cody Rhodes (Barbarian King), Alexa Bliss (Archer Queen), Iyo Sky (Royal Champion), Kane (Dragon Duke) dan American Badass Undertaker (Grand Warden).',
          'Jey Uso (Minion Prince) disertakan dengan Gold Pass.',
          'Supercell menyatakan kulit ini "tidak akan kembali. Selama-lamanya" selepas 1 Oktober.',
          'Pemandangan XL Money in the Bank tersedia dari 2 hingga 30 September, bersama cabaran John Cena dan tentera WWE sementara.'],
  'impact': 'Kulit yang dikatakan penerbit tidak akan kembali ialah jenis kosmetik yang menjadikan akaun Clash of Clans lebih jarang ditemui. Namun sebahagian besar nilai masih datang daripada tahap Town Hall dan wira.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: tinjauan awal format baharu dua split',
  'desc': 'Tinjauan awal Supercell tentang BSC 2027 (24 Ogos 2026): lapan pasukan setiap rantau di empat rantau, Challengers di 12 rantau, dua split 12 minggu, Brawl Cup dan Final Dunia.',
  'lead': 'Supercell memberi tinjauan awal tentang Brawl Stars Championship 2027 pada 24 Ogos 2026, sambil menyatakan butirannya masih boleh berubah.',
  'new': ['Peringkat teratas: 8 pasukan setiap rantau di Asia Timur, EMEA, Amerika Selatan dan Amerika Utara.',
          'Challengers: laluan masuk di 12 rantau.',
          'Dua split selama 12 minggu setiap satu; Split 1 berakhir dengan Brawl Cup, LAN antarabangsa tiga hari, dan Split 2 dengan Final Dunia.',
          'Tarikh, hadiah dan lokasi belum diumumkan.'],
  'impact': 'Format e-sukan tidak mengubah nilai akaun sedia ada; kalkulator Brawl Stars kami masih menggunakan bilangan brawler, Hypercharge dan trofi.'},
}},
'uz': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II chiqdi: Sift olami va Illagerlar Oliy kengashi',
  'desc': 'Mojang Minecraft Dungeons II’ni 2026-yil 29-sentabrda Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch va Switch 2’da chiqardi; 4 o‘yinchigacha birgalikda o‘ynash mumkin.',
  'lead': 'Mojang Studios Minecraft Dungeons II’ni 2026-yil 29-sentabrda chiqardi.',
  'new': ['Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch va Nintendo Switch 2’da mavjud.',
          'Syujetda o‘yinchilar Illagerlar Oliy kengashiga qarshi kurashadi: Prime Enchanter, Supreme Evoker va Grand Illusioner.',
          'O‘yinchilar yangi olam — Sift’ni o‘rganadi; Mojang’ga ko‘ra, u kelasi yili Minecraft Java va Bedrock’ga ham qo‘shiladi.',
          'Yolg‘iz yoki onlayn yoxud bitta ekranda 4 kishigacha birgalikda o‘ynash mumkin.'],
  'impact': 'Dungeons II — alohida o‘yin. Minecraft Java va Bedrock akkauntlari hamon turi, foydalanuvchi nomi va plashlariga qarab baholanadi, shuning uchun bu chiqish ularning qiymatini o‘zgartirmaydi.'},
 'cr-mt-oct': {'title': 'Clash Royale Merge Tactics: Super, eliksir va nishonlardagi oktabr o‘zgarishlari',
  'desc': '2026-yil 1-oktabrdan Merge Tactics 11-mavsumida Super’lar umumiy havzaga o‘tadi, har raunddagi eliksir 5 dan 4 ga kamayadi va 5-darajali skinlar qo‘shiladi; nishon qoidalari 12-mavsumda o‘zgaradi.',
  'lead': 'Supercell Merge Tactics 11-mavsumining oktabr o‘zgarishlarini 2026-yil 30-sentabrda eʼlon qildi; ular 1-oktabrdan kuchga kiradi.',
  'new': ['Super’lar endi boshlang‘ich qo‘shin emas: ular barcha o‘yinchilar talashadigan umumiy havzaga tushadi.',
          'Har raundda olinadigan eliksir 5 dan yana 4 ga qaytadi.',
          'Battle Machine va Dagger Duchess’ni allaqachon yaxshilagan o‘yinchilar uchun 5-darajali skinlar.',
          '12-mavsumdan kumush nishon uchun Olmos ligasiga chiqish, oltin nishon uchun esa eng yaxshi 10 000 talikka kirish kerak.'],
  'impact': '12-mavsumdan yuqori o‘rin nishonlarini olish qiyinlashadi, shuning uchun ular Clash Royale profilida mahoratni aniqroq ko‘rsatadi. Asosiy qiymat omillari Qirol minorasi va karta darajalari bo‘lib qolmoqda.'},
 'ml-mplph': {'title': 'MPL Filippin 18-mavsum pley-offi: PhilSports Arena, 21–25-oktabr',
  'desc': 'MOONTON 2026-yil 26-sentabrda MPL Filippin 18-mavsum pley-offi 21–25-oktabr kunlari PhilSports Arena’da o‘tishini va M8 uchun Filippin jamoalarini aniqlashini eʼlon qildi.',
  'lead': 'MOONTON Games 2026-yil 26-sentabrda MPL Filippin 18-mavsum pley-offining joyi va sanalarini eʼlon qildi.',
  'new': ['Pley-off 2026-yil 21–25-oktabr kunlari Pasig shahridagi PhilSports Arena’da bo‘ladi.',
          'U 2027-yil yanvarida Istanbulda o‘tadigan M8 jahon chempionatida Filippinni kimlar vakil qilishini aniqlaydi.',
          'Chiptalar savdosi 26-sentabrda 200 Filippin pesosidan boshlangan narxlarda ochildi.',
          'Eʼlon o‘yinning 10 yilligiga bag‘ishlangan: 1,5 milliard o‘rnatish va oyiga 110 million faol o‘yinchi.'],
  'impact': 'Kibersport tadbirlari mavjud akkauntlar qiymatini o‘zgartirmaydi. Tadqiqotimizga ko‘ra, Mobile Legends akkaunti qiymatini skinlar, qahramonlar va rivojlanish belgilaydi.'},
 'cr-bal-sep': {'title': 'Clash Royale sentabr balansi: Ice Wizard qahramoni va Minion Giant kuchsizlantirildi',
  'desc': 'Supercell’ning 2026-yil sentabr balans qaydlari Ice Wizard qahramonining muzlatishini 7 dan 5 soniyaga, Minion Giant zararini 189 dan 168 ga tushiradi va Mega Minion hamda Wizard qahramonlarini qayta ishlaydi.',
  'lead': 'Supercell Clash Royale’ning ikki bosqich balans o‘zgarishini eʼlon qildi; ular 2026-yil 8 va 16-sentabrda kuchga kirdi.',
  'new': ['16-sentabr: Ice Wizard qahramoni muzlatishi 7 s → 5 s; Goblinstein qobiliyati 4 s → 3,5 s; Minion Giant zarari 189 → 168; Fire Spirit zarari 207 → 215.',
          '8-sentabr: Freeze 4 s → 3,5 s; Fireball’ning minoraga zarari 172 → 159; Ice Golem sog‘ligi 1 315 → 1 228.',
          'Qayta ishlash: Mega Minion qahramoni (teleport bilan qaytadi, zarar 399 → 422) va Wizard qahramoni (qobiliyat 5 s → 3,5 s); Wizard zarari 281 → 304.',
          'Kuchaytirilganlar orasida Ronin, Spirit Empress va Goblin Cage bor.'],
  'impact': 'Balans o‘zgarishlari qaysi kartalar ommabopligini o‘zgartiradi, akkauntdagi narsalarni emas. Tadqiqotimizga ko‘ra, Clash Royale qiymati Qirol minorasi darajasi, karta darajalari, evolyutsiyalar va noyob bezaklarga bog‘liq.'},
 'gi-wish71': {'title': 'Genshin Impact 7.1 tadbir tilaklari: Vesna va Vodyanitsa bannerlari 13-oktabrgacha',
  'desc': 'HoYoverse’ning 7.1 versiyasi I bosqich tadbir tilaklari 2026-yil 13-oktabrgacha Vesna va Vodyanitsa ehtimolini oshiradi; ehtimoli oshirilgan 4 yulduzlilar — Diona, Faruzan va Chongyun.',
  'lead': 'HoYoverse 7.1 versiyasi I bosqich tadbir tilaklarini 2026-yil 21-sentabrda eʼlon qildi; ular 2026-yil 13-oktabr soat 17:59 gacha davom etadi.',
  'new': ['"When Warm Winds Cavort" Vesna (Anemo) tushish ehtimolini oshiradi.',
          '"Surging Ballad" Vodyanitsa (Hydro) tushish ehtimolini oshiradi.',
          'Ehtimoli oshirilgan 4 yulduzli qahramonlar: Diona (Cryo), Faruzan (Anemo) va Chongyun (Cryo).',
          'Tadbirga xos qahramonlar standart tilakda yo‘q; ikki qahramon banneri bitta kafolat hisoblagichini bo‘lishadi.'],
  'impact': 'Tadqiqotimizga ko‘ra, faqat cheklangan bannerlardan olinadigan qahramonlar va ularning yulduz turkumlari Genshin akkaunti qiymatining asosiy omillaridan.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Trash Goblin Darryl skini va 30-sentabrgacha sovg‘alar',
  'desc': 'Supercell’ning Brawl Stars × Duolingo tadbiri (2026-yil 19-sentabrda eʼlon qilingan) 30-sentabrgacha Trash Goblin Darryl skini, toshlar, Starr Drop’lar va boshqalarni berdi.',
  'lead': 'Supercell Brawl Stars × Duolingo hamkorligini 2026-yil 19-sentabrda eʼlon qildi; u 30-sentabrgacha davom etdi.',
  'new': ['Hamjamiyat maqsadlari va o‘yin ichidagi vazifalardan iborat ikki bosqich, shuningdek yangi Duo Boss Fight rejimi.',
          'Sovg‘alar: Trash Goblin Darryl skini, 20 tosh, 5 Chaos Drop, 3 Mythic Starr Drop, 2 000 tanga, 2 500 Bling va 1 000 kredit.',
          'Duolingo ilovasidagi Brawl Stars topshirig‘i qo‘shimcha bezaklar berdi.',
          'Supercell ijtimoiy tarmoqlarda 3,141592 million tosh sovrinli viktorina ham o‘tkazdi.'],
  'impact': 'Bir martalik hamkorlik skinlari ayrim Brawl Stars kolleksiyalarini ajratib turadi; ko‘pchilik bepul olgan skin noyob pullik skinchalik qiymat qo‘shmaydi.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN qaytdi: To‘qqiz dumli va Hinata to‘plami (16-sentabr – 15-oktabr)',
  'desc': 'Garena’ning NARUTO SHIPPUDEN bilan hamkorligi 2026-yil 16-sentabrdan 15-oktabrgacha Sharingan: Control mahorati, Jiraiya yoki Hinata tanlanadigan to‘plami va mavzuli bezaklar bilan davom etadi.',
  'lead': 'Garena 2026-yil 15-sentabrda Free Fire × NARUTO SHIPPUDEN hamkorligi 16-sentabrdan 15-oktabrgacha qaytishini eʼlon qildi.',
  'new': ['Yangi mahoratlar: To‘qqiz dumlini boshqaradigan Sharingan: Control va 8 Trigrams Palm Rotation.',
          'Yashirin Barg qishlog‘i xaritasida kengaytirilgan Ninja akademiyasi.',
          'Tanlanadigan bosh sovrin: Jiraiya to‘plami yoki Hinata to‘plami (Hinata’ning ilk chiqishi).',
          'Bezaklar: Tsunade’ning plashi, Gaara’ning tatuirovka yuz bo‘yog‘i, Kakashi’ning ANBU niqobi va Froggy Wallet sandig‘i.'],
  'impact': 'Faqat cheklangan vaqt beriladigan litsenziyali hamkorlik to‘plamlari Free Fire kalkulyatorimiz izlaydigan noyob buyumlar qatoriga kiradi.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship 8-mavsumi boshlandi: Istanbuldagi M8 sari',
  'desc': 'MTC 8-mavsumi 2026-yil 12-sentabrdan 18-oktabrgacha sakkiz jamoa va 40 000 dollarlik sovrin jamg‘armasi bilan o‘tadi; undan so‘ng 2027-yil yanvarida Istanbulda M8 jahon chempionati.',
  'lead': 'MOONTON Games 2026-yil 10-sentabrda MLBB Türkiye Championship 8-mavsumi 12-sentabrda boshlanishini eʼlon qildi.',
  'new': ['Muntazam mavsum 12-sentabrdan 18-oktabrgacha; katta final 2026-yil 7-noyabrda.',
          'Sakkiz jamoa ishtirok etadi, jumladan Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok va Dark Passage.',
          'Eng yaxshi oltita jamoa pley-offga chiqib, 40 000 dollar uchun kurashadi.',
          'M8 jahon chempionati 2027-yil yanvarida Istanbulda o‘tadi — bu M seriyasining Yevropadagi birinchi tadbiri.'],
  'impact': 'Kibersport natijalari mavjud akkauntlar qiymatini o‘zgartirmaydi; tadqiqotimizga ko‘ra, Collector va Legend skinlari hamda qahramonlar soni asosiy omil bo‘lib qolmoqda.'},
 'coc-blast': {'title': 'Clash of Clans Equipment Blast medal tadbiri (9–22-sentabr)',
  'desc': 'Equipment Blast tadbiri 2026-yil 9–22-sentabr kunlari o‘tdi: Tag Tickets va Champ Medals yig‘ib, Savdogarda qahramon jihozlari, ruda va bezaklarga almashtirish mumkin edi. Town Hall 6 va undan yuqori.',
  'lead': 'Supercell Equipment Blast medal tadbirini 2026-yil 9-sentabrda eʼlon qildi; u 22-sentabr soat 08:00 UTC gacha davom etdi, Savdogar esa 24-sentabrgacha ochiq bo‘ldi.',
  'new': ['Ko‘p o‘yinchili janglar Tag Tickets berdi; tadbir yo‘li Champ Medals, vaqtinchalik qo‘shinlar va sandiqlar berdi.',
          'Savdogar tadbir medallari evaziga qahramon jihozlari, ruda va bezaklarni sotdi.',
          'Vaqtinchalik qo‘shinlar: Undertaker Yeti, K.A.N.E., Yeeter va Giant Giant.',
          'Town Hall 6 dan mavjud edi.'],
  'impact': 'Qahramon jihozlari va ularning darajalari qahramonlar kuchining bir qismi bo‘lib, tadqiqotimizga ko‘ra u Clash of Clans akkaunti qiymatini belgilaydi; tadbir medallari uni yaxshilashning yana bir yo‘li.'},
 'mc-wild': {'title': 'Minecraft Wilderness Bound yangilanishi: xoldor o‘rmon, somon karavotlar va tashlab ketilgan lagerlar',
  'desc': 'Mojang’ning Wilderness Bound yangilanishi 2026-yil 15-sentabrda xoldor o‘rmon biomi, terak yog‘ochi, somon karavotlar, tashlab ketilgan lagerlar va yostiqchalar bilan chiqdi.',
  'lead': 'Mojang Studios 2026-yilning uchinchi o‘yin yangilanishini 5-sentabrda "Wilderness Bound" deb nomladi va 15-sentabrda chiqardi.',
  'new': ['Yangi biom — baland teraklar va tokcha qo‘ziqorinlari bor xoldor o‘rmon.',
          'Uchta pichan bog‘lamidan yasaladigan somon karavot qayta tug‘ilish nuqtasini o‘zgartirmasdan tunni o‘tkazib yuborish imkonini beradi.',
          'O‘rganish uchun tashlab ketilgan lagerlar va bir xil rangdagi uchta jun plitadan yasaladigan yostiqchalar.',
          'Terak yog‘ochi hamda qurilish uchun kengaytirilgan beton va jun to‘plamlari.'],
  'impact': 'Minecraft akkauntlari o‘yin kontentiga ko‘ra emas, turi, foydalanuvchi nomi va plashlariga ko‘ra baholanadi, shuning uchun yangilanish akkaunt qiymatini o‘zgartirmaydi.'},
 'ff-award': {'title': 'Free Fire Pocket Gamer Mobile Games Awards 2026’da "Best Use of IP or Licence" mukofotini oldi',
  'desc': 'Garena 2026-yil 3-sentabrda Free Fire NARUTO SHIPPUDEN hamkorligi uchun Pocket Gamer Mobile Games Awards 2026’da Best Use of IP or Licence mukofotini olganini xabar qildi.',
  'lead': 'Garena 2026-yil 3-sentabrda Free Fire Pocket Gamer Mobile Games Awards 2026’da "Best Use of IP or Licence" mukofotini qo‘lga kiritganini eʼlon qildi.',
  'new': ['Mukofot NARUTO SHIPPUDEN Chapter 2: Ninja War hamkorligini taqdirlaydi.',
          'Garena’ga ko‘ra, Bangkokdagi Ninja Clash All Stars tadbiriga qariyb 5 000 kishi keldi va videolar 247 milliondan ortiq ko‘rildi.',
          'Hamkorlik mavzuli qahramonlar, jutsu qobiliyatlari va o‘zgartirilgan Yashirin Barg qishlog‘i xaritasini o‘z ichiga oldi.',
          'Peru, Bangladesh, Malayziya va Tayvanda hamjamiyat tadbirlari o‘tkazildi.'],
  'impact': 'Mukofot akkaunt qiymatini o‘zgartirmaydi. Biroq u litsenziyali hamkorliklar Free Fire’ning doimiy qismi ekanini tasdiqlaydi — ularning cheklangan to‘plamlari esa baholashda eʼtibor beriladigan noyob buyumlar qatorida.'},
 'rbx-fall': {'title': 'Roblox kuzgi o‘yinlar sharhi: sentabr va oktabrda chiqadigan 10 ta tajriba',
  'desc': 'Roblox’ning kuzgi o‘yinlar sharhi (2026-yil 2-sentabr) sentabrdagi Showdown va Nemesis’dan oktabrdagi Prime Heroes, Octane va Starforged’gacha 10 ta yangi tajribani sanab o‘tadi.',
  'lead': 'Roblox 2026-yil 2-sentabrda sentabr va oktabrda chiqadigan o‘nta tajribani o‘z ichiga olgan kuzgi o‘yinlar sharhini eʼlon qildi.',
  'new': ['Sentabr: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force va Caramel.',
          'Oktabr: Prime Heroes (sentabrda 6 ta qahramon bilan erta kirish), Octane, Starforged va Scrapbook Saga.',
          'Bir nechta o‘yin Roblox’ning Jumpstart va Incubator ijodkorlar dasturlaridan chiqqan.',
          'Janrlar otishma va poygalardan tortib omon qolish qo‘rqinchli o‘yinlari va fermachilikkacha.'],
  'impact': 'Yangi tajribalar mavjud akkauntlarni o‘zgartirmaydi. Tadqiqotimizga ko‘ra, Roblox akkaunti qiymati Robux, cheklangan buyumlar va uzoq yashaydigan tajribalardagi buyumlardan iborat; yangi o‘yin faqat uning buyumlari savdoga chiqqanda ahamiyat kasb etadi.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: 1-oktabrdan keyin "qaytmaydigan" bir martalik qahramon skinlari',
  'desc': 'Supercell’ning WWE: Search for Cena tadbiri (2026-yil sentabr) Supercell’ga ko‘ra 1-oktabrdan keyin qaytmaydigan oltita WWE qahramon skini va Money in the Bank manzarasini sotdi.',
  'lead': 'Supercell Clash of Clans uchun WWE: Search for Cena tadbirini 2026-yil 1-sentabrda eʼlon qildi; u butun sentabr davom etdi.',
  'new': ['Har biri 9,99 dollarlik qahramon skinlari: Cody Rhodes (Barbar qirol), Alexa Bliss (Kamonchi malika), Iyo Sky (Qirollik chempioni), Kane (Ajdar gersogi) va American Badass Undertaker (Buyuk qo‘riqchi).',
          'Jey Uso (Minion shahzoda) Gold Pass bilan berildi.',
          'Supercell bu skinlar 1-oktabrdan keyin "qaytmaydi. Hech qachon" deydi.',
          'Money in the Bank XL manzarasi 2–30-sentabr kunlari sotildi; shu paytda John Cena sinovi va vaqtinchalik WWE qo‘shinlari ham bor edi.'],
  'impact': 'Noshir hech qachon qaytmaydi degan skinlar aynan Clash of Clans akkauntini noyobroq qiladigan bezaklar turidir. Shunga qaramay, qiymatning katta qismi Town Hall va qahramonlar darajasiga to‘g‘ri keladi.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: ikki bosqichli yangi formatga ilk nazar',
  'desc': 'Supercell’ning BSC 2027’ga ilk nazari (2026-yil 24-avgust): to‘rt mintaqada har mintaqaga sakkiz jamoa, 12 mintaqada Challengers, 12 haftalik ikki bosqich, Brawl Cup va Jahon finali.',
  'lead': 'Supercell 2026-yil 24-avgustda 2027 Brawl Stars Championship’ga ilk nazarni taqdim etdi va tafsilotlar o‘zgarishi mumkinligini aytdi.',
  'new': ['Eng yuqori daraja: Sharqiy Osiyo, EMEA, Janubiy Amerika va Shimoliy Amerikada har mintaqaga 8 jamoa.',
          'Challengers: 12 mintaqada professionallikka kirish yo‘li.',
          'Har biri 12 haftalik ikki bosqich; 1-bosqich uch kunlik xalqaro LAN turniri Brawl Cup bilan, 2-bosqich Jahon finali bilan yakunlanadi.',
          'Sanalar, sovrin jamg‘armasi va o‘tkazish joylari hali eʼlon qilinmagan.'],
  'impact': 'Kibersport formatlari mavjud akkauntlar qiymatini o‘zgartirmaydi; Brawl Stars kalkulyatorimiz hamon brawlerlar soni, Hypercharge’lar va kuboklardan foydalanadi.'},
}},
}
