# News batch 2: kk, tk (from news_text_b2_en.py, facts unchanged)
TEXT = {
'kk': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II шықты: Sift өлшемі және Иллагерлердің Жоғарғы кеңесі',
  'desc': 'Mojang Minecraft Dungeons II-ні 2026 жылғы 29 қыркүйекте Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch және Switch 2-де шығарды; 4 ойыншыға дейін бірге ойнауға болады.',
  'lead': 'Mojang Studios Minecraft Dungeons II-ні 2026 жылғы 29 қыркүйекте шығарды.',
  'new': ['Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch және Nintendo Switch 2-де қолжетімді.',
          'Сюжетте ойыншылар Иллагерлердің Жоғарғы кеңесіне қарсы шығады: Prime Enchanter, Supreme Evoker және Grand Illusioner.',
          'Ойыншылар жаңа Sift өлшемін зерттейді; Mojang-тың айтуынша, ол келесі жылы Minecraft Java мен Bedrock-қа да келеді.',
          'Жалғыз немесе онлайн не бір экранда 4 адамға дейін бірге ойнауға болады.'],
  'impact': 'Dungeons II — бөлек ойын. Minecraft Java және Bedrock аккаунттары әлі де түрімен, пайдаланушы атымен және плащтарымен бағаланады, сондықтан бұл шығарылым олардың құнын өзгертпейді.'},
 'cr-mt-oct': {'title': 'Clash Royale Merge Tactics: Super, эликсир және белгілердегі қазан өзгерістері',
  'desc': '2026 жылғы 1 қазаннан бастап Merge Tactics 11-маусымында Super-лер ортақ пулға өтеді, әр раундтағы эликсир 5-тен 4-ке азаяды және 5-деңгейлі скиндер қосылады; белгі ережелері 12-маусымда өзгереді.',
  'lead': 'Supercell Merge Tactics 11-маусымының қазан өзгерістерін 2026 жылғы 30 қыркүйекте жариялады; олар 1 қазаннан күшіне енеді.',
  'new': ['Super-лер енді бастапқы әскер болмайды: олар барлық ойыншы таласатын ортақ пулға түседі.',
          'Әр раундта алынатын эликсир 5-тен қайтадан 4-ке түседі.',
          'Battle Machine мен Dagger Duchess-ті жақсартып қойған ойыншыларға 5-деңгейлі скиндер.',
          '12-маусымнан бастап күміс белгі үшін Алмас лигаға жету, алтын белгі үшін үздік 10 000-ға кіру қажет.'],
  'impact': '12-маусымнан бастап жоғары орын белгілерін алу қиындайды, сондықтан олар Clash Royale профилінде шеберлікті айқынырақ көрсетеді. Негізгі құн факторлары — Патша мұнарасы мен карталар деңгейі.'},
 'ml-mplph': {'title': 'MPL Филиппин 18-маусымының плей-оффы: PhilSports Arena, 21–25 қазан',
  'desc': 'MOONTON 2026 жылғы 26 қыркүйекте MPL Филиппин 18-маусымының плей-оффы 21–25 қазанда PhilSports Arena-да өтіп, M8-ге баратын Филиппин командаларын анықтайтынын хабарлады.',
  'lead': 'MOONTON Games MPL Филиппин 18-маусымы плей-оффының өтетін жері мен күндерін 2026 жылғы 26 қыркүйекте жариялады.',
  'new': ['Плей-офф 2026 жылғы 21–25 қазанда Пасиг қаласындағы PhilSports Arena-да өтеді.',
          'Ол 2027 жылғы қаңтарда Стамбұлда өтетін M8 әлем чемпионатында Филиппинді кім білдіретінін анықтайды.',
          'Билет сату 26 қыркүйекте 200 филиппин песосынан басталатын бағамен ашылды.',
          'Хабарландыру ойынның 10 жылдығына арналған: 1,5 млрд орнату және айына 110 млн белсенді ойыншы.'],
  'impact': 'Киберспорт іс-шаралары қазіргі аккаунттардың құнын өзгертпейді. Біздің зерттеуіміз бойынша Mobile Legends аккаунтының құнын скиндер, батырлар және прогресс анықтайды.'},
 'cr-bal-sep': {'title': 'Clash Royale қыркүйек балансы: Ice Wizard батыры мен Minion Giant әлсіретілді',
  'desc': 'Supercell-дің 2026 жылғы қыркүйек баланс жазбалары Ice Wizard батырының мұздатуын 7-ден 5 секундқа, Minion Giant зақымын 189-дан 168-ге түсіреді және Mega Minion мен Wizard батырларын қайта өңдейді.',
  'lead': 'Supercell Clash Royale баланс өзгерістерінің екі кезеңін жариялады; олар 2026 жылғы 8 және 16 қыркүйекте күшіне енді.',
  'new': ['16 қыркүйек: Ice Wizard батырының мұздатуы 7 с → 5 с; Goblinstein қабілеті 4 с → 3,5 с; Minion Giant зақымы 189 → 168; Fire Spirit зақымы 207 → 215.',
          '8 қыркүйек: Freeze 4 с → 3,5 с; Fireball-дың мұнараға зақымы 172 → 159; Ice Golem денсаулығы 1 315 → 1 228.',
          'Қайта өңдеу: Mega Minion батыры (телепортпен оралады, зақым 399 → 422) және Wizard батыры (қабілет 5 с → 3,5 с); Wizard зақымы 281 → 304.',
          'Күшейтілгендер арасында Ronin, Spirit Empress және Goblin Cage бар.'],
  'impact': 'Баланс өзгерістері қай карталар танымал екенін өзгертеді, аккаунттағы нәрселерді емес. Біздің зерттеуіміз бойынша Clash Royale құны Патша мұнарасы деңгейіне, карталар деңгейіне, эволюцияларға және сирек әшекейлерге байланысты.'},
 'gi-wish71': {'title': 'Genshin Impact 7.1 іс-шара тілектері: Vesna мен Vodyanitsa баннерлері 13 қазанға дейін',
  'desc': 'HoYoverse-тің 7.1 нұсқасы I кезеңінің іс-шара тілектері 2026 жылғы 13 қазанға дейін Vesna мен Vodyanitsa ықтималдығын арттырады; ықтималдығы артқан 4 жұлдыздылар — Diona, Faruzan және Chongyun.',
  'lead': 'HoYoverse 7.1 нұсқасы I кезеңінің іс-шара тілектерін 2026 жылғы 21 қыркүйекте жариялады; олар 2026 жылғы 13 қазан, 17:59-ға дейін жалғасады.',
  'new': ['"When Warm Winds Cavort" Vesna-ның (Anemo) түсу ықтималдығын арттырады.',
          '"Surging Ballad" Vodyanitsa-ның (Hydro) түсу ықтималдығын арттырады.',
          'Ықтималдығы артқан 4 жұлдызды кейіпкерлер: Diona (Cryo), Faruzan (Anemo) және Chongyun (Cryo).',
          'Іс-шараға тән кейіпкерлер стандартты тілекте жоқ; екі кейіпкер баннері бір кепілдік санағышын бөліседі.'],
  'impact': 'Біздің зерттеуіміз бойынша тек шектеулі баннерлерден алынатын кейіпкерлер мен олардың шоқжұлдыздары Genshin аккаунты құнының негізгі факторларының бірі.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Trash Goblin Darryl скині және 30 қыркүйекке дейін сыйлықтар',
  'desc': 'Supercell-дің Brawl Stars × Duolingo іс-шарасы (2026 жылғы 19 қыркүйекте жарияланған) 30 қыркүйекке дейін Trash Goblin Darryl скинін, асыл тастарды, Starr Drop-тарды және т.б. берді.',
  'lead': 'Supercell Brawl Stars × Duolingo серіктестігін 2026 жылғы 19 қыркүйекте жариялады; ол 30 қыркүйекке дейін жалғасты.',
  'new': ['Қауымдастық мақсаттары мен ойын ішіндегі тапсырмалардан тұратын екі кезең, сондай-ақ жаңа Duo Boss Fight режимі.',
          'Сыйлықтар: Trash Goblin Darryl скині, 20 асыл тас, 5 Chaos Drop, 3 Mythic Starr Drop, 2 000 тиын, 2 500 Bling және 1 000 кредит.',
          'Duolingo қолданбасындағы Brawl Stars тапсырмасы қосымша әшекейлер берді.',
          'Supercell әлеуметтік желілерде 3,141592 млн асыл тас ұтысы бар викторина да өткізді.'],
  'impact': 'Бір реттік серіктестік скиндері кейбір Brawl Stars коллекцияларын ерекшелендіреді; көпшілік тегін алған скин сирек ақылы скинмен салыстырғанда құнға аз әсер етеді.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN қайта оралды: Тоғыз құйрықты және Хината жиынтығы (16 қыркүйек – 15 қазан)',
  'desc': 'Garena-ның NARUTO SHIPPUDEN-мен серіктестігі 2026 жылғы 16 қыркүйек – 15 қазан аралығында Sharingan: Control дағдысы, Джирайя немесе Хината таңдау жиынтығы және тақырыптық әшекейлермен өтеді.',
  'lead': 'Garena 2026 жылғы 15 қыркүйекте Free Fire × NARUTO SHIPPUDEN серіктестігі 16 қыркүйек – 15 қазан аралығында қайта оралатынын хабарлады.',
  'new': ['Жаңа дағдылар: Тоғыз құйрықтыны басқаратын Sharingan: Control және 8 Trigrams Palm Rotation.',
          'Жасырын Жапырақ ауылы картасында кеңейтілген Ниндзя академиясы.',
          'Таңдалатын бас жүлде: Джирайя жиынтығы немесе Хината жиынтығы (Хинатаның алғашқы шығуы).',
          'Әшекейлер: Цунаденің плащы, Гаараның татуировка бет бояуы, Какашидің АНБУ маскасы және Froggy Wallet жәшігі.'],
  'impact': 'Тек шектеулі уақыт берілетін лицензиялық серіктестік жиынтықтары Free Fire калькуляторымыз іздейтін сирек заттардың қатарында.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship 8-маусымы басталды: Стамбұлдағы M8-ге жол',
  'desc': 'MTC 8-маусымы 2026 жылғы 12 қыркүйек – 18 қазан аралығында сегіз команда және 40 000 доллар жүлде қорымен өтеді; одан кейін 2027 жылғы қаңтарда Стамбұлда M8 әлем чемпионаты.',
  'lead': 'MOONTON Games 2026 жылғы 10 қыркүйекте MLBB Türkiye Championship 8-маусымы 12 қыркүйекте басталатынын хабарлады.',
  'new': ['Тұрақты маусым 12 қыркүйек – 18 қазан; гранд-финал 2026 жылғы 7 қарашада.',
          'Сегіз команда қатысады, олардың ішінде Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok және Dark Passage.',
          'Үздік алты команда плей-оффқа шығып, 40 000 доллар үшін күреседі.',
          'M8 әлем чемпионаты 2027 жылғы қаңтарда Стамбұлда өтеді — бұл M сериясының Еуропадағы алғашқы іс-шарасы.'],
  'impact': 'Киберспорт нәтижелері қазіргі аккаунттардың құнын өзгертпейді; біздің зерттеуіміз бойынша Collector және Legend скиндері мен батырлар саны негізгі фактор болып қала береді.'},
 'coc-blast': {'title': 'Clash of Clans Equipment Blast медаль іс-шарасы (9–22 қыркүйек)',
  'desc': 'Equipment Blast іс-шарасы 2026 жылғы 9–22 қыркүйекте өтті: Tag Tickets пен Champ Medals жинап, Саудагерден батыр жабдықтарын, кен мен әшекейлерді алуға болатын. Town Hall 6 және жоғары.',
  'lead': 'Supercell Equipment Blast медаль іс-шарасын 2026 жылғы 9 қыркүйекте жариялады; ол 22 қыркүйек 08:00 UTC-ке дейін жалғасып, Саудагер 24 қыркүйекке дейін ашық болды.',
  'new': ['Көп ойыншылы шайқастар Tag Tickets берді; іс-шара жолы Champ Medals, уақытша әскерлер мен сандықтар берді.',
          'Саудагер іс-шара медальдарына батыр жабдықтарын, кен мен әшекейлерді сатты.',
          'Уақытша әскерлер: Undertaker Yeti, K.A.N.E., Yeeter және Giant Giant.',
          'Town Hall 6-дан бастап қолжетімді болды.'],
  'impact': 'Батыр жабдықтары мен олардың деңгейлері батырлар күшінің бір бөлігі, ал біздің зерттеуіміз бойынша ол Clash of Clans аккаунтының құнын анықтайды; іс-шара медальдары оны жақсартудың тағы бір жолы.'},
 'mc-wild': {'title': 'Minecraft Wilderness Bound жаңартуы: теңбіл орман, сабан төсектер және тастанды лагерьлер',
  'desc': 'Mojang-тың Wilderness Bound жаңартуы 2026 жылғы 15 қыркүйекте теңбіл орман биомы, терек ағашы, сабан төсектер, тастанды лагерьлер және көпшіктермен шықты.',
  'lead': 'Mojang Studios 2026 жылғы үшінші ойын жаңартуын 5 қыркүйекте "Wilderness Bound" деп атап, 15 қыркүйекте шығарды.',
  'new': ['Жаңа биом — биік теректері мен сөре саңырауқұлақтары бар теңбіл орман.',
          'Үш шөп бумасынан жасалатын сабан төсек қайта пайда болу нүктесін өзгертпей түнді өткізіп жіберуге мүмкіндік береді.',
          'Зерттеуге арналған тастанды лагерьлер және бір түсті үш жүн тақтадан жасалатын көпшіктер.',
          'Терек ағашы және құрылысқа арналған кеңейтілген бетон мен жүн жинақтары.'],
  'impact': 'Minecraft аккаунттары ойын мазмұнымен емес, түрімен, пайдаланушы атымен және плащтарымен бағаланады, сондықтан жаңарту аккаунт құнын өзгертпейді.'},
 'ff-award': {'title': 'Free Fire Pocket Gamer Mobile Games Awards 2026-да "Best Use of IP or Licence" марапатын жеңіп алды',
  'desc': 'Garena 2026 жылғы 3 қыркүйекте Free Fire NARUTO SHIPPUDEN серіктестігі үшін Pocket Gamer Mobile Games Awards 2026-да Best Use of IP or Licence марапатын алғанын хабарлады.',
  'lead': 'Garena 2026 жылғы 3 қыркүйекте Free Fire Pocket Gamer Mobile Games Awards 2026-да "Best Use of IP or Licence" марапатын жеңіп алғанын жариялады.',
  'new': ['Марапат NARUTO SHIPPUDEN Chapter 2: Ninja War серіктестігі үшін берілді.',
          'Garena-ның дерегі бойынша Бангкоктағы Ninja Clash All Stars іс-шарасына 5 000-ға жуық адам келіп, бейнелер 247 миллионнан астам рет қаралған.',
          'Серіктестік тақырыптық кейіпкерлерді, джуцу қабілеттерін және өзгертілген Жасырын Жапырақ ауылы картасын қамтыды.',
          'Перу, Бангладеш, Малайзия және Тайваньда қауымдастық іс-шаралары өтті.'],
  'impact': 'Марапат аккаунттардың құнын өзгертпейді. Бірақ ол лицензиялық серіктестіктер Free Fire-дің тұрақты бөлігі екенін растайды — ал олардың шектеулі жиынтықтары бағалауда назар аударылатын сирек заттар қатарында.'},
 'rbx-fall': {'title': 'Roblox күзгі ойындарына шолу: қыркүйек пен қазанда шығатын 10 тәжірибе',
  'desc': 'Roblox-тың күзгі ойындарына шолуы (2026 жылғы 2 қыркүйек) қыркүйектегі Showdown мен Nemesis-тен қазандағы Prime Heroes, Octane және Starforged-қа дейін 10 жаңа тәжірибені атайды.',
  'lead': 'Roblox 2026 жылғы 2 қыркүйекте қыркүйек пен қазанда шығатын он тәжірибе енген күзгі ойындарына шолуды жариялады.',
  'new': ['Қыркүйек: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force және Caramel.',
          'Қазан: Prime Heroes (қыркүйекте 6 батырмен ерте қолжетімділік), Octane, Starforged және Scrapbook Saga.',
          'Бірнеше ойын Roblox-тың Jumpstart және Incubator авторлар бағдарламаларынан шыққан.',
          'Жанрлар атыс пен жарыстан бастап аман қалу қорқынышты ойындары мен фермаға дейін.'],
  'impact': 'Жаңа тәжірибелер қазіргі аккаунттарды өзгертпейді. Біздің зерттеуіміз бойынша Roblox аккаунтының құны Robux-тан, шектеулі заттардан және ұзақ жұмыс істеп келе жатқан тәжірибелердегі заттардан құралады; жаңа ойын тек оның заттары сатыла бастағанда маңызды болады.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: 1 қазаннан кейін "қайтып келмейтін" бір реттік батыр скиндері',
  'desc': 'Supercell-дің WWE: Search for Cena іс-шарасы (2026 жылғы қыркүйек) Supercell-дің айтуынша 1 қазаннан кейін қайтып келмейтін алты WWE батыр скинін және Money in the Bank көрінісін сатты.',
  'lead': 'Supercell Clash of Clans үшін WWE: Search for Cena іс-шарасын 2026 жылғы 1 қыркүйекте жариялады; ол қыркүйек бойы жалғасты.',
  'new': ['Әрқайсысы 9,99 доллар тұратын батыр скиндері: Cody Rhodes (Варвар патша), Alexa Bliss (Садақшы ханшайым), Iyo Sky (Корольдік чемпион), Kane (Айдаһар герцогі) және American Badass Undertaker (Ұлы күзетші).',
          'Jey Uso (Миньон ханзада) Gold Pass-пен берілді.',
          'Supercell бұл скиндер 1 қазаннан кейін "қайтып келмейді. Ешқашан" дейді.',
          'Money in the Bank XL көрінісі 2–30 қыркүйек аралығында сатылды; сонымен бірге John Cena сынағы мен уақытша WWE әскерлері болды.'],
  'impact': 'Баспагер ешқашан қайтып келмейді деген скиндер дәл Clash of Clans аккаунтын сиректеу ететін әшекей түрі. Дегенмен құнның басым бөлігі әлі де Town Hall мен батырлар деңгейінде.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: екі кезеңді жаңа форматқа алғашқы көзқарас',
  'desc': 'Supercell-дің BSC 2027-ге алғашқы көзқарасы (2026 жылғы 24 тамыз): төрт аймақтың әрқайсысында сегіз команда, 12 аймақта Challengers, 12 апталық екі кезең, Brawl Cup және Әлем финалы.',
  'lead': 'Supercell 2026 жылғы 24 тамызда 2027 Brawl Stars Championship-ке алғашқы көзқарасты ұсынып, мәліметтер өзгеруі мүмкін екенін ескертті.',
  'new': ['Жоғары деңгей: Шығыс Азия, EMEA, Оңтүстік Америка және Солтүстік Америкада әр аймаққа 8 команда.',
          'Challengers: 12 аймақта кәсіби деңгейге кіру жолы.',
          'Әрқайсысы 12 апталық екі кезең; 1-кезең үш күндік халықаралық LAN турнирі Brawl Cup-пен, 2-кезең Әлем финалымен аяқталады.',
          'Күндері, жүлде қоры және өтетін орындары әлі жарияланған жоқ.'],
  'impact': 'Киберспорт форматтары қазіргі аккаунттардың құнын өзгертпейді; Brawl Stars калькуляторымыз бұрынғыша бойшылар санын, Hypercharge-терді және кубоктарды пайдаланады.'},
}},
'tk': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II çykdy: Sift ölçegi we Illagerleriň Ýokary geňeşi',
  'desc': 'Mojang Minecraft Dungeons II-ni 2026-njy ýylyň 29-njy sentýabrynda Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch we Switch 2 üçin çykardy; 4 oýunça çenli bilelikde oýnap bolýar.',
  'lead': 'Mojang Studios Minecraft Dungeons II-ni 2026-njy ýylyň 29-njy sentýabrynda çykardy.',
  'new': ['Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch we Nintendo Switch 2-de elýeterli.',
          'Wakalarda oýunçylar Illagerleriň Ýokary geňeşine garşy göreşýär: Prime Enchanter, Supreme Evoker we Grand Illusioner.',
          'Oýunçylar täze Sift ölçegini öwrenýär; Mojang-yň aýtmagyna görä, ol indiki ýyl Minecraft Java we Bedrock-a hem geler.',
          'Ýeke özüň ýa-da onlaýn ýa-da bir ekranda 4 adama çenli bilelikde oýnap bolýar.'],
  'impact': 'Dungeons II aýratyn oýun. Minecraft Java we Bedrock hasaplary henizem görnüşine, ulanyjy adyna we plaşlaryna görä bahalandyrylýar, şonuň üçin bu çykyş olaryň gymmatyny üýtgetmeýär.'},
 'cr-mt-oct': {'title': 'Clash Royale Merge Tactics: Super-ler, eliksir we nyşanlar boýunça oktýabr üýtgeşmeleri',
  'desc': '2026-njy ýylyň 1-nji oktýabryndan Merge Tactics 11-nji möwsüminde Super-ler umumy howza geçýär, her tapgyrdaky eliksir 5-den 4-e azalýar we 5-nji derejeli skinler goşulýar; nyşan düzgünleri 12-nji möwsümde üýtgeýär.',
  'lead': 'Supercell Merge Tactics 11-nji möwsüminiň oktýabr üýtgeşmelerini 2026-njy ýylyň 30-njy sentýabrynda yglan etdi; olar 1-nji oktýabrdan güýje girýär.',
  'new': ['Super-ler indi başlangyç goşun däl: olar ähli oýunçylaryň talaşýan umumy howzuna düşýär.',
          'Her tapgyrda alynýan eliksir 5-den ýene 4-e gaýdýar.',
          'Battle Machine we Dagger Duchess-i eýýäm gowulandyran oýunçylar üçin 5-nji derejeli skinler.',
          '12-nji möwsümden kümüş nyşan üçin Almaz ligasyna ýetmek, altyn nyşan üçin iň gowy 10 000-e girmek gerek.'],
  'impact': '12-nji möwsümden ýokary orun nyşanlaryny almak kynlaşýar, şonuň üçin olar Clash Royale profilinde ussatlygy has aýdyň görkezer. Esasy gymmat faktorlary Patyşa diňi we kart derejeleri bolmagynda galýar.'},
 'ml-mplph': {'title': 'MPL Filippinler 18-nji möwsüm pleý-offy: PhilSports Arena, 21–25-nji oktýabr',
  'desc': 'MOONTON 2026-njy ýylyň 26-njy sentýabrynda MPL Filippinler 18-nji möwsüm pleý-offynyň 21–25-nji oktýabrda PhilSports Arena-da geçjekdigini we M8 üçin Filippin toparlaryny kesgitlejekdigini yglan etdi.',
  'lead': 'MOONTON Games MPL Filippinler 18-nji möwsüm pleý-offynyň geçiriljek ýerini we senelerini 2026-njy ýylyň 26-njy sentýabrynda yglan etdi.',
  'new': ['Pleý-off 2026-njy ýylyň 21–25-nji oktýabrynda Pasig şäherindäki PhilSports Arena-da geçýär.',
          'Ol 2027-nji ýylyň ýanwarynda Stambulda geçjek M8 dünýä çempionatynda Filippinlere kimleriň wekilçilik etjekdigini kesgitleýär.',
          'Bilet satuwy 26-njy sentýabrda 200 filippin pesosyndan başlaýan bahalar bilen açyldy.',
          'Bildiriş oýnuň 10 ýyllygyna bagyşlanýar: 1,5 milliard gurnama we aýda 110 million işjeň oýunçy.'],
  'impact': 'Kibersport çäreleri bar bolan hasaplaryň gymmatyny üýtgetmeýär. Biziň gözlegimize görä, Mobile Legends hasabynyň gymmatyny skinler, gahrymanlar we ösüş kesgitleýär.'},
 'cr-bal-sep': {'title': 'Clash Royale sentýabr deňagramlylygy: Ice Wizard gahrymany we Minion Giant gowşadyldy',
  'desc': 'Supercell-iň 2026-njy ýylyň sentýabr deňagramlylyk bellikleri Ice Wizard gahrymanynyň doňdurmasyny 7-den 5 sekunda, Minion Giant-yň zyýanyny 189-dan 168-e düşürýär we Mega Minion hem-de Wizard gahrymanlaryny täzeden işleýär.',
  'lead': 'Supercell Clash Royale deňagramlylyk üýtgeşmeleriniň iki tapgyryny çap etdi; olar 2026-njy ýylyň 8-nji we 16-njy sentýabrynda güýje girdi.',
  'new': ['16-njy sentýabr: Ice Wizard gahrymanynyň doňdurmasy 7 s → 5 s; Goblinstein ukyby 4 s → 3,5 s; Minion Giant zyýany 189 → 168; Fire Spirit zyýany 207 → 215.',
          '8-nji sentýabr: Freeze 4 s → 3,5 s; Fireball-yň diňe zyýany 172 → 159; Ice Golem saglygy 1 315 → 1 228.',
          'Täzeden işlemek: Mega Minion gahrymany (teleport bilen yzyna gaýdýar, zyýan 399 → 422) we Wizard gahrymany (ukyp 5 s → 3,5 s); Wizard zyýany 281 → 304.',
          'Güýçlendirilenleriň arasynda Ronin, Spirit Empress we Goblin Cage bar.'],
  'impact': 'Deňagramlylyk üýtgeşmeleri haýsy kartlaryň meşhurdygyny üýtgedýär, hasapdaky zatlary däl. Biziň gözlegimize görä, Clash Royale-de gymmat Patyşa diňiniň derejesine, kart derejelerine, ewolýusiýalara we seýrek bezeglere bagly.'},
 'gi-wish71': {'title': 'Genshin Impact 7.1 çäre arzuwlary: Vesna we Vodyanitsa bannerleri 13-nji oktýabra çenli',
  'desc': 'HoYoverse-iň 7.1 wersiýasynyň I tapgyr çäre arzuwlary 2026-njy ýylyň 13-nji oktýabryna çenli Vesna we Vodyanitsa-nyň ähtimallygyny artdyrýar; ähtimallygy artdyrylan 4 ýyldyzlylar — Diona, Faruzan we Chongyun.',
  'lead': 'HoYoverse 7.1 wersiýasynyň I tapgyr çäre arzuwlaryny 2026-njy ýylyň 21-nji sentýabrynda çap etdi; olar 2026-njy ýylyň 13-nji oktýabry, 17:59-a çenli dowam edýär.',
  'new': ['"When Warm Winds Cavort" Vesna-nyň (Anemo) düşmek ähtimallygyny artdyrýar.',
          '"Surging Ballad" Vodyanitsa-nyň (Hydro) düşmek ähtimallygyny artdyrýar.',
          'Ähtimallygy artdyrylan 4 ýyldyzly gahrymanlar: Diona (Cryo), Faruzan (Anemo) we Chongyun (Cryo).',
          'Çärä mahsus gahrymanlar adaty arzuwda ýok; iki gahryman banneri bir kepillik hasaplaýjysyny paýlaşýar.'],
  'impact': 'Biziň gözlegimize görä, diňe çäkli bannerlerden alynýan gahrymanlar we olaryň ýyldyz toparlary Genshin hasabynyň gymmatynyň esasy faktorlarynyň biridir.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Trash Goblin Darryl skini we 30-njy sentýabra çenli sowgatlar',
  'desc': 'Supercell-iň Brawl Stars × Duolingo çäresi (2026-njy ýylyň 19-njy sentýabrynda yglan edildi) 30-njy sentýabra çenli Trash Goblin Darryl skinini, gymmatly daşlary, Starr Drop-lary we beýlekileri berdi.',
  'lead': 'Supercell Brawl Stars × Duolingo hyzmatdaşlygyny 2026-njy ýylyň 19-njy sentýabrynda yglan etdi; ol 30-njy sentýabra çenli dowam etdi.',
  'new': ['Jemgyýet maksatlaryndan we oýun içindäki tabşyryklardan ybarat iki tapgyr, şeýle hem täze Duo Boss Fight tertibi.',
          'Sowgatlar: Trash Goblin Darryl skini, 20 gymmatly daş, 5 Chaos Drop, 3 Mythic Starr Drop, 2 000 teňňe, 2 500 Bling we 1 000 kredit.',
          'Duolingo programmasyndaky Brawl Stars tabşyrygy goşmaça bezegler berdi.',
          'Supercell sosial ulgamlarda 3,141592 million gymmatly daş baýrakly bäsleşik hem geçirdi.'],
  'impact': 'Bir gezeklik hyzmatdaşlyk skinleri käbir Brawl Stars kolleksiýalaryny tapawutlandyrýar; köp adamyň mugt alan skini seýrek tölegli skine garanyňda gymmata az goşant goşýar.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN gaýdyp geldi: Dokuz guýrukly we Hinata toplumy (16-njy sentýabr – 15-nji oktýabr)',
  'desc': 'Garena-nyň NARUTO SHIPPUDEN bilen hyzmatdaşlygy 2026-njy ýylyň 16-njy sentýabryndan 15-nji oktýabryna çenli Sharingan: Control ukyby, Jiraiya ýa-da Hinata saýlama toplumy we tematiki bezegler bilen geçýär.',
  'lead': 'Garena 2026-njy ýylyň 15-nji sentýabrynda Free Fire × NARUTO SHIPPUDEN hyzmatdaşlygynyň 16-njy sentýabrdan 15-nji oktýabra çenli gaýdyp gelýändigini yglan etdi.',
  'new': ['Täze ukyplar: Dokuz guýruklyny dolandyrýan Sharingan: Control we 8 Trigrams Palm Rotation.',
          'Gizlin Ýaprak obasy kartasynda giňeldilen Ninja akademiýasy.',
          'Saýlanýan baş baýrak: Jiraiya toplumy ýa-da Hinata toplumy (Hinata-nyň ilkinji çykyşy).',
          'Bezegler: Tsunade-niň plaşy, Gaara-nyň tatuirowka ýüz boýagy, Kakashi-niň ANBU maskasy we Froggy Wallet sandygy.'],
  'impact': 'Diňe çäkli wagt berilýän ygtyýarnamaly hyzmatdaşlyk toplumlary Free Fire kalkulýatorymyzyň gözleýän seýrek zatlarynyň hataryna girýär.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship 8-nji möwsümi başlandy: Stambuldaky M8-e tarap',
  'desc': 'MTC 8-nji möwsümi 2026-njy ýylyň 12-nji sentýabryndan 18-nji oktýabryna çenli sekiz topar we 40 000 dollarlyk baýrak gaznasy bilen geçýär; soňra 2027-nji ýylyň ýanwarynda Stambulda M8 dünýä çempionaty.',
  'lead': 'MOONTON Games 2026-njy ýylyň 10-njy sentýabrynda MLBB Türkiye Championship 8-nji möwsüminiň 12-nji sentýabrda başlanjakdygyny yglan etdi.',
  'new': ['Adaty möwsüm 12-nji sentýabrdan 18-nji oktýabra çenli; uly final 2026-njy ýylyň 7-nji noýabrynda.',
          'Sekiz topar gatnaşýar, olaryň arasynda Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok we Dark Passage bar.',
          'Iň gowy alty topar pleý-offa çykyp, 40 000 dollar üçin göreşýär.',
          'M8 dünýä çempionaty 2027-nji ýylyň ýanwarynda Stambulda geçer — bu M seriýasynyň Ýewropadaky ilkinji çäresi.'],
  'impact': 'Kibersport netijeleri bar bolan hasaplaryň gymmatyny üýtgetmeýär; biziň gözlegimize görä, Collector we Legend skinleri hem-de gahrymanlaryň sany esasy faktor bolmagynda galýar.'},
 'coc-blast': {'title': 'Clash of Clans Equipment Blast medal çäresi (9–22-nji sentýabr)',
  'desc': 'Equipment Blast çäresi 2026-njy ýylyň 9–22-nji sentýabrynda geçdi: Tag Tickets we Champ Medals ýygnap, Söwdagärde gahryman enjamlaryna, magdana we bezeglere çalşyp bolýardy. Town Hall 6 we ondan ýokary.',
  'lead': 'Supercell Equipment Blast medal çäresini 2026-njy ýylyň 9-njy sentýabrynda yglan etdi; ol 22-nji sentýabr sagat 08:00 UTC-e çenli dowam etdi, Söwdagär 24-nji sentýabra çenli açykdy.',
  'new': ['Köp oýunçyly söweşler Tag Tickets berdi; çäre ýoly Champ Medals, wagtlaýyn goşunlar we sandyklar berdi.',
          'Söwdagär çäre medallarynyň deregine gahryman enjamlaryny, magdany we bezegleri satdy.',
          'Wagtlaýyn goşunlar: Undertaker Yeti, K.A.N.E., Yeeter we Giant Giant.',
          'Town Hall 6-dan elýeterlidi.'],
  'impact': 'Gahryman enjamlary we olaryň derejeleri gahrymanlaryň güýjüniň bir bölegi bolup, biziň gözlegimize görä ol Clash of Clans hasabynyň gymmatyny kesgitleýär; çäre medallary ony gowulandyrmagyň ýene bir ýoly.'},
 'mc-wild': {'title': 'Minecraft Wilderness Bound täzelenmesi: tegmilli tokaý, saman düşekler we taşlanan lagerler',
  'desc': 'Mojang-yň Wilderness Bound täzelenmesi 2026-njy ýylyň 15-nji sentýabrynda tegmilli tokaý biomy, derek agajy, saman düşekler, taşlanan lagerler we ýassyklar bilen çykdy.',
  'lead': 'Mojang Studios 2026-njy ýylyň üçünji oýun täzelenmesini 5-nji sentýabrda "Wilderness Bound" diýip atlandyrdy we 15-nji sentýabrda çykardy.',
  'new': ['Täze biom — beýik derekleri we tekje kömelekleri bolan tegmilli tokaý.',
          'Üç saman düwüninden ýasalýan saman düşek täzeden döreýiş nokadyny üýtgetmezden gijäni geçirmäge mümkinçilik berýär.',
          'Öwrenmek üçin taşlanan lagerler we birmeňzeş reňkli üç ýüň plitadan ýasalýan ýassyklar.',
          'Derek agajy hem-de gurluşyk üçin giňeldilen beton we ýüň toplumlary.'],
  'impact': 'Minecraft hasaplary oýun mazmunyna görä däl-de, görnüşine, ulanyjy adyna we plaşlaryna görä bahalandyrylýar, şonuň üçin täzelenme hasabyň gymmatyny üýtgetmeýär.'},
 'ff-award': {'title': 'Free Fire Pocket Gamer Mobile Games Awards 2026-da "Best Use of IP or Licence" baýragyny aldy',
  'desc': 'Garena 2026-njy ýylyň 3-nji sentýabrynda Free Fire-yň NARUTO SHIPPUDEN hyzmatdaşlygy üçin Pocket Gamer Mobile Games Awards 2026-da Best Use of IP or Licence baýragyny alandygyny habar berdi.',
  'lead': 'Garena 2026-njy ýylyň 3-nji sentýabrynda Free Fire-yň Pocket Gamer Mobile Games Awards 2026-da "Best Use of IP or Licence" baýragyny gazanandygyny yglan etdi.',
  'new': ['Baýrak NARUTO SHIPPUDEN Chapter 2: Ninja War hyzmatdaşlygy üçin berildi.',
          'Garena-nyň maglumatyna görä, Bangkokdaky Ninja Clash All Stars çäresine 5 000 töweregi adam geldi we wideolar 247 milliondan gowrak gezek görüldi.',
          'Hyzmatdaşlyk tematiki gahrymanlary, jutsu ukyplaryny we üýtgedilen Gizlin Ýaprak obasy kartasyny öz içine aldy.',
          'Peruda, Bangladeşde, Malaýziýada we Taýwanda jemgyýet çäreleri geçirildi.'],
  'impact': 'Baýrak hasaplaryň gymmatyny üýtgetmeýär. Ýöne ol ygtyýarnamaly hyzmatdaşlyklaryň Free Fire-yň yzygiderli bölegidigini tassyklaýar — olaryň çäkli toplumlary bolsa bahalandyrmada üns berilýän seýrek zatlaryň hatarynda.'},
 'rbx-fall': {'title': 'Roblox güýz oýunlarynyň syny: sentýabrda we oktýabrda çykýan 10 tejribe',
  'desc': 'Roblox-yň güýz oýunlarynyň syny (2026-njy ýylyň 2-nji sentýabry) sentýabrdaky Showdown we Nemesis-den oktýabrdaky Prime Heroes, Octane we Starforged-a çenli 10 täze tejribäni sanaýar.',
  'lead': 'Roblox 2026-njy ýylyň 2-nji sentýabrynda sentýabrda we oktýabrda çykjak on tejribäni öz içine alýan güýz oýunlarynyň synyny çap etdi.',
  'new': ['Sentýabr: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force we Caramel.',
          'Oktýabr: Prime Heroes (sentýabrda 6 gahryman bilen irki giriş), Octane, Starforged we Scrapbook Saga.',
          'Birnäçe oýun Roblox-yň Jumpstart we Incubator döredijiler maksatnamalaryndan çykdy.',
          'Žanrlar atyşykdan we ýaryşdan başlap diri galmak gorkunç oýunlaryna we fermaçylyga çenli.'],
  'impact': 'Täze tejribeler bar bolan hasaplary üýtgetmeýär. Biziň gözlegimize görä, Roblox hasabynyň gymmaty Robux-dan, çäkli zatlardan we köpden bäri işleýän tejribelerdäki zatlardan ybarat; täze oýun diňe onuň zatlary söwda edilip başlanda ähmiýetli bolýar.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: 1-nji oktýabrdan soň "gaýdyp gelmejek" bir gezeklik gahryman skinleri',
  'desc': 'Supercell-iň WWE: Search for Cena çäresi (2026-njy ýylyň sentýabry) Supercell-iň aýtmagyna görä 1-nji oktýabrdan soň gaýdyp gelmejek alty WWE gahryman skinini we Money in the Bank görnüşini satdy.',
  'lead': 'Supercell Clash of Clans üçin WWE: Search for Cena çäresini 2026-njy ýylyň 1-nji sentýabrynda yglan etdi; ol tutuş sentýabr dowam etdi.',
  'new': ['Her biri 9,99 dollarlyk gahryman skinleri: Cody Rhodes (Barbar patyşa), Alexa Bliss (Okçy melike), Iyo Sky (Patyşa çempiony), Kane (Aždarha gersogy) we American Badass Undertaker (Beýik goragçy).',
          'Jey Uso (Minion şazada) Gold Pass bilen berildi.',
          'Supercell bu skinleriň 1-nji oktýabrdan soň "gaýdyp gelmejekdigini. Hiç haçan" aýdýar.',
          'Money in the Bank XL görnüşi 2–30-njy sentýabr aralygynda satyldy; şol döwürde John Cena synagy we wagtlaýyn WWE goşunlary hem bardy.'],
  'impact': 'Neşirçiniň hiç haçan gaýdyp gelmez diýýän skinleri edil Clash of Clans hasabyny has seýrek edýän bezeg görnüşidir. Şeýle-de bolsa, gymmatyň uly bölegi henizem Town Hall we gahryman derejelerinde.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: iki tapgyrly täze formata ilkinji nazar',
  'desc': 'Supercell-iň BSC 2027-ä ilkinji nazary (2026-njy ýylyň 24-nji awgusty): dört sebitiň her birinde sekiz topar, 12 sebitde Challengers, 12 hepdelik iki tapgyr, Brawl Cup we Dünýä finaly.',
  'lead': 'Supercell 2026-njy ýylyň 24-nji awgustynda 2027 Brawl Stars Championship-a ilkinji nazary hödürledi we jikme-jiklikleriň üýtgäp biljekdigini belledi.',
  'new': ['Iň ýokary dereje: Gündogar Aziýada, EMEA-da, Günorta Amerikada we Demirgazyk Amerikada her sebitde 8 topar.',
          'Challengers: 12 sebitde professional derejä giriş ýoly.',
          'Her biri 12 hepdelik iki tapgyr; 1-nji tapgyr üç günlük halkara LAN ýaryşy Brawl Cup bilen, 2-nji tapgyr Dünýä finaly bilen tamamlanýar.',
          'Seneler, baýrak gaznasy we geçiriljek ýerler entek yglan edilmedi.'],
  'impact': 'Kibersport formatlary bar bolan hasaplaryň gymmatyny üýtgetmeýär; Brawl Stars kalkulýatorymyz öňküsi ýaly söweşijileriň sanyny, Hypercharge-lary we kuboklary ulanýar.'},
}},
}
