# News batch 4: tr, ar, vi, hi (from news_text_b4_en.py, facts unchanged)
TEXT = {
'tr': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends Asya Oyunları’nda: Myanmar, Endonezya’yı 4–0 yenerek ilk MLBB altınını kazandı',
  'desc': 'MOONTON 1 Ekim 2026’da duyurdu: Myanmar, Aichi-Nagoya 2026’da büyük finalde Endonezya’yı 4–0 yenerek Mobile Legends: Bang Bang’de Asya Oyunları’nın ilk altın madalyasını kazandı.',
  'lead': 'MOONTON Games, 1 Ekim 2026’da Mobile Legends: Bang Bang’in Asya Oyunları’ndaki ilk resmî madalya etkinliğinin sonucunu açıkladı.',
  'new': ['Myanmar, Aichi Sky Expo’daki büyük finalde Endonezya’yı 4–0 yendi ve MLBB’de Asya Oyunları’nın ilk altın madalyalısı oldu.',
          'Endonezya gümüş, Malezya ve Moğolistan bronz madalya aldı.',
          'Ön eleme turlarından itibaren 22 Ulusal Olimpiyat Komitesi katıldı, 12 takım ana aşamaya yükseldi.',
          'Takvimde sırada MLBB Championship Tour ve M8 Dünya Şampiyonası var; M8 finalleri İstanbul’da oynanacak.'],
  'impact': 'Espor sonuçları mevcut hesapların değerini değiştirmez. Araştırmamıza göre Mobile Legends’ta değeri hâlâ görünümler, kahramanlar ve hesap ilerlemesi belirliyor.'},
 'mc-drop4': {
  'title': 'Minecraft’ın 2026’daki son oyun güncellemesi testte: buz mağaraları, frostbite ve ice balls',
  'desc': 'Mojang, 2026’nın son game drop’unun testini 30 Eylül 2026’da açtı: buz mağaraları, frostbite adlı donmuş zombi türü, ice balls, buz kristalleri ve buz sarkıtları.',
  'lead': 'Mojang Studios, 30 Eylül 2026’da 2026’nın son Minecraft game drop’u için testleri başlattı.',
  'new': ['Buz kristalleri (ice crystals) ve buz sarkıtlarıyla (icicles) süslü yeni buz mağaraları; sarkıtlar kırılgan.',
          'Yeni yaratık frostbite (donmuş bir zombi türü) ice balls fırlatıyor; Mojang ayrıca bir Freezing iksirinden söz ediyor.',
          '30 Eylül’deki ilk test sürümü Bedrock Edition için preview/beta; yazı ayrıca Java Edition snapshot’larının Minecraft Launcher’da nasıl açılacağını anlatıyor.',
          'Mojang, test sürümlerinin dünyaları bozabileceği konusunda uyarıyor ve yedek alınmasını ya da ayrı bir klasör kullanılmasını istiyor.'],
  'impact': 'Minecraft hesapları oyun içi içeriğe göre değil; hesap türüne (Java veya Bedrock), kullanıcı adına ve pelerinlere göre değerlenir. Bu tür güncellemeler oyuncunun yapabildiklerini değiştirir, hesabın değerini değil.'},
 'cr-bal-oct': {
  'title': 'Clash Royale Ekim denge değişiklikleri: Hero Ice Wizard ve Minion Giant zayıflatıldı, Lava Hound güçlendirildi',
  'desc': 'Supercell 6 Ekim 2026 denge güncellemesini yayımladı: Hero Ice Wizard dondurma hasarı 89 → 46, Minion Giant vuruş hızı 1,5 sn → 1,7 sn, Lava Hound hasarı 53 → 71, Golden Knight yeniden düzenlendi.',
  'lead': 'Supercell, Clash Royale’in 6 Ekim 2026 tarihli denge güncellemesini yayımladı.',
  'new': ['Zayıflatmalar: Hero Ice Wizard dondurma hasarı 89 → 46; Cannon Evolution yaylım hasarı 281 → 261; Barbarian Barrel hasarı 232 → 215; Minion Giant vuruş hızı 1,5 sn → 1,7 sn; Royal Ghost canı 1210 → 1152.',
          'Elixir Collector: ömür 1 dk 33 sn → 1 dk 50 sn, üretim hızı 13 sn → 15 sn.',
          'Güçlendirmeler: Lava Hound hasarı 53 → 71 (vuruş hızı 1,3 sn → 1,5 sn); Ram Rider hasarı 250 → 271; Wall Breakers hasarı 281 → 302; X-Bow hasarı 58 → 61; Three Musketeers canı 883 → 906.',
          'Yeniden düzenleme: Golden Knight hasarı 161 → 168, atılma menzili 5,5 → 5 kare. Supercell, rakamların 11. seviyeye göre verildiğini belirtiyor.'],
  'impact': 'Denge değişiklikleri hangi destelerin güçlü olduğunu değiştirir, hesabın içeriğini değil. Araştırmamıza göre Kral Kulesi seviyesi ve kart seviyeleri ana değer etkenleri olmayı sürdürüyor.'},
}},
'ar': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends في دورة الألعاب الآسيوية: ميانمار تحرز أول ذهبية في MLBB بفوزها على إندونيسيا 4–0',
  'desc': 'أعلنت MOONTON في 1 أكتوبر 2026 أن ميانمار أحرزت أول ذهبية في دورة الألعاب الآسيوية للعبة Mobile Legends: Bang Bang في آيتشي-ناغويا 2026 بعد فوزها على إندونيسيا 4–0 في النهائي الكبير.',
  'lead': 'في 1 أكتوبر 2026 أعلنت MOONTON Games نتيجة أول مشاركة للعبة Mobile Legends: Bang Bang كمسابقة رسمية بميداليات في دورة الألعاب الآسيوية.',
  'new': ['فازت ميانمار على إندونيسيا 4–0 في النهائي الكبير في Aichi Sky Expo وأصبحت أول حاصل على ذهبية الألعاب الآسيوية في MLBB.',
          'نالت إندونيسيا الفضية، ونالت ماليزيا ومنغوليا الميداليتين البرونزيتين.',
          'شاركت 22 لجنة أولمبية وطنية منذ الأدوار التمهيدية، وتأهل 12 فريقًا إلى المرحلة الرئيسية.',
          'التالي في الروزنامة: MLBB Championship Tour وبطولة العالم M8، وتقام نهائيات M8 في إسطنبول بتركيا.'],
  'impact': 'نتائج الرياضات الإلكترونية لا تغيّر قيمة الحسابات الموجودة. وبحسب بحثنا، ما زالت المظاهر والأبطال وتقدّم الحساب هي ما يحدد القيمة في Mobile Legends.'},
 'mc-drop4': {
  'title': 'آخر تحديث لماينكرافت في 2026 يدخل مرحلة الاختبار: كهوف جليدية وfrostbite وice balls',
  'desc': 'فتحت Mojang في 30 سبتمبر 2026 اختبار آخر game drop لعام 2026: كهوف جليدية، ونوع زومبي متجمد اسمه frostbite، وice balls، وبلورات جليدية وأعمدة جليدية متدلية.',
  'lead': 'في 30 سبتمبر 2026 فتحت Mojang Studios اختبار آخر game drop للعبة Minecraft لعام 2026.',
  'new': ['كهوف جليدية جديدة تزيّنها بلورات جليدية (ice crystals) وأعمدة جليدية متدلية (icicles)؛ والأعمدة المتدلية هشّة.',
          'كائن جديد هو frostbite (نوع زومبي متجمد) يرمي ice balls؛ وتذكر Mojang أيضًا جرعة Freezing.',
          'أول نسخة اختبار، في 30 سبتمبر، هي preview/beta لإصدار Bedrock Edition؛ ويشرح المنشور كذلك طريقة تفعيل snapshots لإصدار Java Edition في Minecraft Launcher.',
          'تحذّر Mojang من أن نسخ الاختبار قد تُتلف العوالم، وتطلب أخذ نسخة احتياطية أو استخدام مجلد منفصل.'],
  'impact': 'تُقيَّم حسابات Minecraft بحسب نوع الحساب (Java أو Bedrock) واسم المستخدم والعباءات، لا بحسب محتوى اللعبة. تحديثات كهذه تغيّر ما يستطيع اللاعب فعله، لا قيمة الحساب.'},
 'cr-bal-oct': {
  'title': 'تغييرات التوازن لشهر أكتوبر في Clash Royale: إضعاف Hero Ice Wizard وMinion Giant وتقوية Lava Hound',
  'desc': 'نشرت Supercell تحديث التوازن ليوم 6 أكتوبر 2026: ضرر تجميد Hero Ice Wizard من 89 إلى 46، سرعة ضربة Minion Giant من 1.5 ث إلى 1.7 ث، ضرر Lava Hound من 53 إلى 71، وإعادة تصميم Golden Knight.',
  'lead': 'نشرت Supercell تحديث توازن Clash Royale ليوم 6 أكتوبر 2026.',
  'new': ['الإضعاف: ضرر تجميد Hero Ice Wizard من 89 إلى 46؛ ضرر وابل Cannon Evolution من 281 إلى 261؛ ضرر Barbarian Barrel من 232 إلى 215؛ سرعة ضربة Minion Giant من 1.5 ث إلى 1.7 ث؛ نقاط حياة Royal Ghost من 1210 إلى 1152.',
          'Elixir Collector: مدة البقاء من 1 د 33 ث إلى 1 د 50 ث، وسرعة الإنتاج من 13 ث إلى 15 ث.',
          'التقوية: ضرر Lava Hound من 53 إلى 71 (سرعة الضربة من 1.3 ث إلى 1.5 ث)؛ ضرر Ram Rider من 250 إلى 271؛ ضرر Wall Breakers من 281 إلى 302؛ ضرر X-Bow من 58 إلى 61؛ نقاط حياة Three Musketeers من 883 إلى 906.',
          'إعادة تصميم: ضرر Golden Knight من 161 إلى 168، ومدى الاندفاع من 5.5 إلى 5 مربعات. وتشير Supercell إلى أن الأرقام محسوبة عند المستوى 11.'],
  'impact': 'تغييرات التوازن تبدّل المجموعات القوية، لا ما يحتويه الحساب. وبحسب بحثنا، يبقى مستوى برج الملك ومستويات البطاقات أهم عوامل القيمة.'},
}},
'vi': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends tại Asian Games: Myanmar giành HCV MLBB đầu tiên sau khi thắng Indonesia 4–0',
  'desc': 'Ngày 1/10/2026 MOONTON cho biết Myanmar giành huy chương vàng Asian Games đầu tiên của Mobile Legends: Bang Bang tại Aichi-Nagoya 2026, sau khi thắng Indonesia 4–0 ở Chung kết tổng.',
  'lead': 'Ngày 1/10/2026 MOONTON Games công bố kết quả lần đầu Mobile Legends: Bang Bang là nội dung tranh huy chương chính thức tại Asian Games.',
  'new': ['Myanmar thắng Indonesia 4–0 ở Chung kết tổng tại Aichi Sky Expo và trở thành đội đầu tiên giành HCV Asian Games ở MLBB.',
          'Indonesia giành HCB; Malaysia và Mông Cổ giành HCĐ.',
          '22 Ủy ban Olympic Quốc gia tham dự từ các vòng sơ loại, và 12 đội vào Vòng chính.',
          'Tiếp theo trong lịch thi đấu là MLBB Championship Tour và M8 World Championship, với chung kết M8 diễn ra tại Istanbul, Thổ Nhĩ Kỳ.'],
  'impact': 'Kết quả esports không làm thay đổi giá trị của các tài khoản hiện có. Theo nghiên cứu của chúng tôi, skin, tướng và tiến độ tài khoản vẫn là những gì quyết định giá trị Mobile Legends.'},
 'mc-drop4': {
  'title': 'Game drop cuối cùng của Minecraft năm 2026 bước vào thử nghiệm: hang băng, frostbite và ice balls',
  'desc': 'Ngày 30/9/2026 Mojang mở thử nghiệm game drop cuối cùng của năm 2026: hang băng, biến thể zombie đóng băng tên là frostbite, ice balls, tinh thể băng và nhũ băng.',
  'lead': 'Ngày 30/9/2026 Mojang Studios mở thử nghiệm game drop Minecraft cuối cùng của năm 2026.',
  'new': ['Hang băng mới, được trang trí bằng tinh thể băng (ice crystals) và nhũ băng (icicles); nhũ băng dễ vỡ.',
          'Mob mới frostbite (một biến thể zombie đóng băng) ném ice balls; Mojang cũng nhắc tới thuốc Freezing.',
          'Bản thử nghiệm đầu tiên, ngày 30/9, là preview/beta của Bedrock Edition; bài viết cũng hướng dẫn cách bật snapshot của Java Edition trong Minecraft Launcher.',
          'Mojang cảnh báo các bản thử nghiệm có thể làm hỏng thế giới và đề nghị người chơi sao lưu hoặc dùng thư mục riêng.'],
  'impact': 'Tài khoản Minecraft được định giá theo loại tài khoản (Java hoặc Bedrock), tên người dùng và áo choàng — không phải theo nội dung trong game. Các bản cập nhật như thế này thay đổi những gì người chơi làm được, không thay đổi giá trị tài khoản.'},
 'cr-bal-oct': {
  'title': 'Cân bằng tháng 10 của Clash Royale: Hero Ice Wizard và Minion Giant bị giảm sức mạnh, Lava Hound được tăng',
  'desc': 'Supercell công bố bản cân bằng ngày 6/10/2026: sát thương đóng băng của Hero Ice Wizard 89 → 46, tốc độ đánh của Minion Giant 1,5 giây → 1,7 giây, sát thương Lava Hound 53 → 71, Golden Knight được làm lại.',
  'lead': 'Supercell công bố bản cập nhật cân bằng Clash Royale ngày 6/10/2026.',
  'new': ['Giảm sức mạnh: sát thương đóng băng của Hero Ice Wizard 89 → 46; sát thương loạt bắn của Cannon Evolution 281 → 261; sát thương Barbarian Barrel 232 → 215; tốc độ đánh của Minion Giant 1,5 giây → 1,7 giây; máu Royal Ghost 1210 → 1152.',
          'Elixir Collector: thời gian tồn tại 1 phút 33 giây → 1 phút 50 giây, tốc độ sản xuất 13 giây → 15 giây.',
          'Tăng sức mạnh: sát thương Lava Hound 53 → 71 (tốc độ đánh 1,3 giây → 1,5 giây); sát thương Ram Rider 250 → 271; sát thương Wall Breakers 281 → 302; sát thương X-Bow 58 → 61; máu Three Musketeers 883 → 906.',
          'Làm lại: sát thương Golden Knight 161 → 168, tầm lướt 5,5 → 5 ô. Supercell lưu ý các con số được tính ở Cấp 11.'],
  'impact': 'Thay đổi cân bằng làm thay đổi bộ bài nào mạnh, chứ không thay đổi những gì tài khoản có. Theo nghiên cứu của chúng tôi, cấp King Tower và cấp thẻ bài vẫn là yếu tố giá trị chính.'},
}},
'hi': {'a': {
 'ml-asiad': {
  'title': 'एशियाई खेलों में Mobile Legends: म्यांमार ने इंडोनेशिया को 4–0 से हराकर MLBB का पहला स्वर्ण जीता',
  'desc': 'MOONTON ने 1 अक्टूबर 2026 को बताया कि म्यांमार ने आइची-नागोया 2026 में Mobile Legends: Bang Bang का पहला एशियाई खेल स्वर्ण जीता, ग्रैंड फ़ाइनल में इंडोनेशिया को 4–0 से हराकर।',
  'lead': '1 अक्टूबर 2026 को MOONTON Games ने एशियाई खेलों में आधिकारिक पदक स्पर्धा के रूप में Mobile Legends: Bang Bang की पहली प्रतियोगिता का नतीजा घोषित किया।',
  'new': ['म्यांमार ने Aichi Sky Expo में ग्रैंड फ़ाइनल में इंडोनेशिया को 4–0 से हराया और MLBB में एशियाई खेलों का पहला स्वर्ण पदक विजेता बना।',
          'इंडोनेशिया को रजत मिला; मलेशिया और मंगोलिया को कांस्य पदक मिले।',
          'शुरुआती क्वालिफ़िकेशन राउंड से 22 राष्ट्रीय ओलंपिक समितियों ने हिस्सा लिया और 12 टीमें मुख्य चरण में पहुँचीं।',
          'कैलेंडर में आगे MLBB Championship Tour और M8 World Championship हैं; M8 के फ़ाइनल इस्तांबुल, तुर्किये में होंगे।'],
  'impact': 'ईस्पोर्ट्स के नतीजों से मौजूदा अकाउंट की वैल्यू नहीं बदलती। हमारी रिसर्च में Mobile Legends की वैल्यू अब भी स्किन, हीरो और अकाउंट की प्रगति से तय होती है।'},
 'mc-drop4': {
  'title': 'Minecraft का 2026 का आख़िरी गेम ड्रॉप टेस्टिंग में: बर्फ़ की गुफाएँ, frostbite और ice balls',
  'desc': 'Mojang ने 30 सितंबर 2026 को 2026 के आख़िरी गेम ड्रॉप की टेस्टिंग शुरू की: बर्फ़ की गुफाएँ, frostbite नाम का जमा हुआ ज़ॉम्बी वेरिएंट, ice balls, बर्फ़ के क्रिस्टल और icicles।',
  'lead': '30 सितंबर 2026 को Mojang Studios ने 2026 के आख़िरी Minecraft गेम ड्रॉप की टेस्टिंग शुरू की।',
  'new': ['नई बर्फ़ की गुफाएँ, जो बर्फ़ के क्रिस्टल (ice crystals) और icicles से सजी हैं; icicles नाज़ुक हैं।',
          'नया मॉब frostbite (ज़ॉम्बी का जमा हुआ वेरिएंट) ice balls फेंकता है; Mojang एक Freezing पोशन का भी ज़िक्र करता है।',
          '30 सितंबर का पहला टेस्ट बिल्ड Bedrock Edition का preview/beta है; पोस्ट में यह भी बताया गया है कि Minecraft Launcher में Java Edition के snapshot कैसे चालू करें।',
          'Mojang चेतावनी देता है कि टेस्ट वर्ज़न दुनिया को ख़राब कर सकते हैं और बैकअप लेने या अलग फ़ोल्डर इस्तेमाल करने को कहता है।'],
  'impact': 'Minecraft अकाउंट की वैल्यू अकाउंट के प्रकार (Java या Bedrock), यूज़रनेम और केप से तय होती है — इन-गेम कंटेंट से नहीं। ऐसे अपडेट यह बदलते हैं कि खिलाड़ी क्या कर सकता है, अकाउंट की क़ीमत नहीं।'},
 'cr-bal-oct': {
  'title': 'Clash Royale अक्टूबर बैलेंस बदलाव: Hero Ice Wizard और Minion Giant कमज़ोर, Lava Hound मज़बूत',
  'desc': 'Supercell ने 6 अक्टूबर 2026 का बैलेंस अपडेट प्रकाशित किया: Hero Ice Wizard का फ़्रीज़ डैमेज 89 → 46, Minion Giant की हिट स्पीड 1.5 से → 1.7 से, Lava Hound का डैमेज 53 → 71, Golden Knight में बदलाव।',
  'lead': 'Supercell ने Clash Royale का 6 अक्टूबर 2026 का बैलेंस अपडेट प्रकाशित किया।',
  'new': ['नर्फ़: Hero Ice Wizard का फ़्रीज़ डैमेज 89 → 46; Cannon Evolution का बैराज डैमेज 281 → 261; Barbarian Barrel का डैमेज 232 → 215; Minion Giant की हिट स्पीड 1.5 से → 1.7 से; Royal Ghost के हिटपॉइंट 1210 → 1152।',
          'Elixir Collector: जीवनकाल 1 मि 33 से → 1 मि 50 से, उत्पादन गति 13 से → 15 से।',
          'बफ़: Lava Hound का डैमेज 53 → 71 (हिट स्पीड 1.3 से → 1.5 से); Ram Rider का डैमेज 250 → 271; Wall Breakers का डैमेज 281 → 302; X-Bow का डैमेज 58 → 61; Three Musketeers के हिटपॉइंट 883 → 906।',
          'रीवर्क: Golden Knight का डैमेज 161 → 168, डैश रेंज 5.5 → 5 टाइल। Supercell के अनुसार आँकड़े लेवल 11 पर दिए गए हैं।'],
  'impact': 'बैलेंस बदलाव यह बदलते हैं कि कौन-से डेक मज़बूत हैं, यह नहीं कि अकाउंट में क्या है। हमारी रिसर्च में King Tower का लेवल और कार्ड लेवल ही वैल्यू के मुख्य कारक बने हुए हैं।'},
}},
}
