# News translations: ru, es (from news_data.py 'en', facts unchanged)
TEXT = {
'ru': {
 'ui': {
  'news': 'Новости', 'news_title': 'Новости игр, которые влияют на стоимость аккаунта',
  'news_lead': 'Официальные обновления от издателей игр — каждое сверено с объявлением самого издателя, с коротким пояснением, что оно значит для стоимости аккаунта.',
  'game_title': 'Новости {game}', 'game_lead': 'Официальные обновления {game}, которые влияют на стоимость аккаунта. В каждой статье — ссылка на объявление издателя.',
  'published': 'Опубликовано', 'source': 'Официальный источник', 'by_on': '{pub}, {date}', 'whats_new': 'Что нового',
  'impact': 'Что это значит для стоимости аккаунта', 'more': 'Ещё новости {game}', 'all': 'Все новости',
  'calc': '{game}: калькулятор стоимости и отчёт по рынку', 'read': 'Читать', 'latest': 'Свежие новости {game}',
  'note': 'GameAccountValue не покупает, не продаёт и не перепродаёт аккаунты. Новости пересказаны по объявлениям издателей только для информации.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Весна и Водяница, подтверждены награды к годовщине',
   'desc': 'Версия 7.1 «Реквием по Подземному миру» вышла 23 сентября 2026 года: два новых 5-звёздочных персонажа, два 5-звёздочных оружия и награды к шестой годовщине.',
   'lead': 'HoYoverse выпустила версию 7.1 «Реквием по Подземному миру» 23 сентября 2026 года — это обновление приходится и на шестую годовщину Genshin Impact.',
   'new': ['Два новых 5-звёздочных персонажа: Весна (Vesna; Анемо, меч) и Водяница (Vodyanitsa; Гидро, катализатор).',
           'Новое оружие: Beyond the Chrysalis (5★ меч), Hymn of the Maelstrom (5★ катализатор) и New Bough (4★ меч).',
           'Награды к годовщине по объявлению HoYoverse: два 5-звёздочных персонажа на выбор, «Переплетающиеся судьбы» ×10, Камни истока ×1 600 и сброс бонуса первого пополнения Кристаллов Генезиса.',
           'Техработы начались 23 сентября в 06:00 (UTC+8).'],
   'impact': 'Количество лимитированных 5-звёздочных персонажей, их созвездий и сигнатурного оружия — один из главных факторов стоимости аккаунтов Genshin по нашему исследованию. Персонажи, которых к годовщине бесплатно получают все игроки, делают аккаунт менее уникальным, чем персонажи из лимитированных баннеров.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift — первое новое измерение за 14 с лишним лет — придёт в Java и Bedrock',
   'desc': 'На Minecraft Live 26 сентября 2026 года показали The Sift — четвёртое измерение, которое появится в Java и Bedrock в следующем году, а также Dungeons II и дроп Wilderness Bound.',
   'lead': 'На Minecraft Live 26 сентября 2026 года Mojang Studios объявила, что четвёртое измерение игры, The Sift, появится в Minecraft Java и Bedrock Edition в следующем году.',
   'new': ['The Sift — первое новое измерение за более чем 14 лет; оно присоединится к Верхнему миру, Незеру и Энду.',
           'Дебют измерения — в Minecraft Dungeons II, выход которой Mojang назначила на 29 сентября 2026 года.',
           'Тематический парк Minecraft World откроется в Лондоне в 2027 году.',
           'Игровой дроп Wilderness Bound вышел 15 сентября: пятнистый лес, соломенные кровати, заброшенные лагеря и подушки.'],
   'impact': 'Аккаунты Minecraft оцениваются по типу (Java или Bedrock), нику и плащам, а не по игровому контенту. Такие обновления меняют то, что можно делать в игре, но не стоимость аккаунта.'},
  'rbx-hunt': {
   'title': 'Roblox 20 «The Hunt»: лимитированные UGC-предметы и эксклюзивы Roblox Plus (17–28 сентября)',
   'desc': 'Ивент The Hunt: Roblox 20 проходил с 17 по 28 сентября 2026 года: UGC-награды, лимитированные UGC-предметы и три эксклюзивных предмета для подписчиков Roblox Plus.',
   'lead': 'Roblox отметил 20-летие ивентом The Hunt: Roblox 20 на всей платформе — он шёл с 17 по 28 сентября 2026 года.',
   'new': ['Игроки проходили 20 лет истории Roblox — по квесту на каждый год, начиная с «Year Zero»; прохождение всех 20 открывало «Year Infinity» ещё с 20 играми.',
           'За квесты давали UGC-предметы, а во время ивента были доступны лимитированные UGC-предметы.',
           'Подписчики Roblox Plus получили три эксклюзивных виртуальных предмета и сохраняют классическую тему приложения, классический фон аватара и рамку профиля после ивента.',
           'Классическая тема приложения была бесплатной для всех, пока шёл ивент.'],
   'impact': 'Предметы, которые можно было получить только во время ивента, — одно из того, на что смотрит оценка аккаунта. Roblox не назвал эти предметы в объявлении, поэтому сайт не даёт им цену, пока не появятся реальные объявления о продаже.'},
  'rbx-rdc': {
   'title': 'RDC 2026: авторы Roblox заработали около $1,7 млрд за год; анонсирован Roblox Wallet',
   'desc': 'На RDC 2026 Roblox сообщил о заработке авторов около $1,7 млрд за 12 месяцев и анонсировал Roblox Wallet и Roblox Card для выплат.',
   'lead': 'На конференции разработчиков RDC 2026 (объявление от 11 сентября 2026 года) Roblox поделился цифрами заработка авторов и новыми инструментами выплат.',
   'new': ['С запуска DevEx в 2013 году авторы заработали более $5 млрд, а за 12 месяцев до 30 июня 2026 года — около $1,7 млрд.',
           'Стимулы Roblox Plus принесли авторам более 300 млн Robux за первые четыре месяца (до 17 августа 2026 года).',
           'Roblox Wallet — платёжный счёт с партнёром Airwallex US — даст ежедневные выплаты в реальной валюте: сначала для подходящих независимых авторов из США от 18 лет позже в 2026 году, в других странах — в 2027-м.',
           'Карта Roblox Card, привязанная к Wallet, запланирована с 2027 года.'],
   'impact': 'Эти изменения касаются выплат авторам, а не аккаунтов игроков: объявление не меняло цены Robux, лимитированные предметы и обмен. Баланс Robux и лимитированные предметы остаются тем, что учитывает наш калькулятор Roblox.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: четыре новых оружия для Clash Squad, Prime Diamond и переработка Кенты',
   'desc': 'Патч-ноуты OB55 от Garena (10 сентября 2026 года): с 1 октября в Clash Squad появляются M7, Skorp, RPK и Hawk, вводится Prime Diamond, переработан Кента.',
   'lead': 'Garena опубликовала патч-ноуты OB55 для Free Fire 10 сентября 2026 года; изменения оружия вступают в силу 1 октября.',
   'new': ['Новое оружие Clash Squad с 1 октября: M7 (1 600 CS Cash), Skorp (1 500), RPK (1 500) и Hawk (1 700).',
           'Prime Diamond: алмазы начисляются в зависимости от трат за месяц и забираются в следующем месяце после любого пополнения.',
           'Кента полностью переработан; Морс, Луна и Укун получили изменения баланса.',
           'С 1 октября меняется подвижность по классам оружия: ПП быстрее, снайперские и марксманские винтовки медленнее.'],
   'impact': 'Наш калькулятор Free Fire учитывает баланс алмазов и редкие наборы. OB55 меняет то, как вознаграждаются будущие пополнения, но не меняет предметы, которые уже есть в аккаунтах.'},
  'cr-minion': {
   'title': 'Clash Royale, сезон «Minion Academy»: новая карта Миньон-гигант и герой Ледяной маг',
   'desc': 'Сезон Minion Academy (7 сентября — 5 октября 2026 года) добавляет карту Миньон-гигант, героя Ледяного мага и ивент-альбом с 1 750 картами Миньон-гиганта.',
   'lead': 'Supercell открыла сезон Clash Royale «Minion Academy», который идёт с 7 сентября по 5 октября 2026 года.',
   'new': ['Новая карта Миньон-гигант (Minion Giant): летающая атакующая карта, бьющая по зданиям и башням. Её можно бесплатно получить в ивенте-альбоме Academy Antics; в сундуках она появится только в следующем сезоне.',
           'Ивент-альбом даёт 1 750 карт Миньон-гиганта, эмодзи и скин башни.',
           'Новый герой — Ледяной маг: с трека Pass Royale или за 200 монет героев.',
           'Ивенты: лига 2 на 2 (7–21 сентября), глобальный турнир Princess Gambit (21–26 сентября) и Royale Shuffle (21 сентября — 5 октября). Ничья в Ultimate Champion теперь стоит половину трофеев от поражения.'],
   'impact': 'Скины башен и эмодзи, доступные только во время ивента, делают коллекцию Clash Royale более уникальной, но главными факторами стоимости остаются уровень Королевской башни и уровни карт.'},
  'ml-10': {
   'title': 'Mobile Legends 10 лет: кампания ALL IN и новый коллекционный скин Лейлы',
   'desc': 'Кампания MOONTON ALL IN к 10-летию (с 4 сентября 2026 года): новый эпический скин Наны, бесплатные сундуки скинов и коллекционный скин Лейлы с 9 октября.',
   'lead': 'MOONTON Games 4 сентября 2026 года запустила ALL IN — кампанию к десятилетию Mobile Legends: Bang Bang.',
   'new': ['Пропуск 10-летия (4 сентября — 1 ноября): новый эпический скин Наны, сундук выбора эпического скина, сундук случайного эпического скина и бесплатный юбилейный скин для вернувшихся игроков.',
           'Юбилейные выходные Gala (25 сентября — 11 октября): доступ к 265 скинам, опыт Battle Pass и фрагменты премиум-скинов.',
           'Layla’s Stellar Gala (9 октября — 19 ноября): новый коллекционный скин Лейлы через мини-игру «Starfall Breakout».',
           'MOONTON сообщает о более чем 1,5 млрд установок и 110 млн активных игроков в месяц.'],
   'impact': 'Коллекционные и легендарные скины — среди самых часто упоминаемых факторов стоимости аккаунтов Mobile Legends; скины, которые раздают бесплатно или дают на пробу, к ним не относятся.'},
  'bs-aug': {
   'title': 'Brawl Stars: мифические бойцы Космо и Винс; «Путь Старр» стал Brawler Blast',
   'desc': 'Патч-ноуты Supercell за август 2026 года (1 сентября): два мифических бойца, «Путь Старр» переделан в Brawler Blast с новыми ценами в кредитах, редкость «Ультралегендарный» переименована в «Ультра».',
   'lead': 'Supercell опубликовала патч-ноуты Brawl Stars к августовскому обновлению 2026 года 1 сентября 2026 года.',
   'new': ['Два новых мифических бойца: Космо (Cosmo, контролёр) и Винс (Vince, наносящий урон).',
           'Новые гиперзаряды для Нори и Венди.',
           '«Путь Старр» переделан в «Brawler Blast»: кредиты теперь идут на открытие по редкости — редкий 160, сверхредкий 430, эпический 925, мифический 1 900, легендарный 3 800, ультра 5 500.',
           'Редкость «Ультралегендарный» переименована в «Ультра». Плюс сезон Royal Academy и ивент Brawl-O-Ween на весь месяц.'],
   'impact': 'Наш калькулятор Brawl Stars учитывает число бойцов, гиперзаряды и трофеи. Два новых мифических бойца увеличивают число бойцов, нужных для полной коллекции.'},
  'coc-aug': {
   'title': 'Clash of Clans, августовское обновление: уровни Дигги 11–15 и Золотой пропуск с Ратуши 3',
   'desc': 'Августовское обновление Supercell (30 августа 2026 года): уровни Дигги 11–15 и новые суперзаряды на Ратуше 18, отмена Стартового пропуска, Золотой пропуск с Ратуши 3.',
   'lead': 'Supercell выпустила августовское обновление Clash of Clans 30 августа 2026 года.',
   'new': ['Ратуша 18: питомец Дигги получает уровни 11–15; Хижина строителя и Монолит — новые уровни суперзаряда.',
           'Стартовый пропуск отменён: сезонные испытания и Золотой пропуск теперь доступны с Ратуши 3, награды зависят от уровня Ратуши.',
           'Рыцарь руин больше не теряет здоровье со временем; Ведьма руин призывает 10 рыцарей руин вместо 8.',
           'Изменены модификаторы Лиги войн кланов в титановых лигах.'],
   'impact': 'Уровень Ратуши и уровни героев и питомцев — главные факторы стоимости аккаунтов Clash of Clans по нашему исследованию. Новые максимальные уровни на Ратуше 18 значат, что «максимальному» аккаунту теперь нужно больше улучшений, чем до обновления.'},
  'fn-c7s4': {
   'title': 'Fortnite, Глава 7, Сезон 4 «Override»: Боевой пропуск с Соником и кроссовер с KINGDOM HEARTS',
   'desc': 'Сезон Epic «Override» (Глава 7, Сезон 4): консоли Override, Боевой пропуск за 800 V-Bucks во главе с Ежом Соником и кроссоверы, включая KINGDOM HEARTS.',
   'lead': '4-й сезон 7-й главы Fortnite называется «Override». Epic описывает его как сезон игровых кроссоверов и изменения правил на весь матч.',
   'new': ['Консоли Override есть в каждом матче и позволяют менять правила для всего сервера.',
           'Боевой пропуск стоит 800 V-Bucks; главный герой — Ёж Соник вместе с помощником Тейлзом.',
           'Купившие пропуск до 27 августа 23:59 по восточному времени США получили бонусный облик Infiltrator Grace Crowne за первую неделю.',
           'Кроссоверы сезона: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot и Spyro the Dragon; среди оружия — Midas’ Masterpiece и Mega Buster из Mega Man.'],
   'impact': 'Облики, доступные ограниченное время — например, бонус первой недели, — отличают редкие шкафчики Fortnite от обычных. Облики из Боевого пропуска остаются привязаны к своему сезону.'},
 }},
'es': {
 'ui': {
  'news': 'Noticias', 'news_title': 'Noticias de juegos que afectan al valor de una cuenta',
  'news_lead': 'Actualizaciones oficiales de las editoras, cada una comprobada con el anuncio de la propia editora, con una nota clara sobre lo que significa para el valor de una cuenta.',
  'game_title': 'Noticias de {game}', 'game_lead': 'Actualizaciones oficiales de {game} que afectan a lo que vale una cuenta. Cada artículo enlaza el anuncio de la editora.',
  'published': 'Publicado', 'source': 'Fuente oficial', 'by_on': '{pub}, {date}', 'whats_new': 'Novedades',
  'impact': 'Qué significa para el valor de la cuenta', 'more': 'Más noticias de {game}', 'all': 'Todas las noticias',
  'calc': '{game}: calculadora de valor e informe de mercado', 'read': 'Leer', 'latest': 'Últimas noticias de {game}',
  'note': 'GameAccountValue no compra, vende ni intermedia cuentas. Las noticias resumen anuncios de las editoras solo con fines informativos.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: llegan Vesna y Vodyanitsa y se confirman las recompensas del aniversario',
   'desc': 'La versión 7.1, «Un réquiem para el Inframundo», salió el 23 de septiembre de 2026 con dos personajes de 5 estrellas, dos armas de 5 estrellas y recompensas del sexto aniversario.',
   'lead': 'HoYoverse lanzó la versión 7.1, «Un réquiem para el Inframundo», el 23 de septiembre de 2026; es también la actualización del sexto aniversario de Genshin Impact.',
   'new': ['Dos personajes nuevos de 5 estrellas: Vesna (Anemo, espada) y Vodyanitsa (Hydro, catalizador).',
           'Armas nuevas: Beyond the Chrysalis (espada de 5★), Hymn of the Maelstrom (catalizador de 5★) y New Bough (espada de 4★).',
           'Recompensas de aniversario anunciadas por HoYoverse: dos personajes de 5 estrellas para invitar, Destino entrelazado ×10, Protogemas ×1600 y el reinicio del bono de primera recarga de Cristales Génesis.',
           'El mantenimiento de la actualización empezó el 23 de septiembre a las 06:00 (UTC+8).'],
   'impact': 'El número de personajes de 5 estrellas limitados, sus constelaciones y sus armas exclusivas es uno de los principales factores de valor de una cuenta de Genshin según nuestra investigación. Los personajes regalados a todos por el aniversario hacen una cuenta menos distintiva que los de banners limitados.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, la primera dimensión nueva en más de 14 años, llegará a Java y Bedrock',
   'desc': 'Minecraft Live, el 26 de septiembre de 2026, presentó The Sift, una cuarta dimensión que llegará a Java y Bedrock el año que viene, además de Dungeons II y la actualización Wilderness Bound.',
   'lead': 'En Minecraft Live, el 26 de septiembre de 2026, Mojang Studios anunció que la cuarta dimensión del juego, The Sift, llegará a Minecraft Java y Bedrock Edition el año que viene.',
   'new': ['The Sift es la primera dimensión nueva en más de 14 años y se suma al Mundo Superior, el Nether y el End.',
           'Se estrena en Minecraft Dungeons II, que Mojang fechó para el 29 de septiembre de 2026.',
           'Minecraft World, un parque temático, abrirá en Londres en 2027.',
           'La actualización Wilderness Bound llegó el 15 de septiembre con el bosque moteado, camas de paja, campamentos abandonados y cojines.'],
   'impact': 'Las cuentas de Minecraft se valoran por el tipo (Java o Bedrock), el nombre de usuario y las capas, no por el contenido del juego. Actualizaciones como estas cambian lo que se puede hacer en el juego, no lo que vale una cuenta.'},
  'rbx-hunt': {
   'title': 'Roblox 20 «The Hunt»: objetos UGC limitados y exclusivos de Roblox Plus (17–28 de septiembre)',
   'desc': 'The Hunt: Roblox 20 se celebró del 17 al 28 de septiembre de 2026 con recompensas UGC, objetos UGC de lanzamiento limitado y tres objetos exclusivos para suscriptores de Roblox Plus.',
   'lead': 'Roblox celebró su 20.º aniversario con The Hunt: Roblox 20, un evento en toda la plataforma que se celebró del 17 al 28 de septiembre de 2026.',
   'new': ['Los jugadores recorrían 20 años de historia de Roblox, una misión por año, empezando en «Year Zero»; completar los 20 desbloqueaba «Year Infinity» con 20 juegos más.',
           'Las misiones daban objetos UGC y durante el evento hubo objetos UGC de lanzamiento limitado.',
           'Los suscriptores de Roblox Plus recibieron tres objetos virtuales exclusivos y conservan el tema clásico de la app, el fondo clásico del avatar y el marco de perfil después del evento.',
           'El tema clásico de la app fue gratis para todos mientras duró el evento.'],
   'impact': 'Los objetos que solo se podían conseguir durante un evento son una de las cosas que mira una tasación. Roblox no nombró esos objetos en su anuncio, así que este sitio no les pone precio hasta que existan anuncios de venta reales.'},
  'rbx-rdc': {
   'title': 'RDC 2026: los creadores de Roblox ganaron unos 1700 millones de dólares en un año; llega Roblox Wallet',
   'desc': 'En RDC 2026 Roblox informó de unos 1700 millones de dólares de ganancias de creadores en 12 meses y anunció Roblox Wallet y Roblox Card para los pagos.',
   'lead': 'En su conferencia de desarrolladores RDC 2026 (anuncio del 11 de septiembre de 2026), Roblox compartió cifras de ganancias de creadores y nuevas herramientas de pago.',
   'new': ['Los creadores han ganado más de 5000 millones de dólares desde el lanzamiento de DevEx en 2013, y unos 1700 millones en los 12 meses hasta el 30 de junio de 2026.',
           'Los incentivos de Roblox Plus generaron más de 300 millones de Robux para los creadores en sus primeros cuatro meses (hasta el 17 de agosto de 2026).',
           'Roblox Wallet, una cuenta de pagos con Airwallex US, ofrecerá pagos diarios en dinero real: primero para creadores independientes de EE. UU. mayores de 18 años que cumplan los requisitos, a finales de 2026, y en otros países en 2027.',
           'Está prevista una Roblox Card vinculada a Wallet a partir de 2027.'],
   'impact': 'Estos cambios afectan a los pagos a creadores, no a las cuentas de los jugadores: el anuncio no cambió los precios de los Robux, los objetos limitados ni el intercambio. El saldo de Robux y los objetos limitados siguen siendo lo que pondera nuestra calculadora de Roblox.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: cuatro armas nuevas para Clash Squad, Prime Diamond y rediseño de Kenta',
   'desc': 'Las notas del parche OB55 de Garena (10 de septiembre de 2026) añaden M7, Skorp, RPK y Hawk a Clash Squad desde el 1 de octubre, presentan Prime Diamond y rediseñan a Kenta.',
   'lead': 'Garena publicó las notas del parche OB55 de Free Fire el 10 de septiembre de 2026; los cambios de armas entran en vigor el 1 de octubre.',
   'new': ['Armas nuevas de Clash Squad desde el 1 de octubre: M7 (1600 CS Cash), Skorp (1500), RPK (1500) y Hawk (1700).',
           'Prime Diamond: diamantes según el gasto mensual, que se reclaman el mes siguiente tras cualquier recarga.',
           'Kenta se rediseña por completo; Morse, Luna y Wukong reciben cambios de equilibrio.',
           'Desde el 1 de octubre cambia la movilidad por clase de arma: subfusiles más rápidos, francotiradores y tiradores selectos más lentos.'],
   'impact': 'Nuestra calculadora de Free Fire pondera el saldo de diamantes y los lotes raros. OB55 cambia cómo se premian las recargas futuras; no cambia los objetos que ya tienen las cuentas.'},
  'cr-minion': {
   'title': 'Temporada «Minion Academy» de Clash Royale: nueva carta Esbirro Gigante y el héroe Mago de Hielo',
   'desc': 'La temporada Minion Academy (del 7 de septiembre al 5 de octubre de 2026) añade la carta Esbirro Gigante, un héroe Mago de Hielo y un evento de álbum con 1750 cartas de Esbirro Gigante.',
   'lead': 'Supercell abrió la temporada «Minion Academy» de Clash Royale, que dura del 7 de septiembre al 5 de octubre de 2026.',
   'new': ['Nueva carta Esbirro Gigante (Minion Giant): una carta de victoria voladora que ataca edificios y torres. Es gratis mediante el evento de álbum Academy Antics y no estará en los cofres hasta la próxima temporada.',
           'El evento de álbum da 1750 cartas de Esbirro Gigante, un emote y un aspecto de torre.',
           'Nuevo héroe: Mago de Hielo, desde el Pass Royale o por 200 monedas de héroe.',
           'Eventos: Liga 2c2 (7–21 de septiembre), torneo global Princess Gambit (21–26 de septiembre) y Royale Shuffle (21 de septiembre – 5 de octubre). Un empate en Campeón Definitivo ahora cuesta la mitad de trofeos que una derrota.'],
   'impact': 'Los aspectos de torre y emotes que solo se ofrecen durante un evento hacen más distintiva una colección de Clash Royale, mientras que el nivel de la Torre del Rey y el nivel de las cartas siguen siendo los principales factores de valor.'},
  'ml-10': {
   'title': 'Mobile Legends cumple 10 años: campaña ALL IN y nueva skin Coleccionista de Layla',
   'desc': 'La campaña ALL IN de MOONTON por el décimo aniversario (desde el 4 de septiembre de 2026) trae una nueva skin Épica de Nana, cofres de skins gratis y una skin Coleccionista de Layla desde el 9 de octubre.',
   'lead': 'MOONTON Games lanzó ALL IN, la campaña del décimo aniversario de Mobile Legends: Bang Bang, el 4 de septiembre de 2026.',
   'new': ['Pase de celebración del 10.º aniversario (4 de septiembre – 1 de noviembre): nueva skin Épica de Nana, un cofre de selección de skin Épica, un cofre de skin Épica aleatoria y una skin de aniversario gratis para jugadores que regresan.',
           'Anniversary Gala Weekend (25 de septiembre – 11 de octubre): acceso a 265 skins, EXP del Pase de Batalla y fragmentos de skin premium.',
           'Layla’s Stellar Gala (9 de octubre – 19 de noviembre): la nueva skin Coleccionista de Layla mediante el minijuego «Starfall Breakout».',
           'MOONTON cita más de 1500 millones de instalaciones y 110 millones de jugadores activos al mes.'],
   'impact': 'Las skins Coleccionista y Leyenda están entre los factores de valor más citados en las cuentas de Mobile Legends; las skins regaladas o de prueba no.'},
  'bs-aug': {
   'title': 'Brawl Stars: brawlers míticos Cosmo y Vince; el Camino de Starr pasa a ser Brawler Blast',
   'desc': 'Las notas de agosto de 2026 de Supercell (1 de septiembre) añaden dos brawlers míticos, convierten el Camino de Starr en Brawler Blast con nuevos costes en créditos y renombran Ultralegendario a Ultra.',
   'lead': 'Supercell publicó las notas de la actualización de agosto de 2026 de Brawl Stars el 1 de septiembre de 2026.',
   'new': ['Dos brawlers míticos nuevos: Cosmo (controlador) y Vince (daño).',
           'Nuevas hipercargas para Nori y Wendy.',
           'El Camino de Starr se convierte en «Brawler Blast»: los créditos ahora sirven para desbloquear por rareza — Especial 160, Superespecial 430, Épico 925, Mítico 1900, Legendario 3800, Ultra 5500.',
           'La rareza «Ultralegendario» pasa a llamarse «Ultra». Además, la temporada Royal Academy y un evento Brawl-O-Ween de todo el mes.'],
   'impact': 'Nuestra calculadora de Brawl Stars usa el número de brawlers, las hipercargas y los trofeos. Dos míticos más aumentan el número de brawlers que necesita una colección completa.'},
  'coc-aug': {
   'title': 'Actualización de agosto de Clash of Clans: niveles 11–15 de Diggy y Pase de Oro desde el Ayuntamiento 3',
   'desc': 'La actualización de agosto de 2026 de Supercell (30 de agosto) añade los niveles 11–15 de Diggy y nuevas supercargas en el Ayuntamiento 18, retira el Pase de Inicio y abre el Pase de Oro desde el Ayuntamiento 3.',
   'lead': 'Supercell publicó la actualización de agosto de Clash of Clans el 30 de agosto de 2026.',
   'new': ['Ayuntamiento 18: la mascota Diggy recibe los niveles 11–15; la Cabaña del Constructor y el Monolito reciben nuevos niveles de supercarga.',
           'Se retira el Pase de Inicio: los desafíos de temporada y el Pase de Oro están disponibles desde el Ayuntamiento 3, con recompensas según el nivel del ayuntamiento.',
           'El Caballero de las Ruinas ya no pierde vida con el tiempo; la Bruja de las Ruinas invoca 10 caballeros en lugar de 8.',
           'Se ajustaron los modificadores de la Liga de Guerras de Clanes en las ligas Titán.'],
   'impact': 'El nivel de ayuntamiento y los niveles de héroes y mascotas son los factores de valor de las cuentas de Clash of Clans según nuestra investigación. Los nuevos niveles máximos en el Ayuntamiento 18 hacen que una cuenta «al máximo» necesite ahora más mejoras que antes.'},
  'fn-c7s4': {
   'title': 'Fortnite Capítulo 7 Temporada 4 «Override»: pase de batalla de Sonic y colaboración con KINGDOM HEARTS',
   'desc': 'La temporada «Override» de Epic (Capítulo 7, Temporada 4) trae Consolas Override, un pase de batalla de 800 paVos encabezado por Sonic the Hedgehog y colaboraciones como KINGDOM HEARTS.',
   'lead': 'La Temporada 4 del Capítulo 7 de Fortnite se llama «Override». Epic la presenta como una temporada de colaboraciones con videojuegos y reglas que cambian para toda la partida.',
   'new': ['Las Consolas Override aparecen en todas las partidas y permiten cambiar las reglas para todo el servidor.',
           'El pase de batalla cuesta 800 paVos y lo encabeza Sonic the Hedgehog, con Tails como compañero.',
           'Quienes compraron el pase antes del 27 de agosto a las 23:59 (hora del este de EE. UU.) recibieron el traje Infiltrator Grace Crowne como bonificación de lanzamiento.',
           'Colaboraciones de la temporada: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot y Spyro the Dragon; entre las armas, Midas’ Masterpiece y el Mega Buster de Mega Man.'],
   'impact': 'Los trajes disponibles solo por tiempo limitado, como una bonificación de lanzamiento, son lo que distingue una taquilla rara de Fortnite de una común. Los trajes del pase de batalla quedan ligados a su temporada.'},
 }},
}
