# News translations: pt, id (from news_data.py 'en', facts unchanged)
TEXT = {
'pt': {
 'ui': {
  'news': 'Notícias', 'news_title': 'Notícias de jogos que afetam o valor da conta',
  'news_lead': 'Atualizações oficiais das publishers — cada uma conferida com o anúncio da própria publisher, com uma nota simples sobre o que ela significa para o valor da conta.',
  'game_title': 'Notícias de {game}', 'game_lead': 'Atualizações oficiais de {game} que afetam quanto vale uma conta. Cada matéria traz o link do anúncio da publisher.',
  'published': 'Publicado', 'source': 'Fonte oficial', 'by_on': '{pub}, {date}', 'whats_new': 'O que há de novo',
  'impact': 'O que isso significa para o valor da conta', 'more': 'Mais notícias de {game}', 'all': 'Todas as notícias',
  'calc': '{game}: calculadora de valor e relatório de mercado', 'read': 'Ler', 'latest': 'Últimas notícias de {game}',
  'note': 'O GameAccountValue não compra, vende nem intermedeia contas. As notícias resumem anúncios das publishers apenas para informação.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: chegam Vesna e Vodyanitsa, recompensas de aniversário confirmadas',
   'desc': 'A versão 7.1, “Um Réquiem para o Submundo”, saiu em 23 de setembro de 2026 com dois personagens 5 estrelas, duas armas 5 estrelas e recompensas do sexto aniversário.',
   'lead': 'A HoYoverse lançou a versão 7.1, “Um Réquiem para o Submundo”, em 23 de setembro de 2026 — a atualização que também traz o sexto aniversário de Genshin Impact.',
   'new': ['Dois novos personagens 5 estrelas: Vesna (Anemo, espada) e Vodyanitsa (Hydro, catalisador).',
           'Novas armas: Beyond the Chrysalis (espada 5★), Hymn of the Maelstrom (catalisador 5★) e New Bough (espada 4★).',
           'Recompensas de aniversário anunciadas pela HoYoverse: dois personagens 5 estrelas para convidar, Destino Entrelaçado ×10, Gemas Essenciais ×1.600 e a renovação do bônus da primeira recarga de Cristais Gênesis.',
           'A manutenção da atualização começou em 23 de setembro às 06:00 (UTC+8).'],
   'impact': 'A quantidade de personagens 5 estrelas limitados, suas constelações e armas exclusivas é um dos principais fatores de valor de uma conta de Genshin na nossa pesquisa. Personagens dados de graça a todos no aniversário deixam uma conta menos rara do que personagens de banners limitados.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, a primeira dimensão nova em mais de 14 anos, chega ao Java e ao Bedrock',
   'desc': 'O Minecraft Live de 26 de setembro de 2026 revelou The Sift, uma quarta dimensão que chega ao Java e ao Bedrock no ano que vem, além de Dungeons II e da atualização Wilderness Bound.',
   'lead': 'No Minecraft Live de 26 de setembro de 2026, a Mojang Studios anunciou que a quarta dimensão do jogo, The Sift, chegará ao Minecraft Java e Bedrock Edition no ano que vem.',
   'new': ['The Sift é a primeira dimensão nova em mais de 14 anos e se junta à Superfície, ao Nether e ao End.',
           'A estreia é em Minecraft Dungeons II, com lançamento marcado pela Mojang para 29 de setembro de 2026.',
           'O Minecraft World, uma atração temática, abre em Londres em 2027.',
           'A atualização Wilderness Bound chegou em 15 de setembro com a floresta salpicada, camas de palha, acampamentos abandonados e almofadas.'],
   'impact': 'Contas de Minecraft são avaliadas pelo tipo (Java ou Bedrock), pelo nome de usuário e pelas capas — não pelo conteúdo do jogo. Atualizações assim mudam o que dá para fazer no jogo, não quanto vale uma conta.'},
  'rbx-hunt': {
   'title': 'Roblox 20 “The Hunt”: itens UGC limitados e exclusivos do Roblox Plus (17 a 28 de setembro)',
   'desc': 'O The Hunt: Roblox 20 aconteceu de 17 a 28 de setembro de 2026 com recompensas UGC, itens UGC de lançamento limitado e três itens exclusivos para assinantes do Roblox Plus.',
   'lead': 'O Roblox comemorou 20 anos com o The Hunt: Roblox 20, um evento em toda a plataforma realizado de 17 a 28 de setembro de 2026.',
   'new': ['Os jogadores percorreram 20 anos de história do Roblox, uma missão por ano, começando no “Year Zero”; concluir os 20 liberava o “Year Infinity”, com mais 20 jogos.',
           'As missões davam itens UGC, e itens UGC de lançamento limitado ficaram disponíveis durante o evento.',
           'Assinantes do Roblox Plus receberam três itens virtuais exclusivos e mantêm o tema clássico do app, o fundo clássico do avatar e a moldura de perfil depois do evento.',
           'O tema clássico do app ficou grátis para todos durante o evento.'],
   'impact': 'Itens que só podiam ser obtidos durante um evento estão entre o que uma avaliação considera. O Roblox não nomeou esses itens no anúncio, então este site não dá preço a eles até existirem anúncios reais de venda.'},
  'rbx-rdc': {
   'title': 'RDC 2026: criadores do Roblox ganharam cerca de US$ 1,7 bilhão em um ano; Roblox Wallet anunciado',
   'desc': 'No RDC 2026, o Roblox informou cerca de US$ 1,7 bilhão em ganhos de criadores em 12 meses e anunciou o Roblox Wallet e o Roblox Card para pagamentos.',
   'lead': 'Na conferência de desenvolvedores RDC 2026 (anúncio de 11 de setembro de 2026), o Roblox divulgou números de ganhos dos criadores e novas ferramentas de pagamento.',
   'new': ['Os criadores ganharam mais de US$ 5 bilhões desde o lançamento do DevEx em 2013, e cerca de US$ 1,7 bilhão nos 12 meses até 30 de junho de 2026.',
           'Os incentivos do Roblox Plus geraram mais de 300 milhões de Robux em ganhos para criadores nos primeiros quatro meses (até 17 de agosto de 2026).',
           'O Roblox Wallet, conta de pagamentos feita com a Airwallex US, terá pagamentos diários em dinheiro real — primeiro para criadores independentes elegíveis dos EUA com 18+ ainda em 2026, e internacionalmente em 2027.',
           'Um Roblox Card ligado ao Wallet está previsto a partir de 2027.'],
   'impact': 'Essas mudanças são sobre pagamentos a criadores, não sobre contas de jogadores: o anúncio não mudou preços de Robux, itens limitados nem trocas. Saldo de Robux e itens limitados continuam sendo o que nossa calculadora de Roblox considera.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: quatro armas novas no Contra Squad, Prime Diamond e reformulação do Kenta',
   'desc': 'As notas do OB55 da Garena (10 de setembro de 2026) colocam M7, Skorp, RPK e Hawk no Contra Squad a partir de 1º de outubro, lançam o Prime Diamond e reformulam o Kenta.',
   'lead': 'A Garena publicou as notas da atualização OB55 de Free Fire em 10 de setembro de 2026; as mudanças de armas valem a partir de 1º de outubro.',
   'new': ['Armas novas no Contra Squad a partir de 1º de outubro: M7 (1.600 CS Cash), Skorp (1.500), RPK (1.500) e Hawk (1.700).',
           'Prime Diamond: diamantes ganhos de acordo com o gasto mensal, resgatáveis no mês seguinte após qualquer recarga.',
           'O Kenta foi totalmente reformulado; Morse, Luna e Wukong recebem ajustes de balanceamento.',
           'Mudanças de mobilidade por classe de arma a partir de 1º de outubro: SMGs mais rápidas, rifles de precisão e de atirador mais lentos.'],
   'impact': 'Nossa calculadora de Free Fire considera o saldo de diamantes e os pacotes raros. O OB55 muda como as recargas futuras são recompensadas; não muda os itens que já estão nas contas.'},
  'cr-minion': {
   'title': 'Temporada “Minion Academy” de Clash Royale: nova carta Servo Gigante e o herói Mago de Gelo',
   'desc': 'A temporada Minion Academy (7 de setembro a 5 de outubro de 2026) traz a carta Servo Gigante, o herói Mago de Gelo e um evento de álbum com 1.750 cartas de Servo Gigante.',
   'lead': 'A Supercell abriu a temporada “Minion Academy” de Clash Royale, que vai de 7 de setembro a 5 de outubro de 2026.',
   'new': ['Nova carta Servo Gigante (Minion Giant): uma condição de vitória voadora que mira construções e torres. Ela é grátis pelo evento de álbum Academy Antics e só aparecerá em baús na próxima temporada.',
           'O evento de álbum dá 1.750 cartas de Servo Gigante, um emote e uma skin de torre.',
           'Novo herói: Mago de Gelo, pela trilha do Pass Royale ou por 200 Moedas de Herói.',
           'Eventos: Liga 2v2 (7 a 21 de setembro), torneio global Princess Gambit (21 a 26 de setembro) e Royale Shuffle (21 de setembro a 5 de outubro). Um empate no Campeão Supremo agora custa metade dos troféus de uma derrota.'],
   'impact': 'Skins de torre e emotes oferecidos só durante um evento deixam uma coleção de Clash Royale mais rara, mas o nível da Torre do Rei e os níveis das cartas continuam sendo os principais fatores de valor.'},
  'ml-10': {
   'title': 'Mobile Legends faz 10 anos: campanha ALL IN e nova skin Colecionador da Layla',
   'desc': 'A campanha ALL IN da MOONTON pelos 10 anos (desde 4 de setembro de 2026) traz uma nova skin Épica da Nana, baús de skins grátis e uma skin Colecionador da Layla a partir de 9 de outubro.',
   'lead': 'A MOONTON Games lançou em 4 de setembro de 2026 o ALL IN, campanha de dez anos de Mobile Legends: Bang Bang.',
   'new': ['Passe de Celebração de 10 anos (4 de setembro a 1º de novembro): nova skin Épica da Nana, um Baú de Seleção de Skin Épica, um Baú de Skin Épica Aleatória e uma skin de aniversário grátis para quem volta a jogar.',
           'Anniversary Gala Weekend (25 de setembro a 11 de outubro): acesso a 265 skins, EXP do Passe de Batalha e Fragmentos de Skin Premium.',
           'Layla’s Stellar Gala (9 de outubro a 19 de novembro): a nova skin Colecionador da Layla pelo minijogo “Starfall Breakout”.',
           'A MOONTON cita mais de 1,5 bilhão de instalações e 110 milhões de jogadores ativos por mês.'],
   'impact': 'Skins Colecionador e Lenda estão entre os fatores de valor mais citados em contas de Mobile Legends; skins dadas de graça ou em teste não.'},
  'bs-aug': {
   'title': 'Brawl Stars: brawlers míticos Cosmo e Vince; a Trilha da Starr vira Brawler Blast',
   'desc': 'As notas de agosto de 2026 da Supercell (1º de setembro) trazem dois brawlers míticos, transformam a Trilha da Starr em Brawler Blast com novos custos em créditos e renomeiam Ultralendário para Ultra.',
   'lead': 'A Supercell publicou as notas da atualização de agosto de 2026 de Brawl Stars em 1º de setembro de 2026.',
   'new': ['Dois brawlers míticos novos: Cosmo (controlador) e Vince (dano).',
           'Novas hipercargas para Nori e Wendy.',
           'A Trilha da Starr virou “Brawler Blast”: os créditos agora servem para desbloquear por raridade — Raro 160, Super Raro 430, Épico 925, Mítico 1.900, Lendário 3.800, Ultra 5.500.',
           'A raridade “Ultralendário” passa a se chamar “Ultra”. Além da temporada Royal Academy e de um evento Brawl-O-Ween de um mês inteiro.'],
   'impact': 'Nossa calculadora de Brawl Stars usa a quantidade de brawlers, as hipercargas e os troféus. Mais dois míticos aumentam o número de brawlers que uma coleção completa exige.'},
  'coc-aug': {
   'title': 'Atualização de agosto de Clash of Clans: níveis 11–15 do Diggy e Passe Dourado desde o CV 3',
   'desc': 'A atualização de agosto de 2026 da Supercell (30 de agosto) traz os níveis 11–15 do Diggy e novas supercargas no CV 18, aposenta o Passe Inicial e libera o Passe Dourado a partir do CV 3.',
   'lead': 'A Supercell lançou a atualização de agosto de Clash of Clans em 30 de agosto de 2026.',
   'new': ['Centro de Vila 18: o pet Diggy ganha os níveis 11–15; a Cabana do Construtor e o Monólito ganham novos níveis de supercarga.',
           'O Passe Inicial foi aposentado: os Desafios da Temporada e o Passe Dourado agora ficam disponíveis a partir do CV 3, com recompensas conforme o nível do Centro de Vila.',
           'O Cavaleiro das Ruínas não perde mais vida com o tempo; a Bruxa das Ruínas invoca 10 cavaleiros em vez de 8.',
           'Os modificadores da Liga de Guerras de Clãs nas ligas Titã foram ajustados.'],
   'impact': 'O nível do Centro de Vila e os níveis de heróis e pets são os fatores de valor das contas de Clash of Clans na nossa pesquisa. Os novos níveis máximos no CV 18 fazem uma conta “maxada” precisar de mais melhorias do que antes.'},
  'fn-c7s4': {
   'title': 'Fortnite Capítulo 7 Temporada 4 “Override”: Passe de Batalha do Sonic e crossover com KINGDOM HEARTS',
   'desc': 'A temporada “Override” da Epic (Capítulo 7, Temporada 4) traz os Consoles Override, um Passe de Batalha de 800 V-Bucks liderado por Sonic the Hedgehog e crossovers como KINGDOM HEARTS.',
   'lead': 'A Temporada 4 do Capítulo 7 de Fortnite se chama “Override”. A Epic descreve uma temporada de crossovers com games e regras que mudam para a partida inteira.',
   'new': ['Os Consoles Override aparecem em todas as partidas e deixam os jogadores mudar as regras para o servidor todo.',
           'O Passe de Batalha custa 800 V-Bucks e é liderado por Sonic the Hedgehog, com Tails como Parceiro.',
           'Quem comprou o Passe antes de 27 de agosto às 23:59 (horário do leste dos EUA) ganhou o traje Infiltrator Grace Crowne como bônus da semana de lançamento.',
           'Crossovers da temporada: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot e Spyro the Dragon; entre as armas, Midas’ Masterpiece e o Mega Buster do Mega Man.'],
   'impact': 'Trajes disponíveis só por tempo limitado — como um bônus de lançamento — é o que separa armários raros de Fortnite dos comuns. Trajes do Passe de Batalha continuam ligados à temporada de origem.'},
 }},
'id': {
 'ui': {
  'news': 'Berita', 'news_title': 'Berita game yang memengaruhi nilai akun',
  'news_lead': 'Pembaruan resmi dari penerbit game — masing-masing dicek dengan pengumuman penerbitnya sendiri, disertai catatan singkat tentang artinya bagi nilai akun.',
  'game_title': 'Berita {game}', 'game_lead': 'Pembaruan resmi {game} yang memengaruhi nilai sebuah akun. Setiap artikel menautkan pengumuman penerbit.',
  'published': 'Diterbitkan', 'source': 'Sumber resmi', 'by_on': '{pub}, {date}', 'whats_new': 'Apa yang baru',
  'impact': 'Artinya bagi nilai akun', 'more': 'Berita {game} lainnya', 'all': 'Semua berita',
  'calc': '{game}: kalkulator nilai dan laporan pasar', 'read': 'Baca', 'latest': 'Berita {game} terbaru',
  'note': 'GameAccountValue tidak membeli, menjual, atau menjadi perantara akun. Berita dirangkum dari pengumuman penerbit hanya sebagai informasi.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna dan Vodyanitsa hadir, hadiah anniversary dikonfirmasi',
   'desc': 'Versi 7.1 "A Rekviem for the Underworld" rilis 23 September 2026 dengan dua karakter bintang 5 baru, dua senjata bintang 5, dan hadiah anniversary keenam.',
   'lead': 'HoYoverse merilis Versi 7.1, "A Rekviem for the Underworld", pada 23 September 2026 — pembaruan yang sekaligus membawa anniversary keenam Genshin Impact.',
   'new': ['Dua karakter bintang 5 baru: Vesna (Anemo, pedang) dan Vodyanitsa (Hydro, katalis).',
           'Senjata baru: Beyond the Chrysalis (pedang bintang 5), Hymn of the Maelstrom (katalis bintang 5), dan New Bough (pedang bintang 4).',
           'Hadiah anniversary yang diumumkan HoYoverse: dua karakter bintang 5 untuk diundang, Intertwined Fate ×10, Primogem ×1.600, dan reset bonus top-up pertama Genesis Crystal.',
           'Maintenance pembaruan dimulai 23 September pukul 06.00 (UTC+8).'],
   'impact': 'Jumlah karakter bintang 5 limited, konstelasinya, dan senjata khasnya adalah salah satu pendorong utama nilai akun Genshin dalam riset kami. Karakter yang diberikan gratis ke semua pemain saat anniversary membuat akun kurang istimewa dibanding karakter dari banner limited.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, dimensi baru pertama dalam lebih dari 14 tahun, hadir di Java dan Bedrock',
   'desc': 'Minecraft Live pada 26 September 2026 mengungkap The Sift, dimensi keempat yang hadir di Java dan Bedrock tahun depan, plus Dungeons II dan update Wilderness Bound.',
   'lead': 'Di Minecraft Live pada 26 September 2026, Mojang Studios mengumumkan bahwa dimensi keempat game ini, The Sift, akan hadir di Minecraft Java dan Bedrock Edition tahun depan.',
   'new': ['The Sift adalah dimensi baru pertama dalam lebih dari 14 tahun, bergabung dengan Overworld, Nether, dan End.',
           'Dimensi ini debut di Minecraft Dungeons II, yang dijadwalkan Mojang rilis 29 September 2026.',
           'Minecraft World, atraksi bertema, dibuka di London pada 2027.',
           'Update Wilderness Bound hadir 15 September dengan hutan belang, kasur jerami, kemah terbengkalai, dan bantal duduk.'],
   'impact': 'Akun Minecraft dinilai dari jenisnya (Java atau Bedrock), nama pengguna, dan cape — bukan dari konten dalam game. Update seperti ini mengubah apa yang bisa dilakukan pemain, bukan nilai akunnya.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": item UGC terbatas dan eksklusif Roblox Plus (17–28 September)',
   'desc': 'The Hunt: Roblox 20 berlangsung 17–28 September 2026 dengan hadiah UGC, item UGC rilis terbatas, dan tiga item eksklusif untuk pelanggan Roblox Plus.',
   'lead': 'Roblox merayakan ulang tahun ke-20 dengan The Hunt: Roblox 20, event di seluruh platform yang berlangsung 17–28 September 2026.',
   'new': ['Pemain menelusuri 20 tahun sejarah Roblox, satu misi per tahun, dimulai dari "Year Zero"; menyelesaikan ke-20 tahun membuka "Year Infinity" dengan 20 game tambahan.',
           'Misi memberikan item UGC, dan item UGC rilis terbatas tersedia selama event.',
           'Pelanggan Roblox Plus mendapat tiga item virtual eksklusif dan tetap memiliki tema aplikasi Classic, latar avatar klasik, dan bingkai profil setelah event.',
           'Tema aplikasi Classic gratis untuk semua orang selama event berlangsung.'],
   'impact': 'Item yang hanya bisa didapat selama event termasuk hal yang diperhatikan dalam penaksiran. Roblox tidak menyebut nama item-item itu dalam pengumumannya, jadi situs ini belum memberi harga sampai ada listing nyata.'},
  'rbx-rdc': {
   'title': 'RDC 2026: kreator Roblox meraup sekitar $1,7 miliar dalam setahun; Roblox Wallet diumumkan',
   'desc': 'Di RDC 2026 Roblox melaporkan pendapatan kreator sekitar $1,7 miliar dalam 12 bulan dan mengumumkan Roblox Wallet serta Roblox Card untuk pembayaran.',
   'lead': 'Di konferensi developer RDC 2026 (pengumuman 11 September 2026), Roblox membagikan angka pendapatan kreator dan alat pembayaran baru.',
   'new': ['Kreator telah meraup lebih dari $5 miliar sejak DevEx diluncurkan pada 2013, dan sekitar $1,7 miliar dalam 12 bulan hingga 30 Juni 2026.',
           'Insentif Roblox Plus menghasilkan lebih dari 300 juta Robux untuk kreator dalam empat bulan pertama (hingga 17 Agustus 2026).',
           'Roblox Wallet, akun pembayaran bersama Airwallex US, akan memberi pembayaran harian dalam uang sungguhan — pertama untuk kreator independen AS berusia 18+ yang memenuhi syarat akhir 2026, dan internasional pada 2027.',
           'Roblox Card yang terhubung ke Wallet direncanakan mulai 2027.'],
   'impact': 'Perubahan ini soal pembayaran kreator, bukan akun pemain: pengumuman ini tidak mengubah harga Robux, item limited, atau trading. Saldo Robux dan item limited tetap menjadi yang diperhitungkan kalkulator Roblox kami.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: empat senjata baru Clash Squad, Prime Diamond, dan rework Kenta',
   'desc': 'Patch notes OB55 dari Garena (10 September 2026) menambahkan M7, Skorp, RPK, dan Hawk ke Clash Squad mulai 1 Oktober, memperkenalkan Prime Diamond, dan me-rework Kenta.',
   'lead': 'Garena merilis patch notes OB55 Free Fire pada 10 September 2026; perubahan senjata berlaku mulai 1 Oktober.',
   'new': ['Senjata baru Clash Squad mulai 1 Oktober: M7 (1.600 CS Cash), Skorp (1.500), RPK (1.500), dan Hawk (1.700).',
           'Prime Diamond: diamond didapat sesuai pengeluaran bulanan, bisa diklaim bulan berikutnya setelah top-up apa pun.',
           'Kenta di-rework total; Morse, Luna, dan Wukong mendapat penyesuaian balance.',
           'Perubahan mobilitas per kelas senjata mulai 1 Oktober: SMG lebih cepat, sniper dan marksman rifle lebih lambat.'],
   'impact': 'Kalkulator Free Fire kami memperhitungkan saldo diamond dan bundle langka. OB55 mengubah cara top-up berikutnya diberi hadiah; item yang sudah ada di akun tidak berubah.'},
  'cr-minion': {
   'title': 'Season "Minion Academy" Clash Royale: kartu baru Minion Giant dan hero Ice Wizard',
   'desc': 'Season Minion Academy (7 September – 5 Oktober 2026) menambahkan kartu Minion Giant, hero Ice Wizard, dan event album berisi 1.750 kartu Minion Giant.',
   'lead': 'Supercell membuka season Clash Royale "Minion Academy" yang berlangsung 7 September sampai 5 Oktober 2026.',
   'new': ['Kartu baru Minion Giant: win condition terbang yang menyerang bangunan dan tower. Kartu ini gratis lewat event album Academy Antics dan baru muncul di chest season depan.',
           'Event album memberi 1.750 kartu Minion Giant, emote, dan skin tower.',
           'Hero baru: Ice Wizard, dari jalur Pass Royale atau seharga 200 Hero Coin.',
           'Event: Liga 2v2 (7–21 September), turnamen global Princess Gambit (21–26 September), dan Royale Shuffle (21 September – 5 Oktober). Hasil seri di Ultimate Champion kini hanya memotong setengah trofi dibanding kalah.'],
   'impact': 'Skin tower dan emote yang hanya ditawarkan saat event membuat koleksi Clash Royale lebih istimewa, sementara level King Tower dan level kartu tetap menjadi pendorong nilai utama.'},
  'ml-10': {
   'title': 'Mobile Legends berusia 10 tahun: kampanye ALL IN dan skin Collector baru Layla',
   'desc': 'Kampanye ALL IN MOONTON untuk ulang tahun ke-10 (mulai 4 September 2026) membawa skin Epic baru Nana, chest skin gratis, dan skin Collector Layla mulai 9 Oktober.',
   'lead': 'MOONTON Games meluncurkan ALL IN, kampanye ulang tahun ke-10 Mobile Legends: Bang Bang, pada 4 September 2026.',
   'new': ['10th Anniversary Celebration Pass (4 September – 1 November): skin Epic baru Nana, Epic Skin Selection Chest, Random Epic Skin Chest, dan skin anniversary gratis untuk pemain yang kembali.',
           'Anniversary Gala Weekend (25 September – 11 Oktober): akses ke 265 skin, EXP Battle Pass, dan Premium Skin Fragment.',
           'Layla’s Stellar Gala (9 Oktober – 19 November): skin Collector baru Layla lewat mini-game "Starfall Breakout".',
           'MOONTON menyebut lebih dari 1,5 miliar instalasi dan 110 juta pemain aktif bulanan.'],
   'impact': 'Skin Collector dan Legend termasuk pendorong nilai yang paling sering disebut untuk akun Mobile Legends; skin yang dibagikan gratis atau hanya trial tidak.'},
  'bs-aug': {
   'title': 'Brawl Stars: brawler Mythic Cosmo dan Vince; Starr Road menjadi Brawler Blast',
   'desc': 'Release notes Agustus 2026 dari Supercell (1 September) menambahkan dua brawler Mythic, mengubah Starr Road menjadi Brawler Blast dengan biaya kredit baru, dan mengganti nama Ultra Legendary menjadi Ultra.',
   'lead': 'Supercell merilis release notes update Agustus 2026 Brawl Stars pada 1 September 2026.',
   'new': ['Dua brawler Mythic baru: Cosmo (Controller) dan Vince (Damage Dealer).',
           'Hypercharge baru untuk Nori dan Wendy.',
           'Starr Road diubah menjadi "Brawler Blast": kredit kini dipakai untuk membuka brawler berdasarkan rarity — Rare 160, Super Rare 430, Epic 925, Mythic 1.900, Legendary 3.800, Ultra 5.500.',
           'Rarity "Ultra Legendary" berganti nama menjadi "Ultra". Plus season Royal Academy dan event Brawl-O-Ween selama sebulan penuh.'],
   'impact': 'Kalkulator Brawl Stars kami memakai jumlah brawler, hypercharge, dan trofi. Dua Mythic tambahan menaikkan jumlah brawler yang dibutuhkan untuk koleksi lengkap.'},
  'coc-aug': {
   'title': 'Update Agustus Clash of Clans: level Diggy 11–15 dan Gold Pass mulai Town Hall 3',
   'desc': 'Update Agustus 2026 dari Supercell (30 Agustus) menambahkan level Diggy 11–15 dan supercharge baru di Town Hall 18, menghapus Starter Pass, dan membuka Gold Pass mulai Town Hall 3.',
   'lead': 'Supercell merilis update Agustus Clash of Clans pada 30 Agustus 2026.',
   'new': ['Town Hall 18: pet Diggy mendapat level 11–15; Builder’s Hut dan Monolith mendapat level supercharge baru.',
           'Starter Pass dihapus: Season Challenge dan Gold Pass kini tersedia mulai Town Hall 3, dengan hadiah menyesuaikan level Town Hall.',
           'Ruin Knight tidak lagi kehilangan HP seiring waktu; Ruin Witch memanggil 10 Ruin Knight, bukan 8.',
           'Modifier Clan War League di liga Titan disesuaikan.'],
   'impact': 'Level Town Hall serta level hero dan pet adalah pendorong nilai akun Clash of Clans dalam riset kami. Level maksimum baru di Town Hall 18 berarti akun "max" kini butuh lebih banyak upgrade dibanding sebelum update.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 "Override": Battle Pass Sonic dan crossover KINGDOM HEARTS',
   'desc': 'Season "Override" dari Epic (Chapter 7 Season 4) menghadirkan Override Console, Battle Pass 800 V-Bucks yang dipimpin Sonic the Hedgehog, dan crossover termasuk KINGDOM HEARTS.',
   'lead': 'Chapter 7 Season 4 Fortnite bernama "Override". Epic menggambarkannya sebagai season penuh crossover game dan perubahan aturan untuk seluruh match.',
   'new': ['Override Console muncul di setiap match dan memungkinkan pemain mengubah aturan untuk seluruh server.',
           'Battle Pass seharga 800 V-Bucks dengan Sonic the Hedgehog sebagai bintang utama, ditemani Tails Sidekick.',
           'Pemain yang membeli Pass sebelum 27 Agustus pukul 23.59 waktu timur AS mendapat outfit Infiltrator Grace Crowne sebagai bonus minggu peluncuran.',
           'Crossover season ini: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot, dan Spyro the Dragon; senjatanya antara lain Midas’ Masterpiece dan Mega Buster milik Mega Man.'],
   'impact': 'Outfit yang hanya tersedia dalam waktu terbatas — seperti bonus minggu peluncuran — adalah yang membedakan locker Fortnite langka dari yang biasa. Outfit Battle Pass tetap terikat pada season asalnya.'},
 }},
}
