# News translations: ms, uz (from news_data.py 'en', facts unchanged)
TEXT = {
'ms': {
 'ui': {
  'news': 'Berita', 'news_title': 'Berita permainan yang menjejaskan nilai akaun',
  'news_lead': 'Kemas kini rasmi daripada penerbit permainan — setiap satu disemak dengan pengumuman penerbit itu sendiri, bersama nota ringkas tentang maksudnya bagi nilai akaun.',
  'game_title': 'Berita {game}', 'game_lead': 'Kemas kini rasmi {game} yang menjejaskan nilai sesebuah akaun. Setiap artikel memautkan pengumuman penerbit.',
  'published': 'Diterbitkan', 'source': 'Sumber rasmi', 'by_on': '{pub}, {date}', 'whats_new': 'Apa yang baharu',
  'impact': 'Maksudnya bagi nilai akaun', 'more': 'Lagi berita {game}', 'all': 'Semua berita',
  'calc': '{game}: kalkulator nilai dan laporan pasaran', 'read': 'Baca', 'latest': 'Berita {game} terkini',
  'note': 'GameAccountValue tidak membeli, menjual atau menjadi orang tengah akaun. Berita diringkaskan daripada pengumuman penerbit untuk maklumat sahaja.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna dan Vodyanitsa tiba, ganjaran ulang tahun disahkan',
   'desc': 'Versi 7.1 "A Rekviem for the Underworld" dilancarkan pada 23 September 2026 dengan dua watak 5 bintang baharu, dua senjata 5 bintang dan ganjaran ulang tahun keenam.',
   'lead': 'HoYoverse melancarkan Versi 7.1, "A Rekviem for the Underworld", pada 23 September 2026 — kemas kini yang turut membawa ulang tahun keenam Genshin Impact.',
   'new': ['Dua watak 5 bintang baharu: Vesna (Anemo, pedang) dan Vodyanitsa (Hydro, katalis).',
           'Senjata baharu: Beyond the Chrysalis (pedang 5 bintang), Hymn of the Maelstrom (katalis 5 bintang) dan New Bough (pedang 4 bintang).',
           'Ganjaran ulang tahun yang diumumkan HoYoverse: dua watak 5 bintang untuk dijemput, Intertwined Fate ×10, Primogem ×1,600 dan set semula bonus tambah nilai pertama Genesis Crystal.',
           'Penyelenggaraan kemas kini bermula pada 23 September jam 06:00 (UTC+8).'],
   'impact': 'Dalam penyelidikan kami, bilangan watak 5 bintang terhad, konstelasi dan senjata khas mereka antara pemacu utama nilai akaun Genshin. Watak yang diberi percuma kepada semua pemain sempena ulang tahun tidak menjadikan akaun seistimewa watak daripada sepanduk terhad.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, dimensi baharu pertama dalam lebih 14 tahun, bakal tiba di Java dan Bedrock',
   'desc': 'Minecraft Live pada 26 September 2026 memperkenalkan The Sift, dimensi keempat yang tiba di Java dan Bedrock tahun depan, serta Dungeons II dan kemas kini Wilderness Bound.',
   'lead': 'Di Minecraft Live pada 26 September 2026, Mojang Studios mengumumkan bahawa dimensi keempat permainan ini, The Sift, akan tiba di Minecraft Java dan Bedrock Edition tahun depan.',
   'new': ['The Sift ialah dimensi baharu pertama dalam lebih 14 tahun, menyertai Overworld, Nether dan End.',
           'Ia mula muncul dalam Minecraft Dungeons II, yang ditetapkan Mojang pada 29 September 2026.',
           'Minecraft World, tarikan bertema, akan dibuka di London pada 2027.',
           'Kemas kini Wilderness Bound tiba pada 15 September dengan hutan bertompok, katil jerami, kem terbiar dan kusyen.'],
   'impact': 'Akaun Minecraft dinilai mengikut jenis (Java atau Bedrock), nama pengguna dan jubah (cape) — bukan kandungan dalam permainan. Kemas kini seperti ini mengubah apa yang boleh dilakukan pemain, bukan nilai akaun.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": item UGC terhad dan eksklusif Roblox Plus (17–28 September)',
   'desc': 'The Hunt: Roblox 20 berlangsung dari 17 hingga 28 September 2026 dengan ganjaran UGC, item UGC keluaran terhad dan tiga item eksklusif untuk pelanggan Roblox Plus.',
   'lead': 'Roblox meraikan ulang tahun ke-20 dengan The Hunt: Roblox 20, acara di seluruh platform yang berlangsung dari 17 hingga 28 September 2026.',
   'new': ['Pemain melalui 20 tahun sejarah Roblox, satu misi setiap tahun, bermula dari "Year Zero"; menamatkan kesemua 20 membuka "Year Infinity" dengan 20 lagi permainan.',
           'Misi memberikan item UGC, dan item UGC keluaran terhad tersedia sepanjang acara.',
           'Pelanggan Roblox Plus menerima tiga item maya eksklusif dan kekal memiliki tema aplikasi Classic, latar avatar klasik dan bingkai profil selepas acara.',
           'Tema aplikasi Classic percuma untuk semua sepanjang acara.'],
   'impact': 'Item yang hanya boleh diperoleh semasa acara ialah antara perkara yang dilihat dalam penilaian. Roblox tidak menamakan item tersebut dalam pengumumannya, jadi laman ini tidak meletakkan harga sehingga wujud senarai jualan sebenar.'},
  'rbx-rdc': {
   'title': 'RDC 2026: pencipta Roblox meraih kira-kira $1.7 bilion setahun; Roblox Wallet diumumkan',
   'desc': 'Di RDC 2026 Roblox melaporkan pendapatan pencipta kira-kira $1.7 bilion dalam 12 bulan dan mengumumkan Roblox Wallet serta Roblox Card untuk pembayaran.',
   'lead': 'Di persidangan pembangun RDC 2026 (pengumuman 11 September 2026), Roblox berkongsi angka pendapatan pencipta dan alat pembayaran baharu.',
   'new': ['Pencipta telah meraih lebih $5 bilion sejak DevEx dilancarkan pada 2013, dan kira-kira $1.7 bilion dalam 12 bulan hingga 30 Jun 2026.',
           'Insentif Roblox Plus menjana lebih 300 juta Robux pendapatan pencipta dalam empat bulan pertama (hingga 17 Ogos 2026).',
           'Roblox Wallet, akaun pembayaran yang dikendalikan bersama Airwallex US, akan membuat bayaran harian dalam mata wang sebenar — mula-mula untuk pencipta bebas AS berumur 18+ yang layak pada akhir 2026, dan di peringkat antarabangsa pada 2027.',
           'Roblox Card yang dipautkan kepada Wallet dirancang mulai 2027.'],
   'impact': 'Perubahan ini berkaitan bayaran kepada pencipta, bukan akaun pemain: pengumuman ini tidak mengubah harga Robux, item terhad atau dagangan. Baki Robux dan item terhad kekal sebagai apa yang ditimbang oleh kalkulator Roblox kami.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: empat senjata baharu Clash Squad, Prime Diamond dan olah semula Kenta',
   'desc': 'Nota tampalan OB55 Garena (10 September 2026) menambah M7, Skorp, RPK dan Hawk ke Clash Squad mulai 1 Oktober, memperkenalkan Prime Diamond dan mengolah semula Kenta.',
   'lead': 'Garena menerbitkan nota tampalan OB55 Free Fire pada 10 September 2026; perubahan senjata berkuat kuasa pada 1 Oktober.',
   'new': ['Senjata baharu Clash Squad mulai 1 Oktober: M7 (1,600 CS Cash), Skorp (1,500), RPK (1,500) dan Hawk (1,700).',
           'Prime Diamond: berlian diperoleh mengikut perbelanjaan bulanan, boleh dituntut pada bulan berikutnya selepas sebarang tambah nilai.',
           'Kenta diolah semula sepenuhnya; Morse, Luna dan Wukong menerima pelarasan keseimbangan.',
           'Pergerakan mengikut kelas senjata berubah mulai 1 Oktober: SMG lebih pantas, senapang tembak tepat dan marksman lebih perlahan.'],
   'impact': 'Kalkulator Free Fire kami menimbang baki berlian dan bundle yang jarang ditemui. OB55 mengubah cara tambah nilai akan datang diberi ganjaran; ia tidak mengubah item yang sudah ada dalam akaun.'},
  'cr-minion': {
   'title': 'Musim "Minion Academy" Clash Royale: kad baharu Minion Giant dan wira Ice Wizard',
   'desc': 'Musim Minion Academy (7 September – 5 Oktober 2026) menambah kad Minion Giant, wira Ice Wizard dan acara album yang memberi 1,750 kad Minion Giant.',
   'lead': 'Supercell membuka musim Clash Royale "Minion Academy", berlangsung dari 7 September hingga 5 Oktober 2026.',
   'new': ['Kad baharu Minion Giant: syarat kemenangan yang terbang dan menyasarkan bangunan serta menara. Ia percuma melalui acara album Academy Antics dan hanya akan muncul dalam peti pada musim depan.',
           'Acara album memberi 1,750 kad Minion Giant, satu emote dan satu kulit menara.',
           'Wira baharu: Ice Wizard, daripada laluan Pass Royale atau dengan 200 Hero Coin.',
           'Acara: Liga 2v2 (7–21 September), kejohanan global Princess Gambit (21–26 September) dan Royale Shuffle (21 September – 5 Oktober). Keputusan seri dalam Ultimate Champion kini hanya menolak separuh trofi berbanding kalah.'],
   'impact': 'Kulit menara dan emote yang hanya ditawarkan semasa acara menjadikan koleksi Clash Royale lebih istimewa, tetapi tahap King Tower dan tahap kad kekal sebagai pemacu nilai utama.'},
  'ml-10': {
   'title': 'Mobile Legends genap 10 tahun: kempen ALL IN dan kulit Collector baharu Layla',
   'desc': 'Kempen ALL IN ulang tahun ke-10 MOONTON (mulai 4 September 2026) membawa kulit Epic baharu Nana, peti kulit percuma dan kulit Collector Layla mulai 9 Oktober.',
   'lead': 'MOONTON Games melancarkan ALL IN, kempen ulang tahun ke-10 Mobile Legends: Bang Bang, pada 4 September 2026.',
   'new': ['Pas Sambutan Ulang Tahun ke-10 (4 September – 1 November): kulit Epic baharu Nana, Epic Skin Selection Chest, Random Epic Skin Chest dan kulit ulang tahun percuma untuk pemain yang kembali.',
           'Anniversary Gala Weekend (25 September – 11 Oktober): akses kepada 265 kulit, EXP Battle Pass dan Serpihan Kulit Premium.',
           'Layla’s Stellar Gala (9 Oktober – 19 November): kulit Collector baharu Layla melalui permainan mini "Starfall Breakout".',
           'MOONTON menyebut lebih 1.5 bilion pemasangan dan 110 juta pemain aktif bulanan.'],
   'impact': 'Kulit Collector dan Legend antara pemacu nilai yang paling kerap disebut bagi akaun Mobile Legends; kulit yang diberi percuma atau percubaan tidak.'},
  'bs-aug': {
   'title': 'Brawl Stars: brawler Mythic Cosmo dan Vince; Starr Road menjadi Brawler Blast',
   'desc': 'Nota keluaran Ogos 2026 Supercell (1 September) menambah dua brawler Mythic, menukar Starr Road kepada Brawler Blast dengan kos kredit baharu dan menamakan semula Ultra Legendary kepada Ultra.',
   'lead': 'Supercell menerbitkan nota keluaran kemas kini Ogos 2026 Brawl Stars pada 1 September 2026.',
   'new': ['Dua brawler Mythic baharu: Cosmo (Controller) dan Vince (Damage Dealer).',
           'Hypercharge baharu untuk Nori dan Wendy.',
           'Starr Road diolah semula menjadi "Brawler Blast": kredit kini digunakan untuk membuka kunci mengikut kejarangan — Rare 160, Super Rare 430, Epic 925, Mythic 1,900, Legendary 3,800, Ultra 5,500.',
           'Kejarangan "Ultra Legendary" dinamakan semula "Ultra". Turut ada musim Royal Academy dan acara Brawl-O-Ween sebulan penuh.'],
   'impact': 'Kalkulator Brawl Stars kami menggunakan bilangan brawler, Hypercharge dan trofi. Dua lagi Mythic menambah bilangan brawler yang diperlukan untuk koleksi lengkap.'},
  'coc-aug': {
   'title': 'Kemas kini Ogos Clash of Clans: tahap Diggy 11–15 dan Gold Pass mulai Town Hall 3',
   'desc': 'Kemas kini Ogos 2026 Supercell (30 Ogos) menambah tahap Diggy 11–15 dan supercharge baharu di Town Hall 18, menghapuskan Starter Pass dan membuka Gold Pass mulai Town Hall 3.',
   'lead': 'Supercell melancarkan kemas kini Ogos Clash of Clans pada 30 Ogos 2026.',
   'new': ['Town Hall 18: haiwan peliharaan Diggy mendapat tahap 11–15; Builder’s Hut dan Monolith mendapat tahap supercharge baharu.',
           'Starter Pass dihapuskan: Season Challenge dan Gold Pass kini tersedia mulai Town Hall 3, dengan ganjaran mengikut tahap Town Hall.',
           'Ruin Knight tidak lagi kehilangan nyawa dari semasa ke semasa; Ruin Witch memanggil 10 Ruin Knight dan bukan 8.',
           'Pengubah suai Clan War League dalam liga Titan dilaraskan.'],
   'impact': 'Dalam penyelidikan kami, tahap Town Hall serta tahap wira dan haiwan peliharaan menentukan nilai akaun Clash of Clans. Tahap maksimum baharu di Town Hall 18 bermakna akaun "maks" kini memerlukan lebih banyak naik taraf berbanding sebelum kemas kini.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 "Override": Battle Pass Sonic dan kolaborasi KINGDOM HEARTS',
   'desc': 'Musim "Override" Epic (Chapter 7, Season 4) membawa Override Console, Battle Pass 800 V-Bucks yang diketuai Sonic the Hedgehog dan kolaborasi termasuk KINGDOM HEARTS.',
   'lead': 'Chapter 7 Season 4 Fortnite dinamakan "Override". Epic menggambarkannya sebagai musim kolaborasi permainan dan perubahan peraturan untuk seluruh perlawanan.',
   'new': ['Override Console muncul dalam setiap perlawanan dan membolehkan pemain mengubah peraturan untuk seluruh pelayan.',
           'Battle Pass berharga 800 V-Bucks dan diketuai Sonic the Hedgehog, bersama Tails sebagai Sidekick.',
           'Pemain yang membeli Pass sebelum 27 Ogos jam 11:59 malam (waktu timur AS) menerima pakaian Infiltrator Grace Crowne sebagai bonus minggu pelancaran.',
           'Kolaborasi musim ini: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot dan Spyro the Dragon; senjata termasuk Midas’ Masterpiece dan Mega Buster milik Mega Man.'],
   'impact': 'Pakaian yang hanya tersedia untuk masa terhad — seperti bonus minggu pelancaran — ialah apa yang membezakan loker Fortnite yang jarang dengan yang biasa. Pakaian Battle Pass kekal terikat pada musim asalnya.'},
 }},
'uz': {
 'ui': {
  'news': 'Yangiliklar', 'news_title': 'Akkaunt qiymatiga taʼsir qiladigan o‘yin yangiliklari',
  'news_lead': 'O‘yin noshirlarining rasmiy yangilanishlari — har biri noshirning o‘z eʼloni bilan solishtirilgan va akkaunt qiymati uchun nimani anglatishi qisqa izohlangan.',
  'game_title': '{game} yangiliklari', 'game_lead': 'Akkaunt qiymatiga taʼsir qiladigan rasmiy {game} yangilanishlari. Har bir maqolada noshir eʼloniga havola bor.',
  'published': 'Eʼlon qilingan', 'source': 'Rasmiy manba', 'by_on': '{pub}, {date}', 'whats_new': 'Nima yangi',
  'impact': 'Akkaunt qiymati uchun nimani anglatadi', 'more': 'Boshqa {game} yangiliklari', 'all': 'Barcha yangiliklar',
  'calc': '{game}: qiymat kalkulyatori va bozor hisoboti', 'read': 'O‘qish', 'latest': 'So‘nggi {game} yangiliklari',
  'note': 'GameAccountValue akkauntlarni sotib olmaydi, sotmaydi va vositachilik qilmaydi. Yangiliklar faqat maʼlumot uchun noshirlar eʼlonlaridan qisqacha bayon qilingan.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna va Vodyanitsa keldi, yubiley sovg‘alari tasdiqlandi',
   'desc': '"A Rekviem for the Underworld" deb nomlangan 7.1 versiyasi 2026-yil 23-sentabrda ikki yangi 5 yulduzli qahramon, ikki 5 yulduzli qurol va oltinchi yubiley sovg‘alari bilan chiqdi.',
   'lead': 'HoYoverse 2026-yil 23-sentabrda 7.1 versiyasini — "A Rekviem for the Underworld"ni chiqardi; bu yangilanish Genshin Impact’ning oltinchi yubileyiga ham to‘g‘ri keldi.',
   'new': ['Ikki yangi 5 yulduzli qahramon: Vesna (Anemo, qilich) va Vodyanitsa (Hydro, katalizator).',
           'Yangi qurollar: Beyond the Chrysalis (5★ qilich), Hymn of the Maelstrom (5★ katalizator) va New Bough (4★ qilich).',
           'HoYoverse eʼlon qilgan yubiley sovg‘alari: taklif qilish uchun ikki 5 yulduzli qahramon, Intertwined Fate ×10, Primogem ×1 600 va Genesis Crystal birinchi to‘ldirish bonusining yangilanishi.',
           'Yangilanish uchun texnik ishlar 23-sentabr soat 06:00 da (UTC+8) boshlandi.'],
   'impact': 'Tadqiqotimizga ko‘ra, cheklangan 5 yulduzli qahramonlar soni, ularning yulduz turkumlari va maxsus qurollari Genshin akkaunti qiymatining asosiy omillaridan. Yubileyda hammaga bepul beriladigan qahramonlar akkauntni cheklangan banner qahramonlari kabi noyob qilmaydi.'},
  'mc-live': {
   'title': 'Minecraft Live: 14 yildan ortiq vaqt ichidagi birinchi yangi olam — The Sift Java va Bedrock’ga keladi',
   'desc': '2026-yil 26-sentabrdagi Minecraft Live kelasi yili Java va Bedrock’ga qo‘shiladigan to‘rtinchi olam The Sift’ni, shuningdek Dungeons II va Wilderness Bound yangilanishini tanishtirdi.',
   'lead': '2026-yil 26-sentabrdagi Minecraft Live’da Mojang Studios o‘yinning to‘rtinchi olami — The Sift kelasi yili Minecraft Java va Bedrock Edition’ga qo‘shilishini eʼlon qildi.',
   'new': ['The Sift — 14 yildan ortiq vaqt ichidagi birinchi yangi olam (dimension); u Overworld, Nether va End qatoriga qo‘shiladi.',
           'U ilk bor Minecraft Dungeons II’da paydo bo‘ladi; Mojang uning chiqish sanasini 2026-yil 29-sentabr deb belgilagan.',
           'Mavzuli attraksion Minecraft World 2027-yilda Londonda ochiladi.',
           'Wilderness Bound yangilanishi 15-sentabrda chiqdi: xoldor o‘rmon, somon karavotlar, tashlab ketilgan lagerlar va yostiqchalar.'],
   'impact': 'Minecraft akkauntlari o‘yin kontentiga ko‘ra emas, balki turi (Java yoki Bedrock), foydalanuvchi nomi va plashlariga ko‘ra baholanadi. Bunday yangilanishlar o‘yinchilar nima qila olishini o‘zgartiradi, akkaunt qiymatini emas.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": cheklangan UGC buyumlar va Roblox Plus uchun eksklyuzivlar (17–28-sentabr)',
   'desc': 'The Hunt: Roblox 20 2026-yil 17–28-sentabr kunlari UGC sovg‘alari, cheklangan nashrdagi UGC buyumlar va Roblox Plus obunachilari uchun uchta eksklyuziv buyum bilan o‘tdi.',
   'lead': 'Roblox o‘zining 20 yilligini butun platformada o‘tgan The Hunt: Roblox 20 tadbiri bilan nishonladi; u 2026-yil 17–28-sentabr kunlari bo‘lib o‘tdi.',
   'new': ['O‘yinchilar "Year Zero"dan boshlab, har yil uchun bittadan topshiriq bilan Roblox’ning 20 yillik tarixidan o‘tishdi; barcha 20 yilni tugatish yana 20 ta o‘yinli "Year Infinity"ni ochdi.',
           'Topshiriqlar uchun UGC buyumlar berildi, tadbir davomida esa cheklangan nashrdagi UGC buyumlar ham bor edi.',
           'Roblox Plus obunachilari uchta eksklyuziv virtual buyum oldi va tadbirdan keyin ham Classic ilova mavzusi, klassik avatar foni va profil ramkasini saqlab qoladi.',
           'Tadbir davomida Classic ilova mavzusi hamma uchun bepul edi.'],
   'impact': 'Faqat tadbir paytida olish mumkin bo‘lgan buyumlar baholashda eʼtiborga olinadigan narsalardan biri. Roblox eʼlonda bu buyumlar nomini keltirmadi, shuning uchun haqiqiy sotuv eʼlonlari paydo bo‘lmaguncha bu sayt ularga narx qo‘ymaydi.'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox ijodkorlari bir yilda qariyb 1,7 mlrd dollar ishladi; Roblox Wallet eʼlon qilindi',
   'desc': 'RDC 2026’da Roblox ijodkorlar 12 oyda qariyb 1,7 mlrd dollar ishlaganini maʼlum qildi hamda to‘lovlar uchun Roblox Wallet va Roblox Card’ni eʼlon qildi.',
   'lead': 'Roblox o‘zining RDC 2026 dasturchilar konferensiyasida (2026-yil 11-sentabrdagi eʼlon) ijodkorlar daromadi raqamlari va yangi to‘lov vositalarini taqdim etdi.',
   'new': ['DevEx 2013-yilda ishga tushganidan beri ijodkorlar 5 mlrd dollardan ortiq, 2026-yil 30-iyungacha bo‘lgan 12 oyda esa qariyb 1,7 mlrd dollar ishlashgan.',
           'Roblox Plus rag‘batlari dastlabki to‘rt oyda (2026-yil 17-avgustgacha) ijodkorlarga 300 milliondan ortiq Robux daromad keltirdi.',
           'Airwallex US bilan yuritiladigan to‘lov hisobi Roblox Wallet haqiqiy valyutada har kuni to‘lov beradi — avval 2026-yil oxirida AQShdagi talablarga javob beradigan 18 yoshdan katta mustaqil ijodkorlar uchun, 2027-yilda xalqaro miqyosda.',
           'Wallet bilan bog‘langan Roblox Card 2027-yildan rejalashtirilgan.'],
   'impact': 'Bu o‘zgarishlar o‘yinchilar akkauntlariga emas, ijodkorlarga to‘lovlarga tegishli: eʼlon Robux narxlarini, cheklangan buyumlarni yoki savdoni o‘zgartirmadi. Roblox kalkulyatorimiz hisobga oladigan narsa hamon Robux balansi va cheklangan buyumlardir.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: Clash Squad uchun to‘rtta yangi qurol, Prime Diamond va Kenta yangilandi',
   'desc': 'Garena’ning OB55 yangilanish qaydlari (2026-yil 10-sentabr) 1-oktabrdan Clash Squad’ga M7, Skorp, RPK va Hawk qo‘shadi, Prime Diamond’ni joriy etadi va Kenta’ni qayta ishlaydi.',
   'lead': 'Garena Free Fire’ning OB55 yangilanish qaydlarini 2026-yil 10-sentabrda eʼlon qildi; qurol o‘zgarishlari 1-oktabrdan kuchga kiradi.',
   'new': ['1-oktabrdan Clash Squad’dagi yangi qurollar: M7 (1 600 CS Cash), Skorp (1 500), RPK (1 500) va Hawk (1 700).',
           'Prime Diamond: oylik xarajatga qarab olmos beriladi, har qanday to‘ldirishdan keyin keyingi oyda olish mumkin.',
           'Kenta to‘liq qayta ishlandi; Morse, Luna va Wukong muvozanat o‘zgarishlarini oldi.',
           '1-oktabrdan qurol turiga qarab harakatchanlik o‘zgaradi: SMG’lar tezroq, snayper va marksman miltiqlari sekinroq.'],
   'impact': 'Free Fire kalkulyatorimiz olmos balansi va noyob to‘plamlarni hisobga oladi. OB55 kelgusidagi to‘ldirishlar qanday rag‘batlantirilishini o‘zgartiradi; akkauntlarda allaqachon bor buyumlarni o‘zgartirmaydi.'},
  'cr-minion': {
   'title': 'Clash Royale "Minion Academy" mavsumi: yangi karta Minion Giant va qahramon Ice Wizard',
   'desc': 'Minion Academy mavsumi (2026-yil 7-sentabr – 5-oktabr) Minion Giant kartasi, Ice Wizard qahramoni va 1 750 ta Minion Giant kartasi beradigan albom tadbirini qo‘shadi.',
   'lead': 'Supercell 2026-yil 7-sentabrdan 5-oktabrgacha davom etadigan Clash Royale "Minion Academy" mavsumini boshladi.',
   'new': ['Yangi karta Minion Giant: binolar va minoralarni nishonga oladigan uchuvchi g‘alaba kartasi. U Academy Antics albom tadbiri orqali bepul beriladi va sandiqlarda faqat keyingi mavsumdan chiqadi.',
           'Albom tadbiri 1 750 ta Minion Giant kartasi, emotsiya va minora skinini beradi.',
           'Yangi qahramon: Ice Wizard — Pass Royale yo‘lidan yoki 200 Hero Coin evaziga.',
           'Tadbirlar: 2v2 ligasi (7–21-sentabr), Princess Gambit jahon turniri (21–26-sentabr) va Royale Shuffle (21-sentabr – 5-oktabr). Ultimate Champion’dagi durang endi mag‘lubiyatdagi kuboklarning yarmicha kubok oladi.'],
   'impact': 'Faqat tadbir paytida taklif qilinadigan minora skinlari va emotsiyalar Clash Royale kolleksiyasini noyobroq qiladi, biroq asosiy qiymat omillari Qirol minorasi darajasi va karta darajalari bo‘lib qolmoqda.'},
  'ml-10': {
   'title': 'Mobile Legends 10 yoshda: ALL IN kampaniyasi va Layla uchun yangi Collector skin',
   'desc': 'MOONTON’ning 10 yillik ALL IN kampaniyasi (2026-yil 4-sentabrdan) Nana uchun yangi Epic skin, bepul skin sandiqlari va 9-oktabrdan Layla’ning Collector skinini olib keladi.',
   'lead': 'MOONTON Games 2026-yil 4-sentabrda Mobile Legends: Bang Bang’ning o‘n yilligi uchun ALL IN kampaniyasini boshladi.',
   'new': ['10 yillik bayram pasi (4-sentabr – 1-noyabr): Nana uchun yangi Epic skin, Epic skin tanlash sandig‘i, tasodifiy Epic skin sandig‘i va qaytgan o‘yinchilar uchun bepul yubiley skini.',
           'Anniversary Gala Weekend (25-sentabr – 11-oktabr): 265 ta skindan foydalanish, Battle Pass EXP va Premium skin bo‘laklari.',
           'Layla’s Stellar Gala (9-oktabr – 19-noyabr): "Starfall Breakout" mini-o‘yini orqali Layla’ning yangi Collector skini.',
           'MOONTON 1,5 milliarddan ortiq o‘rnatish va oyiga 110 million faol o‘yinchi haqida xabar beradi.'],
   'impact': 'Collector va Legend skinlari Mobile Legends akkauntlari qiymatining eng ko‘p tilga olinadigan omillaridan; bepul tarqatilgan yoki sinov skinlari emas.'},
  'bs-aug': {
   'title': 'Brawl Stars: Mythic brawlerlar Cosmo va Vince; Starr Road endi Brawler Blast',
   'desc': 'Supercell’ning 2026-yil avgust yangilanish qaydlari (1-sentabr) ikki Mythic brawler qo‘shadi, Starr Road’ni yangi kredit narxlari bilan Brawler Blast’ga aylantiradi va Ultra Legendary nomini Ultra deb o‘zgartiradi.',
   'lead': 'Supercell Brawl Stars’ning 2026-yil avgust yangilanishi qaydlarini 2026-yil 1-sentabrda eʼlon qildi.',
   'new': ['Ikki yangi Mythic brawler: Cosmo (Controller) va Vince (Damage Dealer).',
           'Nori va Wendy uchun yangi Hypercharge’lar.',
           'Starr Road "Brawler Blast"ga aylantirildi: kreditlar endi noyoblik bo‘yicha ochishga sarflanadi — Rare 160, Super Rare 430, Epic 925, Mythic 1 900, Legendary 3 800, Ultra 5 500.',
           '"Ultra Legendary" noyobligi endi "Ultra" deb ataladi. Shuningdek, Royal Academy mavsumi va bir oy davom etadigan Brawl-O-Ween tadbiri.'],
   'impact': 'Brawl Stars kalkulyatorimiz brawlerlar soni, Hypercharge’lar va kuboklardan foydalanadi. Yana ikki Mythic to‘liq kolleksiya uchun zarur brawlerlar sonini oshiradi.'},
  'coc-aug': {
   'title': 'Clash of Clans avgust yangilanishi: Diggy 11–15-darajalar va Gold Pass Town Hall 3 dan',
   'desc': 'Supercell’ning 2026-yil avgust yangilanishi (30-avgust) Town Hall 18 da Diggy’ning 11–15-darajalari va yangi supercharge’larni qo‘shadi, Starter Pass’ni bekor qiladi va Gold Pass’ni Town Hall 3 dan ochadi.',
   'lead': 'Supercell Clash of Clans avgust yangilanishini 2026-yil 30-avgustda chiqardi.',
   'new': ['Town Hall 18: Diggy uy hayvoni 11–15-darajalarni oladi; Builder’s Hut va Monolith yangi supercharge darajalarini oladi.',
           'Starter Pass bekor qilindi: mavsum sinovlari va Gold Pass endi Town Hall 3 dan mavjud, sovg‘alar Town Hall darajasiga qarab o‘zgaradi.',
           'Ruin Knight endi vaqt o‘tishi bilan salomatlik yo‘qotmaydi; Ruin Witch 8 ta o‘rniga 10 ta Ruin Knight chaqiradi.',
           'Titan ligalaridagi Clan War League modifikatorlari o‘zgartirildi.'],
   'impact': 'Tadqiqotimizda Clash of Clans akkaunti qiymatini Town Hall darajasi hamda qahramonlar va uy hayvonlari darajalari belgilaydi. Town Hall 18 dagi yangi maksimal darajalar "maks" akkaunt endi yangilanishdan oldingidan ko‘proq yaxshilashni talab qilishini anglatadi.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 "Override": Sonic’li Battle Pass va KINGDOM HEARTS bilan hamkorlik',
   'desc': 'Epic’ning "Override" mavsumi (Chapter 7, Season 4) Override Console’lar, Sonic the Hedgehog boshchiligidagi 800 V-Bucks’lik Battle Pass va KINGDOM HEARTS kabi hamkorliklarni olib keladi.',
   'lead': 'Fortnite’ning Chapter 7 Season 4 mavsumi "Override" deb ataladi. Epic uni o‘yin hamkorliklari va butun o‘yin qoidalarini o‘zgartirishga qurilgan mavsum deb taʼriflaydi.',
   'new': ['Override Console’lar har bir o‘yinda paydo bo‘ladi va butun server qoidalarini o‘zgartirishga imkon beradi.',
           'Battle Pass 800 V-Bucks turadi, uning bosh qahramoni Sonic the Hedgehog, yonida Tails hamroh.',
           'Pass’ni 27-avgust soat 23:59 gacha (AQSh sharqiy vaqti) sotib olganlar ishga tushirish haftasi bonusi sifatida Infiltrator Grace Crowne kiyimini olishdi.',
           'Mavsumdagi hamkorliklar: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot va Spyro the Dragon; qurollar orasida Midas’ Masterpiece va Mega Man’ning Mega Buster’i bor.'],
   'impact': 'Faqat cheklangan vaqt beriladigan kiyimlar — masalan, ishga tushirish haftasi bonusi — noyob Fortnite shkaflarini oddiylaridan ajratib turadi. Battle Pass kiyimlari o‘z mavsumiga bog‘liq bo‘lib qoladi.'},
 }},
}
