# News batch 3: tl, sw, ms, uz (from news_text_b3_en.py, facts unchanged)
TEXT = {
'tl': {'a': {
 'cr-shock': {
  'title': 'Shocktober season ng Clash Royale: Hero Electro Wizard at libreng Electro Giant Evolution',
  'desc': 'Tatakbo ang Shocktober season mula Oktubre 6 hanggang Nobyembre 2, 2026: Hero Electro Wizard sa Upgraded Pass Royale, libreng Electro Giant Evolution sa Album Event, at mga bagong badge.',
  'lead': 'Inanunsyo ng Supercell ang Shocktober season noong Oktubre 5, 2026; tatakbo ito mula Oktubre 6 hanggang Nobyembre 2.',
  'new': ['Bagong Hero: Electro Wizard, na ang ability na Surging Strikes ay nag-i-stun ng dalawang kalapit na kalaban nang sabay. Nasa Upgraded Pass Royale ito.',
          'Bagong Evolution: Electro Giant. Makukuha ito nang libre kapag natapos ang Album Event na “Shocktober: The Movie!” (Oktubre 6 – Nobyembre 2, mula Arena 3), na may kasama ring emote at tower skin.',
          'Mga badge: hanggang dalawa sa Spooky Chess league (Oktubre 5–19) at isa sa Power Surge Global Tournament (Oktubre 20–25), at may dagdag na badge sa bawat isa para sa mga nasa top 10,000.',
          'Babalik ang 20-Win Challenge mula Oktubre 26 hanggang Nobyembre 2: 20 panalo na may mas kaunti sa 3 talo para sa isang emote.'],
  'impact': 'Ang Evolution na makukuha nang libre ng lahat ng manlalaro ay halos hindi nagpapaiba sa isang account. Mas mahirap makuha ang mga badge para sa top 10,000 at nagpapakita ito ng husay sa profile. Sa aming pananaliksik, ang level ng King Tower at level ng mga card pa rin ang pangunahing salik ng halaga.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — Portal Pendant equipment at mga bagong Hero Skin ngayong Oktubre',
  'desc': 'Tatakbo ang Cosmic Curse: Portal Panic mula Oktubre 1 hanggang 31, 2026: ang Epic Equipment na Portal Pendant para sa Minion Prince mula sa Medal Event (Oktubre 8–25), mga Hero Skin at isang Gold Pass skin.',
  'lead': 'Inanunsyo ng Supercell ang Clash-O-Ween season na “Cosmic Curse: Portal Panic” noong Oktubre 1, 2026; tatagal ito hanggang Oktubre 31.',
  'new': ['Portal Panic Medal Event, Oktubre 8–25, Town Hall 6 pataas: ang Sour Elixir na nakukuha sa mga laban ay nagbubukas ng mga reward at Rift Medals, na ipinambibili sa Trader Shop ng bagong Portal Pendant — Epic Equipment para sa Minion Prince (bukas ang shop hanggang Oktubre 27).',
          'Gold Pass, Oktubre 1–31: ang eksklusibong Hero Skin ng season ay Shroud Queen, at Ghost Champion ang alternatibo.',
          'Mga Hero Skin na darating sa loob ng buwan: Savage King (Oktubre 5), Nasty Prince (Oktubre 7), Terror Champion (Oktubre 9), Behemoth Duke (Oktubre 11) at Spider Warden (Oktubre 13); ang Cosmic Portals XL Scenery mula Oktubre 3.',
          'May pansamantalang troop na Totem Thrower sa buong season, at babalik sa Oktubre 15 ang mga cosmetic ng Cosmic Curse noong 2025.'],
  'impact': 'Nananatili sa account ang Hero Equipment at mga Hero Skin, kaya nadaragdagan nito ang ipinapakita ng account. Sa aming pananaliksik, ang level ng Town Hall at kung gaano kakumpleto ang mga hero para sa level na iyon pa rin ang pangunahing salik ng halaga; pangalawang detalye lang ang mga seasonal na skin.'},
 'coc-ore': {
  'title': 'Ibinaba ng Clash of Clans ang presyo ng Ore sa Gems: Starry Ore mula 35 naging 20 Gems',
  'desc': 'Inanunsyo ng Supercell noong Oktubre 2, 2026 ang bagong baseline na presyo ng Ore sa Gems: Shiny 1 → 0.5, Glowy 5 → 3, Starry 35 → 20. Halos kalahati na lang ang Gems para i-max ang Epic Equipment.',
  'lead': 'Noong Oktubre 2, 2026, inanunsyo ng Supercell ang mas mababang presyo ng Ore sa Gems sa Clash of Clans — bilang bagong baseline, hindi pansamantalang sale.',
  'new': ['Bagong presyo: Shiny Ore 1 Gem → 0.5 Gem, Glowy Ore 5 → 3 Gems, Starry Ore 35 → 20 Gems.',
          'Ayon sa Supercell, halos kalahati ang ibinaba ng Gems na kailangan para i-max ang isang Epic Equipment.',
          'Ginagamit na ng Trader ang bagong presyo mula Hulyo; susunod ang Medal shop sa Medal Event ngayong Oktubre, at sa susunod na buong update ay magiging pamantayan na ito sa buong laro.',
          'May ipinangakong dagdag na pagbabago sa ekonomiya ng Ore sa bandang huli ng Oktubre.'],
  'impact': 'Mas mura nang maabot ang naka-max na Hero Equipment, kaya maaari itong maging mas karaniwan sa mga account na mataas ang Town Hall. Sa aming pananaliksik, ang level ng Town Hall at progreso ng mga hero pa rin ang pangunahing salik ng halaga.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: paano pinipili ang walong team sa bawat rehiyon',
  'desc': 'Ipinaliwanag ng Supercell noong Oktubre 1, 2026 kung paano makakapasok ang mga team sa BSC 2027: anim na direktang imbitasyon bawat rehiyon mula sa leaderboard ng 2026 at dalawang puwesto mula sa BSC Invitational sa Enero 16–17, 2027.',
  'lead': 'Noong Oktubre 1, 2026, inilathala ng Supercell ang daan ng kwalipikasyon para sa Brawl Stars Championship 2027.',
  'new': ['May walong team ang BSC 2027 sa bawat isa sa apat na rehiyon: APAC, EMEA, South America at North America.',
          'Ang nangungunang anim na team sa 2026 BSC Leaderboard ng bawat rehiyon ay direktang iimbitahan at puwedeng magpalit ng hanggang isang manlalaro lang.',
          'Ang huling dalawang puwesto bawat rehiyon ay pagpapasyahan sa BSC Invitational sa Enero 16–17, 2027: maglalaro ang mga team na nasa ika-7 hanggang ika-10 puwesto, at ika-7 hanggang ika-14 sa EMEA.',
          'Ipapadala ang mga imbitasyon sa Nobyembre 23, 2026 at kailangang sumagot ang mga team bago ang Disyembre 20; sinabi ng Supercell na maaaring magbago ang mga petsa. Ang mga bagong team ay magsisimula sa in-game na Championship Challenge at Brawl Stars Challengers.'],
  'impact': 'Hindi binabago ng esports qualification ang halaga ng karaniwang account. Sa aming pananaliksik, tropeo, mga brawler at ang kanilang Power Level pa rin ang batayan ng presyo sa mga listing.'},
}},
'sw': {'a': {
 'cr-shock': {
  'title': 'Msimu wa Shocktober wa Clash Royale: Hero Electro Wizard na Evolution ya bure ya Electro Giant',
  'desc': 'Msimu wa Shocktober unaanza Oktoba 6 hadi Novemba 2, 2026: Hero Electro Wizard katika Upgraded Pass Royale, Evolution ya Electro Giant bure kupitia Album Event, na beji mpya.',
  'lead': 'Supercell ilitangaza msimu wa Shocktober tarehe 5 Oktoba 2026; unaendelea kuanzia Oktoba 6 hadi Novemba 2.',
  'new': ['Hero mpya: Electro Wizard, ambaye uwezo wake Surging Strikes unawapiga bumbuazi maadui wawili wa karibu kwa wakati mmoja. Anapatikana katika Upgraded Pass Royale.',
          'Evolution mpya: Electro Giant. Inafunguliwa bure kwa kukamilisha Album Event “Shocktober: The Movie!” (Oktoba 6 – Novemba 2, kuanzia Arena 3), ambayo pia inatoa emote na skin ya mnara.',
          'Beji: hadi mbili katika ligi ya Spooky Chess (Oktoba 5–19) na moja katika Power Surge Global Tournament (Oktoba 20–25), kila moja ikiwa na beji ya ziada kwa wanaomaliza ndani ya 10,000 bora.',
          '20-Win Challenge inarudi kuanzia Oktoba 26 hadi Novemba 2: ushindi 20 ukiwa na vipigo chini ya 3 unakupa emote.'],
  'impact': 'Evolution ambayo kila mchezaji anaweza kuipata bure haitofautishi sana akaunti moja na nyingine. Beji za 10,000 bora ni ngumu zaidi kupata na zinaonyesha ujuzi kwenye wasifu. Katika utafiti wetu, kiwango cha King Tower na viwango vya kadi vinabaki kuwa vigezo vikuu vya thamani.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — kifaa cha Portal Pendant na Hero Skin mpya mwezi Oktoba',
  'desc': 'Cosmic Curse: Portal Panic inaendelea Oktoba 1 hadi 31, 2026: Epic Equipment ya Portal Pendant kwa Minion Prince kutoka Medal Event (Oktoba 8–25), Hero Skin na skin ya Gold Pass.',
  'lead': 'Supercell ilitangaza msimu wa Clash-O-Ween “Cosmic Curse: Portal Panic” tarehe 1 Oktoba 2026; unaendelea hadi Oktoba 31.',
  'new': ['Portal Panic Medal Event, Oktoba 8–25, Town Hall 6 na kuendelea: Sour Elixir inayokusanywa vitani inafungua zawadi na Rift Medals, ambazo hununua Portal Pendant mpya — Epic Equipment ya Minion Prince — katika Trader Shop (duka liko wazi hadi Oktoba 27).',
          'Gold Pass, Oktoba 1–31: Hero Skin ya kipekee ya msimu ni Shroud Queen, na chaguo mbadala ni Ghost Champion.',
          'Hero Skin zinazowasili ndani ya mwezi: Savage King (Oktoba 5), Nasty Prince (Oktoba 7), Terror Champion (Oktoba 9), Behemoth Duke (Oktoba 11) na Spider Warden (Oktoba 13); Scenery ya Cosmic Portals XL kuanzia Oktoba 3.',
          'Kikosi cha muda, Totem Thrower, kinaongezwa kwa msimu huu, na mapambo ya Cosmic Curse ya 2025 yanarudi Oktoba 15.'],
  'impact': 'Hero Equipment na Hero Skin hubaki kwenye akaunti, kwa hiyo huongeza kile ambacho akaunti inaonyesha. Katika utafiti wetu, kiwango cha Town Hall na jinsi hero walivyokamilika kwa kiwango hicho vinabaki kuwa vigezo vikuu vya thamani; skin za msimu ni jambo la pili.'},
 'coc-ore': {
  'title': 'Clash of Clans yapunguza bei ya Ore kwa Gems: Starry Ore kutoka Gems 35 hadi 20',
  'desc': 'Supercell ilitangaza tarehe 2 Oktoba 2026 bei mpya za msingi za Ore kwa Gems: Shiny 1 → 0.5, Glowy 5 → 3, Starry 35 → 20. Kufikisha Epic Equipment kiwango cha juu kunagharimu takriban nusu ya Gems.',
  'lead': 'Tarehe 2 Oktoba 2026 Supercell ilitangaza bei za chini za Ore kwa Gems katika Clash of Clans — kama bei mpya ya msingi, si punguzo la muda.',
  'new': ['Bei mpya: Shiny Ore Gem 1 → Gem 0.5, Glowy Ore Gems 5 → 3, Starry Ore Gems 35 → 20.',
          'Supercell inasema gharama ya Gems ya kufikisha kipande kimoja cha Epic Equipment kiwango cha juu inashuka kwa takriban nusu.',
          'Trader amekuwa akitumia bei mpya tangu Julai; duka la Medal litafuata katika Medal Event ya Oktoba, na sasisho kamili lijalo litazifanya kuwa bei za kawaida kote kwenye mchezo.',
          'Mabadiliko zaidi ya uchumi wa Ore yameahidiwa baadaye mwezi Oktoba.'],
  'impact': 'Hero Equipment ya kiwango cha juu inakuwa nafuu kufikia, kwa hiyo inaweza kuwa ya kawaida zaidi kwenye akaunti za Town Hall ya juu. Katika utafiti wetu, kiwango cha Town Hall na maendeleo ya hero vinabaki kuwa vigezo vikuu vya thamani.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: jinsi timu nane za kila kanda zinavyochaguliwa',
  'desc': 'Supercell ilieleza tarehe 1 Oktoba 2026 jinsi timu zinavyofika BSC 2027: mialiko sita ya moja kwa moja kwa kila kanda kutoka msimamo wa 2026 na nafasi mbili kutoka BSC Invitational tarehe 16–17 Januari 2027.',
  'lead': 'Tarehe 1 Oktoba 2026 Supercell ilichapisha njia ya kufuzu kwa Brawl Stars Championship 2027.',
  'new': ['BSC 2027 ina timu nane katika kila moja ya kanda nne: APAC, EMEA, Amerika Kusini na Amerika Kaskazini.',
          'Timu sita bora za 2026 BSC Leaderboard ya kila kanda zinapata mwaliko wa moja kwa moja na zinaweza kubadilisha mchezaji mmoja tu.',
          'Nafasi mbili za mwisho za kila kanda zinaamuliwa katika BSC Invitational tarehe 16–17 Januari 2027: timu za nafasi ya 7 hadi 10 zinacheza, na nafasi ya 7 hadi 14 katika EMEA.',
          'Mialiko itatumwa tarehe 23 Novemba 2026 na timu lazima zijibu kabla ya Desemba 20; Supercell inabainisha kuwa tarehe zinaweza kubadilika. Timu mpya zinaanza na Championship Challenge ndani ya mchezo na Brawl Stars Challengers.'],
  'impact': 'Kufuzu kwa esports hakubadilishi thamani ya akaunti ya kawaida. Katika utafiti wetu, bei kwenye matangazo bado inategemea nyara, brawler na Power Level zao.'},
}},
'ms': {'a': {
 'cr-shock': {
  'title': 'Musim Shocktober Clash Royale: Hero Electro Wizard dan Evolusi Electro Giant percuma',
  'desc': 'Musim Shocktober berlangsung dari 6 Oktober hingga 2 November 2026: Hero Electro Wizard dalam Pass Royale yang dinaik taraf, Evolusi Electro Giant percuma melalui Acara Album, dan lencana baharu.',
  'lead': 'Supercell mengumumkan musim Shocktober pada 5 Oktober 2026; ia berlangsung dari 6 Oktober hingga 2 November.',
  'new': ['Hero baharu: Electro Wizard, dengan kebolehan Surging Strikes yang memengsankan dua musuh berdekatan serentak. Ia terdapat dalam Pass Royale yang dinaik taraf.',
          'Evolusi baharu: Electro Giant. Ia dibuka secara percuma dengan melengkapkan Acara Album “Shocktober: The Movie!” (6 Oktober – 2 November, dari Arena 3), yang turut memberi emote dan skin menara.',
          'Lencana: sehingga dua dalam liga Spooky Chess (5–19 Oktober) dan satu dalam Kejohanan Global Power Surge (20–25 Oktober), masing-masing dengan lencana tambahan untuk kedudukan 10,000 teratas.',
          'Cabaran 20 Kemenangan kembali dari 26 Oktober hingga 2 November: 20 kemenangan dengan kurang daripada 3 kekalahan untuk satu emote.'],
  'impact': 'Evolusi yang boleh diperoleh secara percuma oleh setiap pemain hampir tidak membezakan satu akaun daripada yang lain. Lencana 10,000 teratas lebih sukar diperoleh dan menunjukkan kemahiran pada profil. Dalam kajian kami, tahap King Tower dan tahap kad kekal sebagai faktor nilai utama.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — peralatan Portal Pendant dan Skin Hero baharu pada Oktober',
  'desc': 'Cosmic Curse: Portal Panic berlangsung dari 1 hingga 31 Oktober 2026: Peralatan Epik Portal Pendant untuk Minion Prince daripada Acara Pingat (8–25 Oktober), Skin Hero dan skin Gold Pass.',
  'lead': 'Supercell mengumumkan musim Clash-O-Ween “Cosmic Curse: Portal Panic” pada 1 Oktober 2026; ia berlangsung hingga 31 Oktober.',
  'new': ['Acara Pingat Portal Panic, 8–25 Oktober, Town Hall 6 ke atas: Sour Elixir yang dikumpul dalam pertempuran membuka ganjaran dan Rift Medals, yang digunakan di Kedai Trader untuk mendapatkan Portal Pendant baharu — Peralatan Epik untuk Minion Prince (kedai dibuka hingga 27 Oktober).',
          'Gold Pass, 1–31 Oktober: Skin Hero eksklusif musim ini ialah Shroud Queen, dengan Ghost Champion sebagai pilihan alternatif.',
          'Skin Hero yang tiba sepanjang bulan: Savage King (5 Oktober), Nasty Prince (7 Oktober), Terror Champion (9 Oktober), Behemoth Duke (11 Oktober) dan Spider Warden (13 Oktober); Pemandangan Cosmic Portals XL dari 3 Oktober.',
          'Pasukan sementara, Totem Thrower, menyertai musim ini, dan kosmetik Cosmic Curse 2025 kembali pada 15 Oktober.'],
  'impact': 'Peralatan Hero dan Skin Hero kekal pada akaun, jadi ia menambah apa yang ditunjukkan oleh akaun. Dalam kajian kami, tahap Town Hall dan sejauh mana Hero lengkap untuk tahap itu kekal sebagai faktor nilai utama; skin bermusim ialah perincian sampingan.'},
 'coc-ore': {
  'title': 'Clash of Clans menurunkan harga Ore dalam Gem: Starry Ore daripada 35 kepada 20 Gem',
  'desc': 'Supercell mengumumkan pada 2 Oktober 2026 harga asas baharu Ore dalam Gem: Shiny 1 → 0.5, Glowy 5 → 3, Starry 35 → 20. Memaksimumkan Peralatan Epik kini memerlukan kira-kira separuh Gem.',
  'lead': 'Pada 2 Oktober 2026 Supercell mengumumkan harga Gem yang lebih rendah untuk Ore dalam Clash of Clans — sebagai harga asas baharu, bukan jualan masa terhad.',
  'new': ['Harga baharu: Shiny Ore 1 Gem → 0.5 Gem, Glowy Ore 5 → 3 Gem, Starry Ore 35 → 20 Gem.',
          'Menurut Supercell, kos Gem untuk memaksimumkan satu Peralatan Epik turun kira-kira separuh.',
          'Trader telah menggunakan harga baharu sejak Julai; kedai Pingat menyusul dalam Acara Pingat Oktober, dan kemas kini penuh seterusnya menjadikannya harga standard di seluruh permainan.',
          'Lebih banyak perubahan pada ekonomi Ore dijanjikan lewat Oktober.'],
  'impact': 'Peralatan Hero tahap maksimum menjadi lebih murah untuk dicapai, jadi ia mungkin lebih biasa pada akaun Town Hall tinggi. Dalam kajian kami, tahap Town Hall dan kemajuan Hero kekal sebagai faktor nilai utama.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: cara lapan pasukan setiap rantau dipilih',
  'desc': 'Supercell menjelaskan pada 1 Oktober 2026 cara pasukan memasuki BSC 2027: enam jemputan terus bagi setiap rantau daripada kedudukan 2026 dan dua slot daripada BSC Invitational pada 16–17 Januari 2027.',
  'lead': 'Pada 1 Oktober 2026 Supercell menerbitkan laluan kelayakan Brawl Stars Championship 2027.',
  'new': ['BSC 2027 mempunyai lapan pasukan di setiap satu daripada empat rantau: APAC, EMEA, Amerika Selatan dan Amerika Utara.',
          'Enam pasukan teratas dalam BSC Leaderboard 2026 setiap rantau menerima jemputan terus dan boleh menukar paling banyak seorang pemain.',
          'Dua slot terakhir setiap rantau ditentukan di BSC Invitational pada 16–17 Januari 2027: pasukan di kedudukan ke-7 hingga ke-10 bermain, dan ke-7 hingga ke-14 di EMEA.',
          'Jemputan dihantar pada 23 November 2026 dan pasukan mesti menjawab sebelum 20 Disember; Supercell menyatakan tarikh boleh berubah. Pasukan baharu bermula daripada Championship Challenge dalam permainan dan Brawl Stars Challengers.'],
  'impact': 'Kelayakan e-sukan tidak mengubah nilai akaun biasa. Dalam kajian kami, harga dalam iklan masih bergantung pada trofi, brawler dan Power Level mereka.'},
}},
'uz': {'a': {
 'cr-shock': {
  'title': 'Clash Royale Shocktober mavsumi: Hero Electro Wizard va bepul Electro Giant Evolution',
  'desc': 'Shocktober mavsumi 2026-yil 6-oktabrdan 2-noyabrgacha davom etadi: Hero Electro Wizard yaxshilangan Pass Royale’da, Electro Giant Evolution Album tadbiri orqali bepul, yangi nishonlar.',
  'lead': 'Supercell Shocktober mavsumini 2026-yil 5-oktabrda eʼlon qildi; u 6-oktabrdan 2-noyabrgacha davom etadi.',
  'new': ['Yangi Hero: Electro Wizard. Uning Surging Strikes qobiliyati yaqin atrofdagi ikki dushmanni bir vaqtda karaxt qiladi. U yaxshilangan Pass Royale’da mavjud.',
          'Yangi Evolution: Electro Giant. “Shocktober: The Movie!” Album tadbirini (6-oktabr – 2-noyabr, 3-arenadan boshlab) tugatganda bepul ochiladi; tadbir yana emote va minora skinini ham beradi.',
          'Nishonlar: Spooky Chess ligasida (5–19-oktabr) ikkitagacha va Power Surge global turnirida (20–25-oktabr) bitta; har birida eng yaxshi 10 000 talikka kirganlar uchun qoʻshimcha nishon bor.',
          '20 gʻalaba sinovi 26-oktabrdan 2-noyabrgacha qaytadi: 3 tadan kam magʻlubiyat bilan 20 gʻalaba uchun emote beriladi.'],
  'impact': 'Har bir oʻyinchi bepul olishi mumkin boʻlgan Evolution bir akkauntni boshqasidan deyarli farqlamaydi. Eng yaxshi 10 000 talik nishonlarini olish qiyinroq va ular profilda mahoratni koʻrsatadi. Tadqiqotimizga koʻra, King Tower darajasi va kartalar darajasi asosiy qiymat omillari boʻlib qolmoqda.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — oktabrda Portal Pendant jihozi va yangi Hero skinlari',
  'desc': 'Cosmic Curse: Portal Panic 2026-yil 1–31-oktabr kunlari oʻtadi: Medal tadbiridan (8–25-oktabr) Minion Prince uchun Epic jihoz Portal Pendant, Hero skinlari va Gold Pass skini.',
  'lead': 'Supercell Clash-O-Ween mavsumi “Cosmic Curse: Portal Panic”ni 2026-yil 1-oktabrda eʼlon qildi; u 31-oktabrgacha davom etadi.',
  'new': ['Portal Panic Medal tadbiri, 8–25-oktabr, Town Hall 6 va undan yuqori: janglarda yigʻilgan Sour Elixir mukofotlar va Rift Medals’ni ochadi, ularga Trader doʻkonidan yangi Portal Pendant — Minion Prince uchun Epic jihoz — olinadi (doʻkon 27-oktabrgacha ochiq).',
          'Gold Pass, 1–31-oktabr: mavsumning eksklyuziv Hero skini — Shroud Queen, muqobil variant — Ghost Champion.',
          'Oy davomida chiqadigan Hero skinlari: Savage King (5-oktabr), Nasty Prince (7-oktabr), Terror Champion (9-oktabr), Behemoth Duke (11-oktabr) va Spider Warden (13-oktabr); Cosmic Portals XL manzarasi 3-oktabrdan.',
          'Mavsum davomida vaqtinchalik qoʻshin Totem Thrower qoʻshiladi, 2025-yilgi Cosmic Curse kosmetikasi esa 15-oktabrda qaytadi.'],
  'impact': 'Hero jihozlari va Hero skinlari akkauntda qoladi, shuning uchun akkaunt koʻrsatadigan narsalarga qoʻshiladi. Tadqiqotimizga koʻra, Town Hall darajasi va qahramonlarning shu daraja uchun qanchalik toʻliq rivojlangani asosiy qiymat omillari boʻlib qolmoqda; mavsumiy skinlar ikkinchi darajali tafsilot.'},
 'coc-ore': {
  'title': 'Clash of Clans Ore uchun Gem narxlarini tushirdi: Starry Ore 35 dan 20 Gemga',
  'desc': 'Supercell 2026-yil 2-oktabrda Ore uchun yangi asosiy Gem narxlarini eʼlon qildi: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Epic jihozni maksimal darajaga koʻtarish taxminan ikki baravar kam Gem talab qiladi.',
  'lead': '2026-yil 2-oktabrda Supercell Clash of Clans’da Ore uchun Gem narxlari pasayishini eʼlon qildi — bu vaqtinchalik chegirma emas, yangi asosiy narx.',
  'new': ['Yangi narxlar: Shiny Ore 1 Gem → 0,5 Gem, Glowy Ore 5 → 3 Gem, Starry Ore 35 → 20 Gem.',
          'Supercell maʼlumotiga koʻra, bitta Epic jihozni maksimal darajaga koʻtarishning Gem narxi taxminan ikki baravar kamayadi.',
          'Trader yangi narxlardan iyuldan beri foydalanmoqda; Medal doʻkoni oktabrdagi Medal tadbirida oʻtadi, keyingi toʻliq yangilanish esa ularni oʻyinning hamma joyida standart qiladi.',
          'Ore iqtisodiyotidagi yana oʻzgarishlar oktabr oxiriga vaʼda qilingan.'],
  'impact': 'Maksimal darajadagi Hero jihoziga erishish arzonlashadi, shuning uchun u yuqori Town Hall akkauntlarida koʻproq uchrashi mumkin. Tadqiqotimizga koʻra, Town Hall darajasi va qahramonlar rivoji asosiy qiymat omillari boʻlib qolmoqda.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: har bir mintaqadagi sakkiz jamoa qanday tanlanadi',
  'desc': 'Supercell 2026-yil 1-oktabrda jamoalar BSC 2027’ga qanday chiqishini tushuntirdi: 2026-yil reytingidan har bir mintaqaga oltita toʻgʻridan-toʻgʻri taklif va 2027-yil 16–17-yanvardagi BSC Invitational’dan ikkita oʻrin.',
  'lead': '2026-yil 1-oktabrda Supercell Brawl Stars Championship 2027 saralash yoʻlini eʼlon qildi.',
  'new': ['BSC 2027’da toʻrt mintaqaning har birida sakkiztadan jamoa bor: APAC, EMEA, Janubiy Amerika va Shimoliy Amerika.',
          'Har bir mintaqaning 2026-yilgi BSC Leaderboard’idagi eng yaxshi olti jamoa toʻgʻridan-toʻgʻri taklif oladi va koʻpi bilan bitta oʻyinchini almashtirishi mumkin.',
          'Har bir mintaqadagi oxirgi ikki oʻrin 2027-yil 16–17-yanvardagi BSC Invitational’da hal boʻladi: 7–10-oʻrindagi jamoalar oʻynaydi, EMEA’da esa 7–14-oʻrindagilar.',
          'Takliflar 2026-yil 23-noyabrda yuboriladi, jamoalar 20-dekabrgacha javob berishi kerak; Supercell sanalar oʻzgarishi mumkinligini taʼkidlaydi. Yangi jamoalar oʻyin ichidagi Championship Challenge va Brawl Stars Challengers’dan boshlaydi.'],
  'impact': 'Kibersport saralashi oddiy akkaunt qiymatini oʻzgartirmaydi. Tadqiqotimizga koʻra, eʼlonlardagi narx hali ham kuboklar, brawlerlar va ularning Power Level darajasiga bogʻliq.'},
}},
}
