# News batch 3: ru, es, pt, id (from news_text_b3_en.py, facts unchanged)
TEXT = {
'ru': {'a': {
 'cr-shock': {
  'title': 'Сезон Shocktober в Clash Royale: герой Электромаг и бесплатная эволюция Электрогиганта',
  'desc': 'Сезон Shocktober идёт с 6 октября по 2 ноября 2026 года: герой Электромаг в улучшенном Pass Royale, эволюция Электрогиганта бесплатно за альбомное событие, новые значки.',
  'lead': 'Supercell объявила сезон Shocktober 5 октября 2026 года; он идёт с 6 октября по 2 ноября.',
  'new': ['Новый герой — Электромаг (Electro Wizard): способность Surging Strikes оглушает сразу двух ближайших врагов. Он доступен в улучшенном Pass Royale.',
          'Новая эволюция — Электрогигант (Electro Giant). Её дают бесплатно за завершение альбомного события «Shocktober: The Movie!» (6 октября – 2 ноября, с арены 3); там же эмодзи и скин башни.',
          'Значки: до двух в лиге Spooky Chess (5–19 октября) и один в глобальном турнире Power Surge (20–25 октября); за место в топ-10 000 в каждом дают дополнительный значок.',
          'Испытание «20 побед» возвращается с 26 октября по 2 ноября: 20 побед при менее чем 3 поражениях — за это дают эмодзи.'],
  'impact': 'Эволюция, которую бесплатно может получить каждый игрок, почти не отличает один аккаунт от другого. Значки за топ-10 000 получить сложнее, и в профиле они говорят о навыке. По нашим данным, главными факторами стоимости остаются уровень Королевской башни и уровни карт.'},
 'coc-cosmic': {
  'title': 'Clash of Clans, Cosmic Curse: Portal Panic — снаряжение Portal Pendant и новые скины героев в октябре',
  'desc': 'Cosmic Curse: Portal Panic идёт с 1 по 31 октября 2026 года: эпическое снаряжение Portal Pendant для Принца миньонов за медальное событие (8–25 октября), скины героев и скин Золотого пропуска.',
  'lead': 'Supercell объявила сезон Clash-O-Ween «Cosmic Curse: Portal Panic» 1 октября 2026 года; он идёт до 31 октября.',
  'new': ['Медальное событие Portal Panic, 8–25 октября, с ратуши 6: Sour Elixir из боёв открывает награды и Rift Medals, за которые у Торговца покупается новое Portal Pendant — эпическое снаряжение для Принца миньонов (магазин открыт до 27 октября).',
          'Золотой пропуск, 1–31 октября: эксклюзивный скин сезона — Shroud Queen, альтернативный вариант — Ghost Champion.',
          'Скины героев в течение месяца: Savage King (5 октября), Nasty Prince (7 октября), Terror Champion (9 октября), Behemoth Duke (11 октября) и Spider Warden (13 октября); декорация Cosmic Portals XL — с 3 октября.',
          'На сезон добавлен временный юнит Totem Thrower, а 15 октября возвращается косметика Cosmic Curse 2025 года.'],
  'impact': 'Снаряжение и скины героев остаются на аккаунте, поэтому добавляют к тому, что аккаунт показывает. По нашим данным, главными факторами стоимости остаются уровень ратуши и то, насколько прокачаны герои для этого уровня; сезонные скины — второстепенная деталь.'},
 'coc-ore': {
  'title': 'Clash of Clans снижает цены на руду в кристаллах: звёздная руда — с 35 до 20',
  'desc': 'Supercell 2 октября 2026 года объявила новые базовые цены на руду в кристаллах: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Прокачка эпического снаряжения до максимума стоит примерно вдвое меньше кристаллов.',
  'lead': '2 октября 2026 года Supercell объявила о снижении цен на руду в кристаллах в Clash of Clans — как о новой базовой цене, а не временной распродаже.',
  'new': ['Новые цены: Shiny Ore 1 кристалл → 0,5, Glowy Ore 5 → 3, Starry Ore 35 → 20 кристаллов.',
          'По словам Supercell, прокачка одного эпического снаряжения до максимума теперь стоит примерно вдвое меньше кристаллов.',
          'Торговец использует новые цены с июля; магазин медалей перейдёт на них в октябрьском медальном событии, а со следующим крупным обновлением они станут стандартом во всей игре.',
          'Ещё изменения в экономике руды обещаны позже в октябре.'],
  'impact': 'Максимально прокачанное снаряжение героев становится дешевле получить, поэтому на аккаунтах с высокой ратушей оно может встречаться чаще. По нашим данным, главными факторами стоимости остаются уровень ратуши и прокачка героев.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: как отбирают восемь команд в каждом регионе',
  'desc': 'Supercell 1 октября 2026 года объяснила, как команды попадают в BSC 2027: шесть прямых приглашений на регион по рейтингу 2026 года и два места через BSC Invitational 16–17 января 2027 года.',
  'lead': '1 октября 2026 года Supercell опубликовала путь квалификации в Brawl Stars Championship 2027.',
  'new': ['В BSC 2027 по восемь команд в каждом из четырёх регионов: APAC, EMEA, Южная Америка и Северная Америка.',
          'Шесть лучших команд рейтинга BSC 2026 каждого региона получают прямое приглашение и могут заменить не больше одного игрока.',
          'Последние два места в регионе разыгрываются на BSC Invitational 16–17 января 2027 года: играют команды с 7-го по 10-е место, в EMEA — с 7-го по 14-е.',
          'Приглашения рассылают 23 ноября 2026 года, ответить нужно до 20 декабря; Supercell отмечает, что даты могут измениться. Новые команды начинают с внутриигрового Championship Challenge и Brawl Stars Challengers.'],
  'impact': 'Киберспортивная квалификация не меняет стоимость обычного аккаунта. По нашим данным, цену в объявлениях по-прежнему определяют трофеи, бойцы и их уровни силы.'},
}},
'es': {'a': {
 'cr-shock': {
  'title': 'Temporada Shocktober de Clash Royale: Héroe Mago Eléctrico y Evolución gratis del Gigante Eléctrico',
  'desc': 'La temporada Shocktober va del 6 de octubre al 2 de noviembre de 2026: Héroe Mago Eléctrico en el Pass Royale mejorado, Evolución del Gigante Eléctrico gratis con el evento de álbum y nuevas insignias.',
  'lead': 'Supercell anunció la temporada Shocktober el 5 de octubre de 2026; va del 6 de octubre al 2 de noviembre.',
  'new': ['Nuevo Héroe: Mago Eléctrico (Electro Wizard), cuya habilidad Surging Strikes aturde a dos enemigos cercanos a la vez. Está en el Pass Royale mejorado.',
          'Nueva Evolución: Gigante Eléctrico (Electro Giant). Se desbloquea gratis al completar el evento de álbum «Shocktober: The Movie!» (6 de octubre – 2 de noviembre, desde la Arena 3), que también da un emote y un aspecto de torre.',
          'Insignias: hasta dos en la liga Spooky Chess (5–19 de octubre) y una en el Torneo Global Power Surge (20–25 de octubre), cada uno con una insignia extra por acabar entre los 10 000 primeros.',
          'El Desafío de 20 victorias vuelve del 26 de octubre al 2 de noviembre: 20 victorias con menos de 3 derrotas a cambio de un emote.'],
  'impact': 'Una Evolución que cualquier jugador puede conseguir gratis apenas distingue una cuenta de otra. Las insignias por acabar entre los 10 000 primeros son más difíciles de obtener y muestran habilidad en el perfil. Según nuestra investigación, el nivel de la Torre del Rey y el nivel de las cartas siguen siendo los principales factores de valor.'},
 'coc-cosmic': {
  'title': 'Clash of Clans, Cosmic Curse: Portal Panic — equipamiento Portal Pendant y nuevos aspectos de héroe en octubre',
  'desc': 'Cosmic Curse: Portal Panic va del 1 al 31 de octubre de 2026: el equipamiento épico Portal Pendant para el Príncipe Esbirro en el evento de medallas (8–25 de octubre), aspectos de héroe y un aspecto del Pase de Oro.',
  'lead': 'Supercell anunció la temporada de Clash-O-Ween «Cosmic Curse: Portal Panic» el 1 de octubre de 2026; dura hasta el 31 de octubre.',
  'new': ['Evento de medallas Portal Panic, 8–25 de octubre, desde Ayuntamiento 6: el Sour Elixir obtenido en batallas desbloquea recompensas y Rift Medals, con las que se compra en la tienda del Mercader el nuevo Portal Pendant, equipamiento épico para el Príncipe Esbirro (tienda abierta hasta el 27 de octubre).',
          'Pase de Oro, 1–31 de octubre: el aspecto de héroe exclusivo de la temporada es Shroud Queen, con Ghost Champion como alternativa.',
          'Aspectos de héroe que llegan durante el mes: Savage King (5 de octubre), Nasty Prince (7 de octubre), Terror Champion (9 de octubre), Behemoth Duke (11 de octubre) y Spider Warden (13 de octubre); el escenario Cosmic Portals XL desde el 3 de octubre.',
          'Se suma una tropa temporal, Totem Thrower, y los cosméticos de Cosmic Curse de 2025 vuelven el 15 de octubre.'],
  'impact': 'El equipamiento y los aspectos de héroe se quedan en la cuenta, así que suman a lo que la cuenta muestra. Según nuestra investigación, el nivel del Ayuntamiento y lo completos que estén los héroes para ese nivel siguen siendo los principales factores de valor; los aspectos de temporada son un detalle secundario.'},
 'coc-ore': {
  'title': 'Clash of Clans baja el precio en gemas del mineral: el mineral estelar pasa de 35 a 20 gemas',
  'desc': 'Supercell anunció el 2 de octubre de 2026 nuevos precios base en gemas para el mineral: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Llevar al máximo un equipamiento épico cuesta más o menos la mitad de gemas.',
  'lead': 'El 2 de octubre de 2026 Supercell anunció precios más bajos en gemas para el mineral en Clash of Clans, como nuevo precio base y no como oferta temporal.',
  'new': ['Nuevos precios: Shiny Ore 1 gema → 0,5 gemas, Glowy Ore 5 → 3 gemas, Starry Ore 35 → 20 gemas.',
          'Supercell indica que el coste en gemas de llevar al máximo un equipamiento épico baja aproximadamente a la mitad.',
          'El Mercader usa los nuevos precios desde julio; la tienda de medallas los adopta en el evento de medallas de octubre y la próxima actualización completa los hará estándar en todo el juego.',
          'Se prometen más cambios en la economía del mineral a lo largo de octubre.'],
  'impact': 'El equipamiento de héroe al máximo resulta más barato de conseguir, así que puede volverse más habitual en cuentas de Ayuntamiento alto. Según nuestra investigación, el nivel del Ayuntamiento y el progreso de los héroes siguen siendo los principales factores de valor.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: cómo se eligen los ocho equipos de cada región',
  'desc': 'Supercell explicó el 1 de octubre de 2026 cómo llegan los equipos a la BSC 2027: seis invitaciones directas por región según la clasificación de 2026 y dos plazas en el BSC Invitational del 16–17 de enero de 2027.',
  'lead': 'El 1 de octubre de 2026 Supercell publicó la ruta de clasificación para el Brawl Stars Championship 2027.',
  'new': ['La BSC 2027 tiene ocho equipos en cada una de cuatro regiones: APAC, EMEA, Sudamérica y Norteamérica.',
          'Los seis mejores equipos de la clasificación BSC 2026 de cada región reciben invitación directa y pueden cambiar como máximo un jugador.',
          'Las dos últimas plazas por región se deciden en el BSC Invitational del 16–17 de enero de 2027: juegan los equipos del 7.º al 10.º puesto, y del 7.º al 14.º en EMEA.',
          'Las invitaciones se envían el 23 de noviembre de 2026 y los equipos deben responder antes del 20 de diciembre; Supercell avisa de que las fechas pueden cambiar. Los equipos nuevos empiezan por el Championship Challenge del juego y Brawl Stars Challengers.'],
  'impact': 'La clasificación de esports no cambia lo que vale una cuenta normal. Según nuestra investigación, los trofeos, los brawlers y sus niveles de fuerza siguen marcando el precio en los anuncios.'},
}},
'pt': {'a': {
 'cr-shock': {
  'title': 'Temporada Shocktober do Clash Royale: Herói Mago Elétrico e Evolução grátis do Gigante Elétrico',
  'desc': 'A temporada Shocktober vai de 6 de outubro a 2 de novembro de 2026: Herói Mago Elétrico no Pass Royale aprimorado, Evolução do Gigante Elétrico grátis pelo evento de álbum e novas insígnias.',
  'lead': 'A Supercell anunciou a temporada Shocktober em 5 de outubro de 2026; ela vai de 6 de outubro a 2 de novembro.',
  'new': ['Novo Herói: Mago Elétrico (Electro Wizard), cuja habilidade Surging Strikes atordoa dois inimigos próximos de uma vez. Ele está no Pass Royale aprimorado.',
          'Nova Evolução: Gigante Elétrico (Electro Giant). É liberada de graça ao completar o evento de álbum “Shocktober: The Movie!” (6 de outubro – 2 de novembro, a partir da Arena 3), que também dá um emote e um visual de torre.',
          'Insígnias: até duas na liga Spooky Chess (5–19 de outubro) e uma no Torneio Global Power Surge (20–25 de outubro), cada um com uma insígnia extra para quem terminar entre os 10.000 melhores.',
          'O Desafio de 20 Vitórias volta de 26 de outubro a 2 de novembro: 20 vitórias com menos de 3 derrotas valem um emote.'],
  'impact': 'Uma Evolução que todo jogador pode ganhar de graça quase não diferencia uma conta da outra. Insígnias por terminar entre os 10.000 melhores são mais difíceis de conseguir e mostram habilidade no perfil. Na nossa pesquisa, o nível da Torre do Rei e o nível das cartas continuam sendo os principais fatores de valor.'},
 'coc-cosmic': {
  'title': 'Clash of Clans, Cosmic Curse: Portal Panic — equipamento Portal Pendant e novos visuais de herói em outubro',
  'desc': 'Cosmic Curse: Portal Panic vai de 1 a 31 de outubro de 2026: o equipamento épico Portal Pendant para o Príncipe Servo no evento de medalhas (8–25 de outubro), visuais de herói e um visual do Passe de Ouro.',
  'lead': 'A Supercell anunciou a temporada de Clash-O-Ween “Cosmic Curse: Portal Panic” em 1 de outubro de 2026; ela vai até 31 de outubro.',
  'new': ['Evento de medalhas Portal Panic, 8–25 de outubro, a partir do Centro de Vila 6: o Sour Elixir coletado em batalhas libera recompensas e Rift Medals, que compram na loja do Comerciante o novo Portal Pendant, equipamento épico para o Príncipe Servo (loja aberta até 27 de outubro).',
          'Passe de Ouro, 1–31 de outubro: o visual de herói exclusivo da temporada é Shroud Queen, com Ghost Champion como opção alternativa.',
          'Visuais de herói que chegam ao longo do mês: Savage King (5 de outubro), Nasty Prince (7 de outubro), Terror Champion (9 de outubro), Behemoth Duke (11 de outubro) e Spider Warden (13 de outubro); o cenário Cosmic Portals XL a partir de 3 de outubro.',
          'Uma tropa temporária, Totem Thrower, entra na temporada, e os cosméticos do Cosmic Curse de 2025 voltam em 15 de outubro.'],
  'impact': 'Equipamentos e visuais de herói ficam na conta, então somam ao que a conta mostra. Na nossa pesquisa, o nível do Centro de Vila e o quanto os heróis estão completos para esse nível continuam sendo os principais fatores de valor; visuais de temporada são um detalhe secundário.'},
 'coc-ore': {
  'title': 'Clash of Clans reduz o preço do minério em gemas: minério estelar cai de 35 para 20 gemas',
  'desc': 'A Supercell anunciou em 2 de outubro de 2026 novos preços base do minério em gemas: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Levar um equipamento épico ao máximo custa cerca de metade das gemas.',
  'lead': 'Em 2 de outubro de 2026 a Supercell anunciou preços menores em gemas para o minério no Clash of Clans — como novo preço base, não como promoção temporária.',
  'new': ['Novos preços: Shiny Ore 1 gema → 0,5 gema, Glowy Ore 5 → 3 gemas, Starry Ore 35 → 20 gemas.',
          'Segundo a Supercell, o custo em gemas para levar um equipamento épico ao máximo cai aproximadamente pela metade.',
          'O Comerciante usa os novos preços desde julho; a loja de medalhas passa a usá-los no evento de medalhas de outubro, e a próxima atualização completa os torna padrão em todo o jogo.',
          'Mais mudanças na economia do minério foram prometidas para o fim de outubro.'],
  'impact': 'Equipamento de herói no máximo fica mais barato de alcançar, então pode se tornar mais comum em contas de Centro de Vila alto. Na nossa pesquisa, o nível do Centro de Vila e o progresso dos heróis continuam sendo os principais fatores de valor.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: como são escolhidas as oito equipes de cada região',
  'desc': 'A Supercell explicou em 1 de outubro de 2026 como as equipes chegam à BSC 2027: seis convites diretos por região pelo ranking de 2026 e duas vagas no BSC Invitational de 16–17 de janeiro de 2027.',
  'lead': 'Em 1 de outubro de 2026 a Supercell publicou o caminho de classificação para o Brawl Stars Championship 2027.',
  'new': ['A BSC 2027 tem oito equipes em cada uma de quatro regiões: APAC, EMEA, América do Sul e América do Norte.',
          'As seis melhores equipes do ranking BSC 2026 de cada região recebem convite direto e podem trocar no máximo um jogador.',
          'As duas últimas vagas por região são decididas no BSC Invitational de 16–17 de janeiro de 2027: jogam as equipes do 7º ao 10º lugar, e do 7º ao 14º na EMEA.',
          'Os convites saem em 23 de novembro de 2026 e as equipes precisam responder até 20 de dezembro; a Supercell avisa que as datas podem mudar. Equipes novas começam pelo Championship Challenge dentro do jogo e pelo Brawl Stars Challengers.'],
  'impact': 'A classificação de esports não muda quanto vale uma conta comum. Na nossa pesquisa, troféus, brawlers e seus níveis de força continuam definindo o preço nos anúncios.'},
}},
'id': {'a': {
 'cr-shock': {
  'title': 'Musim Shocktober Clash Royale: Hero Electro Wizard dan Evolusi Electro Giant gratis',
  'desc': 'Musim Shocktober berlangsung 6 Oktober – 2 November 2026: Hero Electro Wizard di Pass Royale yang ditingkatkan, Evolusi Electro Giant gratis lewat Event Album, dan lencana baru.',
  'lead': 'Supercell mengumumkan musim Shocktober pada 5 Oktober 2026; musim ini berlangsung dari 6 Oktober sampai 2 November.',
  'new': ['Hero baru: Electro Wizard, dengan kemampuan Surging Strikes yang membuat dua musuh terdekat pingsan sekaligus. Hero ini ada di Pass Royale yang ditingkatkan.',
          'Evolusi baru: Electro Giant. Bisa dibuka gratis dengan menyelesaikan Event Album “Shocktober: The Movie!” (6 Oktober – 2 November, mulai Arena 3), yang juga memberi emote dan skin menara.',
          'Lencana: hingga dua di liga Spooky Chess (5–19 Oktober) dan satu di Turnamen Global Power Surge (20–25 Oktober), masing-masing dengan lencana tambahan untuk peringkat 10.000 besar.',
          'Tantangan 20 Kemenangan kembali pada 26 Oktober – 2 November: 20 kemenangan dengan kurang dari 3 kekalahan untuk mendapatkan emote.'],
  'impact': 'Evolusi yang bisa didapat gratis oleh semua pemain hampir tidak membedakan satu akun dari akun lain. Lencana peringkat 10.000 besar lebih sulit didapat dan menunjukkan kemampuan di profil. Dalam riset kami, level King Tower dan level kartu tetap menjadi faktor nilai utama.'},
 'coc-cosmic': {
  'title': 'Clash of Clans Cosmic Curse: Portal Panic — perlengkapan Portal Pendant dan skin Hero baru di bulan Oktober',
  'desc': 'Cosmic Curse: Portal Panic berlangsung 1–31 Oktober 2026: Perlengkapan Epik Portal Pendant untuk Minion Prince dari Event Medali (8–25 Oktober), skin Hero, dan skin Gold Pass.',
  'lead': 'Supercell mengumumkan musim Clash-O-Ween “Cosmic Curse: Portal Panic” pada 1 Oktober 2026; musim ini berlangsung sampai 31 Oktober.',
  'new': ['Event Medali Portal Panic, 8–25 Oktober, Town Hall 6 ke atas: Sour Elixir dari pertempuran membuka hadiah dan Rift Medals, yang bisa ditukar di Toko Trader dengan Portal Pendant baru — Perlengkapan Epik untuk Minion Prince (toko buka sampai 27 Oktober).',
          'Gold Pass, 1–31 Oktober: skin Hero eksklusif musim ini adalah Shroud Queen, dengan Ghost Champion sebagai pilihan alternatif.',
          'Skin Hero yang hadir selama bulan ini: Savage King (5 Oktober), Nasty Prince (7 Oktober), Terror Champion (9 Oktober), Behemoth Duke (11 Oktober), dan Spider Warden (13 Oktober); Scenery Cosmic Portals XL mulai 3 Oktober.',
          'Pasukan sementara Totem Thrower hadir selama musim ini, dan kosmetik Cosmic Curse 2025 kembali pada 15 Oktober.'],
  'impact': 'Perlengkapan dan skin Hero tetap melekat di akun, sehingga menambah apa yang ditampilkan akun. Dalam riset kami, level Town Hall dan seberapa lengkap Hero untuk level itu tetap menjadi faktor nilai utama; skin musiman hanyalah detail tambahan.'},
 'coc-ore': {
  'title': 'Clash of Clans menurunkan harga Ore dalam Gem: Starry Ore dari 35 menjadi 20 Gem',
  'desc': 'Supercell mengumumkan pada 2 Oktober 2026 harga dasar baru Ore dalam Gem: Shiny 1 → 0,5, Glowy 5 → 3, Starry 35 → 20. Memaksimalkan Perlengkapan Epik kini butuh kira-kira setengah Gem.',
  'lead': 'Pada 2 Oktober 2026 Supercell mengumumkan harga Gem yang lebih rendah untuk Ore di Clash of Clans — sebagai harga dasar baru, bukan diskon sementara.',
  'new': ['Harga baru: Shiny Ore 1 Gem → 0,5 Gem, Glowy Ore 5 → 3 Gem, Starry Ore 35 → 20 Gem.',
          'Menurut Supercell, biaya Gem untuk memaksimalkan satu Perlengkapan Epik turun kira-kira setengahnya.',
          'Trader sudah memakai harga baru sejak Juli; toko Medali menyusul di Event Medali Oktober, dan pembaruan besar berikutnya menjadikannya harga standar di seluruh game.',
          'Perubahan lain pada ekonomi Ore dijanjikan menyusul pada akhir Oktober.'],
  'impact': 'Perlengkapan Hero level maksimal menjadi lebih murah untuk dicapai, sehingga bisa makin umum di akun Town Hall tinggi. Dalam riset kami, level Town Hall dan progres Hero tetap menjadi faktor nilai utama.'},
 'bs-path27': {
  'title': 'Brawl Stars Championship 2027: cara delapan tim tiap region dipilih',
  'desc': 'Supercell menjelaskan pada 1 Oktober 2026 cara tim masuk BSC 2027: enam undangan langsung per region dari peringkat 2026 dan dua slot dari BSC Invitational pada 16–17 Januari 2027.',
  'lead': 'Pada 1 Oktober 2026 Supercell menerbitkan jalur kualifikasi Brawl Stars Championship 2027.',
  'new': ['BSC 2027 diikuti delapan tim di masing-masing dari empat region: APAC, EMEA, Amerika Selatan, dan Amerika Utara.',
          'Enam tim teratas di Leaderboard BSC 2026 tiap region mendapat undangan langsung dan boleh mengganti paling banyak satu pemain.',
          'Dua slot terakhir per region ditentukan di BSC Invitational pada 16–17 Januari 2027: tim peringkat 7–10 bertanding, dan peringkat 7–14 di EMEA.',
          'Undangan dikirim pada 23 November 2026 dan tim harus menjawab paling lambat 20 Desember; Supercell mencatat tanggal bisa berubah. Tim baru memulai dari Championship Challenge di dalam game dan Brawl Stars Challengers.'],
  'impact': 'Kualifikasi esports tidak mengubah nilai akun biasa. Dalam riset kami, trofi, brawler, dan Power Level mereka tetap menjadi dasar harga di iklan.'},
}},
}
