# News translations: tr, ar (from news_data.py 'en', facts unchanged)
TEXT = {
'tr': {
 'ui': {
  'news': 'Haberler', 'news_title': 'Hesap değerini etkileyen oyun haberleri',
  'news_lead': 'Oyun yayıncılarından resmî güncellemeler — her biri yayıncının kendi duyurusuyla karşılaştırıldı; hesap değeri için ne anlama geldiğine dair kısa bir notla.',
  'game_title': '{game} haberleri', 'game_lead': 'Bir hesabın değerini etkileyen resmî {game} güncellemeleri. Her yazıda yayıncının duyurusunun bağlantısı var.',
  'published': 'Yayınlanma', 'source': 'Resmî kaynak', 'by_on': '{pub}, {date}', 'whats_new': 'Neler yeni',
  'impact': 'Hesap değeri için anlamı', 'more': 'Diğer {game} haberleri', 'all': 'Tüm haberler',
  'calc': '{game}: değer hesaplayıcı ve piyasa raporu', 'read': 'Oku', 'latest': 'Son {game} haberleri',
  'note': 'GameAccountValue hesap satın almaz, satmaz ve aracılık etmez. Haberler yalnızca bilgi amacıyla yayıncı duyurularından özetlenmiştir.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna ve Vodyanitsa geldi, yıl dönümü ödülleri kesinleşti',
   'desc': '"A Rekviem for the Underworld" adlı 7.1 sürümü 23 Eylül 2026’da iki yeni 5 yıldızlı karakter, iki 5 yıldızlı silah ve altıncı yıl dönümü ödülleriyle yayınlandı.',
   'lead': 'HoYoverse, Genshin Impact’in altıncı yıl dönümünü de getiren 7.1 sürümünü, "A Rekviem for the Underworld"ü, 23 Eylül 2026’da yayınladı.',
   'new': ['İki yeni 5 yıldızlı karakter: Vesna (Anemo, kılıç) ve Vodyanitsa (Hydro, katalizör).',
           'Yeni silahlar: Beyond the Chrysalis (5★ kılıç), Hymn of the Maelstrom (5★ katalizör) ve New Bough (4★ kılıç).',
           'HoYoverse’ün duyurduğu yıl dönümü ödülleri: davet edilecek iki 5 yıldızlı karakter, Intertwined Fate ×10, Primogem ×1.600 ve Genesis Crystal ilk yükleme bonusunun sıfırlanması.',
           'Güncelleme bakımı 23 Eylül’de 06.00’da (UTC+8) başladı.'],
   'impact': 'Araştırmamıza göre sınırlı 5 yıldızlı karakterlerin sayısı, takımyıldızları ve imza silahları Genshin hesap değerinin başlıca belirleyicilerinden. Yıl dönümünde herkese ücretsiz verilen karakterler, bir hesabı sınırlı afiş karakterleri kadar özel kılmaz.'},
  'mc-live': {
   'title': 'Minecraft Live: 14 yılı aşkın sürenin ilk yeni boyutu The Sift, Java ve Bedrock’a geliyor',
   'desc': '26 Eylül 2026’daki Minecraft Live, gelecek yıl Java ve Bedrock’a gelecek dördüncü boyut The Sift’i, Dungeons II’yi ve Wilderness Bound güncellemesini tanıttı.',
   'lead': 'Mojang Studios, 26 Eylül 2026’daki Minecraft Live’da oyunun dördüncü boyutu The Sift’in gelecek yıl Minecraft Java ve Bedrock Edition’a geleceğini duyurdu.',
   'new': ['The Sift, 14 yılı aşkın sürenin ilk yeni boyutu; Overworld, Nether ve End’e katılıyor.',
           'İlk kez, Mojang’ın 29 Eylül 2026 için tarih verdiği Minecraft Dungeons II’de görünüyor.',
           'Tema parkı Minecraft World, 2027’de Londra’da açılıyor.',
           'Wilderness Bound güncellemesi 15 Eylül’de benekli orman, saman yataklar, terk edilmiş kamplar ve minderlerle geldi.'],
   'impact': 'Minecraft hesapları oyun içeriğine göre değil; hesap türüne (Java veya Bedrock), kullanıcı adına ve pelerinlere göre değerlenir. Bu tür güncellemeler oyuncuların neler yapabileceğini değiştirir, hesabın değerini değil.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": sınırlı UGC eşyalar ve Roblox Plus’a özel ödüller (17–28 Eylül)',
   'desc': 'The Hunt: Roblox 20, 17–28 Eylül 2026 arasında UGC ödülleri, sınırlı sayıda UGC eşyalar ve Roblox Plus abonelerine özel üç eşyayla düzenlendi.',
   'lead': 'Roblox 20. yılını, 17–28 Eylül 2026 arasında tüm platformda düzenlenen The Hunt: Roblox 20 etkinliğiyle kutladı.',
   'new': ['Oyuncular "Year Zero"dan başlayarak her yıl için bir görevle Roblox’un 20 yıllık tarihinde ilerledi; 20 yılın tamamını bitirmek 20 oyun daha içeren "Year Infinity"yi açtı.',
           'Görevler UGC eşyalar verdi; etkinlik boyunca sınırlı sayıda UGC eşyalar da sunuldu.',
           'Roblox Plus aboneleri üç özel sanal eşya aldı; Classic uygulama teması, klasik avatar arka planı ve profil çerçevesi etkinlikten sonra da onlarda kalıyor.',
           'Classic uygulama teması etkinlik süresince herkese ücretsizdi.'],
   'impact': 'Yalnızca bir etkinlik sırasında kazanılabilen eşyalar, bir değerlemenin dikkate aldığı şeylerden biridir. Roblox bu eşyaların adını duyuruda vermedi; bu yüzden bu site gerçek ilanlar oluşana kadar onlara fiyat biçmiyor.'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox içerik üreticileri bir yılda yaklaşık 1,7 milyar dolar kazandı; Roblox Wallet duyuruldu',
   'desc': 'Roblox, RDC 2026’da içerik üreticilerinin 12 ayda yaklaşık 1,7 milyar dolar kazandığını açıkladı ve ödemeler için Roblox Wallet ile Roblox Card’ı duyurdu.',
   'lead': 'Roblox, geliştirici konferansı RDC 2026’da (11 Eylül 2026 duyurusu) içerik üreticisi kazanç rakamlarını ve yeni ödeme araçlarını paylaştı.',
   'new': ['İçerik üreticileri DevEx’in 2013’te başlamasından bu yana 5 milyar dolardan fazla, 30 Haziran 2026’ya kadarki 12 ayda ise yaklaşık 1,7 milyar dolar kazandı.',
           'Roblox Plus teşvikleri ilk dört ayında (17 Ağustos 2026’ya kadar) içerik üreticilerine 300 milyonu aşkın Robux kazandırdı.',
           'Airwallex US ile işletilen ödeme hesabı Roblox Wallet, gerçek parayla günlük ödeme sunacak — önce 2026 sonunda ABD’deki uygun, 18 yaş üstü bağımsız üreticiler için, 2027’de uluslararası.',
           'Wallet’a bağlı bir Roblox Card 2027’den itibaren planlanıyor.'],
   'impact': 'Bu değişiklikler oyuncu hesaplarını değil, üretici ödemelerini ilgilendiriyor: duyuru Robux fiyatlarını, sınırlı eşyaları veya takası değiştirmedi. Roblox hesaplayıcımızın dikkate aldığı şey hâlâ Robux bakiyesi ve sınırlı eşyalar.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: Clash Squad’a dört yeni silah, Prime Diamond ve Kenta yenilemesi',
   'desc': 'Garena’nın OB55 yama notları (10 Eylül 2026), 1 Ekim’den itibaren Clash Squad’a M7, Skorp, RPK ve Hawk’ı ekliyor, Prime Diamond’ı getiriyor ve Kenta’yı yeniliyor.',
   'lead': 'Garena, Free Fire’ın OB55 yama notlarını 10 Eylül 2026’da yayınladı; silah değişiklikleri 1 Ekim’de yürürlüğe giriyor.',
   'new': ['1 Ekim’den itibaren yeni Clash Squad silahları: M7 (1.600 CS Cash), Skorp (1.500), RPK (1.500) ve Hawk (1.700).',
           'Prime Diamond: aylık harcamaya göre kazanılan elmaslar, herhangi bir yüklemeden sonra ertesi ay alınabiliyor.',
           'Kenta baştan yenilendi; Morse, Luna ve Wukong denge değişiklikleri aldı.',
           '1 Ekim’den itibaren silah sınıflarına göre hareketlilik değişiyor: SMG’ler daha hızlı, keskin nişancı ve nişancı tüfekleri daha yavaş.'],
   'impact': 'Free Fire hesaplayıcımız elmas bakiyesini ve nadir paketleri dikkate alır. OB55 gelecekteki yüklemelerin nasıl ödüllendirileceğini değiştiriyor; mevcut hesaplardaki eşyaları değiştirmiyor.'},
  'cr-minion': {
   'title': 'Clash Royale "Minion Academy" sezonu: yeni kart Minyon Dev ve Buz Büyücüsü kahramanı',
   'desc': 'Minion Academy sezonu (7 Eylül – 5 Ekim 2026) Minyon Dev kartını, Buz Büyücüsü kahramanını ve 1.750 Minyon Dev kartı veren bir albüm etkinliğini getiriyor.',
   'lead': 'Supercell, 7 Eylül’den 5 Ekim 2026’ya kadar sürecek Clash Royale sezonu "Minion Academy"yi başlattı.',
   'new': ['Yeni kart Minyon Dev (Minion Giant): binaları ve kuleleri hedef alan, uçan bir kazanma kartı. Academy Antics albüm etkinliğiyle ücretsiz; sandıklarda ancak gelecek sezon çıkacak.',
           'Albüm etkinliği 1.750 Minyon Dev kartı, bir ifade ve bir kule görünümü veriyor.',
           'Yeni kahraman: Buz Büyücüsü; Pass Royale yolundan ya da 200 Kahraman Parası karşılığında.',
           'Etkinlikler: 2’ye 2 Lig (7–21 Eylül), Princess Gambit küresel turnuvası (21–26 Eylül) ve Royale Shuffle (21 Eylül – 5 Ekim). Ultimate Champion’da beraberlik artık yenilginin yarısı kadar kupa kaybettiriyor.'],
   'impact': 'Yalnızca etkinlik sırasında sunulan kule görünümleri ve ifadeler bir Clash Royale koleksiyonunu daha özel kılar; ancak asıl değer belirleyiciler Kral Kulesi seviyesi ve kart seviyeleri olmaya devam ediyor.'},
  'ml-10': {
   'title': 'Mobile Legends 10 yaşında: ALL IN kampanyası ve yeni Layla Collector kostümü',
   'desc': 'MOONTON’un 10. yıl kampanyası ALL IN (4 Eylül 2026’dan itibaren) yeni bir Nana Epic kostümü, ücretsiz kostüm sandıkları ve 9 Ekim’den itibaren bir Layla Collector kostümü getiriyor.',
   'lead': 'MOONTON Games, Mobile Legends: Bang Bang’in onuncu yıl kampanyası ALL IN’i 4 Eylül 2026’da başlattı.',
   'new': ['10. Yıl Kutlama Pass’i (4 Eylül – 1 Kasım): yeni Nana Epic kostümü, Epic Kostüm Seçim Sandığı, Rastgele Epic Kostüm Sandığı ve geri dönen oyunculara ücretsiz bir yıl dönümü kostümü.',
           'Anniversary Gala Weekend (25 Eylül – 11 Ekim): 265 kostüme erişim, Battle Pass EXP’si ve Premium Kostüm Parçaları.',
           'Layla’s Stellar Gala (9 Ekim – 19 Kasım): "Starfall Breakout" mini oyunuyla Layla’nın yeni Collector kostümü.',
           'MOONTON 1,5 milyarı aşkın indirme ve aylık 110 milyon aktif oyuncu bildiriyor.'],
   'impact': 'Collector ve Legend kostümleri, Mobile Legends hesaplarında en sık anılan değer belirleyiciler arasında; ücretsiz dağıtılan ya da deneme sürümü kostümler değil.'},
  'bs-aug': {
   'title': 'Brawl Stars: Mitik savaşçılar Cosmo ve Vince; Starr Yolu artık Brawler Blast',
   'desc': 'Supercell’in Ağustos 2026 güncelleme notları (1 Eylül) iki Mitik savaşçı ekliyor, Starr Yolu’nu yeni kredi maliyetleriyle Brawler Blast’e çeviriyor ve Ultra Efsanevi’nin adını Ultra yapıyor.',
   'lead': 'Supercell, Brawl Stars’ın Ağustos 2026 güncellemesinin notlarını 1 Eylül 2026’da yayınladı.',
   'new': ['İki yeni Mitik savaşçı: Cosmo (Kontrolcü) ve Vince (Hasar Veren).',
           'Nori ve Wendy için yeni Hiperşarjlar.',
           'Starr Yolu "Brawler Blast" olarak yenilendi: krediler artık nadirliğe göre kilit açmaya gidiyor — Nadir 160, Süper Nadir 430, Destansı 925, Mitik 1.900, Efsanevi 3.800, Ultra 5.500.',
           '"Ultra Efsanevi" nadirliğinin adı "Ultra" oldu. Ayrıca Royal Academy sezonu ve ay boyu süren Brawl-O-Ween etkinliği.'],
   'impact': 'Brawl Stars hesaplayıcımız savaşçı sayısını, Hiperşarjları ve kupaları kullanır. İki yeni Mitik, tam bir koleksiyon için gereken savaşçı sayısını artırıyor.'},
  'coc-aug': {
   'title': 'Clash of Clans Ağustos güncellemesi: Diggy seviye 11–15 ve Belediye Binası 3’ten itibaren Altın Pass',
   'desc': 'Supercell’in Ağustos 2026 güncellemesi (30 Ağustos), Belediye Binası 18’de Diggy seviye 11–15 ile yeni süper şarjlar ekliyor, Başlangıç Pass’ini kaldırıyor ve Altın Pass’i BB3’ten itibaren açıyor.',
   'lead': 'Supercell, Clash of Clans Ağustos güncellemesini 30 Ağustos 2026’da yayınladı.',
   'new': ['Belediye Binası 18: Diggy evcil hayvanı 11–15. seviyeleri alıyor; İnşaatçı Kulübesi ve Monolit yeni süper şarj seviyeleri kazanıyor.',
           'Başlangıç Pass’i kaldırıldı: Sezon Görevleri ve Altın Pass artık Belediye Binası 3’ten itibaren açık; ödüller Belediye Binası seviyesine göre ölçekleniyor.',
           'Harabe Şövalyesi artık zamanla can kaybetmiyor; Harabe Cadısı 8 yerine 10 Harabe Şövalyesi çağırıyor.',
           'Titan liglerinde Klan Savaşları Ligi değiştiricileri ayarlandı.'],
   'impact': 'Araştırmamızda Clash of Clans hesap değerini Belediye Binası seviyesi ile kahraman ve evcil hayvan seviyeleri belirliyor. BB18’deki yeni en yüksek seviyeler, "maks" bir hesabın artık güncellemeden öncesine göre daha fazla geliştirmeye ihtiyaç duyduğu anlamına geliyor.'},
  'fn-c7s4': {
   'title': 'Fortnite Bölüm 7 Sezon 4 "Override": Sonic’li Savaş Bileti ve KINGDOM HEARTS iş birliği',
   'desc': 'Epic’in "Override" sezonu (Bölüm 7, Sezon 4) Override Konsolları’nı, Sonic the Hedgehog’un başı çektiği 800 V-Papel’lik Savaş Bileti’ni ve KINGDOM HEARTS dahil iş birliklerini getiriyor.',
   'lead': 'Fortnite’ın Bölüm 7 Sezon 4’ünün adı "Override". Epic bunu oyun iş birlikleri ve tüm maçı etkileyen kural değişiklikleri üzerine kurulu bir sezon olarak tanımlıyor.',
   'new': ['Override Konsolları her maçta çıkıyor ve oyuncuların tüm sunucunun kurallarını değiştirmesine izin veriyor.',
           'Savaş Bileti 800 V-Papel; başrolde Sonic the Hedgehog, yanında Tails Yardımcısı var.',
           'Bileti 27 Ağustos 23.59’dan (ABD Doğu saati) önce alanlar, çıkış haftası bonusu olarak Infiltrator Grace Crowne kıyafetini aldı.',
           'Sezon boyunca iş birlikleri: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot ve Spyro the Dragon; silahlar arasında Midas’ Masterpiece ve Mega Man’in Mega Buster’ı var.'],
   'impact': 'Çıkış haftası bonusu gibi yalnızca sınırlı süre sunulan kıyafetler, nadir Fortnite dolaplarını sıradanlardan ayıran şeydir. Savaş Bileti kıyafetleri geldikleri sezona bağlı kalır.'},
 }},
'ar': {
 'ui': {
  'news': 'الأخبار', 'news_title': 'أخبار الألعاب التي تؤثر في قيمة الحساب',
  'news_lead': 'تحديثات رسمية من ناشري الألعاب — تمت مطابقة كلٍّ منها مع إعلان الناشر نفسه، مع ملاحظة واضحة عمّا تعنيه لقيمة الحساب.',
  'game_title': 'أخبار {game}', 'game_lead': 'تحديثات {game} الرسمية التي تؤثر في قيمة الحساب. كل مقال يضم رابط إعلان الناشر.',
  'published': 'تاريخ النشر', 'source': 'المصدر الرسمي', 'by_on': '{pub}، {date}', 'whats_new': 'ما الجديد',
  'impact': 'ماذا يعني ذلك لقيمة الحساب', 'more': 'المزيد من أخبار {game}', 'all': 'كل الأخبار',
  'calc': '{game}: حاسبة القيمة وتقرير السوق', 'read': 'اقرأ', 'latest': 'أحدث أخبار {game}',
  'note': 'لا يشتري GameAccountValue الحسابات ولا يبيعها ولا يتوسط فيها. تُلخَّص الأخبار من إعلانات الناشرين للمعلومات فقط.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: وصول Vesna وVodyanitsa وتأكيد مكافآت الذكرى السنوية',
   'desc': 'صدر الإصدار 7.1 "A Rekviem for the Underworld" في 23 سبتمبر 2026 مع شخصيتين جديدتين من فئة 5 نجوم وسلاحين من 5 نجوم ومكافآت الذكرى السادسة.',
   'lead': 'أطلقت HoYoverse الإصدار 7.1 "A Rekviem for the Underworld" في 23 سبتمبر 2026، وهو التحديث الذي يحمل أيضًا الذكرى السادسة للعبة Genshin Impact.',
   'new': ['شخصيتان جديدتان من فئة 5 نجوم: Vesna (أنيمو، سيف) وVodyanitsa (هيدرو، محفِّز).',
           'أسلحة جديدة: Beyond the Chrysalis (سيف 5 نجوم) وHymn of the Maelstrom (محفِّز 5 نجوم) وNew Bough (سيف 4 نجوم).',
           'مكافآت الذكرى التي أعلنتها HoYoverse: شخصيتان من 5 نجوم للدعوة، وIntertwined Fate ×10، وPrimogems ×1600، وإعادة تعيين مكافأة الشحن الأول لبلورات Genesis.',
           'بدأت صيانة التحديث في 23 سبتمبر الساعة 06:00 (UTC+8).'],
   'impact': 'بحسب بحثنا، يُعد عدد شخصيات 5 نجوم المحدودة وكوكباتها وأسلحتها المميزة من أهم عوامل قيمة حسابات Genshin. أما الشخصيات التي تُمنح مجانًا لجميع اللاعبين في الذكرى فتجعل الحساب أقل تميزًا من شخصيات اللافتات المحدودة.'},
  'mc-live': {
   'title': 'Minecraft Live: بُعد The Sift، أول بُعد جديد منذ أكثر من 14 عامًا، قادم إلى Java وBedrock',
   'desc': 'كشف Minecraft Live في 26 سبتمبر 2026 عن The Sift، البُعد الرابع القادم إلى Java وBedrock العام المقبل، إلى جانب Dungeons II وتحديث Wilderness Bound.',
   'lead': 'في Minecraft Live يوم 26 سبتمبر 2026، أعلنت Mojang Studios أن البُعد الرابع للعبة، The Sift، سيصل إلى Minecraft Java وBedrock Edition العام المقبل.',
   'new': ['The Sift هو أول بُعد جديد منذ أكثر من 14 عامًا، وينضم إلى العالم العلوي والنذر والإند.',
           'يظهر لأول مرة في Minecraft Dungeons II، الذي حددت Mojang موعد صدوره في 29 سبتمبر 2026.',
           'يُفتتح Minecraft World، وهو مَعلم ترفيهي، في لندن عام 2027.',
           'وصل تحديث Wilderness Bound في 15 سبتمبر مع الغابة المرقّطة وأسرّة القش والمخيمات المهجورة والوسائد.'],
   'impact': 'تُقيَّم حسابات Minecraft بحسب نوعها (Java أو Bedrock) واسم المستخدم والعباءات، لا بحسب محتوى اللعبة. تغيّر تحديثات كهذه ما يمكن للاعبين فعله، لا قيمة الحساب.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": عناصر UGC محدودة وحصريات Roblox Plus (17–28 سبتمبر)',
   'desc': 'أُقيم The Hunt: Roblox 20 من 17 إلى 28 سبتمبر 2026 مع مكافآت UGC وعناصر UGC محدودة الإصدار وثلاثة عناصر حصرية لمشتركي Roblox Plus.',
   'lead': 'احتفلت Roblox بذكراها العشرين بحدث The Hunt: Roblox 20 على مستوى المنصة، وأُقيم من 17 إلى 28 سبتمبر 2026.',
   'new': ['تنقّل اللاعبون عبر 20 عامًا من تاريخ Roblox، بمهمة لكل عام بدءًا من "Year Zero"؛ وإنهاء الأعوام العشرين كلها يفتح "Year Infinity" مع 20 لعبة إضافية.',
           'منحت المهام عناصر UGC، وتوفرت عناصر UGC محدودة الإصدار خلال الحدث.',
           'حصل مشتركو Roblox Plus على ثلاثة عناصر افتراضية حصرية، ويحتفظون بسمة التطبيق الكلاسيكية وخلفية الأفاتار الكلاسيكية وإطار الملف الشخصي بعد الحدث.',
           'كانت سمة التطبيق الكلاسيكية مجانية للجميع طوال الحدث.'],
   'impact': 'العناصر التي لا يمكن الحصول عليها إلا خلال حدث ما من الأمور التي ينظر إليها التقييم. لم تُسمِّ Roblox هذه العناصر في إعلانها، لذلك لا يضع هذا الموقع لها سعرًا حتى تظهر إعلانات بيع حقيقية.'},
  'rbx-rdc': {
   'title': 'RDC 2026: صنّاع Roblox ربحوا نحو 1.7 مليار دولار في عام، والإعلان عن Roblox Wallet',
   'desc': 'أعلنت Roblox في RDC 2026 عن أرباح للصنّاع تقارب 1.7 مليار دولار خلال 12 شهرًا، وكشفت عن Roblox Wallet وRoblox Card للمدفوعات.',
   'lead': 'في مؤتمر المطوّرين RDC 2026 (إعلان 11 سبتمبر 2026)، شاركت Roblox أرقام أرباح الصنّاع وأدوات دفع جديدة.',
   'new': ['ربح الصنّاع أكثر من 5 مليارات دولار منذ إطلاق DevEx عام 2013، ونحو 1.7 مليار دولار في الأشهر الـ12 حتى 30 يونيو 2026.',
           'حققت حوافز Roblox Plus أكثر من 300 مليون Robux من أرباح الصنّاع في أشهرها الأربعة الأولى (حتى 17 أغسطس 2026).',
           'سيقدّم Roblox Wallet، وهو حساب مدفوعات يُدار مع Airwallex US، دفعات يومية بعملة حقيقية — أولًا للصنّاع المستقلين المؤهلين في الولايات المتحدة ممن بلغوا 18 عامًا في أواخر 2026، ودوليًا في 2027.',
           'من المخطط إطلاق Roblox Card مرتبطة بالمحفظة ابتداءً من 2027.'],
   'impact': 'تخص هذه التغييرات مدفوعات الصنّاع لا حسابات اللاعبين: فالإعلان لم يغيّر أسعار Robux ولا العناصر المحدودة ولا التبادل. يبقى رصيد Robux والعناصر المحدودة هما ما تزنه حاسبة Roblox لدينا.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: أربعة أسلحة جديدة في Clash Squad وPrime Diamond وإعادة تصميم Kenta',
   'desc': 'تضيف ملاحظات تحديث OB55 من Garena (10 سبتمبر 2026) أسلحة M7 وSkorp وRPK وHawk إلى Clash Squad بدءًا من 1 أكتوبر، وتقدّم Prime Diamond وتعيد تصميم Kenta.',
   'lead': 'نشرت Garena ملاحظات تحديث OB55 للعبة Free Fire في 10 سبتمبر 2026؛ وتسري تغييرات الأسلحة في 1 أكتوبر.',
   'new': ['أسلحة Clash Squad الجديدة من 1 أكتوبر: M7 ‏(1600 CS Cash) وSkorp ‏(1500) وRPK ‏(1500) وHawk ‏(1700).',
           'Prime Diamond: ماسات تُكتسب بحسب الإنفاق الشهري، ويمكن استلامها في الشهر التالي بعد أي شحن.',
           'إعادة تصميم كاملة لشخصية Kenta، وتعديلات توازن لـMorse وLuna وWukong.',
           'تغييرات في الحركة حسب فئة السلاح من 1 أكتوبر: الرشاشات الخفيفة أسرع، وبنادق القنص والرماية الدقيقة أبطأ.'],
   'impact': 'تزن حاسبة Free Fire لدينا رصيد الماس والحزم النادرة. يغيّر OB55 طريقة مكافأة عمليات الشحن القادمة، ولا يغيّر العناصر الموجودة أصلًا في الحسابات.'},
  'cr-minion': {
   'title': 'موسم "Minion Academy" في Clash Royale: بطاقة Minion Giant الجديدة والبطل Ice Wizard',
   'desc': 'يضيف موسم Minion Academy (7 سبتمبر – 5 أكتوبر 2026) بطاقة Minion Giant والبطل Ice Wizard وحدث ألبوم يمنح 1750 بطاقة Minion Giant.',
   'lead': 'افتتحت Supercell موسم Clash Royale "Minion Academy" الممتد من 7 سبتمبر إلى 5 أكتوبر 2026.',
   'new': ['بطاقة جديدة Minion Giant: بطاقة فوز طائرة تستهدف المباني والأبراج. تُنال مجانًا عبر حدث ألبوم Academy Antics، ولن تظهر في الصناديق قبل الموسم القادم.',
           'يمنح حدث الألبوم 1750 بطاقة Minion Giant ورمزًا تعبيريًا ومظهرًا للبرج.',
           'بطل جديد: Ice Wizard، من مسار Pass Royale أو مقابل 200 عملة أبطال.',
           'الأحداث: دوري 2 ضد 2 (7–21 سبتمبر)، وبطولة Princess Gambit العالمية (21–26 سبتمبر)، وRoyale Shuffle (21 سبتمبر – 5 أكتوبر). صار التعادل في Ultimate Champion يكلّف نصف كؤوس الخسارة.'],
   'impact': 'مظاهر الأبراج والرموز التعبيرية المعروضة خلال الأحداث فقط تجعل مجموعة Clash Royale أكثر تميزًا، بينما يبقى مستوى برج الملك ومستويات البطاقات أهم عوامل القيمة.'},
  'ml-10': {
   'title': 'Mobile Legends تُتم 10 أعوام: حملة ALL IN ومظهر Collector جديد لـLayla',
   'desc': 'تقدّم حملة ALL IN من MOONTON للذكرى العاشرة (منذ 4 سبتمبر 2026) مظهر Epic جديدًا لـNana وصناديق مظاهر مجانية ومظهر Collector لـLayla بدءًا من 9 أكتوبر.',
   'lead': 'أطلقت MOONTON Games في 4 سبتمبر 2026 حملة ALL IN للذكرى العاشرة للعبة Mobile Legends: Bang Bang.',
   'new': ['تذكرة احتفال الذكرى العاشرة (4 سبتمبر – 1 نوفمبر): مظهر Epic جديد لـNana، وصندوق اختيار مظهر Epic، وصندوق مظهر Epic عشوائي، ومظهر ذكرى مجاني للاعبين العائدين.',
           'Anniversary Gala Weekend ‏(25 سبتمبر – 11 أكتوبر): الوصول إلى 265 مظهرًا، وخبرة Battle Pass، وشظايا مظاهر مميزة.',
           'Layla’s Stellar Gala ‏(9 أكتوبر – 19 نوفمبر): مظهر Collector الجديد لـLayla عبر اللعبة المصغّرة "Starfall Breakout".',
           'تذكر MOONTON أكثر من 1.5 مليار عملية تثبيت و110 ملايين لاعب نشط شهريًا.'],
   'impact': 'مظاهر Collector وLegend من أكثر عوامل قيمة حسابات Mobile Legends ذكرًا، أما المظاهر الموزعة مجانًا أو التجريبية فلا.'},
  'bs-aug': {
   'title': 'Brawl Stars: المقاتلان الأسطوريان Cosmo وVince، وطريق Starr يصبح Brawler Blast',
   'desc': 'تضيف ملاحظات تحديث أغسطس 2026 من Supercell (1 سبتمبر) مقاتلَين من فئة Mythic، وتحوّل طريق Starr إلى Brawler Blast بتكاليف رصيد جديدة، وتغيّر اسم Ultra Legendary إلى Ultra.',
   'lead': 'نشرت Supercell ملاحظات تحديث أغسطس 2026 للعبة Brawl Stars في 1 سبتمبر 2026.',
   'new': ['مقاتلان جديدان من فئة Mythic: Cosmo (متحكّم) وVince (مُلحق ضرر).',
           'شحنات Hypercharge جديدة لـNori وWendy.',
           'أُعيد تصميم طريق Starr ليصبح "Brawler Blast": صار الرصيد يُستخدم لفتح المقاتلين بحسب الندرة — Rare ‏160، Super Rare ‏430، Epic ‏925، Mythic ‏1900، Legendary ‏3800، Ultra ‏5500.',
           'تغيّر اسم ندرة "Ultra Legendary" إلى "Ultra". إضافة إلى موسم Royal Academy وحدث Brawl-O-Ween طوال الشهر.'],
   'impact': 'تعتمد حاسبة Brawl Stars لدينا على عدد المقاتلين وشحنات Hypercharge والكؤوس. يرفع مقاتلان أسطوريان إضافيان عدد المقاتلين اللازم لمجموعة كاملة.'},
  'coc-aug': {
   'title': 'تحديث أغسطس في Clash of Clans: مستويات Diggy من 11 إلى 15 وGold Pass من قاعة البلدة 3',
   'desc': 'يضيف تحديث أغسطس 2026 من Supercell (30 أغسطس) مستويات Diggy من 11 إلى 15 وشحنات فائقة جديدة في قاعة البلدة 18، ويلغي Starter Pass ويفتح Gold Pass من قاعة البلدة 3.',
   'lead': 'أصدرت Supercell تحديث أغسطس للعبة Clash of Clans في 30 أغسطس 2026.',
   'new': ['قاعة البلدة 18: يحصل الحيوان الأليف Diggy على المستويات 11–15، وينال كوخ البنّاء والمونوليث مستويات شحن فائق جديدة.',
           'أُلغي Starter Pass: صارت تحديات الموسم وGold Pass متاحة من قاعة البلدة 3، مع مكافآت تتدرج بحسب مستوى القاعة.',
           'لم يعد Ruin Knight يفقد صحته مع الوقت، وصارت Ruin Witch تستدعي 10 فرسان بدلًا من 8.',
           'عُدّلت معدِّلات دوري حروب العشائر في دوريات Titan.'],
   'impact': 'بحسب بحثنا، يحدد مستوى قاعة البلدة ومستويات الأبطال والحيوانات الأليفة قيمة حسابات Clash of Clans. وتعني المستويات القصوى الجديدة في القاعة 18 أن الحساب "المكتمل" يحتاج الآن إلى ترقيات أكثر مما قبل التحديث.'},
  'fn-c7s4': {
   'title': 'Fortnite الفصل 7 الموسم 4 "Override": تذكرة معركة Sonic وتعاون مع KINGDOM HEARTS',
   'desc': 'يقدّم موسم "Override" من Epic (الفصل 7، الموسم 4) لوحات Override، وتذكرة معركة بسعر 800 V-Bucks يتصدرها Sonic the Hedgehog، وتعاونات منها KINGDOM HEARTS.',
   'lead': 'اسم الموسم الرابع من الفصل السابع في Fortnite هو "Override"، وتصفه Epic بأنه موسم تعاونات مع ألعاب أخرى وتغييرات في قواعد المباراة كلها.',
   'new': ['تظهر لوحات Override في كل مباراة وتتيح للاعبين تغيير القواعد للخادم بأكمله.',
           'سعر تذكرة المعركة 800 V-Bucks، ويتصدرها Sonic the Hedgehog ومعه Tails كرفيق.',
           'حصل من اشترى التذكرة قبل 27 أغسطس الساعة 11:59 مساءً بتوقيت شرق الولايات المتحدة على زي Infiltrator Grace Crowne مكافأةً لأسبوع الإطلاق.',
           'تعاونات الموسم: KINGDOM HEARTS وPac-Man وMega Man وPersona 5 Royal وCyberpunk: Edgerunners وCrash Bandicoot وSpyro the Dragon؛ ومن الأسلحة Midas’ Masterpiece وMega Buster الخاص بـMega Man.'],
   'impact': 'الأزياء المتاحة لفترة محدودة فقط — مثل مكافأة أسبوع الإطلاق — هي ما يميّز خزائن Fortnite النادرة عن العادية. وتبقى أزياء تذكرة المعركة مرتبطة بموسمها.'},
 }},
}
