# News batch 4: tl, sw, ms, uz (from news_text_b4_en.py, facts unchanged)
TEXT = {
'tl': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends sa Asian Games: nakuha ng Myanmar ang unang MLBB gold matapos talunin ang Indonesia 4–0',
  'desc': 'Iniulat ng MOONTON noong Oktubre 1, 2026 na nanalo ang Myanmar ng unang Asian Games gold sa Mobile Legends: Bang Bang sa Aichi-Nagoya 2026, matapos i-sweep ang Indonesia 4–0 sa Grand Final.',
  'lead': 'Noong Oktubre 1, 2026, inanunsyo ng MOONTON Games ang resulta ng unang paglahok ng Mobile Legends: Bang Bang bilang opisyal na medal event sa Asian Games.',
  'new': ['Tinalo ng Myanmar ang Indonesia 4–0 sa Grand Final sa Aichi Sky Expo at naging unang gold medallist ng Asian Games sa MLBB.',
          'Silver ang Indonesia; bronze naman ang Malaysia at Mongolia.',
          '22 National Olympic Committee ang sumali mula sa preliminary rounds, at 12 team ang umabot sa Main Stage.',
          'Kasunod sa kalendaryo ang MLBB Championship Tour at ang M8 World Championship, na ang finals ay gaganapin sa Istanbul, Türkiye.'],
  'impact': 'Hindi binabago ng resulta ng esports ang halaga ng mga kasalukuyang account. Sa aming pananaliksik, skin, hero at progreso ng account pa rin ang nagtatakda ng halaga sa Mobile Legends.'},
 'mc-drop4': {
  'title': 'Huling game drop ng Minecraft sa 2026, nasa testing na: ice caves, frostbite at ice balls',
  'desc': 'Binuksan ng Mojang noong Setyembre 30, 2026 ang testing ng huling game drop ng 2026: ice caves, isang frozen na zombie variant na tinatawag na frostbite, ice balls, ice crystals at icicles.',
  'lead': 'Noong Setyembre 30, 2026, binuksan ng Mojang Studios ang testing ng huling Minecraft game drop ng 2026.',
  'new': ['Mga bagong ice cave na may ice crystals at icicles; marupok ang mga icicle.',
          'Isang bagong mob, ang frostbite (frozen na variant ng zombie), ang bumabato ng ice balls; binanggit din ng Mojang ang Freezing potion.',
          'Ang unang test build noong Setyembre 30 ay preview/beta ng Bedrock Edition; ipinapaliwanag din ng post kung paano i-enable ang mga snapshot ng Java Edition sa Minecraft Launcher.',
          'Nagbabala ang Mojang na puwedeng masira ng mga testing version ang mga world at hinihiling na mag-backup o gumamit ng hiwalay na folder.'],
  'impact': 'Ang halaga ng Minecraft account ay batay sa uri ng account (Java o Bedrock), username at mga cape — hindi sa laman ng laro. Binabago ng ganitong update ang nagagawa ng manlalaro, hindi ang halaga ng account.'},
 'cr-bal-oct': {
  'title': 'Mga balance change ng Clash Royale ngayong Oktubre: na-nerf ang Hero Ice Wizard at Minion Giant, na-buff ang Lava Hound',
  'desc': 'Inilathala ng Supercell ang balance update ng Oktubre 6, 2026: freeze damage ng Hero Ice Wizard 89 → 46, hit speed ng Minion Giant 1.5 s → 1.7 s, damage ng Lava Hound 53 → 71, at na-rework ang Golden Knight.',
  'lead': 'Inilathala ng Supercell ang balance update ng Clash Royale para sa Oktubre 6, 2026.',
  'new': ['Mga nerf: freeze damage ng Hero Ice Wizard 89 → 46; barrage damage ng Cannon Evolution 281 → 261; damage ng Barbarian Barrel 232 → 215; hit speed ng Minion Giant 1.5 s → 1.7 s; hitpoints ng Royal Ghost 1210 → 1152.',
          'Elixir Collector: lifetime 1 min 33 s → 1 min 50 s, production speed 13 s → 15 s.',
          'Mga buff: damage ng Lava Hound 53 → 71 (hit speed 1.3 s → 1.5 s); damage ng Ram Rider 250 → 271; damage ng Wall Breakers 281 → 302; damage ng X-Bow 58 → 61; hitpoints ng Three Musketeers 883 → 906.',
          'Rework: damage ng Golden Knight 161 → 168, dash range 5.5 → 5 tile. Ayon sa Supercell, naka-scale ang mga numero sa Level 11.'],
  'impact': 'Binabago ng mga balance change kung aling deck ang malakas, hindi ang laman ng account. Sa aming pananaliksik, ang level ng King Tower at level ng mga card pa rin ang pangunahing salik ng halaga.'},
}},
'sw': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends kwenye Michezo ya Asia: Myanmar yashinda dhahabu ya kwanza ya MLBB kwa kuifunga Indonesia 4–0',
  'desc': 'MOONTON iliripoti tarehe 1 Oktoba 2026 kwamba Myanmar ilishinda dhahabu ya kwanza ya Michezo ya Asia katika Mobile Legends: Bang Bang huko Aichi-Nagoya 2026, baada ya kuifunga Indonesia 4–0 katika Fainali Kuu.',
  'lead': 'Tarehe 1 Oktoba 2026 MOONTON Games ilitangaza matokeo ya mara ya kwanza ya Mobile Legends: Bang Bang kuwa shindano rasmi la medali katika Michezo ya Asia.',
  'new': ['Myanmar iliifunga Indonesia 4–0 katika Fainali Kuu kwenye Aichi Sky Expo na kuwa mshindi wa kwanza wa dhahabu ya Michezo ya Asia katika MLBB.',
          'Indonesia ilipata fedha; Malaysia na Mongolia zilipata medali za shaba.',
          'Kamati 22 za Olimpiki za Kitaifa zilishiriki kuanzia raundi za awali, na timu 12 zilifika Hatua Kuu.',
          'Kinachofuata kwenye kalenda ni MLBB Championship Tour na M8 World Championship, huku fainali za M8 zikifanyika Istanbul, Uturuki.'],
  'impact': 'Matokeo ya esports hayabadilishi thamani ya akaunti zilizopo. Katika utafiti wetu, skin, hero na maendeleo ya akaunti vinabaki kuwa vinavyoamua thamani katika Mobile Legends.'},
 'mc-drop4': {
  'title': 'Game drop ya mwisho ya Minecraft ya 2026 yaingia majaribio: mapango ya barafu, frostbite na ice balls',
  'desc': 'Mojang ilifungua tarehe 30 Septemba 2026 majaribio ya game drop ya mwisho ya 2026: mapango ya barafu, aina ya zombie aliyeganda iitwayo frostbite, ice balls, ice crystals na icicles.',
  'lead': 'Tarehe 30 Septemba 2026 Mojang Studios ilifungua majaribio ya game drop ya mwisho ya Minecraft ya 2026.',
  'new': ['Mapango mapya ya barafu yaliyopambwa kwa ice crystals na icicles; icicles ni dhaifu na huvunjika kwa urahisi.',
          'Mob mpya, frostbite (aina ya zombie aliyeganda), hurusha ice balls; Mojang pia inataja dawa ya Freezing.',
          'Toleo la kwanza la majaribio, la Septemba 30, ni preview/beta ya Bedrock Edition; chapisho pia linaeleza jinsi ya kuwasha snapshot za Java Edition katika Minecraft Launcher.',
          'Mojang inaonya kwamba matoleo ya majaribio yanaweza kuharibu dunia zako na inaomba uhifadhi nakala au utumie folda tofauti.'],
  'impact': 'Akaunti za Minecraft hupimwa thamani kwa aina ya akaunti (Java au Bedrock), jina la mtumiaji na cape — si kwa maudhui ya mchezo. Masasisho kama haya hubadilisha kile mchezaji anaweza kufanya, si thamani ya akaunti.'},
 'cr-bal-oct': {
  'title': 'Mabadiliko ya usawa ya Clash Royale ya Oktoba: Hero Ice Wizard na Minion Giant wamepunguzwa nguvu, Lava Hound ameongezwa',
  'desc': 'Supercell ilichapisha sasisho la usawa la tarehe 6 Oktoba 2026: madhara ya kugandisha ya Hero Ice Wizard 89 → 46, kasi ya pigo ya Minion Giant sek 1.5 → sek 1.7, madhara ya Lava Hound 53 → 71, na Golden Knight amerekebishwa.',
  'lead': 'Supercell ilichapisha sasisho la usawa la Clash Royale la tarehe 6 Oktoba 2026.',
  'new': ['Kupunguzwa nguvu: madhara ya kugandisha ya Hero Ice Wizard 89 → 46; madhara ya mfululizo ya Cannon Evolution 281 → 261; madhara ya Barbarian Barrel 232 → 215; kasi ya pigo ya Minion Giant sek 1.5 → sek 1.7; uhai wa Royal Ghost 1210 → 1152.',
          'Elixir Collector: muda wa kuishi dak 1 sek 33 → dak 1 sek 50, kasi ya uzalishaji sek 13 → sek 15.',
          'Kuongezwa nguvu: madhara ya Lava Hound 53 → 71 (kasi ya pigo sek 1.3 → sek 1.5); madhara ya Ram Rider 250 → 271; madhara ya Wall Breakers 281 → 302; madhara ya X-Bow 58 → 61; uhai wa Three Musketeers 883 → 906.',
          'Marekebisho: madhara ya Golden Knight 161 → 168, umbali wa kurukia vigae 5.5 → 5. Supercell inabainisha kuwa namba zimepimwa kwa Level 11.'],
  'impact': 'Mabadiliko ya usawa hubadilisha deck zipi zina nguvu, si kile akaunti inachomiliki. Katika utafiti wetu, kiwango cha King Tower na viwango vya kadi vinabaki kuwa vigezo vikuu vya thamani.'},
}},
'ms': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends di Sukan Asia: Myanmar menang emas MLBB pertama selepas menewaskan Indonesia 4–0',
  'desc': 'MOONTON melaporkan pada 1 Oktober 2026 bahawa Myanmar memenangi emas Sukan Asia pertama dalam Mobile Legends: Bang Bang di Aichi-Nagoya 2026, selepas menewaskan Indonesia 4–0 dalam Grand Final.',
  'lead': 'Pada 1 Oktober 2026 MOONTON Games mengumumkan keputusan penampilan sulung Mobile Legends: Bang Bang sebagai acara pingat rasmi Sukan Asia.',
  'new': ['Myanmar menewaskan Indonesia 4–0 dalam Grand Final di Aichi Sky Expo dan menjadi pemenang pingat emas Sukan Asia pertama dalam MLBB.',
          'Indonesia meraih perak; Malaysia dan Mongolia meraih pingat gangsa.',
          '22 Jawatankuasa Olimpik Kebangsaan mengambil bahagian dari pusingan awal, dan 12 pasukan mara ke Peringkat Utama.',
          'Seterusnya dalam kalendar ialah MLBB Championship Tour dan M8 World Championship, dengan pusingan akhir M8 di Istanbul, Türkiye.'],
  'impact': 'Keputusan e-sukan tidak mengubah nilai akaun sedia ada. Dalam kajian kami, skin, hero dan kemajuan akaun kekal sebagai penentu nilai Mobile Legends.'},
 'mc-drop4': {
  'title': 'Game drop terakhir Minecraft 2026 memasuki ujian: gua ais, frostbite dan ice balls',
  'desc': 'Mojang membuka ujian game drop terakhir 2026 pada 30 September 2026: gua ais, varian zombi beku bernama frostbite, ice balls, hablur ais dan icicles.',
  'lead': 'Pada 30 September 2026 Mojang Studios membuka ujian game drop Minecraft terakhir bagi 2026.',
  'new': ['Gua ais baharu yang dihiasi hablur ais (ice crystals) dan icicles; icicles mudah pecah.',
          'Mob baharu, frostbite (varian zombi beku), melontar ice balls; Mojang turut menyebut posyen Freezing.',
          'Binaan ujian pertama, pada 30 September, ialah preview/beta Bedrock Edition; hantaran itu juga menerangkan cara mengaktifkan snapshot Java Edition dalam Minecraft Launcher.',
          'Mojang memberi amaran bahawa versi ujian boleh merosakkan dunia dan meminta pemain membuat sandaran atau menggunakan folder berasingan.'],
  'impact': 'Akaun Minecraft dinilai berdasarkan jenis akaun (Java atau Bedrock), nama pengguna dan cape — bukan kandungan dalam permainan. Kemas kini seperti ini mengubah apa yang pemain boleh lakukan, bukan nilai akaun.'},
 'cr-bal-oct': {
  'title': 'Perubahan imbangan Clash Royale Oktober: Hero Ice Wizard dan Minion Giant dilemahkan, Lava Hound dikuatkan',
  'desc': 'Supercell menerbitkan kemas kini imbangan 6 Oktober 2026: kerosakan beku Hero Ice Wizard 89 → 46, kelajuan pukulan Minion Giant 1.5 s → 1.7 s, kerosakan Lava Hound 53 → 71, dan Golden Knight dirombak.',
  'lead': 'Supercell menerbitkan kemas kini imbangan Clash Royale bertarikh 6 Oktober 2026.',
  'new': ['Dilemahkan: kerosakan beku Hero Ice Wizard 89 → 46; kerosakan tembakan bertalu Cannon Evolution 281 → 261; kerosakan Barbarian Barrel 232 → 215; kelajuan pukulan Minion Giant 1.5 s → 1.7 s; mata nyawa Royal Ghost 1210 → 1152.',
          'Elixir Collector: jangka hayat 1 min 33 s → 1 min 50 s, kelajuan pengeluaran 13 s → 15 s.',
          'Dikuatkan: kerosakan Lava Hound 53 → 71 (kelajuan pukulan 1.3 s → 1.5 s); kerosakan Ram Rider 250 → 271; kerosakan Wall Breakers 281 → 302; kerosakan X-Bow 58 → 61; mata nyawa Three Musketeers 883 → 906.',
          'Rombakan: kerosakan Golden Knight 161 → 168, jarak rempuhan 5.5 → 5 petak. Supercell menyatakan angka-angka ini diukur pada Tahap 11.'],
  'impact': 'Perubahan imbangan mengubah dek mana yang kuat, bukan apa yang dimiliki akaun. Dalam kajian kami, tahap King Tower dan tahap kad kekal sebagai faktor nilai utama.'},
}},
'uz': {'a': {
 'ml-asiad': {
  'title': 'Osiyo oʻyinlarida Mobile Legends: Myanma Indoneziyani 4–0 hisobida yengib, MLBB boʻyicha birinchi oltinni oldi',
  'desc': 'MOONTON 2026-yil 1-oktabrda xabar berdi: Myanma Aichi-Nagoya 2026’da Mobile Legends: Bang Bang boʻyicha Osiyo oʻyinlarining birinchi oltin medalini qoʻlga kiritdi va Grand Finalda Indoneziyani 4–0 hisobida yengdi.',
  'lead': '2026-yil 1-oktabrda MOONTON Games Mobile Legends: Bang Bang Osiyo oʻyinlarida ilk bor rasmiy medal turi sifatida oʻtkazilgan musobaqa natijasini eʼlon qildi.',
  'new': ['Myanma Aichi Sky Expo’dagi Grand Finalda Indoneziyani 4–0 hisobida yengdi va MLBB boʻyicha Osiyo oʻyinlarining birinchi oltin medal sohibi boʻldi.',
          'Indoneziya kumush, Malayziya va Mongoliya bronza medallarini oldi.',
          'Dastlabki saralash bosqichlaridan boshlab 22 ta Milliy olimpiya qoʻmitasi qatnashdi, 12 jamoa asosiy bosqichga chiqdi.',
          'Taqvimda keyingilari — MLBB Championship Tour va M8 jahon chempionati; M8 finallari Turkiyaning Istanbul shahrida oʻtadi.'],
  'impact': 'Kibersport natijalari mavjud akkauntlar qiymatini oʻzgartirmaydi. Tadqiqotimizga koʻra, Mobile Legends’da qiymatni hali ham skinlar, qahramonlar va akkaunt rivoji belgilaydi.'},
 'mc-drop4': {
  'title': 'Minecraft’ning 2026-yildagi oxirgi game drop’i sinovga chiqdi: muz gʻorlari, frostbite va ice balls',
  'desc': 'Mojang 2026-yil 30-sentabrda 2026-yilning oxirgi game drop’i sinovini ochdi: muz gʻorlari, frostbite deb nomlangan muzlagan zombi turi, ice balls, muz kristallari va icicles.',
  'lead': '2026-yil 30-sentabrda Mojang Studios 2026-yilning oxirgi Minecraft game drop’i sinovini ochdi.',
  'new': ['Muz kristallari (ice crystals) va icicles bilan bezatilgan yangi muz gʻorlari; icicles moʻrt.',
          'Yangi mob frostbite (muzlagan zombi turi) ice balls otadi; Mojang Freezing iksirini ham tilga oladi.',
          '30-sentabrdagi birinchi sinov versiyasi — Bedrock Edition uchun preview/beta; maqolada Minecraft Launcher’da Java Edition snapshot’larini qanday yoqish ham tushuntirilgan.',
          'Mojang sinov versiyalari dunyolarni buzishi mumkinligi haqida ogohlantiradi va zaxira nusxa olishni yoki alohida papkadan foydalanishni soʻraydi.'],
  'impact': 'Minecraft akkauntlari oʻyin ichidagi kontentga emas, akkaunt turiga (Java yoki Bedrock), foydalanuvchi nomiga va plashlarga qarab baholanadi. Bunday yangilanishlar oʻyinchi nima qila olishini oʻzgartiradi, akkaunt qiymatini emas.'},
 'cr-bal-oct': {
  'title': 'Clash Royale oktabr balans oʻzgarishlari: Hero Ice Wizard va Minion Giant kuchsizlantirildi, Lava Hound kuchaytirildi',
  'desc': 'Supercell 2026-yil 6-oktabrdagi balans yangilanishini eʼlon qildi: Hero Ice Wizard muzlatish zarari 89 → 46, Minion Giant zarba tezligi 1,5 s → 1,7 s, Lava Hound zarari 53 → 71, Golden Knight qayta ishlangan.',
  'lead': 'Supercell Clash Royale’ning 2026-yil 6-oktabrdagi balans yangilanishini eʼlon qildi.',
  'new': ['Kuchsizlantirishlar: Hero Ice Wizard muzlatish zarari 89 → 46; Cannon Evolution yalpi oʻq zarari 281 → 261; Barbarian Barrel zarari 232 → 215; Minion Giant zarba tezligi 1,5 s → 1,7 s; Royal Ghost jon ballari 1210 → 1152.',
          'Elixir Collector: ishlash muddati 1 daq 33 s → 1 daq 50 s, ishlab chiqarish tezligi 13 s → 15 s.',
          'Kuchaytirishlar: Lava Hound zarari 53 → 71 (zarba tezligi 1,3 s → 1,5 s); Ram Rider zarari 250 → 271; Wall Breakers zarari 281 → 302; X-Bow zarari 58 → 61; Three Musketeers jon ballari 883 → 906.',
          'Qayta ishlash: Golden Knight zarari 161 → 168, tashlanish masofasi 5,5 → 5 katak. Supercell raqamlar 11-daraja uchun berilganini taʼkidlaydi.'],
  'impact': 'Balans oʻzgarishlari qaysi kolodalar kuchli ekanini oʻzgartiradi, akkauntda nima borligini emas. Tadqiqotimizga koʻra, King Tower darajasi va kartalar darajasi asosiy qiymat omillari boʻlib qolmoqda.'},
}},
}
