# News batch 4: fr, de, it, pl (from news_text_b4_en.py, facts unchanged)
TEXT = {
'fr': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends aux Jeux asiatiques : le Myanmar décroche le premier or MLBB en battant l’Indonésie 4–0',
  'desc': 'MOONTON a annoncé le 1er octobre 2026 que le Myanmar a remporté le premier or des Jeux asiatiques sur Mobile Legends: Bang Bang à Aichi-Nagoya 2026, en battant l’Indonésie 4–0 en grande finale.',
  'lead': 'Le 1er octobre 2026, MOONTON Games a annoncé le résultat de la première édition de Mobile Legends: Bang Bang comme épreuve officielle à médailles des Jeux asiatiques.',
  'new': ['Le Myanmar a battu l’Indonésie 4–0 en grande finale à l’Aichi Sky Expo et devient le premier médaillé d’or des Jeux asiatiques sur MLBB.',
          'L’Indonésie prend l’argent ; la Malaisie et la Mongolie prennent les médailles de bronze.',
          '22 Comités nationaux olympiques ont participé dès les tours préliminaires, et 12 équipes ont atteint la phase principale.',
          'Prochaines étapes du calendrier : le MLBB Championship Tour et le Championnat du monde M8, dont les finales se joueront à Istanbul, en Turquie.'],
  'impact': 'Les résultats esport ne changent pas la valeur des comptes existants. D’après nos recherches, les skins, les héros et la progression du compte restent ce qui fait la valeur sur Mobile Legends.'},
 'mc-drop4': {
  'title': 'Le dernier game drop Minecraft de 2026 entre en test : grottes de glace, le frostbite et les ice balls',
  'desc': 'Mojang a ouvert le 30 septembre 2026 les tests du dernier game drop de 2026 : grottes de glace, une variante de zombie gelé appelée frostbite, ice balls, cristaux de glace et stalactites de glace.',
  'lead': 'Le 30 septembre 2026, Mojang Studios a ouvert les tests du dernier game drop Minecraft de 2026.',
  'new': ['De nouvelles grottes de glace, décorées de cristaux de glace (ice crystals) et de stalactites de glace (icicles) ; ces dernières sont fragiles.',
          'Une nouvelle créature, le frostbite (variante de zombie gelé), lance des ice balls ; Mojang mentionne aussi une potion Freezing.',
          'La première version de test, le 30 septembre, est une preview/bêta de Bedrock Edition ; l’article explique aussi comment activer les snapshots de Java Edition dans le Minecraft Launcher.',
          'Mojang prévient que les versions de test peuvent corrompre les mondes et demande de les sauvegarder ou d’utiliser un dossier séparé.'],
  'impact': 'Les comptes Minecraft sont évalués selon le type de compte (Java ou Bedrock), le pseudo et les capes — pas selon le contenu du jeu. Ces mises à jour changent ce que l’on peut faire, pas la valeur d’un compte.'},
 'cr-bal-oct': {
  'title': 'Équilibrage d’octobre de Clash Royale : nerf de Hero Ice Wizard et Minion Giant, buff de Lava Hound',
  'desc': 'Supercell a publié la mise à jour d’équilibrage du 6 octobre 2026 : dégâts de gel de Hero Ice Wizard 89 → 46, vitesse de frappe de Minion Giant 1,5 s → 1,7 s, dégâts de Lava Hound 53 → 71, refonte de Golden Knight.',
  'lead': 'Supercell a publié la mise à jour d’équilibrage de Clash Royale du 6 octobre 2026.',
  'new': ['Nerfs : dégâts de gel de Hero Ice Wizard 89 → 46 ; dégâts de la salve de Cannon Evolution 281 → 261 ; dégâts de Barbarian Barrel 232 → 215 ; vitesse de frappe de Minion Giant 1,5 s → 1,7 s ; points de vie de Royal Ghost 1210 → 1152.',
          'Elixir Collector : durée de vie 1 min 33 s → 1 min 50 s, vitesse de production 13 s → 15 s.',
          'Buffs : dégâts de Lava Hound 53 → 71 (vitesse de frappe 1,3 s → 1,5 s) ; dégâts de Ram Rider 250 → 271 ; dégâts de Wall Breakers 281 → 302 ; dégâts de X-Bow 58 → 61 ; points de vie de Three Musketeers 883 → 906.',
          'Refonte : dégâts de Golden Knight 161 → 168, portée de la ruée 5,5 → 5 cases. Supercell précise que les chiffres sont donnés au niveau 11.'],
  'impact': 'Les changements d’équilibrage modifient les decks qui dominent, pas ce que contient un compte. D’après nos recherches, le niveau de la Tour du Roi et le niveau des cartes restent les principaux facteurs de valeur.'},
}},
'de': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends bei den Asienspielen: Myanmar holt mit 4:0 gegen Indonesien das erste MLBB-Gold',
  'desc': 'MOONTON meldete am 1. Oktober 2026: Myanmar gewann bei Aichi-Nagoya 2026 das erste Asienspiele-Gold in Mobile Legends: Bang Bang und besiegte Indonesien im Großen Finale mit 4:0.',
  'lead': 'Am 1. Oktober 2026 gab MOONTON Games das Ergebnis der ersten Austragung von Mobile Legends: Bang Bang als offizieller Medaillenwettbewerb der Asienspiele bekannt.',
  'new': ['Myanmar besiegte Indonesien im Großen Finale in der Aichi Sky Expo mit 4:0 und ist damit der erste Goldmedaillengewinner der Asienspiele in MLBB.',
          'Indonesien holte Silber; Malaysia und die Mongolei holten die Bronzemedaillen.',
          '22 Nationale Olympische Komitees nahmen ab den Vorrunden teil, 12 Teams erreichten die Hauptrunde.',
          'Als Nächstes stehen die MLBB Championship Tour und die M8-Weltmeisterschaft an; die M8-Finals finden in Istanbul (Türkei) statt.'],
  'impact': 'E-Sport-Ergebnisse ändern nichts am Wert bestehender Konten. Nach unserer Recherche bestimmen weiterhin Skins, Helden und der Kontofortschritt den Wert in Mobile Legends.'},
 'mc-drop4': {
  'title': 'Minecrafts letzter Game Drop 2026 geht in den Test: Eishöhlen, der Frostbite und Ice Balls',
  'desc': 'Mojang hat am 30. September 2026 den Test des letzten Game Drops 2026 gestartet: Eishöhlen, eine gefrorene Zombie-Variante namens Frostbite, Ice Balls, Eiskristalle und Eiszapfen.',
  'lead': 'Am 30. September 2026 hat Mojang Studios den Test des letzten Minecraft-Game-Drops 2026 gestartet.',
  'new': ['Neue Eishöhlen, geschmückt mit Eiskristallen (ice crystals) und Eiszapfen (icicles); die Eiszapfen sind zerbrechlich.',
          'Ein neuer Mob, der Frostbite (eine gefrorene Zombie-Variante), wirft Ice Balls; Mojang erwähnt außerdem einen Freezing-Trank.',
          'Die erste Testversion vom 30. September ist eine Preview/Beta der Bedrock Edition; der Beitrag erklärt auch, wie man Snapshots der Java Edition im Minecraft Launcher aktiviert.',
          'Mojang warnt, dass Testversionen Welten beschädigen können, und bittet darum, Backups anzulegen oder einen eigenen Ordner zu nutzen.'],
  'impact': 'Minecraft-Konten werden nach Kontotyp (Java oder Bedrock), Benutzername und Capes bewertet — nicht nach Spielinhalten. Solche Updates ändern, was Spieler tun können, nicht den Wert eines Kontos.'},
 'cr-bal-oct': {
  'title': 'Clash Royale Balance-Änderungen im Oktober: Hero Ice Wizard und Minion Giant abgeschwächt, Lava Hound gestärkt',
  'desc': 'Supercell hat das Balance-Update vom 6. Oktober 2026 veröffentlicht: Frostschaden von Hero Ice Wizard 89 → 46, Trefferrate von Minion Giant 1,5 s → 1,7 s, Schaden von Lava Hound 53 → 71, Golden Knight überarbeitet.',
  'lead': 'Supercell hat das Clash-Royale-Balance-Update vom 6. Oktober 2026 veröffentlicht.',
  'new': ['Abschwächungen: Frostschaden von Hero Ice Wizard 89 → 46; Salvenschaden von Cannon Evolution 281 → 261; Schaden von Barbarian Barrel 232 → 215; Trefferrate von Minion Giant 1,5 s → 1,7 s; Trefferpunkte von Royal Ghost 1210 → 1152.',
          'Elixir Collector: Lebensdauer 1 min 33 s → 1 min 50 s, Produktionstempo 13 s → 15 s.',
          'Stärkungen: Schaden von Lava Hound 53 → 71 (Trefferrate 1,3 s → 1,5 s); Schaden von Ram Rider 250 → 271; Schaden von Wall Breakers 281 → 302; Schaden von X-Bow 58 → 61; Trefferpunkte von Three Musketeers 883 → 906.',
          'Überarbeitung: Schaden von Golden Knight 161 → 168, Sprintreichweite 5,5 → 5 Felder. Supercell weist darauf hin, dass die Werte für Level 11 gelten.'],
  'impact': 'Balance-Änderungen verschieben, welche Decks stark sind — nicht, was ein Konto besitzt. Nach unserer Recherche bleiben das Level des Königsturms und die Kartenlevel die wichtigsten Wertfaktoren.'},
}},
'it': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends ai Giochi asiatici: il Myanmar vince il primo oro MLBB battendo l’Indonesia 4–0',
  'desc': 'MOONTON ha comunicato il 1º ottobre 2026 che il Myanmar ha vinto il primo oro dei Giochi asiatici in Mobile Legends: Bang Bang ad Aichi-Nagoya 2026, battendo l’Indonesia 4–0 nella finalissima.',
  'lead': 'Il 1º ottobre 2026 MOONTON Games ha annunciato il risultato della prima edizione di Mobile Legends: Bang Bang come evento ufficiale da medaglia ai Giochi asiatici.',
  'new': ['Il Myanmar ha battuto l’Indonesia 4–0 nella finalissima all’Aichi Sky Expo ed è il primo vincitore dell’oro dei Giochi asiatici in MLBB.',
          'All’Indonesia è andato l’argento; a Malesia e Mongolia i bronzi.',
          '22 Comitati olimpici nazionali hanno partecipato dai turni preliminari e 12 squadre hanno raggiunto la fase principale.',
          'I prossimi appuntamenti sono l’MLBB Championship Tour e il Mondiale M8, con le finali di M8 a Istanbul, in Turchia.'],
  'impact': 'I risultati esport non cambiano il valore degli account esistenti. Secondo la nostra ricerca, skin, eroi e progressi dell’account restano ciò che determina il valore in Mobile Legends.'},
 'mc-drop4': {
  'title': 'L’ultimo game drop di Minecraft del 2026 entra in test: grotte di ghiaccio, il frostbite e le ice balls',
  'desc': 'Mojang ha aperto il 30 settembre 2026 i test dell’ultimo game drop del 2026: grotte di ghiaccio, una variante di zombie congelato chiamata frostbite, ice balls, cristalli di ghiaccio e ghiaccioli.',
  'lead': 'Il 30 settembre 2026 Mojang Studios ha aperto i test dell’ultimo game drop di Minecraft del 2026.',
  'new': ['Nuove grotte di ghiaccio, decorate con cristalli di ghiaccio (ice crystals) e ghiaccioli (icicles); i ghiaccioli sono fragili.',
          'Un nuovo mob, il frostbite (variante di zombie congelato), lancia ice balls; Mojang cita anche una pozione Freezing.',
          'La prima versione di test, del 30 settembre, è una preview/beta di Bedrock Edition; il post spiega anche come attivare gli snapshot di Java Edition nel Minecraft Launcher.',
          'Mojang avverte che le versioni di test possono corrompere i mondi e chiede di fare un backup o usare una cartella separata.'],
  'impact': 'Gli account Minecraft si valutano in base al tipo di account (Java o Bedrock), al nome utente e ai mantelli — non ai contenuti di gioco. Aggiornamenti come questi cambiano ciò che si può fare, non quanto vale un account.'},
 'cr-bal-oct': {
  'title': 'Bilanciamento di ottobre di Clash Royale: nerf a Hero Ice Wizard e Minion Giant, buff a Lava Hound',
  'desc': 'Supercell ha pubblicato l’aggiornamento di bilanciamento del 6 ottobre 2026: danno da congelamento di Hero Ice Wizard 89 → 46, velocità di colpo di Minion Giant 1,5 s → 1,7 s, danno di Lava Hound 53 → 71, Golden Knight rivisto.',
  'lead': 'Supercell ha pubblicato l’aggiornamento di bilanciamento di Clash Royale del 6 ottobre 2026.',
  'new': ['Nerf: danno da congelamento di Hero Ice Wizard 89 → 46; danno della raffica di Cannon Evolution 281 → 261; danno di Barbarian Barrel 232 → 215; velocità di colpo di Minion Giant 1,5 s → 1,7 s; punti ferita di Royal Ghost 1210 → 1152.',
          'Elixir Collector: durata 1 min 33 s → 1 min 50 s, velocità di produzione 13 s → 15 s.',
          'Buff: danno di Lava Hound 53 → 71 (velocità di colpo 1,3 s → 1,5 s); danno di Ram Rider 250 → 271; danno di Wall Breakers 281 → 302; danno di X-Bow 58 → 61; punti ferita di Three Musketeers 883 → 906.',
          'Revisione: danno di Golden Knight 161 → 168, portata dello scatto 5,5 → 5 caselle. Supercell precisa che i numeri sono riferiti al livello 11.'],
  'impact': 'Le modifiche al bilanciamento cambiano quali mazzi sono forti, non ciò che un account possiede. Secondo la nostra ricerca, il livello della Torre del Re e il livello delle carte restano i principali fattori di valore.'},
}},
'pl': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends na Igrzyskach Azjatyckich: Mjanma zdobywa pierwsze złoto MLBB, pokonując Indonezję 4:0',
  'desc': 'MOONTON poinformował 1 października 2026 r., że Mjanma zdobyła pierwsze złoto Igrzysk Azjatyckich w Mobile Legends: Bang Bang na Aichi-Nagoja 2026, pokonując Indonezję 4:0 w wielkim finale.',
  'lead': '1 października 2026 r. MOONTON Games ogłosił wynik pierwszego występu Mobile Legends: Bang Bang jako oficjalnej konkurencji medalowej Igrzysk Azjatyckich.',
  'new': ['Mjanma pokonała Indonezję 4:0 w wielkim finale w Aichi Sky Expo i została pierwszym złotym medalistą Igrzysk Azjatyckich w MLBB.',
          'Indonezja zdobyła srebro, a Malezja i Mongolia — brązowe medale.',
          'Od rund wstępnych startowały 22 Narodowe Komitety Olimpijskie, a 12 drużyn awansowało do fazy głównej.',
          'Następne w kalendarzu są MLBB Championship Tour i Mistrzostwa Świata M8, których finały odbędą się w Stambule w Turcji.'],
  'impact': 'Wyniki esportowe nie zmieniają wartości istniejących kont. Według naszych badań o wartości w Mobile Legends nadal decydują skórki, bohaterowie i postęp konta.'},
 'mc-drop4': {
  'title': 'Ostatni game drop Minecrafta w 2026 r. trafia do testów: lodowe jaskinie, frostbite i ice balls',
  'desc': 'Mojang otworzył 30 września 2026 r. testy ostatniego game dropu 2026 r.: lodowe jaskinie, zamrożony wariant zombie o nazwie frostbite, ice balls, kryształy lodu i sople.',
  'lead': '30 września 2026 r. Mojang Studios otworzyło testy ostatniego game dropu Minecrafta w 2026 r.',
  'new': ['Nowe lodowe jaskinie ozdobione kryształami lodu (ice crystals) i soplami (icicles); sople są kruche.',
          'Nowy mob, frostbite (zamrożony wariant zombie), rzuca ice balls; Mojang wspomina też o miksturze Freezing.',
          'Pierwsza wersja testowa, z 30 września, to preview/beta Bedrock Edition; wpis wyjaśnia także, jak włączyć snapshoty Java Edition w Minecraft Launcherze.',
          'Mojang ostrzega, że wersje testowe mogą uszkodzić światy, i prosi o robienie kopii zapasowych lub używanie osobnego folderu.'],
  'impact': 'Konta Minecraft wycenia się według typu konta (Java lub Bedrock), nazwy użytkownika i peleryn — a nie zawartości gry. Takie aktualizacje zmieniają to, co gracz może robić, a nie wartość konta.'},
 'cr-bal-oct': {
  'title': 'Październikowe zmiany balansu w Clash Royale: osłabieni Hero Ice Wizard i Minion Giant, wzmocniony Lava Hound',
  'desc': 'Supercell opublikował aktualizację balansu z 6 października 2026 r.: obrażenia zamrożenia Hero Ice Wizard 89 → 46, szybkość ataku Minion Giant 1,5 s → 1,7 s, obrażenia Lava Hound 53 → 71, przebudowany Golden Knight.',
  'lead': 'Supercell opublikował aktualizację balansu Clash Royale z 6 października 2026 r.',
  'new': ['Osłabienia: obrażenia zamrożenia Hero Ice Wizard 89 → 46; obrażenia salwy Cannon Evolution 281 → 261; obrażenia Barbarian Barrel 232 → 215; szybkość ataku Minion Giant 1,5 s → 1,7 s; punkty życia Royal Ghost 1210 → 1152.',
          'Elixir Collector: czas życia 1 min 33 s → 1 min 50 s, szybkość produkcji 13 s → 15 s.',
          'Wzmocnienia: obrażenia Lava Hound 53 → 71 (szybkość ataku 1,3 s → 1,5 s); obrażenia Ram Rider 250 → 271; obrażenia Wall Breakers 281 → 302; obrażenia X-Bow 58 → 61; punkty życia Three Musketeers 883 → 906.',
          'Przebudowa: obrażenia Golden Knight 161 → 168, zasięg szarży 5,5 → 5 pól. Supercell zaznacza, że liczby podano dla poziomu 11.'],
  'impact': 'Zmiany balansu wpływają na to, które talie są mocne, a nie na to, co jest na koncie. Według naszych badań głównymi czynnikami wartości pozostają poziom Wieży Króla i poziomy kart.'},
}},
}
