# News batch 4: kk, tk, ky (from news_text_b4_en.py, facts unchanged)
TEXT = {
'kk': {'a': {
 'ml-asiad': {
  'title': 'Азия ойындарындағы Mobile Legends: Мьянма Индонезияны 4–0 есебімен жеңіп, MLBB бойынша алғашқы алтынды алды',
  'desc': 'MOONTON 2026 жылғы 1 қазанда хабарлады: Мьянма Айчи-Нагоя 2026-да Mobile Legends: Bang Bang бойынша Азия ойындарының алғашқы алтын медалін жеңіп алды, гранд-финалда Индонезияны 4–0 есебімен ұтты.',
  'lead': '2026 жылғы 1 қазанда MOONTON Games Mobile Legends: Bang Bang Азия ойындарында алғаш рет ресми медальдық түр ретінде өткен жарыстың қорытындысын жариялады.',
  'new': ['Мьянма Aichi Sky Expo-дағы гранд-финалда Индонезияны 4–0 есебімен жеңіп, MLBB бойынша Азия ойындарының алғашқы алтын медаль иегері атанды.',
          'Индонезия күміс алды; Малайзия мен Моңғолия қола медаль алды.',
          'Алдын ала іріктеу кезеңдерінен бастап 22 Ұлттық олимпиада комитеті қатысты, 12 команда негізгі кезеңге шықты.',
          'Күнтізбеде келесілері — MLBB Championship Tour және M8 әлем чемпионаты; M8 финалдары Түркияның Стамбұл қаласында өтеді.'],
  'impact': 'Киберспорт нәтижелері қолданыстағы аккаунттардың құнын өзгертпейді. Біздің зерттеуімізше, Mobile Legends-те құнды әлі де скиндер, кейіпкерлер және аккаунттың дамуы анықтайды.'},
 'mc-drop4': {
  'title': 'Minecraft-тың 2026 жылғы соңғы game drop-ы сынаққа шықты: мұз үңгірлері, frostbite және ice balls',
  'desc': 'Mojang 2026 жылғы 30 қыркүйекте 2026 жылдың соңғы game drop-ының сынағын ашты: мұз үңгірлері, frostbite деп аталатын мұздаған зомби түрі, ice balls, мұз кристалдары және icicles.',
  'lead': '2026 жылғы 30 қыркүйекте Mojang Studios 2026 жылдың соңғы Minecraft game drop-ының сынағын ашты.',
  'new': ['Мұз кристалдарымен (ice crystals) және icicles-пен безендірілген жаңа мұз үңгірлері; icicles сынғыш.',
          'Жаңа моб frostbite (мұздаған зомби түрі) ice balls лақтырады; Mojang Freezing сусынын да атайды.',
          '30 қыркүйектегі алғашқы сынақ нұсқасы — Bedrock Edition үшін preview/beta; жазбада Minecraft Launcher-де Java Edition snapshot-тарын қалай қосу керегі де түсіндірілген.',
          'Mojang сынақ нұсқалары әлемдерді бүлдіруі мүмкін екенін ескертеді және сақтық көшірме жасауды немесе бөлек қалтаны қолдануды сұрайды.'],
  'impact': 'Minecraft аккаунттары ойын ішіндегі контентке емес, аккаунт түріне (Java немесе Bedrock), пайдаланушы атына және жамылғыларға қарай бағаланады. Мұндай жаңартулар ойыншының не істей алатынын өзгертеді, аккаунттың құнын емес.'},
 'cr-bal-oct': {
  'title': 'Clash Royale қазан айындағы баланс өзгерістері: Hero Ice Wizard пен Minion Giant әлсіретілді, Lava Hound күшейтілді',
  'desc': 'Supercell 2026 жылғы 6 қазандағы баланс жаңартуын жариялады: Hero Ice Wizard мұздату зақымы 89 → 46, Minion Giant соққы жылдамдығы 1,5 с → 1,7 с, Lava Hound зақымы 53 → 71, Golden Knight қайта өңделді.',
  'lead': 'Supercell Clash Royale-дің 2026 жылғы 6 қазандағы баланс жаңартуын жариялады.',
  'new': ['Әлсіретулер: Hero Ice Wizard мұздату зақымы 89 → 46; Cannon Evolution жаппай ату зақымы 281 → 261; Barbarian Barrel зақымы 232 → 215; Minion Giant соққы жылдамдығы 1,5 с → 1,7 с; Royal Ghost өмір ұпайлары 1210 → 1152.',
          'Elixir Collector: жұмыс уақыты 1 мин 33 с → 1 мин 50 с, өндіру жылдамдығы 13 с → 15 с.',
          'Күшейтулер: Lava Hound зақымы 53 → 71 (соққы жылдамдығы 1,3 с → 1,5 с); Ram Rider зақымы 250 → 271; Wall Breakers зақымы 281 → 302; X-Bow зақымы 58 → 61; Three Musketeers өмір ұпайлары 883 → 906.',
          'Қайта өңдеу: Golden Knight зақымы 161 → 168, ұмтылу қашықтығы 5,5 → 5 тор. Supercell сандар 11-деңгейге есептелгенін айтады.'],
  'impact': 'Баланс өзгерістері қай колодалардың күшті екенін өзгертеді, аккаунтта не барын емес. Біздің зерттеуімізше, King Tower деңгейі мен карталар деңгейі құнның негізгі факторлары болып қала береді.'},
}},
'tk': {'a': {
 'ml-asiad': {
  'title': 'Aziýa oýunlarynda Mobile Legends: Mýanma Indoneziýany 4–0 hasabynda ýeňip, MLBB boýunça ilkinji altyny aldy',
  'desc': 'MOONTON 2026-njy ýylyň 1-nji oktýabrynda habar berdi: Mýanma Aýçi-Nagoýa 2026-da Mobile Legends: Bang Bang boýunça Aziýa oýunlarynyň ilkinji altyn medalyny gazandy, grand-finalda Indoneziýany 4–0 hasabynda ýeňdi.',
  'lead': '2026-njy ýylyň 1-nji oktýabrynda MOONTON Games Mobile Legends: Bang Bang-yň Aziýa oýunlarynda ilkinji gezek resmi medal görnüşi hökmünde geçirilen ýaryşynyň netijesini yglan etdi.',
  'new': ['Mýanma Aichi Sky Expo-daky grand-finalda Indoneziýany 4–0 hasabynda ýeňip, MLBB boýunça Aziýa oýunlarynyň ilkinji altyn medal eýesi boldy.',
          'Indoneziýa kümüş aldy; Malaýziýa we Mongoliýa bürünç medal aldy.',
          'Deslapky saýlama tapgyrlaryndan başlap 22 Milli olimpiýa komiteti gatnaşdy, 12 topar esasy tapgyra çykdy.',
          'Senenamada indikiler — MLBB Championship Tour we M8 dünýä çempionaty; M8 finallary Türkiýäniň Stambul şäherinde geçer.'],
  'impact': 'Kibersport netijeleri bar bolan hasaplaryň gymmatyny üýtgetmeýär. Biziň barlagymyza görä, Mobile Legends-de gymmaty henizem skinler, gahrymanlar we hasabyň ösüşi kesgitleýär.'},
 'mc-drop4': {
  'title': 'Minecraft-yň 2026-njy ýyldaky soňky game drop-y synaga çykdy: buz gowaklary, frostbite we ice balls',
  'desc': 'Mojang 2026-njy ýylyň 30-njy sentýabrynda 2026-njy ýylyň soňky game drop-ynyň synagyny açdy: buz gowaklary, frostbite diýen doňan zombi görnüşi, ice balls, buz kristallary we icicles.',
  'lead': '2026-njy ýylyň 30-njy sentýabrynda Mojang Studios 2026-njy ýylyň soňky Minecraft game drop-ynyň synagyny açdy.',
  'new': ['Buz kristallary (ice crystals) we icicles bilen bezelen täze buz gowaklary; icicles port.',
          'Täze mob frostbite (doňan zombi görnüşi) ice balls zyňýar; Mojang Freezing içgisini hem agzaýar.',
          '30-njy sentýabrdaky ilkinji synag wersiýasy — Bedrock Edition üçin preview/beta; ýazgyda Minecraft Launcher-de Java Edition snapshot-laryny nädip açmalydygy hem düşündirilýär.',
          'Mojang synag wersiýalarynyň dünýäleri zaýalap biljekdigini duýdurýar we ätiýaçlyk nusga almagy ýa-da aýratyn bukjany ulanmagy haýyş edýär.'],
  'impact': 'Minecraft hasaplary oýnuň içindäki mazmuna görä däl-de, hasabyň görnüşine (Java ýa-da Bedrock), ulanyjy adyna we ýapynjalara görä bahalandyrylýar. Şeýle täzelenmeler oýunçynyň näme edip bilýändigini üýtgedýär, hasabyň gymmatyny däl.'},
 'cr-bal-oct': {
  'title': 'Clash Royale oktýabr deňagramlylyk üýtgeşmeleri: Hero Ice Wizard we Minion Giant gowşadyldy, Lava Hound güýçlendirildi',
  'desc': 'Supercell 2026-njy ýylyň 6-njy oktýabryndaky deňagramlylyk täzelenmesini çap etdi: Hero Ice Wizard doňdurma zeperi 89 → 46, Minion Giant urgy tizligi 1,5 s → 1,7 s, Lava Hound zeperi 53 → 71, Golden Knight täzeden işlenildi.',
  'lead': 'Supercell Clash Royale-iň 2026-njy ýylyň 6-njy oktýabryndaky deňagramlylyk täzelenmesini çap etdi.',
  'new': ['Gowşatmalar: Hero Ice Wizard doňdurma zeperi 89 → 46; Cannon Evolution yzly-yzyna atyş zeperi 281 → 261; Barbarian Barrel zeperi 232 → 215; Minion Giant urgy tizligi 1,5 s → 1,7 s; Royal Ghost jan ballary 1210 → 1152.',
          'Elixir Collector: işleýän wagty 1 min 33 s → 1 min 50 s, öndüriş tizligi 13 s → 15 s.',
          'Güýçlendirmeler: Lava Hound zeperi 53 → 71 (urgy tizligi 1,3 s → 1,5 s); Ram Rider zeperi 250 → 271; Wall Breakers zeperi 281 → 302; X-Bow zeperi 58 → 61; Three Musketeers jan ballary 883 → 906.',
          'Täzeden işlemek: Golden Knight zeperi 161 → 168, okdurylma aralygy 5,5 → 5 öýjük. Supercell sanlaryň 11-nji dereje üçin berlendigini belleýär.'],
  'impact': 'Deňagramlylyk üýtgeşmeleri haýsy kolodalaryň güýçlüdigini üýtgedýär, hasapda näme bardygyny däl. Biziň barlagymyza görä, King Tower derejesi we kartlaryň derejesi gymmatyň esasy faktorlary bolmagynda galýar.'},
}},
'ky': {'a': {
 'ml-asiad': {
  'title': 'Азия оюндарындагы Mobile Legends: Мьянма Индонезияны 4–0 эсебинде жеңип, MLBB боюнча биринчи алтынды алды',
  'desc': 'MOONTON 2026-жылдын 1-октябрында билдирди: Мьянма Айчи-Нагоя 2026’да Mobile Legends: Bang Bang боюнча Азия оюндарынын биринчи алтын медалын утуп алды, гранд-финалда Индонезияны 4–0 эсебинде жеңди.',
  'lead': '2026-жылдын 1-октябрында MOONTON Games Mobile Legends: Bang Bang Азия оюндарында биринчи жолу расмий медалдык түр катары өткөн мелдештин жыйынтыгын жарыялады.',
  'new': ['Мьянма Aichi Sky Expo’догу гранд-финалда Индонезияны 4–0 эсебинде жеңип, MLBB боюнча Азия оюндарынын биринчи алтын медаль ээси болду.',
          'Индонезия күмүш алды; Малайзия менен Монголия коло медаль алышты.',
          'Алдын ала тандоо айлампаларынан баштап 22 Улуттук олимпиада комитети катышты, 12 команда негизги баскычка чыкты.',
          'Календарда кийинкилери — MLBB Championship Tour жана M8 дүйнө чемпионаты; M8 финалдары Түркиянын Стамбул шаарында өтөт.'],
  'impact': 'Киберспорт жыйынтыктары учурдагы аккаунттардын баасын өзгөртпөйт. Биздин изилдөөбүз боюнча, Mobile Legends’те баалуулукту дагы эле скиндер, каармандар жана аккаунттун өнүгүүсү аныктайт.'},
 'mc-drop4': {
  'title': 'Minecraft’тын 2026-жылдагы акыркы game drop’у сыноого чыкты: муз үңкүрлөрү, frostbite жана ice balls',
  'desc': 'Mojang 2026-жылдын 30-сентябрында 2026-жылдын акыркы game drop’унун сыноосун ачты: муз үңкүрлөрү, frostbite деп аталган тоңгон зомби түрү, ice balls, муз кристаллдары жана icicles.',
  'lead': '2026-жылдын 30-сентябрында Mojang Studios 2026-жылдын акыркы Minecraft game drop’унун сыноосун ачты.',
  'new': ['Муз кристаллдары (ice crystals) жана icicles менен кооздолгон жаңы муз үңкүрлөрү; icicles морт.',
          'Жаңы моб frostbite (тоңгон зомби түрү) ice balls ыргытат; Mojang Freezing ичимдигин да атайт.',
          '30-сентябрдагы биринчи сыноо версиясы — Bedrock Edition үчүн preview/beta; макалада Minecraft Launcher’де Java Edition snapshot’торун кантип күйгүзүү керектиги да түшүндүрүлгөн.',
          'Mojang сыноо версиялары дүйнөлөрдү бузушу мүмкүн экенин эскертет жана камдык көчүрмө жасоону же өзүнчө папканы колдонууну суранат.'],
  'impact': 'Minecraft аккаунттары оюн ичиндеги контентке эмес, аккаунттун түрүнө (Java же Bedrock), колдонуучунун атына жана жамынчыларга жараша бааланат. Мындай жаңыртуулар оюнчу эмне кыла аларын өзгөртөт, аккаунттун баасын эмес.'},
 'cr-bal-oct': {
  'title': 'Clash Royale октябрдагы баланс өзгөрүүлөрү: Hero Ice Wizard жана Minion Giant алсыратылды, Lava Hound күчөтүлдү',
  'desc': 'Supercell 2026-жылдын 6-октябрындагы баланс жаңыртуусун жарыялады: Hero Ice Wizard тоңдуруу зыяны 89 → 46, Minion Giant сокку ылдамдыгы 1,5 с → 1,7 с, Lava Hound зыяны 53 → 71, Golden Knight кайра иштелди.',
  'lead': 'Supercell Clash Royale’дин 2026-жылдын 6-октябрындагы баланс жаңыртуусун жарыялады.',
  'new': ['Алсыратуулар: Hero Ice Wizard тоңдуруу зыяны 89 → 46; Cannon Evolution удаа атуу зыяны 281 → 261; Barbarian Barrel зыяны 232 → 215; Minion Giant сокку ылдамдыгы 1,5 с → 1,7 с; Royal Ghost өмүр упайлары 1210 → 1152.',
          'Elixir Collector: иштөө убактысы 1 мүн 33 с → 1 мүн 50 с, өндүрүү ылдамдыгы 13 с → 15 с.',
          'Күчөтүүлөр: Lava Hound зыяны 53 → 71 (сокку ылдамдыгы 1,3 с → 1,5 с); Ram Rider зыяны 250 → 271; Wall Breakers зыяны 281 → 302; X-Bow зыяны 58 → 61; Three Musketeers өмүр упайлары 883 → 906.',
          'Кайра иштөө: Golden Knight зыяны 161 → 168, чабуул аралыгы 5,5 → 5 клетка. Supercell сандар 11-деңгээл үчүн берилгенин белгилейт.'],
  'impact': 'Баланс өзгөрүүлөрү кайсы колодалар күчтүү экенин өзгөртөт, аккаунтта эмне бар экенин эмес. Биздин изилдөөбүз боюнча, King Tower деңгээли жана карталардын деңгээли баалуулуктун негизги факторлору бойдон калууда.'},
}},
}
