# News translations: vi, hi (from news_data.py 'en', facts unchanged)
TEXT = {
'vi': {
 'ui': {
  'news': 'Tin tức', 'news_title': 'Tin tức game ảnh hưởng đến giá trị tài khoản',
  'news_lead': 'Cập nhật chính thức từ các nhà phát hành game — mỗi tin đều được đối chiếu với thông báo của chính nhà phát hành, kèm ghi chú ngắn về ý nghĩa với giá trị tài khoản.',
  'game_title': 'Tin tức {game}', 'game_lead': 'Các cập nhật chính thức của {game} ảnh hưởng đến giá trị tài khoản. Mỗi bài đều dẫn link thông báo của nhà phát hành.',
  'published': 'Đăng ngày', 'source': 'Nguồn chính thức', 'by_on': '{pub}, {date}', 'whats_new': 'Có gì mới',
  'impact': 'Ý nghĩa với giá trị tài khoản', 'more': 'Thêm tin {game}', 'all': 'Tất cả tin tức',
  'calc': '{game}: máy tính định giá và báo cáo thị trường', 'read': 'Đọc', 'latest': 'Tin {game} mới nhất',
  'note': 'GameAccountValue không mua, bán hay môi giới tài khoản. Tin tức được tóm tắt từ thông báo của nhà phát hành, chỉ để tham khảo.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna và Vodyanitsa ra mắt, xác nhận quà kỷ niệm',
   'desc': 'Phiên bản 7.1 "A Rekviem for the Underworld" ra mắt ngày 23/09/2026 với hai nhân vật 5 sao mới, hai vũ khí 5 sao và quà kỷ niệm 6 năm.',
   'lead': 'HoYoverse phát hành phiên bản 7.1 "A Rekviem for the Underworld" ngày 23/09/2026 — bản cập nhật cũng mang theo lễ kỷ niệm 6 năm của Genshin Impact.',
   'new': ['Hai nhân vật 5 sao mới: Vesna (Phong, kiếm đơn) và Vodyanitsa (Thủy, pháp khí).',
           'Vũ khí mới: Beyond the Chrysalis (kiếm đơn 5 sao), Hymn of the Maelstrom (pháp khí 5 sao) và New Bough (kiếm đơn 4 sao).',
           'Quà kỷ niệm HoYoverse công bố: mời hai nhân vật 5 sao, Mối Duyên Vương Vấn ×10, Nguyên Thạch ×1.600 và làm mới thưởng nạp lần đầu Đá Sáng Thế.',
           'Bảo trì cập nhật bắt đầu lúc 06:00 ngày 23/09 (UTC+8).'],
   'impact': 'Theo nghiên cứu của chúng tôi, số nhân vật 5 sao giới hạn, cung mệnh và vũ khí đặc trưng là một trong những yếu tố chính quyết định giá trị tài khoản Genshin. Nhân vật được tặng miễn phí cho mọi người dịp kỷ niệm làm tài khoản kém nổi bật hơn so với nhân vật từ banner giới hạn.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, chiều không gian mới đầu tiên sau hơn 14 năm, sẽ đến Java và Bedrock',
   'desc': 'Minecraft Live ngày 26/09/2026 giới thiệu The Sift, chiều không gian thứ tư sẽ đến Java và Bedrock năm sau, cùng Dungeons II và bản cập nhật Wilderness Bound.',
   'lead': 'Tại Minecraft Live ngày 26/09/2026, Mojang Studios công bố chiều không gian thứ tư của game, The Sift, sẽ đến Minecraft Java và Bedrock Edition vào năm sau.',
   'new': ['The Sift là chiều không gian mới đầu tiên sau hơn 14 năm, cùng với Overworld, Nether và End.',
           'Nó ra mắt trước trong Minecraft Dungeons II, được Mojang ấn định phát hành ngày 29/09/2026.',
           'Công viên chủ đề Minecraft World mở cửa tại London năm 2027.',
           'Bản cập nhật Wilderness Bound ra ngày 15/09 với rừng lốm đốm, giường rơm, trại bỏ hoang và đệm ngồi.'],
   'impact': 'Tài khoản Minecraft được định giá theo loại (Java hay Bedrock), tên người dùng và áo choàng — không theo nội dung trong game. Những cập nhật như vậy thay đổi điều người chơi có thể làm, không thay đổi giá trị tài khoản.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": vật phẩm UGC giới hạn và quà độc quyền Roblox Plus (17–28/9)',
   'desc': 'The Hunt: Roblox 20 diễn ra từ 17 đến 28/09/2026 với phần thưởng UGC, vật phẩm UGC phát hành giới hạn và ba vật phẩm độc quyền cho người đăng ký Roblox Plus.',
   'lead': 'Roblox kỷ niệm 20 năm bằng The Hunt: Roblox 20, sự kiện trên toàn nền tảng diễn ra từ 17 đến 28/09/2026.',
   'new': ['Người chơi đi qua 20 năm lịch sử Roblox, mỗi năm một nhiệm vụ, bắt đầu từ "Year Zero"; hoàn thành cả 20 năm sẽ mở "Year Infinity" với 20 game nữa.',
           'Nhiệm vụ tặng vật phẩm UGC, và vật phẩm UGC phát hành giới hạn có mặt trong suốt sự kiện.',
           'Người đăng ký Roblox Plus nhận ba vật phẩm ảo độc quyền và giữ lại giao diện ứng dụng Classic, nền avatar cổ điển và khung hồ sơ sau sự kiện.',
           'Giao diện ứng dụng Classic miễn phí cho mọi người trong thời gian sự kiện.'],
   'impact': 'Vật phẩm chỉ kiếm được trong sự kiện là một trong những điều mà việc thẩm định xem xét. Roblox không nêu tên các vật phẩm này trong thông báo, nên trang này chưa định giá chúng cho đến khi có tin đăng bán thật.'},
  'rbx-rdc': {
   'title': 'RDC 2026: nhà sáng tạo Roblox kiếm khoảng 1,7 tỷ USD trong một năm; ra mắt Roblox Wallet',
   'desc': 'Tại RDC 2026, Roblox cho biết nhà sáng tạo kiếm khoảng 1,7 tỷ USD trong 12 tháng và công bố Roblox Wallet cùng Roblox Card để chi trả.',
   'lead': 'Tại hội nghị nhà phát triển RDC 2026 (thông báo ngày 11/09/2026), Roblox chia sẻ số liệu thu nhập của nhà sáng tạo và các công cụ chi trả mới.',
   'new': ['Nhà sáng tạo đã kiếm hơn 5 tỷ USD kể từ khi DevEx ra mắt năm 2013, và khoảng 1,7 tỷ USD trong 12 tháng tính đến 30/06/2026.',
           'Các ưu đãi Roblox Plus mang lại hơn 300 triệu Robux thu nhập cho nhà sáng tạo trong bốn tháng đầu (đến 17/08/2026).',
           'Roblox Wallet, tài khoản thanh toán vận hành cùng Airwallex US, sẽ chi trả hằng ngày bằng tiền thật — trước tiên cho nhà sáng tạo độc lập đủ điều kiện ở Mỹ từ 18 tuổi vào cuối năm 2026, quốc tế vào năm 2027.',
           'Roblox Card liên kết với Wallet dự kiến ra mắt từ năm 2027.'],
   'impact': 'Những thay đổi này liên quan đến chi trả cho nhà sáng tạo, không phải tài khoản người chơi: thông báo không thay đổi giá Robux, vật phẩm giới hạn hay giao dịch. Số dư Robux và vật phẩm giới hạn vẫn là những gì máy tính Roblox của chúng tôi cân nhắc.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: bốn súng mới cho Tử Chiến, Prime Diamond và làm lại Kenta',
   'desc': 'Ghi chú bản cập nhật OB55 của Garena (10/09/2026) thêm M7, Skorp, RPK và Hawk vào Tử Chiến từ 1/10, ra mắt Prime Diamond và làm lại Kenta.',
   'lead': 'Garena công bố ghi chú bản cập nhật OB55 của Free Fire ngày 10/09/2026; các thay đổi súng có hiệu lực từ 1/10.',
   'new': ['Súng mới cho Tử Chiến (Clash Squad) từ 1/10: M7 (1.600 CS Cash), Skorp (1.500), RPK (1.500) và Hawk (1.700).',
           'Prime Diamond: kim cương nhận theo mức chi tiêu hằng tháng, nhận được vào tháng sau khi có bất kỳ lần nạp nào.',
           'Kenta được làm lại hoàn toàn; Morse, Luna và Wukong được cân bằng lại.',
           'Thay đổi độ cơ động theo loại súng từ 1/10: SMG nhanh hơn, súng bắn tỉa và súng trường thiện xạ chậm hơn.'],
   'impact': 'Máy tính Free Fire của chúng tôi cân nhắc số dư kim cương và các gói hiếm. OB55 thay đổi cách thưởng cho các lần nạp sau này; không thay đổi vật phẩm đã có trong tài khoản.'},
  'cr-minion': {
   'title': 'Mùa "Minion Academy" của Clash Royale: lá bài mới Minion Giant và anh hùng Ice Wizard',
   'desc': 'Mùa Minion Academy (7/9 – 5/10/2026) thêm lá bài Minion Giant, anh hùng Ice Wizard và sự kiện album tặng 1.750 thẻ Minion Giant.',
   'lead': 'Supercell mở mùa Clash Royale "Minion Academy", kéo dài từ 7/9 đến 5/10/2026.',
   'new': ['Lá bài mới Minion Giant: lá tấn công chính biết bay, nhắm vào công trình và tháp. Nhận miễn phí qua sự kiện album Academy Antics và chỉ xuất hiện trong rương từ mùa sau.',
           'Sự kiện album tặng 1.750 thẻ Minion Giant, một biểu cảm và một skin tháp.',
           'Anh hùng mới: Ice Wizard, từ đường Pass Royale hoặc với 200 Xu Anh Hùng.',
           'Sự kiện: Giải 2v2 (7–21/9), giải đấu toàn cầu Princess Gambit (21–26/9) và Royale Shuffle (21/9 – 5/10). Hòa ở Ultimate Champion giờ chỉ mất một nửa số cúp so với thua.'],
   'impact': 'Skin tháp và biểu cảm chỉ có trong sự kiện làm bộ sưu tập Clash Royale nổi bật hơn, còn cấp Tháp Vua và cấp thẻ bài vẫn là yếu tố giá trị chính.'},
  'ml-10': {
   'title': 'Mobile Legends tròn 10 tuổi: chiến dịch ALL IN và skin Collector mới cho Layla',
   'desc': 'Chiến dịch ALL IN mừng 10 năm của MOONTON (từ 4/9/2026) mang đến skin Epic mới cho Nana, rương skin miễn phí và skin Collector cho Layla từ 9/10.',
   'lead': 'MOONTON Games khởi động ALL IN, chiến dịch mừng 10 năm Mobile Legends: Bang Bang, vào ngày 4/9/2026.',
   'new': ['Thẻ Kỷ niệm 10 năm (4/9 – 1/11): skin Epic mới cho Nana, Rương Chọn Skin Epic, Rương Skin Epic Ngẫu nhiên và skin kỷ niệm miễn phí cho người chơi quay lại.',
           'Anniversary Gala Weekend (25/9 – 11/10): dùng thử 265 skin, EXP Battle Pass và Mảnh Skin Cao cấp.',
           'Layla’s Stellar Gala (9/10 – 19/11): skin Collector mới của Layla qua mini-game "Starfall Breakout".',
           'MOONTON cho biết game có hơn 1,5 tỷ lượt cài đặt và 110 triệu người chơi hoạt động mỗi tháng.'],
   'impact': 'Skin Collector và Legend nằm trong số các yếu tố giá trị được nhắc đến nhiều nhất với tài khoản Mobile Legends; skin tặng miễn phí hay dùng thử thì không.'},
  'bs-aug': {
   'title': 'Brawl Stars: tay đấu Thần thoại Cosmo và Vince; Starr Road thành Brawler Blast',
   'desc': 'Ghi chú cập nhật tháng 8/2026 của Supercell (1/9) thêm hai tay đấu Thần thoại, biến Starr Road thành Brawler Blast với giá tín dụng mới và đổi tên Ultra Legendary thành Ultra.',
   'lead': 'Supercell công bố ghi chú bản cập nhật tháng 8/2026 của Brawl Stars vào ngày 1/9/2026.',
   'new': ['Hai tay đấu Thần thoại mới: Cosmo (Kiểm soát) và Vince (Gây sát thương).',
           'Hypercharge mới cho Nori và Wendy.',
           'Starr Road được làm lại thành "Brawler Blast": tín dụng giờ dùng để mở khóa theo độ hiếm — Hiếm 160, Siêu hiếm 430, Sử thi 925, Thần thoại 1.900, Huyền thoại 3.800, Ultra 5.500.',
           'Độ hiếm "Ultra Legendary" được đổi tên thành "Ultra". Kèm mùa Royal Academy và sự kiện Brawl-O-Ween kéo dài cả tháng.'],
   'impact': 'Máy tính Brawl Stars của chúng tôi dùng số tay đấu, Hypercharge và cúp. Thêm hai tay đấu Thần thoại làm tăng số tay đấu cần có cho một bộ sưu tập đầy đủ.'},
  'coc-aug': {
   'title': 'Cập nhật tháng 8 của Clash of Clans: Diggy cấp 11–15 và Gold Pass từ Nhà Chính 3',
   'desc': 'Bản cập nhật tháng 8/2026 của Supercell (30/8) thêm cấp 11–15 cho Diggy và các cấp siêu nạp mới ở Nhà Chính 18, bỏ Starter Pass và mở Gold Pass từ Nhà Chính 3.',
   'lead': 'Supercell phát hành bản cập nhật tháng 8 của Clash of Clans ngày 30/8/2026.',
   'new': ['Nhà Chính 18: thú cưng Diggy có thêm cấp 11–15; Chòi Thợ Xây và Monolith có cấp siêu nạp mới.',
           'Bỏ Starter Pass: Thử thách Mùa và Gold Pass giờ có từ Nhà Chính 3, phần thưởng tăng theo cấp Nhà Chính.',
           'Ruin Knight không còn mất máu theo thời gian; Ruin Witch triệu hồi 10 Ruin Knight thay vì 8.',
           'Điều chỉnh các bộ điều chỉnh của Liên đoàn Chiến tranh Bang ở các giải Titan.'],
   'impact': 'Theo nghiên cứu của chúng tôi, cấp Nhà Chính cùng cấp anh hùng và thú cưng quyết định giá trị tài khoản Clash of Clans. Cấp tối đa mới ở Nhà Chính 18 nghĩa là một tài khoản "max" giờ cần nhiều nâng cấp hơn trước bản cập nhật.'},
  'fn-c7s4': {
   'title': 'Fortnite Chương 7 Mùa 4 "Override": Battle Pass Sonic và hợp tác KINGDOM HEARTS',
   'desc': 'Mùa "Override" của Epic (Chương 7 Mùa 4) có Override Console, Battle Pass 800 V-Bucks do Sonic the Hedgehog dẫn đầu và các màn hợp tác như KINGDOM HEARTS.',
   'lead': 'Chương 7 Mùa 4 của Fortnite mang tên "Override". Epic mô tả đây là mùa xoay quanh các màn hợp tác game và thay đổi luật cho cả trận.',
   'new': ['Override Console xuất hiện ở mọi trận và cho người chơi thay đổi luật cho toàn bộ máy chủ.',
           'Battle Pass giá 800 V-Bucks, dẫn đầu bởi Sonic the Hedgehog cùng bạn đồng hành Tails.',
           'Người mua Pass trước 23:59 ngày 27/8 (giờ miền Đông Mỹ) nhận trang phục Infiltrator Grace Crowne làm quà tuần ra mắt.',
           'Hợp tác trong mùa: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot và Spyro the Dragon; vũ khí có Midas’ Masterpiece và Mega Buster của Mega Man.'],
   'impact': 'Trang phục chỉ có trong thời gian giới hạn — như quà tuần ra mắt — là thứ phân biệt tủ đồ Fortnite hiếm với tủ đồ thường. Trang phục Battle Pass gắn liền với mùa mà chúng ra đời.'},
 }},
'hi': {
 'ui': {
  'news': 'समाचार', 'news_title': 'गेम समाचार जो अकाउंट की कीमत पर असर डालते हैं',
  'news_lead': 'गेम पब्लिशर्स के आधिकारिक अपडेट — हर एक को पब्लिशर की अपनी घोषणा से मिलाकर जाँचा गया है, साथ में अकाउंट की कीमत के लिए इसका मतलब सरल शब्दों में।',
  'game_title': '{game} समाचार', 'game_lead': '{game} के आधिकारिक अपडेट जो किसी अकाउंट की कीमत पर असर डालते हैं। हर लेख में पब्लिशर की घोषणा का लिंक है।',
  'published': 'प्रकाशित', 'source': 'आधिकारिक स्रोत', 'by_on': '{pub}, {date}', 'whats_new': 'क्या नया है',
  'impact': 'अकाउंट की कीमत के लिए इसका मतलब', 'more': '{game} के और समाचार', 'all': 'सभी समाचार',
  'calc': '{game}: वैल्यू कैलकुलेटर और मार्केट रिपोर्ट', 'read': 'पढ़ें', 'latest': '{game} के ताज़ा समाचार',
  'note': 'GameAccountValue अकाउंट न ख़रीदता है, न बेचता है, न उनकी दलाली करता है। समाचार सिर्फ़ जानकारी के लिए पब्लिशर्स की घोषणाओं से संक्षेप में दिए गए हैं।'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna और Vodyanitsa आए, एनिवर्सरी रिवॉर्ड की पुष्टि',
   'desc': 'वर्ज़न 7.1 "A Rekviem for the Underworld" 23 सितंबर 2026 को दो नए 5-स्टार कैरेक्टर, दो 5-स्टार हथियार और छठी एनिवर्सरी रिवॉर्ड के साथ आया।',
   'lead': 'HoYoverse ने 23 सितंबर 2026 को वर्ज़न 7.1 "A Rekviem for the Underworld" जारी किया — इसी अपडेट के साथ Genshin Impact की छठी एनिवर्सरी भी आई।',
   'new': ['दो नए 5-स्टार कैरेक्टर: Vesna (Anemo, तलवार) और Vodyanitsa (Hydro, कैटलिस्ट)।',
           'नए हथियार: Beyond the Chrysalis (5-स्टार तलवार), Hymn of the Maelstrom (5-स्टार कैटलिस्ट) और New Bough (4-स्टार तलवार)।',
           'HoYoverse द्वारा घोषित एनिवर्सरी रिवॉर्ड: बुलाने के लिए दो 5-स्टार कैरेक्टर, Intertwined Fate ×10, Primogems ×1,600 और Genesis Crystal के पहले टॉप-अप बोनस का रीसेट।',
           'अपडेट मेंटेनेंस 23 सितंबर को सुबह 06:00 (UTC+8) शुरू हुआ।'],
   'impact': 'हमारी रिसर्च में लिमिटेड 5-स्टार कैरेक्टर की संख्या, उनके कॉन्स्टेलेशन और सिग्नेचर हथियार Genshin अकाउंट की कीमत के मुख्य कारकों में से हैं। एनिवर्सरी पर सबको मुफ़्त मिलने वाले कैरेक्टर किसी अकाउंट को लिमिटेड बैनर वाले कैरेक्टर जितना ख़ास नहीं बनाते।'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, 14 साल से ज़्यादा में पहला नया डाइमेंशन, Java और Bedrock में आएगा',
   'desc': '26 सितंबर 2026 के Minecraft Live में The Sift दिखाया गया — चौथा डाइमेंशन जो अगले साल Java और Bedrock में आएगा — साथ में Dungeons II और Wilderness Bound अपडेट।',
   'lead': '26 सितंबर 2026 को Minecraft Live में Mojang Studios ने घोषणा की कि गेम का चौथा डाइमेंशन, The Sift, अगले साल Minecraft Java और Bedrock Edition में आएगा।',
   'new': ['The Sift 14 साल से ज़्यादा में पहला नया डाइमेंशन है, जो Overworld, Nether और End के साथ जुड़ेगा।',
           'इसकी शुरुआत Minecraft Dungeons II में होगी, जिसकी रिलीज़ Mojang ने 29 सितंबर 2026 तय की।',
           'थीम आधारित आकर्षण Minecraft World 2027 में लंदन में खुलेगा।',
           'Wilderness Bound अपडेट 15 सितंबर को आया — dappled forest, भूसे के बिस्तर, वीरान कैंप और कुशन के साथ।'],
   'impact': 'Minecraft अकाउंट की कीमत अकाउंट के प्रकार (Java या Bedrock), यूज़रनेम और केप से तय होती है, गेम के कंटेंट से नहीं। ऐसे अपडेट यह बदलते हैं कि खिलाड़ी क्या कर सकते हैं, अकाउंट की कीमत नहीं।'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": लिमिटेड UGC आइटम और Roblox Plus के एक्सक्लूसिव (17–28 सितंबर)',
   'desc': 'The Hunt: Roblox 20 17 से 28 सितंबर 2026 तक चला — UGC रिवॉर्ड, लिमिटेड-रिलीज़ UGC आइटम और Roblox Plus सब्सक्राइबर्स के लिए तीन एक्सक्लूसिव आइटम के साथ।',
   'lead': 'Roblox ने अपनी 20वीं सालगिरह पूरे प्लेटफ़ॉर्म पर The Hunt: Roblox 20 इवेंट से मनाई, जो 17 से 28 सितंबर 2026 तक चला।',
   'new': ['खिलाड़ी Roblox के 20 साल के इतिहास से गुज़रे — हर साल के लिए एक क्वेस्ट, शुरुआत "Year Zero" से; सभी 20 पूरे करने पर "Year Infinity" खुला, जिसमें 20 और गेम थे।',
           'क्वेस्ट पर UGC आइटम मिले, और इवेंट के दौरान लिमिटेड-रिलीज़ UGC आइटम उपलब्ध रहे।',
           'Roblox Plus सब्सक्राइबर्स को तीन एक्सक्लूसिव वर्चुअल आइटम मिले, और इवेंट के बाद भी Classic ऐप थीम, क्लासिक अवतार बैकग्राउंड और प्रोफ़ाइल फ़्रेम उनके पास रहेंगे।',
           'इवेंट के दौरान Classic ऐप थीम सबके लिए मुफ़्त थी।'],
   'impact': 'जो आइटम सिर्फ़ किसी इवेंट के दौरान मिल सकते थे, वे उन चीज़ों में हैं जिन्हें मूल्यांकन देखता है। Roblox ने घोषणा में इन आइटम के नाम नहीं बताए, इसलिए जब तक असली लिस्टिंग न आएँ, यह साइट इनकी कीमत नहीं लगाती।'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox क्रिएटर्स ने एक साल में लगभग $1.7 अरब कमाए; Roblox Wallet की घोषणा',
   'desc': 'RDC 2026 में Roblox ने 12 महीनों में क्रिएटर्स की लगभग $1.7 अरब कमाई बताई और भुगतान के लिए Roblox Wallet और Roblox Card की घोषणा की।',
   'lead': 'अपने डेवलपर सम्मेलन RDC 2026 में (11 सितंबर 2026 की घोषणा) Roblox ने क्रिएटर्स की कमाई के आँकड़े और भुगतान के नए टूल साझा किए।',
   'new': ['2013 में DevEx शुरू होने के बाद से क्रिएटर्स $5 अरब से ज़्यादा कमा चुके हैं, और 30 जून 2026 तक के 12 महीनों में लगभग $1.7 अरब।',
           'Roblox Plus इंसेंटिव से पहले चार महीनों में (17 अगस्त 2026 तक) क्रिएटर्स को 30 करोड़ से ज़्यादा Robux की कमाई हुई।',
           'Roblox Wallet, Airwallex US के साथ चलने वाला पेमेंट अकाउंट, असली मुद्रा में रोज़ाना भुगतान देगा — पहले 2026 के अंत में अमेरिका के योग्य 18+ स्वतंत्र क्रिएटर्स के लिए, और 2027 में अंतरराष्ट्रीय स्तर पर।',
           'Wallet से जुड़ा Roblox Card 2027 से लाने की योजना है।'],
   'impact': 'ये बदलाव क्रिएटर्स के भुगतान से जुड़े हैं, खिलाड़ियों के अकाउंट से नहीं: घोषणा ने Robux की कीमतें, लिमिटेड आइटम या ट्रेडिंग नहीं बदली। Robux बैलेंस और लिमिटेड आइटम ही वह हैं जिन्हें हमारा Roblox कैलकुलेटर गिनता है।'},
  'ff-ob55': {
   'title': 'Free Fire OB55: Clash Squad में चार नए हथियार, Prime Diamond और Kenta का रीवर्क',
   'desc': 'Garena के OB55 पैच नोट्स (10 सितंबर 2026) 1 अक्टूबर से Clash Squad में M7, Skorp, RPK और Hawk जोड़ते हैं, Prime Diamond लाते हैं और Kenta को रीवर्क करते हैं।',
   'lead': 'Garena ने 10 सितंबर 2026 को Free Fire के OB55 पैच नोट्स जारी किए; हथियारों के बदलाव 1 अक्टूबर से लागू होते हैं।',
   'new': ['1 अक्टूबर से Clash Squad के नए हथियार: M7 (1,600 CS Cash), Skorp (1,500), RPK (1,500) और Hawk (1,700)।',
           'Prime Diamond: मासिक ख़र्च के हिसाब से डायमंड, जो किसी भी टॉप-अप के बाद अगले महीने क्लेम किए जा सकते हैं।',
           'Kenta को पूरी तरह रीवर्क किया गया; Morse, Luna और Wukong में बैलेंस बदलाव।',
           '1 अक्टूबर से हथियार श्रेणी के हिसाब से मोबिलिटी बदली: SMG तेज़, स्नाइपर और मार्क्समैन राइफ़ल धीमी।'],
   'impact': 'हमारा Free Fire कैलकुलेटर डायमंड बैलेंस और दुर्लभ बंडल गिनता है। OB55 आगे के टॉप-अप के इनाम का तरीका बदलता है; मौजूदा अकाउंट में पहले से मौजूद आइटम नहीं बदलते।'},
  'cr-minion': {
   'title': 'Clash Royale का "Minion Academy" सीज़न: नया कार्ड Minion Giant और Ice Wizard हीरो',
   'desc': 'Minion Academy सीज़न (7 सितंबर – 5 अक्टूबर 2026) Minion Giant कार्ड, Ice Wizard हीरो और 1,750 Minion Giant कार्ड वाला एल्बम इवेंट लाता है।',
   'lead': 'Supercell ने Clash Royale का "Minion Academy" सीज़न शुरू किया, जो 7 सितंबर से 5 अक्टूबर 2026 तक चलेगा।',
   'new': ['नया कार्ड Minion Giant: उड़ने वाला विन कंडीशन कार्ड जो इमारतों और टावरों को निशाना बनाता है। यह Academy Antics एल्बम इवेंट से मुफ़्त मिलता है और अगले सीज़न से पहले चेस्ट में नहीं आएगा।',
           'एल्बम इवेंट से 1,750 Minion Giant कार्ड, एक इमोट और एक टावर स्किन मिलती है।',
           'नया हीरो: Ice Wizard, Pass Royale ट्रैक से या 200 Hero Coins में।',
           'इवेंट: 2v2 लीग (7–21 सितंबर), Princess Gambit ग्लोबल टूर्नामेंट (21–26 सितंबर) और Royale Shuffle (21 सितंबर – 5 अक्टूबर)। Ultimate Champion में ड्रॉ पर अब हार के आधे ट्रॉफ़ी ही जाते हैं।'],
   'impact': 'सिर्फ़ इवेंट के दौरान मिलने वाली टावर स्किन और इमोट Clash Royale कलेक्शन को ज़्यादा ख़ास बनाते हैं, जबकि King Tower लेवल और कार्ड लेवल ही मुख्य कीमत कारक बने रहते हैं।'},
  'ml-10': {
   'title': 'Mobile Legends के 10 साल: ALL IN कैंपेन और Layla की नई Collector स्किन',
   'desc': 'MOONTON का 10वीं सालगिरह कैंपेन ALL IN (4 सितंबर 2026 से) Nana की नई Epic स्किन, मुफ़्त स्किन चेस्ट और 9 अक्टूबर से Layla की Collector स्किन लाता है।',
   'lead': 'MOONTON Games ने 4 सितंबर 2026 को Mobile Legends: Bang Bang का दसवीं सालगिरह कैंपेन ALL IN शुरू किया।',
   'new': ['10th Anniversary Celebration Pass (4 सितंबर – 1 नवंबर): Nana की नई Epic स्किन, Epic Skin Selection Chest, Random Epic Skin Chest और लौटने वाले खिलाड़ियों के लिए मुफ़्त एनिवर्सरी स्किन।',
           'Anniversary Gala Weekend (25 सितंबर – 11 अक्टूबर): 265 स्किन का एक्सेस, Battle Pass EXP और Premium Skin Fragments।',
           'Layla’s Stellar Gala (9 अक्टूबर – 19 नवंबर): "Starfall Breakout" मिनी-गेम से Layla की नई Collector स्किन।',
           'MOONTON 1.5 अरब से ज़्यादा इंस्टॉल और हर महीने 11 करोड़ सक्रिय खिलाड़ियों का आँकड़ा देता है।'],
   'impact': 'Collector और Legend स्किन Mobile Legends अकाउंट की कीमत के सबसे ज़्यादा बताए जाने वाले कारकों में हैं; मुफ़्त या ट्रायल में दी गई स्किन नहीं।'},
  'bs-aug': {
   'title': 'Brawl Stars: Mythic ब्रॉलर Cosmo और Vince; Starr Road अब Brawler Blast',
   'desc': 'Supercell के अगस्त 2026 रिलीज़ नोट्स (1 सितंबर) दो Mythic ब्रॉलर जोड़ते हैं, Starr Road को नए क्रेडिट दामों के साथ Brawler Blast बनाते हैं और Ultra Legendary का नाम Ultra करते हैं।',
   'lead': 'Supercell ने 1 सितंबर 2026 को Brawl Stars के अगस्त 2026 अपडेट के रिलीज़ नोट्स जारी किए।',
   'new': ['दो नए Mythic ब्रॉलर: Cosmo (Controller) और Vince (Damage Dealer)।',
           'Nori और Wendy के लिए नए Hypercharge।',
           'Starr Road को "Brawler Blast" में बदला गया: क्रेडिट अब रैरिटी के हिसाब से अनलॉक में लगते हैं — Rare 160, Super Rare 430, Epic 925, Mythic 1,900, Legendary 3,800, Ultra 5,500।',
           '"Ultra Legendary" रैरिटी का नाम अब "Ultra" है। साथ में Royal Academy सीज़न और पूरे महीने चलने वाला Brawl-O-Ween इवेंट।'],
   'impact': 'हमारा Brawl Stars कैलकुलेटर ब्रॉलर की संख्या, Hypercharge और ट्रॉफ़ी देखता है। दो और Mythic से पूरे कलेक्शन के लिए ज़रूरी ब्रॉलर की संख्या बढ़ जाती है।'},
  'coc-aug': {
   'title': 'Clash of Clans अगस्त अपडेट: Diggy लेवल 11–15 और Town Hall 3 से Gold Pass',
   'desc': 'Supercell का अगस्त 2026 अपडेट (30 अगस्त) Town Hall 18 पर Diggy लेवल 11–15 और नए सुपरचार्ज जोड़ता है, Starter Pass हटाता है और Town Hall 3 से Gold Pass खोलता है।',
   'lead': 'Supercell ने 30 अगस्त 2026 को Clash of Clans का अगस्त अपडेट जारी किया।',
   'new': ['Town Hall 18: पेट Diggy को लेवल 11–15; Builder’s Hut और Monolith को नए सुपरचार्ज लेवल।',
           'Starter Pass हटाया गया: Season Challenges और Gold Pass अब Town Hall 3 से उपलब्ध हैं, इनाम Town Hall लेवल के हिसाब से।',
           'Ruin Knight अब समय के साथ हेल्थ नहीं खोता; Ruin Witch अब 8 की जगह 10 Ruin Knight बुलाती है।',
           'Titan लीग में Clan War League के मॉडिफ़ायर बदले गए।'],
   'impact': 'हमारी रिसर्च में Town Hall लेवल और हीरो व पेट लेवल Clash of Clans अकाउंट की कीमत तय करते हैं। Town Hall 18 पर नए अधिकतम लेवल का मतलब है कि "मैक्स" अकाउंट को अब अपडेट से पहले से ज़्यादा अपग्रेड चाहिए।'},
  'fn-c7s4': {
   'title': 'Fortnite चैप्टर 7 सीज़न 4 "Override": Sonic Battle Pass और KINGDOM HEARTS क्रॉसओवर',
   'desc': 'Epic का "Override" सीज़न (चैप्टर 7, सीज़न 4) Override Console, Sonic the Hedgehog वाला 800 V-Bucks का Battle Pass और KINGDOM HEARTS समेत क्रॉसओवर लाता है।',
   'lead': 'Fortnite के चैप्टर 7 सीज़न 4 का नाम "Override" है। Epic इसे गेमिंग क्रॉसओवर और पूरे मैच के नियम बदलने वाला सीज़न बताता है।',
   'new': ['Override Console हर मैच में आते हैं और खिलाड़ियों को पूरे सर्वर के नियम बदलने देते हैं।',
           'Battle Pass 800 V-Bucks का है, जिसमें सबसे आगे Sonic the Hedgehog और साथ में Tails Sidekick हैं।',
           '27 अगस्त रात 11:59 (अमेरिकी पूर्वी समय) से पहले Pass ख़रीदने वालों को लॉन्च-वीक बोनस में Infiltrator Grace Crowne आउटफ़िट मिला।',
           'सीज़न के क्रॉसओवर: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot और Spyro the Dragon; हथियारों में Midas’ Masterpiece और Mega Man का Mega Buster।'],
   'impact': 'सिर्फ़ सीमित समय के लिए मिलने वाले आउटफ़िट — जैसे लॉन्च-वीक बोनस — ही दुर्लभ Fortnite लॉकर को आम लॉकर से अलग करते हैं। Battle Pass आउटफ़िट अपने सीज़न से जुड़े रहते हैं।'},
 }},
}
