# News batch 2: vi, hi (from news_text_b2_en.py, facts unchanged)
TEXT = {
'vi': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II đã ra mắt: chiều không gian Sift và Hội đồng Illager tối cao',
  'desc': 'Mojang phát hành Minecraft Dungeons II ngày 29/09/2026 trên Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch và Switch 2, hỗ trợ chơi chung tối đa 4 người.',
  'lead': 'Mojang Studios phát hành Minecraft Dungeons II ngày 29/09/2026.',
  'new': ['Có mặt trên Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch và Nintendo Switch 2.',
          'Cốt truyện đưa người chơi đối đầu Hội đồng Illager tối cao: Prime Enchanter, Supreme Evoker và Grand Illusioner.',
          'Người chơi khám phá chiều không gian mới Sift, mà theo Mojang cũng sẽ đến Minecraft Java và Bedrock vào năm sau.',
          'Có thể chơi một mình hoặc chơi chung tối đa 4 người, trực tuyến hay cùng màn hình.'],
  'impact': 'Dungeons II là một game riêng. Tài khoản Minecraft Java và Bedrock vẫn được định giá theo loại, tên người dùng và áo choàng, nên việc ra mắt không làm thay đổi giá trị của chúng.'},
 'cr-mt-oct': {'title': 'Merge Tactics của Clash Royale: thay đổi tháng 10 với Super, Elixir và huy hiệu',
  'desc': 'Từ 1/10/2026, mùa 11 của Merge Tactics đưa Super vào kho chung, giảm Elixir mỗi vòng từ 5 xuống 4 và thêm skin cấp 5; quy định huy hiệu thay đổi từ mùa 12.',
  'lead': 'Supercell công bố thay đổi tháng 10 cho mùa 11 của Merge Tactics ngày 30/09/2026; áp dụng từ 1/10.',
  'new': ['Super không còn là quân khởi đầu: chúng vào kho chung để mọi người chơi tranh giành.',
          'Elixir nhận mỗi vòng quay lại từ 5 xuống 4.',
          'Battle Machine và Dagger Duchess có skin cấp 5 cho người chơi đã nâng cấp chúng.',
          'Từ mùa 12, huy hiệu Bạc cần lên Liên đoàn Kim cương và huy hiệu Vàng cần lọt top 10.000.'],
  'impact': 'Từ mùa 12, huy hiệu thứ hạng cao khó đạt hơn, nên thể hiện kỹ năng rõ hơn trên hồ sơ Clash Royale. Cấp Tháp Vua và cấp thẻ vẫn là yếu tố giá trị chính.'},
 'ml-mplph': {'title': 'Vòng playoff MPL Philippines mùa 18: PhilSports Arena, 21–25/10',
  'desc': 'MOONTON công bố ngày 26/09/2026 rằng vòng playoff MPL Philippines mùa 18 diễn ra 21–25/10 tại PhilSports Arena và chọn ra đội Philippines dự M8.',
  'lead': 'MOONTON Games công bố địa điểm và lịch vòng playoff MPL Philippines mùa 18 ngày 26/09/2026.',
  'new': ['Vòng playoff diễn ra tại PhilSports Arena, thành phố Pasig, từ 21 đến 25/10/2026.',
          'Giải chọn ra các đội đại diện Philippines dự Giải vô địch thế giới M8 tại Istanbul vào tháng 1/2027.',
          'Vé mở bán từ 26/09, giá từ 200 peso Philippines.',
          'Thông báo đánh dấu 10 năm của game, với 1,5 tỷ lượt cài đặt và 110 triệu người chơi hoạt động mỗi tháng.'],
  'impact': 'Các sự kiện esports không thay đổi giá trị tài khoản hiện có. Theo nghiên cứu của chúng tôi, giá trị tài khoản Mobile Legends đến từ skin, tướng và tiến độ.'},
 'cr-bal-sep': {'title': 'Cân bằng tháng 9 của Clash Royale: giảm sức mạnh anh hùng Ice Wizard và Minion Giant',
  'desc': 'Ghi chú cân bằng tháng 9/2026 của Supercell giảm thời gian đóng băng của anh hùng Ice Wizard từ 7 xuống 5 giây và sát thương Minion Giant từ 189 xuống 168, đồng thời làm lại anh hùng Mega Minion và Wizard.',
  'lead': 'Supercell đăng hai đợt điều chỉnh cân bằng Clash Royale, áp dụng ngày 8 và 16/09/2026.',
  'new': ['16/09: đóng băng của anh hùng Ice Wizard 7 giây → 5 giây; kỹ năng Goblinstein 4 giây → 3,5 giây; sát thương Minion Giant 189 → 168; sát thương Fire Spirit 207 → 215.',
          '08/09: Freeze 4 giây → 3,5 giây; sát thương Fireball lên tháp 172 → 159; máu Ice Golem 1.315 → 1.228.',
          'Làm lại: anh hùng Mega Minion (dịch chuyển về chỗ cũ, sát thương 399 → 422) và anh hùng Wizard (kỹ năng 5 giây → 3,5 giây); sát thương Wizard 281 → 304.',
          'Được tăng sức mạnh gồm Ronin, Spirit Empress và Goblin Cage.'],
  'impact': 'Cân bằng thay đổi lá bài nào được ưa chuộng, không thay đổi những gì tài khoản sở hữu. Theo nghiên cứu của chúng tôi, giá trị Clash Royale theo cấp Tháp Vua, cấp thẻ, tiến hóa và vật phẩm trang trí hiếm.'},
 'gi-wish71': {'title': 'Cầu nguyện sự kiện Genshin Impact 7.1: banner Vesna và Vodyanitsa đến 13/10',
  'desc': 'Cầu nguyện sự kiện giai đoạn I phiên bản 7.1 của HoYoverse tăng tỉ lệ Vesna và Vodyanitsa đến 13/10/2026, với Diona, Faruzan và Chongyun là nhân vật 4 sao tăng tỉ lệ.',
  'lead': 'HoYoverse đăng cầu nguyện sự kiện giai đoạn I phiên bản 7.1 ngày 21/09/2026; kéo dài đến 17:59 ngày 13/10/2026.',
  'new': ['"When Warm Winds Cavort" tăng tỉ lệ nhận Vesna (Phong).',
          '"Surging Ballad" tăng tỉ lệ nhận Vodyanitsa (Thủy).',
          'Nhân vật 4 sao tăng tỉ lệ: Diona (Băng), Faruzan (Phong) và Chongyun (Băng).',
          'Nhân vật độc quyền sự kiện không có trong cầu nguyện thường; hai banner nhân vật dùng chung bộ đếm bảo hiểm.'],
  'impact': 'Theo nghiên cứu của chúng tôi, nhân vật chỉ có trong banner giới hạn và cung mệnh của họ là một trong những yếu tố chính quyết định giá trị tài khoản Genshin.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: skin Darryl Trash Goblin và phần thưởng đến 30/9',
  'desc': 'Sự kiện Brawl Stars × Duolingo của Supercell (công bố 19/09/2026) tặng skin Darryl Trash Goblin, đá quý, Starr Drop và nhiều thứ khác đến 30/9.',
  'lead': 'Supercell công bố màn hợp tác Brawl Stars × Duolingo ngày 19/09/2026; sự kiện kéo dài đến 30/9.',
  'new': ['Hai giai đoạn mục tiêu cộng đồng và nhiệm vụ trong game, cùng chế độ mới Duo Boss Fight.',
          'Phần thưởng: skin Darryl Trash Goblin, 20 đá quý, 5 Chaos Drop, 3 Mythic Starr Drop, 2.000 xu, 2.500 Bling và 1.000 tín dụng.',
          'Nhiệm vụ Brawl Stars trong ứng dụng Duolingo tặng thêm vật phẩm trang trí.',
          'Supercell cũng tổ chức đố vui trên mạng xã hội với giải thưởng 3,141592 triệu đá quý.'],
  'impact': 'Skin từ những màn hợp tác chỉ có một lần giúp một số bộ sưu tập Brawl Stars nổi bật; skin mà nhiều người nhận miễn phí đóng góp ít hơn skin trả phí hiếm.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN trở lại: Cửu Vĩ và gói Hinata (16/9 – 15/10)',
  'desc': 'Màn hợp tác của Garena với NARUTO SHIPPUDEN diễn ra từ 16/9 đến 15/10/2026 với kỹ năng Sharingan: Control, gói chọn Jiraiya hoặc Hinata và vật phẩm trang trí theo chủ đề.',
  'lead': 'Garena công bố ngày 15/09/2026 rằng màn hợp tác Free Fire × NARUTO SHIPPUDEN trở lại từ 16/9 đến 15/10.',
  'new': ['Kỹ năng mới: Sharingan: Control để điều khiển Cửu Vĩ, và 8 Trigrams Palm Rotation.',
          'Học viện Ninja được mở rộng trên bản đồ Làng Lá.',
          'Giải lớn được chọn một: gói Jiraiya hoặc gói Hinata (lần đầu Hinata xuất hiện).',
          'Vật phẩm trang trí: áo choàng Tsunade, sơn mặt hình xăm Gaara, mặt nạ ANBU của Kakashi và hòm Froggy Wallet.'],
  'impact': 'Các gói từ màn hợp tác có bản quyền chỉ bán trong thời gian giới hạn nằm trong số vật phẩm hiếm mà máy tính Free Fire của chúng tôi tìm kiếm.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship mùa 8 khởi tranh, hướng tới M8 tại Istanbul',
  'desc': 'MTC mùa 8 diễn ra từ 12/9 đến 18/10/2026 với tám đội và quỹ thưởng 40.000 USD, trước Giải vô địch thế giới M8 tại Istanbul vào tháng 1/2027.',
  'lead': 'MOONTON Games công bố ngày 10/09/2026 rằng MLBB Türkiye Championship mùa 8 khởi tranh ngày 12/9.',
  'new': ['Mùa giải chính từ 12/9 đến 18/10; chung kết tổng ngày 7/11/2026.',
          'Tám đội tham gia, trong đó có Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok và Dark Passage.',
          'Sáu đội dẫn đầu vào playoff để tranh quỹ thưởng 40.000 USD.',
          'Giải vô địch thế giới M8 tổ chức tại Istanbul vào tháng 1/2027 — sự kiện M Series đầu tiên ở châu Âu.'],
  'impact': 'Kết quả esports không thay đổi giá trị tài khoản hiện có; skin Collector, Legend và số tướng vẫn là yếu tố chính theo nghiên cứu của chúng tôi.'},
 'coc-blast': {'title': 'Sự kiện huy chương Equipment Blast của Clash of Clans (9–22/9)',
  'desc': 'Sự kiện Equipment Blast diễn ra 9–22/09/2026: kiếm Tag Ticket và Champ Medal để đổi ở Thương nhân lấy trang bị anh hùng, quặng và vật phẩm trang trí. Từ Nhà Chính 6.',
  'lead': 'Supercell công bố sự kiện huy chương Equipment Blast ngày 09/09/2026; kéo dài đến 08:00 UTC ngày 22/9, Thương nhân mở đến 24/9.',
  'new': ['Trận nhiều người chơi cho Tag Ticket; đường sự kiện cho Champ Medal, quân tạm thời và rương.',
          'Thương nhân bán trang bị anh hùng, quặng và vật phẩm trang trí bằng huy chương sự kiện.',
          'Quân tạm thời: Undertaker Yeti, K.A.N.E., Yeeter và Giant Giant.',
          'Mở từ Nhà Chính 6.'],
  'impact': 'Trang bị anh hùng và cấp của chúng góp phần vào sức mạnh anh hùng — yếu tố quyết định giá trị tài khoản Clash of Clans theo nghiên cứu của chúng tôi; huy chương sự kiện là thêm một cách nâng cấp.'},
 'mc-wild': {'title': 'Bản cập nhật Minecraft Wilderness Bound: rừng lốm đốm, giường rơm và trại bỏ hoang',
  'desc': 'Bản cập nhật Wilderness Bound của Mojang ra mắt ngày 15/09/2026 với quần xã rừng lốm đốm, gỗ dương, giường rơm, trại bỏ hoang và đệm ngồi.',
  'lead': 'Mojang Studios đặt tên bản cập nhật thứ ba của năm 2026 là "Wilderness Bound" ngày 5/9 và phát hành ngày 15/9.',
  'new': ['Quần xã mới: rừng lốm đốm với cây dương cao và nấm kệ.',
          'Giường rơm làm từ ba kiện cỏ khô giúp bỏ qua ban đêm mà không đổi điểm hồi sinh.',
          'Trại bỏ hoang để khám phá, và đệm ngồi làm từ ba phiến len cùng màu.',
          'Gỗ dương cùng các bộ bê tông và len mở rộng để xây dựng.'],
  'impact': 'Tài khoản Minecraft được định giá theo loại, tên người dùng và áo choàng, không theo nội dung game, nên bản cập nhật không làm thay đổi giá trị tài khoản.'},
 'ff-award': {'title': 'Free Fire thắng giải "Sử dụng IP hoặc bản quyền xuất sắc nhất" tại Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena cho biết ngày 03/09/2026 rằng Free Fire thắng giải Best Use of IP or Licence tại Pocket Gamer Mobile Games Awards 2026 nhờ màn hợp tác NARUTO SHIPPUDEN.',
  'lead': 'Garena công bố ngày 03/09/2026 rằng Free Fire thắng giải "Best Use of IP or Licence" tại Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Giải thưởng ghi nhận màn hợp tác NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Theo Garena, sự kiện Ninja Clash All Stars ở Bangkok thu hút gần 5.000 khách và hơn 247 triệu lượt xem video.',
          'Màn hợp tác có nhân vật theo chủ đề, kỹ năng nhẫn thuật và bản đồ Làng Lá được biến đổi.',
          'Các sự kiện cộng đồng được tổ chức tại Peru, Bangladesh, Malaysia và Đài Loan.'],
  'impact': 'Giải thưởng không thay đổi giá trị tài khoản, nhưng khẳng định các màn hợp tác có bản quyền là một phần thường xuyên của Free Fire — và gói giới hạn của chúng nằm trong số vật phẩm hiếm mà việc thẩm định xem xét.'},
 'rbx-fall': {'title': 'Giới thiệu game mùa thu của Roblox: 10 trải nghiệm ra mắt trong tháng 9 và 10',
  'desc': 'Bài giới thiệu game mùa thu của Roblox (02/09/2026) liệt kê 10 trải nghiệm mới, từ Showdown và Nemesis tháng 9 đến Prime Heroes, Octane và Starforged tháng 10.',
  'lead': 'Roblox đăng bài giới thiệu game mùa thu ngày 02/09/2026, gồm mười trải nghiệm ra mắt trong tháng 9 và 10.',
  'new': ['Tháng 9: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force và Caramel.',
          'Tháng 10: Prime Heroes (truy cập sớm từ tháng 9 với 6 anh hùng), Octane, Starforged và Scrapbook Saga.',
          'Một số game đến từ chương trình nhà sáng tạo Jumpstart và Incubator của Roblox.',
          'Thể loại trải dài từ bắn súng, đua xe đến kinh dị sinh tồn và nông trại.'],
  'impact': 'Trải nghiệm mới không thay đổi tài khoản hiện có. Theo nghiên cứu của chúng tôi, giá trị tài khoản Roblox đến từ Robux, vật phẩm giới hạn và vật phẩm trong các trải nghiệm lâu năm; game mới chỉ có ý nghĩa khi vật phẩm của nó bắt đầu được giao dịch.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: skin anh hùng một lần "không quay lại" sau 1/10',
  'desc': 'Sự kiện WWE: Search for Cena của Supercell (tháng 9/2026) bán sáu skin anh hùng WWE mà Supercell nói sẽ không quay lại sau 1/10, cùng cảnh quan Money in the Bank.',
  'lead': 'Supercell công bố sự kiện WWE: Search for Cena cho Clash of Clans ngày 01/09/2026; sự kiện kéo dài cả tháng 9.',
  'new': ['Skin anh hùng giá 9,99 USD: Cody Rhodes (Vua Barbarian), Alexa Bliss (Nữ hoàng Cung thủ), Iyo Sky (Nhà vô địch Hoàng gia), Kane (Công tước Rồng) và American Badass Undertaker (Đại Hộ vệ).',
          'Jey Uso (Hoàng tử Minion) đi kèm Gold Pass.',
          'Supercell cho biết các skin "sẽ không quay lại. Không bao giờ" sau 1/10.',
          'Cảnh quan XL Money in the Bank có từ 2 đến 30/9, cùng thử thách John Cena và quân WWE tạm thời.'],
  'impact': 'Những skin mà nhà phát hành khẳng định không bao giờ quay lại chính là loại vật phẩm trang trí khiến tài khoản Clash of Clans hiếm hơn. Dù vậy, cấp Nhà Chính và anh hùng vẫn chiếm phần lớn giá trị.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: cái nhìn đầu tiên về thể thức hai split mới',
  'desc': 'Cái nhìn đầu tiên của Supercell về BSC 2027 (24/08/2026): tám đội mỗi khu vực ở bốn khu vực, Challengers ở 12 khu vực, hai split 12 tuần, Brawl Cup và Chung kết Thế giới.',
  'lead': 'Supercell giới thiệu cái nhìn đầu tiên về Brawl Stars Championship 2027 ngày 24/08/2026, lưu ý chi tiết vẫn có thể thay đổi.',
  'new': ['Cấp cao nhất: 8 đội mỗi khu vực ở Đông Á, EMEA, Nam Mỹ và Bắc Mỹ.',
          'Challengers: con đường vào chuyên nghiệp ở 12 khu vực.',
          'Hai split, mỗi split 12 tuần; split 1 kết thúc bằng Brawl Cup — giải LAN quốc tế ba ngày — và split 2 bằng Chung kết Thế giới.',
          'Ngày thi đấu, tiền thưởng và địa điểm chưa được công bố.'],
  'impact': 'Thể thức esports không thay đổi giá trị tài khoản hiện có; máy tính Brawl Stars của chúng tôi vẫn dùng số tay đấu, Hypercharge và cúp.'},
}},
'hi': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II रिलीज़: Sift डाइमेंशन और Illager High Council',
  'desc': 'Mojang ने 29 सितंबर 2026 को Minecraft Dungeons II को Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch और Switch 2 पर रिलीज़ किया, 4 खिलाड़ियों तक को-ऑप के साथ।',
  'lead': 'Mojang Studios ने 29 सितंबर 2026 को Minecraft Dungeons II रिलीज़ किया।',
  'new': ['Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch और Nintendo Switch 2 पर उपलब्ध।',
          'कहानी में खिलाड़ियों का मुक़ाबला Illager High Council से है: Prime Enchanter, Supreme Evoker और Grand Illusioner।',
          'खिलाड़ी नया डाइमेंशन Sift एक्सप्लोर करते हैं; Mojang के मुताबिक यह अगले साल Minecraft Java और Bedrock में भी आएगा।',
          'अकेले या 4 खिलाड़ियों तक के को-ऑप में, ऑनलाइन या एक ही स्क्रीन पर खेल सकते हैं।'],
  'impact': 'Dungeons II एक अलग गेम है। Minecraft Java और Bedrock अकाउंट अब भी प्रकार, यूज़रनेम और केप से आँके जाते हैं, इसलिए यह रिलीज़ उनकी कीमत नहीं बदलती।'},
 'cr-mt-oct': {'title': 'Clash Royale Merge Tactics: Supers, एलिक्सिर और बैज में अक्टूबर के बदलाव',
  'desc': '1 अक्टूबर 2026 से Merge Tactics सीज़न 11 में Supers साझा पूल में जाते हैं, हर राउंड का एलिक्सिर 5 से 4 होता है और लेवल 5 स्किन आती हैं; बैज के नियम सीज़न 12 में बदलेंगे।',
  'lead': 'Supercell ने 30 सितंबर 2026 को Merge Tactics सीज़न 11 के अक्टूबर बदलावों की घोषणा की; ये 1 अक्टूबर से लागू हैं।',
  'new': ['Supers अब शुरुआती ट्रूप नहीं मिलते: वे साझा पूल में जाते हैं, जिसके लिए सभी खिलाड़ी मुक़ाबला करते हैं।',
          'हर राउंड में मिलने वाला एलिक्सिर 5 से वापस 4 हो गया।',
          'Battle Machine और Dagger Duchess को अपग्रेड कर चुके खिलाड़ियों के लिए लेवल 5 स्किन।',
          'सीज़न 12 से सिल्वर बैज के लिए Diamond League और गोल्ड बैज के लिए टॉप 10,000 में आना ज़रूरी।'],
  'impact': 'सीज़न 12 से ऊँची रैंक वाले बैज पाना कठिन होगा, इसलिए Clash Royale प्रोफ़ाइल पर वे कौशल को ज़्यादा साफ़ दिखाएँगे। King Tower और कार्ड लेवल ही मुख्य कीमत कारक बने रहते हैं।'},
 'ml-mplph': {'title': 'MPL फ़िलीपींस सीज़न 18 प्लेऑफ़: PhilSports Arena, 21–25 अक्टूबर',
  'desc': 'MOONTON ने 26 सितंबर 2026 को बताया कि MPL फ़िलीपींस सीज़न 18 प्लेऑफ़ 21–25 अक्टूबर को PhilSports Arena में होंगे और M8 के लिए फ़िलीपींस की टीमें तय करेंगे।',
  'lead': 'MOONTON Games ने 26 सितंबर 2026 को MPL फ़िलीपींस सीज़न 18 प्लेऑफ़ की जगह और तारीख़ें घोषित कीं।',
  'new': ['प्लेऑफ़ 21 से 25 अक्टूबर 2026 तक पासिग शहर के PhilSports Arena में होंगे।',
          'इनसे तय होगा कि जनवरी 2027 में इस्तांबुल में होने वाली M8 वर्ल्ड चैंपियनशिप में फ़िलीपींस का प्रतिनिधित्व कौन करेगा।',
          'टिकट बिक्री 26 सितंबर को शुरू हुई, कीमत 200 फ़िलीपीनी पेसो से।',
          'घोषणा गेम की 10वीं सालगिरह पर है: 1.5 अरब इंस्टॉल और हर महीने 11 करोड़ सक्रिय खिलाड़ी।'],
  'impact': 'ई-स्पोर्ट्स इवेंट मौजूदा अकाउंट की कीमत नहीं बदलते। हमारी रिसर्च में Mobile Legends की कीमत स्किन, हीरो और प्रोग्रेस से तय होती है।'},
 'cr-bal-sep': {'title': 'Clash Royale सितंबर बैलेंस: Hero Ice Wizard और Minion Giant कमज़ोर हुए',
  'desc': 'Supercell के सितंबर 2026 बैलेंस नोट्स Hero Ice Wizard का फ़्रीज़ 7 से 5 सेकंड और Minion Giant का डैमेज 189 से 168 करते हैं, साथ ही Hero Mega Minion और Hero Wizard को रीवर्क करते हैं।',
  'lead': 'Supercell ने Clash Royale के बैलेंस बदलावों के दो दौर जारी किए, जो 8 और 16 सितंबर 2026 को लागू हुए।',
  'new': ['16 सितंबर: Hero Ice Wizard फ़्रीज़ 7 से → 5 से; Goblinstein एबिलिटी 4 से → 3.5 से; Minion Giant डैमेज 189 → 168; Fire Spirit डैमेज 207 → 215।',
          '8 सितंबर: Freeze 4 से → 3.5 से; Fireball का टावर डैमेज 172 → 159; Ice Golem हिटपॉइंट्स 1,315 → 1,228।',
          'रीवर्क: Hero Mega Minion (टेलीपोर्ट से वापस, डैमेज 399 → 422) और Hero Wizard (एबिलिटी 5 से → 3.5 से); Wizard डैमेज 281 → 304।',
          'Ronin, Spirit Empress और Goblin Cage समेत कुछ कार्ड मज़बूत किए गए।'],
  'impact': 'बैलेंस बदलाव यह बदलते हैं कि कौन से कार्ड लोकप्रिय हैं, अकाउंट में क्या है यह नहीं। हमारी रिसर्च में Clash Royale की कीमत King Tower लेवल, कार्ड लेवल, इवोल्यूशन और दुर्लभ कॉस्मेटिक्स से तय होती है।'},
 'gi-wish71': {'title': 'Genshin Impact 7.1 इवेंट विश: Vesna और Vodyanitsa के बैनर 13 अक्टूबर तक',
  'desc': 'HoYoverse के वर्ज़न 7.1 फ़ेज़ I इवेंट विश 13 अक्टूबर 2026 तक Vesna और Vodyanitsa का ड्रॉप रेट बढ़ाते हैं; बूस्टेड 4-स्टार हैं Diona, Faruzan और Chongyun।',
  'lead': 'HoYoverse ने 21 सितंबर 2026 को वर्ज़न 7.1 फ़ेज़ I इवेंट विश जारी किए; ये 13 अक्टूबर 2026, 17:59 तक चलेंगे।',
  'new': ['"When Warm Winds Cavort" में Vesna (Anemo) का ड्रॉप रेट बढ़ा है।',
          '"Surging Ballad" में Vodyanitsa (Hydro) का ड्रॉप रेट बढ़ा है।',
          'बूस्टेड 4-स्टार कैरेक्टर: Diona (Cryo), Faruzan (Anemo) और Chongyun (Cryo)।',
          'इवेंट-एक्सक्लूसिव कैरेक्टर स्टैंडर्ड विश में नहीं हैं; दोनों कैरेक्टर बैनर एक ही पिटी काउंटर साझा करते हैं।'],
  'impact': 'हमारी रिसर्च में सिर्फ़ लिमिटेड बैनर से मिलने वाले कैरेक्टर और उनके कॉन्स्टेलेशन Genshin अकाउंट की कीमत के मुख्य कारकों में से हैं।'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Trash Goblin Darryl स्किन और 30 सितंबर तक रिवॉर्ड',
  'desc': 'Supercell का Brawl Stars × Duolingo इवेंट (19 सितंबर 2026 को घोषित) 30 सितंबर तक Trash Goblin Darryl स्किन, जेम्स, Starr Drops और बहुत कुछ देता रहा।',
  'lead': 'Supercell ने 19 सितंबर 2026 को Brawl Stars × Duolingo क्रॉसओवर की घोषणा की; यह 30 सितंबर तक चला।',
  'new': ['कम्युनिटी लक्ष्यों और इन-गेम टास्क के दो चरण, साथ में नया Duo Boss Fight मोड।',
          'रिवॉर्ड: Trash Goblin Darryl स्किन, 20 जेम्स, 5 Chaos Drops, 3 Mythic Starr Drops, 2,000 कॉइन्स, 2,500 Bling और 1,000 क्रेडिट्स।',
          'Duolingo ऐप में Brawl Stars क्वेस्ट से अतिरिक्त कॉस्मेटिक्स मिले।',
          'Supercell ने सोशल मीडिया पर 3.141592 मिलियन जेम्स का क्विज़ गिवअवे भी किया।'],
  'impact': 'एक बार के क्रॉसओवर की स्किन कुछ Brawl Stars कलेक्शन को अलग बनाती हैं; जो स्किन बहुत लोगों को मुफ़्त मिली, वह दुर्लभ पेड स्किन से कम जोड़ती है।'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN की वापसी: Nine Tails और Hinata बंडल (16 सितंबर – 15 अक्टूबर)',
  'desc': 'Garena का NARUTO SHIPPUDEN सहयोग 16 सितंबर से 15 अक्टूबर 2026 तक चलता है — Sharingan: Control स्किल, Jiraiya या Hinata में से एक बंडल और थीम वाले कॉस्मेटिक्स के साथ।',
  'lead': 'Garena ने 15 सितंबर 2026 को घोषणा की कि Free Fire × NARUTO SHIPPUDEN सहयोग 16 सितंबर से 15 अक्टूबर तक लौट रहा है।',
  'new': ['नई स्किल्स: Nine Tails को नियंत्रित करने वाली Sharingan: Control, और 8 Trigrams Palm Rotation।',
          'Hidden Leaf Village मैप में बड़ी की गई Ninja Academy।',
          'चुनने वाला बड़ा इनाम: Jiraiya बंडल या Hinata बंडल (Hinata की पहली एंट्री)।',
          'कॉस्मेटिक्स: Tsunade का Cloak, Gaara का Tattoo Facepaint, Kakashi का ANBU मास्क और Froggy Wallet क्रेट।'],
  'impact': 'सीमित समय के लिए मिलने वाले लाइसेंस वाले सहयोग के बंडल उन दुर्लभ आइटम में हैं जिन्हें हमारा Free Fire कैलकुलेटर ढूँढता है।'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship सीज़न 8 शुरू, इस्तांबुल में M8 की ओर',
  'desc': 'MTC सीज़न 8 12 सितंबर से 18 अक्टूबर 2026 तक आठ टीमों और 40,000 डॉलर के प्राइज़ पूल के साथ चलेगा; उसके बाद जनवरी 2027 में इस्तांबुल में M8 वर्ल्ड चैंपियनशिप।',
  'lead': 'MOONTON Games ने 10 सितंबर 2026 को घोषणा की कि MLBB Türkiye Championship सीज़न 8 12 सितंबर से शुरू होगा।',
  'new': ['रेगुलर सीज़न 12 सितंबर से 18 अक्टूबर तक; ग्रैंड फ़ाइनल 7 नवंबर 2026 को।',
          'आठ टीमें हिस्सा ले रही हैं, जिनमें Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok और Dark Passage शामिल हैं।',
          'शीर्ष छह टीमें प्लेऑफ़ में जाकर 40,000 डॉलर के प्राइज़ पूल के लिए खेलेंगी।',
          'M8 वर्ल्ड चैंपियनशिप जनवरी 2027 में इस्तांबुल में होगी — यूरोप में M सीरीज़ का पहला इवेंट।'],
  'impact': 'ई-स्पोर्ट्स के नतीजे मौजूदा अकाउंट की कीमत नहीं बदलते; हमारी रिसर्च में Collector और Legend स्किन और हीरो की संख्या ही मुख्य कारक हैं।'},
 'coc-blast': {'title': 'Clash of Clans Equipment Blast मेडल इवेंट (9–22 सितंबर)',
  'desc': 'Equipment Blast इवेंट 9 से 22 सितंबर 2026 तक चला: Tag Tickets और Champ Medals कमाकर Trader से हीरो इक्विपमेंट, ओर और कॉस्मेटिक्स ले सकते थे। Town Hall 6+।',
  'lead': 'Supercell ने 9 सितंबर 2026 को Equipment Blast मेडल इवेंट की घोषणा की; यह 22 सितंबर 08:00 UTC तक चला और Trader 24 सितंबर तक खुला रहा।',
  'new': ['मल्टीप्लेयर बैटल से Tag Tickets मिले; इवेंट ट्रैक से Champ Medals, अस्थायी ट्रूप्स और चेस्ट।',
          'Trader में इवेंट मेडल से हीरो इक्विपमेंट, ओर और कॉस्मेटिक्स मिले।',
          'अस्थायी ट्रूप्स: Undertaker Yeti, K.A.N.E., Yeeter और Giant Giant।',
          'Town Hall 6 से उपलब्ध।'],
  'impact': 'हीरो इक्विपमेंट और उसके लेवल हीरो की ताक़त का हिस्सा हैं, जो हमारी रिसर्च में Clash of Clans अकाउंट की कीमत तय करती है; इवेंट मेडल उसे अपग्रेड करने का एक और तरीका हैं।'},
 'mc-wild': {'title': 'Minecraft का Wilderness Bound अपडेट: dappled forest, भूसे के बिस्तर और वीरान कैंप',
  'desc': 'Mojang का Wilderness Bound अपडेट 15 सितंबर 2026 को आया — dappled forest बायोम, पॉपलर लकड़ी, भूसे के बिस्तर, वीरान कैंप और कुशन के साथ।',
  'lead': 'Mojang Studios ने 5 सितंबर को 2026 के तीसरे गेम ड्रॉप का नाम "Wilderness Bound" रखा और 15 सितंबर को इसे जारी किया।',
  'new': ['नया बायोम dappled forest, ऊँचे पॉपलर पेड़ों और शेल्फ़ मशरूम के साथ।',
          'तीन घास की गठरियों से बने भूसे के बिस्तर से स्पॉन पॉइंट बदले बिना रात छोड़ी जा सकती है।',
          'एक्सप्लोर करने के लिए वीरान कैंप, और एक ही रंग की तीन ऊन स्लैब से बने कुशन।',
          'पॉपलर लकड़ी और बिल्डिंग के लिए बढ़ाए गए कंक्रीट और ऊन सेट।'],
  'impact': 'Minecraft अकाउंट की कीमत प्रकार, यूज़रनेम और केप से तय होती है, गेम कंटेंट से नहीं, इसलिए गेम ड्रॉप अकाउंट की कीमत नहीं बदलता।'},
 'ff-award': {'title': 'Free Fire ने Pocket Gamer Mobile Games Awards 2026 में "Best Use of IP or Licence" जीता',
  'desc': 'Garena ने 3 सितंबर 2026 को बताया कि Free Fire ने NARUTO SHIPPUDEN सहयोग के लिए Pocket Gamer Mobile Games Awards 2026 में Best Use of IP or Licence जीता।',
  'lead': 'Garena ने 3 सितंबर 2026 को घोषणा की कि Free Fire ने Pocket Gamer Mobile Games Awards 2026 में "Best Use of IP or Licence" पुरस्कार जीता।',
  'new': ['यह पुरस्कार NARUTO SHIPPUDEN Chapter 2: Ninja War सहयोग के लिए है।',
          'Garena के अनुसार बैंकॉक में Ninja Clash All Stars इवेंट में लगभग 5,000 लोग आए और 24.7 करोड़ से ज़्यादा वीडियो व्यूज़ मिले।',
          'सहयोग में थीम वाले कैरेक्टर, जुत्सु एबिलिटी और बदला हुआ Hidden Leaf Village मैप शामिल था।',
          'पेरू, बांग्लादेश, मलेशिया और ताइवान में कम्युनिटी इवेंट हुए।'],
  'impact': 'पुरस्कार से अकाउंट की कीमत नहीं बदलती, लेकिन यह पुष्टि करता है कि लाइसेंस वाले सहयोग Free Fire का नियमित हिस्सा हैं — और उनके सीमित बंडल उन दुर्लभ आइटम में हैं जिन्हें मूल्यांकन देखता है।'},
 'rbx-fall': {'title': 'Roblox फ़ॉल गेम्स प्रीव्यू: सितंबर और अक्टूबर में आने वाले 10 एक्सपीरियंस',
  'desc': 'Roblox का फ़ॉल गेम्स प्रीव्यू (2 सितंबर 2026) 10 नए एक्सपीरियंस बताता है — सितंबर में Showdown और Nemesis से लेकर अक्टूबर में Prime Heroes, Octane और Starforged तक।',
  'lead': 'Roblox ने 2 सितंबर 2026 को फ़ॉल गेम्स प्रीव्यू जारी किया, जिसमें सितंबर और अक्टूबर में आने वाले दस एक्सपीरियंस हैं।',
  'new': ['सितंबर: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force और Caramel।',
          'अक्टूबर: Prime Heroes (सितंबर में 6 हीरो के साथ अर्ली एक्सेस), Octane, Starforged और Scrapbook Saga।',
          'कई गेम Roblox के Jumpstart और Incubator क्रिएटर प्रोग्राम से आए हैं।',
          'शैलियाँ शूटर और रेसिंग से लेकर सर्वाइवल हॉरर और फ़ार्मिंग तक।'],
  'impact': 'नए एक्सपीरियंस मौजूदा अकाउंट नहीं बदलते। हमारी रिसर्च में Roblox अकाउंट की कीमत Robux, लिमिटेड आइटम और पुराने एक्सपीरियंस के आइटम से आती है; नया गेम तभी मायने रखता है जब उसके आइटम ट्रेड होने लगें।'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: एक बार की हीरो स्किन जो 1 अक्टूबर के बाद "वापस नहीं आएँगी"',
  'desc': 'Supercell के WWE: Search for Cena इवेंट (सितंबर 2026) में छह WWE हीरो स्किन बिकीं, जो Supercell के अनुसार 1 अक्टूबर के बाद वापस नहीं आएँगी, साथ में Money in the Bank सीनरी।',
  'lead': 'Supercell ने 1 सितंबर 2026 को Clash of Clans के लिए WWE: Search for Cena इवेंट की घोषणा की; यह पूरे सितंबर चला।',
  'new': ['$9.99 वाली हीरो स्किन: Cody Rhodes (Barbarian King), Alexa Bliss (Archer Queen), Iyo Sky (Royal Champion), Kane (Dragon Duke) और American Badass Undertaker (Grand Warden)।',
          'Jey Uso (Minion Prince) Gold Pass के साथ मिला।',
          'Supercell कहता है कि 1 अक्टूबर के बाद ये स्किन "वापस नहीं आएँगी। कभी नहीं"।',
          'Money in the Bank XL सीनरी 2 से 30 सितंबर तक उपलब्ध थी, साथ में John Cena चैलेंज और अस्थायी WWE ट्रूप्स।'],
  'impact': 'जिन स्किन के बारे में पब्लिशर कहता है कि वे कभी वापस नहीं आएँगी, वही कॉस्मेटिक्स Clash of Clans अकाउंट को दुर्लभ बनाते हैं। फिर भी कीमत का बड़ा हिस्सा Town Hall और हीरो लेवल से आता है।'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: दो स्प्लिट वाले नए फ़ॉर्मेट की पहली झलक',
  'desc': 'Supercell की BSC 2027 की पहली झलक (24 अगस्त 2026): चार क्षेत्रों में हर क्षेत्र में आठ टीमें, 12 क्षेत्रों में Challengers, 12-12 हफ़्ते के दो स्प्लिट, Brawl Cup और वर्ल्ड फ़ाइनल्स।',
  'lead': 'Supercell ने 24 अगस्त 2026 को 2027 Brawl Stars Championship की पहली झलक दी और कहा कि विवरण बदल सकते हैं।',
  'new': ['टॉप लेवल: पूर्वी एशिया, EMEA, दक्षिण अमेरिका और उत्तरी अमेरिका में हर क्षेत्र में 8 टीमें।',
          'Challengers: 12 क्षेत्रों में प्रोफ़ेशनल बनने का रास्ता।',
          '12-12 हफ़्ते के दो स्प्लिट; स्प्लिट 1 तीन दिन के अंतरराष्ट्रीय LAN Brawl Cup पर और स्प्लिट 2 वर्ल्ड फ़ाइनल्स पर ख़त्म होता है।',
          'तारीख़ें, प्राइज़ पूल और जगहें अभी घोषित नहीं हुई हैं।'],
  'impact': 'ई-स्पोर्ट्स फ़ॉर्मेट मौजूदा अकाउंट की कीमत नहीं बदलते; हमारा Brawl Stars कैलकुलेटर अब भी ब्रॉलर की संख्या, Hypercharge और ट्रॉफ़ी देखता है।'},
}},
}
