# News translations: it, pl (from news_data.py 'en', facts unchanged)
TEXT = {
'it': {
 'ui': {
  'news': 'Notizie', 'news_title': 'Notizie sui giochi che influiscono sul valore di un account',
  'news_lead': 'Aggiornamenti ufficiali degli editori: ognuno verificato sull’annuncio dell’editore stesso, con una nota chiara su cosa significa per il valore di un account.',
  'game_title': 'Notizie su {game}', 'game_lead': 'Gli aggiornamenti ufficiali di {game} che influiscono sul valore di un account. Ogni articolo rimanda all’annuncio dell’editore.',
  'published': 'Pubblicato il', 'source': 'Fonte ufficiale', 'by_on': '{pub}, {date}', 'whats_new': 'Le novità',
  'impact': 'Cosa significa per il valore dell’account', 'more': 'Altre notizie su {game}', 'all': 'Tutte le notizie',
  'calc': '{game}: calcolatore di valore e report di mercato', 'read': 'Leggi', 'latest': 'Ultime notizie su {game}',
  'note': 'GameAccountValue non compra, non vende e non fa da intermediario per account. Le notizie riassumono gli annunci degli editori solo a scopo informativo.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: arrivano Vesna e Vodyanitsa, confermate le ricompense dell’anniversario',
   'desc': 'La versione 7.1, «A Rekviem for the Underworld», è uscita il 23 settembre 2026 con due nuovi personaggi a 5 stelle, due armi a 5 stelle e le ricompense del sesto anniversario.',
   'lead': 'HoYoverse ha pubblicato la versione 7.1, «A Rekviem for the Underworld», il 23 settembre 2026: l’aggiornamento porta anche il sesto anniversario di Genshin Impact.',
   'new': ['Due nuovi personaggi a 5 stelle: Vesna (Anemo, spada) e Vodyanitsa (Hydro, catalizzatore).',
           'Nuove armi: Beyond the Chrysalis (spada 5★), Hymn of the Maelstrom (catalizzatore 5★) e New Bough (spada 4★).',
           'Ricompense dell’anniversario annunciate da HoYoverse: due personaggi a 5 stelle da invitare, Destino intrecciato ×10, Protogemme ×1.600 e il ripristino del bonus della prima ricarica dei Cristalli della genesi.',
           'La manutenzione dell’aggiornamento è iniziata il 23 settembre alle 06:00 (UTC+8).'],
   'impact': 'Secondo la nostra ricerca, il numero di personaggi a 5 stelle limitati, le loro costellazioni e le armi distintive sono tra i principali fattori di valore di un account Genshin. I personaggi regalati a tutti per l’anniversario rendono un account meno distintivo di quelli dei banner limitati.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, la prima nuova dimensione da oltre 14 anni, arriva su Java e Bedrock',
   'desc': 'Minecraft Live del 26 settembre 2026 ha svelato The Sift, una quarta dimensione in arrivo su Java e Bedrock l’anno prossimo, oltre a Dungeons II e all’aggiornamento Wilderness Bound.',
   'lead': 'Al Minecraft Live del 26 settembre 2026 Mojang Studios ha annunciato che la quarta dimensione del gioco, The Sift, arriverà su Minecraft Java e Bedrock Edition l’anno prossimo.',
   'new': ['The Sift è la prima nuova dimensione da oltre 14 anni e si aggiunge a Sopramondo, Nether ed End.',
           'Debutta in Minecraft Dungeons II, che Mojang ha fissato per il 29 settembre 2026.',
           'Minecraft World, un’attrazione a tema, aprirà a Londra nel 2027.',
           'L’aggiornamento Wilderness Bound è arrivato il 15 settembre con la foresta screziata, i letti di paglia, gli accampamenti abbandonati e i cuscini.'],
   'impact': 'Gli account Minecraft si valutano per tipo (Java o Bedrock), nome utente e mantelli, non per i contenuti di gioco. Aggiornamenti come questi cambiano cosa si può fare nel gioco, non quanto vale un account.'},
  'rbx-hunt': {
   'title': 'Roblox 20 «The Hunt»: oggetti UGC limitati ed esclusive Roblox Plus (17–28 settembre)',
   'desc': 'The Hunt: Roblox 20 si è svolto dal 17 al 28 settembre 2026 con ricompense UGC, oggetti UGC a edizione limitata e tre oggetti esclusivi per gli abbonati Roblox Plus.',
   'lead': 'Roblox ha festeggiato i 20 anni con The Hunt: Roblox 20, un evento su tutta la piattaforma dal 17 al 28 settembre 2026.',
   'new': ['I giocatori attraversavano 20 anni di storia di Roblox, una missione per anno, partendo da «Year Zero»; completarli tutti sbloccava «Year Infinity» con altri 20 giochi.',
           'Le missioni davano oggetti UGC e durante l’evento erano disponibili oggetti UGC a edizione limitata.',
           'Gli abbonati Roblox Plus hanno ricevuto tre oggetti virtuali esclusivi e mantengono il tema Classic dell’app, lo sfondo avatar classico e la cornice del profilo dopo l’evento.',
           'Il tema Classic dell’app è stato gratuito per tutti durante l’evento.'],
   'impact': 'Gli oggetti ottenibili solo durante un evento sono tra gli elementi che una valutazione considera. Roblox non ha nominato questi oggetti nell’annuncio, quindi questo sito non assegna loro un prezzo finché non esistono annunci di vendita reali.'},
  'rbx-rdc': {
   'title': 'RDC 2026: i creator di Roblox hanno guadagnato circa 1,7 miliardi di dollari in un anno; annunciato Roblox Wallet',
   'desc': 'Alla RDC 2026 Roblox ha comunicato circa 1,7 miliardi di dollari di guadagni dei creator in 12 mesi e ha annunciato Roblox Wallet e Roblox Card per i pagamenti.',
   'lead': 'Alla sua conferenza per sviluppatori RDC 2026 (annuncio dell’11 settembre 2026) Roblox ha condiviso i dati sui guadagni dei creator e nuovi strumenti di pagamento.',
   'new': ['I creator hanno guadagnato oltre 5 miliardi di dollari dal lancio di DevEx nel 2013 e circa 1,7 miliardi nei 12 mesi fino al 30 giugno 2026.',
           'Gli incentivi Roblox Plus hanno generato oltre 300 milioni di Robux di guadagni per i creator nei primi quattro mesi (fino al 17 agosto 2026).',
           'Roblox Wallet, un conto di pagamento gestito con Airwallex US, offrirà pagamenti giornalieri in valuta reale: prima, a fine 2026, per i creator indipendenti statunitensi idonei dai 18 anni in su, poi a livello internazionale nel 2027.',
           'Una Roblox Card collegata al Wallet è prevista dal 2027.'],
   'impact': 'Queste novità riguardano i pagamenti ai creator, non gli account dei giocatori: l’annuncio non ha cambiato i prezzi dei Robux, gli oggetti limitati né gli scambi. Saldo di Robux e oggetti limitati restano ciò che pesa il nostro calcolatore Roblox.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: quattro nuove armi in Clash Squad, Prime Diamond e rework di Kenta',
   'desc': 'Le note della patch OB55 di Garena (10 settembre 2026) aggiungono M7, Skorp, RPK e Hawk a Clash Squad dal 1º ottobre, introducono Prime Diamond e rielaborano Kenta.',
   'lead': 'Garena ha pubblicato le note della patch OB55 di Free Fire il 10 settembre 2026; le modifiche alle armi entrano in vigore il 1º ottobre.',
   'new': ['Nuove armi Clash Squad dal 1º ottobre: M7 (1.600 CS Cash), Skorp (1.500), RPK (1.500) e Hawk (1.700).',
           'Prime Diamond: diamanti ottenuti in base alla spesa mensile, riscattabili il mese successivo dopo una qualsiasi ricarica.',
           'Kenta viene completamente rielaborato; Morse, Luna e Wukong ricevono modifiche di bilanciamento.',
           'Dal 1º ottobre cambia la mobilità per classe d’arma: mitragliette più veloci, fucili di precisione e da tiratore scelto più lenti.'],
   'impact': 'Il nostro calcolatore Free Fire pesa il saldo di diamanti e i bundle rari. OB55 cambia il modo in cui vengono premiate le ricariche future; non cambia gli oggetti già presenti negli account.'},
  'cr-minion': {
   'title': 'Clash Royale, stagione «Minion Academy»: nuova carta Sgherro gigante ed eroe Stregone di ghiaccio',
   'desc': 'La stagione Minion Academy (7 settembre – 5 ottobre 2026) aggiunge la carta Sgherro gigante (Minion Giant), l’eroe Stregone di ghiaccio e un evento album con 1.750 carte.',
   'lead': 'Supercell ha aperto la stagione «Minion Academy» di Clash Royale, in corso dal 7 settembre al 5 ottobre 2026.',
   'new': ['Nuova carta Sgherro gigante (Minion Giant): una condizione di vittoria volante che punta edifici e torri. È gratuita tramite l’evento album Academy Antics e non comparirà nei bauli fino alla prossima stagione.',
           'L’evento album dà 1.750 carte Sgherro gigante, un’emote e una skin per la torre.',
           'Nuovo eroe: Stregone di ghiaccio, dal percorso del Pass Royale o per 200 monete eroe.',
           'Eventi: lega 2c2 (7–21 settembre), torneo globale Princess Gambit (21–26 settembre) e Royale Shuffle (21 settembre – 5 ottobre). Un pareggio in Campione supremo ora costa metà dei trofei di una sconfitta.'],
   'impact': 'Le skin delle torri e le emote offerte solo durante un evento rendono più distintiva una collezione di Clash Royale, ma il livello della Torre del Re e i livelli delle carte restano i principali fattori di valore.'},
  'ml-10': {
   'title': 'Mobile Legends compie 10 anni: campagna ALL IN e nuova skin Collector di Layla',
   'desc': 'La campagna ALL IN di MOONTON per i 10 anni (dal 4 settembre 2026) porta una nuova skin Epica di Nana, forzieri di skin gratuiti e una skin Collector di Layla dal 9 ottobre.',
   'lead': 'Il 4 settembre 2026 MOONTON Games ha lanciato ALL IN, la campagna per il decimo anniversario di Mobile Legends: Bang Bang.',
   'new': ['Pass celebrativo del 10º anniversario (4 settembre – 1º novembre): nuova skin Epica di Nana, forziere di selezione skin Epica, forziere skin Epica casuale e una skin anniversario gratuita per chi torna a giocare.',
           'Anniversary Gala Weekend (25 settembre – 11 ottobre): accesso a 265 skin, EXP del Battle Pass e frammenti di skin premium.',
           'Layla’s Stellar Gala (9 ottobre – 19 novembre): la nuova skin Collector di Layla tramite il minigioco «Starfall Breakout».',
           'MOONTON cita oltre 1,5 miliardi di installazioni e 110 milioni di giocatori attivi al mese.'],
   'impact': 'Le skin Collector e Legend sono tra i fattori di valore più citati per gli account Mobile Legends; le skin regalate o in prova no.'},
  'bs-aug': {
   'title': 'Brawl Stars: i brawler mitici Cosmo e Vince; il Percorso di Starr diventa Brawler Blast',
   'desc': 'Le note di aggiornamento di agosto 2026 di Supercell (1º settembre) aggiungono due brawler mitici, trasformano il Percorso di Starr in Brawler Blast con nuovi costi in crediti e rinominano Ultra leggendario in Ultra.',
   'lead': 'Supercell ha pubblicato le note dell’aggiornamento di agosto 2026 di Brawl Stars il 1º settembre 2026.',
   'new': ['Due nuovi brawler mitici: Cosmo (controllo) e Vince (danni).',
           'Nuove Ipercariche per Nori e Wendy.',
           'Il Percorso di Starr diventa «Brawler Blast»: i crediti ora servono a sbloccare per rarità — Raro 160, Super raro 430, Epico 925, Mitico 1.900, Leggendario 3.800, Ultra 5.500.',
           'La rarità «Ultra leggendario» si chiama ora «Ultra». In più la stagione Royal Academy e un evento Brawl-O-Ween per tutto il mese.'],
   'impact': 'Il nostro calcolatore Brawl Stars usa il numero di brawler, le Ipercariche e i trofei. Due mitici in più aumentano il numero di brawler richiesti da una collezione completa.'},
  'coc-aug': {
   'title': 'Clash of Clans, aggiornamento di agosto: Diggy livelli 11–15 e Pass d’oro dal Municipio 3',
   'desc': 'L’aggiornamento di agosto 2026 di Supercell (30 agosto) aggiunge i livelli 11–15 di Diggy e nuove supercariche al Municipio 18, ritira lo Starter Pass e apre il Pass d’oro dal Municipio 3.',
   'lead': 'Supercell ha pubblicato l’aggiornamento di agosto di Clash of Clans il 30 agosto 2026.',
   'new': ['Municipio 18: il compagno Diggy ottiene i livelli 11–15; la Capanna del costruttore e il Monolito ottengono nuovi livelli di supercarica.',
           'Lo Starter Pass viene ritirato: le sfide stagionali e il Pass d’oro sono disponibili dal Municipio 3, con ricompense in base al livello del municipio.',
           'Il Cavaliere delle rovine non perde più vita nel tempo; la Strega delle rovine evoca 10 cavalieri invece di 8.',
           'Sono stati modificati i modificatori della Lega delle guerre tra clan nelle leghe Titano.'],
   'impact': 'Secondo la nostra ricerca, il livello del municipio e i livelli di eroi e compagni determinano il valore degli account Clash of Clans. I nuovi livelli massimi al Municipio 18 fanno sì che un account «maxato» richieda ora più potenziamenti di prima.'},
  'fn-c7s4': {
   'title': 'Fortnite Capitolo 7 Stagione 4 «Override»: Pass battaglia di Sonic e crossover con KINGDOM HEARTS',
   'desc': 'La stagione «Override» di Epic (Capitolo 7, Stagione 4) porta le Console Override, un Pass battaglia da 800 V-buck guidato da Sonic the Hedgehog e crossover come KINGDOM HEARTS.',
   'lead': 'La Stagione 4 del Capitolo 7 di Fortnite si chiama «Override». Epic la descrive come una stagione di crossover videoludici e regole che cambiano per l’intera partita.',
   'new': ['Le Console Override compaiono in ogni partita e permettono ai giocatori di cambiare le regole per tutto il server.',
           'Il Pass battaglia costa 800 V-buck ed è guidato da Sonic the Hedgehog, affiancato da Tails come spalla.',
           'Chi ha acquistato il Pass entro il 27 agosto alle 23:59 (ora della costa est degli USA) ha ricevuto il costume Infiltrator Grace Crowne come bonus della settimana di lancio.',
           'Crossover della stagione: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot e Spyro the Dragon; tra le armi, Midas’ Masterpiece e il Mega Buster di Mega Man.'],
   'impact': 'I costumi disponibili solo per un periodo limitato, come un bonus di lancio, sono ciò che distingue un armadietto Fortnite raro da uno comune. I costumi del Pass battaglia restano legati alla loro stagione.'},
 }},
'pl': {
 'ui': {
  'news': 'Aktualności', 'news_title': 'Wiadomości ze świata gier, które wpływają na wartość konta',
  'news_lead': 'Oficjalne aktualizacje od wydawców gier — każda sprawdzona w ogłoszeniu samego wydawcy, z krótką notą, co oznacza dla wartości konta.',
  'game_title': 'Aktualności: {game}', 'game_lead': 'Oficjalne aktualizacje {game}, które wpływają na wartość konta. Każdy artykuł linkuje do ogłoszenia wydawcy.',
  'published': 'Opublikowano', 'source': 'Oficjalne źródło', 'by_on': '{pub}, {date}', 'whats_new': 'Co nowego',
  'impact': 'Co to oznacza dla wartości konta', 'more': 'Więcej aktualności: {game}', 'all': 'Wszystkie aktualności',
  'calc': '{game}: kalkulator wartości i raport rynkowy', 'read': 'Czytaj', 'latest': 'Najnowsze wiadomości: {game}',
  'note': 'GameAccountValue nie kupuje, nie sprzedaje i nie pośredniczy w obrocie kontami. Wiadomości streszczają ogłoszenia wydawców wyłącznie w celach informacyjnych.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna i Vodyanitsa już są, nagrody rocznicowe potwierdzone',
   'desc': 'Wersja 7.1 „A Rekviem for the Underworld” ukazała się 23 września 2026 r. z dwiema nowymi postaciami 5-gwiazdkowymi, dwiema broniami 5-gwiazdkowymi i nagrodami na szóstą rocznicę.',
   'lead': 'HoYoverse wydało wersję 7.1 „A Rekviem for the Underworld” 23 września 2026 r. — aktualizacja przynosi też szóstą rocznicę Genshin Impact.',
   'new': ['Dwie nowe postacie 5-gwiazdkowe: Vesna (Anemo, miecz) i Vodyanitsa (Hydro, katalizator).',
           'Nowe bronie: Beyond the Chrysalis (miecz 5★), Hymn of the Maelstrom (katalizator 5★) i New Bough (miecz 4★).',
           'Nagrody rocznicowe ogłoszone przez HoYoverse: dwie postacie 5-gwiazdkowe do zaproszenia, Splecione przeznaczenie ×10, Prakamienie ×1600 oraz reset bonusu za pierwsze doładowanie Kryształów Genesis.',
           'Prace techniczne rozpoczęły się 23 września o 06:00 (UTC+8).'],
   'impact': 'Według naszych badań liczba limitowanych postaci 5-gwiazdkowych, ich konstelacje i bronie sygnaturowe należą do głównych czynników wartości konta Genshin. Postacie rozdane wszystkim za darmo na rocznicę czynią konto mniej wyjątkowym niż postacie z limitowanych banerów.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, pierwszy nowy wymiar od ponad 14 lat, trafi do Java i Bedrock',
   'desc': 'Minecraft Live 26 września 2026 r. pokazał The Sift — czwarty wymiar, który w przyszłym roku trafi do Java i Bedrock — a także Dungeons II i aktualizację Wilderness Bound.',
   'lead': 'Podczas Minecraft Live 26 września 2026 r. Mojang Studios ogłosiło, że czwarty wymiar gry, The Sift, trafi do Minecraft Java i Bedrock Edition w przyszłym roku.',
   'new': ['The Sift to pierwszy nowy wymiar od ponad 14 lat; dołączy do Overworldu, Netheru i Endu.',
           'Debiutuje w Minecraft Dungeons II, którego premierę Mojang wyznaczył na 29 września 2026 r.',
           'Minecraft World, tematyczna atrakcja, zostanie otwarty w Londynie w 2027 r.',
           'Aktualizacja Wilderness Bound pojawiła się 15 września z nakrapianym lasem, łóżkami ze słomy, porzuconymi obozami i poduszkami.'],
   'impact': 'Konta Minecraft wycenia się według typu (Java lub Bedrock), nazwy użytkownika i peleryn — nie według zawartości gry. Takie aktualizacje zmieniają to, co można robić w grze, a nie wartość konta.'},
  'rbx-hunt': {
   'title': 'Roblox 20 „The Hunt”: limitowane przedmioty UGC i wyłączności Roblox Plus (17–28 września)',
   'desc': 'The Hunt: Roblox 20 trwał od 17 do 28 września 2026 r.: nagrody UGC, przedmioty UGC z limitowanej edycji i trzy wyłączne przedmioty dla subskrybentów Roblox Plus.',
   'lead': 'Roblox uczcił 20-lecie wydarzeniem The Hunt: Roblox 20 na całej platformie, które trwało od 17 do 28 września 2026 r.',
   'new': ['Gracze przechodzili przez 20 lat historii Robloxa, po jednym zadaniu na rok, zaczynając od „Year Zero”; ukończenie wszystkich 20 odblokowywało „Year Infinity” z 20 kolejnymi grami.',
           'Zadania dawały przedmioty UGC, a w trakcie wydarzenia dostępne były przedmioty UGC z limitowanej edycji.',
           'Subskrybenci Roblox Plus otrzymali trzy wyłączne przedmioty wirtualne i po wydarzeniu zachowują motyw aplikacji Classic, klasyczne tło awatara i ramkę profilu.',
           'Motyw aplikacji Classic był darmowy dla wszystkich w czasie wydarzenia.'],
   'impact': 'Przedmioty, które można było zdobyć tylko w trakcie wydarzenia, należą do tego, na co patrzy wycena. Roblox nie wymienił ich nazw w ogłoszeniu, więc ta strona nie podaje ich cen, dopóki nie pojawią się prawdziwe oferty sprzedaży.'},
  'rbx-rdc': {
   'title': 'RDC 2026: twórcy Robloxa zarobili ok. 1,7 mld dolarów w rok; ogłoszono Roblox Wallet',
   'desc': 'Na RDC 2026 Roblox podał, że twórcy zarobili ok. 1,7 mld dolarów w 12 miesięcy, i ogłosił Roblox Wallet oraz Roblox Card do wypłat.',
   'lead': 'Na konferencji deweloperów RDC 2026 (ogłoszenie z 11 września 2026 r.) Roblox przedstawił dane o zarobkach twórców i nowe narzędzia do wypłat.',
   'new': ['Od startu DevEx w 2013 r. twórcy zarobili ponad 5 mld dolarów, a w 12 miesiącach do 30 czerwca 2026 r. — ok. 1,7 mld.',
           'Zachęty Roblox Plus przyniosły twórcom ponad 300 mln Robux w pierwszych czterech miesiącach (do 17 sierpnia 2026 r.).',
           'Roblox Wallet, konto płatnicze prowadzone z Airwallex US, zapewni codzienne wypłaty w prawdziwej walucie — najpierw pod koniec 2026 r. dla uprawnionych niezależnych twórców z USA w wieku 18+, a w 2027 r. międzynarodowo.',
           'Karta Roblox Card powiązana z Wallet jest planowana od 2027 r.'],
   'impact': 'Te zmiany dotyczą wypłat dla twórców, nie kont graczy: ogłoszenie nie zmieniło cen Robux, przedmiotów limitowanych ani wymiany. Saldo Robux i przedmioty limitowane pozostają tym, co uwzględnia nasz kalkulator Roblox.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: cztery nowe bronie w Clash Squad, Prime Diamond i przebudowa Kenty',
   'desc': 'Notatki do łatki OB55 od Garena (10 września 2026 r.) dodają M7, Skorp, RPK i Hawk do Clash Squad od 1 października, wprowadzają Prime Diamond i przebudowują Kentę.',
   'lead': 'Garena opublikowała notatki do łatki OB55 dla Free Fire 10 września 2026 r.; zmiany broni obowiązują od 1 października.',
   'new': ['Nowe bronie Clash Squad od 1 października: M7 (1600 CS Cash), Skorp (1500), RPK (1500) i Hawk (1700).',
           'Prime Diamond: diamenty zależne od miesięcznych wydatków, do odebrania w kolejnym miesiącu po dowolnym doładowaniu.',
           'Kenta przechodzi pełną przebudowę; Morse, Luna i Wukong dostają zmiany balansu.',
           'Od 1 października zmienia się mobilność według klasy broni: pistolety maszynowe szybsze, karabiny snajperskie i wyborowe wolniejsze.'],
   'impact': 'Nasz kalkulator Free Fire uwzględnia saldo diamentów i rzadkie pakiety. OB55 zmienia sposób nagradzania przyszłych doładowań; nie zmienia przedmiotów, które już są na kontach.'},
  'cr-minion': {
   'title': 'Clash Royale, sezon „Minion Academy”: nowa karta Gigantyczny Stwór i bohater Lodowy Czarodziej',
   'desc': 'Sezon Minion Academy (7 września – 5 października 2026 r.) dodaje kartę Gigantyczny Stwór (Minion Giant), bohatera Lodowego Czarodzieja i wydarzenie albumowe z 1750 kartami.',
   'lead': 'Supercell otworzył sezon Clash Royale „Minion Academy”, trwający od 7 września do 5 października 2026 r.',
   'new': ['Nowa karta Gigantyczny Stwór (Minion Giant): latający warunek zwycięstwa, który atakuje budynki i wieże. Jest darmowa w wydarzeniu albumowym Academy Antics, a w skrzyniach pojawi się dopiero w przyszłym sezonie.',
           'Wydarzenie albumowe daje 1750 kart Gigantycznego Stwora, emotkę i skórkę wieży.',
           'Nowy bohater: Lodowy Czarodziej, ze ścieżki Pass Royale lub za 200 monet bohaterów.',
           'Wydarzenia: liga 2v2 (7–21 września), globalny turniej Princess Gambit (21–26 września) i Royale Shuffle (21 września – 5 października). Remis w Ultimate Champion kosztuje teraz połowę pucharków za porażkę.'],
   'impact': 'Skórki wież i emotki dostępne tylko podczas wydarzeń czynią kolekcję Clash Royale bardziej wyjątkową, ale głównymi czynnikami wartości pozostają poziom Wieży Króla i poziomy kart.'},
  'ml-10': {
   'title': 'Mobile Legends kończy 10 lat: kampania ALL IN i nowa skórka Collector dla Layli',
   'desc': 'Kampania ALL IN od MOONTON na 10-lecie (od 4 września 2026 r.) przynosi nową skórkę Epic dla Nany, darmowe skrzynie ze skórkami i skórkę Collector dla Layli od 9 października.',
   'lead': 'MOONTON Games uruchomiło 4 września 2026 r. ALL IN — kampanię na dziesięciolecie Mobile Legends: Bang Bang.',
   'new': ['Przepustka na 10-lecie (4 września – 1 listopada): nowa skórka Epic dla Nany, skrzynia wyboru skórki Epic, skrzynia losowej skórki Epic i darmowa skórka rocznicowa dla powracających graczy.',
           'Anniversary Gala Weekend (25 września – 11 października): dostęp do 265 skórek, EXP przepustki bojowej i fragmenty skórek premium.',
           'Layla’s Stellar Gala (9 października – 19 listopada): nowa skórka Collector dla Layli w minigrze „Starfall Breakout”.',
           'MOONTON podaje ponad 1,5 mld instalacji i 110 mln aktywnych graczy miesięcznie.'],
   'impact': 'Skórki Collector i Legend należą do najczęściej wymienianych czynników wartości kont Mobile Legends; skórki rozdawane za darmo lub testowe — nie.'},
  'bs-aug': {
   'title': 'Brawl Stars: mityczni zadymiarze Cosmo i Vince; Szlak Starr zmienia się w Brawler Blast',
   'desc': 'Notatki Supercell do aktualizacji z sierpnia 2026 r. (1 września) dodają dwóch mitycznych zadymiarzy, zmieniają Szlak Starr w Brawler Blast z nowymi kosztami w kredytach i przemianowują Ultralegendarną rzadkość na Ultra.',
   'lead': 'Supercell opublikował notatki do sierpniowej aktualizacji Brawl Stars 2026 r. 1 września 2026 r.',
   'new': ['Dwóch nowych mitycznych zadymiarzy: Cosmo (kontroler) i Vince (zadający obrażenia).',
           'Nowe hiperładunki dla Nori i Wendy.',
           'Szlak Starr zmienia się w „Brawler Blast”: kredyty idą teraz na odblokowania według rzadkości — rzadki 160, superrzadki 430, epicki 925, mityczny 1900, legendarny 3800, Ultra 5500.',
           'Rzadkość „Ultralegendarna” nazywa się teraz „Ultra”. Do tego sezon Royal Academy i trwające cały miesiąc wydarzenie Brawl-O-Ween.'],
   'impact': 'Nasz kalkulator Brawl Stars uwzględnia liczbę zadymiarzy, hiperładunki i pucharki. Dwóch kolejnych mitycznych zwiększa liczbę zadymiarzy potrzebnych do pełnej kolekcji.'},
  'coc-aug': {
   'title': 'Clash of Clans, aktualizacja sierpniowa: Diggy poziomy 11–15 i Złota przepustka od Ratusza 3',
   'desc': 'Sierpniowa aktualizacja Supercell 2026 r. (30 sierpnia) dodaje poziomy 11–15 Diggy’ego i nowe superładunki na Ratuszu 18, wycofuje przepustkę startową i otwiera Złotą przepustkę od Ratusza 3.',
   'lead': 'Supercell wydał sierpniową aktualizację Clash of Clans 30 sierpnia 2026 r.',
   'new': ['Ratusz 18: zwierzak Diggy dostaje poziomy 11–15; Chata budowniczego i Monolit — nowe poziomy superładunku.',
           'Przepustka startowa zostaje wycofana: wyzwania sezonowe i Złota przepustka są dostępne od Ratusza 3, a nagrody zależą od poziomu ratusza.',
           'Rycerz Ruin nie traci już zdrowia z czasem; Wiedźma Ruin przywołuje 10 rycerzy zamiast 8.',
           'Zmieniono modyfikatory Ligi Wojen Klanów w ligach Tytan.'],
   'impact': 'Według naszych badań to poziom ratusza oraz poziomy bohaterów i zwierzaków decydują o wartości kont Clash of Clans. Nowe maksymalne poziomy na Ratuszu 18 oznaczają, że „zmaksowane” konto potrzebuje teraz więcej ulepszeń niż przed aktualizacją.'},
  'fn-c7s4': {
   'title': 'Fortnite Rozdział 7 Sezon 4 „Override”: karnet bojowy z Sonikiem i crossover KINGDOM HEARTS',
   'desc': 'Sezon „Override” od Epic (Rozdział 7, Sezon 4) przynosi konsole Override, karnet bojowy za 800 V-dolców z Sonikiem the Hedgehog na czele i crossovery, m.in. KINGDOM HEARTS.',
   'lead': '4. sezon 7. rozdziału Fortnite nazywa się „Override”. Epic opisuje go jako sezon crossoverów z grami i zmian zasad dla całego meczu.',
   'new': ['Konsole Override pojawiają się w każdym meczu i pozwalają zmieniać zasady dla całego serwera.',
           'Karnet bojowy kosztuje 800 V-dolców, a jego gwiazdą jest Sonic the Hedgehog z Tailsem jako pomocnikiem.',
           'Kto kupił karnet przed 27 sierpnia do 23:59 czasu wschodniego USA, dostał strój Infiltrator Grace Crowne jako bonus tygodnia premiery.',
           'Crossovery sezonu: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot i Spyro the Dragon; wśród broni Midas’ Masterpiece i Mega Buster Mega Mana.'],
   'impact': 'Stroje dostępne tylko przez ograniczony czas — jak bonus tygodnia premiery — odróżniają rzadkie szafki Fortnite od zwykłych. Stroje z karnetu bojowego pozostają związane ze swoim sezonem.'},
 }},
}
