# News batch 4: ru, es, pt, id (from news_text_b4_en.py, facts unchanged)
TEXT = {
'ru': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends на Азиатских играх: Мьянма взяла первое золото MLBB, обыграв Индонезию 4:0',
  'desc': 'MOONTON сообщила 1 октября 2026 года: Мьянма выиграла первое золото Азиатских игр по Mobile Legends: Bang Bang на Айти-Нагоя 2026, победив Индонезию в гранд-финале со счётом 4:0.',
  'lead': '1 октября 2026 года MOONTON Games объявила итог первого выступления Mobile Legends: Bang Bang как официальной медальной дисциплины Азиатских игр.',
  'new': ['Мьянма обыграла Индонезию 4:0 в гранд-финале в Aichi Sky Expo и стала первым обладателем золота Азиатских игр по MLBB.',
          'Индонезия получила серебро; бронзовые медали — у Малайзии и Монголии.',
          'С предварительных раундов участвовали 22 национальных олимпийских комитета, в основную стадию вышли 12 команд.',
          'Дальше в календаре — MLBB Championship Tour и чемпионат мира M8; финалы M8 пройдут в Стамбуле (Турция).'],
  'impact': 'Киберспортивные результаты не меняют стоимость существующих аккаунтов. По нашим данным, стоимость в Mobile Legends по-прежнему определяют скины, герои и прогресс аккаунта.'},
 'mc-drop4': {
  'title': 'Последний игровой дроп Minecraft 2026 года вышел на тестирование: ледяные пещеры, frostbite и ice balls',
  'desc': 'Mojang открыла тестирование последнего игрового дропа 2026 года 30 сентября 2026 года: ледяные пещеры, замёрзший вариант зомби frostbite, ice balls, ледяные кристаллы и сосульки.',
  'lead': '30 сентября 2026 года Mojang Studios открыла тестирование последнего игрового дропа Minecraft 2026 года.',
  'new': ['Новые ледяные пещеры, украшенные ледяными кристаллами (ice crystals) и сосульками (icicles); сосульки хрупкие.',
          'Новый моб frostbite — замёрзший вариант зомби — бросает ice balls; Mojang упоминает и зелье Freezing.',
          'Первая тестовая сборка от 30 сентября — preview/beta для Bedrock Edition; в посте также объясняется, как включить снапшоты Java Edition в Minecraft Launcher.',
          'Mojang предупреждает, что тестовые версии могут повредить миры, и просит делать резервные копии или использовать отдельную папку.'],
  'impact': 'Аккаунты Minecraft оцениваются по типу аккаунта (Java или Bedrock), никнейму и плащам, а не по игровому контенту. Такие обновления меняют то, что игрок может делать, а не стоимость аккаунта.'},
 'cr-bal-oct': {
  'title': 'Октябрьские правки баланса Clash Royale: Hero Ice Wizard и Minion Giant ослаблены, Lava Hound усилена',
  'desc': 'Supercell опубликовала обновление баланса от 6 октября 2026 года: урон заморозки Hero Ice Wizard 89 → 46, скорость атаки Minion Giant 1,5 с → 1,7 с, урон Lava Hound 53 → 71, переработан Golden Knight.',
  'lead': 'Supercell опубликовала обновление баланса Clash Royale от 6 октября 2026 года.',
  'new': ['Ослабления: урон заморозки Hero Ice Wizard 89 → 46; урон залпа Cannon Evolution 281 → 261; урон Barbarian Barrel 232 → 215; скорость атаки Minion Giant 1,5 с → 1,7 с; здоровье Royal Ghost 1210 → 1152.',
          'Elixir Collector: время жизни 1 мин 33 с → 1 мин 50 с, скорость производства 13 с → 15 с.',
          'Усиления: урон Lava Hound 53 → 71 (скорость атаки 1,3 с → 1,5 с); урон Ram Rider 250 → 271; урон Wall Breakers 281 → 302; урон X-Bow 58 → 61; здоровье Three Musketeers 883 → 906.',
          'Переработка: урон Golden Knight 161 → 168, дальность рывка 5,5 → 5 клеток. Supercell уточняет, что цифры приведены для 11-го уровня.'],
  'impact': 'Правки баланса меняют то, какие колоды сильны, а не то, что есть на аккаунте. По нашим данным, главными факторами стоимости остаются уровень Королевской башни и уровни карт.'},
}},
'es': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends en los Juegos Asiáticos: Myanmar gana el primer oro de MLBB al vencer 4–0 a Indonesia',
  'desc': 'MOONTON informó el 1 de octubre de 2026 de que Myanmar ganó el primer oro de los Juegos Asiáticos en Mobile Legends: Bang Bang en Aichi-Nagoya 2026, tras barrer 4–0 a Indonesia en la gran final.',
  'lead': 'El 1 de octubre de 2026 MOONTON Games anunció el resultado del estreno de Mobile Legends: Bang Bang como prueba oficial con medallas en los Juegos Asiáticos.',
  'new': ['Myanmar venció 4–0 a Indonesia en la gran final en el Aichi Sky Expo y se convirtió en el primer medallista de oro de los Juegos Asiáticos en MLBB.',
          'Indonesia se llevó la plata; Malasia y Mongolia, los bronces.',
          'Participaron 22 Comités Olímpicos Nacionales desde las rondas preliminares y 12 equipos llegaron a la fase principal.',
          'Lo siguiente en el calendario son el MLBB Championship Tour y el Mundial M8, cuyas finales serán en Estambul (Turquía).'],
  'impact': 'Los resultados de esports no cambian el valor de las cuentas existentes. Según nuestra investigación, los aspectos, los héroes y el progreso de la cuenta siguen marcando el valor en Mobile Legends.'},
 'mc-drop4': {
  'title': 'El último game drop de Minecraft de 2026 entra en pruebas: cuevas de hielo, el frostbite y ice balls',
  'desc': 'Mojang abrió el 30 de septiembre de 2026 las pruebas del último game drop de 2026: cuevas de hielo, una variante de zombi congelado llamada frostbite, ice balls, cristales de hielo y carámbanos.',
  'lead': 'El 30 de septiembre de 2026 Mojang Studios abrió las pruebas del último game drop de Minecraft de 2026.',
  'new': ['Nuevas cuevas de hielo, decoradas con cristales de hielo (ice crystals) y carámbanos (icicles); los carámbanos son frágiles.',
          'Una criatura nueva, el frostbite (variante de zombi congelado), lanza ice balls; Mojang menciona también una poción Freezing.',
          'La primera versión de prueba, del 30 de septiembre, es una preview/beta de Bedrock Edition; la publicación explica además cómo activar las snapshots de Java Edition en el Minecraft Launcher.',
          'Mojang avisa de que las versiones de prueba pueden dañar los mundos y pide hacer copias de seguridad o usar otra carpeta.'],
  'impact': 'Las cuentas de Minecraft se valoran por el tipo de cuenta (Java o Bedrock), el nombre de usuario y las capas, no por el contenido del juego. Estas actualizaciones cambian lo que se puede hacer, no lo que vale una cuenta.'},
 'cr-bal-oct': {
  'title': 'Cambios de equilibrio de octubre en Clash Royale: nerf a Hero Ice Wizard y Minion Giant, mejora a Lava Hound',
  'desc': 'Supercell publicó la actualización de equilibrio del 6 de octubre de 2026: daño de congelación de Hero Ice Wizard 89 → 46, velocidad de ataque de Minion Giant 1,5 s → 1,7 s, daño de Lava Hound 53 → 71 y Golden Knight rediseñado.',
  'lead': 'Supercell publicó la actualización de equilibrio de Clash Royale del 6 de octubre de 2026.',
  'new': ['Nerfs: daño de congelación de Hero Ice Wizard 89 → 46; daño de la ráfaga de Cannon Evolution 281 → 261; daño de Barbarian Barrel 232 → 215; velocidad de ataque de Minion Giant 1,5 s → 1,7 s; puntos de vida de Royal Ghost 1210 → 1152.',
          'Elixir Collector: duración 1 min 33 s → 1 min 50 s, velocidad de producción 13 s → 15 s.',
          'Mejoras: daño de Lava Hound 53 → 71 (velocidad de ataque 1,3 s → 1,5 s); daño de Ram Rider 250 → 271; daño de Wall Breakers 281 → 302; daño de X-Bow 58 → 61; puntos de vida de Three Musketeers 883 → 906.',
          'Rediseño: daño de Golden Knight 161 → 168, alcance de la embestida 5,5 → 5 casillas. Supercell indica que las cifras corresponden al nivel 11.'],
  'impact': 'Los cambios de equilibrio alteran qué mazos son fuertes, no lo que tiene una cuenta. Según nuestra investigación, el nivel de la Torre del Rey y el nivel de las cartas siguen siendo los principales factores de valor.'},
}},
'pt': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends nos Jogos Asiáticos: Mianmar ganha o primeiro ouro de MLBB ao vencer a Indonésia por 4–0',
  'desc': 'A MOONTON informou em 1 de outubro de 2026 que Mianmar ganhou o primeiro ouro dos Jogos Asiáticos em Mobile Legends: Bang Bang em Aichi-Nagoya 2026, vencendo a Indonésia por 4–0 na grande final.',
  'lead': 'Em 1 de outubro de 2026 a MOONTON Games anunciou o resultado da estreia de Mobile Legends: Bang Bang como modalidade oficial com medalhas nos Jogos Asiáticos.',
  'new': ['Mianmar venceu a Indonésia por 4–0 na grande final no Aichi Sky Expo e se tornou o primeiro medalhista de ouro dos Jogos Asiáticos em MLBB.',
          'A Indonésia ficou com a prata; Malásia e Mongólia, com os bronzes.',
          '22 Comitês Olímpicos Nacionais participaram desde as rodadas preliminares, e 12 equipes chegaram à fase principal.',
          'Os próximos no calendário são o MLBB Championship Tour e o Mundial M8, com as finais do M8 em Istambul, na Turquia.'],
  'impact': 'Resultados de esports não mudam o valor de contas existentes. Na nossa pesquisa, skins, heróis e o progresso da conta continuam definindo o valor em Mobile Legends.'},
 'mc-drop4': {
  'title': 'O último game drop de Minecraft de 2026 entra em testes: cavernas de gelo, o frostbite e ice balls',
  'desc': 'A Mojang abriu em 30 de setembro de 2026 os testes do último game drop de 2026: cavernas de gelo, uma variante de zumbi congelado chamada frostbite, ice balls, cristais de gelo e pingentes de gelo.',
  'lead': 'Em 30 de setembro de 2026 a Mojang Studios abriu os testes do último game drop de Minecraft de 2026.',
  'new': ['Novas cavernas de gelo, decoradas com cristais de gelo (ice crystals) e pingentes de gelo (icicles); os pingentes são frágeis.',
          'Um novo mob, o frostbite (variante de zumbi congelado), arremessa ice balls; a Mojang também cita uma poção Freezing.',
          'A primeira versão de teste, de 30 de setembro, é uma preview/beta da Bedrock Edition; o post também explica como ativar as snapshots da Java Edition no Minecraft Launcher.',
          'A Mojang avisa que versões de teste podem corromper mundos e pede que os jogadores façam backup ou usem outra pasta.'],
  'impact': 'Contas de Minecraft são avaliadas pelo tipo de conta (Java ou Bedrock), pelo nome de usuário e pelas capas, não pelo conteúdo do jogo. Atualizações assim mudam o que dá para fazer, não quanto vale uma conta.'},
 'cr-bal-oct': {
  'title': 'Mudanças de balanceamento de outubro no Clash Royale: nerf em Hero Ice Wizard e Minion Giant, buff em Lava Hound',
  'desc': 'A Supercell publicou a atualização de balanceamento de 6 de outubro de 2026: dano de congelamento do Hero Ice Wizard 89 → 46, velocidade de ataque do Minion Giant 1,5 s → 1,7 s, dano do Lava Hound 53 → 71 e Golden Knight retrabalhado.',
  'lead': 'A Supercell publicou a atualização de balanceamento do Clash Royale de 6 de outubro de 2026.',
  'new': ['Nerfs: dano de congelamento do Hero Ice Wizard 89 → 46; dano da rajada do Cannon Evolution 281 → 261; dano do Barbarian Barrel 232 → 215; velocidade de ataque do Minion Giant 1,5 s → 1,7 s; pontos de vida do Royal Ghost 1210 → 1152.',
          'Elixir Collector: duração 1 min 33 s → 1 min 50 s, velocidade de produção 13 s → 15 s.',
          'Buffs: dano do Lava Hound 53 → 71 (velocidade de ataque 1,3 s → 1,5 s); dano do Ram Rider 250 → 271; dano dos Wall Breakers 281 → 302; dano do X-Bow 58 → 61; pontos de vida dos Three Musketeers 883 → 906.',
          'Retrabalho: dano do Golden Knight 161 → 168, alcance da investida 5,5 → 5 quadrados. A Supercell informa que os números valem para o nível 11.'],
  'impact': 'Mudanças de balanceamento alteram quais decks são fortes, não o que a conta tem. Na nossa pesquisa, o nível da Torre do Rei e o nível das cartas continuam sendo os principais fatores de valor.'},
}},
'id': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends di Asian Games: Myanmar raih emas MLBB pertama setelah menang 4–0 atas Indonesia',
  'desc': 'MOONTON melaporkan pada 1 Oktober 2026 bahwa Myanmar meraih emas Asian Games pertama untuk Mobile Legends: Bang Bang di Aichi-Nagoya 2026 setelah menyapu Indonesia 4–0 di Grand Final.',
  'lead': 'Pada 1 Oktober 2026 MOONTON Games mengumumkan hasil debut Mobile Legends: Bang Bang sebagai nomor resmi peraih medali di Asian Games.',
  'new': ['Myanmar mengalahkan Indonesia 4–0 di Grand Final di Aichi Sky Expo dan menjadi peraih emas Asian Games pertama untuk MLBB.',
          'Indonesia meraih perak; Malaysia dan Mongolia meraih perunggu.',
          '22 Komite Olimpiade Nasional ikut sejak babak kualifikasi awal, dan 12 tim lolos ke Main Stage.',
          'Berikutnya di kalender adalah MLBB Championship Tour dan M8 World Championship, dengan final M8 digelar di Istanbul, Turki.'],
  'impact': 'Hasil esports tidak mengubah nilai akun yang sudah ada. Dalam riset kami, skin, hero, dan progres akun tetap menjadi penentu nilai Mobile Legends.'},
 'mc-drop4': {
  'title': 'Game drop terakhir Minecraft tahun 2026 masuk tahap uji: gua es, frostbite, dan ice balls',
  'desc': 'Mojang membuka pengujian game drop terakhir 2026 pada 30 September 2026: gua es, varian zombie beku bernama frostbite, ice balls, kristal es, dan icicles.',
  'lead': 'Pada 30 September 2026 Mojang Studios membuka pengujian game drop Minecraft terakhir tahun 2026.',
  'new': ['Gua es baru yang dihiasi kristal es (ice crystals) dan icicles; icicles mudah pecah.',
          'Mob baru, frostbite (varian zombie beku), melempar ice balls; Mojang juga menyebut ramuan Freezing.',
          'Build uji pertama, 30 September, adalah preview/beta Bedrock Edition; artikelnya juga menjelaskan cara mengaktifkan snapshot Java Edition di Minecraft Launcher.',
          'Mojang mengingatkan bahwa versi uji bisa merusak dunia dan meminta pemain membuat cadangan atau memakai folder terpisah.'],
  'impact': 'Akun Minecraft dinilai dari jenis akun (Java atau Bedrock), username, dan cape — bukan dari konten dalam game. Pembaruan seperti ini mengubah apa yang bisa dilakukan pemain, bukan nilai akun.'},
 'cr-bal-oct': {
  'title': 'Perubahan balance Clash Royale Oktober: Hero Ice Wizard dan Minion Giant di-nerf, Lava Hound di-buff',
  'desc': 'Supercell menerbitkan pembaruan balance 6 Oktober 2026: damage pembekuan Hero Ice Wizard 89 → 46, kecepatan serangan Minion Giant 1,5 dtk → 1,7 dtk, damage Lava Hound 53 → 71, dan Golden Knight dirombak.',
  'lead': 'Supercell menerbitkan pembaruan balance Clash Royale tanggal 6 Oktober 2026.',
  'new': ['Nerf: damage pembekuan Hero Ice Wizard 89 → 46; damage rentetan Cannon Evolution 281 → 261; damage Barbarian Barrel 232 → 215; kecepatan serangan Minion Giant 1,5 dtk → 1,7 dtk; hitpoint Royal Ghost 1210 → 1152.',
          'Elixir Collector: masa hidup 1 mnt 33 dtk → 1 mnt 50 dtk, kecepatan produksi 13 dtk → 15 dtk.',
          'Buff: damage Lava Hound 53 → 71 (kecepatan serangan 1,3 dtk → 1,5 dtk); damage Ram Rider 250 → 271; damage Wall Breakers 281 → 302; damage X-Bow 58 → 61; hitpoint Three Musketeers 883 → 906.',
          'Rework: damage Golden Knight 161 → 168, jarak dash 5,5 → 5 petak. Supercell mencatat angka-angka ini dihitung pada Level 11.'],
  'impact': 'Perubahan balance menggeser deck mana yang kuat, bukan isi sebuah akun. Dalam riset kami, level King Tower dan level kartu tetap menjadi faktor nilai utama.'},
}},
}
