# News batch 2: tl, sw (from news_text_b2_en.py, facts unchanged)
TEXT = {
'tl': {'a': {
 'mc-d2': {'title': 'Labas na ang Minecraft Dungeons II: ang dimension na Sift at ang Illager High Council',
  'desc': 'Inilabas ng Mojang ang Minecraft Dungeons II noong Setyembre 29, 2026 sa Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch at Switch 2, na may co-op para sa hanggang 4 na manlalaro.',
  'lead': 'Inilabas ng Mojang Studios ang Minecraft Dungeons II noong Setyembre 29, 2026.',
  'new': ['Available sa Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch at Nintendo Switch 2.',
          'Sa kuwento, kalaban ng mga manlalaro ang Illager High Council: ang Prime Enchanter, ang Supreme Evoker at ang Grand Illusioner.',
          'Gagalugarin ng mga manlalaro ang bagong dimension na Sift, na ayon sa Mojang ay darating din sa Minecraft Java at Bedrock sa susunod na taon.',
          'Puwedeng maglaro nang mag-isa o co-op hanggang 4 na tao, online man o sa iisang screen.'],
  'impact': 'Hiwalay na laro ang Dungeons II. Tinatasa pa rin ang Minecraft Java at Bedrock account ayon sa uri, username at mga cape, kaya hindi nababago ng paglabas na ito ang halaga nila.'},
 'cr-mt-oct': {'title': 'Merge Tactics ng Clash Royale: mga pagbabago sa Oktubre sa Supers, Elixir at badge',
  'desc': 'Simula Oktubre 1, 2026, ililipat ng Merge Tactics season 11 ang mga Super sa shared pool, ibababa ang Elixir kada round mula 5 hanggang 4 at magdadagdag ng Level 5 skin; magbabago ang badge sa season 12.',
  'lead': 'Inanunsyo ng Supercell ang mga pagbabago sa Oktubre para sa Merge Tactics season 11 noong Setyembre 30, 2026; may bisa ito mula Oktubre 1.',
  'new': ['Hindi na starting troop ang mga Super: mapupunta sila sa shared pool na pinag-aagawan ng lahat ng manlalaro.',
          'Bumalik sa 4 mula 5 ang Elixir na nakukuha kada round.',
          'May Level 5 skin ang Battle Machine at Dagger Duchess para sa mga nakapag-upgrade na sa kanila.',
          'Mula season 12, kailangang umabot sa Diamond League para sa Silver badge at mapabilang sa top 10,000 para sa Gold badge.'],
  'impact': 'Mula season 12, mas mahirap nang makuha ang mga badge sa mataas na ranggo, kaya mas malinaw nitong maipapakita ang galing sa isang Clash Royale profile. King Tower at card level pa rin ang pangunahing batayan ng halaga.'},
 'ml-mplph': {'title': 'MPL Philippines Season 18 Playoffs: PhilSports Arena, Oktubre 21–25',
  'desc': 'Inanunsyo ng MOONTON noong Setyembre 26, 2026 na gaganapin ang MPL Philippines Season 18 Playoffs sa Oktubre 21–25 sa PhilSports Arena at dito pipiliin ang mga koponang Pinoy para sa M8.',
  'lead': 'Inanunsyo ng MOONTON Games ang venue at petsa ng MPL Philippines Season 18 Playoffs noong Setyembre 26, 2026.',
  'new': ['Gaganapin ang playoffs sa PhilSports Arena sa Pasig City mula Oktubre 21 hanggang 25, 2026.',
          'Dito malalaman kung aling mga koponan ang kakatawan sa Pilipinas sa M8 World Championship sa Istanbul sa Enero 2027.',
          'Nagbukas ang bentahan ng tiket noong Setyembre 26, mula PHP 200.',
          'Kasabay ng anunsyo ang ika-10 anibersaryo ng laro: 1.5 bilyong install at 110 milyong aktibong manlalaro bawat buwan.'],
  'impact': 'Hindi binabago ng mga esports event ang halaga ng mga kasalukuyang account. Sa aming pananaliksik, skin, hero at progreso ang nagtatakda ng halaga ng Mobile Legends account.'},
 'cr-bal-sep': {'title': 'Balanse ng Clash Royale sa Setyembre: na-nerf ang hero na Ice Wizard at ang Minion Giant',
  'desc': 'Pinaikli ng September 2026 balance notes ng Supercell ang freeze ng hero na Ice Wizard mula 7 hanggang 5 segundo at ibinaba ang damage ng Minion Giant mula 189 hanggang 168, at ni-rework ang hero na Mega Minion at Wizard.',
  'lead': 'Naglabas ang Supercell ng dalawang round ng balance change sa Clash Royale, na ipinatupad noong Setyembre 8 at 16, 2026.',
  'new': ['Setyembre 16: freeze ng hero na Ice Wizard 7 s → 5 s; ability ng Goblinstein 4 s → 3.5 s; damage ng Minion Giant 189 → 168; damage ng Fire Spirit 207 → 215.',
          'Setyembre 8: Freeze 4 s → 3.5 s; tower damage ng Fireball 172 → 159; hitpoints ng Ice Golem 1,315 → 1,228.',
          'Rework: hero na Mega Minion (bumabalik sa pamamagitan ng warp, damage 399 → 422) at hero na Wizard (ability 5 s → 3.5 s); damage ng Wizard 281 → 304.',
          'Kabilang sa mga na-buff ang Ronin, Spirit Empress at Goblin Cage.'],
  'impact': 'Binabago ng balance change kung aling card ang uso, hindi kung ano ang laman ng account. Sa aming pananaliksik, sinusundan ng halaga sa Clash Royale ang King Tower level, card level, evolution at bihirang cosmetics.'},
 'gi-wish71': {'title': 'Event Wish ng Genshin Impact 7.1: banner nina Vesna at Vodyanitsa hanggang Oktubre 13',
  'desc': 'Pinalalaki ng Version 7.1 Phase I event wishes ng HoYoverse ang tsansa nina Vesna at Vodyanitsa hanggang Oktubre 13, 2026, kasama sina Diona, Faruzan at Chongyun bilang boosted na 4-star.',
  'lead': 'Inilabas ng HoYoverse ang Version 7.1 Phase I event wishes noong Setyembre 21, 2026; tatagal ito hanggang Oktubre 13, 2026, 17:59.',
  'new': ['Pinalalaki ng "When Warm Winds Cavort" ang tsansang makuha si Vesna (Anemo).',
          'Pinalalaki ng "Surging Ballad" ang tsansang makuha si Vodyanitsa (Hydro).',
          'Mga boosted na 4-star na karakter: Diona (Cryo), Faruzan (Anemo) at Chongyun (Cryo).',
          'Wala sa standard wish ang mga event-exclusive na karakter; iisa ang pity counter ng dalawang character banner.'],
  'impact': 'Sa aming pananaliksik, ang mga karakter na makukuha lang sa limited banner, pati ang kanilang constellation, ay kabilang sa pangunahing nagpapataas ng halaga ng Genshin account.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Trash Goblin Darryl skin at rewards hanggang Setyembre 30',
  'desc': 'Nagbigay ang Brawl Stars × Duolingo event ng Supercell (inanunsyo noong Setyembre 19, 2026) ng Trash Goblin Darryl skin, gems, Starr Drops at iba pa hanggang Setyembre 30.',
  'lead': 'Inanunsyo ng Supercell ang Brawl Stars × Duolingo crossover noong Setyembre 19, 2026; tumagal ito hanggang Setyembre 30.',
  'new': ['Dalawang yugto ng community goal at in-game task, pati ang bagong Duo Boss Fight mode.',
          'Rewards: Trash Goblin Darryl skin, 20 Gems, 5 Chaos Drops, 3 Mythic Starr Drops, 2,000 Coins, 2,500 Bling at 1,000 Credits.',
          'May dagdag na cosmetics mula sa Brawl Stars quest sa Duolingo app.',
          'Nagpa-trivia giveaway din ang Supercell sa social media na may 3.141592 milyong gems.'],
  'impact': 'Ang mga skin mula sa minsanang crossover ang nagpapatingkad sa ilang Brawl Stars collection; mas kaunti ang naidaragdag ng skin na libreng nakuha ng marami kaysa sa bihirang bayad na skin.'},
 'ff-naruto': {'title': 'Bumalik ang Free Fire × NARUTO SHIPPUDEN: Nine Tails at Hinata bundle (Setyembre 16 – Oktubre 15)',
  'desc': 'Tatagal ang NARUTO SHIPPUDEN collab ng Garena mula Setyembre 16 hanggang Oktubre 15, 2026, kasama ang skill na Sharingan: Control, isang pipiliing bundle nina Jiraiya o Hinata at themed cosmetics.',
  'lead': 'Inanunsyo ng Garena noong Setyembre 15, 2026 na babalik ang Free Fire × NARUTO SHIPPUDEN collab mula Setyembre 16 hanggang Oktubre 15.',
  'new': ['Bagong skill: Sharingan: Control para utusan ang Nine Tails, at 8 Trigrams Palm Rotation.',
          'Pinalawak na Ninja Academy sa mapa ng Hidden Leaf Village.',
          'Pipiliing grand prize: Jiraiya bundle o Hinata bundle (unang labas ni Hinata).',
          'Cosmetics: Cloak ni Tsunade, Tattoo Facepaint ni Gaara, ANBU mask ni Kakashi at ang Froggy Wallet crate.'],
  'impact': 'Ang mga bundle mula sa licensed collab na limitado ang panahon ay kabilang sa mga bihirang item na hinahanap ng aming Free Fire calculator.'},
 'ml-mtc8': {'title': 'Nagsimula ang MLBB Türkiye Championship Season 8 patungong M8 sa Istanbul',
  'desc': 'Tatakbo ang MTC Season 8 mula Setyembre 12 hanggang Oktubre 18, 2026 na may walong koponan at US$40,000 na premyo, bago ang M8 World Championship sa Istanbul sa Enero 2027.',
  'lead': 'Inanunsyo ng MOONTON Games noong Setyembre 10, 2026 na magsisimula ang MLBB Türkiye Championship Season 8 sa Setyembre 12.',
  'new': ['Regular season mula Setyembre 12 hanggang Oktubre 18; ang grand finals ay sa Nobyembre 7, 2026.',
          'Walong koponan ang kalahok, kabilang ang Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok at Dark Passage.',
          'Papasok sa playoffs ang nangungunang anim para sa bahagi ng US$40,000 na premyo.',
          'Gaganapin ang M8 World Championship sa Istanbul sa Enero 2027 — ang unang M Series event sa Europa.'],
  'impact': 'Hindi binabago ng resulta ng esports ang halaga ng mga kasalukuyang account; sa aming pananaliksik, Collector at Legend skin at bilang ng hero pa rin ang pangunahing batayan.'},
 'coc-blast': {'title': 'Equipment Blast medal event ng Clash of Clans (Setyembre 9–22)',
  'desc': 'Ginanap ang Equipment Blast mula Setyembre 9 hanggang 22, 2026: kumuha ng Tag Tickets at Champ Medals at ipambili sa Trader ng hero equipment, ore at cosmetics. Town Hall 6 pataas.',
  'lead': 'Inanunsyo ng Supercell ang Equipment Blast medal event noong Setyembre 9, 2026; tumagal ito hanggang Setyembre 22, 08:00 UTC, at bukas ang Trader hanggang Setyembre 24.',
  'new': ['Nagbigay ng Tag Tickets ang mga multiplayer battle; nagbigay ang event track ng Champ Medals, pansamantalang tropa at chest.',
          'Nagbenta ang Trader ng hero equipment, ore at cosmetics kapalit ng event medal.',
          'Pansamantalang tropa: Undertaker Yeti, K.A.N.E., Yeeter at Giant Giant.',
          'Available mula Town Hall 6.'],
  'impact': 'Bahagi ng lakas ng hero ang hero equipment at ang level nito, at sa aming pananaliksik ito ang nagtatakda ng halaga ng Clash of Clans account; isa pang paraan ang event medal para i-upgrade ito.'},
 'mc-wild': {'title': 'Wilderness Bound drop ng Minecraft: dappled forest, straw bed at abandonadong kampo',
  'desc': 'Dumating ang Wilderness Bound game drop ng Mojang noong Setyembre 15, 2026 na may dappled forest biome, poplar wood, straw bed, abandonadong kampo at cushion.',
  'lead': 'Pinangalanan ng Mojang Studios na "Wilderness Bound" ang ikatlong game drop nito sa 2026 noong Setyembre 5 at inilabas noong Setyembre 15.',
  'new': ['Bagong biome, ang dappled forest, na may matataas na poplar at shelf mushroom.',
          'Gawa sa tatlong hay bale ang straw bed at hinahayaan kang laktawan ang gabi nang hindi binabago ang spawn point.',
          'Mga abandonadong kampo na puwedeng galugarin, at cushion na gawa sa tatlong magkakulay na wool slab.',
          'Poplar wood at pinalawak na concrete at wool set para sa pagtatayo.'],
  'impact': 'Tinatasa ang Minecraft account ayon sa uri, username at mga cape, hindi sa laman ng laro, kaya hindi binabago ng game drop ang halaga ng account.'},
 'ff-award': {'title': 'Nanalo ang Free Fire ng "Best Use of IP or Licence" sa Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Ayon sa Garena noong Setyembre 3, 2026, nanalo ang Free Fire ng Best Use of IP or Licence sa Pocket Gamer Mobile Games Awards 2026 dahil sa NARUTO SHIPPUDEN collab.',
  'lead': 'Inanunsyo ng Garena noong Setyembre 3, 2026 na nanalo ang Free Fire ng "Best Use of IP or Licence" sa Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Kinikilala ng parangal ang NARUTO SHIPPUDEN Chapter 2: Ninja War collab.',
          'Ayon sa Garena, halos 5,000 ang dumalo sa Ninja Clash All Stars sa Bangkok at umabot sa mahigit 247 milyon ang video views.',
          'May themed characters, jutsu abilities at binagong mapa ng Hidden Leaf Village ang collab.',
          'Nagkaroon ng community event sa Peru, Bangladesh, Malaysia at Taiwan.'],
  'impact': 'Hindi binabago ng parangal ang halaga ng account. Pero kinukumpirma nitong regular na bahagi ng Free Fire ang mga licensed collab — at kabilang ang limitadong bundle nila sa mga bihirang item na tinitingnan ng appraisal.'},
 'rbx-fall': {'title': 'Roblox Fall Games Preview: 10 experience ngayong Setyembre at Oktubre',
  'desc': 'Inililista ng Roblox Fall Games Preview (Setyembre 2, 2026) ang 10 bagong experience, mula Showdown at Nemesis sa Setyembre hanggang Prime Heroes, Octane at Starforged sa Oktubre.',
  'lead': 'Inilabas ng Roblox ang Fall Games Preview noong Setyembre 2, 2026, na may sampung experience para sa Setyembre at Oktubre.',
  'new': ['Setyembre: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force at Caramel.',
          'Oktubre: Prime Heroes (early access sa Setyembre na may 6 na hero), Octane, Starforged at Scrapbook Saga.',
          'Ilan sa mga ito ay galing sa Jumpstart at Incubator creator program ng Roblox.',
          'Iba-iba ang genre, mula shooter at racing hanggang survival horror at farming.'],
  'impact': 'Hindi binabago ng mga bagong experience ang kasalukuyang account. Sa aming pananaliksik, galing ang halaga ng Roblox account sa Robux, limited item at item sa matatagal nang experience; mahalaga lang ang bagong laro kapag na-trade na ang mga item nito.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: minsanang hero skin na "hindi na babalik" pagkatapos ng Oktubre 1',
  'desc': 'Nagbenta ang WWE: Search for Cena event ng Supercell (Setyembre 2026) ng anim na WWE hero skin na ayon sa Supercell ay hindi na babalik pagkatapos ng Oktubre 1, pati ang Money in the Bank scenery.',
  'lead': 'Inanunsyo ng Supercell ang WWE: Search for Cena event ng Clash of Clans noong Setyembre 1, 2026; tumagal ito buong Setyembre.',
  'new': ['Hero skin na $9.99 bawat isa: Cody Rhodes (Barbarian King), Alexa Bliss (Archer Queen), Iyo Sky (Royal Champion), Kane (Dragon Duke) at American Badass Undertaker (Grand Warden).',
          'Kasama sa Gold Pass si Jey Uso (Minion Prince).',
          'Sabi ng Supercell, "hindi na babalik. Kailanman" ang mga skin pagkatapos ng Oktubre 1.',
          'Available ang Money in the Bank XL scenery mula Setyembre 2 hanggang 30, kasabay ng John Cena challenge at pansamantalang WWE troops.'],
  'impact': 'Ang mga skin na sinasabi ng publisher na hindi na kailanman babalik ang mismong uri ng cosmetic na nagpapabihira sa isang Clash of Clans account. Gayunman, Town Hall at hero level pa rin ang may hawak ng karamihan sa halaga.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: unang silip sa bagong two-split na format',
  'desc': 'Unang silip ng Supercell sa BSC 2027 (Agosto 24, 2026): walong koponan bawat rehiyon sa apat na rehiyon, Challengers sa 12 rehiyon, dalawang tig-12 linggong split, ang Brawl Cup at World Finals.',
  'lead': 'Nagbigay ang Supercell ng unang silip sa 2027 Brawl Stars Championship noong Agosto 24, 2026, at sinabing puwede pang magbago ang mga detalye.',
  'new': ['Top level: 8 koponan bawat rehiyon sa East Asia, EMEA, South America at North America.',
          'Challengers: daan papasok sa 12 rehiyon.',
          'Dalawang split na tig-12 linggo; nagtatapos ang Split 1 sa Brawl Cup, isang tatlong-araw na international LAN, at ang Split 2 sa World Finals.',
          'Hindi pa inaanunsyo ang mga petsa, premyo at lugar.'],
  'impact': 'Hindi binabago ng esports format ang halaga ng mga kasalukuyang account; bilang ng brawler, Hypercharge at trophy pa rin ang ginagamit ng aming Brawl Stars calculator.'},
}},
'sw': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II imetoka: ulimwengu wa Sift na Baraza Kuu la Illager',
  'desc': 'Mojang ilitoa Minecraft Dungeons II tarehe 29 Septemba 2026 kwenye Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch na Switch 2, ikiwa na uchezaji wa pamoja hadi wachezaji 4.',
  'lead': 'Mojang Studios ilitoa Minecraft Dungeons II tarehe 29 Septemba 2026.',
  'new': ['Inapatikana kwenye Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch na Nintendo Switch 2.',
          'Hadithi inawakutanisha wachezaji na Baraza Kuu la Illager: Prime Enchanter, Supreme Evoker na Grand Illusioner.',
          'Wachezaji wanachunguza ulimwengu mpya, Sift, ambao kwa mujibu wa Mojang utakuja pia kwenye Minecraft Java na Bedrock mwaka ujao.',
          'Unaweza kucheza peke yako au kwa ushirikiano hadi watu 4, mtandaoni au kwenye skrini moja.'],
  'impact': 'Dungeons II ni mchezo tofauti. Akaunti za Minecraft Java na Bedrock bado hupimwa kwa aina, jina la mtumiaji na makoti, kwa hiyo kutoka kwake hakubadilishi thamani yake.'},
 'cr-mt-oct': {'title': 'Merge Tactics ya Clash Royale: mabadiliko ya Oktoba kwa Super, Elixir na beji',
  'desc': 'Kuanzia 1 Oktoba 2026, msimu wa 11 wa Merge Tactics unahamisha Super kwenye hifadhi ya pamoja, unapunguza Elixir kwa raundi kutoka 5 hadi 4 na kuongeza ngozi za kiwango cha 5; sheria za beji zinabadilika msimu wa 12.',
  'lead': 'Supercell ilitangaza mabadiliko ya Oktoba ya msimu wa 11 wa Merge Tactics tarehe 30 Septemba 2026; yanaanza kutumika 1 Oktoba.',
  'new': ['Super si wanajeshi wa kuanzia tena: wanaenda kwenye hifadhi ya pamoja ambayo wachezaji wote wanagombania.',
          'Elixir inayopatikana kila raundi inarudi kutoka 5 hadi 4.',
          'Battle Machine na Dagger Duchess wanapata ngozi za kiwango cha 5 kwa wachezaji ambao tayari wamewaboresha.',
          'Kuanzia msimu wa 12, beji ya Fedha inahitaji kufika Diamond League na beji ya Dhahabu inahitaji kuwa ndani ya 10,000 bora.'],
  'impact': 'Kuanzia msimu wa 12, beji za nafasi za juu zitakuwa ngumu zaidi kupata, hivyo zitaonyesha ujuzi kwa uwazi zaidi kwenye wasifu wa Clash Royale. Kiwango cha King Tower na viwango vya kadi vinabaki kuwa vichocheo vikuu vya thamani.'},
 'ml-mplph': {'title': 'Mtoano wa MPL Philippines msimu wa 18: PhilSports Arena, 21–25 Oktoba',
  'desc': 'MOONTON ilitangaza tarehe 26 Septemba 2026 kwamba mtoano wa msimu wa 18 wa MPL Philippines utafanyika 21–25 Oktoba katika PhilSports Arena na utaamua timu za Ufilipino kwa M8.',
  'lead': 'MOONTON Games ilitangaza ukumbi na tarehe za mtoano wa msimu wa 18 wa MPL Philippines tarehe 26 Septemba 2026.',
  'new': ['Mtoano unafanyika PhilSports Arena, jijini Pasig, kuanzia 21 hadi 25 Oktoba 2026.',
          'Utaamua timu zitakazowakilisha Ufilipino kwenye Mashindano ya Dunia ya M8 jijini Istanbul mwezi Januari 2027.',
          'Uuzaji wa tiketi ulifunguliwa 26 Septemba, kuanzia peso 200 za Ufilipino.',
          'Tangazo linaadhimisha miaka 10 ya mchezo: usakinishaji bilioni 1.5 na wachezaji hai milioni 110 kila mwezi.'],
  'impact': 'Matukio ya esports hayabadilishi thamani ya akaunti zilizopo. Katika utafiti wetu, thamani ya akaunti za Mobile Legends inatokana na ngozi, mashujaa na maendeleo.'},
 'cr-bal-sep': {'title': 'Usawazishaji wa Septemba wa Clash Royale: shujaa Ice Wizard na Minion Giant wapunguzwa nguvu',
  'desc': 'Maelezo ya usawazishaji ya Septemba 2026 ya Supercell yanapunguza muda wa kuganda wa shujaa Ice Wizard kutoka sekunde 7 hadi 5 na madhara ya Minion Giant kutoka 189 hadi 168, na kuwafanyia upya mashujaa Mega Minion na Wizard.',
  'lead': 'Supercell ilichapisha awamu mbili za mabadiliko ya usawazishaji ya Clash Royale, yaliyoanza kutumika 8 na 16 Septemba 2026.',
  'new': ['16 Septemba: kuganda kwa shujaa Ice Wizard sek 7 → sek 5; uwezo wa Goblinstein sek 4 → sek 3.5; madhara ya Minion Giant 189 → 168; madhara ya Fire Spirit 207 → 215.',
          '8 Septemba: Freeze sek 4 → sek 3.5; madhara ya Fireball kwa minara 172 → 159; afya ya Ice Golem 1,315 → 1,228.',
          'Marekebisho: shujaa Mega Minion (anarudi kwa kuhamia papo hapo, madhara 399 → 422) na shujaa Wizard (uwezo sek 5 → sek 3.5); madhara ya Wizard 281 → 304.',
          'Walioongezewa nguvu ni pamoja na Ronin, Spirit Empress na Goblin Cage.'],
  'impact': 'Usawazishaji hubadilisha kadi zinazopendwa, si kile ambacho akaunti inamiliki. Katika utafiti wetu, thamani ya Clash Royale hufuata kiwango cha King Tower, viwango vya kadi, mageuzi na mapambo adimu.'},
 'gi-wish71': {'title': 'Event Wish za Genshin Impact 7.1: banner za Vesna na Vodyanitsa hadi 13 Oktoba',
  'desc': 'Event Wish za awamu ya I ya Toleo 7.1 kutoka HoYoverse zinaongeza nafasi ya Vesna na Vodyanitsa hadi 13 Oktoba 2026, na Diona, Faruzan na Chongyun kama wahusika wa nyota 4 walioongezewa nafasi.',
  'lead': 'HoYoverse ilichapisha Event Wish za awamu ya I ya Toleo 7.1 tarehe 21 Septemba 2026; zinaendelea hadi 13 Oktoba 2026 saa 17:59.',
  'new': ['"When Warm Winds Cavort" inaongeza nafasi ya kupata Vesna (Anemo).',
          '"Surging Ballad" inaongeza nafasi ya kupata Vodyanitsa (Hydro).',
          'Wahusika wa nyota 4 walioongezewa nafasi: Diona (Cryo), Faruzan (Anemo) na Chongyun (Cryo).',
          'Wahusika maalum wa tukio hawapo kwenye wish ya kawaida; banner mbili za wahusika zinashiriki kihesabu kimoja cha uhakika.'],
  'impact': 'Katika utafiti wetu, wahusika wanaopatikana tu kupitia banner za muda mfupi, pamoja na constellation zao, ni miongoni mwa vichocheo vikuu vya thamani ya akaunti ya Genshin.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: ngozi ya Trash Goblin Darryl na zawadi hadi 30 Septemba',
  'desc': 'Tukio la Brawl Stars × Duolingo la Supercell (lililotangazwa 19 Septemba 2026) lilitoa ngozi ya Trash Goblin Darryl, vito, Starr Drops na zaidi hadi 30 Septemba.',
  'lead': 'Supercell ilitangaza ushirikiano wa Brawl Stars × Duolingo tarehe 19 Septemba 2026; ulidumu hadi 30 Septemba.',
  'new': ['Awamu mbili za malengo ya jumuiya na kazi za ndani ya mchezo, pamoja na hali mpya ya Duo Boss Fight.',
          'Zawadi: ngozi ya Trash Goblin Darryl, Vito 20, Chaos Drops 5, Mythic Starr Drops 3, Sarafu 2,000, Bling 2,500 na Credits 1,000.',
          'Jukumu la Brawl Stars ndani ya programu ya Duolingo lilitoa mapambo ya ziada.',
          'Supercell pia ilifanya shindano la maswali mitandaoni lenye zawadi ya vito milioni 3.141592.'],
  'impact': 'Ngozi kutoka kwa ushirikiano wa mara moja hufanya baadhi ya mikusanyiko ya Brawl Stars ijitokeze; ngozi waliyoipata wengi bure inaongeza kidogo kuliko ngozi adimu ya kulipia.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN yarudi: Mkia Tisa na kifurushi cha Hinata (16 Septemba – 15 Oktoba)',
  'desc': 'Ushirikiano wa Garena na NARUTO SHIPPUDEN unaendelea 16 Septemba – 15 Oktoba 2026 ukiwa na ujuzi wa Sharingan: Control, kifurushi cha kuchagua Jiraiya au Hinata na mapambo yenye mandhari.',
  'lead': 'Garena ilitangaza tarehe 15 Septemba 2026 kwamba ushirikiano wa Free Fire × NARUTO SHIPPUDEN unarudi kuanzia 16 Septemba hadi 15 Oktoba.',
  'new': ['Ujuzi mpya: Sharingan: Control unaoongoza Mkia Tisa, na 8 Trigrams Palm Rotation.',
          'Chuo cha Ninja kilichopanuliwa kwenye ramani ya Kijiji Kilichofichwa cha Jani.',
          'Zawadi kuu ya kuchagua: kifurushi cha Jiraiya au kifurushi cha Hinata (Hinata akionekana kwa mara ya kwanza).',
          'Mapambo: Joho la Tsunade, Rangi ya Uso ya Tatoo ya Gaara, Barakoa ya ANBU ya Kakashi na sanduku la Froggy Wallet.'],
  'impact': 'Vifurushi kutoka kwa ushirikiano wenye leseni vinavyopatikana kwa muda mfupi ni miongoni mwa vitu adimu ambavyo kikokotoo chetu cha Free Fire hutafuta.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship msimu wa 8 waanza, njiani kuelekea M8 Istanbul',
  'desc': 'MTC msimu wa 8 unafanyika 12 Septemba – 18 Oktoba 2026 ukiwa na timu nane na zawadi ya dola 40,000, kabla ya Mashindano ya Dunia ya M8 Istanbul Januari 2027.',
  'lead': 'MOONTON Games ilitangaza tarehe 10 Septemba 2026 kwamba MLBB Türkiye Championship msimu wa 8 unaanza 12 Septemba.',
  'new': ['Msimu wa kawaida 12 Septemba – 18 Oktoba; fainali kuu tarehe 7 Novemba 2026.',
          'Timu nane zinashiriki, zikiwemo Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok na Dark Passage.',
          'Timu sita bora zinaingia mtoano kugombania zawadi ya dola 40,000.',
          'Mashindano ya Dunia ya M8 yatafanyika Istanbul Januari 2027 — tukio la kwanza la M Series barani Ulaya.'],
  'impact': 'Matokeo ya esports hayabadilishi thamani ya akaunti zilizopo; ngozi za Collector na Legend na idadi ya mashujaa zinabaki kuwa vichocheo vikuu katika utafiti wetu.'},
 'coc-blast': {'title': 'Tukio la medali la Equipment Blast la Clash of Clans (9–22 Septemba)',
  'desc': 'Tukio la Equipment Blast lilifanyika 9–22 Septemba 2026: pata Tag Tickets na Champ Medals uzitumie kwa Mfanyabiashara kununua vifaa vya mashujaa, madini na mapambo. Town Hall 6 na zaidi.',
  'lead': 'Supercell ilitangaza tukio la medali la Equipment Blast tarehe 9 Septemba 2026; lilidumu hadi 22 Septemba saa 08:00 UTC, na Mfanyabiashara alikuwa wazi hadi 24 Septemba.',
  'new': ['Mapigano ya wachezaji wengi yalitoa Tag Tickets; njia ya tukio ilitoa Champ Medals, wanajeshi wa muda na masanduku.',
          'Mfanyabiashara aliuza vifaa vya mashujaa, madini na mapambo kwa medali za tukio.',
          'Wanajeshi wa muda: Undertaker Yeti, K.A.N.E., Yeeter na Giant Giant.',
          'Linapatikana kuanzia Town Hall 6.'],
  'impact': 'Vifaa vya mashujaa na viwango vyake ni sehemu ya nguvu ya mashujaa, ambayo katika utafiti wetu huamua thamani ya akaunti za Clash of Clans; medali za tukio ni njia nyingine ya kuviboresha.'},
 'mc-wild': {'title': 'Sasisho la Minecraft Wilderness Bound: msitu wenye madoa, vitanda vya majani na kambi zilizotelekezwa',
  'desc': 'Sasisho la Wilderness Bound la Mojang lilitoka tarehe 15 Septemba 2026 likiwa na biomu ya msitu wenye madoa, mbao za mipapai, vitanda vya majani, kambi zilizotelekezwa na mito ya kukalia.',
  'lead': 'Mojang Studios ilipa sasisho lake la tatu la 2026 jina "Wilderness Bound" tarehe 5 Septemba na kulitoa tarehe 15 Septemba.',
  'new': ['Biomu mpya, msitu wenye madoa, yenye miti mirefu ya mipapai na uyoga wa rafu.',
          'Vitanda vya majani vinavyotengenezwa kwa marobota matatu ya nyasi vinakuruhusu kuruka usiku bila kubadilisha mahali pa kuzaliwa upya.',
          'Kambi zilizotelekezwa za kuchunguza, na mito ya kukalia inayotengenezwa kwa vipande vitatu vya sufu vya rangi moja.',
          'Mbao za mipapai pamoja na seti zilizopanuliwa za saruji na sufu za ujenzi.'],
  'impact': 'Akaunti za Minecraft hupimwa kwa aina, jina la mtumiaji na makoti, si kwa maudhui ya mchezo, kwa hiyo sasisho halibadilishi thamani ya akaunti.'},
 'ff-award': {'title': 'Free Fire yashinda "Best Use of IP or Licence" katika Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena ilisema tarehe 3 Septemba 2026 kwamba Free Fire ilishinda Best Use of IP or Licence katika Pocket Gamer Mobile Games Awards 2026 kwa ushirikiano wake na NARUTO SHIPPUDEN.',
  'lead': 'Garena ilitangaza tarehe 3 Septemba 2026 kwamba Free Fire ilishinda "Best Use of IP or Licence" katika Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Tuzo hii inatambua ushirikiano wa NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Kwa mujibu wa Garena, tukio lake la Ninja Clash All Stars jijini Bangkok lilivutia karibu wageni 5,000 na zaidi ya mara milioni 247 za kutazamwa kwa video.',
          'Ushirikiano ulijumuisha wahusika wenye mandhari, uwezo wa jutsu na ramani iliyobadilishwa ya Kijiji Kilichofichwa cha Jani.',
          'Matukio ya jumuiya yalifanyika Peru, Bangladesh, Malaysia na Taiwan.'],
  'impact': 'Tuzo haibadilishi thamani ya akaunti. Lakini inathibitisha kuwa ushirikiano wenye leseni ni sehemu ya kawaida ya Free Fire — na vifurushi vyao vya muda mfupi ni miongoni mwa vitu adimu ambavyo tathmini huangalia.'},
 'rbx-fall': {'title': 'Muhtasari wa michezo ya vuli ya Roblox: uzoefu 10 unaokuja Septemba na Oktoba',
  'desc': 'Muhtasari wa michezo ya vuli ya Roblox (2 Septemba 2026) unaorodhesha uzoefu 10 mpya, kuanzia Showdown na Nemesis Septemba hadi Prime Heroes, Octane na Starforged Oktoba.',
  'lead': 'Roblox ilichapisha muhtasari wake wa michezo ya vuli tarehe 2 Septemba 2026, ukiwa na uzoefu kumi unaotarajiwa Septemba na Oktoba.',
  'new': ['Septemba: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force na Caramel.',
          'Oktoba: Prime Heroes (ufikiaji wa mapema Septemba ukiwa na mashujaa 6), Octane, Starforged na Scrapbook Saga.',
          'Michezo kadhaa inatoka kwenye programu za watengenezaji za Roblox, Jumpstart na Incubator.',
          'Aina zake ni kuanzia michezo ya kufyatua risasi na mbio hadi hofu ya kuishi na kilimo.'],
  'impact': 'Uzoefu mpya haubadilishi akaunti zilizopo. Katika utafiti wetu, thamani ya akaunti ya Roblox inatokana na Robux, vitu vya limited na vitu ndani ya uzoefu wa muda mrefu; mchezo mpya una maana pale tu vitu vyake vinapoanza kuuzwa.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: ngozi za mashujaa za mara moja "zisizorudi" baada ya 1 Oktoba',
  'desc': 'Tukio la WWE: Search for Cena la Supercell (Septemba 2026) liliuza ngozi sita za mashujaa wa WWE ambazo kwa mujibu wa Supercell hazitarudi baada ya 1 Oktoba, pamoja na mandhari ya Money in the Bank.',
  'lead': 'Supercell ilitangaza tukio la WWE: Search for Cena la Clash of Clans tarehe 1 Septemba 2026; lilidumu Septemba nzima.',
  'new': ['Ngozi za mashujaa kwa dola 9.99 kila moja: Cody Rhodes (Barbarian King), Alexa Bliss (Archer Queen), Iyo Sky (Royal Champion), Kane (Dragon Duke) na American Badass Undertaker (Grand Warden).',
          'Jey Uso (Minion Prince) alikuja na Gold Pass.',
          'Supercell inasema ngozi hizi "hazitarudi. Kamwe" baada ya 1 Oktoba.',
          'Mandhari ya Money in the Bank XL ilipatikana 2–30 Septemba, pamoja na changamoto ya John Cena na wanajeshi wa muda wa WWE.'],
  'impact': 'Ngozi ambazo mchapishaji anasema hazitarudi kamwe ndizo hasa aina ya mapambo yanayoifanya akaunti ya Clash of Clans kuwa adimu zaidi. Hata hivyo, sehemu kubwa ya thamani bado iko kwenye viwango vya Town Hall na mashujaa.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: mtazamo wa kwanza wa muundo mpya wa awamu mbili',
  'desc': 'Mtazamo wa kwanza wa Supercell kuhusu BSC 2027 (24 Agosti 2026): timu nane kwa kila kanda katika kanda nne, Challengers katika kanda 12, awamu mbili za wiki 12, Brawl Cup na Fainali za Dunia.',
  'lead': 'Supercell ilitoa mtazamo wa kwanza wa Brawl Stars Championship 2027 tarehe 24 Agosti 2026, ikisema maelezo bado yanaweza kubadilika.',
  'new': ['Ngazi ya juu: timu 8 kwa kila kanda katika Asia Mashariki, EMEA, Amerika Kusini na Amerika Kaskazini.',
          'Challengers: njia ya kuingia katika kanda 12.',
          'Awamu mbili za wiki 12 kila moja; awamu ya 1 inaishia kwa Brawl Cup, mashindano ya kimataifa ya LAN ya siku tatu, na awamu ya 2 kwa Fainali za Dunia.',
          'Tarehe, zawadi na maeneo bado havijatangazwa.'],
  'impact': 'Miundo ya esports haibadilishi thamani ya akaunti zilizopo; kikokotoo chetu cha Brawl Stars bado kinatumia idadi ya brawler, Hypercharge na vikombe.'},
}},
}
