# News translations: fr, de (from news_data.py 'en', facts unchanged)
TEXT = {
'fr': {
 'ui': {
  'news': 'Actualités', 'news_title': 'L’actualité des jeux qui influe sur la valeur d’un compte',
  'news_lead': 'Des mises à jour officielles des éditeurs — chacune vérifiée dans l’annonce de l’éditeur lui-même, avec une note claire sur ce qu’elle change pour la valeur d’un compte.',
  'game_title': 'Actualités {game}', 'game_lead': 'Les mises à jour officielles de {game} qui influent sur la valeur d’un compte. Chaque article renvoie vers l’annonce de l’éditeur.',
  'published': 'Publié le', 'source': 'Source officielle', 'by_on': '{pub}, {date}', 'whats_new': 'Les nouveautés',
  'impact': 'Ce que cela change pour la valeur d’un compte', 'more': 'Plus d’actualités {game}', 'all': 'Toutes les actualités',
  'calc': '{game} : calculateur de valeur et rapport de marché', 'read': 'Lire', 'latest': 'Dernières actualités {game}',
  'note': 'GameAccountValue n’achète, ne vend et ne négocie aucun compte. Les actualités résument les annonces des éditeurs, à titre d’information uniquement.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1 : Vesna et Vodyanitsa arrivent, les récompenses d’anniversaire sont confirmées',
   'desc': 'La version 7.1, « A Rekviem for the Underworld », est sortie le 23 septembre 2026 avec deux personnages 5 étoiles, deux armes 5 étoiles et les récompenses du sixième anniversaire.',
   'lead': 'HoYoverse a publié la version 7.1, « A Rekviem for the Underworld », le 23 septembre 2026 — la mise à jour qui porte aussi le sixième anniversaire de Genshin Impact.',
   'new': ['Deux nouveaux personnages 5 étoiles : Vesna (Anémo, épée à une main) et Vodyanitsa (Hydro, catalyseur).',
           'Nouvelles armes : Beyond the Chrysalis (épée 5★), Hymn of the Maelstrom (catalyseur 5★) et New Bough (épée 4★).',
           'Récompenses d’anniversaire annoncées par HoYoverse : deux personnages 5 étoiles à inviter, Destinées entrelacées ×10, Primogemmes ×1 600 et la réinitialisation du bonus de première recharge de Cristaux de genèse.',
           'La maintenance de mise à jour a commencé le 23 septembre à 06 h 00 (UTC+8).'],
   'impact': 'Le nombre de personnages 5 étoiles limités, leurs constellations et leurs armes emblématiques font partie des principaux facteurs de valeur d’un compte Genshin selon nos recherches. Les personnages offerts à tous pour l’anniversaire rendent un compte moins singulier que ceux des bannières limitées.'},
  'mc-live': {
   'title': 'Minecraft Live : The Sift, première nouvelle dimension depuis plus de 14 ans, arrive sur Java et Bedrock',
   'desc': 'Le Minecraft Live du 26 septembre 2026 a dévoilé The Sift, une quatrième dimension qui arrive sur Java et Bedrock l’an prochain, ainsi que Dungeons II et la mise à jour Wilderness Bound.',
   'lead': 'Lors du Minecraft Live du 26 septembre 2026, Mojang Studios a annoncé que la quatrième dimension du jeu, The Sift, arrivera sur Minecraft Java et Bedrock Edition l’an prochain.',
   'new': ['The Sift est la première nouvelle dimension depuis plus de 14 ans ; elle rejoint la Surface, le Nether et l’End.',
           'Elle fait ses débuts dans Minecraft Dungeons II, dont Mojang a fixé la sortie au 29 septembre 2026.',
           'Minecraft World, une attraction thématique, ouvrira à Londres en 2027.',
           'La mise à jour Wilderness Bound est sortie le 15 septembre avec la forêt tachetée, les lits de paille, les camps abandonnés et les coussins.'],
   'impact': 'Un compte Minecraft s’évalue selon son type (Java ou Bedrock), son pseudo et ses capes — pas selon le contenu du jeu. Ces mises à jour changent ce que l’on peut faire en jeu, pas la valeur d’un compte.'},
  'rbx-hunt': {
   'title': 'Roblox 20 « The Hunt » : objets UGC limités et exclusivités Roblox Plus (17–28 septembre)',
   'desc': 'The Hunt: Roblox 20 s’est tenu du 17 au 28 septembre 2026 avec des récompenses UGC, des objets UGC en édition limitée et trois objets exclusifs pour les abonnés Roblox Plus.',
   'lead': 'Roblox a fêté ses 20 ans avec The Hunt: Roblox 20, un événement sur toute la plateforme qui s’est déroulé du 17 au 28 septembre 2026.',
   'new': ['Les joueurs traversaient 20 ans d’histoire de Roblox, une quête par année, en partant de « Year Zero » ; terminer les 20 débloquait « Year Infinity », avec 20 jeux de plus.',
           'Les quêtes donnaient des objets UGC, et des objets UGC en édition limitée étaient proposés pendant l’événement.',
           'Les abonnés Roblox Plus ont reçu trois objets virtuels exclusifs et conservent le thème d’application Classic, le fond d’avatar classique et le cadre de profil après l’événement.',
           'Le thème d’application Classic était gratuit pour tous pendant l’événement.'],
   'impact': 'Les objets qu’on ne pouvait obtenir que pendant un événement font partie de ce qu’une estimation examine. Roblox n’a pas nommé ces objets dans son annonce ; ce site ne leur donne donc pas de prix tant qu’il n’existe pas d’annonces de vente réelles.'},
  'rbx-rdc': {
   'title': 'RDC 2026 : les créateurs Roblox ont gagné environ 1,7 milliard de dollars en un an ; Roblox Wallet annoncé',
   'desc': 'À la RDC 2026, Roblox a annoncé environ 1,7 milliard de dollars de revenus pour les créateurs sur 12 mois, ainsi que Roblox Wallet et Roblox Card pour les paiements.',
   'lead': 'Lors de sa conférence pour développeurs RDC 2026 (annonce du 11 septembre 2026), Roblox a publié des chiffres de revenus des créateurs et de nouveaux outils de paiement.',
   'new': ['Les créateurs ont gagné plus de 5 milliards de dollars depuis le lancement de DevEx en 2013, et environ 1,7 milliard sur les 12 mois jusqu’au 30 juin 2026.',
           'Les incitations Roblox Plus ont généré plus de 300 millions de Robux de revenus pour les créateurs en quatre mois (jusqu’au 17 août 2026).',
           'Roblox Wallet, un compte de paiement géré avec Airwallex US, proposera des versements quotidiens en monnaie réelle — d’abord fin 2026 pour les créateurs indépendants éligibles aux États-Unis âgés de 18 ans et plus, puis à l’international en 2027.',
           'Une Roblox Card liée au Wallet est prévue à partir de 2027.'],
   'impact': 'Ces changements concernent la rémunération des créateurs, pas les comptes des joueurs : l’annonce ne modifie ni le prix des Robux, ni les objets limités, ni les échanges. Le solde de Robux et les objets limités restent ce que pèse notre calculateur Roblox.'},
  'ff-ob55': {
   'title': 'Free Fire OB55 : quatre nouvelles armes en Clash Squad, Prime Diamond et refonte de Kenta',
   'desc': 'Les notes de patch OB55 de Garena (10 septembre 2026) ajoutent M7, Skorp, RPK et Hawk au Clash Squad à partir du 1er octobre, lancent Prime Diamond et refondent Kenta.',
   'lead': 'Garena a publié les notes de patch OB55 de Free Fire le 10 septembre 2026 ; les changements d’armes s’appliquent au 1er octobre.',
   'new': ['Nouvelles armes Clash Squad à partir du 1er octobre : M7 (1 600 CS Cash), Skorp (1 500), RPK (1 500) et Hawk (1 700).',
           'Prime Diamond : des diamants gagnés selon les dépenses du mois, à récupérer le mois suivant après n’importe quelle recharge.',
           'Kenta est entièrement refondu ; Morse, Luna et Wukong reçoivent des ajustements d’équilibrage.',
           'Mobilité revue par classe d’arme à partir du 1er octobre : SMG plus rapides, fusils de précision et de tireur d’élite plus lents.'],
   'impact': 'Notre calculateur Free Fire pèse le solde de diamants et les packs rares. OB55 modifie la façon dont les futures recharges sont récompensées ; il ne change pas les objets déjà présents sur les comptes.'},
  'cr-minion': {
   'title': 'Clash Royale, saison « Minion Academy » : nouvelle carte Gargouille géante et héros Sorcier de glace',
   'desc': 'La saison Minion Academy (7 septembre – 5 octobre 2026) ajoute la carte Gargouille géante (Minion Giant), le héros Sorcier de glace et un événement d’album offrant 1 750 cartes.',
   'lead': 'Supercell a ouvert la saison « Minion Academy » de Clash Royale, du 7 septembre au 5 octobre 2026.',
   'new': ['Nouvelle carte Gargouille géante (Minion Giant) : une carte de victoire volante qui cible les bâtiments et les tours. Elle est gratuite via l’événement d’album Academy Antics et n’apparaîtra dans les coffres qu’à la saison prochaine.',
           'L’événement d’album donne 1 750 cartes Gargouille géante, une émote et une apparence de tour.',
           'Nouveau héros : Sorcier de glace, via le parcours Pass Royale ou pour 200 pièces de héros.',
           'Événements : ligue 2c2 (7–21 septembre), tournoi mondial Princess Gambit (21–26 septembre) et Royale Shuffle (21 septembre – 5 octobre). Un match nul en Champion ultime coûte désormais moitié moins de trophées qu’une défaite.'],
   'impact': 'Les apparences de tour et les émotes proposées uniquement pendant un événement rendent une collection Clash Royale plus singulière ; le niveau de la Tour du roi et celui des cartes restent les principaux facteurs de valeur.'},
  'ml-10': {
   'title': 'Mobile Legends a 10 ans : campagne ALL IN et nouveau skin Collector de Layla',
   'desc': 'La campagne ALL IN de MOONTON pour les 10 ans (depuis le 4 septembre 2026) apporte un nouveau skin Épique de Nana, des coffres de skins gratuits et un skin Collector de Layla dès le 9 octobre.',
   'lead': 'MOONTON Games a lancé le 4 septembre 2026 ALL IN, la campagne des dix ans de Mobile Legends: Bang Bang.',
   'new': ['Pass de célébration des 10 ans (4 septembre – 1er novembre) : nouveau skin Épique de Nana, coffre de sélection de skin Épique, coffre de skin Épique aléatoire et skin d’anniversaire gratuit pour les joueurs qui reviennent.',
           'Anniversary Gala Weekend (25 septembre – 11 octobre) : accès à 265 skins, EXP de Battle Pass et fragments de skin premium.',
           'Layla’s Stellar Gala (9 octobre – 19 novembre) : le nouveau skin Collector de Layla via le mini-jeu « Starfall Breakout ».',
           'MOONTON revendique plus de 1,5 milliard d’installations et 110 millions de joueurs actifs par mois.'],
   'impact': 'Les skins Collector et Legend comptent parmi les facteurs de valeur les plus cités pour un compte Mobile Legends ; les skins offerts ou en essai non.'},
  'bs-aug': {
   'title': 'Brawl Stars : les brawlers mythiques Cosmo et Vince ; la Route de Starr devient Brawler Blast',
   'desc': 'Les notes de mise à jour d’août 2026 de Supercell (1er septembre) ajoutent deux brawlers mythiques, transforment la Route de Starr en Brawler Blast avec de nouveaux coûts en crédits et renomment Ultra Légendaire en Ultra.',
   'lead': 'Supercell a publié les notes de la mise à jour d’août 2026 de Brawl Stars le 1er septembre 2026.',
   'new': ['Deux nouveaux brawlers mythiques : Cosmo (contrôleur) et Vince (dégâts).',
           'Nouvelles hypercharges pour Nori et Wendy.',
           'La Route de Starr devient « Brawler Blast » : les crédits servent désormais à débloquer par rareté — Rare 160, Super rare 430, Épique 925, Mythique 1 900, Légendaire 3 800, Ultra 5 500.',
           'La rareté « Ultra Légendaire » est renommée « Ultra ». Avec la saison Royal Academy et un événement Brawl-O-Ween sur tout le mois.'],
   'impact': 'Notre calculateur Brawl Stars utilise le nombre de brawlers, les hypercharges et les trophées. Deux mythiques de plus augmentent le nombre de brawlers nécessaires pour une collection complète.'},
  'coc-aug': {
   'title': 'Clash of Clans, mise à jour d’août : Diggy niveaux 11 à 15 et Pass d’or dès l’hôtel de ville 3',
   'desc': 'La mise à jour d’août 2026 de Supercell (30 août) ajoute les niveaux 11 à 15 de Diggy et de nouvelles surcharges à l’HDV 18, retire le Pass de démarrage et ouvre le Pass d’or dès l’HDV 3.',
   'lead': 'Supercell a publié la mise à jour d’août de Clash of Clans le 30 août 2026.',
   'new': ['Hôtel de ville 18 : le familier Diggy passe aux niveaux 11 à 15 ; la Cabane d’ouvrier et le Monolithe reçoivent de nouveaux niveaux de surcharge.',
           'Le Pass de démarrage est retiré : les défis de saison et le Pass d’or sont accessibles dès l’HDV 3, avec des récompenses adaptées au niveau de l’hôtel de ville.',
           'Le Chevalier des ruines ne perd plus de points de vie avec le temps ; la Sorcière des ruines invoque 10 chevaliers au lieu de 8.',
           'Les modificateurs de la Ligue de guerre de clans ont été ajustés dans les ligues Titan.'],
   'impact': 'Le niveau d’hôtel de ville et ceux des héros et familiers déterminent la valeur d’un compte Clash of Clans selon nos recherches. Les nouveaux niveaux maximum à l’HDV 18 signifient qu’un compte « max » demande désormais plus d’améliorations qu’avant la mise à jour.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapitre 7 Saison 4 « Override » : Passe de combat Sonic et crossover KINGDOM HEARTS',
   'desc': 'La saison « Override » d’Epic (Chapitre 7, Saison 4) apporte les consoles Override, un Passe de combat à 800 V-bucks mené par Sonic the Hedgehog et des crossovers dont KINGDOM HEARTS.',
   'lead': 'La saison 4 du chapitre 7 de Fortnite s’appelle « Override ». Epic la présente comme une saison de crossovers vidéoludiques et de règles modifiables pour toute la partie.',
   'new': ['Les consoles Override apparaissent dans chaque partie et permettent de changer les règles pour tout le serveur.',
           'Le Passe de combat coûte 800 V-bucks et met en avant Sonic the Hedgehog, accompagné de Tails en acolyte.',
           'Les joueurs ayant acheté le Passe avant le 27 août à 23 h 59 (heure de l’Est des États-Unis) ont reçu la tenue Infiltrator Grace Crowne en bonus de lancement.',
           'Crossovers de la saison : KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot et Spyro the Dragon ; parmi les armes, le Midas’ Masterpiece et le Mega Buster de Mega Man.'],
   'impact': 'Les tenues disponibles pour une durée limitée — comme un bonus de lancement — sont ce qui distingue un casier Fortnite rare d’un casier courant. Les tenues du Passe de combat restent liées à leur saison.'},
 }},
'de': {
 'ui': {
  'news': 'News', 'news_title': 'Spiele-News, die den Wert eines Kontos beeinflussen',
  'news_lead': 'Offizielle Updates der Spielepublisher – jedes mit der Ankündigung des Publishers selbst abgeglichen, mit einer klaren Notiz, was es für den Kontowert bedeutet.',
  'game_title': '{game}-News', 'game_lead': 'Offizielle {game}-Updates, die den Wert eines Kontos beeinflussen. Jeder Artikel verlinkt die Ankündigung des Publishers.',
  'published': 'Veröffentlicht', 'source': 'Offizielle Quelle', 'by_on': '{pub}, {date}', 'whats_new': 'Was ist neu',
  'impact': 'Was das für den Kontowert bedeutet', 'more': 'Weitere {game}-News', 'all': 'Alle News',
  'calc': '{game}: Wertrechner und Marktbericht', 'read': 'Lesen', 'latest': 'Neueste {game}-News',
  'note': 'GameAccountValue kauft, verkauft und vermittelt keine Konten. Die News fassen Ankündigungen der Publisher nur zur Information zusammen.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna und Vodyanitsa kommen, Jubiläumsbelohnungen bestätigt',
   'desc': 'Version 7.1 „A Rekviem for the Underworld“ erschien am 23. September 2026 mit zwei neuen 5-Sterne-Figuren, zwei 5-Sterne-Waffen und Belohnungen zum sechsten Jubiläum.',
   'lead': 'HoYoverse hat Version 7.1 „A Rekviem for the Underworld“ am 23. September 2026 veröffentlicht – das Update bringt auch das sechste Jubiläum von Genshin Impact.',
   'new': ['Zwei neue 5-Sterne-Figuren: Vesna (Anemo, Schwert) und Vodyanitsa (Hydro, Katalysator).',
           'Neue Waffen: Beyond the Chrysalis (5★-Schwert), Hymn of the Maelstrom (5★-Katalysator) und New Bough (4★-Schwert).',
           'Von HoYoverse angekündigte Jubiläumsbelohnungen: zwei 5-Sterne-Figuren zum Einladen, Verwobenes Schicksal ×10, Protogemmen ×1.600 und ein Zurücksetzen des Erstaufladebonus für Genesiskristalle.',
           'Die Update-Wartung begann am 23. September um 06:00 Uhr (UTC+8).'],
   'impact': 'Die Zahl limitierter 5-Sterne-Figuren, ihre Konstellationen und Signaturwaffen gehören laut unserer Recherche zu den wichtigsten Werttreibern von Genshin-Konten. Figuren, die zum Jubiläum alle gratis bekommen, machen ein Konto weniger besonders als Figuren aus limitierten Bannern.'},
  'mc-live': {
   'title': 'Minecraft Live: The Sift, die erste neue Dimension seit über 14 Jahren, kommt zu Java und Bedrock',
   'desc': 'Minecraft Live am 26. September 2026 zeigte The Sift, eine vierte Dimension, die nächstes Jahr zu Java und Bedrock kommt, dazu Dungeons II und das Wilderness-Bound-Update.',
   'lead': 'Bei Minecraft Live am 26. September 2026 kündigten die Mojang Studios an, dass die vierte Dimension des Spiels, The Sift, nächstes Jahr in Minecraft Java und Bedrock Edition kommt.',
   'new': ['The Sift ist die erste neue Dimension seit über 14 Jahren und reiht sich neben Oberwelt, Nether und End ein.',
           'Ihren ersten Auftritt hat sie in Minecraft Dungeons II, das Mojang für den 29. September 2026 angesetzt hat.',
           'Minecraft World, eine Themenattraktion, eröffnet 2027 in London.',
           'Das Wilderness-Bound-Update erschien am 15. September mit dem gefleckten Wald, Strohbetten, verlassenen Lagern und Sitzkissen.'],
   'impact': 'Minecraft-Konten werden nach Kontotyp (Java oder Bedrock), Nutzername und Umhängen bewertet – nicht nach Spielinhalten. Solche Updates verändern, was man im Spiel tun kann, nicht den Wert eines Kontos.'},
  'rbx-hunt': {
   'title': 'Roblox 20 „The Hunt“: limitierte UGC-Items und Roblox-Plus-Exklusives (17.–28. September)',
   'desc': 'The Hunt: Roblox 20 lief vom 17. bis 28. September 2026 mit UGC-Belohnungen, limitierten UGC-Items und drei exklusiven Items für Roblox-Plus-Abonnenten.',
   'lead': 'Roblox feierte sein 20-jähriges Jubiläum mit The Hunt: Roblox 20, einem plattformweiten Event vom 17. bis 28. September 2026.',
   'new': ['Spieler durchliefen 20 Jahre Roblox-Geschichte, eine Quest pro Jahr, beginnend im „Year Zero“; wer alle 20 schaffte, schaltete „Year Infinity“ mit 20 weiteren Spielen frei.',
           'Quests brachten UGC-Items, und während des Events gab es limitierte UGC-Items.',
           'Roblox-Plus-Abonnenten erhielten drei exklusive virtuelle Items und behalten das Classic-App-Design, den klassischen Avatar-Hintergrund und den Profilrahmen nach dem Event.',
           'Das Classic-App-Design war während des Events für alle kostenlos.'],
   'impact': 'Items, die es nur während eines Events gab, gehören zu dem, was eine Bewertung betrachtet. Roblox hat die Items in der Ankündigung nicht benannt; diese Website bepreist sie daher erst, wenn es echte Angebote gibt.'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox-Creator verdienten rund 1,7 Mrd. US-Dollar in einem Jahr; Roblox Wallet angekündigt',
   'desc': 'Auf der RDC 2026 nannte Roblox rund 1,7 Mrd. US-Dollar Creator-Einnahmen in 12 Monaten und kündigte Roblox Wallet und Roblox Card für Auszahlungen an.',
   'lead': 'Auf seiner Entwicklerkonferenz RDC 2026 (Ankündigung vom 11. September 2026) veröffentlichte Roblox Zahlen zu Creator-Einnahmen und neue Auszahlungswerkzeuge.',
   'new': ['Seit dem Start von DevEx 2013 haben Creator über 5 Mrd. US-Dollar verdient, in den 12 Monaten bis 30. Juni 2026 rund 1,7 Mrd.',
           'Roblox-Plus-Anreize brachten Creatorn in den ersten vier Monaten (bis 17. August 2026) über 300 Millionen Robux ein.',
           'Roblox Wallet, ein Zahlungskonto mit Airwallex US, soll tägliche Auszahlungen in echter Währung bieten – zuerst Ende 2026 für berechtigte unabhängige US-Creator ab 18, international 2027.',
           'Eine mit dem Wallet verknüpfte Roblox Card ist ab 2027 geplant.'],
   'impact': 'Diese Änderungen betreffen Creator-Auszahlungen, nicht Spielerkonten: Die Ankündigung änderte weder Robux-Preise noch limitierte Items oder den Handel. Robux-Guthaben und limitierte Items bleiben das, was unser Roblox-Rechner gewichtet.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: vier neue Clash-Squad-Waffen, Prime Diamond und Kenta-Überarbeitung',
   'desc': 'Garenas OB55-Patchnotes (10. September 2026) bringen ab 1. Oktober M7, Skorp, RPK und Hawk in Clash Squad, führen Prime Diamond ein und überarbeiten Kenta.',
   'lead': 'Garena veröffentlichte die OB55-Patchnotes für Free Fire am 10. September 2026; die Waffenänderungen gelten ab 1. Oktober.',
   'new': ['Neue Clash-Squad-Waffen ab 1. Oktober: M7 (1.600 CS Cash), Skorp (1.500), RPK (1.500) und Hawk (1.700).',
           'Prime Diamond: Diamanten je nach Monatsausgaben, einlösbar im Folgemonat nach einer beliebigen Aufladung.',
           'Kenta wird komplett überarbeitet; Morse, Luna und Wukong erhalten Balance-Anpassungen.',
           'Mobilität nach Waffenklasse ab 1. Oktober geändert: MPs schneller, Scharfschützen- und Präzisionsgewehre langsamer.'],
   'impact': 'Unser Free-Fire-Rechner gewichtet das Diamantenguthaben und seltene Bundles. OB55 ändert, wie künftige Aufladungen belohnt werden; die Items, die schon in Konten sind, ändert es nicht.'},
  'cr-minion': {
   'title': 'Clash Royale, Saison „Minion Academy“: neue Karte Lakaienriese und Held Eismagier',
   'desc': 'Die Saison Minion Academy (7. September – 5. Oktober 2026) bringt die Karte Lakaienriese (Minion Giant), den Helden Eismagier und ein Albumevent mit 1.750 Lakaienriesen-Karten.',
   'lead': 'Supercell hat die Clash-Royale-Saison „Minion Academy“ eröffnet, die vom 7. September bis 5. Oktober 2026 läuft.',
   'new': ['Neue Karte Lakaienriese (Minion Giant): eine fliegende Siegbedingung, die Gebäude und Türme angreift. Sie ist über das Albumevent Academy Antics gratis und erscheint erst nächste Saison in Truhen.',
           'Das Albumevent bringt 1.750 Lakaienriesen-Karten, ein Emote und einen Turm-Skin.',
           'Neuer Held: Eismagier, über den Pass-Royale-Pfad oder für 200 Heldenmünzen.',
           'Events: 2v2-Liga (7.–21. September), weltweites Princess-Gambit-Turnier (21.–26. September) und Royale Shuffle (21. September – 5. Oktober). Ein Unentschieden im Ultimativen Champion kostet jetzt nur halb so viele Trophäen wie eine Niederlage.'],
   'impact': 'Turm-Skins und Emotes, die es nur während eines Events gibt, machen eine Clash-Royale-Sammlung besonderer; die wichtigsten Werttreiber bleiben aber das Königsturm-Level und die Kartenlevel.'},
  'ml-10': {
   'title': 'Mobile Legends wird 10: ALL-IN-Kampagne und neuer Collector-Skin für Layla',
   'desc': 'MOONTONs ALL-IN-Kampagne zum 10. Jubiläum (ab 4. September 2026) bringt einen neuen Epic-Skin für Nana, kostenlose Skin-Truhen und ab 9. Oktober einen Collector-Skin für Layla.',
   'lead': 'MOONTON Games startete am 4. September 2026 ALL IN, die Kampagne zum zehnjährigen Jubiläum von Mobile Legends: Bang Bang.',
   'new': ['Pass zum 10. Jubiläum (4. September – 1. November): neuer Epic-Skin für Nana, Epic-Skin-Auswahltruhe, zufällige Epic-Skin-Truhe und ein kostenloser Jubiläums-Skin für zurückkehrende Spieler.',
           'Anniversary Gala Weekend (25. September – 11. Oktober): Zugriff auf 265 Skins, Battle-Pass-EP und Premium-Skin-Fragmente.',
           'Layla’s Stellar Gala (9. Oktober – 19. November): Laylas neuer Collector-Skin über das Minispiel „Starfall Breakout“.',
           'MOONTON nennt über 1,5 Milliarden Installationen und 110 Millionen monatlich aktive Spieler.'],
   'impact': 'Collector- und Legend-Skins gehören zu den am häufigsten genannten Werttreibern von Mobile-Legends-Konten; gratis verteilte oder Test-Skins nicht.'},
  'bs-aug': {
   'title': 'Brawl Stars: mythische Brawler Cosmo und Vince; der Starr-Pfad wird zu Brawler Blast',
   'desc': 'Supercells Versionshinweise für August 2026 (1. September) bringen zwei mythische Brawler, machen aus dem Starr-Pfad Brawler Blast mit neuen Credit-Kosten und benennen Ultra-Legendär in Ultra um.',
   'lead': 'Supercell veröffentlichte die Versionshinweise zum Brawl-Stars-Update August 2026 am 1. September 2026.',
   'new': ['Zwei neue mythische Brawler: Cosmo (Kontrolle) und Vince (Schadensverursacher).',
           'Neue Hyperladungen für Nori und Wendy.',
           'Der Starr-Pfad wird zu „Brawler Blast“: Credits fließen jetzt in Freischaltungen nach Seltenheit – Selten 160, Super selten 430, Episch 925, Mythisch 1.900, Legendär 3.800, Ultra 5.500.',
           'Die Seltenheit „Ultra-Legendär“ heißt jetzt „Ultra“. Dazu die Saison Royal Academy und ein monatslanges Brawl-O-Ween-Event.'],
   'impact': 'Unser Brawl-Stars-Rechner nutzt die Zahl der Brawler, Hyperladungen und Trophäen. Zwei weitere mythische Brawler erhöhen die Zahl der Brawler, die eine vollständige Sammlung braucht.'},
  'coc-aug': {
   'title': 'Clash of Clans August-Update: Diggy Level 11–15 und Goldpass ab Rathaus 3',
   'desc': 'Supercells August-Update 2026 (30. August) bringt Diggy Level 11–15 und neue Superladungen auf Rathaus 18, schafft den Starterpass ab und öffnet den Goldpass ab Rathaus 3.',
   'lead': 'Supercell veröffentlichte das Clash-of-Clans-August-Update am 30. August 2026.',
   'new': ['Rathaus 18: Das Haustier Diggy erhält Level 11–15; Bauarbeiterhütte und Monolith bekommen neue Superladungsstufen.',
           'Der Starterpass entfällt: Saisonherausforderungen und Goldpass gibt es jetzt ab Rathaus 3, Belohnungen skalieren mit dem Rathauslevel.',
           'Der Ruinenritter verliert keine Lebenspunkte mehr mit der Zeit; die Ruinenhexe beschwört 10 statt 8 Ruinenritter.',
           'Die Modifikatoren der Clankriegsliga in den Titan-Ligen wurden angepasst.'],
   'impact': 'Rathauslevel sowie Helden- und Haustierlevel bestimmen laut unserer Recherche den Wert von Clash-of-Clans-Konten. Neue Höchstlevel auf Rathaus 18 bedeuten, dass ein „maximiertes“ Konto jetzt mehr Upgrades braucht als vor dem Update.'},
  'fn-c7s4': {
   'title': 'Fortnite Kapitel 7 Saison 4 „Override“: Sonic-Battle-Pass und KINGDOM-HEARTS-Crossover',
   'desc': 'Epics Saison „Override“ (Kapitel 7, Saison 4) bringt Override-Konsolen, einen Battle Pass für 800 V-Bucks mit Sonic the Hedgehog an der Spitze und Crossovers wie KINGDOM HEARTS.',
   'lead': 'Fortnites Kapitel 7 Saison 4 heißt „Override“. Epic beschreibt eine Saison voller Gaming-Crossovers und Regeländerungen für das ganze Match.',
   'new': ['Override-Konsolen tauchen in jedem Match auf und lassen Spieler die Regeln für den ganzen Server ändern.',
           'Der Battle Pass kostet 800 V-Bucks und wird von Sonic the Hedgehog angeführt, dazu kommt Tails als Sidekick.',
           'Wer den Pass vor dem 27. August um 23:59 Uhr (US-Ostküstenzeit) kaufte, erhielt das Outfit Infiltrator Grace Crowne als Bonus zur Startwoche.',
           'Crossovers der Saison: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot und Spyro the Dragon; zu den Waffen gehören Midas’ Masterpiece und Mega Mans Mega Buster.'],
   'impact': 'Outfits, die es nur für begrenzte Zeit gab – etwa ein Bonus zur Startwoche –, unterscheiden seltene Fortnite-Spinde von gewöhnlichen. Battle-Pass-Outfits bleiben an ihre Saison gebunden.'},
 }},
}
