# News batch 4: ja, ko, zh, th (from news_text_b4_en.py, facts unchanged)
TEXT = {
'ja': {'a': {
 'ml-asiad': {
  'title': 'アジア競技大会のMobile Legends：ミャンマーがインドネシアに4–0で勝利し、MLBB初の金メダル',
  'desc': 'MOONTONは2026年10月1日、愛知・名古屋2026のMobile Legends: Bang Bangでミャンマーがグランドファイナルでインドネシアを4–0で下し、アジア競技大会初の金メダルを獲得したと発表しました。',
  'lead': 'MOONTON Gamesは2026年10月1日、Mobile Legends: Bang Bangがアジア競技大会の正式メダル種目として初めて行われた大会の結果を発表しました。',
  'new': ['ミャンマーはAichi Sky Expoでのグランドファイナルでインドネシアに4–0で勝利し、MLBBでアジア競技大会初の金メダリストになりました。',
          '銀メダルはインドネシア、銅メダルはマレーシアとモンゴルです。',
          '予選ラウンドから22の国内オリンピック委員会が参加し、12チームがメインステージに進みました。',
          '今後の日程はMLBB Championship TourとM8世界選手権で、M8の決勝はトルコのイスタンブールで行われます。'],
  'impact': 'eスポーツの結果は既存アカウントの価値を変えません。当サイトの調査では、Mobile Legendsの価値を決めるのは引き続きスキン、ヒーロー、アカウントの進行度です。'},
 'mc-drop4': {
  'title': 'マイクラ2026年最後のゲームドロップがテスト開始：氷の洞窟、frostbite、ice balls',
  'desc': 'Mojangは2026年9月30日、2026年最後のゲームドロップのテストを開始しました。氷の洞窟、凍ったゾンビの亜種frostbite、ice balls、氷の結晶、つららが登場します。',
  'lead': 'Mojang Studiosは2026年9月30日、2026年最後のMinecraftゲームドロップのテストを開始しました。',
  'new': ['氷の結晶（ice crystals）とつらら（icicles）で飾られた新しい氷の洞窟。つららは壊れやすいとされています。',
          '新モブのfrostbite（凍ったゾンビの亜種）はice ballsを投げます。MojangはFreezingのポーションにも触れています。',
          '9月30日の最初のテスト版はBedrock Editionのpreview/betaです。記事ではMinecraft LauncherでJava Editionのスナップショットを有効にする方法も説明しています。',
          'Mojangはテスト版がワールドを破損させる可能性があるとして、バックアップか別フォルダの使用を呼びかけています。'],
  'impact': 'Minecraftアカウントの価値はアカウントの種類（JavaかBedrock）、ユーザー名、マントで決まり、ゲーム内コンテンツでは決まりません。こうしたアップデートはプレイヤーができることを変えますが、アカウントの価値は変えません。'},
 'cr-bal-oct': {
  'title': 'クラロワ10月のバランス調整：Hero Ice WizardとMinion Giantが弱体化、Lava Houndが強化',
  'desc': 'Supercellは2026年10月6日のバランス調整を公開しました。Hero Ice Wizardのフリーズダメージ89 → 46、Minion Giantの攻撃速度1.5秒 → 1.7秒、Lava Houndのダメージ53 → 71、Golden Knightは調整。',
  'lead': 'Supercellはクラッシュ・ロワイヤルの2026年10月6日のバランス調整を公開しました。',
  'new': ['弱体化：Hero Ice Wizardのフリーズダメージ89 → 46、Cannon Evolutionの連射ダメージ281 → 261、Barbarian Barrelのダメージ232 → 215、Minion Giantの攻撃速度1.5秒 → 1.7秒、Royal GhostのHP 1210 → 1152。',
          'Elixir Collector：稼働時間1分33秒 → 1分50秒、生産速度13秒 → 15秒。',
          '強化：Lava Houndのダメージ53 → 71（攻撃速度1.3秒 → 1.5秒）、Ram Riderのダメージ250 → 271、Wall Breakersのダメージ281 → 302、X-Bowのダメージ58 → 61、Three MusketeersのHP 883 → 906。',
          '調整：Golden Knightのダメージ161 → 168、ダッシュ射程5.5 → 5マス。Supercellは数値がレベル11基準であると説明しています。'],
  'impact': 'バランス調整は強いデッキを変えますが、アカウントが持つ内容は変えません。当サイトの調査では、キングタワーのレベルとカードレベルが引き続き主な価値要因です。'},
}},
'ko': {'a': {
 'ml-asiad': {
  'title': '아시안게임 Mobile Legends: 미얀마, 인도네시아를 4–0으로 꺾고 첫 MLBB 금메달',
  'desc': 'MOONTON은 2026년 10월 1일, 아이치·나고야 2026 Mobile Legends: Bang Bang에서 미얀마가 그랜드 파이널에서 인도네시아를 4–0으로 이기고 아시안게임 첫 금메달을 땄다고 밝혔습니다.',
  'lead': 'MOONTON Games는 2026년 10월 1일 Mobile Legends: Bang Bang이 아시안게임 정식 메달 종목으로 처음 치러진 대회의 결과를 발표했습니다.',
  'new': ['미얀마는 Aichi Sky Expo에서 열린 그랜드 파이널에서 인도네시아를 4–0으로 이기고 MLBB 첫 아시안게임 금메달리스트가 되었습니다.',
          '은메달은 인도네시아, 동메달은 말레이시아와 몽골이 차지했습니다.',
          '예선 라운드부터 22개 국가올림픽위원회가 참가했고, 12개 팀이 메인 스테이지에 올랐습니다.',
          '다음 일정은 MLBB Championship Tour와 M8 월드 챔피언십이며, M8 결승은 튀르키예 이스탄불에서 열립니다.'],
  'impact': 'e스포츠 결과는 기존 계정의 가치를 바꾸지 않습니다. 저희 조사에서는 스킨, 영웅, 계정 진행도가 여전히 Mobile Legends 가치를 좌우합니다.'},
 'mc-drop4': {
  'title': '마인크래프트 2026년 마지막 게임 드롭 테스트 시작: 얼음 동굴, frostbite, ice balls',
  'desc': 'Mojang은 2026년 9월 30일 2026년 마지막 게임 드롭의 테스트를 시작했습니다. 얼음 동굴, 얼어붙은 좀비 변종 frostbite, ice balls, 얼음 결정, 고드름이 나옵니다.',
  'lead': 'Mojang Studios는 2026년 9월 30일 2026년 마지막 Minecraft 게임 드롭의 테스트를 시작했습니다.',
  'new': ['얼음 결정(ice crystals)과 고드름(icicles)으로 꾸며진 새 얼음 동굴. 고드름은 깨지기 쉽습니다.',
          '새 몹 frostbite(얼어붙은 좀비 변종)는 ice balls를 던집니다. Mojang은 Freezing 물약도 언급했습니다.',
          '9월 30일의 첫 테스트 빌드는 Bedrock Edition의 preview/beta입니다. 게시글은 Minecraft Launcher에서 Java Edition 스냅샷을 켜는 방법도 설명합니다.',
          'Mojang은 테스트 버전이 월드를 손상시킬 수 있다며 백업하거나 별도 폴더를 쓰라고 안내합니다.'],
  'impact': 'Minecraft 계정의 가치는 계정 유형(Java 또는 Bedrock), 사용자 이름, 망토로 정해지며 게임 내 콘텐츠로 정해지지 않습니다. 이런 업데이트는 플레이어가 할 수 있는 일을 바꿀 뿐, 계정의 가치를 바꾸지 않습니다.'},
 'cr-bal-oct': {
  'title': '클래시 로얄 10월 밸런스 변경: Hero Ice Wizard와 Minion Giant 너프, Lava Hound 버프',
  'desc': 'Supercell은 2026년 10월 6일 밸런스 업데이트를 공개했습니다. Hero Ice Wizard 빙결 피해 89 → 46, Minion Giant 공격 속도 1.5초 → 1.7초, Lava Hound 피해 53 → 71, Golden Knight 리워크.',
  'lead': 'Supercell은 클래시 로얄의 2026년 10월 6일 밸런스 업데이트를 공개했습니다.',
  'new': ['너프: Hero Ice Wizard 빙결 피해 89 → 46, Cannon Evolution 연사 피해 281 → 261, Barbarian Barrel 피해 232 → 215, Minion Giant 공격 속도 1.5초 → 1.7초, Royal Ghost 체력 1210 → 1152.',
          'Elixir Collector: 지속 시간 1분 33초 → 1분 50초, 생산 속도 13초 → 15초.',
          '버프: Lava Hound 피해 53 → 71(공격 속도 1.3초 → 1.5초), Ram Rider 피해 250 → 271, Wall Breakers 피해 281 → 302, X-Bow 피해 58 → 61, Three Musketeers 체력 883 → 906.',
          '리워크: Golden Knight 피해 161 → 168, 돌진 사거리 5.5 → 5타일. Supercell은 수치가 레벨 11 기준이라고 밝혔습니다.'],
  'impact': '밸런스 변경은 어떤 덱이 강한지를 바꿀 뿐, 계정이 가진 내용을 바꾸지 않습니다. 저희 조사에서는 킹 타워 레벨과 카드 레벨이 여전히 주요 가치 요인입니다.'},
}},
'zh': {'a': {
 'ml-asiad': {
  'title': '亚运会 Mobile Legends：缅甸 4–0 击败印度尼西亚，夺得首枚 MLBB 金牌',
  'desc': 'MOONTON 于 2026 年 10 月 1 日宣布：在爱知·名古屋 2026 亚运会 Mobile Legends: Bang Bang 项目中，缅甸在总决赛以 4–0 击败印度尼西亚，夺得该项目首枚亚运金牌。',
  'lead': '2026 年 10 月 1 日，MOONTON Games 公布了 Mobile Legends: Bang Bang 首次作为亚运会正式奖牌项目的比赛结果。',
  'new': ['缅甸在 Aichi Sky Expo 举行的总决赛中以 4–0 击败印度尼西亚，成为 MLBB 首位亚运会金牌得主。',
          '印度尼西亚获得银牌；马来西亚和蒙古获得铜牌。',
          '从预选赛起共有 22 个国家（地区）奥委会参赛，12 支队伍晋级正赛。',
          '接下来的赛程是 MLBB Championship Tour 和 M8 世界锦标赛，M8 决赛将在土耳其伊斯坦布尔举行。'],
  'impact': '电竞赛果不会改变现有账号的价值。根据我们的研究，皮肤、英雄和账号进度仍是决定 Mobile Legends 价值的因素。'},
 'mc-drop4': {
  'title': 'Minecraft 2026 年最后一次游戏更新开始测试：冰洞、frostbite 与 ice balls',
  'desc': 'Mojang 于 2026 年 9 月 30 日开启 2026 年最后一次 game drop 的测试：冰洞、名为 frostbite 的冰冻僵尸变种、ice balls、冰晶和冰锥。',
  'lead': '2026 年 9 月 30 日，Mojang Studios 开启了 2026 年最后一次 Minecraft game drop 的测试。',
  'new': ['新的冰洞，以冰晶（ice crystals）和冰锥（icicles）装饰；冰锥很容易碎。',
          '新生物 frostbite（冰冻僵尸变种）会投掷 ice balls；Mojang 还提到了 Freezing 药水。',
          '9 月 30 日的首个测试版本是 Bedrock Edition 的 preview/beta；文章还说明了如何在 Minecraft Launcher 中启用 Java Edition 的 snapshot。',
          'Mojang 提醒测试版本可能损坏存档，建议玩家备份或使用单独的文件夹。'],
  'impact': 'Minecraft 账号的价值取决于账号类型（Java 或 Bedrock）、用户名和披风，而不是游戏内内容。这类更新改变的是玩家能做的事，而不是账号的价值。'},
 'cr-bal-oct': {
  'title': '皇室战争 10 月平衡性调整：Hero Ice Wizard 与 Minion Giant 被削弱，Lava Hound 获得加强',
  'desc': 'Supercell 公布了 2026 年 10 月 6 日的平衡性更新：Hero Ice Wizard 冰冻伤害 89 → 46，Minion Giant 攻击速度 1.5 秒 → 1.7 秒，Lava Hound 伤害 53 → 71，Golden Knight 重做。',
  'lead': 'Supercell 公布了《皇室战争》2026 年 10 月 6 日的平衡性更新。',
  'new': ['削弱：Hero Ice Wizard 冰冻伤害 89 → 46；Cannon Evolution 齐射伤害 281 → 261；Barbarian Barrel 伤害 232 → 215；Minion Giant 攻击速度 1.5 秒 → 1.7 秒；Royal Ghost 生命值 1210 → 1152。',
          'Elixir Collector：存在时间 1 分 33 秒 → 1 分 50 秒，生产速度 13 秒 → 15 秒。',
          '加强：Lava Hound 伤害 53 → 71（攻击速度 1.3 秒 → 1.5 秒）；Ram Rider 伤害 250 → 271；Wall Breakers 伤害 281 → 302；X-Bow 伤害 58 → 61；Three Musketeers 生命值 883 → 906。',
          '重做：Golden Knight 伤害 161 → 168，冲刺距离 5.5 → 5 格。Supercell 说明以上数值均按 11 级计算。'],
  'impact': '平衡性调整改变的是哪些卡组更强，而不是账号里有什么。根据我们的研究，国王塔等级和卡牌等级仍是主要的价值因素。'},
}},
'th': {'a': {
 'ml-asiad': {
  'title': 'Mobile Legends ในเอเชียนเกมส์: เมียนมาคว้าทอง MLBB แรก ชนะอินโดนีเซีย 4–0',
  'desc': 'MOONTON แจ้งเมื่อ 1 ตุลาคม 2026 ว่าเมียนมาคว้าเหรียญทองเอเชียนเกมส์เหรียญแรกของ Mobile Legends: Bang Bang ที่ไอจิ-นาโกย่า 2026 หลังชนะอินโดนีเซีย 4–0 ในรอบชิงชนะเลิศ',
  'lead': 'เมื่อวันที่ 1 ตุลาคม 2026 MOONTON Games ประกาศผลการแข่งขัน Mobile Legends: Bang Bang ครั้งแรกในฐานะกีฬาชิงเหรียญอย่างเป็นทางการของเอเชียนเกมส์',
  'new': ['เมียนมาชนะอินโดนีเซีย 4–0 ในรอบชิงชนะเลิศที่ Aichi Sky Expo และเป็นเจ้าของเหรียญทองเอเชียนเกมส์คนแรกของ MLBB',
          'อินโดนีเซียได้เหรียญเงิน ส่วนมาเลเซียและมองโกเลียได้เหรียญทองแดง',
          'มีคณะกรรมการโอลิมปิกแห่งชาติ 22 ชาติเข้าร่วมตั้งแต่รอบคัดเลือกเบื้องต้น และ 12 ทีมผ่านเข้าสู่รอบหลัก',
          'รายการต่อไปในปฏิทินคือ MLBB Championship Tour และ M8 World Championship โดยรอบชิงของ M8 จะจัดที่อิสตันบูล ประเทศตุรกี'],
  'impact': 'ผลการแข่งขันอีสปอร์ตไม่ได้เปลี่ยนมูลค่าของบัญชีที่มีอยู่ จากการวิจัยของเรา สกิน ฮีโร่ และความคืบหน้าของบัญชียังคงเป็นสิ่งที่กำหนดมูลค่าใน Mobile Legends'},
 'mc-drop4': {
  'title': 'เกมดรอปสุดท้ายของ Minecraft ปี 2026 เข้าสู่ช่วงทดสอบ: ถ้ำน้ำแข็ง, frostbite และ ice balls',
  'desc': 'Mojang เปิดทดสอบเกมดรอปสุดท้ายของปี 2026 เมื่อ 30 กันยายน 2026: ถ้ำน้ำแข็ง ซอมบี้แช่แข็งชื่อ frostbite, ice balls ผลึกน้ำแข็ง และแท่งน้ำแข็งย้อย',
  'lead': 'เมื่อวันที่ 30 กันยายน 2026 Mojang Studios เปิดทดสอบเกมดรอปสุดท้ายของ Minecraft ประจำปี 2026',
  'new': ['ถ้ำน้ำแข็งใหม่ที่ประดับด้วยผลึกน้ำแข็ง (ice crystals) และแท่งน้ำแข็งย้อย (icicles) โดยแท่งน้ำแข็งย้อยแตกง่าย',
          'ม็อบใหม่ frostbite (ซอมบี้แช่แข็ง) ขว้าง ice balls และ Mojang ยังพูดถึงยา Freezing ด้วย',
          'เวอร์ชันทดสอบแรกเมื่อ 30 กันยายนเป็น preview/beta ของ Bedrock Edition บทความยังอธิบายวิธีเปิดใช้ snapshot ของ Java Edition ใน Minecraft Launcher',
          'Mojang เตือนว่าเวอร์ชันทดสอบอาจทำให้โลกเสียหาย และขอให้สำรองข้อมูลหรือใช้โฟลเดอร์แยก'],
  'impact': 'บัญชี Minecraft ถูกประเมินจากประเภทบัญชี (Java หรือ Bedrock) ชื่อผู้ใช้ และผ้าคลุม ไม่ใช่จากเนื้อหาในเกม อัปเดตแบบนี้เปลี่ยนสิ่งที่ผู้เล่นทำได้ ไม่ได้เปลี่ยนมูลค่าของบัญชี'},
 'cr-bal-oct': {
  'title': 'ปรับสมดุล Clash Royale เดือนตุลาคม: Hero Ice Wizard และ Minion Giant ถูกเนิร์ฟ, Lava Hound ได้บัฟ',
  'desc': 'Supercell เผยอัปเดตสมดุลวันที่ 6 ตุลาคม 2026: ดาเมจแช่แข็งของ Hero Ice Wizard 89 → 46, ความเร็วโจมตีของ Minion Giant 1.5 วิ → 1.7 วิ, ดาเมจ Lava Hound 53 → 71 และ Golden Knight ถูกปรับใหม่',
  'lead': 'Supercell เผยอัปเดตสมดุลของ Clash Royale ประจำวันที่ 6 ตุลาคม 2026',
  'new': ['เนิร์ฟ: ดาเมจแช่แข็งของ Hero Ice Wizard 89 → 46; ดาเมจระดมยิงของ Cannon Evolution 281 → 261; ดาเมจ Barbarian Barrel 232 → 215; ความเร็วโจมตีของ Minion Giant 1.5 วิ → 1.7 วิ; พลังชีวิต Royal Ghost 1210 → 1152',
          'Elixir Collector: อายุการใช้งาน 1 นาที 33 วิ → 1 นาที 50 วิ, ความเร็วการผลิต 13 วิ → 15 วิ',
          'บัฟ: ดาเมจ Lava Hound 53 → 71 (ความเร็วโจมตี 1.3 วิ → 1.5 วิ); ดาเมจ Ram Rider 250 → 271; ดาเมจ Wall Breakers 281 → 302; ดาเมจ X-Bow 58 → 61; พลังชีวิต Three Musketeers 883 → 906',
          'ปรับใหม่: ดาเมจ Golden Knight 161 → 168, ระยะพุ่ง 5.5 → 5 ช่อง Supercell ระบุว่าตัวเลขคิดที่เลเวล 11'],
  'impact': 'การปรับสมดุลเปลี่ยนว่าเด็คไหนแข็งแกร่ง ไม่ได้เปลี่ยนสิ่งที่บัญชีมี จากการวิจัยของเรา เลเวล King Tower และเลเวลการ์ดยังคงเป็นปัจจัยหลักของมูลค่า'},
}},
}
