# News translations: kk, tk (from news_data.py 'en', facts unchanged)
TEXT = {
'kk': {
 'ui': {
  'news': 'Жаңалықтар', 'news_title': 'Аккаунт құнына әсер ететін ойын жаңалықтары',
  'news_lead': 'Ойын баспагерлерінің ресми жаңартулары — әрқайсысы баспагердің өз хабарландыруымен салыстырылған, аккаунт құны үшін не білдіретіні қысқаша түсіндірілген.',
  'game_title': '{game} жаңалықтары', 'game_lead': 'Аккаунт құнына әсер ететін ресми {game} жаңартулары. Әр мақалада баспагер хабарландыруына сілтеме бар.',
  'published': 'Жарияланды', 'source': 'Ресми дереккөз', 'by_on': '{pub}, {date}', 'whats_new': 'Не жаңа',
  'impact': 'Аккаунт құны үшін не білдіреді', 'more': 'Басқа {game} жаңалықтары', 'all': 'Барлық жаңалықтар',
  'calc': '{game}: құн калькуляторы және нарық есебі', 'read': 'Оқу', 'latest': '{game} соңғы жаңалықтары',
  'note': 'GameAccountValue аккаунттарды сатып алмайды, сатпайды және делдал болмайды. Жаңалықтар тек ақпарат үшін баспагерлер хабарландыруларынан қысқаша берілген.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna мен Vodyanitsa келді, мерейтой сыйлықтары расталды',
   'desc': '«A Rekviem for the Underworld» 7.1 нұсқасы 2026 жылғы 23 қыркүйекте екі жаңа 5 жұлдызды кейіпкермен, екі 5 жұлдызды қарумен және алтыншы мерейтой сыйлықтарымен шықты.',
   'lead': 'HoYoverse 2026 жылғы 23 қыркүйекте 7.1 нұсқасын — «A Rekviem for the Underworld»-ты шығарды; бұл жаңарту Genshin Impact-тің алтыншы мерейтойына да тура келді.',
   'new': ['Екі жаңа 5 жұлдызды кейіпкер: Vesna (Anemo, семсер) және Vodyanitsa (Hydro, катализатор).',
           'Жаңа қарулар: Beyond the Chrysalis (5★ семсер), Hymn of the Maelstrom (5★ катализатор) және New Bough (4★ семсер).',
           'HoYoverse жариялаған мерейтой сыйлықтары: шақыруға екі 5 жұлдызды кейіпкер, Intertwined Fate ×10, Primogem ×1 600 және Genesis Crystal бірінші толтыру бонусын қалпына келтіру.',
           'Жаңартуға арналған техникалық жұмыстар 23 қыркүйекте сағат 06:00-де (UTC+8) басталды.'],
   'impact': 'Біздің зерттеуіміз бойынша шектеулі 5 жұлдызды кейіпкерлер саны, олардың шоқжұлдыздары мен арнайы қарулары Genshin аккаунты құнының негізгі факторларының бірі. Мерейтойда бәріне тегін берілетін кейіпкерлер аккаунтты шектеулі баннер кейіпкерлеріндей ерекше етпейді.'},
  'mc-live': {
   'title': 'Minecraft Live: 14 жылдан астам уақыттағы алғашқы жаңа өлшем The Sift Java мен Bedrock-қа келеді',
   'desc': '2026 жылғы 26 қыркүйектегі Minecraft Live келесі жылы Java мен Bedrock-қа қосылатын төртінші өлшем The Sift-ті, сондай-ақ Dungeons II мен Wilderness Bound жаңартуын таныстырды.',
   'lead': '2026 жылғы 26 қыркүйектегі Minecraft Live-та Mojang Studios ойынның төртінші өлшемі The Sift келесі жылы Minecraft Java және Bedrock Edition-ға қосылатынын жариялады.',
   'new': ['The Sift — 14 жылдан астам уақыттағы алғашқы жаңа өлшем; ол Overworld, Nether және End қатарына қосылады.',
           'Ол алғаш Minecraft Dungeons II-де пайда болады; Mojang оның шығу күнін 2026 жылғы 29 қыркүйек деп белгіледі.',
           'Тақырыптық аттракцион Minecraft World 2027 жылы Лондонда ашылады.',
           'Wilderness Bound жаңартуы 15 қыркүйекте шықты: теңбіл орман, сабан төсектер, тастанды лагерьлер және көпшіктер.'],
   'impact': 'Minecraft аккаунттары ойын мазмұнымен емес, түрімен (Java немесе Bedrock), пайдаланушы атымен және плащтарымен бағаланады. Мұндай жаңартулар ойыншылар не істей алатынын өзгертеді, аккаунт құнын емес.'},
  'rbx-hunt': {
   'title': 'Roblox 20 «The Hunt»: шектеулі UGC заттар және Roblox Plus эксклюзивтері (17–28 қыркүйек)',
   'desc': 'The Hunt: Roblox 20 2026 жылғы 17–28 қыркүйекте UGC сыйлықтарымен, шектеулі шығарылымдағы UGC заттармен және Roblox Plus жазылушыларына арналған үш эксклюзив затпен өтті.',
   'lead': 'Roblox 20 жылдығын бүкіл платформада өткен The Hunt: Roblox 20 іс-шарасымен атап өтті; ол 2026 жылғы 17–28 қыркүйекте болды.',
   'new': ['Ойыншылар «Year Zero»-дан бастап, әр жылға бір тапсырмамен Roblox-тың 20 жылдық тарихынан өтті; барлық 20 жылды аяқтау тағы 20 ойыны бар «Year Infinity»-ді ашты.',
           'Тапсырмалар үшін UGC заттар берілді, ал іс-шара кезінде шектеулі шығарылымдағы UGC заттар болды.',
           'Roblox Plus жазылушылары үш эксклюзив виртуалды зат алды және іс-шарадан кейін де Classic қолданба тақырыбын, классикалық аватар фонын және профиль жақтауын сақтап қалады.',
           'Іс-шара кезінде Classic қолданба тақырыбы бәріне тегін болды.'],
   'impact': 'Тек іс-шара кезінде алуға болатын заттар — бағалау назар аударатын нәрселердің бірі. Roblox хабарландыруда бұл заттардың атауын келтірмеді, сондықтан нақты сату хабарландырулары пайда болмайынша бұл сайт оларға баға қоймайды.'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox авторлары бір жылда шамамен 1,7 млрд доллар тапты; Roblox Wallet жарияланды',
   'desc': 'RDC 2026-да Roblox авторлардың 12 айда шамамен 1,7 млрд доллар тапқанын хабарлап, төлемдерге арналған Roblox Wallet пен Roblox Card-ты жариялады.',
   'lead': 'Roblox өзінің RDC 2026 әзірлеушілер конференциясында (2026 жылғы 11 қыркүйектегі хабарландыру) авторлар табысының сандарын және жаңа төлем құралдарын ұсынды.',
   'new': ['DevEx 2013 жылы іске қосылғаннан бері авторлар 5 млрд доллардан астам, ал 2026 жылғы 30 маусымға дейінгі 12 айда шамамен 1,7 млрд доллар тапқан.',
           'Roblox Plus ынталандырулары алғашқы төрт айда (2026 жылғы 17 тамызға дейін) авторларға 300 миллионнан астам Robux табыс әкелді.',
           'Airwallex US-пен бірге жүргізілетін төлем шоты Roblox Wallet нақты валютада күн сайын төлейді — алдымен 2026 жылдың соңында АҚШ-тағы талаптарға сай 18 жастан асқан тәуелсіз авторлар үшін, 2027 жылы халықаралық деңгейде.',
           'Wallet-пен байланысқан Roblox Card 2027 жылдан жоспарланған.'],
   'impact': 'Бұл өзгерістер ойыншылар аккаунттарына емес, авторларға төлемдерге қатысты: хабарландыру Robux бағасын, шектеулі заттарды немесе саудаларды өзгертпеді. Roblox калькуляторымыз ескеретін нәрсе — бұрынғыдай Robux балансы мен шектеулі заттар.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: Clash Squad-қа төрт жаңа қару, Prime Diamond және Кентаны қайта өңдеу',
   'desc': 'Garena-ның OB55 патч жазбалары (2026 жылғы 10 қыркүйек) 1 қазаннан бастап Clash Squad-қа M7, Skorp, RPK және Hawk қосады, Prime Diamond енгізеді және Кентаны қайта өңдейді.',
   'lead': 'Garena Free Fire-дің OB55 патч жазбаларын 2026 жылғы 10 қыркүйекте жариялады; қару өзгерістері 1 қазаннан күшіне енеді.',
   'new': ['1 қазаннан бастап Clash Squad-тағы жаңа қарулар: M7 (1 600 CS Cash), Skorp (1 500), RPK (1 500) және Hawk (1 700).',
           'Prime Diamond: айлық шығынға қарай берілетін алмастар, кез келген толтырудан кейін келесі айда алуға болады.',
           'Кента толығымен қайта өңделді; Морзе, Луна және Укун баланс өзгерістерін алды.',
           '1 қазаннан бастап қару түріне қарай қозғалғыштық өзгереді: SMG жылдамырақ, снайпер және марксман мылтықтары баяуырақ.'],
   'impact': 'Free Fire калькуляторымыз алмас балансын және сирек жиынтықтарды ескереді. OB55 болашақ толтырулардың қалай марапатталатынын өзгертеді; аккаунттарда бұрыннан бар заттарды өзгертпейді.'},
  'cr-minion': {
   'title': 'Clash Royale «Minion Academy» маусымы: жаңа карта Minion Giant және Ice Wizard кейіпкері',
   'desc': 'Minion Academy маусымы (2026 жылғы 7 қыркүйек – 5 қазан) Minion Giant картасын, Ice Wizard кейіпкерін және 1 750 Minion Giant картасын беретін альбом іс-шарасын қосады.',
   'lead': 'Supercell 2026 жылғы 7 қыркүйектен 5 қазанға дейін жалғасатын Clash Royale «Minion Academy» маусымын бастады.',
   'new': ['Жаңа карта Minion Giant: ғимараттар мен мұнараларды нысанаға алатын ұшатын жеңіс картасы. Ол Academy Antics альбом іс-шарасы арқылы тегін беріледі және сандықтарда тек келесі маусымда шығады.',
           'Альбом іс-шарасы 1 750 Minion Giant картасын, эмоция және мұнара скинін береді.',
           'Жаңа кейіпкер: Ice Wizard — Pass Royale жолынан немесе 200 Hero Coin-ға.',
           'Іс-шаралар: 2v2 лигасы (7–21 қыркүйек), Princess Gambit әлемдік турнирі (21–26 қыркүйек) және Royale Shuffle (21 қыркүйек – 5 қазан). Ultimate Champion-дағы тең ойын енді жеңілістегі кубоктардың жартысындай ғана кубок алады.'],
   'impact': 'Тек іс-шара кезінде ұсынылатын мұнара скиндері мен эмоциялар Clash Royale коллекциясын ерекшелей түседі, бірақ негізгі құн факторлары — Патша мұнарасының деңгейі мен карталар деңгейі.'},
  'ml-10': {
   'title': 'Mobile Legends 10 жаста: ALL IN науқаны және Лейланың жаңа Collector скині',
   'desc': 'MOONTON-ның 10 жылдық ALL IN науқаны (2026 жылғы 4 қыркүйектен) Нанаға жаңа Epic скин, тегін скин сандықтарын және 9 қазаннан Лейланың Collector скинін әкеледі.',
   'lead': 'MOONTON Games 2026 жылғы 4 қыркүйекте Mobile Legends: Bang Bang-тың он жылдығына арналған ALL IN науқанын бастады.',
   'new': ['10 жылдық мереке пасы (4 қыркүйек – 1 қараша): Нанаға жаңа Epic скин, Epic скин таңдау сандығы, кездейсоқ Epic скин сандығы және оралған ойыншыларға тегін мерейтой скині.',
           'Anniversary Gala Weekend (25 қыркүйек – 11 қазан): 265 скинге қолжетімділік, Battle Pass EXP және Premium скин бөлшектері.',
           'Layla’s Stellar Gala (9 қазан – 19 қараша): «Starfall Breakout» мини-ойыны арқылы Лейланың жаңа Collector скині.',
           'MOONTON 1,5 миллиардтан астам орнату және айына 110 миллион белсенді ойыншы туралы хабарлайды.'],
   'impact': 'Collector және Legend скиндері — Mobile Legends аккаунттары құнының ең жиі аталатын факторларының бірі; тегін таратылған немесе сынақ скиндері олай емес.'},
  'bs-aug': {
   'title': 'Brawl Stars: Mythic бойшылар Cosmo мен Vince; Starr Road енді Brawler Blast',
   'desc': 'Supercell-дің 2026 жылғы тамыз жаңарту жазбалары (1 қыркүйек) екі Mythic бойшы қосады, Starr Road-ты жаңа кредит бағаларымен Brawler Blast-ке айналдырады және Ultra Legendary атауын Ultra деп өзгертеді.',
   'lead': 'Supercell Brawl Stars-тың 2026 жылғы тамыз жаңартуының жазбаларын 2026 жылғы 1 қыркүйекте жариялады.',
   'new': ['Екі жаңа Mythic бойшы: Cosmo (Controller) және Vince (Damage Dealer).',
           'Nori мен Wendy үшін жаңа Hypercharge-тер.',
           'Starr Road «Brawler Blast»-ке айналды: кредиттер енді сиректік бойынша ашуға жұмсалады — Rare 160, Super Rare 430, Epic 925, Mythic 1 900, Legendary 3 800, Ultra 5 500.',
           '«Ultra Legendary» сиректігі енді «Ultra» деп аталады. Сонымен қатар Royal Academy маусымы және бір айға созылатын Brawl-O-Ween іс-шарасы.'],
   'impact': 'Brawl Stars калькуляторымыз бойшылар санын, Hypercharge-терді және кубоктарды пайдаланады. Тағы екі Mythic толық коллекцияға қажет бойшылар санын арттырады.'},
  'coc-aug': {
   'title': 'Clash of Clans тамыз жаңартуы: Diggy 11–15 деңгейлері және Town Hall 3-тен Gold Pass',
   'desc': 'Supercell-дің 2026 жылғы тамыз жаңартуы (30 тамыз) Town Hall 18-де Diggy-дің 11–15 деңгейлерін және жаңа суперзарядтарды қосады, Starter Pass-ты алып тастап, Gold Pass-ты Town Hall 3-тен ашады.',
   'lead': 'Supercell Clash of Clans тамыз жаңартуын 2026 жылғы 30 тамызда шығарды.',
   'new': ['Town Hall 18: Diggy үй жануары 11–15 деңгейлерін алады; Builder’s Hut пен Monolith жаңа суперзаряд деңгейлерін алады.',
           'Starter Pass алынып тасталды: маусым сынақтары мен Gold Pass енді Town Hall 3-тен қолжетімді, сыйлықтар Town Hall деңгейіне қарай өзгереді.',
           'Ruin Knight енді уақыт өте денсаулығын жоғалтпайды; Ruin Witch 8 орнына 10 Ruin Knight шақырады.',
           'Titan лигаларындағы Clan War League модификаторлары өзгертілді.'],
   'impact': 'Біздің зерттеуіміз бойынша Clash of Clans аккаунтының құнын Town Hall деңгейі және батырлар мен үй жануарларының деңгейлері анықтайды. Town Hall 18-дегі жаңа ең жоғары деңгейлер «макс» аккаунтқа енді жаңартудан бұрынғыдан көбірек жақсарту керек екенін білдіреді.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 «Override»: Sonic бар Battle Pass және KINGDOM HEARTS-пен ынтымақтастық',
   'desc': 'Epic-тің «Override» маусымы (Chapter 7, Season 4) Override Console-дарды, Sonic the Hedgehog бастаған 800 V-Bucks-тық Battle Pass-ты және KINGDOM HEARTS сияқты ынтымақтастықтарды әкеледі.',
   'lead': 'Fortnite-тың Chapter 7 Season 4 маусымы «Override» деп аталады. Epic оны ойын ынтымақтастықтары мен бүкіл матч ережелерін өзгертуге құрылған маусым деп сипаттайды.',
   'new': ['Override Console-дар әр матчта пайда болады және бүкіл сервер ережелерін өзгертуге мүмкіндік береді.',
           'Battle Pass 800 V-Bucks тұрады, оның басты кейіпкері — Sonic the Hedgehog, жанында серігі Tails.',
           'Pass-ты 27 тамыз сағат 23:59-ға дейін (АҚШ шығыс уақыты) сатып алғандар іске қосу аптасының бонусы ретінде Infiltrator Grace Crowne киімін алды.',
           'Маусымдағы ынтымақтастықтар: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot және Spyro the Dragon; қарулар арасында Midas’ Masterpiece және Mega Man-ның Mega Buster-і бар.'],
   'impact': 'Тек шектеулі уақыт берілетін киімдер — мысалы, іске қосу аптасының бонусы — сирек Fortnite шкафтарын қарапайымдарынан ажыратады. Battle Pass киімдері өз маусымымен байланысты болып қалады.'},
 }},
'tk': {
 'ui': {
  'news': 'Täzelikler', 'news_title': 'Hasabyň gymmatyna täsir edýän oýun täzelikleri',
  'news_lead': 'Oýun neşirçileriniň resmi täzelenmeleri — her biri neşirçiniň öz bildirişi bilen deňeşdirildi we hasabyň gymmaty üçin näme aňladýandygy gysgaça düşündirildi.',
  'game_title': '{game} täzelikleri', 'game_lead': 'Hasabyň gymmatyna täsir edýän resmi {game} täzelenmeleri. Her makalada neşirçiniň bildirişine salgylanma bar.',
  'published': 'Çap edildi', 'source': 'Resmi çeşme', 'by_on': '{pub}, {date}', 'whats_new': 'Näme täze',
  'impact': 'Hasabyň gymmaty üçin näme aňladýar', 'more': 'Beýleki {game} täzelikleri', 'all': 'Ähli täzelikler',
  'calc': '{game}: gymmat kalkulýatory we bazar hasabaty', 'read': 'Oka', 'latest': 'Soňky {game} täzelikleri',
  'note': 'GameAccountValue hasaplary satyn almaýar, satmaýar we araçylyk etmeýär. Täzelikler diňe maglumat üçin neşirçileriň bildirişlerinden gysgaça berildi.'},
 'a': {
  'gi71': {
   'title': 'Genshin Impact 7.1: Vesna we Vodyanitsa geldi, ýubileý sowgatlary tassyklandy',
   'desc': '"A Rekviem for the Underworld" atly 7.1 wersiýasy 2026-njy ýylyň 23-nji sentýabrynda iki täze 5 ýyldyzly gahryman, iki 5 ýyldyzly ýarag we altynjy ýubileý sowgatlary bilen çykdy.',
   'lead': 'HoYoverse 2026-njy ýylyň 23-nji sentýabrynda 7.1 wersiýasyny — "A Rekviem for the Underworld"-y çykardy; bu täzelenme Genshin Impact-iň altynjy ýubileýine hem gabat geldi.',
   'new': ['Iki täze 5 ýyldyzly gahryman: Vesna (Anemo, gylyç) we Vodyanitsa (Hydro, katalizator).',
           'Täze ýaraglar: Beyond the Chrysalis (5★ gylyç), Hymn of the Maelstrom (5★ katalizator) we New Bough (4★ gylyç).',
           'HoYoverse-iň yglan eden ýubileý sowgatlary: çagyrmak üçin iki 5 ýyldyzly gahryman, Intertwined Fate ×10, Primogem ×1 600 we Genesis Crystal ilkinji doldurma bonusynyň täzeden başlanmagy.',
           'Täzelenme üçin tehniki işler 23-nji sentýabrda sagat 06:00-da (UTC+8) başlandy.'],
   'impact': 'Biziň gözlegimize görä, çäkli 5 ýyldyzly gahrymanlaryň sany, olaryň ýyldyz toparlary we aýratyn ýaraglary Genshin hasabynyň gymmatynyň esasy faktorlarynyň biridir. Ýubileýde hemmelere mugt berilýän gahrymanlar hasaby çäkli banner gahrymanlary ýaly aýratyn etmeýär.'},
  'mc-live': {
   'title': 'Minecraft Live: 14 ýyldan gowrak wagtyň ilkinji täze ölçegi The Sift Java we Bedrock-a gelýär',
   'desc': '2026-njy ýylyň 26-njy sentýabryndaky Minecraft Live indiki ýyl Java we Bedrock-a goşuljak dördünji ölçeg The Sift-i, şeýle hem Dungeons II-ni we Wilderness Bound täzelenmesini tanyşdyrdy.',
   'lead': '2026-njy ýylyň 26-njy sentýabryndaky Minecraft Live-da Mojang Studios oýnuň dördünji ölçegi The Sift-iň indiki ýyl Minecraft Java we Bedrock Edition-a goşuljakdygyny yglan etdi.',
   'new': ['The Sift — 14 ýyldan gowrak wagtyň ilkinji täze ölçegi; ol Overworld, Nether we End hataryna goşulýar.',
           'Ol ilkinji gezek Minecraft Dungeons II-de peýda bolýar; Mojang onuň çykyş senesini 2026-njy ýylyň 29-njy sentýabry diýip belledi.',
           'Tematiki attraksion Minecraft World 2027-nji ýylda Londonda açylýar.',
           'Wilderness Bound täzelenmesi 15-nji sentýabrda çykdy: tegmilli tokaý, saman düşekler, taşlanan lagerler we ýassyklar.'],
   'impact': 'Minecraft hasaplary oýun mazmunyna görä däl-de, görnüşine (Java ýa-da Bedrock), ulanyjy adyna we plaşlaryna görä bahalandyrylýar. Şeýle täzelenmeler oýunçylaryň näme edip biljekdigini üýtgedýär, hasabyň gymmatyny däl.'},
  'rbx-hunt': {
   'title': 'Roblox 20 "The Hunt": çäkli UGC zatlary we Roblox Plus üçin eksklýuziwler (17–28-nji sentýabr)',
   'desc': 'The Hunt: Roblox 20 2026-njy ýylyň 17–28-nji sentýabrynda UGC sowgatlary, çäkli neşirdäki UGC zatlary we Roblox Plus ýazylyjylary üçin üç eksklýuziw zat bilen geçdi.',
   'lead': 'Roblox 20 ýyllygyny ähli platformada geçen The Hunt: Roblox 20 çäresi bilen belledi; ol 2026-njy ýylyň 17–28-nji sentýabrynda boldy.',
   'new': ['Oýunçylar "Year Zero"-dan başlap, her ýyl üçin bir tabşyryk bilen Roblox-yň 20 ýyllyk taryhyndan geçdiler; ähli 20 ýyly tamamlamak ýene 20 oýunly "Year Infinity"-ni açdy.',
           'Tabşyryklar üçin UGC zatlary berildi, çäre dowamynda bolsa çäkli neşirdäki UGC zatlary hem bardy.',
           'Roblox Plus ýazylyjylary üç eksklýuziw wirtual zat aldylar we çäreden soň hem Classic programma temasyny, nusgawy awatar fonuny we profil çarçuwasyny saklaýarlar.',
           'Çäre dowamynda Classic programma temasy hemmeler üçin mugtdy.'],
   'impact': 'Diňe çäre wagtynda alyp bolýan zatlar bahalandyrmanyň üns berýän zatlarynyň biridir. Roblox bildirişde bu zatlaryň atlaryny görkezmedi, şonuň üçin hakyky satuw bildirişleri peýda bolýança bu saýt olara baha goýmaýar.'},
  'rbx-rdc': {
   'title': 'RDC 2026: Roblox döredijileri bir ýylda takmynan 1,7 mlrd dollar gazandy; Roblox Wallet yglan edildi',
   'desc': 'RDC 2026-da Roblox döredijileriň 12 aýda takmynan 1,7 mlrd dollar gazanandygyny habar berdi we tölegler üçin Roblox Wallet we Roblox Card-y yglan etdi.',
   'lead': 'Roblox özüniň RDC 2026 işläp düzüjiler konferensiýasynda (2026-njy ýylyň 11-nji sentýabryndaky bildiriş) döredijileriň girdeji sanlaryny we täze töleg gurallaryny hödürledi.',
   'new': ['DevEx 2013-nji ýylda işe girizilenden bäri döredijiler 5 mlrd dollardan gowrak, 2026-njy ýylyň 30-njy iýunyna çenli 12 aýda bolsa takmynan 1,7 mlrd dollar gazandylar.',
           'Roblox Plus höweslendirmeleri ilkinji dört aýda (2026-njy ýylyň 17-nji awgustyna çenli) döredijilere 300 milliondan gowrak Robux girdeji getirdi.',
           'Airwallex US bilen alnyp barylýan töleg hasaby Roblox Wallet hakyky pulda her gün töleg berer — ilki 2026-njy ýylyň ahyrynda ABŞ-daky talaplara laýyk gelýän 18 ýaşdan uly garaşsyz döredijiler üçin, 2027-nji ýylda halkara derejesinde.',
           'Wallet bilen baglanyşykly Roblox Card 2027-nji ýyldan meýilleşdirilýär.'],
   'impact': 'Bu üýtgeşmeler oýunçylaryň hasaplaryna däl-de, döredijilere tölegler bilen baglanyşykly: bildiriş Robux bahalaryny, çäkli zatlary ýa-da söwdany üýtgetmedi. Roblox kalkulýatorymyzyň hasaba alýan zady öňküsi ýaly Robux balansy we çäkli zatlardyr.'},
  'ff-ob55': {
   'title': 'Free Fire OB55: Clash Squad üçin dört täze ýarag, Prime Diamond we Kentanyň täzeden işlenmegi',
   'desc': 'Garena-nyň OB55 täzelenme belliklerine (2026-njy ýylyň 10-njy sentýabry) görä, 1-nji oktýabrdan Clash Squad-a M7, Skorp, RPK we Hawk goşulýar, Prime Diamond girizilýär we Kenta täzeden işlenýär.',
   'lead': 'Garena Free Fire-iň OB55 täzelenme belliklerini 2026-njy ýylyň 10-njy sentýabrynda çap etdi; ýarag üýtgeşmeleri 1-nji oktýabrdan güýje girýär.',
   'new': ['1-nji oktýabrdan Clash Squad-daky täze ýaraglar: M7 (1 600 CS Cash), Skorp (1 500), RPK (1 500) we Hawk (1 700).',
           'Prime Diamond: aýlyk çykdajylara görä berilýän almazlar, islendik doldurmadan soň indiki aýda alyp bolýar.',
           'Kenta doly täzeden işlendi; Morse, Luna we Wukong deňagramlylyk üýtgeşmelerini aldy.',
           '1-nji oktýabrdan ýarag görnüşine görä hereketlilik üýtgeýär: SMG-ler çaltrak, snaýper we marksman tüpeňleri haýalrak.'],
   'impact': 'Free Fire kalkulýatorymyz almaz balansyny we seýrek toplumlary hasaba alýar. OB55 geljekki doldurmalaryň nähili sylaglanjakdygyny üýtgedýär; hasaplarda eýýäm bar bolan zatlary üýtgetmeýär.'},
  'cr-minion': {
   'title': 'Clash Royale "Minion Academy" möwsümi: täze kart Minion Giant we Ice Wizard gahrymany',
   'desc': 'Minion Academy möwsümi (2026-njy ýylyň 7-nji sentýabry – 5-nji oktýabry) Minion Giant kartyny, Ice Wizard gahrymanyny we 1 750 Minion Giant kartyny berýän albom çäresini goşýar.',
   'lead': 'Supercell 2026-njy ýylyň 7-nji sentýabryndan 5-nji oktýabryna çenli dowam edýän Clash Royale "Minion Academy" möwsümini başlady.',
   'new': ['Täze kart Minion Giant: binalary we diňleri nyşana alýan uçýan ýeňiş karty. Ol Academy Antics albom çäresi arkaly mugt berilýär we sandyklarda diňe indiki möwsümde çykar.',
           'Albom çäresi 1 750 Minion Giant kartyny, bir emosiýany we diň skinini berýär.',
           'Täze gahryman: Ice Wizard — Pass Royale ýolundan ýa-da 200 Hero Coin-a.',
           'Çäreler: 2v2 ligasy (7–21-nji sentýabr), Princess Gambit dünýä ýaryşy (21–26-njy sentýabr) we Royale Shuffle (21-nji sentýabr – 5-nji oktýabr). Ultimate Champion-daky deňme-deň netije indi ýeňlişdäki kubogyň ýarysyny aýyrýar.'],
   'impact': 'Diňe çäre wagtynda hödürlenýän diň skinleri we emosiýalar Clash Royale kolleksiýasyny has aýratyn edýär, emma esasy gymmat faktorlary Patyşa diňiniň derejesi we kart derejeleri bolmagynda galýar.'},
  'ml-10': {
   'title': 'Mobile Legends 10 ýaşynda: ALL IN kampaniýasy we Laýlanyň täze Collector skini',
   'desc': 'MOONTON-yň 10 ýyllyk ALL IN kampaniýasy (2026-njy ýylyň 4-nji sentýabryndan) Nana üçin täze Epic skin, mugt skin sandyklaryny we 9-njy oktýabrdan Laýlanyň Collector skinini getirýär.',
   'lead': 'MOONTON Games 2026-njy ýylyň 4-nji sentýabrynda Mobile Legends: Bang Bang-yň on ýyllygy üçin ALL IN kampaniýasyny başlady.',
   'new': ['10 ýyllyk baýramçylyk pasy (4-nji sentýabr – 1-nji noýabr): Nana üçin täze Epic skin, Epic skin saýlama sandygy, tötänleýin Epic skin sandygy we gaýdyp gelen oýunçylar üçin mugt ýubileý skini.',
           'Anniversary Gala Weekend (25-nji sentýabr – 11-nji oktýabr): 265 skini ulanmak, Battle Pass EXP we Premium skin bölekleri.',
           'Layla’s Stellar Gala (9-njy oktýabr – 19-njy noýabr): "Starfall Breakout" mini-oýny arkaly Laýlanyň täze Collector skini.',
           'MOONTON 1,5 milliarddan gowrak gurnama we aýda 110 million işjeň oýunçy barada habar berýär.'],
   'impact': 'Collector we Legend skinleri Mobile Legends hasaplarynyň gymmatynyň iň köp agzalýan faktorlarynyň biridir; mugt paýlanan ýa-da synag skinleri beýle däl.'},
  'bs-aug': {
   'title': 'Brawl Stars: Mythic söweşijiler Cosmo we Vince; Starr Road indi Brawler Blast',
   'desc': 'Supercell-iň 2026-njy ýylyň awgust täzelenme bellikleri (1-nji sentýabr) iki Mythic söweşiji goşýar, Starr Road-y täze kredit bahalary bilen Brawler Blast-a öwürýär we Ultra Legendary adyny Ultra diýip üýtgedýär.',
   'lead': 'Supercell Brawl Stars-yň 2026-njy ýylyň awgust täzelenmesiniň belliklerini 2026-njy ýylyň 1-nji sentýabrynda çap etdi.',
   'new': ['Iki täze Mythic söweşiji: Cosmo (Controller) we Vince (Damage Dealer).',
           'Nori we Wendy üçin täze Hypercharge-lar.',
           'Starr Road "Brawler Blast"-a öwrüldi: kreditler indi seýreklige görä açmaga harçlanýar — Rare 160, Super Rare 430, Epic 925, Mythic 1 900, Legendary 3 800, Ultra 5 500.',
           '"Ultra Legendary" seýrekligi indi "Ultra" diýlip atlandyrylýar. Mundan başga-da, Royal Academy möwsümi we bir aý dowam edýän Brawl-O-Ween çäresi.'],
   'impact': 'Brawl Stars kalkulýatorymyz söweşijileriň sanyny, Hypercharge-lary we kuboklary ulanýar. Ýene iki Mythic doly kolleksiýa üçin zerur söweşijileriň sanyny artdyrýar.'},
  'coc-aug': {
   'title': 'Clash of Clans awgust täzelenmesi: Diggy 11–15-nji derejeler we Town Hall 3-den Gold Pass',
   'desc': 'Supercell-iň 2026-njy ýylyň awgust täzelenmesi (30-njy awgust) Town Hall 18-de Diggy-niň 11–15-nji derejelerini we täze superzarýadlary goşýar, Starter Pass-y ýatyrýar we Gold Pass-y Town Hall 3-den açýar.',
   'lead': 'Supercell Clash of Clans awgust täzelenmesini 2026-njy ýylyň 30-njy awgustynda çykardy.',
   'new': ['Town Hall 18: öý haýwany Diggy 11–15-nji derejeleri alýar; Builder’s Hut we Monolith täze superzarýad derejelerini alýar.',
           'Starter Pass ýatyryldy: möwsüm synaglary we Gold Pass indi Town Hall 3-den elýeterli, sylaglar Town Hall derejesine görä üýtgeýär.',
           'Ruin Knight indi wagtyň geçmegi bilen saglygyny ýitirmeýär; Ruin Witch 8-iň ýerine 10 Ruin Knight çagyrýar.',
           'Titan ligalaryndaky Clan War League modifikatorlary üýtgedildi.'],
   'impact': 'Biziň gözlegimizde Clash of Clans hasabynyň gymmatyny Town Hall derejesi hem-de gahrymanlaryň we öý haýwanlarynyň derejeleri kesgitleýär. Town Hall 18-däki täze iň ýokary derejeler "maks" hasabyň indi täzelenmeden öňkiden has köp gowulandyrmany talap edýändigini aňladýar.'},
  'fn-c7s4': {
   'title': 'Fortnite Chapter 7 Season 4 "Override": Sonic-li Battle Pass we KINGDOM HEARTS bilen hyzmatdaşlyk',
   'desc': 'Epic-iň "Override" möwsümi (Chapter 7, Season 4) Override Console-lary, Sonic the Hedgehog ýolbaşçylygyndaky 800 V-Bucks-lyk Battle Pass-y we KINGDOM HEARTS ýaly hyzmatdaşlyklary getirýär.',
   'lead': 'Fortnite-yň Chapter 7 Season 4 möwsümi "Override" diýlip atlandyrylýar. Epic ony oýun hyzmatdaşlyklaryna we tutuş oýnuň düzgünlerini üýtgetmäge gurlan möwsüm diýip häsiýetlendirýär.',
   'new': ['Override Console-lar her oýunda peýda bolýar we tutuş serweriň düzgünlerini üýtgetmäge mümkinçilik berýär.',
           'Battle Pass 800 V-Bucks durýar, onuň baş gahrymany Sonic the Hedgehog, ýanynda Tails ýoldaşy.',
           'Pass-y 27-nji awgust sagat 23:59-a çenli (ABŞ-nyň gündogar wagty) satyn alanlar işe girizmek hepdesiniň bonusy hökmünde Infiltrator Grace Crowne eşigini aldylar.',
           'Möwsümdäki hyzmatdaşlyklar: KINGDOM HEARTS, Pac-Man, Mega Man, Persona 5 Royal, Cyberpunk: Edgerunners, Crash Bandicoot we Spyro the Dragon; ýaraglaryň arasynda Midas’ Masterpiece we Mega Man-yň Mega Buster-i bar.'],
   'impact': 'Diňe çäkli wagt berilýän eşikler — meselem, işe girizmek hepdesiniň bonusy — seýrek Fortnite şkaflaryny adatylaryndan tapawutlandyrýar. Battle Pass eşikleri öz möwsümine bagly bolmagynda galýar.'},
 }},
}
