# News batch 2: it, pl (from news_text_b2_en.py, facts unchanged)
TEXT = {
'it': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II è uscito: la dimensione del Sift e l’Alto Consiglio degli Illager',
  'desc': 'Mojang ha pubblicato Minecraft Dungeons II il 29 settembre 2026 su Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch e Switch 2, con cooperativa fino a 4 giocatori.',
  'lead': 'Mojang Studios ha pubblicato Minecraft Dungeons II il 29 settembre 2026.',
  'new': ['Disponibile su Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch e Nintendo Switch 2.',
          'La storia mette i giocatori contro l’Alto Consiglio degli Illager: il Prime Enchanter, il Supreme Evoker e il Grand Illusioner.',
          'Si esplora una nuova dimensione, il Sift, che secondo Mojang arriverà anche in Minecraft Java e Bedrock il prossimo anno.',
          'Si gioca da soli o in cooperativa fino a 4 giocatori, online o sullo stesso schermo.'],
  'impact': 'Dungeons II è un gioco a parte. Gli account Minecraft Java e Bedrock si valutano ancora per tipo, nome utente e mantelli, quindi l’uscita non ne cambia il valore.'},
 'cr-mt-oct': {'title': 'Merge Tactics di Clash Royale: le novità di ottobre su Super, elisir e distintivi',
  'desc': 'Dal 1º ottobre 2026 la stagione 11 di Merge Tactics sposta i Super nel pool comune, riduce l’elisir per round da 5 a 4 e aggiunge skin di livello 5; i distintivi cambiano nella stagione 12.',
  'lead': 'Supercell ha annunciato le modifiche di ottobre della stagione 11 di Merge Tactics il 30 settembre 2026; valgono dal 1º ottobre.',
  'new': ['I Super non sono più truppe iniziali: finiscono nel pool comune, che tutti i giocatori si contendono.',
          'L’elisir guadagnato a ogni round torna da 5 a 4.',
          'Macchina da battaglia e Duchessa dei pugnali ricevono skin di livello 5 per chi le ha già potenziate.',
          'Dalla stagione 12 il distintivo d’argento richiede la Lega Diamante e quello d’oro un posto nella top 10.000.'],
  'impact': 'Dalla stagione 12 i distintivi di piazzamento saranno più difficili da ottenere e mostreranno meglio l’abilità su un profilo Clash Royale. Il livello della Torre del Re e delle carte restano i principali fattori di valore.'},
 'ml-mplph': {'title': 'Playoff della MPL Philippines stagione 18: PhilSports Arena, 21–25 ottobre',
  'desc': 'MOONTON ha annunciato il 26 settembre 2026 che i playoff della stagione 18 della MPL Philippines si giocano dal 21 al 25 ottobre al PhilSports Arena e decidono le squadre filippine per M8.',
  'lead': 'MOONTON Games ha annunciato sede e date dei playoff della stagione 18 della MPL Philippines il 26 settembre 2026.',
  'new': ['I playoff si giocano al PhilSports Arena di Pasig dal 21 al 25 ottobre 2026.',
          'Decidono quali squadre rappresenteranno le Filippine al campionato del mondo M8 di Istanbul a gennaio 2027.',
          'La vendita dei biglietti è aperta dal 26 settembre, a partire da 200 pesos filippini.',
          'L’annuncio celebra i 10 anni del gioco: 1,5 miliardi di installazioni e 110 milioni di giocatori attivi al mese.'],
  'impact': 'Gli eventi esport non cambiano il valore degli account esistenti. Secondo la nostra ricerca, il valore in Mobile Legends dipende da skin, eroi e progressi.'},
 'cr-bal-sep': {'title': 'Bilanciamento di settembre di Clash Royale: nerf all’eroe Stregone di ghiaccio e allo Sgherro gigante',
  'desc': 'Le note di bilanciamento di settembre 2026 di Supercell riducono il congelamento dell’eroe Stregone di ghiaccio da 7 a 5 secondi e i danni dello Sgherro gigante da 189 a 168, e rielaborano gli eroi Mega Sgherro e Stregone.',
  'lead': 'Supercell ha pubblicato due tornate di modifiche al bilanciamento di Clash Royale, applicate l’8 e il 16 settembre 2026.',
  'new': ['16 settembre: congelamento dell’eroe Stregone di ghiaccio 7 s → 5 s; abilità di Goblinstein 4 s → 3,5 s; danni dello Sgherro gigante 189 → 168; danni dello Spirito di fuoco 207 → 215.',
          '8 settembre: Congelamento 4 s → 3,5 s; danni della Palla di fuoco alle torri 172 → 159; punti ferita del Golem di ghiaccio 1.315 → 1.228.',
          'Rielaborazioni: eroe Mega Sgherro (torna indietro con il teletrasporto, danni 399 → 422) ed eroe Stregone (abilità 5 s → 3,5 s); danni dello Stregone 281 → 304.',
          'Potenziati tra gli altri Ronin, Imperatrice degli spiriti e Gabbia del goblin.'],
  'impact': 'Il bilanciamento cambia le carte più usate, non ciò che un account possiede. Secondo la nostra ricerca, il valore in Clash Royale segue il livello della Torre del Re, delle carte, le evoluzioni e i cosmetici rari.'},
 'gi-wish71': {'title': 'Desideri evento di Genshin Impact 7.1: Vesna e Vodyanitsa fino al 13 ottobre',
  'desc': 'I desideri evento della fase I della versione 7.1 aumentano le probabilità di Vesna e Vodyanitsa fino al 13 ottobre 2026, con Diona, Faruzan e Chongyun come personaggi a 4 stelle in evidenza.',
  'lead': 'HoYoverse ha pubblicato i desideri evento della fase I della versione 7.1 il 21 settembre 2026; durano fino al 13 ottobre 2026 alle 17:59.',
  'new': ['«When Warm Winds Cavort» aumenta le probabilità di ottenere Vesna (Anemo).',
          '«Surging Ballad» aumenta le probabilità di ottenere Vodyanitsa (Hydro).',
          'Personaggi a 4 stelle in evidenza: Diona (Cryo), Faruzan (Anemo) e Chongyun (Cryo).',
          'I personaggi esclusivi dell’evento non sono nel desiderio standard; i due banner dei personaggi condividono lo stesso contatore della garanzia.'],
  'impact': 'I personaggi ottenibili solo dai banner limitati, con le loro costellazioni, sono tra i principali fattori di valore di un account Genshin secondo la nostra ricerca.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: skin Darryl Goblin della spazzatura e ricompense fino al 30 settembre',
  'desc': 'L’evento Brawl Stars × Duolingo di Supercell (annunciato il 19 settembre 2026) dava la skin Darryl Goblin della spazzatura, gemme, Starr Drop e altro fino al 30 settembre.',
  'lead': 'Supercell ha annunciato il crossover Brawl Stars × Duolingo il 19 settembre 2026; è durato fino al 30 settembre.',
  'new': ['Due fasi di obiettivi della community e compiti in gioco, più una nuova modalità Duo Boss Fight.',
          'Ricompense: skin Darryl Goblin della spazzatura (Trash Goblin), 20 gemme, 5 Chaos Drop, 3 Starr Drop mitici, 2.000 monete, 2.500 Bling e 1.000 crediti.',
          'Una missione di Brawl Stars nell’app Duolingo dava cosmetici extra.',
          'Supercell ha anche organizzato sui social un quiz con 3,141592 milioni di gemme in palio.'],
  'impact': 'Le skin di un crossover unico fanno risaltare alcune collezioni di Brawl Stars; una skin ricevuta gratis da molti giocatori conta meno di una rara a pagamento.'},
 'ff-naruto': {'title': 'Torna Free Fire × NARUTO SHIPPUDEN: Nove Code e bundle di Hinata (16 settembre – 15 ottobre)',
  'desc': 'La collaborazione di Garena con NARUTO SHIPPUDEN va dal 16 settembre al 15 ottobre 2026 con l’abilità Sharingan: Control, un bundle a scelta tra Jiraiya e Hinata e cosmetici a tema.',
  'lead': 'Garena ha annunciato il 15 settembre 2026 il ritorno della collaborazione Free Fire × NARUTO SHIPPUDEN dal 16 settembre al 15 ottobre.',
  'new': ['Nuove abilità: Sharingan: Control, per comandare il Nove Code, e 8 Trigrams Palm Rotation.',
          'Un’Accademia Ninja ampliata nella mappa del Villaggio della Foglia.',
          'Premio principale a scelta: bundle di Jiraiya o bundle di Hinata (il suo debutto).',
          'Cosmetici: mantello di Tsunade, trucco del tatuaggio di Gaara, maschera ANBU di Kakashi e cassa Froggy Wallet.'],
  'impact': 'I bundle di collaborazioni su licenza disponibili per un periodo limitato sono tra gli oggetti rari che il nostro calcolatore Free Fire cerca.'},
 'ml-mtc8': {'title': 'Al via la stagione 8 del MLBB Türkiye Championship, verso M8 a Istanbul',
  'desc': 'La stagione 8 del MTC va dal 12 settembre al 18 ottobre 2026 con otto squadre e un montepremi di 40.000 dollari, prima del mondiale M8 di Istanbul a gennaio 2027.',
  'lead': 'MOONTON Games ha annunciato il 10 settembre 2026 che la stagione 8 del MLBB Türkiye Championship inizia il 12 settembre.',
  'new': ['Stagione regolare dal 12 settembre al 18 ottobre; finalissima il 7 novembre 2026.',
          'Partecipano otto squadre, tra cui Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok e Dark Passage.',
          'Le prime sei vanno ai playoff e si contendono 40.000 dollari.',
          'Il campionato del mondo M8 si terrà a Istanbul a gennaio 2027: il primo evento della serie M in Europa.'],
  'impact': 'I risultati esport non cambiano il valore degli account esistenti; skin Collector e Legend e numero di eroi restano i fattori principali secondo la nostra ricerca.'},
 'coc-blast': {'title': 'Evento medaglie Equipment Blast di Clash of Clans (9–22 settembre)',
  'desc': 'L’evento Equipment Blast si è svolto dal 9 al 22 settembre 2026: Tag Ticket e Champ Medal da spendere dal Mercante in equipaggiamento degli eroi, minerale e cosmetici. Dal Municipio 6.',
  'lead': 'Supercell ha annunciato l’evento medaglie Equipment Blast il 9 settembre 2026; è durato fino al 22 settembre alle 08:00 UTC, con il Mercante aperto fino al 24.',
  'new': ['Le battaglie multigiocatore davano Tag Ticket; il percorso dell’evento dava Champ Medal, truppe temporanee e scrigni.',
          'Il Mercante vendeva equipaggiamento degli eroi, minerale e cosmetici in cambio delle medaglie dell’evento.',
          'Truppe temporanee: Undertaker Yeti, K.A.N.E., Yeeter e Giant Giant.',
          'Disponibile dal Municipio 6.'],
  'impact': 'L’equipaggiamento degli eroi e i suoi livelli fanno parte della forza degli eroi, che secondo la nostra ricerca determina il valore degli account Clash of Clans; le medaglie dell’evento sono un modo in più per potenziarlo.'},
 'mc-wild': {'title': 'Aggiornamento Wilderness Bound di Minecraft: foresta screziata, letti di paglia e accampamenti abbandonati',
  'desc': 'L’aggiornamento Wilderness Bound di Mojang è arrivato il 15 settembre 2026 con il bioma della foresta screziata, il legno di pioppo, i letti di paglia, gli accampamenti abbandonati e i cuscini.',
  'lead': 'Mojang Studios ha chiamato «Wilderness Bound» il terzo aggiornamento del 2026 il 5 settembre e l’ha pubblicato il 15 settembre.',
  'new': ['Un nuovo bioma, la foresta screziata, con alti pioppi e funghi a mensola.',
          'I letti di paglia, fatti con tre balle di fieno, permettono di saltare la notte senza cambiare il punto di rinascita.',
          'Accampamenti abbandonati da esplorare e cuscini fatti con tre lastre di lana dello stesso colore.',
          'Legno di pioppo e set di cemento e lana ampliati per costruire.'],
  'impact': 'Gli account Minecraft si valutano per tipo, nome utente e mantelli, non per i contenuti di gioco: un aggiornamento non ne cambia il valore.'},
 'ff-award': {'title': 'Free Fire vince «Miglior uso di una IP o licenza» ai Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena ha comunicato il 3 settembre 2026 che Free Fire ha vinto Best Use of IP or Licence ai Pocket Gamer Mobile Games Awards 2026 per la collaborazione con NARUTO SHIPPUDEN.',
  'lead': 'Garena ha annunciato il 3 settembre 2026 che Free Fire ha vinto «Best Use of IP or Licence» ai Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Il premio riconosce la collaborazione NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Secondo Garena, l’evento Ninja Clash All Stars a Bangkok ha attirato quasi 5.000 visitatori e oltre 247 milioni di visualizzazioni.',
          'La collaborazione includeva personaggi a tema, abilità jutsu e una mappa trasformata del Villaggio della Foglia.',
          'Si sono tenuti eventi per la community in Perù, Bangladesh, Malesia e Taiwan.'],
  'impact': 'Un premio non cambia il valore degli account, ma conferma che le collaborazioni su licenza sono una costante di Free Fire, e i loro bundle limitati sono tra gli oggetti rari che una valutazione considera.'},
 'rbx-fall': {'title': 'Anteprima dei giochi d’autunno di Roblox: 10 esperienze tra settembre e ottobre',
  'desc': 'L’anteprima dei giochi d’autunno di Roblox (2 settembre 2026) elenca 10 nuove esperienze, da Showdown e Nemesis a settembre a Prime Heroes, Octane e Starforged a ottobre.',
  'lead': 'Roblox ha pubblicato la sua anteprima dei giochi d’autunno il 2 settembre 2026, con dieci esperienze in arrivo tra settembre e ottobre.',
  'new': ['Settembre: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force e Caramel.',
          'Ottobre: Prime Heroes (accesso anticipato a settembre con 6 eroi), Octane, Starforged e Scrapbook Saga.',
          'Diversi titoli nascono dai programmi per creator Jumpstart e Incubator di Roblox.',
          'I generi vanno dagli sparatutto e dalle corse al survival horror e ai giochi di fattoria.'],
  'impact': 'Le nuove esperienze non cambiano gli account esistenti. Secondo la nostra ricerca, il valore di un account Roblox viene da Robux, oggetti limitati e oggetti di esperienze consolidate; un gioco nuovo conta solo quando i suoi oggetti iniziano a essere scambiati.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: skin degli eroi uniche che «non torneranno» dopo il 1º ottobre',
  'desc': 'L’evento WWE: Search for Cena di Supercell (settembre 2026) ha venduto sei skin degli eroi WWE che, secondo Supercell, non torneranno dopo il 1º ottobre, oltre allo scenario Money in the Bank.',
  'lead': 'Supercell ha annunciato l’evento WWE: Search for Cena di Clash of Clans il 1º settembre 2026; è durato tutto settembre.',
  'new': ['Skin degli eroi a 9,99 $: Cody Rhodes (Re Barbaro), Alexa Bliss (Regina degli Arcieri), Iyo Sky (Campionessa Reale), Kane (Duca Drago) e American Badass Undertaker (Gran Sorvegliante).',
          'Jey Uso (Principe Sgherro) era incluso nel Pass d’oro.',
          'Supercell afferma che le skin «non torneranno. Mai» dopo il 1º ottobre.',
          'Lo scenario XL Money in the Bank era disponibile dal 2 al 30 settembre, con una sfida di John Cena e truppe WWE temporanee.'],
  'impact': 'Le skin che l’editore dice non torneranno mai sono proprio il tipo di cosmetico che rende più raro un account Clash of Clans. La maggior parte del valore resta comunque nei livelli del municipio e degli eroi.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: primo sguardo al nuovo formato in due split',
  'desc': 'Il primo sguardo di Supercell al BSC 2027 (24 agosto 2026): otto squadre per regione in quattro regioni, Challengers in 12 regioni, due split da 12 settimane, la Brawl Cup e le Finali mondiali.',
  'lead': 'Supercell ha mostrato un primo sguardo al Brawl Stars Championship 2027 il 24 agosto 2026, avvertendo che i dettagli possono ancora cambiare.',
  'new': ['Livello principale: 8 squadre per regione in Asia orientale, EMEA, Sud America e Nord America.',
          'Challengers: una via d’accesso in 12 regioni.',
          'Due split da 12 settimane; il primo si chiude con la Brawl Cup, una LAN internazionale di tre giorni, il secondo con le Finali mondiali.',
          'Date, montepremi e sedi non sono ancora stati annunciati.'],
  'impact': 'I formati esport non cambiano il valore degli account esistenti; il nostro calcolatore Brawl Stars continua a usare il numero di brawler, le Ipercariche e i trofei.'},
}},
'pl': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II już jest: wymiar Sift i Wysoka Rada Illagerów',
  'desc': 'Mojang wydał Minecraft Dungeons II 29 września 2026 r. na Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch i Switch 2, z kooperacją do 4 graczy.',
  'lead': 'Mojang Studios wydało Minecraft Dungeons II 29 września 2026 r.',
  'new': ['Gra jest dostępna na Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch i Nintendo Switch 2.',
          'Fabuła stawia graczy przeciwko Wysokiej Radzie Illagerów: Prime Enchanterowi, Supreme Evokerowi i Grand Illusionerowi.',
          'Gracze eksplorują nowy wymiar, Sift, który według Mojang w przyszłym roku trafi też do Minecraft Java i Bedrock.',
          'Można grać samemu albo w kooperacji do 4 osób, online lub na jednym ekranie.'],
  'impact': 'Dungeons II to osobna gra. Konta Minecraft Java i Bedrock nadal wycenia się według typu, nazwy użytkownika i peleryn, więc premiera nie zmienia ich wartości.'},
 'cr-mt-oct': {'title': 'Merge Tactics w Clash Royale: październikowe zmiany Superów, eliksiru i odznak',
  'desc': 'Od 1 października 2026 r. w 11. sezonie Merge Tactics Supery trafiają do wspólnej puli, eliksir za rundę spada z 5 do 4, pojawiają się skórki 5. poziomu; zasady odznak zmienią się w 12. sezonie.',
  'lead': 'Supercell ogłosił październikowe zmiany 11. sezonu Merge Tactics 30 września 2026 r.; obowiązują od 1 października.',
  'new': ['Supery nie są już jednostkami startowymi: trafiają do wspólnej puli, o którą rywalizują wszyscy gracze.',
          'Eliksir zdobywany w każdej rundzie wraca z 5 do 4.',
          'Machina Bojowa i Księżna Sztyletów dostają skórki 5. poziomu dla graczy, którzy już je ulepszyli.',
          'Od 12. sezonu srebrna odznaka wymaga dojścia do Ligi Diamentowej, a złota — miejsca w top 10 000.'],
  'impact': 'Od 12. sezonu odznaki za wysokie miejsca będą trudniejsze do zdobycia, więc lepiej pokażą umiejętności na profilu Clash Royale. Głównymi czynnikami wartości pozostają poziom Wieży Króla i poziomy kart.'},
 'ml-mplph': {'title': 'Play-offy MPL Philippines, sezon 18: PhilSports Arena, 21–25 października',
  'desc': 'MOONTON ogłosił 26 września 2026 r., że play-offy 18. sezonu MPL Philippines odbędą się 21–25 października w PhilSports Arena i wyłonią filipińskie drużyny na M8.',
  'lead': 'MOONTON Games ogłosiło 26 września 2026 r. miejsce i terminy play-offów 18. sezonu MPL Philippines.',
  'new': ['Play-offy odbędą się w PhilSports Arena w Pasig od 21 do 25 października 2026 r.',
          'Wyłonią drużyny, które będą reprezentować Filipiny na mistrzostwach świata M8 w Stambule w styczniu 2027 r.',
          'Sprzedaż biletów ruszyła 26 września, ceny od 200 peso filipińskich.',
          'Ogłoszenie świętuje 10-lecie gry: 1,5 mld instalacji i 110 mln aktywnych graczy miesięcznie.'],
  'impact': 'Wydarzenia e-sportowe nie zmieniają wartości istniejących kont. Według naszych badań o wartości kont Mobile Legends decydują skórki, bohaterowie i postępy.'},
 'cr-bal-sep': {'title': 'Wrześniowy balans Clash Royale: osłabiony bohater Lodowy Czarodziej i Gigantyczny Stwór',
  'desc': 'Wrześniowe zmiany balansu Supercell z 2026 r. skracają zamrożenie bohatera Lodowego Czarodzieja z 7 do 5 sekund i obniżają obrażenia Gigantycznego Stwora ze 189 do 168, przebudowując też bohaterów Mega Stwora i Czarodzieja.',
  'lead': 'Supercell opublikował dwie tury zmian balansu Clash Royale, wprowadzone 8 i 16 września 2026 r.',
  'new': ['16 września: zamrożenie bohatera Lodowego Czarodzieja 7 s → 5 s; zdolność Goblinsteina 4 s → 3,5 s; obrażenia Gigantycznego Stwora 189 → 168; obrażenia Ognistego Ducha 207 → 215.',
          '8 września: Zamrożenie 4 s → 3,5 s; obrażenia Kuli Ognia w wieże 172 → 159; punkty życia Lodowego Golema 1315 → 1228.',
          'Przebudowy: bohater Mega Stwór (wraca teleportem, obrażenia 399 → 422) i bohater Czarodziej (zdolność 5 s → 3,5 s); obrażenia Czarodzieja 281 → 304.',
          'Wzmocnienia m.in. dla Ronina, Cesarzowej Duchów i Klatki z Goblinem.'],
  'impact': 'Balans zmienia popularność kart, a nie zawartość konta. Według naszych badań wartość w Clash Royale zależy od poziomu Wieży Króla, poziomów kart, ewolucji i rzadkich kosmetyków.'},
 'gi-wish71': {'title': 'Życzenia wydarzenia w Genshin Impact 7.1: banery Vesny i Vodyanitsy do 13 października',
  'desc': 'Życzenia wydarzenia z fazy I wersji 7.1 od HoYoverse zwiększają szansę na Vesnę i Vodyanitsę do 13 października 2026 r.; wyróżnione postacie 4-gwiazdkowe to Diona, Faruzan i Chongyun.',
  'lead': 'HoYoverse opublikowało życzenia wydarzenia z fazy I wersji 7.1 21 września 2026 r.; trwają do 13 października 2026 r., godz. 17:59.',
  'new': ['„When Warm Winds Cavort” zwiększa szansę na Vesnę (Anemo).',
          '„Surging Ballad” zwiększa szansę na Vodyanitsę (Hydro).',
          'Wyróżnione postacie 4-gwiazdkowe: Diona (Cryo), Faruzan (Anemo) i Chongyun (Cryo).',
          'Postaci ekskluzywnych dla wydarzenia nie ma w standardowym życzeniu; oba banery postaci dzielą wspólny licznik gwarancji.'],
  'impact': 'Postacie dostępne wyłącznie z limitowanych banerów, wraz z ich konstelacjami, należą według naszych badań do głównych czynników wartości konta Genshin.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: skórka Darryl Śmieciowy Goblin i nagrody do 30 września',
  'desc': 'Wydarzenie Brawl Stars × Duolingo od Supercell (ogłoszone 19 września 2026 r.) dawało do 30 września skórkę Darryl Śmieciowy Goblin, klejnoty, Starr Dropy i więcej.',
  'lead': 'Supercell ogłosił crossover Brawl Stars × Duolingo 19 września 2026 r.; trwał do 30 września.',
  'new': ['Dwie fazy celów społeczności i zadań w grze oraz nowy tryb Duo Boss Fight.',
          'Nagrody: skórka Darryl Śmieciowy Goblin (Trash Goblin), 20 klejnotów, 5 Chaos Dropów, 3 mityczne Starr Dropy, 2000 monet, 2500 Blingu i 1000 kredytów.',
          'Zadanie Brawl Stars w aplikacji Duolingo dawało dodatkowe kosmetyki.',
          'Supercell zorganizował też w mediach społecznościowych quiz z pulą 3,141592 mln klejnotów.'],
  'impact': 'Skórki z jednorazowych crossoverów wyróżniają niektóre kolekcje Brawl Stars; skórka, którą wielu dostało za darmo, znaczy mniej niż rzadka płatna.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN wraca: Dziewięcioogoniasty i pakiet Hinaty (16 września – 15 października)',
  'desc': 'Kolaboracja Garena z NARUTO SHIPPUDEN trwa od 16 września do 15 października 2026 r.: umiejętność Sharingan: Control, pakiet do wyboru Jiraiya lub Hinata oraz tematyczne kosmetyki.',
  'lead': 'Garena ogłosiła 15 września 2026 r., że kolaboracja Free Fire × NARUTO SHIPPUDEN wraca od 16 września do 15 października.',
  'new': ['Nowe umiejętności: Sharingan: Control, pozwalający dowodzić Dziewięcioogoniastym, oraz 8 Trigrams Palm Rotation.',
          'Rozbudowana Akademia Ninja na mapie Wioski Ukrytej w Liściach.',
          'Główna nagroda do wyboru: pakiet Jiraiyi albo pakiet Hinaty (jej debiut w grze).',
          'Kosmetyki: płaszcz Tsunade, malunek z tatuażem Gaary, maska ANBU Kakashiego i skrzynia Froggy Wallet.'],
  'impact': 'Pakiety z licencjonowanych kolaboracji dostępne przez ograniczony czas należą do rzadkich przedmiotów, których szuka nasz kalkulator Free Fire.'},
 'ml-mtc8': {'title': 'Rusza 8. sezon MLBB Türkiye Championship — w drodze na M8 w Stambule',
  'desc': '8. sezon MTC trwa od 12 września do 18 października 2026 r.: osiem drużyn i pula 40 000 dolarów przed mistrzostwami świata M8 w Stambule w styczniu 2027 r.',
  'lead': 'MOONTON Games ogłosiło 10 września 2026 r., że 8. sezon MLBB Türkiye Championship startuje 12 września.',
  'new': ['Sezon zasadniczy od 12 września do 18 października; wielki finał 7 listopada 2026 r.',
          'Gra osiem drużyn, m.in. Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok i Dark Passage.',
          'Sześć najlepszych awansuje do play-offów i walczy o pulę 40 000 dolarów.',
          'Mistrzostwa świata M8 odbędą się w Stambule w styczniu 2027 r. — to pierwsze wydarzenie serii M w Europie.'],
  'impact': 'Wyniki e-sportowe nie zmieniają wartości istniejących kont; według naszych badań głównymi czynnikami pozostają skórki Collector i Legend oraz liczba bohaterów.'},
 'coc-blast': {'title': 'Wydarzenie z medalami Equipment Blast w Clash of Clans (9–22 września)',
  'desc': 'Wydarzenie Equipment Blast trwało od 9 do 22 września 2026 r.: Tag Tickety i Champ Medale wymieniało się u Handlarza na wyposażenie bohaterów, rudę i kosmetyki. Od Ratusza 6.',
  'lead': 'Supercell ogłosił wydarzenie z medalami Equipment Blast 9 września 2026 r.; trwało do 22 września, godz. 08:00 UTC, a Handlarz był otwarty do 24 września.',
  'new': ['Bitwy wieloosobowe dawały Tag Tickety; ścieżka wydarzenia dawała Champ Medale, tymczasowe jednostki i skrzynie.',
          'Handlarz sprzedawał wyposażenie bohaterów, rudę i kosmetyki za medale z wydarzenia.',
          'Tymczasowe jednostki: Undertaker Yeti, K.A.N.E., Yeeter i Giant Giant.',
          'Dostępne od Ratusza 6.'],
  'impact': 'Wyposażenie bohaterów i jego poziomy wpływają na siłę bohaterów, która według naszych badań decyduje o wartości kont Clash of Clans; medale z wydarzenia to kolejny sposób jej ulepszania.'},
 'mc-wild': {'title': 'Aktualizacja Minecraft Wilderness Bound: nakrapiany las, łóżka ze słomy i porzucone obozy',
  'desc': 'Aktualizacja Wilderness Bound od Mojang pojawiła się 15 września 2026 r. z biomem nakrapianego lasu, drewnem topoli, łóżkami ze słomy, porzuconymi obozami i poduszkami.',
  'lead': 'Mojang Studios nazwało trzecią aktualizację 2026 roku „Wilderness Bound” 5 września i wydało ją 15 września.',
  'new': ['Nowy biom — nakrapiany las z wysokimi topolami i grzybami-hubami.',
          'Łóżka ze słomy z trzech bel siana pozwalają przespać noc bez zmiany punktu odrodzenia.',
          'Porzucone obozy do odkrywania i poduszki z trzech płyt wełny w tym samym kolorze.',
          'Drewno topoli oraz rozszerzone zestawy betonu i wełny do budowania.'],
  'impact': 'Konta Minecraft wycenia się według typu, nazwy użytkownika i peleryn, a nie zawartości gry, więc aktualizacja nie zmienia ich wartości.'},
 'ff-award': {'title': 'Free Fire z nagrodą „Best Use of IP or Licence” na Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena poinformowała 3 września 2026 r., że Free Fire zdobył nagrodę Best Use of IP or Licence na Pocket Gamer Mobile Games Awards 2026 za kolaborację z NARUTO SHIPPUDEN.',
  'lead': 'Garena ogłosiła 3 września 2026 r., że Free Fire zdobył nagrodę „Best Use of IP or Licence” na Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Nagroda wyróżnia kolaborację NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Według Garena wydarzenie Ninja Clash All Stars w Bangkoku przyciągnęło prawie 5000 gości i ponad 247 mln wyświetleń.',
          'Kolaboracja obejmowała tematyczne postacie, umiejętności jutsu i przemienioną mapę Wioski Ukrytej w Liściach.',
          'Wydarzenia dla społeczności odbyły się w Peru, Bangladeszu, Malezji i na Tajwanie.'],
  'impact': 'Nagroda nie zmienia wartości kont, ale potwierdza, że licencjonowane kolaboracje są stałym elementem Free Fire — a ich limitowane pakiety należą do rzadkich przedmiotów branych pod uwagę przy wycenie.'},
 'rbx-fall': {'title': 'Jesienny przegląd gier Roblox: 10 doświadczeń we wrześniu i październiku',
  'desc': 'Jesienny przegląd gier Roblox (2 września 2026 r.) wymienia 10 nowych doświadczeń — od Showdown i Nemesis we wrześniu po Prime Heroes, Octane i Starforged w październiku.',
  'lead': 'Roblox opublikował jesienny przegląd gier 2 września 2026 r. — dziesięć doświadczeń zaplanowanych na wrzesień i październik.',
  'new': ['Wrzesień: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force i Caramel.',
          'Październik: Prime Heroes (wczesny dostęp we wrześniu z 6 bohaterami), Octane, Starforged i Scrapbook Saga.',
          'Kilka tytułów pochodzi z programów dla twórców Roblox Jumpstart i Incubator.',
          'Gatunki od strzelanek i wyścigów po survival horror i farmę.'],
  'impact': 'Nowe doświadczenia nie zmieniają istniejących kont. Według naszych badań wartość konta Roblox to Robux, przedmioty limitowane i przedmioty z długo działających doświadczeń; nowa gra liczy się dopiero, gdy jej przedmioty trafią do obrotu.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: jednorazowe skórki bohaterów, które „nie wrócą” po 1 października',
  'desc': 'Wydarzenie WWE: Search for Cena od Supercell (wrzesień 2026 r.) sprzedawało sześć skórek bohaterów WWE, które według Supercell nie wrócą po 1 października, oraz dekorację Money in the Bank.',
  'lead': 'Supercell ogłosił wydarzenie WWE: Search for Cena w Clash of Clans 1 września 2026 r.; trwało przez cały wrzesień.',
  'new': ['Skórki bohaterów po 9,99 $: Cody Rhodes (Król Barbarzyńców), Alexa Bliss (Królowa Łuczniczek), Iyo Sky (Królewska Mistrzyni), Kane (Smoczy Książę) i American Badass Undertaker (Wielki Strażnik).',
          'Jey Uso (Książę Stworów) był w Złotej przepustce.',
          'Supercell podaje, że po 1 października skórki „nie wrócą. Nigdy”.',
          'Dekoracja XL Money in the Bank była dostępna od 2 do 30 września, wraz z wyzwaniem Johna Ceny i tymczasowymi jednostkami WWE.'],
  'impact': 'Skórki, o których wydawca mówi, że nigdy nie wrócą, to właśnie te kosmetyki, które czynią konto Clash of Clans rzadszym. Większość wartości nadal jednak dają poziomy ratusza i bohaterów.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: pierwsze spojrzenie na nowy format z dwoma splitami',
  'desc': 'Pierwsze spojrzenie Supercell na BSC 2027 (24 sierpnia 2026 r.): po osiem drużyn w czterech regionach, Challengers w 12 regionach, dwa 12-tygodniowe splity, Brawl Cup i Finały Światowe.',
  'lead': 'Supercell pokazał pierwsze spojrzenie na Brawl Stars Championship 2027 24 sierpnia 2026 r., zastrzegając, że szczegóły mogą się zmienić.',
  'new': ['Najwyższy poziom: po 8 drużyn w regionach Azja Wschodnia, EMEA, Ameryka Południowa i Ameryka Północna.',
          'Challengers: ścieżka wejścia w 12 regionach.',
          'Dwa splity po 12 tygodni; pierwszy kończy się Brawl Cup — trzydniowym międzynarodowym turniejem LAN — a drugi Finałami Światowymi.',
          'Terminy, pula nagród i miejsca nie zostały jeszcze ogłoszone.'],
  'impact': 'Formaty e-sportowe nie zmieniają wartości istniejących kont; nasz kalkulator Brawl Stars nadal uwzględnia liczbę zadymiarzy, hiperładunki i pucharki.'},
}},
}
