# News batch 2: fr, de (from news_text_b2_en.py, facts unchanged)
TEXT = {
'fr': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II est sorti : la dimension du Sift et le Haut Conseil illageois',
  'desc': 'Mojang a sorti Minecraft Dungeons II le 29 septembre 2026 sur Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch et Switch 2, avec une coopération jusqu’à 4 joueurs.',
  'lead': 'Mojang Studios a sorti Minecraft Dungeons II le 29 septembre 2026.',
  'new': ['Disponible sur Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch et Nintendo Switch 2.',
          'L’histoire oppose les joueurs au Haut Conseil illageois : le Prime Enchanter, le Supreme Evoker et le Grand Illusioner.',
          'Les joueurs explorent une nouvelle dimension, le Sift, qui arrivera aussi dans Minecraft Java et Bedrock l’an prochain selon Mojang.',
          'On joue seul ou en coopération jusqu’à 4 joueurs, en ligne ou sur le même écran.'],
  'impact': 'Dungeons II est un jeu à part. Les comptes Minecraft Java et Bedrock restent évalués selon leur type, leur pseudo et leurs capes : cette sortie ne change pas leur valeur.'},
 'cr-mt-oct': {'title': 'Merge Tactics de Clash Royale : changements d’octobre pour les Supers, l’élixir et les badges',
  'desc': 'Dès le 1er octobre 2026, la saison 11 de Merge Tactics place les Supers dans la réserve commune, baisse l’élixir par manche de 5 à 4 et ajoute des apparences de niveau 5 ; les badges changent en saison 12.',
  'lead': 'Supercell a annoncé le 30 septembre 2026 les changements d’octobre de la saison 11 de Merge Tactics ; ils s’appliquent dès le 1er octobre.',
  'new': ['Les Supers ne sont plus des troupes de départ : ils rejoignent la réserve commune que tous les joueurs se disputent.',
          'L’élixir gagné par manche repasse de 5 à 4.',
          'La Machine de combat et la Duchesse aux dagues reçoivent des apparences de niveau 5 pour les joueurs qui les ont déjà améliorées.',
          'Dès la saison 12, le badge d’argent exige d’atteindre la ligue Diamant et le badge d’or une place dans le top 10 000.'],
  'impact': 'Dès la saison 12, les badges de classement seront plus difficiles à obtenir et montreront mieux le niveau sur un profil Clash Royale. Le niveau de la Tour du roi et des cartes reste le principal facteur de valeur.'},
 'ml-mplph': {'title': 'Playoffs de la MPL Philippines saison 18 : PhilSports Arena, du 21 au 25 octobre',
  'desc': 'MOONTON a annoncé le 26 septembre 2026 que les playoffs de la saison 18 de la MPL Philippines auront lieu du 21 au 25 octobre au PhilSports Arena et désigneront les équipes philippines du M8.',
  'lead': 'MOONTON Games a annoncé le 26 septembre 2026 le lieu et les dates des playoffs de la saison 18 de la MPL Philippines.',
  'new': ['Les playoffs se tiennent au PhilSports Arena de Pasig, du 21 au 25 octobre 2026.',
          'Ils désignent les équipes qui représenteront les Philippines au championnat du monde M8 à Istanbul en janvier 2027.',
          'La billetterie a ouvert le 26 septembre, à partir de 200 pesos philippins.',
          'L’annonce célèbre les 10 ans du jeu : 1,5 milliard d’installations et 110 millions de joueurs actifs par mois.'],
  'impact': 'Les événements esport ne changent pas la valeur des comptes existants. D’après nos recherches, la valeur d’un compte Mobile Legends dépend des skins, des héros et de la progression.'},
 'cr-bal-sep': {'title': 'Équilibrage de septembre de Clash Royale : le héros Sorcier de glace et la Gargouille géante affaiblis',
  'desc': 'Les notes d’équilibrage de septembre 2026 de Supercell réduisent le gel du héros Sorcier de glace de 7 à 5 secondes et les dégâts de la Gargouille géante de 189 à 168, et retravaillent les héros Méga-gargouille et Sorcier.',
  'lead': 'Supercell a publié deux séries d’équilibrages pour Clash Royale, appliquées les 8 et 16 septembre 2026.',
  'new': ['16 septembre : gel du héros Sorcier de glace 7 s → 5 s ; capacité de Goblinstein 4 s → 3,5 s ; dégâts de la Gargouille géante 189 → 168 ; dégâts de l’Esprit de feu 207 → 215.',
          '8 septembre : Gel 4 s → 3,5 s ; dégâts de la Boule de feu sur les tours 172 → 159 ; points de vie du Golem de glace 1 315 → 1 228.',
          'Refontes : héros Méga-gargouille (revient par téléportation, dégâts 399 → 422) et héros Sorcier (capacité 5 s → 3,5 s) ; dégâts du Sorcier 281 → 304.',
          'Renforcements notamment pour Ronin, l’Impératrice des esprits et la Cage à gobelin.'],
  'impact': 'L’équilibrage change les cartes à la mode, pas ce que possède un compte. D’après nos recherches, la valeur sur Clash Royale suit le niveau de la Tour du roi, des cartes, les évolutions et les cosmétiques rares.'},
 'gi-wish71': {'title': 'Vœux événementiels de Genshin Impact 7.1 : Vesna et Vodyanitsa jusqu’au 13 octobre',
  'desc': 'Les vœux événementiels de la phase I de la version 7.1 augmentent les chances de Vesna et de Vodyanitsa jusqu’au 13 octobre 2026, avec Diona, Faruzan et Chongyun en personnages 4 étoiles mis en avant.',
  'lead': 'HoYoverse a publié les vœux événementiels de la phase I de la version 7.1 le 21 septembre 2026 ; ils durent jusqu’au 13 octobre 2026 à 17 h 59.',
  'new': ['« When Warm Winds Cavort » augmente les chances d’obtenir Vesna (Anémo).',
          '« Surging Ballad » augmente les chances d’obtenir Vodyanitsa (Hydro).',
          'Personnages 4 étoiles mis en avant : Diona (Cryo), Faruzan (Anémo) et Chongyun (Cryo).',
          'Les personnages exclusifs à l’événement ne sont pas dans le vœu standard ; les deux bannières de personnages partagent le même compteur de garantie.'],
  'impact': 'Les personnages obtenables uniquement via des bannières limitées, et leurs constellations, comptent parmi les principaux facteurs de valeur d’un compte Genshin selon nos recherches.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo : skin Darryl Gobelin poubelle et récompenses jusqu’au 30 septembre',
  'desc': 'L’événement Brawl Stars × Duolingo de Supercell (annoncé le 19 septembre 2026) offrait le skin Darryl Gobelin poubelle, des gemmes, des Starr Drops et plus encore jusqu’au 30 septembre.',
  'lead': 'Supercell a annoncé le crossover Brawl Stars × Duolingo le 19 septembre 2026 ; il a duré jusqu’au 30 septembre.',
  'new': ['Deux phases d’objectifs communautaires et de tâches en jeu, plus un nouveau mode Duo Boss Fight.',
          'Récompenses : skin Darryl Gobelin poubelle (Trash Goblin), 20 gemmes, 5 Chaos Drops, 3 Starr Drops mythiques, 2 000 pièces, 2 500 bling et 1 000 crédits.',
          'Une quête Brawl Stars dans l’application Duolingo donnait des cosmétiques supplémentaires.',
          'Supercell a aussi organisé un quiz sur ses réseaux avec 3,141592 millions de gemmes à gagner.'],
  'impact': 'Les skins d’un crossover unique font ressortir certaines collections Brawl Stars ; un skin reçu gratuitement par beaucoup de joueurs pèse moins qu’un skin payant rare.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN revient : Kyûbi et pack Hinata (16 septembre – 15 octobre)',
  'desc': 'La collaboration de Garena avec NARUTO SHIPPUDEN se déroule du 16 septembre au 15 octobre 2026 avec la compétence Sharingan: Control, un pack au choix Jiraiya ou Hinata et des cosmétiques thématiques.',
  'lead': 'Garena a annoncé le 15 septembre 2026 le retour de la collaboration Free Fire × NARUTO SHIPPUDEN du 16 septembre au 15 octobre.',
  'new': ['Nouvelles compétences : Sharingan: Control, qui permet de commander Kyûbi, et 8 Trigrams Palm Rotation.',
          'Une Académie des ninjas agrandie sur la carte du village caché de la Feuille.',
          'Grand prix au choix : pack Jiraiya ou pack Hinata (première apparition d’Hinata).',
          'Cosmétiques : cape de Tsunade, maquillage du tatouage de Gaara, masque ANBU de Kakashi et caisse Froggy Wallet.'],
  'impact': 'Les packs de collaborations sous licence disponibles pour une durée limitée font partie des objets rares que recherche notre calculateur Free Fire.'},
 'ml-mtc8': {'title': 'Lancement de la saison 8 du MLBB Türkiye Championship, sur la route du M8 à Istanbul',
  'desc': 'La saison 8 du MTC se déroule du 12 septembre au 18 octobre 2026 avec huit équipes et 40 000 dollars de prize pool, avant le championnat du monde M8 à Istanbul en janvier 2027.',
  'lead': 'MOONTON Games a annoncé le 10 septembre 2026 que la saison 8 du MLBB Türkiye Championship démarre le 12 septembre.',
  'new': ['Saison régulière du 12 septembre au 18 octobre ; grande finale le 7 novembre 2026.',
          'Huit équipes participent, dont Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok et Dark Passage.',
          'Les six meilleures équipes accèdent aux playoffs et se partagent 40 000 dollars.',
          'Le championnat du monde M8 aura lieu à Istanbul en janvier 2027 : le premier événement de la série M en Europe.'],
  'impact': 'Les résultats esport ne changent pas la valeur des comptes existants ; les skins Collector et Legend et le nombre de héros restent les principaux facteurs selon nos recherches.'},
 'coc-blast': {'title': 'Événement de médailles Equipment Blast de Clash of Clans (9–22 septembre)',
  'desc': 'L’événement Equipment Blast s’est tenu du 9 au 22 septembre 2026 : Tag Tickets et Champ Medals à dépenser chez le Marchand en équipements de héros, minerai et cosmétiques. HDV 6 et plus.',
  'lead': 'Supercell a annoncé l’événement de médailles Equipment Blast le 9 septembre 2026 ; il a duré jusqu’au 22 septembre à 08 h 00 UTC, le Marchand restant ouvert jusqu’au 24.',
  'new': ['Les combats multijoueurs rapportaient des Tag Tickets ; le parcours de l’événement donnait des Champ Medals, des troupes temporaires et des coffres.',
          'Le Marchand vendait équipements de héros, minerai et cosmétiques contre des médailles d’événement.',
          'Troupes temporaires : Undertaker Yeti, K.A.N.E., Yeeter et Giant Giant.',
          'Accessible dès l’hôtel de ville 6.'],
  'impact': 'Les équipements de héros et leurs niveaux font partie de la force des héros, qui détermine la valeur d’un compte Clash of Clans selon nos recherches ; les médailles d’événement sont un moyen de plus de les améliorer.'},
 'mc-wild': {'title': 'Mise à jour Wilderness Bound de Minecraft : forêt tachetée, lits de paille et camps abandonnés',
  'desc': 'La mise à jour Wilderness Bound de Mojang est arrivée le 15 septembre 2026 avec le biome de la forêt tachetée, le bois de peuplier, les lits de paille, les camps abandonnés et les coussins.',
  'lead': 'Mojang Studios a baptisé sa troisième mise à jour de 2026 « Wilderness Bound » le 5 septembre et l’a publiée le 15 septembre.',
  'new': ['Un nouveau biome, la forêt tachetée, avec de grands peupliers et des champignons en étagère.',
          'Les lits de paille, fabriqués avec trois bottes de foin, permettent de passer la nuit sans changer de point d’apparition.',
          'Des camps abandonnés à explorer et des coussins fabriqués avec trois dalles de laine de la même couleur.',
          'Du bois de peuplier et des ensembles de béton et de laine élargis pour construire.'],
  'impact': 'Un compte Minecraft s’évalue selon son type, son pseudo et ses capes, pas selon le contenu du jeu : une mise à jour ne change pas sa valeur.'},
 'ff-award': {'title': 'Free Fire remporte « Meilleure utilisation d’une licence » aux Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena a indiqué le 3 septembre 2026 que Free Fire a remporté Best Use of IP or Licence aux Pocket Gamer Mobile Games Awards 2026 pour sa collaboration NARUTO SHIPPUDEN.',
  'lead': 'Garena a annoncé le 3 septembre 2026 que Free Fire a remporté le prix « Best Use of IP or Licence » aux Pocket Gamer Mobile Games Awards 2026.',
  'new': ['Le prix récompense la collaboration NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Selon Garena, son événement Ninja Clash All Stars à Bangkok a réuni près de 5 000 visiteurs et plus de 247 millions de vues.',
          'La collaboration comprenait des personnages thématiques, des capacités de jutsu et une carte du village caché de la Feuille transformée.',
          'Des événements communautaires ont eu lieu au Pérou, au Bangladesh, en Malaisie et à Taïwan.'],
  'impact': 'Un prix ne change pas la valeur des comptes, mais il confirme que les collaborations sous licence sont régulières dans Free Fire — et leurs packs limités font partie des objets rares qu’examine une estimation.'},
 'rbx-fall': {'title': 'Aperçu des jeux d’automne de Roblox : 10 expériences en septembre et octobre',
  'desc': 'L’aperçu des jeux d’automne de Roblox (2 septembre 2026) liste 10 nouvelles expériences, de Showdown et Nemesis en septembre à Prime Heroes, Octane et Starforged en octobre.',
  'lead': 'Roblox a publié son aperçu des jeux d’automne le 2 septembre 2026, avec dix expériences prévues en septembre et octobre.',
  'new': ['Septembre : Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force et Caramel.',
          'Octobre : Prime Heroes (accès anticipé en septembre avec 6 héros), Octane, Starforged et Scrapbook Saga.',
          'Plusieurs titres sont issus des programmes pour créateurs Jumpstart et Incubator de Roblox.',
          'Les genres vont du jeu de tir et de la course à l’horreur de survie et à la ferme.'],
  'impact': 'Les nouvelles expériences ne changent pas les comptes existants. D’après nos recherches, la valeur d’un compte Roblox vient des Robux, des objets limités et des objets d’expériences installées ; un nouveau jeu ne compte qu’une fois ses objets échangés.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE : des apparences de héros uniques qui « ne reviendront pas » après le 1er octobre',
  'desc': 'L’événement WWE: Search for Cena de Supercell (septembre 2026) a vendu six apparences de héros WWE qui, selon Supercell, ne reviendront pas après le 1er octobre, ainsi que le décor Money in the Bank.',
  'lead': 'Supercell a annoncé l’événement WWE: Search for Cena de Clash of Clans le 1er septembre 2026 ; il a duré tout le mois de septembre.',
  'new': ['Apparences de héros à 9,99 $ : Cody Rhodes (Roi des barbares), Alexa Bliss (Reine des archers), Iyo Sky (Championne royale), Kane (Duc dragon) et American Badass Undertaker (Grand gardien).',
          'Jey Uso (Prince gargouille) était inclus dans le Pass or.',
          'Supercell affirme que ces apparences « ne reviendront pas. Jamais » après le 1er octobre.',
          'Le décor XL Money in the Bank était disponible du 2 au 30 septembre, avec un défi John Cena et des troupes WWE temporaires.'],
  'impact': 'Les apparences dont l’éditeur dit qu’elles ne reviendront jamais sont exactement le type de cosmétique qui rend un compte Clash of Clans plus rare. L’essentiel de la valeur reste toutefois porté par les niveaux d’hôtel de ville et de héros.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027 : premier aperçu du nouveau format en deux splits',
  'desc': 'Premier aperçu du BSC 2027 par Supercell (24 août 2026) : huit équipes par région dans quatre régions, Challengers dans 12 régions, deux splits de 12 semaines, la Brawl Cup et les finales mondiales.',
  'lead': 'Supercell a dévoilé un premier aperçu du Brawl Stars Championship 2027 le 24 août 2026, en précisant que les détails peuvent encore changer.',
  'new': ['Niveau supérieur : 8 équipes par région en Asie de l’Est, EMEA, Amérique du Sud et Amérique du Nord.',
          'Challengers : une voie d’accès dans 12 régions.',
          'Deux splits de 12 semaines ; le premier se termine par la Brawl Cup, une LAN internationale de trois jours, le second par les finales mondiales.',
          'Dates, prize pool et lieux n’ont pas encore été annoncés.'],
  'impact': 'Les formats esport ne changent pas la valeur des comptes existants ; notre calculateur Brawl Stars continue d’utiliser le nombre de brawlers, les hypercharges et les trophées.'},
}},
'de': {'a': {
 'mc-d2': {'title': 'Minecraft Dungeons II ist erschienen: die Sift-Dimension und der Hohe Illager-Rat',
  'desc': 'Mojang hat Minecraft Dungeons II am 29. September 2026 für Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch und Switch 2 veröffentlicht – mit Koop für bis zu 4 Spieler.',
  'lead': 'Mojang Studios hat Minecraft Dungeons II am 29. September 2026 veröffentlicht.',
  'new': ['Erhältlich für Steam, Xbox Series X|S, PlayStation 5, Nintendo Switch und Nintendo Switch 2.',
          'Die Geschichte stellt die Spieler gegen den Hohen Illager-Rat: den Prime Enchanter, den Supreme Evoker und den Grand Illusioner.',
          'Gespielt wird unter anderem in der neuen Dimension Sift, die laut Mojang nächstes Jahr auch in Minecraft Java und Bedrock kommt.',
          'Allein oder im Koop mit bis zu 4 Spielern, online oder am selben Bildschirm.'],
  'impact': 'Dungeons II ist ein eigenständiges Spiel. Minecraft-Java- und -Bedrock-Konten werden weiterhin nach Kontotyp, Nutzername und Umhängen bewertet – der Release ändert ihren Wert nicht.'},
 'cr-mt-oct': {'title': 'Clash Royale Merge Tactics: Oktober-Änderungen bei Supers, Elixier und Abzeichen',
  'desc': 'Ab 1. Oktober 2026 kommen die Supers in Merge Tactics Saison 11 in den gemeinsamen Pool, das Elixier pro Runde sinkt von 5 auf 4, und es gibt Stufe-5-Skins; die Abzeichen ändern sich in Saison 12.',
  'lead': 'Supercell hat die Oktober-Änderungen für Merge Tactics Saison 11 am 30. September 2026 angekündigt; sie gelten ab 1. Oktober.',
  'new': ['Supers sind keine Starttruppen mehr: Sie kommen in den gemeinsamen Pool, um den alle Spieler konkurrieren.',
          'Das Elixier pro Runde geht von 5 wieder auf 4 zurück.',
          'Kampfmaschine und Dolchherzogin erhalten Stufe-5-Skins für Spieler, die sie bereits aufgewertet haben.',
          'Ab Saison 12 braucht das Silberabzeichen die Diamantliga und das Goldabzeichen einen Platz unter den Top 10.000.'],
  'impact': 'Ab Saison 12 sind Platzierungsabzeichen schwerer zu bekommen und zeigen das Können auf einem Clash-Royale-Profil deutlicher. Königsturm- und Kartenlevel bleiben die wichtigsten Werttreiber.'},
 'ml-mplph': {'title': 'Playoffs der MPL Philippines Saison 18: PhilSports Arena, 21.–25. Oktober',
  'desc': 'MOONTON hat am 26. September 2026 angekündigt, dass die Playoffs der MPL Philippines Saison 18 vom 21. bis 25. Oktober in der PhilSports Arena stattfinden und die philippinischen Teams für M8 bestimmen.',
  'lead': 'MOONTON Games hat Ort und Termine der Playoffs der MPL Philippines Saison 18 am 26. September 2026 bekannt gegeben.',
  'new': ['Die Playoffs finden vom 21. bis 25. Oktober 2026 in der PhilSports Arena in Pasig statt.',
          'Sie entscheiden, welche Teams die Philippinen bei der M8-Weltmeisterschaft im Januar 2027 in Istanbul vertreten.',
          'Der Ticketverkauf startete am 26. September, ab 200 philippinischen Pesos.',
          'Die Ankündigung feiert das 10-jährige Jubiläum des Spiels: 1,5 Milliarden Installationen und 110 Millionen monatlich aktive Spieler.'],
  'impact': 'E-Sport-Events ändern den Wert bestehender Konten nicht. Laut unserer Recherche bestimmen Skins, Helden und Fortschritt den Wert von Mobile-Legends-Konten.'},
 'cr-bal-sep': {'title': 'Clash-Royale-Balance im September: Held Eismagier und Lakaienriese abgeschwächt',
  'desc': 'Supercells Balance-Notizen vom September 2026 verkürzen das Einfrieren des Helden Eismagier von 7 auf 5 Sekunden und senken den Schaden des Lakaienriesen von 189 auf 168; die Helden Mega-Lakai und Magier werden überarbeitet.',
  'lead': 'Supercell hat zwei Runden Balance-Änderungen für Clash Royale veröffentlicht, die am 8. und 16. September 2026 in Kraft traten.',
  'new': ['16. September: Einfrieren des Helden Eismagier 7 s → 5 s; Fähigkeit von Goblinstein 4 s → 3,5 s; Schaden des Lakaienriesen 189 → 168; Schaden des Feuergeists 207 → 215.',
          '8. September: Frost 4 s → 3,5 s; Feuerball-Turmschaden 172 → 159; Trefferpunkte des Eisgolems 1.315 → 1.228.',
          'Überarbeitungen: Held Mega-Lakai (teleportiert sich zurück, Schaden 399 → 422) und Held Magier (Fähigkeit 5 s → 3,5 s); Schaden des Magiers 281 → 304.',
          'Verstärkt wurden unter anderem Ronin, Geisterkaiserin und Koboldkäfig.'],
  'impact': 'Balance-Änderungen verschieben, welche Karten beliebt sind, nicht, was ein Konto besitzt. Laut unserer Recherche richtet sich der Wert bei Clash Royale nach Königsturm- und Kartenlevel, Evolutionen und seltener Kosmetik.'},
 'gi-wish71': {'title': 'Genshin Impact 7.1 Event-Gebete: Vesna und Vodyanitsa bis 13. Oktober',
  'desc': 'HoYoverses Event-Gebete der Phase I von Version 7.1 erhöhen die Chance auf Vesna und Vodyanitsa bis 13. Oktober 2026; erhöhte 4-Sterne-Figuren sind Diona, Faruzan und Chongyun.',
  'lead': 'HoYoverse hat die Event-Gebete der Phase I von Version 7.1 am 21. September 2026 veröffentlicht; sie laufen bis 13. Oktober 2026, 17:59 Uhr.',
  'new': ['„When Warm Winds Cavort“ erhöht die Chance auf Vesna (Anemo).',
          '„Surging Ballad“ erhöht die Chance auf Vodyanitsa (Hydro).',
          'Erhöhte 4-Sterne-Figuren: Diona (Kryo), Faruzan (Anemo) und Chongyun (Kryo).',
          'Event-exklusive Figuren gibt es nicht im Standardgebet; die beiden Figuren-Banner teilen sich einen Garantiezähler.'],
  'impact': 'Figuren, die es nur über limitierte Banner gibt, und ihre Konstellationen gehören laut unserer Recherche zu den wichtigsten Werttreibern von Genshin-Konten.'},
 'bs-duo': {'title': 'Brawl Stars × Duolingo: Skin Darryl Müllkobold und Belohnungen bis 30. September',
  'desc': 'Supercells Event Brawl Stars × Duolingo (angekündigt am 19. September 2026) brachte bis 30. September den Skin Darryl Müllkobold, Juwelen, Starr Drops und mehr.',
  'lead': 'Supercell hat das Crossover Brawl Stars × Duolingo am 19. September 2026 angekündigt; es lief bis 30. September.',
  'new': ['Zwei Phasen mit Community-Zielen und Aufgaben im Spiel, dazu der neue Modus Duo Boss Fight.',
          'Belohnungen: Skin Darryl Müllkobold (Trash Goblin), 20 Juwelen, 5 Chaos Drops, 3 mythische Starr Drops, 2.000 Münzen, 2.500 Bling und 1.000 Credits.',
          'Eine Brawl-Stars-Quest in der Duolingo-App brachte zusätzliche Kosmetik.',
          'Supercell veranstaltete außerdem auf Social Media ein Quiz mit 3,141592 Millionen Juwelen als Preise.'],
  'impact': 'Skins aus einmaligen Crossovers lassen manche Brawl-Stars-Sammlungen herausstechen; ein Skin, den viele gratis bekommen haben, trägt weniger bei als ein seltener bezahlter.'},
 'ff-naruto': {'title': 'Free Fire × NARUTO SHIPPUDEN ist zurück: Neunschwänziger und Hinata-Paket (16. September – 15. Oktober)',
  'desc': 'Garenas Kooperation mit NARUTO SHIPPUDEN läuft vom 16. September bis 15. Oktober 2026 mit der Fähigkeit Sharingan: Control, einem Wahlpaket Jiraiya oder Hinata und thematischer Kosmetik.',
  'lead': 'Garena hat am 15. September 2026 angekündigt, dass die Kooperation Free Fire × NARUTO SHIPPUDEN vom 16. September bis 15. Oktober zurückkehrt.',
  'new': ['Neue Fähigkeiten: Sharingan: Control, mit der man den Neunschwänzigen steuert, und 8 Trigrams Palm Rotation.',
          'Eine erweiterte Ninja-Akademie auf der Karte des Verborgenen Blattdorfs.',
          'Hauptpreis zur Wahl: Jiraiya-Paket oder Hinata-Paket (Hinatas Debüt).',
          'Kosmetik: Tsunades Umhang, Gaaras Tattoo-Gesichtsbemalung, Kakashis ANBU-Maske und die Froggy-Wallet-Kiste.'],
  'impact': 'Pakete aus lizenzierten Kooperationen, die es nur für begrenzte Zeit gibt, gehören zu den seltenen Gegenständen, nach denen unser Free-Fire-Rechner sucht.'},
 'ml-mtc8': {'title': 'MLBB Türkiye Championship Saison 8 startet – auf dem Weg zu M8 in Istanbul',
  'desc': 'Die MTC Saison 8 läuft vom 12. September bis 18. Oktober 2026 mit acht Teams und 40.000 US-Dollar Preisgeld, vor der M8-Weltmeisterschaft im Januar 2027 in Istanbul.',
  'lead': 'MOONTON Games hat am 10. September 2026 angekündigt, dass die MLBB Türkiye Championship Saison 8 am 12. September startet.',
  'new': ['Reguläre Saison vom 12. September bis 18. Oktober; das große Finale ist am 7. November 2026.',
          'Acht Teams treten an, darunter Aurora Gaming, FUT Esports, Bushido Wildcats, Pacific Esports, Ozorok und Dark Passage.',
          'Die besten sechs Teams ziehen in die Playoffs ein und spielen um 40.000 US-Dollar.',
          'Die M8-Weltmeisterschaft findet im Januar 2027 in Istanbul statt – das erste M-Series-Event in Europa.'],
  'impact': 'E-Sport-Ergebnisse ändern den Wert bestehender Konten nicht; Collector- und Legend-Skins und die Zahl der Helden bleiben laut unserer Recherche die wichtigsten Faktoren.'},
 'coc-blast': {'title': 'Clash of Clans Medaillen-Event Equipment Blast (9.–22. September)',
  'desc': 'Das Equipment-Blast-Event lief vom 9. bis 22. September 2026: Tag Tickets und Champ Medals beim Händler gegen Heldenausrüstung, Erz und Kosmetik tauschen. Ab Rathaus 6.',
  'lead': 'Supercell hat das Medaillen-Event Equipment Blast am 9. September 2026 angekündigt; es lief bis 22. September, 08:00 UTC, der Händler blieb bis 24. September geöffnet.',
  'new': ['Mehrspielerkämpfe brachten Tag Tickets; der Event-Pfad gab Champ Medals, temporäre Truppen und Truhen.',
          'Der Händler verkaufte Heldenausrüstung, Erz und Kosmetik gegen Event-Medaillen.',
          'Temporäre Truppen: Undertaker Yeti, K.A.N.E., Yeeter und Giant Giant.',
          'Verfügbar ab Rathaus 6.'],
  'impact': 'Heldenausrüstung und ihre Level fließen in die Heldenstärke ein, die laut unserer Recherche den Wert von Clash-of-Clans-Konten bestimmt; Event-Medaillen sind ein weiterer Weg, sie aufzuwerten.'},
 'mc-wild': {'title': 'Minecraft-Update Wilderness Bound: gefleckter Wald, Strohbetten und verlassene Lager',
  'desc': 'Mojangs Update Wilderness Bound erschien am 15. September 2026 mit dem Biom gefleckter Wald, Pappelholz, Strohbetten, verlassenen Lagern und Sitzkissen.',
  'lead': 'Mojang Studios hat sein drittes Update 2026 am 5. September „Wilderness Bound“ getauft und am 15. September veröffentlicht.',
  'new': ['Ein neues Biom, der gefleckte Wald, mit hohen Pappeln und Konsolenpilzen.',
          'Strohbetten aus drei Heuballen lassen die Nacht überspringen, ohne den Spawnpunkt zu ändern.',
          'Verlassene Lager zum Erkunden und Sitzkissen aus drei gleichfarbigen Wollstufen.',
          'Pappelholz sowie erweiterte Beton- und Wollsets zum Bauen.'],
  'impact': 'Minecraft-Konten werden nach Typ, Nutzername und Umhängen bewertet, nicht nach Spielinhalten – ein Update ändert ihren Wert nicht.'},
 'ff-award': {'title': 'Free Fire gewinnt „Best Use of IP or Licence“ bei den Pocket Gamer Mobile Games Awards 2026',
  'desc': 'Garena hat am 3. September 2026 mitgeteilt, dass Free Fire bei den Pocket Gamer Mobile Games Awards 2026 für die NARUTO-SHIPPUDEN-Kooperation den Preis Best Use of IP or Licence gewonnen hat.',
  'lead': 'Garena hat am 3. September 2026 bekannt gegeben, dass Free Fire bei den Pocket Gamer Mobile Games Awards 2026 „Best Use of IP or Licence“ gewonnen hat.',
  'new': ['Der Preis würdigt die Kooperation NARUTO SHIPPUDEN Chapter 2: Ninja War.',
          'Laut Garena kamen zu seinem Event Ninja Clash All Stars in Bangkok fast 5.000 Besucher, bei über 247 Millionen Videoaufrufen.',
          'Die Kooperation umfasste thematische Figuren, Jutsu-Fähigkeiten und eine umgestaltete Karte des Verborgenen Blattdorfs.',
          'Community-Events fanden in Peru, Bangladesch, Malaysia und Taiwan statt.'],
  'impact': 'Ein Preis ändert keine Kontowerte. Er bestätigt aber, dass lizenzierte Kooperationen fester Teil von Free Fire sind – und deren limitierte Pakete gehören zu den seltenen Gegenständen, auf die eine Bewertung achtet.'},
 'rbx-fall': {'title': 'Roblox Fall Games Preview: 10 Erlebnisse im September und Oktober',
  'desc': 'Robloxʼ Fall Games Preview (2. September 2026) nennt 10 neue Erlebnisse – von Showdown und Nemesis im September bis Prime Heroes, Octane und Starforged im Oktober.',
  'lead': 'Roblox hat am 2. September 2026 seine Fall Games Preview veröffentlicht, mit zehn Erlebnissen für September und Oktober.',
  'new': ['September: Showdown: The Showdown Cup, Monster in the Mansion, GOAT Football League, Nemesis, Fossil Force und Caramel.',
          'Oktober: Prime Heroes (Early Access im September mit 6 Helden), Octane, Starforged und Scrapbook Saga.',
          'Mehrere Titel stammen aus den Creator-Programmen Jumpstart und Incubator von Roblox.',
          'Die Genres reichen von Shootern und Rennspielen bis zu Survival-Horror und Farming.'],
  'impact': 'Neue Erlebnisse ändern bestehende Konten nicht. Laut unserer Recherche kommt der Wert eines Roblox-Kontos aus Robux, limitierten Items und Items in etablierten Erlebnissen; ein neues Spiel zählt erst, wenn seine Items gehandelt werden.'},
 'coc-wwe': {'title': 'Clash of Clans × WWE: einmalige Helden-Skins, die nach dem 1. Oktober „nicht zurückkommen“',
  'desc': 'Supercells Event WWE: Search for Cena (September 2026) verkaufte sechs WWE-Helden-Skins, die laut Supercell nach dem 1. Oktober nicht zurückkommen, dazu die Szenerie Money in the Bank.',
  'lead': 'Supercell hat das Event WWE: Search for Cena für Clash of Clans am 1. September 2026 angekündigt; es lief den ganzen September.',
  'new': ['Helden-Skins für je 9,99 $: Cody Rhodes (Barbarenkönig), Alexa Bliss (Bogenschützenkönigin), Iyo Sky (Königliche Championesse), Kane (Drachenherzog) und American Badass Undertaker (Großer Wächter).',
          'Jey Uso (Lakaienprinz) war im Goldpass enthalten.',
          'Laut Supercell kommen die Skins nach dem 1. Oktober „nicht zurück. Niemals“.',
          'Die XL-Szenerie Money in the Bank gab es vom 2. bis 30. September, dazu eine John-Cena-Herausforderung und temporäre WWE-Truppen.'],
  'impact': 'Skins, von denen der Publisher sagt, dass sie nie zurückkommen, sind genau die Art Kosmetik, die ein Clash-of-Clans-Konto seltener macht. Den Großteil des Werts tragen aber weiterhin Rathaus- und Heldenlevel.'},
 'bs-bsc27': {'title': 'Brawl Stars Championship 2027: erster Blick auf das neue Format mit zwei Splits',
  'desc': 'Supercells erster Blick auf die BSC 2027 (24. August 2026): acht Teams pro Region in vier Regionen, Challengers in 12 Regionen, zwei Splits à 12 Wochen, der Brawl Cup und die Weltmeisterschaft.',
  'lead': 'Supercell hat am 24. August 2026 einen ersten Blick auf die Brawl Stars Championship 2027 gegeben und darauf hingewiesen, dass sich Details noch ändern können.',
  'new': ['Oberste Ebene: 8 Teams pro Region in Ostasien, EMEA, Südamerika und Nordamerika.',
          'Challengers: ein Einstiegsweg in 12 Regionen.',
          'Zwei Splits à 12 Wochen; Split 1 endet mit dem Brawl Cup, einem dreitägigen internationalen LAN-Turnier, Split 2 mit dem Weltfinale.',
          'Termine, Preisgeld und Austragungsorte wurden noch nicht bekannt gegeben.'],
  'impact': 'E-Sport-Formate ändern den Wert bestehender Konten nicht; unser Brawl-Stars-Rechner nutzt weiterhin die Zahl der Brawler, Hyperladungen und Trophäen.'},
}},
}
