"""Market rows + esports/streamer data for the 8 other games.
Prices: game pages (global) and the 2026-09-21 news-page research (FunPay,
igitems) — see scripts/research/world-markets.md. Esports: Esports Earnings
(2026-09-28). Streams: TwitchMetrics (updated 2026-09-25)."""

FP = 'https://funpay.com/en/lots/'
MARKETS = {
 'roblox': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/roblox-accounts-for-sale/a/70-1-0'), ('igitems.com', 'https://igitems.com/roblox-account')], local='$0.50 – $60 (~$800)', usd='$0.50 – $800', demand='rbx_g'),
   'cis': dict(where=[('FunPay', FP + '927/')], local='€0.01 – €117', usd='$0.01 – $133', demand='rbx_c'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/roblox-account')], local='≤ ₫20,095,375', usd='≤ $803', demand='rbx_s')},
 'clash-of-clans': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/clash-of-clans-account-for-sale/a/18-1-0'), ('igitems.com', 'https://igitems.com/clash-of-clans-account')], local='$10 – $260', usd='$10 – $260', demand='coc_g'),
   'cis': dict(where=[('FunPay', FP + '147/')], local='€0.072 – €252.51', usd='$0.08 – $288', demand='coc_c'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/clashofclans-account')], local='$64 – $289', usd='$64 – $289', demand='coc_s')},
 'clash-royale': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/clash-royale-accounts/a/52-1-0'), ('igitems.com', 'https://igitems.com/clash-royale-account')], local='$0.50 – $600+', usd='$0.50 – $600+', demand='cr_g'),
   'cis': dict(where=[('FunPay', FP + '149/')], local='€0.0127 – €1,082', usd='$0.01 – $1,232', demand='cr_c'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/clashroyale-account')], local='$27 – $965', usd='$27 – $965', demand='cr_s')},
 'free-fire': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/free-fire-accounts/a/46-1-0'), ('igitems.com', 'https://igitems.com/free-fire-account')], local='$0.73 – $250 (~$755)', usd='$0.73 – $755', demand='ff_g'),
   'cis': dict(where=[('FunPay', FP + '591/')], local='€0.24 – €3,278', usd='$0.27 – $3,733', demand='ff_c'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/freefire-account')], local='$30 – $520', usd='$30 – $520', demand='ff_s')},
 'genshin-impact': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/genshin-impact-accounts/a/39-0-0'), ('igitems.com', 'https://igitems.com/genshin-impact-account')], local='$5 – $9,000', usd='$5 – $9,000', demand='gi_g'),
   'cis': dict(where=[('FunPay', FP + '696/')], local='€0.14 – €1,284', usd='$0.16 – $1,462', demand='gi_c'),
   'cn': dict(where=[('悠悠游戏 UU898', 'https://www.uu898.com/newTrade-1586/')], local='¥105.60 – ¥225.60', usd='$16 – $34', demand='gi_cn'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/genshinimpact-account')], local='$16 – $200', usd='$16 – $200', demand='gi_s')},
 'mobile-legends': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/mobile-legends-accounts/a/55-1-0'), ('igitems.com', 'https://igitems.com/mobile-legends-account')], local='$0.50 – $300 (~$605)', usd='$0.50 – $605', demand='ml_g'),
   'cis': dict(where=[('FunPay', FP + '366/')], local='€0.058 – €2,821', usd='$0.07 – $3,212', demand=None),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/mobilelegends-account')], local='$43 – $343', usd='$43 – $343', demand='ml_s')},
 'fortnite': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/fortnite-accounts-for-sale/a/16-1-0'), ('igitems.com', 'https://igitems.com/fnite-account')], local='$10.90 – $6,200', usd='$10.90 – $6,200', demand='fn_g'),
   'cis': dict(where=[('FunPay', FP + '248/')], local='€0.053 – €3,852', usd='$0.06 – $4,386', demand='fn_c'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/fnite-account')], local='$53 – $850', usd='$53 – $850', demand='fn_s')},
 'minecraft': {
   'global': dict(where=[('Eldorado.gg', 'https://www.eldorado.gg/minecraft-accounts/a/61-1-0'), ('igitems.com', 'https://igitems.com/mc-account')], local='$0.50 – $632', usd='$0.50 – $632', demand='mc_g'),
   'cis': dict(where=[('FunPay', FP + '221/')], local='€55 – €57', usd='$63 – $65', demand='mc_c'),
   'sea': dict(where=[('igitems.com', 'https://igitems.com/mc-account')], local='$17 – $650+', usd='$17 – $650+', demand='mc_s')},
}

EE = 'https://www.esportsearnings.com/games/'
EXTRA = {
 'mobile-legends': dict(
   esports=dict(src=('Esports Earnings', EE + '531-mobile-legends-bang-bang/countries'), total='$24,494,451.87', span='2017-09 – 2026-08',
     rows=[('PH', '$8,689,040', 401), ('ID', '$5,009,305', 324), ('MY', '$2,511,113', 265), ('RU', '$1,283,124', 81), ('MM', '$1,255,091', 146), ('SG', '$963,876', 157),
           ('TR', '$629,604', 71), ('KH', '$558,773', 133), ('BR', '$505,542', 120), ('US', '$319,770', 97), ('SA', '$305,295', 38), ('EG', '$299,177', 53),
           ('DE', '$274,470', 4), ('CN', '$227,800', 29), ('MN', '$210,038', 23)]),
   players=dict(src=('Esports Earnings', EE + '531-mobile-legends-bang-bang'), rows=[('KarlTzy', 'PH', '$385,285'), ('Oheb', 'PH', '$357,030'), ('Sekys', 'MY', '$351,517'), ('FlapTzy', 'PH', '$340,294'), ('Jaypee', 'PH', '$339,148')]),
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Mobile+Legends%3A+Bang+Bang'), date='2026-09-25',
     rows=[('smetanduck', 'ru', 1553), ('MLBB_CIS', 'ru', 1510), ('titamin1', 'ru', 1353), ('oneshotmlbb', 'ru', 1039), ('wizer02', 'ru', 744), ('betboom_esports', 'ru', 644),
           ('LegoML', 'ru', 631), ('hikomlbb', 'ru', 479), ('evilkingmlbb', 'ru', 460), ('geass81', 'ru', 441)])),
 'free-fire': dict(
   esports=dict(src=('Esports Earnings', EE + '598-free-fire/countries'), total='$22,258,992.14', span='2019-01 – 2026-07',
     rows=[('TH', '$5,895,415', 243), ('ID', '$5,271,726', 448), ('BR', '$4,313,504', 243), ('VN', '$1,810,157', 184), ('MY', '$539,127', 116), ('AR', '$438,691', 51),
           ('RU', '$372,524', 24), ('CL', '$323,858', 22), ('IN', '$278,745', 75), ('PT', '$252,000', 21), ('PK', '$241,267', 47), ('MX', '$225,909', 47),
           ('CO', '$222,974', 37), ('TW', '$220,284', 34), ('MA', '$197,000', 27)]),
   players=dict(src=('Esports Earnings', EE + '598-free-fire'), rows=[('Joena', 'TH', '$544,865'), ('Moshi', 'TH', '$439,287'), ('GetHigh', 'TH', '$427,050'), ('TheCruz', 'TH', '$381,210'), ('Bops', 'BR', '$234,600')]),
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Free+Fire'), date='2026-09-25',
     rows=[('Zelika9', 'es', 368), ('MaeRelish', 'es', 197), ('SoyZegah', 'es', 115), ('zamados', 'es', 109), ('loud_voltan', 'pt', 101), ('TreborAbyss', 'es', 96),
           ('A3SAGXX', 'es', 84), ('KwamonTV', 'es', 79), ('neurifypro', 'en', 76), ('Monje_Live', 'es', 73), ('mypatrick07', 'fr', 62), ('renzon_marques_yt', 'pt', 58)])),
 'fortnite': dict(
   esports=dict(src=('Esports Earnings', EE + '534-fortnite/countries'), total='$209,108,965.33', span='2018-02 – 2026-06',
     rows=[('US', '$53,463,713', 3724), ('CA', '$9,377,905', 355), ('GB', '$8,886,417', 689), ('DK', '$8,764,846', 316), ('FR', '$8,461,201', 934), ('PL', '$7,110,332', 463),
           ('BR', '$6,810,888', 716), ('DE', '$6,586,428', 697), ('SE', '$5,477,302', 332), ('RU', '$5,246,354', 375), ('AU', '$4,913,034', 1040), ('JP', '$4,360,313', 976),
           ('AT', '$4,028,799', 47), ('NL', '$3,566,118', 242), ('NO', '$3,488,690', 180)]),
   players=dict(src=('Esports Earnings', EE + '534-fortnite'), rows=[('Bugha', 'US', '$3,771,558'), ('Aqua', 'AT', '$2,193,575'), ('psalm', 'US', '$1,874,589'), ('EpikWhale', 'US', '$1,866,287'), ('Kami', 'PL', '$1,676,725')]),
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Fortnite'), date='2026-09-25',
     rows=[('Michou', 'fr', 6711), ('Peterbot', 'en', 5317), ('Clix', 'en', 5289), ('HappyHappyGal', 'en', 5261), ('faxuty', 'en', 5181), ('AussieAntics', 'en', 4629),
           ('gorilon', 'es', 4595), ('Nikof', 'fr', 4080), ('gger3x', 'en', 2726), ('bazerk4', 'en', 2674), ('suetam1v4', 'pt', 2480), ('k1ng', 'es', 2428), ('TooseFN', 'ru', 2027)])),
 'clash-royale': dict(
   esports=dict(src=('Esports Earnings', EE + '464-clash-royale/countries'), total='$9,626,325.93', span='2016-04 – 2024-11',
     rows=[('JP', '$1,518,929', 71), ('EG', '$974,710', 13), ('BR', '$931,348', 33), ('CN', '$841,620', 53), ('US', '$782,275', 88), ('ES', '$713,730', 50),
           ('DE', '$667,433', 36), ('MX', '$665,105', 42), ('KR', '$532,543', 51), ('FR', '$235,538', 51), ('CA', '$183,800', 8), ('NL', '$155,342', 6),
           ('RU', '$137,115', 11), ('PT', '$135,773', 4), ('PL', '$110,566', 6)]),
   players=dict(src=('Esports Earnings', EE + '464-clash-royale'), rows=[('Mohamed Light', 'EG', '$960,808'), ('Mugi', 'JP', '$608,919'), ('Morten', 'DE', '$331,050'), ('LucasXGamer', 'BR', '$243,508'), ('SergioRamos', 'MX', '$243,025')]),
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Clash+Royale'), date='2026-09-25',
     rows=[('Narek_Cr', 'ru', 2705), ('mohamedlightcr', 'en', 1232), ('BigSpinCR', 'de', 1196), ('mortenroyale', 'de', 1116), ('bale_gg', 'es', 1008), ('BENIJU03', 'es', 723),
           ('Juicy', 'en', 711), ('Pompeyo4', 'es', 588), ('ClashRoyale', 'en', 524), ('RockstarCR', 'es', 519), ('erbacce_cr', 'it', 509), ('Nefastone', 'it', 465)])),
 'clash-of-clans': dict(
   esports=dict(src=('Esports Earnings', EE + '507-clash-of-clans/countries'), total='$6,950,742.37', span='2017-10 – 2024-11',
     rows=[('DE', '$1,415,748', 101), ('JP', '$1,103,667', 56), ('CN', '$801,827', 55), ('FR', '$574,240', 21), ('BR', '$566,527', 22), ('KR', '$312,033', 33),
           ('US', '$200,162', 69), ('ES', '$189,838', 18), ('FI', '$122,050', 12), ('TW', '$115,200', 15), ('IT', '$112,220', 13), ('IN', '$103,938', 49),
           ('PL', '$90,795', 3), ('MX', '$80,388', 5), ('GB', '$66,400', 5)]),
   players=dict(src=('Esports Earnings', EE + '507-clash-of-clans'), rows=[('GAKU', 'JP', '$184,772'), ('Klaus', 'JP', '$173,105'), ('Jojo23', 'DE', '$146,150'), ('yuta14', 'JP', '$144,372'), ('STARs', 'JP', '$132,305')]),
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Clash+of+Clans'), date='2026-09-25',
     rows=[('henock_muteta', 'fr', 465), ('ClashOfClans', 'en', 278), ('Elchiki_coc', 'fr', 230), ('Skarex_Live', 'fr', 190), ('suziegaming', 'en', 155), ('gurugulabgaming', 'en', 128),
           ('Style_coc', 'es', 123), ('CarbonFin', 'en', 112), ('marinaul', 'pt', 76), ('Chepper', 'de', 67), ('Haplo_80', 'it', 57)])),
 'minecraft': dict(
   esports=dict(src=('Esports Earnings', EE + '559-minecraft/countries'), total='$4,063,371.15', span='2018-12 – 2025-09',
     rows=[('US', '$2,288,571', 317), ('GB', '$409,640', 130), ('ES', '$283,934', 42), ('CA', '$270,875', 47), ('FR', '$184,067', 29), ('MX', '$146,150', 18),
           ('DE', '$91,733', 27), ('NL', '$41,306', 15), ('PL', '$29,851', 18), ('AU', '$25,062', 17), ('AT', '$23,845', 2), ('SE', '$20,474', 8), ('AR', '$12,325', 5), ('TR', '$10,671', 19)]),
   players=dict(src=('Esports Earnings', EE + '559-minecraft'), rows=[('Sapnap', 'US', '$228,039'), ('Dasnerth', 'US', '$172,461'), ('Purpled', 'US', '$121,705'), ('Technoblade', 'US', '$120,000'), ('Olliegamerz', 'ES', '$111,375')]),
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Minecraft'), date='2026-09-25',
     rows=[('auronplay', 'es', 40085), ('juansguarnizo', 'es', 8222), ('QuackityToo', 'es', 7613), ('michaelreeves', 'en', 6396), ('LyonWGFLive', 'it', 5894), ('Etoiles', 'fr', 5720),
           ('aldo_geo', 'es', 5257), ('BastiGHG', 'de', 5256), ('Roier', 'es', 5052), ('Grian', 'en', 3803), ('TangoTek', 'en', 3139), ('HIKAKIN', 'ja', 2772)])),
 'genshin-impact': dict(
   streams=dict(src=('TwitchMetrics', 'https://www.twitchmetrics.net/channels/popularity?game=Genshin+Impact'), date='2026-09-25',
     rows=[('GenshinImpactOfficial', 'en', 37317), ('Zy0xxx', 'en', 2993), ('fobm4ster', 'en', 1733), ('Janek534222', 'pl', 1571), ('AxeSay7', 'ru', 1411), ('Zajef77', 'en', 1203),
           ('Putupau', 'es', 1178), ('ABYSS__CUP', 'ru', 744), ('MironMinMax', 'ru', 709), ('Nokapt', 'fr', 647), ('Muuurrchik', 'ru', 563)])),
 # roblox: Esports Earnings lists a single $100K creator event; TwitchMetrics shows no channels → no extra blocks
}

# "what listings there emphasise" — short, from the verified top listings
N = {
 'en': dict(gi_cn='Starter builds with popular characters (Nahida, Neuvillette); "lifetime recovery guarantee"', rbx_g='Limited items (Headless, Korblox), Robux, account age', rbx_c='Mostly low-priced accounts; top listing €117', rbx_s='Accounts tied to a specific experience (top ≈ $803)',
   coc_g='Town Hall level, heroes, CWL medals', coc_c='Low-priced; top single-game listing €252', coc_s='Maxed Town Hall accounts',
   cr_g='Card evolutions, maxed cards, champions', cr_c='Maxed collector accounts: all evolutions and heroes', cr_s='"Esports-ready" accounts: all evolutions, maxed cards',
   ff_g='Rare bundles, diamonds, Elite Pass history', ff_c='High-level collector accounts with Heroic rank', ff_s='OG accounts: early Elite Pass, 1,500 fashion items',
   gi_g='5★ characters, constellations (C6), weapon refinements', gi_c='Top listing is bundled with Honkai: Star Rail', gi_s='AR59 with several 5★ characters',
   ml_g='Rank, hero and skin count (Collector / Legend skins)', ml_s='Immortal rank, 130 heroes, 552 skins',
   fn_g='OG Chapter 1 skins (Renegade Raider, Black Knight)', fn_c='2018-era accounts with 800+ skins', fn_s='700+ skins incl. Renegade Raider and collabs',
   mc_g='Account type (Java), rare capes, short names', mc_c='Mostly private-server ranks, not official accounts', mc_s='Number and rarity of capes'),
 'ru': dict(gi_cn='Стартовые аккаунты с популярными персонажами (Нахида, Нёвиллет); «пожизненная гарантия возврата»', rbx_g='Лимитки (Headless, Korblox), Robux, возраст аккаунта', rbx_c='В основном недорогие аккаунты; максимум — €117', rbx_s='Аккаунты, привязанные к конкретному режиму (максимум ≈ $803)',
   coc_g='Уровень ратуши, герои, медали ЛВК', coc_c='Недорого; максимум по одной игре — €252', coc_s='Аккаунты с максимальной ратушей',
   cr_g='Эволюции карт, прокачанные карты, чемпионы', cr_c='Коллекционные аккаунты: все эволюции и герои', cr_s='«Турнирные» аккаунты: все эволюции, прокачанные карты',
   ff_g='Редкие наборы, алмазы, история Elite Pass', ff_c='Коллекционные аккаунты высокого уровня с рангом «Героический»', ff_s='OG-аккаунты: ранний Elite Pass, 1 500 предметов одежды',
   gi_g='5★ персонажи, созвездия (C6), пробуждения оружия', gi_c='Самое дорогое объявление — вместе с Honkai: Star Rail', gi_s='AR59 и несколько 5★ персонажей',
   ml_g='Ранг, число героев и скинов (Collector / Legend)', ml_s='Ранг Immortal, 130 героев, 552 скина',
   fn_g='OG-скины 1-й главы (Renegade Raider, Black Knight)', fn_c='Аккаунты 2018 года с 800+ скинами', fn_s='700+ скинов, включая Renegade Raider и коллаборации',
   mc_g='Тип аккаунта (Java), редкие плащи, короткие ники', mc_c='В основном донат-ранги частных серверов, а не официальные аккаунты', mc_s='Количество и редкость плащей'),
 'es': dict(gi_cn='Cuentas iniciales con personajes populares (Nahida, Neuvillette); «garantía de recuperación de por vida»', rbx_g='Limiteds (Headless, Korblox), Robux, antigüedad', rbx_c='Sobre todo cuentas baratas; máximo €117', rbx_s='Cuentas ligadas a una experiencia concreta (máx. ≈ $803)',
   coc_g='Nivel de Ayuntamiento, héroes, medallas de LGC', coc_c='Barato; máximo de un solo juego €252', coc_s='Cuentas con Ayuntamiento al máximo',
   cr_g='Evoluciones, cartas al máximo, campeones', cr_c='Cuentas de coleccionista: todas las evoluciones y héroes', cr_s='Cuentas "de competición": todas las evoluciones, cartas al máximo',
   ff_g='Lotes raros, diamantes, historial de Pase Élite', ff_c='Cuentas de alto nivel con rango Heroico', ff_s='Cuentas OG: Pase Élite antiguo, 1.500 prendas',
   gi_g='Personajes 5★, constelaciones (C6), refinamientos', gi_c='El anuncio más caro incluye Honkai: Star Rail', gi_s='AR59 con varios personajes 5★',
   ml_g='Rango, número de héroes y skins (Collector / Legend)', ml_s='Rango Inmortal, 130 héroes, 552 skins',
   fn_g='Skins OG del Capítulo 1 (Renegade Raider, Black Knight)', fn_c='Cuentas de 2018 con 800+ skins', fn_s='700+ skins, incl. Renegade Raider y colaboraciones',
   mc_g='Tipo de cuenta (Java), capas raras, nombres cortos', mc_c='Sobre todo rangos de servidores privados, no cuentas oficiales', mc_s='Número y rareza de capas'),
 'pt': dict(gi_cn='Contas iniciais com personagens populares (Nahida, Neuvillette); "garantia vitalícia de recuperação"', rbx_g='Limiteds (Headless, Korblox), Robux, idade da conta', rbx_c='Contas baratas na maioria; máximo €117', rbx_s='Contas ligadas a uma experiência específica (máx. ≈ $803)',
   coc_g='Nível do Centro de Vila, heróis, medalhas da LGC', coc_c='Barato; máximo de um só jogo €252', coc_s='Contas com CV no máximo',
   cr_g='Evoluções, cartas no máximo, campeões', cr_c='Contas de colecionador: todas as evoluções e heróis', cr_s='Contas "de campeonato": todas as evoluções, cartas no máximo',
   ff_g='Pacotes raros, diamantes, histórico de Passe de Elite', ff_c='Contas de nível alto com rank Heroico', ff_s='Contas OG: Passe de Elite antigo, 1.500 itens de roupa',
   gi_g='Personagens 5★, constelações (C6), refinamentos', gi_c='O anúncio mais caro inclui Honkai: Star Rail', gi_s='AR59 com vários personagens 5★',
   ml_g='Elo, número de heróis e skins (Collector / Legend)', ml_s='Elo Imortal, 130 heróis, 552 skins',
   fn_g='Skins OG do Capítulo 1 (Renegade Raider, Black Knight)', fn_c='Contas de 2018 com 800+ skins', fn_s='700+ skins, incl. Renegade Raider e collabs',
   mc_g='Tipo de conta (Java), capas raras, nomes curtos', mc_c='Na maioria ranks de servidores privados, não contas oficiais', mc_s='Quantidade e raridade de capas'),
 'id': dict(gi_cn='Akun awal dengan karakter populer (Nahida, Neuvillette); "jaminan pemulihan seumur hidup"', rbx_g='Item limited (Headless, Korblox), Robux, umur akun', rbx_c='Sebagian besar akun murah; tertinggi €117', rbx_s='Akun terkait experience tertentu (tertinggi ≈ $803)',
   coc_g='Level Balai Kota, hero, medali CWL', coc_c='Murah; listing tertinggi satu game €252', coc_s='Akun Balai Kota maksimal',
   cr_g='Evolusi kartu, kartu maksimal, champion', cr_c='Akun kolektor: semua evolusi dan hero', cr_s='Akun "siap turnamen": semua evolusi, kartu maksimal',
   ff_g='Bundle langka, diamond, riwayat Elite Pass', ff_c='Akun kolektor level tinggi dengan rank Heroic', ff_s='Akun OG: Elite Pass awal, 1.500 item fashion',
   gi_g='Karakter 5★, konstelasi (C6), refinement senjata', gi_c='Listing termahal digabung dengan Honkai: Star Rail', gi_s='AR59 dengan beberapa karakter 5★',
   ml_g='Rank, jumlah hero dan skin (Collector / Legend)', ml_s='Rank Immortal, 130 hero, 552 skin',
   fn_g='Skin OG Chapter 1 (Renegade Raider, Black Knight)', fn_c='Akun era 2018 dengan 800+ skin', fn_s='700+ skin termasuk Renegade Raider dan kolaborasi',
   mc_g='Jenis akun (Java), cape langka, nama pendek', mc_c='Kebanyakan rank server privat, bukan akun resmi', mc_s='Jumlah dan kelangkaan cape'),
 'tr': dict(gi_cn='Popüler karakterli başlangıç hesapları (Nahida, Neuvillette); "ömür boyu geri alma garantisi"', rbx_g='Limited eşyalar (Headless, Korblox), Robux, hesap yaşı', rbx_c='Çoğunlukla ucuz hesaplar; en yüksek €117', rbx_s='Belirli bir deneyime bağlı hesaplar (en yüksek ≈ $803)',
   coc_g='Belediye Binası seviyesi, kahramanlar, KSL madalyaları', coc_c='Ucuz; tek oyunluk en yüksek ilan €252', coc_s='Maksimum Belediye Binalı hesaplar',
   cr_g='Kart evrimleri, maksimum kartlar, şampiyonlar', cr_c='Koleksiyoner hesaplar: tüm evrimler ve kahramanlar', cr_s='"Turnuvaya hazır" hesaplar: tüm evrimler, maksimum kartlar',
   ff_g='Nadir paketler, elmaslar, Elite Pass geçmişi', ff_c='Kahraman rütbeli yüksek seviyeli koleksiyon hesapları', ff_s='OG hesaplar: erken Elite Pass, 1.500 kıyafet',
   gi_g='5★ karakterler, takımyıldızlar (C6), silah arıtma', gi_c='En pahalı ilan Honkai: Star Rail ile birlikte', gi_s='Birkaç 5★ karakterli AR59',
   ml_g='Rütbe, kahraman ve kostüm sayısı (Collector / Legend)', ml_s='Immortal rütbe, 130 kahraman, 552 kostüm',
   fn_g='1. Bölüm OG kostümleri (Renegade Raider, Black Knight)', fn_c='800+ kostümlü 2018 dönemi hesaplar', fn_s='Renegade Raider ve iş birlikleri dahil 700+ kostüm',
   mc_g='Hesap türü (Java), nadir pelerinler, kısa isimler', mc_c='Çoğunlukla özel sunucu rütbeleri, resmi hesap değil', mc_s='Pelerin sayısı ve nadirliği'),
 'ar': dict(gi_cn='حسابات مبتدئة بشخصيات شائعة (Nahida وNeuvillette)؛ "ضمان استرداد مدى الحياة"', rbx_g='العناصر المحدودة (Headless وKorblox) وRobux وعمر الحساب', rbx_c='غالباً حسابات رخيصة؛ الأعلى €117', rbx_s='حسابات مرتبطة بتجربة معينة (الأعلى ≈ $803)',
   coc_g='مستوى قاعة البلدة والأبطال وميداليات حرب الدوري', coc_c='رخيص؛ أعلى إعلان للعبة واحدة €252', coc_s='حسابات بقاعة بلدة كاملة التطوير',
   cr_g='تطورات البطاقات والبطاقات المطوّرة والأبطال', cr_c='حسابات جامعين: كل التطورات والأبطال', cr_s='حسابات "جاهزة للبطولات": كل التطورات وبطاقات مطوّرة',
   ff_g='حزم نادرة وماس وسجل Elite Pass', ff_c='حسابات جامعين عالية المستوى برتبة Heroic', ff_s='حسابات OG: ‏Elite Pass مبكر و1,500 قطعة ملابس',
   gi_g='شخصيات 5★ والأبراج (C6) وتحسين الأسلحة', gi_c='أغلى إعلان مدمج مع Honkai: Star Rail', gi_s='AR59 مع عدة شخصيات 5★',
   ml_g='الرتبة وعدد الأبطال والسكنات (Collector / Legend)', ml_s='رتبة Immortal و130 بطلاً و552 سكن',
   fn_g='سكنات OG من الفصل الأول (Renegade Raider وBlack Knight)', fn_c='حسابات من 2018 بأكثر من 800 سكن', fn_s='أكثر من 700 سكن منها Renegade Raider وتعاونات',
   mc_g='نوع الحساب (Java) وعباءات نادرة وأسماء قصيرة', mc_c='غالباً رتب خوادم خاصة وليست حسابات رسمية', mc_s='عدد العباءات وندرتها'),
 'vi': dict(gi_cn='Tài khoản khởi đầu có nhân vật phổ biến (Nahida, Neuvillette); "bảo hành thu hồi trọn đời"', rbx_g='Vật phẩm limited (Headless, Korblox), Robux, tuổi tài khoản', rbx_c='Chủ yếu tài khoản rẻ; cao nhất €117', rbx_s='Tài khoản gắn với một experience cụ thể (cao nhất ≈ $803)',
   coc_g='Cấp Nhà chính, anh hùng, huy chương CWL', coc_c='Giá rẻ; tin đắt nhất một game €252', coc_s='Tài khoản Nhà chính full cấp',
   cr_g='Tiến hóa thẻ, thẻ full cấp, tướng champion', cr_c='Tài khoản sưu tầm: đủ tiến hóa và anh hùng', cr_s='Tài khoản "thi đấu": đủ tiến hóa, thẻ full cấp',
   ff_g='Gói hiếm, kim cương, lịch sử Elite Pass', ff_c='Tài khoản sưu tầm cấp cao, rank Huyền thoại', ff_s='Tài khoản OG: Elite Pass đời đầu, 1.500 món thời trang',
   gi_g='Nhân vật 5★, cung mệnh (C6), tinh luyện vũ khí', gi_c='Tin đắt nhất gộp chung Honkai: Star Rail', gi_s='AR59 với nhiều nhân vật 5★',
   ml_g='Rank, số tướng và skin (Collector / Legend)', ml_s='Rank Immortal, 130 tướng, 552 skin',
   fn_g='Skin OG Chương 1 (Renegade Raider, Black Knight)', fn_c='Tài khoản thời 2018 với 800+ skin', fn_s='700+ skin gồm Renegade Raider và hợp tác',
   mc_g='Loại tài khoản (Java), áo choàng hiếm, tên ngắn', mc_c='Chủ yếu là rank server riêng, không phải tài khoản chính thức', mc_s='Số lượng và độ hiếm áo choàng'),
 'hi': dict(gi_cn='लोकप्रिय किरदारों वाले शुरुआती अकाउंट (Nahida, Neuvillette); "आजीवन रिकवरी गारंटी"', rbx_g='लिमिटेड आइटम (Headless, Korblox), Robux, अकाउंट की उम्र', rbx_c='ज़्यादातर सस्ते अकाउंट; सबसे ऊँचा €117', rbx_s='किसी खास एक्सपीरियंस से जुड़े अकाउंट (सबसे ऊँचा ≈ $803)',
   coc_g='टाउन हॉल लेवल, हीरो, CWL मेडल', coc_c='सस्ता; एक गेम की सबसे ऊँची लिस्टिंग €252', coc_s='मैक्स टाउन हॉल वाले अकाउंट',
   cr_g='कार्ड इवोल्यूशन, मैक्स कार्ड, चैंपियन', cr_c='कलेक्टर अकाउंट: सारे इवोल्यूशन और हीरो', cr_s='"टूर्नामेंट-रेडी" अकाउंट: सारे इवोल्यूशन, मैक्स कार्ड',
   ff_g='दुर्लभ बंडल, डायमंड, Elite Pass इतिहास', ff_c='Heroic रैंक वाले ऊँचे लेवल के कलेक्टर अकाउंट', ff_s='OG अकाउंट: शुरुआती Elite Pass, 1,500 फ़ैशन आइटम',
   gi_g='5★ किरदार, कॉन्स्टेलेशन (C6), हथियार रिफ़ाइनमेंट', gi_c='सबसे महँगी लिस्टिंग Honkai: Star Rail के साथ', gi_s='कई 5★ किरदारों वाला AR59',
   ml_g='रैंक, हीरो और स्किन की संख्या (Collector / Legend)', ml_s='Immortal रैंक, 130 हीरो, 552 स्किन',
   fn_g='चैप्टर 1 की OG स्किन (Renegade Raider, Black Knight)', fn_c='800+ स्किन वाले 2018 के अकाउंट', fn_s='Renegade Raider और कोलैब सहित 700+ स्किन',
   mc_g='अकाउंट टाइप (Java), दुर्लभ केप, छोटे नाम', mc_c='ज़्यादातर प्राइवेट सर्वर रैंक, आधिकारिक अकाउंट नहीं', mc_s='केप की संख्या और दुर्लभता'),
 'fr': dict(gi_cn='Comptes de départ avec des personnages populaires (Nahida, Neuvillette) ; « garantie de récupération à vie »', rbx_g='Objets limités (Headless, Korblox), Robux, ancienneté', rbx_c='Surtout des comptes bon marché ; maximum 117 €', rbx_s='Comptes liés à une expérience précise (max. ≈ 803 $)',
   coc_g='Niveau d\'hôtel de ville, héros, médailles de LGC', coc_c='Bon marché ; annonce max. pour un seul jeu 252 €', coc_s='Comptes avec hôtel de ville au maximum',
   cr_g='Évolutions, cartes au maximum, champions', cr_c='Comptes de collection : toutes les évolutions et tous les héros', cr_s='Comptes « prêts pour l\'esport » : toutes les évolutions, cartes au max.',
   ff_g='Packs rares, diamants, historique du Passe Élite', ff_c='Comptes de collection haut niveau, rang Héroïque', ff_s='Comptes OG : ancien Passe Élite, 1 500 tenues',
   gi_g='Personnages 5★, constellations (C6), raffinements d\'armes', gi_c='L\'annonce la plus chère inclut Honkai: Star Rail', gi_s='AR59 avec plusieurs personnages 5★',
   ml_g='Rang, nombre de héros et de skins (Collector / Legend)', ml_s='Rang Immortal, 130 héros, 552 skins',
   fn_g='Skins OG du Chapitre 1 (Renegade Raider, Black Knight)', fn_c='Comptes de 2018 avec 800+ skins', fn_s='700+ skins dont Renegade Raider et collabs',
   mc_g='Type de compte (Java), capes rares, pseudos courts', mc_c='Surtout des grades de serveurs privés, pas des comptes officiels', mc_s='Nombre et rareté des capes'),
 'de': dict(gi_cn='Starterkonten mit beliebten Charakteren (Nahida, Neuvillette); „lebenslange Rückholgarantie“', rbx_g='Limited-Items (Headless, Korblox), Robux, Kontoalter', rbx_c='Meist günstige Konten; Höchstwert 117 €', rbx_s='An ein bestimmtes Erlebnis gebundene Konten (max. ≈ 803 $)',
   coc_g='Rathaus-Level, Helden, CWL-Medaillen', coc_c='Günstig; höchstes Einzelspiel-Angebot 252 €', coc_s='Konten mit maximalem Rathaus',
   cr_g='Karten-Evolutionen, maximierte Karten, Champions', cr_c='Sammlerkonten: alle Evolutionen und Helden', cr_s='„Turnierfertige“ Konten: alle Evolutionen, maximierte Karten',
   ff_g='Seltene Bundles, Diamanten, Elite-Pass-Verlauf', ff_c='Hochstufige Sammlerkonten mit Rang Heroisch', ff_s='OG-Konten: früher Elite Pass, 1.500 Kleidungsstücke',
   gi_g='5★-Charaktere, Konstellationen (C6), Waffenverfeinerung', gi_c='Teuerstes Angebot inklusive Honkai: Star Rail', gi_s='AR59 mit mehreren 5★-Charakteren',
   ml_g='Rang, Anzahl der Helden und Skins (Collector / Legend)', ml_s='Rang Immortal, 130 Helden, 552 Skins',
   fn_g='OG-Skins aus Kapitel 1 (Renegade Raider, Black Knight)', fn_c='Konten aus 2018 mit 800+ Skins', fn_s='700+ Skins inkl. Renegade Raider und Kollabs',
   mc_g='Kontotyp (Java), seltene Umhänge, kurze Namen', mc_c='Meist Ränge privater Server, keine offiziellen Konten', mc_s='Anzahl und Seltenheit der Umhänge'),
 'it': dict(gi_cn='Account iniziali con personaggi popolari (Nahida, Neuvillette); "garanzia di recupero a vita"', rbx_g='Oggetti limited (Headless, Korblox), Robux, anzianità', rbx_c='Per lo più account economici; massimo 117 €', rbx_s='Account legati a un\'esperienza specifica (max. ≈ 803 $)',
   coc_g='Livello del Municipio, eroi, medaglie della CWL', coc_c='Economico; annuncio massimo per un solo gioco 252 €', coc_s='Account con Municipio al massimo',
   cr_g='Evoluzioni, carte al massimo, campioni', cr_c='Account da collezione: tutte le evoluzioni e gli eroi', cr_s='Account "da torneo": tutte le evoluzioni, carte al massimo',
   ff_g='Pacchetti rari, diamanti, storico del Pass Élite', ff_c='Account da collezione di alto livello con rango Eroico', ff_s='Account OG: Pass Élite dei primi tempi, 1.500 capi',
   gi_g='Personaggi 5★, costellazioni (C6), affinamenti delle armi', gi_c='L\'annuncio più caro include Honkai: Star Rail', gi_s='AR59 con diversi personaggi 5★',
   ml_g='Rango, numero di eroi e skin (Collector / Legend)', ml_s='Rango Immortal, 130 eroi, 552 skin',
   fn_g='Skin OG del Capitolo 1 (Renegade Raider, Black Knight)', fn_c='Account del 2018 con 800+ skin', fn_s='700+ skin, tra cui Renegade Raider e collaborazioni',
   mc_g='Tipo di account (Java), mantelli rari, nomi corti', mc_c='Per lo più gradi di server privati, non account ufficiali', mc_s='Numero e rarità dei mantelli'),
 'ja': dict(gi_cn='人気キャラ（ナヒーダ、ヌヴィレット）入りの初期アカウント。「永久補償」付き', rbx_g='リミテッド（Headless、Korblox）、Robux、アカウント歴', rbx_c='ほとんどが安価なアカウント。最高€117', rbx_s='特定のエクスペリエンスに紐づくアカウント（最高約$803）',
   coc_g='タウンホールレベル、ヒーロー、CWLメダル', coc_c='安価。単体ゲームの最高出品€252', coc_s='タウンホールカンストのアカウント',
   cr_g='カードの進化、カンストカード、チャンピオン', cr_c='コレクターアカウント：全進化・全ヒーロー', cr_s='「大会向け」アカウント：全進化、カンストカード',
   ff_g='レアバンドル、ダイヤ、エリートパス履歴', ff_c='ヒロイックランクの高レベルコレクターアカウント', ff_s='OGアカウント：初期エリートパス、衣装1,500点',
   gi_g='星5キャラ、命ノ星座（C6）、武器精錬', gi_c='最高額の出品は崩壊：スターレイルとのセット', gi_s='星5キャラ複数のAR59',
   ml_g='ランク、ヒーロー数とスキン数（Collector / Legend）', ml_s='Immortalランク、ヒーロー130、スキン552',
   fn_g='チャプター1のOGスキン（Renegade Raider、Black Knight）', fn_c='スキン800以上の2018年頃のアカウント', fn_s='Renegade Raiderやコラボを含むスキン700以上',
   mc_g='アカウント種別（Java）、レアなマント、短い名前', mc_c='ほとんどは非公式サーバーのランクで、公式アカウントではない', mc_s='マントの数とレア度'),
 'ko': dict(gi_cn='인기 캐릭터(나히다, 느비예트) 보유 시작 계정; "평생 회수 보상" 표기', rbx_g='리미티드 아이템(Headless, Korblox), 로벅스, 계정 연차', rbx_c='대부분 저가 계정; 최고 €117', rbx_s='특정 체험에 연동된 계정(최고 약 $803)',
   coc_g='마을회관 레벨, 영웅, CWL 메달', coc_c='저가; 단일 게임 최고 매물 €252', coc_s='마을회관 만렙 계정',
   cr_g='카드 진화, 만렙 카드, 챔피언', cr_c='컬렉터 계정: 모든 진화와 영웅', cr_s='"대회용" 계정: 모든 진화, 만렙 카드',
   ff_g='희귀 번들, 다이아몬드, 엘리트 패스 이력', ff_c='히로익 랭크의 고레벨 컬렉터 계정', ff_s='OG 계정: 초창기 엘리트 패스, 의상 1,500개',
   gi_g='5성 캐릭터, 운명의 자리(C6), 무기 재련', gi_c='최고가 매물은 붕괴: 스타레일과 묶음', gi_s='5성 캐릭터 여럿을 보유한 AR59',
   ml_g='랭크, 영웅·스킨 수(Collector / Legend)', ml_s='Immortal 랭크, 영웅 130, 스킨 552',
   fn_g='챕터 1 OG 스킨(Renegade Raider, Black Knight)', fn_c='스킨 800개 이상인 2018년 계정', fn_s='Renegade Raider·콜라보 포함 스킨 700개 이상',
   mc_g='계정 유형(Java), 희귀 망토, 짧은 닉네임', mc_c='대부분 사설 서버 등급이며 공식 계정이 아님', mc_s='망토 수와 희귀도'),
 'th': dict(gi_cn='บัญชีเริ่มต้นที่มีตัวละครยอดนิยม (Nahida, Neuvillette) พร้อม "รับประกันการกู้คืนตลอดชีพ"', rbx_g='ไอเท็มลิมิเต็ด (Headless, Korblox), Robux, อายุบัญชี', rbx_c='ส่วนใหญ่เป็นบัญชีราคาถูก สูงสุด €117', rbx_s='บัญชีที่ผูกกับเอ็กซ์พีเรียนซ์เฉพาะ (สูงสุด ≈ $803)',
   coc_g='เลเวลศาลากลาง ฮีโร่ เหรียญ CWL', coc_c='ราคาถูก ประกาศเกมเดียวสูงสุด €252', coc_s='บัญชีศาลากลางตัน',
   cr_g='การวิวัฒนาการการ์ด การ์ดตัน แชมเปี้ยน', cr_c='บัญชีสะสม: วิวัฒนาการและฮีโร่ครบ', cr_s='บัญชี "พร้อมแข่ง": วิวัฒนาการครบ การ์ดตัน',
   ff_g='บันเดิลหายาก เพชร ประวัติ Elite Pass', ff_c='บัญชีสะสมเลเวลสูงแรงค์ฮีโรอิก', ff_s='บัญชี OG: Elite Pass ยุคแรก ชุดแฟชั่น 1,500 ชิ้น',
   gi_g='ตัวละคร 5★ กลุ่มดาว (C6) การเกลาอาวุธ', gi_c='ประกาศแพงที่สุดรวมกับ Honkai: Star Rail', gi_s='AR59 มีตัวละคร 5★ หลายตัว',
   ml_g='แรงค์ จำนวนฮีโร่และสกิน (Collector / Legend)', ml_s='แรงค์ Immortal ฮีโร่ 130 สกิน 552',
   fn_g='สกิน OG บทที่ 1 (Renegade Raider, Black Knight)', fn_c='บัญชียุค 2018 สกินกว่า 800', fn_s='สกินกว่า 700 รวม Renegade Raider และคอลแลบ',
   mc_g='ประเภทบัญชี (Java) ผ้าคลุมหายาก ชื่อสั้น', mc_c='ส่วนใหญ่เป็นยศเซิร์ฟเวอร์เอกชน ไม่ใช่บัญชีทางการ', mc_s='จำนวนและความหายากของผ้าคลุม'),
 'pl': dict(gi_cn='Konta startowe z popularnymi postaciami (Nahida, Neuvillette); „dożywotnia gwarancja odzyskania”', rbx_g='Przedmioty limited (Headless, Korblox), Robux, wiek konta', rbx_c='Głównie tanie konta; maksimum 117 €', rbx_s='Konta powiązane z konkretnym trybem (maks. ≈ 803 $)',
   coc_g='Poziom ratusza, bohaterowie, medale LWK', coc_c='Tanio; najdroższa oferta jednej gry 252 €', coc_s='Konta z maksymalnym ratuszem',
   cr_g='Ewolucje kart, wymaksowane karty, czempioni', cr_c='Konta kolekcjonerskie: wszystkie ewolucje i bohaterowie', cr_s='Konta „turniejowe”: wszystkie ewolucje, wymaksowane karty',
   ff_g='Rzadkie zestawy, diamenty, historia Elite Pass', ff_c='Kolekcjonerskie konta wysokiego poziomu z rangą Heroiczną', ff_s='Konta OG: wczesny Elite Pass, 1500 ubrań',
   gi_g='Postacie 5★, konstelacje (C6), rafinacje broni', gi_c='Najdroższa oferta w pakiecie z Honkai: Star Rail', gi_s='AR59 z kilkoma postaciami 5★',
   ml_g='Ranga, liczba bohaterów i skórek (Collector / Legend)', ml_s='Ranga Immortal, 130 bohaterów, 552 skórki',
   fn_g='Skórki OG z Rozdziału 1 (Renegade Raider, Black Knight)', fn_c='Konta z 2018 r. z 800+ skórkami', fn_s='700+ skórek, w tym Renegade Raider i kolaboracje',
   mc_g='Typ konta (Java), rzadkie peleryny, krótkie nazwy', mc_c='Głównie rangi prywatnych serwerów, nie oficjalne konta', mc_s='Liczba i rzadkość peleryn'),
 'zh': dict(gi_cn='含热门角色（纳西妲、那维莱特）的起步号；标注"终身找回包赔"', rbx_g='限定物品（Headless、Korblox）、Robux、账号年龄', rbx_c='多为低价账号；最高€117', rbx_s='绑定特定体验的账号（最高约$803）',
   coc_g='大本营等级、英雄、联赛奖牌', coc_c='价格低；单游戏最高挂单€252', coc_s='满级大本营账号',
   cr_g='卡牌进化、满级卡牌、英雄卡', cr_c='收藏级账号：全部进化和英雄', cr_s='"比赛级"账号：全部进化、满级卡牌',
   ff_g='稀有礼包、钻石、精英通行证历史', ff_c='英勇段位的高等级收藏账号', ff_s='OG账号：早期精英通行证、1,500件时装',
   gi_g='五星角色、命之座（C6）、武器精炼', gi_c='最贵挂单与《崩坏：星穹铁道》捆绑', gi_s='拥有多个五星角色的AR59',
   ml_g='段位、英雄与皮肤数量（Collector / Legend）', ml_s='Immortal段位、130个英雄、552款皮肤',
   fn_g='第一章OG皮肤（Renegade Raider、Black Knight）', fn_c='2018年前后、800+皮肤的账号', fn_s='700+皮肤，含Renegade Raider及联动',
   mc_g='账号类型（Java）、稀有披风、短ID', mc_c='多为私服等级，而非官方账号', mc_s='披风数量与稀有度'),
}

# one-line caveat under every streamer table
TW_ONLY = {
 'en': 'Twitch only — in many countries these games are streamed mostly on other platforms.',
 'ru': 'Только Twitch — во многих странах эти игры чаще стримят на других платформах.',
 'es': 'Solo Twitch: en muchos países estos juegos se transmiten sobre todo en otras plataformas.',
 'pt': 'Somente Twitch — em muitos países esses jogos são transmitidos principalmente em outras plataformas.',
 'id': 'Hanya Twitch — di banyak negara game ini lebih banyak disiarkan di platform lain.',
 'tr': 'Yalnızca Twitch — birçok ülkede bu oyunlar çoğunlukla başka platformlarda yayınlanıyor.',
 'ar': 'Twitch فقط — في كثير من الدول تُبث هذه الألعاب غالباً على منصات أخرى.',
 'vi': 'Chỉ Twitch — ở nhiều nước các game này chủ yếu được phát trên nền tảng khác.',
 'hi': 'केवल Twitch — कई देशों में ये गेम ज़्यादातर दूसरे प्लेटफ़ॉर्म पर स्ट्रीम होते हैं।',
 'fr': 'Twitch uniquement — dans de nombreux pays, ces jeux sont surtout diffusés sur d\'autres plateformes.',
 'de': 'Nur Twitch — in vielen Ländern werden diese Spiele vor allem auf anderen Plattformen gestreamt.',
 'it': 'Solo Twitch: in molti paesi questi giochi sono trasmessi soprattutto su altre piattaforme.',
 'ja': 'Twitchのみ。多くの国では、これらのゲームは主に他のプラットフォームで配信されています。',
 'ko': 'Twitch만 해당 — 많은 나라에서 이 게임들은 주로 다른 플랫폼에서 방송됩니다.',
 'th': 'เฉพาะ Twitch — ในหลายประเทศเกมเหล่านี้สตรีมบนแพลตฟอร์มอื่นเป็นหลัก',
 'pl': 'Tylko Twitch — w wielu krajach te gry transmituje się głównie na innych platformach.',
 'zh': '仅统计Twitch——在许多国家，这些游戏主要在其他平台直播。',
}


# second research round: JP / CN / KR / TR rows
from world_data2 import ROWS as _ROWS, N2 as _N2
for _g, _rows in _ROWS.items():
    MARKETS[_g].update(_rows)
for _l, _notes in _N2.items():
    N[_l].update(_notes)

# Malay (2026-09-30)
N['ms'] = {'coc_c': 'Harga rendah; iklan tertinggi untuk permainan ini €252',
 'coc_cn': 'Town Hall 18 dengan wira, pertahanan dan equipment dimaksimumkan',
 'coc_g': 'Tahap Town Hall, wira, pingat CWL',
 'coc_jp': 'Town Hall 18, wira dimaksimumkan, permata',
 'coc_s': 'Akaun Town Hall yang dimaksimumkan',
 'coc_tr': 'Nama dalam permainan yang jarang; Town Hall 18 dimaksimumkan',
 'cr_c': 'Akaun pengumpul yang dimaksimumkan: semua evolusi dan wira',
 'cr_g': 'Evolusi kad, kad maksimum, champion',
 'cr_jp': 'Tahap akaun, kad legendary, permata, lencana cabaran 20 kemenangan',
 'cr_s': 'Akaun "sedia e-sukan": semua evolusi, kad maksimum',
 'cr_tr': 'Akaun yang dimaksimumkan sepenuhnya, champion, evolusi, permata',
 'ff_c': 'Akaun pengumpul tahap tinggi dengan rank Heroic',
 'ff_g': 'Bundle jarang, berlian, sejarah Elite Pass',
 'ff_s': 'Akaun OG: Elite Pass awal, 1,500 item fesyen',
 'ff_tr': 'Tahap Prime 8, senjata EVO',
 'fn_c': 'Akaun era 2018 dengan 800+ skin',
 'fn_g': 'Skin OG Chapter 1 (Renegade Raider, Black Knight)',
 'fn_s': '700+ skin termasuk Renegade Raider dan kolaborasi',
 'fn_tr': 'Akaun OG dan bilangan skin',
 'gi_c': 'Iklan teratas dijual bersama Honkai: Star Rail',
 'gi_cn': 'Binaan permulaan dengan watak popular (Nahida, Neuvillette); "jaminan pemulihan seumur hidup"',
 'gi_cn2': 'Dari akaun permulaan hingga koleksi 100+ watak lima bintang; "pengesahan rasmi", jaminan seumur hidup',
 'gi_g': 'Watak 5★, constellation (C6), refinement senjata',
 'gi_jp': 'Akaun permulaan reroll dengan 48,000+ Primogem; teratas: beberapa watak C6',
 'gi_kr': 'Watak dan senjata lima bintang dengan constellation penuh (C6)',
 'gi_s': 'AR59 dengan beberapa watak 5★',
 'gi_tr': 'Bilangan watak lima bintang (teratas: 118), AR60',
 'mc_c': 'Kebanyakannya rank pelayan persendirian, bukan akaun rasmi',
 'mc_g': 'Jenis akaun (Java), cape jarang, nama pendek',
 'mc_s': 'Bilangan dan kejarangan cape',
 'ml_g': 'Rank, bilangan wira dan skin (skin Collector / Legend)',
 'ml_s': 'Rank Immortal, 130 wira, 552 skin',
 'ml_tr': 'Bilangan skin dan mata koleksi (teratas: 807 skin)',
 'rbx_c': 'Kebanyakannya akaun berharga rendah; iklan tertinggi €117',
 'rbx_g': 'Item Limited (Headless, Korblox), Robux, umur akaun',
 'rbx_s': 'Akaun yang berkaitan dengan experience tertentu (tertinggi ≈ $803)',
 'rbx_tr': 'Headless dan Korblox'}
TW_ONLY['ms'] = 'Twitch sahaja — di banyak negara permainan ini kebanyakannya distrim di platform lain.'
