"""Second research round (2026-09-28): Japan (GameTrade), China (交易猫),
Korea (저팔계), Türkiye (GameSatış) rows for the other games. Placeholder
prices (¥999,999 etc.) excluded. Rates: 157.2 JPY, 6.71 CNY, 1,370 KRW,
48.8 TRY per USD."""

GT = 'https://gametrade.jp/'
GS = 'https://www.gamesatis.com/'
ROWS = {
 'genshin-impact': {
   'jp': dict(where=[('GameTrade', GT + 'genshin-impact/exhibits')], local='¥3,000 – ¥2,500,000', usd='$19 – $15,903', demand='gi_jp'),
   'cn': dict(where=[('悠悠游戏 UU898', 'https://www.uu898.com/newTrade-1586/'), ('交易猫 Jiaoyimao', 'https://m.jiaoyimao.com/jg1009609/f299442-c299444/o110/')], local='¥105.60 – ¥7,500', usd='$16 – $1,118', demand='gi_cn2'),
   'kr': dict(where=[('저팔계 Jeo8gye', 'https://www.jeo8gye.com/trade/list?game_code=89')], local='₩50,000 – ₩2,500,000', usd='$36 – $1,825', demand='gi_kr'),
   'tr': dict(where=[('GameSatış', GS + 'genshin-impact-hesap-satisi')], local='500 ₺ – 25,000 ₺', usd='$10 – $512', demand='gi_tr')},
 'clash-royale': {
   'jp': dict(where=[('GameTrade', GT + 'clashroyale/exhibits')], local='¥2,500 – ¥180,000', usd='$16 – $1,145', demand='cr_jp'),
   'tr': dict(where=[('GameSatış', GS + 'clash-royale-hesap-satisi')], local='100 ₺ – 29,999 ₺', usd='$2 – $615', demand='cr_tr')},
 'clash-of-clans': {
   'jp': dict(where=[('GameTrade', GT + 'clash-of-clans/exhibits')], local='¥1,280 – ¥248,000', usd='$8 – $1,578', demand='coc_jp'),
   'cn': dict(where=[('交易猫 Jiaoyimao', 'https://m.jiaoyimao.com/jg1002582-4/c4/')], local='¥210 – ¥12,888', usd='$31 – $1,921', demand='coc_cn'),
   'tr': dict(where=[('GameSatış', GS + 'clash-of-clans-hesap-satisi')], local='100 ₺ – 19,000 ₺', usd='$2 – $389', demand='coc_tr')},
 'fortnite': {'tr': dict(where=[('GameSatış', GS + 'fortnite-hesap-satisi')], local='400 ₺ – 11,000 ₺', usd='$8 – $225', demand='fn_tr')},
 'roblox': {'tr': dict(where=[('GameSatış', GS + 'roblox-hesap-satisi')], local='50 ₺ – 18,000 ₺', usd='$1 – $369', demand='rbx_tr')},
 'free-fire': {'tr': dict(where=[('GameSatış', GS + 'free-fire-hesap-satisi')], local='450 ₺ – 15,000 ₺', usd='$9 – $307', demand='ff_tr')},
 'mobile-legends': {'tr': dict(where=[('GameSatış', GS + 'mobile-legends-hesap-satisi')], local='250 ₺ – 50,000 ₺', usd='$5 – $1,025', demand='ml_tr')},
}

N2 = {
 'en': dict(gi_jp='Reroll starter accounts with 48,000+ Primogems; top: several C6 characters', cr_jp='Account level, legendary cards, gems, 20-win challenge badges', coc_jp='Town Hall 18, maxed heroes, gems',
   gi_cn2='From starter accounts to 100+ five-star collections; "official verification", lifetime guarantee', coc_cn='Town Hall 18 with maxed heroes, defenses and equipment', gi_kr='Fully-constellated (C6) five-star characters and weapons',
   fn_tr='OG accounts and skin count', coc_tr='Rare in-game names; maxed Town Hall 18', cr_tr='Fully maxed accounts, champions, evolutions, gems', rbx_tr='Headless and Korblox',
   gi_tr='Number of five-star characters (top: 118), AR60', ff_tr='Prime level 8, EVO weapons', ml_tr='Skin count and collection points (top: 807 skins)'),
 'ru': dict(gi_jp='Стартовые аккаунты с 48 000+ примогемов; в топе — несколько персонажей C6', cr_jp='Уровень аккаунта, легендарные карты, кристаллы, бейджи за 20 побед', coc_jp='Ратуша 18, прокачанные герои, кристаллы',
   gi_cn2='От стартовых аккаунтов до коллекций из 100+ пятизвёздочных; «официальная проверка», пожизненная гарантия', coc_cn='Ратуша 18 с максимальными героями, защитой и снаряжением', gi_kr='Пятизвёздочные персонажи и оружие с полными созвездиями (C6)',
   fn_tr='OG-аккаунты и число скинов', coc_tr='Редкие игровые ники; максимальная ратуша 18', cr_tr='Полностью прокачанные аккаунты, чемпионы, эволюции, кристаллы', rbx_tr='Headless и Korblox',
   gi_tr='Число пятизвёздочных персонажей (максимум — 118), AR60', ff_tr='Уровень Prime 8, EVO-оружие', ml_tr='Число скинов и очки коллекции (максимум — 807 скинов)'),
 'es': dict(gi_jp='Cuentas iniciales con 48.000+ Protogemas; arriba: varios personajes C6', cr_jp='Nivel de cuenta, cartas legendarias, gemas, insignias de 20 victorias', coc_jp='Ayuntamiento 18, héroes al máximo, gemas',
   gi_cn2='De cuentas iniciales a colecciones de 100+ personajes 5★; «verificación oficial», garantía de por vida', coc_cn='Ayuntamiento 18 con héroes, defensas y equipo al máximo', gi_kr='Personajes 5★ y armas con constelaciones completas (C6)',
   fn_tr='Cuentas OG y número de skins', coc_tr='Nombres de jugador raros; Ayuntamiento 18 al máximo', cr_tr='Cuentas al máximo, campeones, evoluciones, gemas', rbx_tr='Headless y Korblox',
   gi_tr='Número de personajes 5★ (máx.: 118), AR60', ff_tr='Nivel Prime 8, armas EVO', ml_tr='Número de skins y puntos de colección (máx.: 807 skins)'),
 'pt': dict(gi_jp='Contas iniciais com 48.000+ Gemas Essenciais; no topo: vários personagens C6', cr_jp='Nível da conta, cartas lendárias, gemas, insígnias de 20 vitórias', coc_jp='CV 18, heróis no máximo, gemas',
   gi_cn2='De contas iniciais a coleções com 100+ personagens 5★; "verificação oficial", garantia vitalícia', coc_cn='CV 18 com heróis, defesas e equipamentos no máximo', gi_kr='Personagens 5★ e armas com constelações completas (C6)',
   fn_tr='Contas OG e número de skins', coc_tr='Nomes raros no jogo; CV 18 no máximo', cr_tr='Contas no máximo, campeões, evoluções, gemas', rbx_tr='Headless e Korblox',
   gi_tr='Número de personagens 5★ (máx.: 118), AR60', ff_tr='Nível Prime 8, armas EVO', ml_tr='Número de skins e pontos de coleção (máx.: 807 skins)'),
 'id': dict(gi_jp='Akun awal dengan 48.000+ Primogem; teratas: beberapa karakter C6', cr_jp='Level akun, kartu legendaris, gem, lencana tantangan 20 menang', coc_jp='Balai Kota 18, hero maksimal, gem',
   gi_cn2='Dari akun awal hingga koleksi 100+ karakter 5★; "verifikasi resmi", jaminan seumur hidup', coc_cn='Balai Kota 18 dengan hero, pertahanan, dan equipment maksimal', gi_kr='Karakter 5★ dan senjata dengan konstelasi penuh (C6)',
   fn_tr='Akun OG dan jumlah skin', coc_tr='Nama dalam game yang langka; Balai Kota 18 maksimal', cr_tr='Akun maksimal, champion, evolusi, gem', rbx_tr='Headless dan Korblox',
   gi_tr='Jumlah karakter 5★ (tertinggi: 118), AR60', ff_tr='Level Prime 8, senjata EVO', ml_tr='Jumlah skin dan poin koleksi (tertinggi: 807 skin)'),
 'tr': dict(gi_jp='48.000+ Primogem\'li başlangıç hesapları; en üstte: birkaç C6 karakter', cr_jp='Hesap seviyesi, efsanevi kartlar, taşlar, 20 galibiyet rozetleri', coc_jp='Belediye Binası 18, maksimum kahramanlar, taşlar',
   gi_cn2='Başlangıç hesaplarından 100+ beş yıldızlı koleksiyonlara; "resmi doğrulama", ömür boyu garanti', coc_cn='Kahramanları, savunmaları ve ekipmanı maksimum Belediye Binası 18', gi_kr='Tam takımyıldızlı (C6) beş yıldızlı karakterler ve silahlar',
   fn_tr='OG hesaplar ve kostüm sayısı', coc_tr='Nadir oyun içi isimler; maksimum Belediye Binası 18', cr_tr='Tamamen maksimum hesaplar, şampiyonlar, evrimler, taşlar', rbx_tr='Headless ve Korblox',
   gi_tr='Beş yıldızlı karakter sayısı (en fazla: 118), AR60', ff_tr='Prime seviye 8, EVO silahlar', ml_tr='Kostüm sayısı ve koleksiyon puanı (en fazla: 807 kostüm)'),
 'ar': dict(gi_jp='حسابات مبتدئة بأكثر من 48,000 Primogem؛ الأعلى: عدة شخصيات C6', cr_jp='مستوى الحساب والبطاقات الأسطورية والجواهر وشارات تحدي 20 فوزاً', coc_jp='قاعة البلدة 18 وأبطال مطوّرون بالكامل وجواهر',
   gi_cn2='من الحسابات المبتدئة إلى مجموعات تضم أكثر من 100 شخصية 5★؛ "تحقق رسمي" وضمان مدى الحياة', coc_cn='قاعة البلدة 18 مع أبطال ودفاعات ومعدات مطوّرة بالكامل', gi_kr='شخصيات 5★ وأسلحة بأبراج كاملة (C6)',
   fn_tr='حسابات OG وعدد السكنات', coc_tr='أسماء نادرة داخل اللعبة؛ قاعة البلدة 18 كاملة', cr_tr='حسابات مطوّرة بالكامل وأبطال وتطورات وجواهر', rbx_tr='Headless وKorblox',
   gi_tr='عدد شخصيات 5★ (الأعلى: 118)، AR60', ff_tr='مستوى Prime 8 وأسلحة EVO', ml_tr='عدد السكنات ونقاط المجموعة (الأعلى: 807 سكن)'),
 'vi': dict(gi_jp='Tài khoản khởi đầu có 48.000+ Nguyên Thạch; đắt nhất: nhiều nhân vật C6', cr_jp='Cấp tài khoản, thẻ huyền thoại, đá quý, huy hiệu thử thách 20 trận thắng', coc_jp='Nhà chính 18, anh hùng full cấp, đá quý',
   gi_cn2='Từ tài khoản khởi đầu đến bộ sưu tập 100+ nhân vật 5★; "xác minh chính thức", bảo hành trọn đời', coc_cn='Nhà chính 18 với anh hùng, phòng thủ và trang bị full', gi_kr='Nhân vật 5★ và vũ khí full cung mệnh (C6)',
   fn_tr='Tài khoản OG và số skin', coc_tr='Tên trong game hiếm; Nhà chính 18 full', cr_tr='Tài khoản full, champion, tiến hóa, đá quý', rbx_tr='Headless và Korblox',
   gi_tr='Số nhân vật 5★ (cao nhất: 118), AR60', ff_tr='Cấp Prime 8, vũ khí EVO', ml_tr='Số skin và điểm sưu tập (cao nhất: 807 skin)'),
 'hi': dict(gi_jp='48,000+ Primogem वाले शुरुआती अकाउंट; सबसे ऊपर: कई C6 किरदार', cr_jp='अकाउंट लेवल, लीजेंडरी कार्ड, जेम, 20-जीत चैलेंज बैज', coc_jp='टाउन हॉल 18, मैक्स हीरो, जेम',
   gi_cn2='शुरुआती अकाउंट से लेकर 100+ फ़ाइव-स्टार संग्रह तक; "आधिकारिक सत्यापन", आजीवन गारंटी', coc_cn='मैक्स हीरो, डिफ़ेंस और इक्विपमेंट वाला टाउन हॉल 18', gi_kr='पूरे कॉन्स्टेलेशन (C6) वाले फ़ाइव-स्टार किरदार और हथियार',
   fn_tr='OG अकाउंट और स्किन की संख्या', coc_tr='दुर्लभ इन-गेम नाम; मैक्स टाउन हॉल 18', cr_tr='पूरी तरह मैक्स अकाउंट, चैंपियन, इवोल्यूशन, जेम', rbx_tr='Headless और Korblox',
   gi_tr='फ़ाइव-स्टार किरदारों की संख्या (सबसे ज़्यादा: 118), AR60', ff_tr='Prime लेवल 8, EVO हथियार', ml_tr='स्किन की संख्या और कलेक्शन पॉइंट (सबसे ज़्यादा: 807 स्किन)'),
 'fr': dict(gi_jp='Comptes de départ avec 48 000+ Primogemmes ; en haut : plusieurs personnages C6', cr_jp='Niveau du compte, cartes légendaires, gemmes, badges de défi à 20 victoires', coc_jp='Hôtel de ville 18, héros au max, gemmes',
   gi_cn2='Des comptes de départ aux collections de 100+ personnages 5★ ; « vérification officielle », garantie à vie', coc_cn='Hôtel de ville 18 avec héros, défenses et équipements au max', gi_kr='Personnages 5★ et armes aux constellations complètes (C6)',
   fn_tr='Comptes OG et nombre de skins', coc_tr='Pseudos rares ; hôtel de ville 18 au max', cr_tr='Comptes au max, champions, évolutions, gemmes', rbx_tr='Headless et Korblox',
   gi_tr='Nombre de personnages 5★ (max. : 118), AR60', ff_tr='Niveau Prime 8, armes EVO', ml_tr='Nombre de skins et points de collection (max. : 807 skins)'),
 'de': dict(gi_jp='Starterkonten mit 48.000+ Urgesteinen; ganz oben: mehrere C6-Charaktere', cr_jp='Kontostufe, legendäre Karten, Juwelen, Abzeichen für 20 Siege', coc_jp='Rathaus 18, maximierte Helden, Juwelen',
   gi_cn2='Von Starterkonten bis zu Sammlungen mit 100+ 5★-Charakteren; „offizielle Verifizierung“, lebenslange Garantie', coc_cn='Rathaus 18 mit maximierten Helden, Verteidigung und Ausrüstung', gi_kr='5★-Charaktere und Waffen mit vollen Konstellationen (C6)',
   fn_tr='OG-Konten und Anzahl der Skins', coc_tr='Seltene Spielernamen; maximiertes Rathaus 18', cr_tr='Voll ausgebaute Konten, Champions, Evolutionen, Juwelen', rbx_tr='Headless und Korblox',
   gi_tr='Anzahl der 5★-Charaktere (max.: 118), AR60', ff_tr='Prime-Stufe 8, EVO-Waffen', ml_tr='Anzahl der Skins und Sammelpunkte (max.: 807 Skins)'),
 'it': dict(gi_jp='Account iniziali con 48.000+ Protogemme; in cima: diversi personaggi C6', cr_jp='Livello account, carte leggendarie, gemme, badge della sfida da 20 vittorie', coc_jp='Municipio 18, eroi al massimo, gemme',
   gi_cn2='Da account iniziali a collezioni con 100+ personaggi 5★; "verifica ufficiale", garanzia a vita', coc_cn='Municipio 18 con eroi, difese ed equipaggiamento al massimo', gi_kr='Personaggi 5★ e armi con costellazioni complete (C6)',
   fn_tr='Account OG e numero di skin', coc_tr='Nomi di gioco rari; Municipio 18 al massimo', cr_tr='Account al massimo, campioni, evoluzioni, gemme', rbx_tr='Headless e Korblox',
   gi_tr='Numero di personaggi 5★ (massimo: 118), AR60', ff_tr='Livello Prime 8, armi EVO', ml_tr='Numero di skin e punti collezione (massimo: 807 skin)'),
 'ja': dict(gi_jp='原石48,000以上のリセマラ初期垢。最高額は完凸キャラ複数', cr_jp='アカウントレベル、URカード、エメラルド、20勝チャレンジのバッジ', coc_jp='TH18、ヒーローカンスト、エメラルド',
   gi_cn2='初期垢から星5が100体以上のコレクションまで。「公式認証」「永久補償」付き', coc_cn='ヒーロー・防衛・装備カンストのTH18', gi_kr='完凸（C6）の星5キャラと武器',
   fn_tr='OGアカウントとスキン数', coc_tr='レアなゲーム内の名前、カンストのTH18', cr_tr='カンストアカウント、チャンピオン、進化、エメラルド', rbx_tr='HeadlessとKorblox',
   gi_tr='星5キャラの数（最多118）、冒険ランク60', ff_tr='Primeレベル8、EVO武器', ml_tr='スキン数とコレクションポイント（最多807スキン）'),
 'ko': dict(gi_jp='원석 48,000개 이상의 리세 시작 계정; 최고가는 풀돌 캐릭터 여럿', cr_jp='계정 레벨, 전설 카드, 보석, 20승 챌린지 배지', coc_jp='마을회관 18, 영웅 만렙, 보석',
   gi_cn2='시작 계정부터 5성 100개 이상 컬렉션까지; "공식 인증", 평생 보상', coc_cn='영웅·방어·장비 만렙 마을회관 18', gi_kr='풀돌(C6) 5성 캐릭터와 무기',
   fn_tr='OG 계정과 스킨 수', coc_tr='희귀 닉네임; 만렙 마을회관 18', cr_tr='풀강 계정, 챔피언, 진화, 보석', rbx_tr='Headless와 Korblox',
   gi_tr='5성 캐릭터 수(최다 118), 모험 등급 60', ff_tr='Prime 레벨 8, EVO 무기', ml_tr='스킨 수와 컬렉션 포인트(최다 807 스킨)'),
 'th': dict(gi_jp='บัญชีเริ่มต้นที่มี Primogem 48,000+ ; แพงสุด: ตัวละคร C6 หลายตัว', cr_jp='เลเวลบัญชี การ์ดตำนาน อัญมณี เหรียญตราชาเลนจ์ชนะ 20 ครั้ง', coc_jp='ศาลากลาง 18 ฮีโร่ตัน อัญมณี',
   gi_cn2='ตั้งแต่บัญชีเริ่มต้นจนถึงคอลเลกชันตัวละคร 5★ กว่า 100 ตัว; "ตรวจสอบทางการ" รับประกันตลอดชีพ', coc_cn='ศาลากลาง 18 ฮีโร่ ป้อมป้องกัน และอุปกรณ์ตัน', gi_kr='ตัวละครและอาวุธ 5★ กลุ่มดาวเต็ม (C6)',
   fn_tr='บัญชี OG และจำนวนสกิน', coc_tr='ชื่อในเกมที่หายาก; ศาลากลาง 18 ตัน', cr_tr='บัญชีตันทุกอย่าง แชมเปี้ยน วิวัฒนาการ อัญมณี', rbx_tr='Headless และ Korblox',
   gi_tr='จำนวนตัวละคร 5★ (สูงสุด 118) AR60', ff_tr='Prime เลเวล 8 อาวุธ EVO', ml_tr='จำนวนสกินและแต้มคอลเลกชัน (สูงสุด 807 สกิน)'),
 'pl': dict(gi_jp='Konta startowe z 48 000+ Prakamieni; na szczycie: kilka postaci C6', cr_jp='Poziom konta, karty legendarne, klejnoty, odznaki za wyzwanie 20 zwycięstw', coc_jp='Ratusz 18, wymaksowani bohaterowie, klejnoty',
   gi_cn2='Od kont startowych po kolekcje ze 100+ postaciami 5★; „oficjalna weryfikacja”, dożywotnia gwarancja', coc_cn='Ratusz 18 z wymaksowanymi bohaterami, obroną i ekwipunkiem', gi_kr='Postacie 5★ i bronie z pełnymi konstelacjami (C6)',
   fn_tr='Konta OG i liczba skórek', coc_tr='Rzadkie nazwy w grze; wymaksowany ratusz 18', cr_tr='W pełni wymaksowane konta, czempioni, ewolucje, klejnoty', rbx_tr='Headless i Korblox',
   gi_tr='Liczba postaci 5★ (najwięcej: 118), AR60', ff_tr='Poziom Prime 8, bronie EVO', ml_tr='Liczba skórek i punkty kolekcji (najwięcej: 807 skórek)'),
 'zh': dict(gi_jp='原石48,000以上的初始号；最高价为多个满命角色', cr_jp='账号等级、传奇卡牌、宝石、20胜挑战徽章', coc_jp='18本、满级英雄、宝石',
   gi_cn2='从初始号到100+五星收藏号；"官方验号"、永久包赔', coc_cn='满王满防满装备的18本', gi_kr='满命（C6）五星角色与武器',
   fn_tr='OG账号与皮肤数量', coc_tr='稀有游戏ID；满级18本', cr_tr='全满账号、英雄卡、进化、宝石', rbx_tr='Headless与Korblox',
   gi_tr='五星角色数量（最多118个）、冒险等级60', ff_tr='Prime等级8、EVO武器', ml_tr='皮肤数量与收藏积分（最多807款皮肤）'),
}
